### ISSUE TITLE
Wine tools for cross-compiling

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#10008]
### System

* xuname:  Void 4.14.6-chrysalis x86_64 GenuineIntel uptodate rFFF
* package:  wine-32bit

### Expected behavior

Being able to compile wine on a 64 bit host.

### Actual behavior

Compilation fails with error `checking for the directory containing the Wine tools... configure: error: you must use the --with-wine-tools option when cross-compiling`

And if I add this line to the template,
```
checking for the directory containing the Wine tools... configure: error: could not find Wine tools in yes
=> ERROR: wine-2.21_1: failed to run do_configure() at line 7.
```

### Steps to reproduce the behavior
1. clone the void-packages
2. run `./xbps-src -a i686 pkg wine-32bit` on a x86_64

**Comment by cr6git** [comment]
Probably related to [#8256](https://github.com/voidlinux/void-packages/pull/8256) ?

**Comment by Duncaen** [comment]
We don't cross compile i686 packages.
You can simply create a i686 masterdir on your x84_64 host and natively built it.
```
./xbps-src -m masterdir-i686 binary-bootstrap i686
./xbps-src -m masterdir-i686 pkg wine
```

**Comment by Vintodrimmer** [comment]
Thank you.
