### ISSUE TITLE
[broken] gutenprint 5.2.13 build incorrect

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#10025]
### System

* xuname:  
  Void 4.13.15_1 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  
  gutenprint 5.2.13

### Behavior
On newst gutenprint I receive the following error on my printer:
```
The PPD version (5.2.12) is not compatible with Gutenprint 5.2.13. 
Please run `/usr/sbin/cups-genppdupdate' as administrator.`
```

I am trying to update using: `cups-genppdupdate`
```
bash: /usr/bin/cups-genppdupdate: -w: Defect Interpreter: File or directory not  found
```

Upon viewing the file I saw the following issue in line 1:
```
#!  -w
# Update CUPS PPDs for Gutenprint queues.
# Copyright (C) 2002-2003 Roger Leigh (rleigh@debian.org)
#
```

I am guessing we have some packaging issues here. 

Edit:
So it seems like on gutenprint `5.2.13` there is a new utility required to convert between `5.2.12` and `5.2.13`. 

https://sourceforge.net/projects/gimp-print/files/gutenprint-5.2/5.2.13/ 
```
 * A utility to update PPD files from an earlier release of Gutenprint, cups-genppdupdate. 
This utility may be used to update PPD files generated by earlier versions of Gutenprint starting 
from 4.3.21, including any 5.0, 5.1, or 5.2 release or pre-release. 
This is normally installed in /usr/sbin. This utility cannot update PPD files from Gimp-Print 4.2.
```

@maxice8 please don't bump packages if you have no chance to test them before. I've broken drivers now and I cannot print anymore until I found a fix.

**Comment by Anachron** [comment]
So it seems like `cups-genppdupdate` is a `perl` script.

I've checked it by inspecting the arch pkg.
https://www.archlinux.org/packages/extra/x86_64/gutenprint/download/

**Comment by cr6git** [comment]
To be fair @maxice8 is not the only one who was tricked, someone else had done the same in his own [commit](https://github.com/voidlinux/void-packages/pull/8390/commits/4f4baa67c4acbbb6de0b3da8e6bfd6c2a9528ba3) a few hours later.
