### ISSUE TITLE
ruby-2.4.3 build segfaulting for *-musl on the builders

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10044]
As [you can see here](https://build.voidlinux.eu/builders/x86_64-musl_builder/builds/6630/steps/shell_3/logs/stdio) building ruby-2.4.3 segfauls on the *-musl builders.
It does however [build just fine locally](http://repo.voidlinux.de/current/) with all dependencies compiled with gcc-7.2.0.

I first thought it was related to /etc/localtime, but that doesn't seem to be the case.

Since I can't reproduce the segfault here, what do you think about revbumping the dependencies (zlib, readline, libffi, libressl, gdbm, libyaml, pango) for a try, in case they were not yet built with gcc-7.2.0?
Or perhaps only those which are built using g++.

**Comment by chneukirchen** [comment]
Hm, it also builds fine in my local hostdir, which doesn't have more recent packages afaiu.

**Comment by pullmoll** [comment]
Ok. A broken ruby for *-musl will leave a trail of wrecks in the repo, so what can we do?
I see two options: import ruby*-musl.xbps from elsewhere or debug the segfault on the builder(s).

**Comment by chneukirchen** [comment]
However, it also crashes on all other musl builders in that line calling Time.locale. Investigating.

**Comment by pullmoll** [comment]
Perhaps a diff between 2.4.2 and 2.4.3 can tell the critical change.

**Comment by chneukirchen** [comment]
Apparently it also worked on aarch64-musl? The diff is quite small, nothing time related afaics.

**Comment by chneukirchen** [comment]
Perhaps we can just disable the docs on musl as a stopgap.

**Comment by pullmoll** [comment]
https://github.com/voidlinux/void-packages/commit/c087c2bd93c445944485731ad4dabcda0261ac05

**Comment by pullmoll** [comment]
Regarding aarch64-musl: yes, so it is probably one of the host dependencies causing the trouble. The aarch64-musl builder doesn't use the x86_64 repository.
