### ISSUE TITLE
go: needs host build on aarch64*

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10064]
I updated go to not use nopie=yes, because that fails with gcc7.
Now we have the aarch64* builders failing to build go, probably because of a missing host go.
Sorry @chneukirchen :-/

**Comment by chneukirchen** [comment]
Done.

**Comment by pullmoll** [comment]
Not quite. The `aarch64-musl` builder still tries to build `go` with `x86_64-linux-gnu-g++` yet `CFLAGS` for aarch64.

**Comment by chneukirchen** [comment]
I just ran `void-packages/xbps-src -m chroot -H /hostdir -t pkg go`:
index: added `go-1.9.2_2' (x86_64-musl).

**Comment by chneukirchen** [comment]
index: skipping `go-1.9.2_2' (aarch64-musl), already registered.

**Comment by chneukirchen** [comment]
fixed now.
