### ISSUE TITLE
Package request: OpenOrienteering Mapper

### ISSUE THREAD

**Issue by Symbian9** [voidlinux/void-packages#10062]
*OpenOrienteering Mapper* is a software for creating maps for the orienteering sport.

- https://github.com/openorienteering/mapper
  - https://github.com/openorienteering/superbuild
    - http://download.opensuse.org/repositories/home:/dg0yt/

**Comment by pullmoll** [comment]
I think it's best to wait for 0.8.0 as the latest two releases are *previews* in beta state?

**Comment by Symbian9** [comment]
> I think it's best to wait for 0.8.0

`v0.8.0` is upcoming stable release, but for testing I need nightly builds from `master`.

For example, look inside this directory:
- http://download.opensuse.org/repositories/home:/dg0yt/Arch_Community/x86_64/

**Comment by pullmoll** [comment]
We package unstable or testing releases only in exceptional cases.
I think you'll have to roll your own template to try to follow nightly builds. We don't have the resources for such a thing.

**Comment by Symbian9** [comment]
I mean, need help in adopting existing build ecosystem for Void
- https://github.com/openorienteering/superbuild

**Comment by Johnnynator** [comment]
For packaging superbuild is not needed and will not be used.
Troubles with superbuild are pboably best sorted out upstream and not here. 

I quickly have done a template for OpenOrienteering Mapper and clipper (dep) and will make a PR when 0.8.0 is released.
https://github.com/Johnnynator/void-packages/commits/oomapper

**Comment by Symbian9** [comment]
I create issue on OpenOrienteering Mapper tracker and would be happy to help with it (if I can do something with it).

**Comment by Symbian9** [comment]
> I quickly have done a template for OpenOrienteering Mapper

Greate! ;-)

Just for the record, recommend use `openorienteering-mapper` as folder name inside `srcpkgs`

- https://github.com/voidlinux/void-packages/tree/master/srcpkgs/openorienteering-mapper

**Comment by Symbian9** [comment]
> I think it's best to wait for 0.8.0

OpenOrienteering Mapper v0.8.0 released!

- https://github.com/openorienteering/mapper/releases/tag/v0.8.0

**Comment by Johnnynator** [comment]
https://github.com/voidlinux/void-packages/pull/11591

**Comment by maxice8** [comment]
@lemmi it is solved
