### ISSUE TITLE
remove package 'compute'

### ISSUE THREAD

**Issue by oliver-cfc** [voidlinux/void-packages#10091]
I'm not sure if this should be done as a PR so wanted to ask here first.

compute (in the repo) has been superceded by datamash (also now in the repo) so there's no real point in keeping compute around any more

From https://github.com/agordon/compute :
Compute is now GNU Datamash !
compute (now GNU Datamash is a command-line program to perform textual,numerical,statistical operation on text files.

**Comment by Vaelatern** [comment]
This has to be done with datamash knowing it's to be installed instead of `compute`. There is a workflow for this, but I don't know it off the  top of my head.

**Comment by ebfe** [comment]
Could use replaces= but i don't think it makes much sense if the binary name changed.
