### ISSUE TITLE
Flameshot packaging changes

### ISSUE THREAD

**Issue by lupoDharkael** [voidlinux/void-packages#10147]
I'm the developer of Flameshot (https://github.com/voidlinux/void-packages/tree/master/srcpkgs/flameshot). 
Just letting you know I've implemented automatic translation generation in builds in the version 0.5.0, so the build needs a new dependency. `lrelease` needs to be installed, I don't know how you name your packages in this distro but here are some of its names in other distros, hope that helps:  `qttools5-dev-tools`, `qt5-linguist`, `qt5-tools`.

It's interesting to point that multiple .qm files will be generated after the qmake execution. "make install" should install everything properly but you have to pass the "packaging" variable and set the BASEDIR if you need to install in a custom directory.

Check it here for more info: https://github.com/lupoDharkael/flameshot#packaging

**Comment by cr6git** [comment]
Hi @lupoDharkael 

In Void linux `lrelease` is part of `qt5-host-tools` (already pulled by `qt5-devel` in the template).

You can close this issue.
