### ISSUE TITLE
glibc-devel on x86_64 uses TSX instructions

### ISSUE THREAD

**Issue by strake** [voidlinux/void-packages#1017]
XEND in particular, which is illegal on many machines, including mine.

I tried configuring with --disable-lock-elision and building with -march=x86-64, in vain.

$ objdump -d /lib/libpthread.a

    pthread_rwlock_unlock.o:     file format elf64-x86-64
    
    
    Disassembly of section .text:
    
    0000000000000000 <__pthread_rwlock_unlock>:
       0:	49 89 f8             	mov    %rdi,%r8
       3:	8b 7f 18             	mov    0x18(%rdi),%edi
       6:	85 ff                	test   %edi,%edi
       8:	75 16                	jne    20 <__pthread_rwlock_unlock+0x20>
       a:	41 8b 70 04          	mov    0x4(%r8),%esi
       e:	85 f6                	test   %esi,%esi
      10:	75 0e                	jne    20 <__pthread_rwlock_unlock+0x20>
      12:	0f 01 d5             	xend   
      15:	31 c0                	xor    %eax,%eax
      17:	c3                   	retq   
      18:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
      1f:	00 
      20:	bf 01 00 00 00       	mov    $0x1,%edi
      25:	31 c0                	xor    %eax,%eax
      27:	41 8b 70 1c          	mov    0x1c(%r8),%esi
      2b:	f0 41 0f b1 38       	lock cmpxchg %edi,(%r8)
      30:	74 16                	je     48 <__pthread_rwlock_unlock+0x48>
      32:	49 8d 38             	lea    (%r8),%rdi
      35:	48 81 ec 80 00 00 00 	sub    $0x80,%rsp
      3c:	e8 00 00 00 00       	callq  41 <__pthread_rwlock_unlock+0x41>
      41:	48 81 c4 80 00 00 00 	add    $0x80,%rsp
      48:	41 8b 40 18          	mov    0x18(%r8),%eax
      4c:	85 c0                	test   %eax,%eax
      4e:	75 70                	jne    c0 <__pthread_rwlock_unlock+0xc0>
      50:	41 8b 40 04          	mov    0x4(%r8),%eax
      54:	83 e8 01             	sub    $0x1,%eax
      57:	85 c0                	test   %eax,%eax
      59:	41 89 40 04          	mov    %eax,0x4(%r8)
      5d:	75 71                	jne    d0 <__pthread_rwlock_unlock+0xd0>
      5f:	41 8b 48 14          	mov    0x14(%r8),%ecx
      63:	85 c9                	test   %ecx,%ecx
      65:	0f 85 8d 00 00 00    	jne    f8 <__pthread_rwlock_unlock+0xf8>
      6b:	41 8b 50 10          	mov    0x10(%r8),%edx
      6f:	85 d2                	test   %edx,%edx
      71:	74 5d                	je     d0 <__pthread_rwlock_unlock+0xd0>
      73:	41 83 40 08 01       	addl   $0x1,0x8(%r8)
      78:	41 8b 70 1c          	mov    0x1c(%r8),%esi
      7c:	f0 41 ff 08          	lock decl (%r8)
      80:	74 16                	je     98 <__pthread_rwlock_unlock+0x98>
      82:	49 8d 38             	lea    (%r8),%rdi
      85:	48 81 ec 80 00 00 00 	sub    $0x80,%rsp
      8c:	e8 00 00 00 00       	callq  91 <__pthread_rwlock_unlock+0x91>
      91:	48 81 c4 80 00 00 00 	add    $0x80,%rsp
      98:	41 8b 70 1c          	mov    0x1c(%r8),%esi
      9c:	45 31 d2             	xor    %r10d,%r10d
      9f:	ba ff ff ff 7f       	mov    $0x7fffffff,%edx
      a4:	49 8d 78 08          	lea    0x8(%r8),%rdi
      a8:	b8 ca 00 00 00       	mov    $0xca,%eax
      ad:	40 80 f6 81          	xor    $0x81,%sil
      b1:	48 63 f6             	movslq %esi,%rsi
      b4:	0f 05                	syscall 
      b6:	e9 5a ff ff ff       	jmpq   15 <__pthread_rwlock_unlock+0x15>
      bb:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)
      c0:	41 8b 40 04          	mov    0x4(%r8),%eax
      c4:	41 c7 40 18 00 00 00 	movl   $0x0,0x18(%r8)
      cb:	00 
      cc:	85 c0                	test   %eax,%eax
      ce:	74 8f                	je     5f <__pthread_rwlock_unlock+0x5f>
      d0:	41 8b 70 1c          	mov    0x1c(%r8),%esi
      d4:	f0 41 ff 08          	lock decl (%r8)
      d8:	74 16                	je     f0 <__pthread_rwlock_unlock+0xf0>
      da:	49 8d 38             	lea    (%r8),%rdi
      dd:	48 81 ec 80 00 00 00 	sub    $0x80,%rsp
      e4:	e8 00 00 00 00       	callq  e9 <__pthread_rwlock_unlock+0xe9>
      e9:	48 81 c4 80 00 00 00 	add    $0x80,%rsp
      f0:	31 c0                	xor    %eax,%eax
      f2:	c3                   	retq   
      f3:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)
      f8:	41 83 40 0c 01       	addl   $0x1,0xc(%r8)
      fd:	41 8b 70 1c          	mov    0x1c(%r8),%esi
     101:	f0 41 ff 08          	lock decl (%r8)
     105:	74 16                	je     11d <__pthread_rwlock_unlock+0x11d>
     107:	49 8d 38             	lea    (%r8),%rdi
     10a:	48 81 ec 80 00 00 00 	sub    $0x80,%rsp
     111:	e8 00 00 00 00       	callq  116 <__pthread_rwlock_unlock+0x116>
     116:	48 81 c4 80 00 00 00 	add    $0x80,%rsp
     11d:	41 8b 70 1c          	mov    0x1c(%r8),%esi
     121:	45 31 d2             	xor    %r10d,%r10d
     124:	ba 01 00 00 00       	mov    $0x1,%edx
     129:	49 8d 78 0c          	lea    0xc(%r8),%rdi
     12d:	b8 ca 00 00 00       	mov    $0xca,%eax
     132:	40 80 f6 81          	xor    $0x81,%sil
     136:	48 63 f6             	movslq %esi,%rsi
     139:	0f 05                	syscall 
     13b:	31 c0                	xor    %eax,%eax
     13d:	c3                   	retq   

    elision-unlock.o:     file format elf64-x86-64
    
    
    Disassembly of section .text:
    
    0000000000000000 <__lll_unlock_elision>:
       0:   8b 07                   mov    (%rdi),%eax
       2:   48 89 fa                mov    %rdi,%rdx
       5:   85 c0                   test   %eax,%eax
       7:   74 27                   je     30 <__lll_unlock_elision+0x30>
       9:   f0 ff 0a                lock decl (%rdx)
       c:   74 16                   je     24 <__lll_unlock_elision+0x24>
       e:   48 8d 3a                lea    (%rdx),%rdi
      11:   48 81 ec 80 00 00 00    sub    $0x80,%rsp
      18:   e8 00 00 00 00          callq  1d <__lll_unlock_elision+0x1d>
      1d:   48 81 c4 80 00 00 00    add    $0x80,%rsp
      24:   31 c0                   xor    %eax,%eax
      26:   c3                      retq
      27:   66 0f 1f 84 00 00 00    nopw   0x0(%rax,%rax,1)
      2e:   00 00
      30:   0f 01 d5                xend
      33:   31 c0                   xor    %eax,%eax
      35:   c3                      retq

**Comment by xtraeme** [comment]
What CPU is it? the lock elision support seems to be always built and there's a runtime check to enable it:

```
static void
elision_init (int argc __attribute__ ((unused)),
              char **argv  __attribute__ ((unused)),
              char **environ)
{
  __elision_available = HAS_RTM;
#ifdef ENABLE_LOCK_ELISION
  __pthread_force_elision = __libc_enable_secure ? 0 : __elision_available;
#endif
  if (!HAS_RTM)
    __elision_aconf.retry_try_xbegin = 0; /* Disable elision on rwlocks */
}
```
and then they check for `HAS_RTM`:

```
# define HAS_RTM        HAS_CPU_FEATURE (COMMON_CPUID_INDEX_7, ebx, bit_RTM)
```

Are you seeing `SIGILL` on any application that uses pthread rwlocks?

**Comment by strake** [comment]
On 25/02/2015, Juan RP <notifications@github.com> wrote:
> What CPU is it?

Intel Core i5 M 520

> Are you seeing `SIGILL` on any application that uses pthread rwlocks?

Yes, I built wpa_supplicant 2.3, which dies on SIGILL, which I traced
with gdb to pthread_rwlock_unlock in libc. This seems to happen only
if I static-link it.

A static-linked pthread_rwlock test program I wrote jumps over the
illegal instruction.

I can't find any use of pthread_rwlock in wpa_supplicant source, and
I'm not sure what's pulling it in.

**Comment by xtraeme** [comment]
Statically linking with glibc and pthreads is probably not supported.... in fact glibc does not support statically linked binaries completely (due to NSS).

If you want to build something statically I'd suggest you to use the musl C library... see https://github.com/voidlinux/void-packages#building-packages-natively-for-the-musl-c-library for more information.

Closing this because as I was assuming, this is only for static binaries... which we do not provide by default with glibc.

**Comment by xtraeme** [comment]
For reference I merged a patch from Fedora to disable completely the lock elision runtime check.

See https://github.com/voidlinux/void-packages/commit/2d1a45ccb1e19521f6c9741e0a864b6fed22e8f7
