### ISSUE TITLE
package request: brother HL-1110

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#10189]
printer webpage http://support.brother.com/g/b/downloadlist.aspx?c=eu_ot&lang=en&prod=hl1110_us_eu_as&os=10013

**Comment by cr6git** [comment]
@icf20 do you still need this driver? check the forum...

**Comment by icf20** [comment]
@cr6git no i dont need it any more, should i close this ?

**Comment by cr6git** [comment]
you do as you wish, me I stopped working on this.

**Comment by Anachron** [comment]
isn‘t this driver supported by gutenprint?
