### ISSUE TITLE
Package Request: ffado

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#1018]
pkgname="ffado"
version="2.2.1"
revision=1
build_style=gnu-configure
short_desc="open-source drivers for FireWire based pro-audio devices"
maintainer="name <email>"
license="GPL-3"
homepage="http://www.ffado.org"
distfiles="http://www.ffado.org/files/libffado-${version}.tgz"
checksum="9f299b8ecd9885338aeae8c7f2fc10af9afb85ca4384256d485b010a128b35f6"
depends="libxml++2>=2.6.13 libraw1394>=2.0.7 libiec61883>=1.1.0 dbus>=1.0 libdbus-c++ libconfig jack>=0.109.12"

**Comment by xtraeme** [comment]
This is not the proper way to submit packages, open a proper Pull Request with your git commit.
