### ISSUE TITLE
Music on Console (moc) aac playback broken on musl

### ISSUE THREAD

**Issue by aproto** [voidlinux/void-packages#10196]
### System

* xuname:  
  Void 4.14.8_1 x86_64-musl GenuineIntel uptodate r
* package:  
  moc 2.5.2 revision 2930

### Expected behavior
Be able to play aac format music streams.
### Actual behavior
Trying to play an aac format music stream crashes the player with:
FATAL_ERROR: Can't receive value from the server!
### Steps to reproduce the behavior
Fresh install of void-musl, xbps-install -S moc alsa-utils, try to play aac stream, i.e:
$mocp http://ice3.somafm.com/dronezone-64-aac, moc crashes.
### Additional info
I have tried this on actual hardware and in a VM. I set up two VMs one with a clean glibc install and one with a clean musl install. I installed only moc and alsa-utils and tried playing both an aac stream and an mp3 stream. The glibc moc played both streams fine while the musl moc would play mp3 streams but crash on aac streams. When installing moc, both versions pulled the same dependencies.
### Debug logs musl
moc client: https://p.teknik.io/Ymkbi
moc server: https://p.teknik.io/YFaRV

### Debug logs glibc
moc client: https://p.teknik.io/yGzb3
moc server: https://p.teknik.io/ZsuPZ

**Comment by cr6git** [comment]
You're right, it's broken.

mpv is one possible alternative.
