### ISSUE TITLE
Package Request: libdbus-c++

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#1021]
pkgname="libdbus-c++"
version="0.9.0"
revision=1
build_style=gnu-configure
short_desc="a C++ API for D-BUS"
maintainer="name <email>"
license="LGPL-2.1"
homepage="http://dbus-cplusplus.sourceforge.net/"
distfiles="http://downloads.sourceforge.net/project/dbus-cplusplus/dbus-c++/${version}/${pkgname}-${version}.tar.gz"
checksum="bc11ac297b3cb010be904c72789695543ee3fdf3d75cdc8225fd371385af4e61"

**Comment by xtraeme** [comment]
This is not the proper way to submit packages, open a proper Pull Request with your git commit.

**Comment by dicktyr** [comment]
> This is not the proper way to submit packages, open a proper Pull Request with your git commit.

sorry
I merely thought it would be useful to post a template

I would open a proper pull request
but I have no repository to pull from
(in spite of having a github account
I don't use git, at least not yet)
