### ISSUE TITLE
mailpile package outdated 

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#10236]
mailpile is going for the version 0,99 the template uses version 0,52

**Comment by anjandev** [comment]
Waiting on the mailpile developers to make a `1.0.0rc1` tag on their git repo.

**Comment by Vaelatern** [comment]
rc is not the same as a release.
We like to wait for stable releases.

**Comment by icf20** [comment]
I don't know what's the latest stable release, they advice not using 0,52 and even got that link removed
