### ISSUE TITLE
Package Request: grub-customizer

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#10302]
Website: https://launchpad.net/grub-customizer

Tried extracting the deb but grub customizer can't find libcrypto.so.1.0.0 and when symlinking, a symbol lookup error occurred.

If anyone could package this, it would be much appreciated. Thanks!

**Comment by pullmoll** [comment]
LMK if it works for you. I ran only a quck test without actually modifying my grub.cfg.
