### ISSUE TITLE
notion keeps being built after move from main to nonfree repo.

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10326]
I'm not sure what could be done to get rid of the constant rebuilding of notion after it was moved from the main repo to nonfree (or whatever is in the template's `repository=...` line). The code checking for the packages to build should detect that a (newer) package already exists elsewhere after such a change, but I have no clue how to achieve that.

**Comment by pullmoll** [comment]
Ok, I got it: no way to solve this until **whenever**.

**Comment by chneukirchen** [comment]
I think removing the template, then removing the binaries, then reinstalling the template should work.

**Comment by ebfe** [comment]
Notion is still rebuilt every builder run on the musl builders. Someone with access to the builder should remove notion from the indexes at current/musl/*-repodata.

**Comment by ebfe** [comment]
Setting bestmatching=true the xbps configuration that xbps-checkvers uses might work too. Not sure what the glibc builders use.

**Comment by the-maldridge** [comment]
The old binaries are still there on the musl builders, but also on the glibc builders (search and you'll get 2 versions for -32bit), so something unique is happening on the musl builders.
