### ISSUE TITLE
Packages with SHA256 mismatches / wrong distfiles

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10353]
- [x] Cutegram
      (9189b96f9b07775311c30f89c6ab702581325fbe9e5bf0d44633ada2b84dc5c6)
- [x] Fritzing
      (cd9f5709b8481639ff8649d516d34cb18a096efa3981e3d20f3cc9d6c9953c97)
- [x] ImageMagick
      https://www.imagemagick.org/download/ImageMagick-6.9.9-30.tar.xz: Not Found
- [x] Pyrex
      http://code.enthought.com/src/Pyrex-0.9.9.tar.gz: Forbidden
- [x] R-cran
      https://cran.r-project.org/src/contrib/data.table_1.10.4.tar.gz: Not Found
- [x] R-cran-nloptr
      (84225b993cb1ef7854edda9629858662cc8592b0d1344baadea4177486ece1eb)
- [ ] R-cran-tibble
      https://cran.r-project.org/src/contrib/tibble_1.3.4.tar.gz: Not found
- [x] TSC
      ftp://ftp.secretchronicles.org/releases/TSC-2.0.0.tar.xz: Connection refused
- [ ] adom
      http://www.ancardia.com/download/adom_linux_debian_64_r60_pub.tar.gz: Not Found
- [x] allegro5
      http://download.gna.org/allegro/allegro/5.2.2/allegro-5.2.2.tar.gz: Connection timed out
- [x] alpine
      http://alpine.freeiz.com/alpine/patches/alpine-2.21/all.patch.gz: Gone
- [x] ampache
      (5e284c91c7d52abdaef43a0fd5b7d252e8d06e18dafad93c2361c96b014bb966)
- [x] apache-directory-studio
      http://wwwftp.ciril.fr/pub/apache/directory/studio/2.0.0.v20151221-M10/ApacheDirectoryStudio-2.0.0.v20151221-M10-linux.gtk.x86_64.tar.gz: Not Found
- [x] apache-maven
      http://apache.arvixe.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz: No route to host
- [x] arandr
      http://christian.amsuess.com/tools/arandr/files/arandr_0.1.9.orig.tar.gz: Not Found
- [x] awoken-icons
      https://dl.dropbox.com/u/8029324/AwOken-2.5.zip: Not Found
- [x] banner
      http://www.moria.de/~michael/banner/banner-1.2.tar.gz: Not Found
- [x] bokken
      http://inguma.eu/attachments/download/212/bokken-1.8.tar.gz: Operation not permitted
- [x] btfs
      (bb9679045540554232eff303fc4f615d28eb4023461eae3f65f08f2427ec9ef2)
- [ ] btsync
      https://download-cdn.getsyncapp.com/2.0.105/linux-x64/BitTorrent-Sync_x64.tar.gz: No address record
- [x] byacc
      ftp://invisible-island.net/byacc/byacc-20170709.tgz: Connection timed out
- [x] c-client
      ftp://ftp.cac.washington.edu/imap/imap-2007f.tar.gz: No address record
- [x] cadaver
      http://www.webdav.org/cadaver/cadaver-0.23.3.tar.gz: Connection refused
- [x] catalyst
      fetching distfile 'radeon-crimson-15.12-15.302-151217a-297685e.zip'...
      flock: failed to execute wget: No such file or directory
- [ ] chromium-widevine
      (c9e71c9fa76878d25c86538f732d50a7af3544c2b1cd19953a07c3f8d4ec1ca1)
- [x] ckbcomp
      http://ftp.debian.org/debian/pool/main/c/console-setup/console-setup_1.173.tar.xz: Not Found
- [x] clsync
      (1af63b86c1d0bd663311f2129792446dc8fc4def5559f76658b51b69a8d0c3bd)
- [x] cproto
      ftp://invisible-island.net/cproto/cproto-4.7m.tgz: Connection timed out
- [x] drbd-utils
      http://oss.linbit.com/drbd/drbd-utils-8.9.6.tar.gz: Not Found
- [x] dunelegacy
      (4740df9e94712b34f5d6fa1ca3c24658c4808b40431aa156ed66c318be9f4de8)
- [x] econnman
      http://download.enlightenment.org/rel/apps/econnman/econnman-1.1.tar.gz: Not Found
- [x] ejabberd
      (aa4e29ee084030671e9c042baa9e4449d8f3502fa920aea4155912ffa5486fce)
- [x] entr
      (02d78f18ae530e64bfbb9d8e0250962f85946e10850dd065899d03af15f26876)
- [x] enventor
      http://download.enlightenment.org/rel/apps/enventor/enventor-1.0.0.tar.bz2: Not Found
- [x] envypn-font
      http://files.ywstd.fr/p/envypn-font/envypn-font-1.7.1.tar.gz: No address record
- [x] epson-inkjet-printer-escpr
      https://download3.ebz.epson.net/dsc/f/03/00/05/55/39/d16f39e5f8953e033f6f38083b38c50c543b891c/epson-inkjet-printer-escpr-1.6.13-1lsb3.2.tar.gz: Not Found
- [x] epstopdf
      (4c4e48722bdd2d52a36440e3f54434d381db64cdfb0ff36b646f504751337330)
- [x] evolution-data-server
      http://ftp.gnome.org/pub/GNOME/sources/evolution-data-server/3/evolution-data-server-3.26.3.tar.xz: Not Found
- [x] exquisite
      http://download.enlightenment.org/releases/exquisite-1.0.0.tar.gz: Not Found
- [x] flao
      http://sigwinch.xyz/software/_files/flao-0.2.tar.bz2: Connection timed out
- [x] flashrom
      http://download.flashrom.org/releases/flashrom-0.9.9.1.tar.bz2: Permanent Redirect
- [x] font-symbola
      (ff0706603b93238008ce1b76fdeeb83c23a470bd90fed56c2c64c6a052842c50)
- [ ] foomatic-db{,-nonfree}
      https://www.openprinting.org/download/foomatic/foomatic-db-4.0-20171222.tar.gz: Not Found
      https://www.openprinting.org/download/foomatic/foomatic-db-nonfree-20171106.tar.gz: Not Found
      Note: this is a permanent issue because the file changes everyday. We ought to use foomatic-db-current.tar.gz and not keep track of the checksum.
- [x] fox
      http://ftp.fox-toolkit.org/pub/fox-1.6.55.tar.gz: Not Found
- [x] fribidi
      http://fribidi.org/download/fribidi-0.19.7.tar.bz2: Not Found
- [x] gajim-otr
      (3aa8a6e17d861e10bca0d55639d100f63eb2aa197bf1b0ab4b0d86c40d1f1391)
- [x] gdash
      https://bitbucket.org/czirkoszoltan/gdash/downloads/gdash-20130427unstable.tar.gz: Not Found
      There is an update which doesn't work (already tried it). Just ignore for now.
- [x] gmic
      (ce71a7d6acf9acde79de42a660f715e8779933e1689f14d39fb0ceaca7582efd)
- [x] gnome-colors-icon-theme
      http://gnome-colors.googlecode.com/files/gnome-colors-5.5.1.tar.gz: Not Found
- [x] gpm
      http://www.nico.schottelius.org/software/gpm/archives/gpm-1.20.7.tar.lzma: Operation not permitted
- [x] graphviz
      http://www.graphviz.org/pub/graphviz/stable/SOURCES/graphviz-2.40.1.tar.gz: Not Found
- [x] gtk-engine-equinox
      (2acbc7705d6dfd6153d6de870d1a55b33c6f716ae71434bf395b9fdbb4d66d78)
- [x] guilt
      http://guilt.31bits.net/src/guilt-0.36.tar.gz: Connection timed out
- [x] handbrake
      (390238cef6373d17a737ddb4319a09bc6691e693a2db06ba60249463e5bafd16)
- [x] hedgewars
      http://download.gna.org/hedgewars/hedgewars-src-0.9.22.tar.bz2: Connection timed out
- [x] httptunnel
      http://www.nocrew.org/software/httptunnel/httptunnel-3.3.tar.gz: Not Found
- [x] hunspell-es_ES
      http://forja.rediris.es/frs/download.php/2945/es_ES.oxt: Connection timed out
- [x]  hunspell-hr_HR
      http://www.libreoffice-na.us/English-4.3-installs/add-on-dictionaries-large-list/Croatian_dictionary_and_hyphenation_patterns--dict-hr____2003-09-28.oxt: Not Found
- [x] hunspell-it_IT
      (53ebeda48a339e88e16f6c7ab530ca66a3337d4d416adf667e1029e27c6eba3f)
- [x] hunspell-pl_PL
      https://sjp.pl/slownik/ort/sjp-myspell-pl-20170717.zip: Not Found
- [x] hunspell-ru_RU
      (713f736948bb8b61c9f65e4bfd5defac0d68e71545f5123fef75f569e55eb9f7)
- [ ] j4status
      http://download.tuxfamily.org/j4tools/j4status/j4status-0.1.tar.xz: Not Found
- [x] jeti-filemanager
      (4da4ddee8fe6774b91ea473810d6c6898777c9bbcb8816996d72095dc0e18691)
- [x] lcms2
      (48c6fdf98396fa245ed86e622028caf49b96fa22f3e5734f853f806fbc8e7d20)
- [x] lfe
      (1967c6d3f604ea3ba5013b021426d8a28f45eee47fd208109ef116af2e74ab23)
- [x] libconfig
      http://www.hyperrealm.com/libconfig/libconfig-1.5.tar.gz: Not Found
- [x] libewf
      https://googledrive.com/host/0B3fBvzttpiiSMTdoaVExWWNsRjg/libewf-20140608.tar.gz: Not Found
- [x] liboauth
      http://downloads.sourceforge.net/sourceforge/liboauth/liboauth-1.0.3.tar.gz: Operation not permitted
- [x] libode
      (2eaebb9f8b7642815e46227956ca223806f666acd11e31708bd030028cf72bac)
- [x] libpng12
      ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng12/libpng-1.2.57.tar.xz: File unavailable (e.g., file not found, no access)
- [x] libpqxx
      http://pqxx.org/download/software/libpqxx/libpqxx-4.0.1.tar.gz: Connection reset by peer
- [x] rlog
      http://rlog.googlecode.com/files/rlog-1.4.tar.gz: Not Found
- [x] libsexy
      http://releases.chipx86.com/libsexy/libsexy/libsexy-0.1.11.tar.gz: Not Found
- [x] libshout-idjc
      http://downloads.sourceforge.net/sourceforge/idjc/libshout-idjc-2.4.1.tar.gz: Not Found
- [x] lightzone
      (4e8e80baf30ab03cd301cfbc42c419b699a57d7ac663a7778839db0e066a6669)
- [ ] lua-luadbi
      http://luadbi.googlecode.com/files/luadbi.0.5.tar.gz: Not Found
- [ ] luakit
      (277f8ee237b7728f00dd2f6875dc386f41280ff69024e40a153a949faaff905b)
- [ ] luaposix
      (ba0bc343783fc33958cd02a68cdbfd65430152d9f297f7ed92678b1a305bd5d7)
- [x] makeself
      (ca0ca386d97bd984f62e9475d9203e2df5fd5abfc55ff5c777e8d324909aa040)
- [x] monero-core
      (39870b40b81cfe986c4ccd379fdde2cf34dabe8e427f7a9723e73ec9ee4ceae0)
- [x] mp3info
      http://fossies.org/linux/misc/mp3info-0.8.5a.tgz: Gone
- [x] myrepos
      https://github.com/joeyh/myrepos/archive/1.20170129.tar.gz: Not Found
- [x] ncftp
      (129e5954850290da98af012559e6743de193de0012e972ff939df9b604f81c23)
- [x] nitrogen
      http://projects.l3ib.org/nitrogen/files/nitrogen-1.6.1.tar.gz: Connection timed out
- [x] numactl
      ftp://oss.sgi.com/www/projects/libnuma/download/numactl-2.0.11.tar.gz: Connection timed out
- [x] ppl
      http://bugseng.com/products/ppl/download/ftp/releases/1.2/ppl-1.2.tar.gz: Forbidden
- [x] python-efl
      http://download.enlightenment.org/rel/bindings/python/python-efl-1.20.0.tar.gz: Not Found
- [x] python-notify
      http://www.galago-project.org/files/releases/source/notify-python/notify-python-0.1.1.tar.gz: Not Found
- [x] qt5-styleplugins
      (dbe1c03f00c6eadebc0ed9d5ec1eeb9129e8132c8574545dfa788f505c2dd9a3)
- [x] qtfm
      (b2bbd68b7fb21df0f5e18d63447f8666bd51922b348eebef9f2c354246a33a10)
- [x] rasterview
      (690e0666aa76a4abf962506a3bed5b5b0406d4b69a2696b27392db6243f3d806)
- [x] sexy-python
      http://releases.chipx86.com/libsexy/sexy-python/sexy-python-0.1.9.tar.gz: Not Found
- [x] since
      http://welz.org.za/projects/since/since-1.1.tar.gz: Connection refused
- [x] skype (amd64)
      (115cb4b9ba713f85830487cb300478352019487fd09c795824566943fd638ee0)
- [x] slstatus
      https://git.nulltime.net/slstatus/snapshot/slstatus-2.0.tar.gz: No address record
- [x] smem
      https://www.selenic.com/smem/download/smem-1.4.tar.gz: No route to host
- [x] soulseekqt
      https://dl.dropboxusercontent.com/u/7226803/SoulseekQt-2016-1-17-64bit.tgz: Not Found
- [x] splint
      http://www.splint.org/downloads/splint-3.1.2.src.tgz: Connection refused
- [x] suricata
      (830057d48d7b6ba156c4981a28d16b540dc3bb376f7a909c8d4eb16405098267)
- [x] task
      (42d227ef5006d6d576165ae22384798ba52073471524ccc92a7872272863576d)
- [x] tcllibe
      (6b854dcf03c73834c064b9d16c7287e2146ef2223fe85297db4e9918ec89d8f8)
- [x] tintin
      (7f3eb8237252d1a23c6388e6f9ee2a8a2e79e143b5f5a809700775a45a6c6c55)
- [x] touchegg
      http://touchegg.googlecode.com/files/touchegg-1.1.1.tar.gz: Not Found
- [x] ttf-material-icons
      (b25cf06c66f87fc9ff7fa81213c8f725dfc268027f8cc8b6366e9a9cd41f1105)
- [x] ttf-ubuntu-font-family
      (e2be027d439f71210d7ade9a1765001b875c7df775f3853b7e4eaa962d7b744e)
- [x] ufoai (ufoai-2.5-data.tar)
      (5e706a424aff6a2ea30a4c798129d6304e897387eadf808528129b512b7dcdb0)
- [x] uzbl
      (9721873db3fd859707f703a101b4f2d0538f92e9678f8ad437a7203078f9abbe)
- [x] varnish
      http://repo.varnish-cache.org/source/varnish-3.0.7.tar.gz: Gone
- [x] vile
      ftp://invisible-island.net/vile/current/vile-9.8s.tgz: Connection timed out
- [x] xcmenu
      https://github.com/Cloudef/xcmenu/archive/v0.1.0.tar.gz: Not Found
- [ ] xen
      http://bits.xensource.com/oss-xen/release/4.7.2/xen-4.7.2.tar.gz: No address record
      #10612

… more to come …

**Comment by chneukirchen** [comment]
alpine moved to http://repo.or.cz/alpine.git

**Comment by cr6git** [comment]
I have no problem with `smem`.

**Comment by pullmoll** [comment]
Me neither. It seems that was temporary. Marked as solved.

**Comment by cr6git** [comment]
I have no problem fetching catalyst distfiles.

**Comment by pullmoll** [comment]
catalyst: It's my fault. I ran the test with `./xbps-src -I fetch` which means that things like `wget` are just not installed and trying to use it of course fails.

**Comment by cr6git** [comment]
No problem with apache-maven.

**Comment by cr6git** [comment]
flashrom fixed by @maxice8 in [#10382](https://github.com/voidlinux/void-packages/pull/10382).

**Comment by cr6git** [comment]
Trying to fix econnman, I have another problem with elementary: [#10548](https://github.com/voidlinux/void-packages/issues/10548).

However, tarballs are available at [econnman.git](https://git.enlightenment.org/apps/econnman.git).

**Comment by cr6git** [comment]
Cutegram depends on libqtelegram-ae and TelegramQML, which need to be adjusted to allow cross compilation.

**Comment by pullmoll** [comment]
It seems I need to revbump `econnman-1.1.0` to at least `_4` because it is considered less than `1.1_3` ;-P

**Comment by cr6git** [comment]
@pullmoll As I mentioned, econnman does not start:
````
$ sudo xbps-install -S econnman
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...

Name     Action    Version           New version            Download size
econnman install   -                 1.1.0_4                61KB 

Size to download:               62KB
Size required on disk:         176KB
Free space on disk:             28GB

Do you want to continue? [Y/n] y

[*] Downloading binary packages
econnman-1.1.0_4.noarch.xbps: 61KB [avg rate: 1331MB/s]
econnman-1.1.0_4.noarch.xbps.sig: 512B [avg rate: 15MB/s]

[*] Verifying package integrity
econnman-1.1.0_4: verifying RSA signature...

[*] Running transaction tasks
econnman-1.1.0_4: unpacking ...

[*] Configuring unpacked packages
econnman-1.1.0_4: configuring ...
Updating MIME database...
econnman-1.1.0_4: installed successfully.

1 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.

$ econnman-bin
Traceback (most recent call last):
  File "/usr/bin/econnman-bin", line 45, in <module>
    import elementary as elm
ImportError: No module named elementary
````

**Comment by cr6git** [comment]
@pullmoll something went wrong with Cutegram.

**Comment by cr6git** [comment]
Yes, `on x86_64-musl`.

**Comment by cr6git** [comment]
I have no problem with python-notify.

**Comment by cr6git** [comment]
According to [/releases](http://varnish-cache.org/releases/), varnish-3.0.7 is End Of Life.

**Comment by pullmoll** [comment]
python-notify: I guess that was temporary then. Works here as well.

**Comment by cr6git** [comment]
No problem with liboauth.

**Comment by cr6git** [comment]
No problem with libpqxx.

**Comment by cr6git** [comment]
No problem fetching libsexy / sexy-python, again a temporary glitch?

**Comment by pullmoll** [comment]
Tagged the ones which are reachable again. For me apache-maven fails, though.
```shell
$ LC_ALL=C wget http://apache.arvixe.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
--2018-01-13 15:04:54--  http://apache.arvixe.com/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
Resolving apache.arvixe.com... 198.58.87.82
Connecting to apache.arvixe.com|198.58.87.82|:80... failed: No route to host.
```

**Comment by cr6git** [comment]
For me it works:
````
$ xgensum srcpkgs/apache-maven/template
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
x86_64-musl-repodata: 1402KB [avg rate: 7447KB/s]
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/x86_64-musl-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-repodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-repodata': Not Found
=> apache-maven-3.5.2_1: running do-fetch hook: 00-distfiles ...
=> apache-maven-3.5.2_1: fetching distfile 'apache-maven-3.5.2-src.tar.gz'...
looking up www-us.apache.org
connecting to www-us.apache.org:443
SSL options: 80004014
Peer verification enabled
Using CA cert path: /etc/ssl/certs
Verify hostname
TLSv1.2 connection established using ECDHE-RSA-AES256-GCM-SHA384
Certificate subject: /C=US/postalCode=21050-2747/ST=Maryland/L=Forest Hill/street=1901 Munsey Drive/O=The Apache Software Foundation/OU=Infrastructure/OU=Hosted by Secure Sockets Laboratories/CN=*.apache.org
Certificate issuer: /C=US/O=SSL.com/OU=www.ssl.com/CN=SSL.com High Assurance CA
requesting https://www-us.apache.org/dist/maven/maven-3/3.5.2/source/apache-maven-3.5.2-src.tar.gz
apache-maven-3.5.2-src.tar.gz: [2608KB 0%] 20KB/s ETA: 10m51s
apache-maven-3.5.2-src.tar.gz: [2608KB 15%] 342KB/s ETA: 00m10s
apache-maven-3.5.2-src.tar.gz: [2608KB 37%] 452KB/s ETA: 00m04s
apache-maven-3.5.2-src.tar.gz: [2608KB 60%] 500KB/s ETA: 00m02s
apache-maven-3.5.2-src.tar.gz: [2608KB 83%] 522KB/s ETA: 00m00s
apache-maven-3.5.2-src.tar.gz: 2608KB [avg rate: 625KB/s]
=> apache-maven-3.5.2_1: verifying checksum for distfile 'apache-maven-3.5.2-src.tar.gz'... OK.
=> apache-maven-3.5.2_1: fetching distfile 'apache-maven-3.5.2-bin.tar.gz'...
looking up www-us.apache.org
connecting to www-us.apache.org:443
SSL options: 80004014
Peer verification enabled
Using CA cert path: /etc/ssl/certs
Verify hostname
TLSv1.2 connection established using ECDHE-RSA-AES256-GCM-SHA384
Certificate subject: /C=US/postalCode=21050-2747/ST=Maryland/L=Forest Hill/street=1901 Munsey Drive/O=The Apache Software Foundation/OU=Infrastructure/OU=Hosted by Secure Sockets Laboratories/CN=*.apache.org
Certificate issuer: /C=US/O=SSL.com/OU=www.ssl.com/CN=SSL.com High Assurance CA
requesting https://www-us.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
apache-maven-3.5.2-bin.tar.gz: [8534KB 0%] 20KB/s ETA: 00m00s
apache-maven-3.5.2-bin.tar.gz: [8534KB 1%] 168KB/s ETA: 01m24s
apache-maven-3.5.2-bin.tar.gz: [8534KB 5%] 323KB/s ETA: 00m33s
apache-maven-3.5.2-bin.tar.gz: [8534KB 10%] 376KB/s ETA: 00m24s
apache-maven-3.5.2-bin.tar.gz: [8534KB 17%] 417KB/s ETA: 00m19s
apache-maven-3.5.2-bin.tar.gz: [8534KB 23%] 440KB/s ETA: 00m16s
apache-maven-3.5.2-bin.tar.gz: [8534KB 29%] 456KB/s ETA: 00m14s
apache-maven-3.5.2-bin.tar.gz: [8534KB 35%] 466KB/s ETA: 00m12s
apache-maven-3.5.2-bin.tar.gz: [8534KB 42%] 477KB/s ETA: 00m11s
apache-maven-3.5.2-bin.tar.gz: [8534KB 49%] 493KB/s ETA: 00m09s
apache-maven-3.5.2-bin.tar.gz: [8534KB 57%] 516KB/s ETA: 00m07s
apache-maven-3.5.2-bin.tar.gz: [8534KB 67%] 553KB/s ETA: 00m05s
apache-maven-3.5.2-bin.tar.gz: [8534KB 78%] 578KB/s ETA: 00m03s
apache-maven-3.5.2-bin.tar.gz: [8534KB 91%] 623KB/s ETA: 00m01s
apache-maven-3.5.2-bin.tar.gz: 8534KB [avg rate: 684KB/s]
=> apache-maven-3.5.2_1: verifying checksum for distfile 'apache-maven-3.5.2-bin.tar.gz'... OK.

````

**Comment by pullmoll** [comment]
Strange thing is that I can reach the site with `traceroute apache.arvixe.com` but not from the browser(s) or with `wget` or `xbps-uhelper fetch`. Perhaps my router needs to be slapped around a bit with a large trout :)

**Comment by newbluemoon** [comment]
Updating R-cran-tibble requires adding a couple of new packages. Maybe the maintainer @wagnerflo wants to do this? :)

**Comment by cr6git** [comment]
The latest release is 1.4.1, published 2017-12-25, see [here](https://cran.r-project.org/web/packages/tibble/index.html).
As you pointed out, the build fails because of missing dependencies:
````
=> R-cran-tibble-1.4.1_1: running do_install ...
ERROR: dependencies ‘crayon’, ‘pillar’ are not available for package ‘tibble’
* removing ‘/destdir/R-cran-tibble-1.4.1/usr/lib/R/library/tibble’
=> ERROR: R-cran-tibble-1.4.1_1: failed to run do_install() at line 6.
=> ERROR: R-cran-tibble-1.4.1_1: failed to run do_install() at line 4.
````

**Comment by pullmoll** [comment]
**R** is yet another language which I don't speak. Is **R-cran** a dialect or just a pronunciation? I'll leave it to anyone who want's to tackle that. Or just let's leave this alone, if noone is interested. All I did was trying to fetch all distfiles to see the failures. I doubt we need to become ambitious for no reason.

**Comment by newbluemoon** [comment]
Don’t know much about R, too. Just tried to update the package. Even started to create the ‘crayon’ and ‘pillar’ packages, but these require other new packages to create. So my ambition died there ;)

**Comment by newbluemoon** [comment]
‘adom’ is a binary distribution only. It is linked against `libtinfo.so.5` and `libncurses.so.5` which aren’t available in void. The idea was to create symlinks for these libs pointing to the actual libncurses in a separate directory to avoid conflicts and use a wrapper script:

```
do_install() {
        ...
	vmkdir usr/lib/adom
	vcopy adom usr/lib/adom
	ln -s ../libncursesw.so.6 ${DESTDIR}/usr/lib/adom/libtinfo.so.5
	ln -s ../libncursesw.so.6 ${DESTDIR}/usr/lib/adom/libncurses.so.5
	vmkdir usr/bin
	cat > ${DESTDIR}/usr/bin/adom << _EOF
#! /bin/sh
LD_LIBRARY_PATH=/usr/lib/adom /usr/lib/adom/adom "$@"
_EOF
	chmod 755 ${DESTDIR}/usr/bin/adom
}
```

But there is a problem: `libncurses.so.5` is referenced in `shlibs`

    libncurses.so.5 ncurses-libs-6.0_1 ignore

but ncurses-libs doesn’t provide `libncurses.so.5` (or a symlink) and this ends in an ‘unresolvable shlib error’ when trying to install the package. I’m not sure which way to go: add a symlink in ncurses-libs libncurses.so.5 -> libncurses.so.6 or remove the line from `shlibs`?

**Comment by wagnerflo** [comment]
@pullmoll, @newbluemoon: I'll take care of the R and R-cran (CRAN is to R what CPAN is to Perl) packages next week. Currently I'm away from any workable computer setup so any earlier ain't possible.

**Comment by newbluemoon** [comment]
<i>enventor</i> and <i>exquisite</i> from the enlightenment project are probably too old, also see #6741. I don’t think it makes sense to waste energy there.

<i>flao</i> seems to be gone. Couldn’t even find it in the AUR.

<i>btsync</i> is now <i>resilio-sync</i>: [https://www.resilio.com/](https://www.resilio.com/). Someone fancy creating a new package? ;)

<i>lfe</i> was updated to 1.3 but there is something wrong with the `Makefile` which was fixed and a new release 1.3.1 should be available anytime soon (whatever that means).

You can make a tick for <i>R-cran</i> (the fith from above). This was #10766. :)

**Comment by pullmoll** [comment]
@newbluemoon since you're symlinking for a pseudo libncurses.so.5 perhaps you can add `shlibs_provide=libncurses.so.5` to avoid the `unresolvable shlib error`. I think in that case xbps-install should be happy with the pkg alone.

**Comment by newbluemoon** [comment]
@pullmoll That works, thanks! :)
Had a different idea about `shlib_provides` in mind. So it’s only relevant for the package that’s using it and doesn’t affect others?

**Comment by pullmoll** [comment]
AFAIK yes. Tĥink about how it could have an impact on other packages?
There is no `common/*` code looking through all templates searching for `shlib_provides`
This variable only modifies what goes into the specific package's meta data.

**Comment by newbluemoon** [comment]
Yes, thinking about it, it shouldn’t. But does the `xbps` binary make use of this information when it’s in the package database?

**Comment by pullmoll** [comment]
@newbluemoon eventor download exists as tar.xz but I don't know which template tried to download it as I don't find that name in srcpkgs/*/template. And with the build problems with newer efl we could just remove it. Huh? exquisite is gone on enlightenment.org, so we can definitely remove it. I'll be looking into the others.

**Comment by newbluemoon** [comment]
@pullmoll I think you didn’t find it because it’s e<i>**n**</i>ventor ;)

**Comment by pullmoll** [comment]
@newbluemoon f*sck! :) @ebfe what do we do with flao? I can't find a trace of it.

**Comment by newbluemoon** [comment]
For exquisite I found a download here:
https://download.enlightenment.org/att/releases/exquisite-1.0.0.tar.bz2

But it’s six years old and I think it’s just for historical reasons still there.

**Comment by pullmoll** [comment]
Well, exquisite is @xtraeme 's package and IIRC he prefers enlightenment (DE), so we should leave it to him to drop the package, if he wishes.

**Comment by cr6git** [comment]
Great! We are almost finished! 😄

**Comment by cr6git** [comment]
@pullmoll tintin checksum has changed again? between [my pull](https://github.com/voidlinux/void-packages/pull/10417) and @Hoshpak 's [recent fix](https://github.com/voidlinux/void-packages/pull/10903).
For what strange reason it changes so often?

**Comment by cr6git** [comment]
@pullmoll I just realized that we have 2 packages: `apache-maven` and `apache-maven-bin`.

I was testing `apache-maven` which is ok, and you were testing `apache-maven-bin` which produces the network error `No route to host`.
This is why apache-maven-bin is in the list [#10899](https://github.com/voidlinux/void-packages/issues/10899), I just realized that.

**Comment by Gottox** [comment]
Close this for now, the remainders are taken care of in https://github.com/voidlinux/void-packages/issues/10899
