### ISSUE TITLE
package request: nyx (tor-nyx?)

### ISSUE THREAD

**Issue by copyleftie** [voidlinux/void-packages#10370]
(or should it be called tor-nyx?)

[https://nyx.torproject.org/#download](https://nyx.torproject.org/#download)
[https://gitweb.torproject.org/nyx.git](https://gitweb.torproject.org/nyx.git)

**Comment by pullmoll** [comment]
Oops, it seems @wpbirney also wanted to make a package for nyx and chose python2, while my choice was to use python3. I think it doesn't really matter, or does it?

**Comment by wpbirney** [comment]
@pullmoll I don't believe it matters as it builds with any python >= 2.7 including python3
