### ISSUE TITLE
Idea: avoid force registering noarch packages

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#10387]
If multiple architecture's packages live in a shared repository, the `xbps-src` command line switch `-f` (`XBPS_BUILD_FORCEMODE`) leaves broken indexes for the other architectures whenever the package to register is `noarch`.

I think a clever fix for `common/hooks/do-pkg/00-gen-pkg.sh` could help circumvent that problem by not force registering `noarch` packages, except for an update, in which case force is redundant anyway.

I wanted to ask, if someone see a problem with simply skipping the `xbps-create` call for the case where a `*.noarch.xbps` package file already exists?

**Comment by ebfe** [comment]
> I wanted ask, if someone see a problem with simply skipping the `xbps-create` call for the case where a `*.noarch.xbps` package file already exists?

Fixing a broken template then requires to manually delte the xbps and
clean up the repo index.

**Comment by pullmoll** [comment]
Then perhaps a better solution could be to make 00-gen-pkg.sh look for other existing `*-repodata` files and check if they already referenced the current `*.noarch.xbps` file. If that was the case, the force built package could then be registered for the other architectures at the same time.

Not sure if that would be viable and comparably less error prone than having to manually fix an e.g. `*-doc` subpackage for multiple architectures with the help of `xbps-rindex`.

**Comment by ebfe** [comment]
> Then perhaps a better solution could be to make 00-gen-pkg.sh look for
> other existing `*-repodata` files and check if they already referenced
> the current `*.noarch.xbps` file. If that was the case, the force
> built package could then be registered for the other architectures at
> the same time.
> 
> Not sure if that would be viable and comparably less error prone than
> having to manually fix an e.g. `*-doc` subpackage for multiple
> architectures with the help of `xbps-rindex`.

imo, the solution is to make xbps-rindex handle this case.
