### ISSUE TITLE
i3 exit problem

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1039]
On exit `i3` with $mod+shift+e, Terminal and  `i3-nagbar` run in Background and aren't not closed.

If I run `i3-msg exit` from Termial, the Terminal run also in Background and i3 exit.

The `i3` session is started via `lxdm`.  With `xdm` the exit is normal and cosed all.

See https://github.com/i3/i3/issues/1505

**Comment by xtraeme** [comment]
I cannot reproduce it...

**Comment by pulux** [comment]
I can't also reproduce it now.
