### ISSUE TITLE
proot cannot be cross compiled for aarch64-musl

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#10481]
### System

* xuname:  `Void 4.14.11_1 x86_64-musl GenuineIntel uptodate rFFFFFF`

* package:  `proot-5.1.0_4`

### Expected behavior
It would be possible to cross build this package...
### Actual behavior
([build log](https://gist.github.com/cr6git/d164f032cf14ce52864eb97f6a6477ac)) `aarch64-musl` fails!
````
$ ./xbps-src -a aarch64-musl pkg proot
[...]
=> proot-5.1.0_4: running do_build ...
  CC	cli/note.o
  CC	execve/enter.o
  CC	execve/exit.o
  CC	execve/shebang.o
  CC	execve/elf.o
./execve/enter.c: In function 'compute_load_addresses':
./execve/enter.c:335:36: error: 'EXEC_PIC_ADDRESS' undeclared (first use in this function)
   add_load_base(tracee->load_info, EXEC_PIC_ADDRESS);
                                    ^~~~~~~~~~~~~~~~
./execve/enter.c:335:36: note: each undeclared identifier is reported only once for each function it appears in
./execve/enter.c:349:44: error: 'INTERP_PIC_ADDRESS' undeclared (first use in this function); did you mean 'EXEC_PIC_ADDRESS'?
   add_load_base(tracee->load_info->interp, INTERP_PIC_ADDRESS);
                                            ^~~~~~~~~~~~~~~~~~
                                            EXEC_PIC_ADDRESS
make: *** [GNUmakefile:162: execve/enter.o] Error 1
make: *** Waiting for unfinished jobs....
  CC	execve/ldso.o
rm .check_process_vm.o .check_seccomp_filter.o
=> ERROR: proot-5.1.0_4: failed to run do_build() at line 25.
````

([build log](https://gist.github.com/cr6git/3ff7659799205e0a1370f8ee209cf5fe)) `armv6l-musl` works.

([build log](https://gist.github.com/cr6git/3fd57b33a57a64e34b1611dd06875d10)) `armv7l-musl` works.
### Steps to reproduce the behavior
Try to cross build this package for `aarch64-musl`.
````
$ ./xbps-src -a aarch64-musl pkg proot
````

**Comment by newbluemoon** [comment]
This seems to be an upstream bug. In `src/arch.h` `EXEC_PIC_ADDRESS` and `INTERP_PIC_ADDRESS` are **not** defined for `ARCH_ARM64` and yet they’re used in `src/execve/enter.c`.

**Comment by newbluemoon** [comment]
Proot 5.1.0 was released three years ago. The issue seems to be resolved in the git version. Debian e.g. uses a patch to fix this. Maybe just adapt this patch?

**Comment by cr6git** [comment]
Thanks @newbluemoon
