### ISSUE TITLE
Patch request: infinality

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1053]
Could we include infinality patchset or the ubuntu patchset to improve font rendering on lcd displays?

http://www.infinality.net/blog/
https://wiki.archlinux.org/index.php/Infinality

**Comment by bougyman** [comment]
can you link to the patchset you're recommending?

**Comment by thypon** [comment]
https://github.com/bohoomil/fontconfig-ultimate This is the patchset updated very ofter from bohoomil.

This instead is the patches from ubuntu would be much more tricky.

**Comment by nmeum** [comment]
:+1:

**Comment by skrzyp** [comment]
:+1: 
It's quite easy, just add patches for freetype and cairo, but fontconfig part might be more tricky.

**Comment by thypon** [comment]
Right now the patch is alredy inside the void-packages repository. To apply simply download it and:

```
xbulk -oultimate cairo freetype fontconfig
xbps-install -R hostdir/binpkgs/ cairo freetype fontconfig
```

**Comment by thypon** [comment]
I'm considering to create a separate repository containing these updated packages.

**Comment by nkoehring** [comment]
@thypon I unfortunately didn't find out, what this `xbulk` command is. Is it `./common/xbps-src/shutils/bulk.sh` ?

**Comment by Duncaen** [comment]
@nkoehring the patches are obsolete and already removed again from the templates. (https://www.freetype.org/index.html#news)

`xbulk` is part of `xtools`.
