### ISSUE TITLE
Upower Segmentation Fault

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1054]
[gattuso@R2D2 ~]$ upower -m
    Monitoring activity from the power daemon. Press Ctrl+C to cancel.

    (upower:6438): libupower-glib-WARNING **: up_client_get_devices failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.207 was not provided by any .service files
    Segmentation fault
    [gattuso@R2D2 ~]$ upower -e

    (upower:6454): libupower-glib-WARNING **: up_client_get_devices failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.210 was not provided by any .service files
    Segmentation fault
    [gattuso@R2D2 ~]$ dmesg | tail -n 4
    [ 1809.958414] traps: upowerd[6441] trap int3 ip:7f1899f7c8e0 sp:7fff5073e2a0 error:0
    [ 1809.964751] upower[6438]: segfault at 8 ip 000000000040178c sp 00007fff54ba18c0 error 4 in upower[400000+3000]
    [ 1813.703829] traps: upowerd[6457] trap int3 ip:7f9d4d7348e0 sp:7fffee2a3ac0 error:0
    [ 1813.710535] upower[6454]: segfault at 8 ip 000000000040158f sp 00007fff9734b390 error 4 in upower[400000+3000]

- I saw it because the battery indicator and the keyboard backlight doesn't work.

One question: is ASLR enabled in voidlinux?

**Comment by xtraeme** [comment]
Try `xbps-query -s upower` and then update to 0.99.0_6 and see if this fixes the segfault.

ASLR is enabled in void.

**Comment by thypon** [comment]
I updated to 0.99.0_6 from 0.99.0_5, same error.

**Comment by xtraeme** [comment]
The issue is that almost all pkgs are rebuilt against upower 0.x, the only exception being gnome which needs 0.99.x.

So you were trying to use upower 0.99.x while the pkgs were linked against libupower-glib.so.1 (0.x).

**Comment by thypon** [comment]
I think so. I have however another problem with upower 0.x.

**Comment by xtraeme** [comment]
```
[juan@leysa void-packages]$ xbps-query --fulldeptree -Rx kde|grep upower
libupower-glib1-0.9.23_7
upower0-0.9.23_7
[juan@leysa void-packages]$
```

Not sure what you mean, but there's not any package that depends directly on upower (0.99).

**Comment by thypon** [comment]
I finally solved the problem. Now kde works with upower (no upower0). The log i got was similar to these from "http://forums.gentoo.org/viewtopic-p-7067438.html". The problem was with polkit and not upower.

i solved only by using this command:
```
usermod -d /var/empty polkitd 
```
This change the home directory of polkitd user from /dev/null to /var/empty solving the problem.
