### ISSUE TITLE
Update Flatpak to version 10.2.1

### ISSUE THREAD

**Issue by rushsteve1** [voidlinux/void-packages#10593]
### System

* package:  
  `flatpak` and by extension `flatpak-devel`

## Issue
The current version of Flatpak provided by the repo is out of date.
Provided version: 0.10.1 
Latest version: [0.10.2.1](https://github.com/flatpak/flatpak/releases/tag/0.10.2.1)

The new version contains usability improvements and bugfixes.

Hopefully this should be an easy update, and if not someone let me know and I will take it up in a couple weeks when I have time. Presumably it should just be a matter of bumping the version in the [template file](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/flatpak/template).

**Comment by Vaelatern** [comment]
3566c418cdfb76a48a4406f09b51def37b80ba36
