### ISSUE TITLE
feature request: Remmina RDP-plugin

### ISSUE THREAD

**Issue by MellowVoidUser** [voidlinux/void-packages#10609]
Current version of Remmina doesn't support the RDP protocol which would be very nice to use for me...
( as a noob getting completly lost in building it myself, also the remmina flatpak option is too complex since it needs flatpak-builder which is way over my head. Anyone who can make this easy for me and other noobs is greatly appreciated )

**Comment by cr6git** [comment]
Because I used the cmake flag `-DWITH_FREERDP=OFF` in the template.

But if it's necessary, I can change that.

**Comment by cr6git** [comment]
I removed the flag, added `freerdp-devel` to the `makedepends`, but now it doesn't build:
````
-- Finding suggested package FREERDP.
--   Disable this using "-DWITH_FREERDP=OFF".
-- Checking for module 'freerdp>=1.0'
--   Found freerdp, version 1.0.2
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FREERDP (missing: FREERDP_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFREERDP.cmake:35 (find_package_handle_standard_args)
  cmake/FindOptionalPackage.cmake:37 (find_package)
  remmina-plugins/CMakeLists.txt:59 (find_suggested_package)

-- Configuring incomplete, errors occurred!
See also "/builddir/Remmina-1.1.2/build/CMakeFiles/CMakeOutput.log".
=> ERROR: remmina-1.1.2_2: failed to run do_configure() at line 38.
````

**Comment by Johnnynator** [comment]
I suspect that the Remina rdp plugin depends on a newer freerdp version than the latest release. Which is somewhat ironic since both projects come from the same team and there wasn't a stable release of both projects for years.

**Comment by cr6git** [comment]
It looks similar to issue [#193](https://github.com/FreeRDP/Remmina/issues/193)...

@Johnnynator you're probably right, freerdp-1.0.2 too old...

**Comment by newbluemoon** [comment]
The latest [FreeRDP release](https://github.com/FreeRDP/FreeRDP/releases) is 2.0.0-rc1 which seems to include the missing `libfreerdp-client.so` and `libfreerdp-locale.so`.

**Comment by cr6git** [comment]
@newbluemoon but it's pre-release, the latest is still [1.0.2](https://github.com/FreeRDP/FreeRDP/releases/tag/1.0.2).

**Comment by newbluemoon** [comment]
@cr6git Yes, just meant to say that it’s there ;) But with the rate of progress with rc0 from 2017-07-24 and rc1 from 2017-11-28 it can take a while...

**Comment by cr6git** [comment]
@newbluemoon ok, I modified the [template](https://gist.github.com/cr6git/93194e2ca91e8247349400562894cb07) to build 2.0.0-rc1 but I got [errors](https://gist.github.com/cr6git/fb718563dabc58aee14541d5fba6b5a7)...

**Comment by newbluemoon** [comment]
Found [this](https://sourceforge.net/p/freerdp/mailman/message/36160657/):

> The FIPS_mode() functions are a part of the OpenSSL library. However,
> OpenBSD uses LibreSSL, which does not support FIPS mode and never will.
> 
> So this could be fixed by updating the CMakeLists to support OpenBSD.
> It should disable FIPS mode usage for OpenBSD

**Comment by cr6git** [comment]
You are probably right, but I don't feel I'm competent enough to create a patch.

**Comment by newbluemoon** [comment]
Good news: it’s already fixed and merged upstream (and actually quite simple :)).

https://github.com/FreeRDP/FreeRDP/pull/4298/files

Should have looked there earlier, sorry!

**Comment by newbluemoon** [comment]
Just for convenience ;)

```
--- winpr/libwinpr/utils/ssl.c.orig	2017-11-28 15:26:30.000000000 +0100
+++ winpr/libwinpr/utils/ssl.c		2018-01-10 10:28:17.187304871 +0100
@@ -279,7 +279,7 @@
 
 	if (flags & WINPR_SSL_INIT_ENABLE_FIPS)
 	{
-#if (OPENSSL_VERSION_NUMBER < 0x10001000L)
+#if (OPENSSL_VERSION_NUMBER < 0x10001000L) || defined(LIBRESSL_VERSION_NUMBER)
 		WLog_ERR(TAG, "Openssl fips mode ENable not available on openssl versions less than 1.0.1!");
 #else
 		WLog_DBG(TAG, "Ensuring openssl fips mode is ENabled");
@@ -348,7 +348,7 @@
 
 BOOL winpr_FIPSMode(void)
 {
-#if (OPENSSL_VERSION_NUMBER < 0x10001000L)
+#if (OPENSSL_VERSION_NUMBER < 0x10001000L) || defined(LIBRESSL_VERSION_NUMBER)
 	return FALSE;
 #else
 	return (FIPS_mode() == 1);
```

**Comment by cr6git** [comment]
OK! Here's my new [template](https://gist.github.com/cr6git/c0290c97f82723c8e601e9e2e5606ae2) to build freerdp [2.0.0-rc1](https://github.com/FreeRDP/FreeRDP/releases/tag/2.0.0-rc1), using the patch for libressl, of course.

Update common/shlibs with:
````
libfreerdp-client2.so.2 libfreerdp-2.0.0rc1_1
libfreerdp2.so.2 libfreerdp-2.0.0rc1_1
libwinpr2.so.2 libfreerdp-2.0.0rc1_1
libwinpr-tools2.so.2 libfreerdp-2.0.0rc1_1
````

And my new [template](https://gist.github.com/cr6git/49b5d6ff93ef5cc243a3ae3cdea8c984) to build remmina [1.2.0-rcgit.26](https://github.com/FreeRDP/Remmina/releases/tag/v1.2.0-rcgit.26).

But... I got new [build errors](https://gist.github.com/cr6git/5e1f80555162daf0845a57cc4aadccf4). 😕

**Comment by newbluemoon** [comment]
```
/builddir/Remmina-1.2.0-rcgit.26/remmina-plugins/rdp/rdp_event.c:46:10: fatal error: execinfo.h: No such file or directory
```

Execinfo again ;)

This patch works for me:

```
--- remmina-plugins/rdp/rdp_event.c.orig	2017-12-28 23:29:03.000000000 +0100
+++ remmina-plugins/rdp/rdp_event.c		2018-01-10 14:23:01.455993508 +0100
@@ -43,7 +43,9 @@
 #include <gdk/gdkkeysyms.h>
 #include <cairo/cairo-xlib.h>
 #include <freerdp/locale/keyboard.h>
+#ifdef __GLIBC__
 #include <execinfo.h>
+#endif
 
 static void remmina_rdp_event_on_focus_in(GtkWidget* widget, GdkEventKey* event, RemminaProtocolWidget* gp)
 {
```

**Comment by pullmoll** [comment]
As an alternative we have `libexecinfo-devel`. It's perhaps worth a try if adding this to `makedepends` for `*-musl` and also adding `-lexecinfo` to either `LDFLAGS` or `LIBS` works out.

**Comment by newbluemoon** [comment]
@pullmoll Thanks! Didn’t think of this one (it’s a rather new package if I’m correct). It works by just adding it to `makedepends`. :)

**Comment by cr6git** [comment]
Thanks @Johnnynator for libexecinfo. 👍

**Comment by pullmoll** [comment]
I think a release candidate is ok, especially since it's a tagged version, as long as there is no stable 1.2.x release.

**Comment by cr6git** [comment]
It's done!

**Comment by MellowVoidUser** [comment]
Cool!
Thanks for all the work, I really appreciate this since it means I can use my laptop for work.
I'm gonna try it asap.

Thanks cr6git and others!

**Comment by MellowVoidUser** [comment]
the repo seams to have remmina-1.2.0rc26 for arm but not (yet?) for x86_64
als so for freerdp-2.0.0rc1_1...

**Comment by newbluemoon** [comment]
See here: https://build.voidlinux.eu/waterfall
It’s still in the pipeline, you’ll just have to wait a little bit longer ;)

**Comment by MellowVoidUser** [comment]
I didn't know that a waterfall existed (learning a lot about voidlinux). Thnx

**Comment by MellowVoidUser** [comment]
it can confirm it works!
kudos!
