### ISSUE TITLE
Some terminfo files are missing

### ISSUE THREAD

**Issue by z3ntu** [voidlinux/void-packages#10672]
### System

* xuname:  
Void 4.14.12_4 x86_64 GenuineIntel/KVM notuptodate rFFF
* package:  
ncurses-6.0_2

### Expected behavior
e.g. the file /usr/share/terminfo/k/konsole-256color should exist to provide terminfo for that $TERM variable
### Actual behavior
That file doesn't exist (in that 'k' folder only kon & kon2 is present compared to 34 files on Arch Linux.
### Steps to reproduce the behavior
\-

**Comment by pullmoll** [comment]
Install `ncurses-term` for the full list of terminals. `ncurses-base` contains only a small selection of terminals.

**Comment by z3ntu** [comment]
Thanks. Really sucks when the terminal is unknown and every curses application is behaving weirdly (like in bash backspace isn't working etc).
So is this package too big to be installed by default or why isn't it installed?

**Comment by pullmoll** [comment]
I don't really know. Perhaps size was an issue when @xtraeme originally created the package. Some (embedded) systems have very small storage space available...
