### ISSUE TITLE
autofs: add support of sssd

### ISSUE THREAD

**Issue by blizar** [voidlinux/void-packages#10690]
### System

* xuname:  
  Void 4.14.12_4 x86_64 GenuineIntel notuptodate rF
* package:  
  autofs 5.1.4_1

### Expected behavior
autofs doesn't work with sssd map file
it seems to be compile without the sssd support

### Actual behavior
$ automount -m
open_lookup:104: cannot open lookup module sss (/usr/lib/autofs/lookup_sss.so: cannot open share object file: no such file or directory)

**Comment by pullmoll** [comment]
This should be fixed in `autofs-5.1.4_2`. It doesn't work for `x86_64-musl`, though, because `sssd` depends on `ncsd` which is a `glibc` subpackage - and of course `glibc` cannot be built for `x86_64-musl`.
