### ISSUE TITLE
Request: lxc runit support

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1071]
Now only supports systemd service.

**Comment by bougyman** [comment]
What do you propose? Lxc cannot be directly supervised/run in the foreground, it's not a fit for runit supervision. I'll take a look into the systemd service and see if I can come up with something.

**Comment by thypon** [comment]
lxc supports an lxc-autostart directive supposed to work with the respective init daemon.

**Comment by thypon** [comment]
the problem with lxc-autostart is that is a forking program. How to track and supervise it?

**Comment by xtraeme** [comment]
Something like this should be really enough:

```
lxc-autostart/run:
#!/bin/sh
lxc-autostart || exit 1
exec chpst -b lxc-autostart pause
```

```
lxc-autostart/finish:
#!/bin/sh
lxc-autostart -s 15 || exit 1
```
