### ISSUE TITLE
Package request: Overpass

### ISSUE THREAD

**Issue by espectalll** [voidlinux/void-packages#10727]
Source code at https://github.com/RedHatBrand/Overpass

I will package this on my own asap, but others' contributions are welcome (?)

**Comment by cr6git** [comment]
Done.

**Comment by cr6git** [comment]
@espectalll you can close this.

**Comment by espectalll** [comment]
OK, it's been added at https://github.com/voidlinux/void-packages/commit/4fe9406b32c8c09c18f7063cd1468ea08422ace0, closing
