### ISSUE TITLE
openjdk broken: unresolvable shlibs

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-packages#1076]
So after updating today it seems I get a few unresolvable shlibs. Now, I did read up on this and tried the [solution](https://groups.google.com/forum/#!topic/voidlinux/_XjhqGPbew0) posted on Twitter.
However, running `xbps-query -s '' -p transaction` on it's own, produces no results, and neither does running the full command.

I'm not sure how to reproduce the issue here, but I've pasted the output of running `xbps-install -Su` below.

    [*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...  
    [*] Updating `http://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...  
    [*] Updating `http://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...  
    [*] Updating `http://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...  
    openjdk-8u40_3: broken, unresolvable shlib `libawt.so'  
    openjdk-8u40_3: broken, unresolvable shlib `libawt_xawt.so'  
    openjdk-8u40_3: broken, unresolvable shlib `libjava.so'  
    openjdk-8u40_3: broken, unresolvable shlib `libjli.so'  
    openjdk-8u40_3: broken, unresolvable shlib `libjvm.so'
    Transaction aborted due to unresolved shlibs.

**Comment by Epictek** [comment]
I'm also experiencing this problem

**Comment by xtraeme** [comment]
The openjdk pkg needs to set those shlibs manually:

```
shlib_provides="libawt.so libawt_xawt.so libjava.so libjli.so libjvm.so"
```

Will fix this soon, thanks.

**Comment by 230v** [comment]
Bug come back

openjdk-8u60_1: broken, unresolvable shlib `libawt.so'
openjdk-8u60_1: broken, unresolvable shlib `libawt_xawt.so'
openjdk-8u60_1: broken, unresolvable shlib `libjava.so'
openjdk-8u60_1: broken, unresolvable shlib `libjli.so'
openjdk-8u60_1: broken, unresolvable shlib `libjvm.so'
Transaction aborted due to unresolved shlibs.
