### ISSUE TITLE
LibreOffice eats 100% CPU

### ISSUE THREAD

**Issue by scadu** [voidlinux/void-packages#10807]
### System

* xuname:  
Void 4.14.13_1 x86_64 GenuineIntel uptodate r
* package:  
libreoffice
glib

### Expected behavior
Not to eat my ~cat~ CPU.

### Actual behavior
For example process `/usr/lib/libreoffice/program/soffice.bin --writer --splash-pipe=5` uses 100% CPU.

### Steps to reproduce the behavior
Run LibreOffice Writer.

[One of comments](https://bugs.documentfoundation.org/show_bug.cgi?id=108246#c16) on Document Foundation bug tracker points to a certain commit in glib2 causing a CPU loop. Reverting this revert commit seems to "fix" the issue for now.

Arch guys have already reverted this commit in a [current version of glib2 package](https://git.archlinux.org/svntogit/packages.git/commit/trunk/PKGBUILD?h=packages/glib2&id=682f2fb8c822bba8b588623a197db2be55ba8a4d)

I could prepare a PR, if there is no better solution for this.

**Comment by codingHahn** [comment]
Can conform with Impress too. It has nothing to do with the JRE Environment. It makes using Libreoffice almost impossible, because the fan is constantly spinning.

**Comment by pullmoll** [comment]
LMK if reverting the revert (or was it triple already?) solves the issue.

**Comment by scadu** [comment]
@pullmoll just pulled the glib update, opened few documents in Writer. Seems to be working. Thanks.
