### ISSUE TITLE
Atom: wrong paths in desktop file

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#1086]
Launching Atom from the applications menu does not open atom and icon for atom does not appear either. 

In the desktop file for 'Exec' we have:  
`Exec=/destdir/atom-0.186.0/usr/share/atom/atom %U`  
This obviously won't work and instead should be 

`Exec=atom`  
since atom has a link in /usr/bin and the desktop file looks there anyway 

Furthermore, the icon 'atom.png' has a path of:  
``Icon=/destdir/atom-0.186.0/usr/share/atom/resources/app/resources/atom.png`  
The icon should be moved to /usr/share/pixmaps and the desktop file changed to:  

`Icon=atom.png`

I'm sure this issue has already been noticed since it is hard to miss but I wanted to report it anyway.

**Comment by thypon** [comment]
line n22 of template should have fixed the path problem. I can't find where the bug lies right now and i quickfix manually with:

```
export PKGDESTDIR="/destdir/atom-0.186.0"
sudo -E sed -i "s|${PKGDESTDIR}||" /usr/share/applications/atom.desktop
```

For the icon right now i don't think is a good idea to move `/usr/share/pixmaps` until atom is considered api stable.

**Comment by thypon** [comment]
this bug is not solved.

**Comment by silvernode** [comment]
yep, still the same
