### ISSUE TITLE
docker-cli not build

### ISSUE THREAD

**Issue by espositom221** [voidlinux/void-packages#10885]
### System

* xuname:  
 Void 4.14.13_2 x86_64 GenuineIntel uptodate rFF
* package: 
  docker

### Actual behavior

The  build of docker package get static version for docker cli.
Arch linux build docker cli
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/docker

regards

**Comment by arete** [comment]
fix in https://github.com/void-linux/void-packages/pull/2139

**Comment by espositom221** [comment]
/close

Il 31 ago 2018 06:29, "Gerardo Di Iorio" <notifications@github.com> ha
scritto:

fix in void-linux/void-packages#2139
<https://github.com/void-linux/void-packages/pull/2139>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/voidlinux/void-packages/issues/10885#issuecomment-417549418>,
or mute the thread
