### ISSUE TITLE
php-apache: PHP module not threadsafe

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-packages#1090]
Alright, so I'm not sure how many of you are running Apache on Void Linux, but I gave it a shot today to see how well it fared.

Turns out, not that great at all. Enabling the php5 module (/usr/libexec/httpd/modules/libphp5.so) results in apache crashing, with the error:

    [Tue Mar 10 12:17:48.004690 2015] [:crit] [pid 1802:tid 140380627330944] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
    AH00013: Pre-configuration failed

So that seems to be an issue to me, that was not related to my configuration, especially considering the only configuration option changed was the addition of a LoadModule statement.

Reproduce:

    # xbps-install -S php-apache apache
    # nano /etc/httpd/httpd.conf

Then add the following line, after the list of LoadModule configurations.

    LoadModule php5_module /usr/libexec/httpd/modules/libphp.so

And run:

    # httpd

That's it, the error should now display.

**Comment by xtraeme** [comment]
https://github.com/voidlinux/void-packages/issues/823

**Comment by necrophcodr** [comment]
I guess this can be closed. Seems a strange non-documented issue though.
