### ISSUE TITLE
php using wrong open_basedir value

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-packages#1091]
Reading the php/patches/php.ini.patch file:

    --- php.ini-production.orig	2014-08-27 15:31:35.000000000 +0200
    +++ php.ini-production	2014-09-30 17:56:35.704994951 +0200
    @@ -296,7 +296,7 @@ serialize_precision = 17
     ; or per-virtualhost web server configuration file. This directive is
     ; *NOT* affected by whether Safe Mode is turned On or Off.
     ; http://php.net/open-basedir
    -;open_basedir =
    +open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/

It becomes clear that, compared to the apache webdirectory, PHP is only allowed to read /srv/http, while apache works from /srv/httpd.

Perhaps using /srv/httpd would be ideal here? Not sure if other packages would conflict with this choice, but in that case /srv/httpd/ could be added instead of replacing the existing path.

**Comment by xtraeme** [comment]
Makes sense.
