### ISSUE TITLE
virt-manager, failed to initialize KVM: Permission denied

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1095]
create a new VM (as user in group wheel or root) with VNC Console brings:

```
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 89, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/create.py", line 1855, in do_install
    guest.start_install(meter=meter)
  File "/usr/share/virt-manager/virtinst/guest.py", line 405, in start_install
    noboot)
  File "/usr/share/virt-manager/virtinst/guest.py", line 469, in _create_guest
    dom = self.conn.createLinux(start_xml or final_xml, 0)
  File "/usr/lib/python2.7/site-packages/libvirt.py", line 3497, in createLinux
    if ret is None:raise libvirtError('virDomainCreateLinux() failed', conn=self)
libvirtError: internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied
failed to initialize KVM: Permission denied
```
maybe it comes from libvirtd

**Comment by pulux** [comment]
not in (Usermode) `qemu:///session`

only in `qemu:///system`

**Comment by xtraeme** [comment]
Probably libvirt must be added to a group that is able to access to `/dev/kvm`:

```
[juan@leysa void-packages]$ xbps-query -R -pinstall-msg qemu
To enable KVM your user must be added to the 'wheel' group:

        $ usermod -aG wheel <username>

Don't forget to load the appropiate KVM module for your CPU (x86 only):

        $ modprobe kvm-amd # for AMD CPUs
        $ modprobe kvm-intel # for Intel CPUs
[juan@leysa void-packages]$
```

**Comment by pulux** [comment]
I'm in the group wheel and libvirtd runs as root

If I define a VM from via `virsh define vm.xml`, these run fine. If I try to define a new VM via virt-manager GUI, the error occur.

**Comment by thypon** [comment]
The problem is that even if libvirtd runs as root it starts qemu with user:group defined into `/etc/libvirt/qemu.conf` (by default nobody:nobody). One long term solution could be to add a new system group named `kvm` (changing /dev/kvm to user:group root:kvm) and run qemu from nobody:kvm.

**Comment by chneukirchen** [comment]
+1 for group kvm.

**Comment by vhosakot** [comment]
I was able to resolve the `failed to initialize KVM: Permission denied` error after doing the following:

```
rmmod kvm_intel
rmmod kvm
modprobe kvm
modprobe kvm_intel
```

The above commands reload the `kvm_intel` and `kvm` kernel modules.

**Comment by bartman** [comment]
As pointed out by @vhosakot, reloading the drivers did the trick.  Thanks!

I initially had the problem in virt-manager running remotely.  Then from virsh crate ...xml.

Surprisingly, issuing kvm -cpu ... -machine ... worked fine.  But using libvirst kept saying "permission denied", even when running as root.

Again, rmmod and modprobe did the trick.

**Comment by AddoSolutions** [comment]
> I was able to resolve the `failed to initialize KVM: Permission denied` error after doing the following:
> 
> ```
> rmmod kvm_intel
> rmmod kvm
> modprobe kvm
> modprobe kvm_intel
> ```
> The above commands reload the `kvm_intel` and `kvm` kernel modules.

That worked perfect for me.  I had done a fresh install and I didn't reboot after the install but worth noting.
