### ISSUE TITLE
 Elogind errors on boot, slower login

### ISSUE THREAD

**Issue by emacsomancer** [voidlinux/void-packages#10997]
### System

* xuname:  
Void 4.14.14_1 x86_64-musl GenuineIntel uptodate rFF

* package:  
 elogind-235.2_1

### Expected behaviour
boot/login without issue

### Actual behaviour
displays error messages on boot (see below), delays login by 10+ seconds:

    .... elogind[8822]: Cannot determine cgroup we are running in: No medium found
    .... elogind[8822]: Out of memory.

### Steps to reproduce the behaviour
boot computer

[see also: https://forum.voidlinux.eu/t/elogind-errors-on-boot-slower-login/4399 ]

**Comment by cr6git** [comment]
[bugs.gentoo.org/644834](https://bugs.gentoo.org/644834)
