### ISSUE TITLE
Package request: soundconverter

### ISSUE THREAD

**Issue by xdave** [voidlinux/void-packages#110]
http://soundconverter.org/

**Comment by Vaelatern** [comment]
```
# Template file for 'soundconverter'
pkgname=soundconverter
version=2.1.6
revision=1
#wrksrc=
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends="intltool python"
makedepends="pygtk-devel"
depends=""
short_desc="Leading audio file converter for the GNOME Desktop"
maintainer="Toyam Cox <Vaelatern@gmail.com>"
license="GPL-3"
homepage="http://soundconverter.org/"
distfiles="https://launchpad.net/${pkgname}/trunk/${version}/+download/${pkgname}-${version}.tar.xz"
checksum=2ffb6718d8e43a67be4d99e5a9c7b5cd82fce15d30b4861608b7d1666884a690
```

Build stops at
```
checking for python-gnome 2.16 installed... not found
configure: error: required python-gnome version not found
```

Not sure which `python-gnome` is referred to here.

**Comment by the-maldridge** [comment]
@Vaelatern did you ever determine which version of python-gnome this wanted?  I suspect that this is the same issue I ran into quite some time ago where the package dates back to the time where gnome was updating various bindings and its no longer possible to build the needed versions anymore.

**Comment by newbluemoon** [comment]
@Vaelatern I modified your template to use the latest version, added some dependencies and now it works :-) Tested on glibc and musl. I’m just not sure if I should do a PR or if you would like to do it yourself.

<pre>
# Template file for 'soundconverter'
pkgname=soundconverter
version=3.0.0beta1
revision=1
wrksrc="${pkgname}-${version/beta1/-beta1}"
build_style=gnu-configure
hostmakedepends="intltool python3"
makedepends="gtk+3-devel python3-gobject gstreamer1-devel"
short_desc="Leading audio file converter for the GNOME Desktop"
maintainer="Toyam Cox <Vaelatern@gmail.com>"
license="GPL-3"
homepage="http://soundconverter.org/"
distfiles="https://launchpad.net/${pkgname}/trunk/${version/beta1/-beta1}/+download/${pkgname}-${version/beta1/-beta1}.tar.xz"
checksum=e7a7a0cc27fd4165b4fae3baa7b735eda9b92b80ff6a7d8976a50679c4832f38
nocross="dependency python3-gobject cannot be cross compiled"
</pre>

**Comment by cr6git** [comment]
It's done.
