### ISSUE TITLE
vlc requires libbcm_host.so, missing dependency?

### ISSUE THREAD

**Issue by jfcolom** [voidlinux/void-packages#11017]
### System
* uname -a
Linux ------ 4.9.77_1 #1 SMP Sat Jan 20 06:04:27 UTC 2018 armv7l GNU/Linux
* package:  
vlc-2.2.8_2

### Expected behavior
Run and reproduce some media

### Actual behavior
Running vlc from  a terminal:

> vlc: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory

### Steps to reproduce the behavior
Install and run vlc in a rpi runing armv7l void linux:
```
xbps-install vlc
vlc

```

**Comment by jfcolom** [comment]
The required library is owned by rpi-userland which is installed. It is in /opt/vc/lib/libbcm_host.so.
I have try to workaround the problem by runing
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/vc/lib/
vlc
```
I don' get the error message any more. Unfortunately, i get "Segmentation Fault" instead

**Comment by cr6git** [comment]
> warning: cannot read `/usr/lib/vlc/plugins/plugins.dat`: No such file or directory

This file is removed during `post_install()` in the current [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/vlc/template#L83).

**Comment by jfcolom** [comment]
I've tried to generate `/usr/lib/vlc/plugins/plugins.dat` by running
`/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins/`
However, I get Segmentation Fault

**Comment by cr6git** [comment]
This is what the INSTALL [script](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/vlc/INSTALL) is supposed to do.

**Comment by cr6git** [comment]
Just to be clear: I don't have a Raspberry to make some tests, so it's impossible for me to help you more, I'm sorry.

**Comment by jfcolom** [comment]
Thank you, anyway!

**Comment by jfcolom** [comment]
I have removed these files (which seem to me specific to rpi platform):
```
/usr/lib/vlc/plugins/codec/libmmal_codec_plugin.so
/usr/lib/vlc/plugins/video_output/libmmal_vout_plugin.so
```
Now I can regenerate the cache without segfault:
`/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins/`

Unfortunately, vlc still is not working

> VLC media player 2.2.8 Weatherwax (revision 2.2.7-14-g3cc1d8cba9)
> Inconsistency detected by ld.so: dl-tls.c: 74: _dl_next_tls_modid: Assertion `result <= GL(dl_tls_max_dtv_idx) + 1' failed!

**Comment by newbluemoon** [comment]
Is this your first attempt at using vlc on the Raspberry or was it working previously? In the latter case we could try to track down what has changed.

I’m using armv7l-musl and get a different error:

```
Error loading script /usr/lib/vlc/lua/intf/cli.luac: /usr/lib/vlc/lua/intf/cli.luac: incompatible precompiled chunk
```

**Comment by newbluemoon** [comment]
Actually it is working, just the ncurses interface is not. The GUI is not a default build option for non-x86 targets. When specifying a file to play on the command line it’s ok.

**Comment by jfcolom** [comment]
It is my first attempt at using vlc on my Raspberry (no screen) with Void. I would be happy if i could run vlc just by specifying a sound file on the command line. When running  `vlc -vv song.wav` I also get some warnings, one of them similar to the one you are pointing out.

```
[014d6b50] core libvlc warning: cannot load module `/usr/lib/vlc/plugins/demux/libmkv_plugin.so' (/usr/lib/vlc/plugins/demux/libmkv_plugin.so: undefined symbol: _ZNK7libebml10EbmlStringcvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv)
[014d6b50] core libvlc warning: cannot load module `/usr/lib/vlc/plugins/video_output/libegl_x11_plugin.so' (/opt/vc/lib/libEGL.so: undefined symbol: glPointSizePointerOES)
[015784a8] lua demux meta warning: Error loading script /usr/lib/vlc/lua/meta/reader/filename.luac: /usr/lib/vlc/lua/meta/reader/filename.luac: incompatible precompiled chunk
```

**Comment by newbluemoon** [comment]
The `dl-tls.c` in your earlier error message is part of the glibc so I don’t get this error. But I have no clue what’s wrong there.

As alternatives, if you just want to play an audio file you can also try mpv and for videos omxplayer.

**Comment by jfcolom** [comment]
I suspect there is a problem with rpi-userland package. I have the newest 20180103_1, what version do you have (`xbps-query -s rpi-userland`)? 
Maybe a rebuild of vlc package could help

**Comment by newbluemoon** [comment]
I have the same rpi-userland version. But you can try to rebuild vlc and see if that helps. I just can’t test the build for glibc myself, apparently ;)

**Comment by jfcolom** [comment]
I have rebuilt the package and reinstalled vlc and libvlc. but i end with the same error.

In conclusion, I have got into many 'irregularities'. First, rpi-userland libraries are not available by default and must be manually set in LD_LIBRARY_PATH (or configured en /etc/ld.so.conf.d). Then, some plugins in /usr/lib/vlc/plugins raise segfault when cached with /usr/lib/vlc/vlc-cache-gen. Finally I get "Inconsistence detected by ld.so"

Maybe is time to consider your suggested alternatives (mpv, omxplayer), mpd, or migrate my void linux rpi to armv7l-musl. 

Thank you

**Comment by jfcolom** [comment]
I have installed void linux armv7l-musl on the RPI3 and vlc is now playing sound, without raising segfault.
However I still need to rebuild the plugin cache after installation (installation fails at this stage)
`# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/vc/lib:/opt/vc/liplugins`
`# /usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins/`
And also to export LD_LIBRARY_PATH to vlc 
`$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/vc/lib:/opt/vc/liplugins`
`$ vlc song.wav`
It seems like libraries provided by rpi-userland package in /opt/vc/lib are not available by default.

**Comment by newbluemoon** [comment]
Just reinstalled vlc and I don’t have any problem with the plugin cache. Strange.

But regarding the library path: maybe a solution is to put `LD_LIBRARY_PATH=...` in your `.bashrc` (or whatever shell you’re using)? Or would a wrapper make sense?

**Comment by pullmoll** [comment]
I think the rpi-userland package should add a file like `/etc/ld.conf.so.d/rpi-userland.conf` which contains
```
/opt/vc/lib
```

**Comment by jfcolom** [comment]
> But regarding the library path: maybe a solution is to put LD_LIBRARY_PATH=... in your .bashrc (or whatever shell you’re using)? Or would a wrapper make sense?

Yes, those workarounds are perfectly valid to me.

> I think the rpi-userland package should add a file like /etc/ld.conf.so.d/rpi-userland.conf which contains /opt/vc/lib

I think so.

**Comment by newbluemoon** [comment]
Just found out that `ld.conf.so.d` isn’t used on musl. Trying to find out how it’s done there...

**Comment by jfcolom** [comment]
The `ldconfig` program exists, and it belongs to musl package in armv7l-musl rootfs. However, it belongs to glibc package in glibc distributions. Perhaps ld.conf.so.d is used in musl, but the folder has not been created because we don't have installed packages providing dynamic libraries.

**Comment by newbluemoon** [comment]
`ldconfig` in musl is just a symlink to `true`.

Regarding the library path I found [this post](http://www.openwall.com/lists/musl/2015/04/22/4) in musl’s mailing list. Also see the last item in section ‘Additional Files Used’ of musl’s [manual](https://www.musl-libc.org/doc/1.0.0/manual.html):

> ../etc/ld-musl-$(ARCH).path, taken relative to the location of the "program interpreter" specified in the program's headers - if present, this will be processed as a text file containing the shared library search path, with components delimited by newlines or colons. If absent, a default path of "/lib:/usr/local/lib:/usr/lib" will be used. Not used by static-linked programs.

The caveat is that on musl the paths specified in `/etc/ld-musl-$(ARCH).path` aren’t added to the list; if that file exists **only** the paths contained are searched! So that the glibc rpi-userland should add the file @pullmoll suggested and the musl version a file `/etc/ld-musl-armhf.path` with `/lib:/usr/local/lib:/usr/lib:/opt/vc/lib` (i.e. the default path plus the rpi-userland libs).

@pullmoll If you’re OK with this I can do a PR to add this to rpi-userland. Perhaps there’s another path that should be added? Tested it on my Pi and didn’t run into any problem (yet ;)).

**Comment by newbluemoon** [comment]
Adding

```
case "$XBPS_TARGET_MACHINE" in
	*-musl) 
		vmkdir etc
		echo /lib:/usr/local/lib:/usr/lib:/opt/vc/lib > ${DESTDIR}/etc/ld-musl-armhf.path
		;;
	*)
		vmkdir etc/ld.so.conf.d
		echo /opt/vc/lib > ${DESTDIR}/etc/ld.so.conf.d/rpi-userland.conf
		;;
esac
```

to rpi-userland’s `post_install()` should do it.

**Comment by newbluemoon** [comment]
@jfcolom Does the updated rpi-userland solve your issue?

**Comment by jfcolom** [comment]
Sure!, It does.
Thank you very much.
