### ISSUE TITLE
Package Request: Heroes of Newerth

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#11026]
So I've played http://www.heroesofnewerth.com/ a while ago which has a linux client as well (https://www.heroesofnewerth.com/download/).

The file itself is an self-decompressing file which has 18 LoC and uses dd to write the rest of it's data to a temporary file which is launched immediately after and removed after executing. 

I plan to write a template which automatically downloads this file and strips the first lines (the extraction code) and then runs the launcher (and if possible installs some other files along with it, like license and alike).

Are you okay with that or is this a too big "hack" that you do not want to have in the official repo?

**Comment by Vaelatern** [comment]
It can probably be a `nonfree` and `restricted` package.

**Comment by Anachron** [comment]
It was more of a queston about whether this type of packaging/distribution is fine here, since I have to write some "special" install functions which modify the "binary".

The other thing is that the URL doesn't change when a new version is released. So it basically always installs the latest version from the website (unless we mirror those packages which are 4.5GB each).

If you don't see any issues I'll go ahead and write it. 

My suggestion `heroes-of-newerth` and version is always `latest`?

**Comment by Anachron** [comment]
I've created a template but it fails since it requires old shlibs and harfbuzz which breaks other stuff.
If anyone else wants to give this a try I can upload my template here.

**Comment by Vaelatern** [comment]
@Anachron just paste your template here. It might never be used, but at least it can be found.
