### ISSUE TITLE
john doesn't build jumbo patch

### ISSUE THREAD

**Issue by abenson** [voidlinux/void-packages#11024]
### System

* xuname:  Void 4.14.14_1 x86_64 GenuineIntel uptodate rrFFFF
* package:  john-1.8.0_8

### Expected behavior

John should support many formats. 

~~~
$ john --list=formats | tr '\n' ' ' |  tr ',' '\n'  | wc -l
193
~~~

### Actual behavior

John only supports the basic built-in formats.

~~~
$ john --list=formats | tr '\n' ' ' |  tr ',' '\n'  | wc -l
10
~~~

### Additional Notes

Looking at the results of the configure, it seems that for some reason the steps to generate the list of format plugins fails. 

~~~
configure: creating ./fmt_externs.h
cpp: fatal error: too many input files
compilation terminated.
configure: creating ./fmt_registers.h
cpp: fatal error: too many input files
compilation terminated.
cpp: fatal error: too many input files
compilation terminated.
cpp: fatal error: too many input files
compilation terminated.
~~~

One of the failing lines in configure is:

~~~
$CPP -P -DAC_BUILT $CPU_BEST_FLAGS $CFLAGS $HAVE_OPENCL $HAVE_CUDA $CFLAGS_EXTRA $OPENSSL_CFLAGS -DFMT_EXTERNS_H *_fmt_plug.c | LC_ALL=C $GREP "extern struct fmt_main" | LC_ALL=C $SORT -f > fmt_externs.h
~~~

The other lines are similar.

I'll keep poking at it to see if I can fix the issue. I just wanted to open this for visibility.

**Comment by cr6git** [comment]
[#9226](https://github.com/voidlinux/void-packages/issues/9226)

**Comment by Vaelatern** [comment]
This issue should stay open.

**Comment by newbluemoon** [comment]
Just an idea without having looked at the code: it’s likely `$OPENSSL_CFLAGS` might be the culprit. Depending on how those flags are extracted the command to do so probably fails because Void has LibreSSL and a possible error message is interpreted as filenames by `$CPP`?

**Comment by newbluemoon** [comment]
No, just checked: it’s not `$OPENSSL_CFLAGS`.

**Comment by newbluemoon** [comment]
Found the solution: `$CPP=cpp` takes only one input file. The referenced PR changes `$CPP` to `$CC -E` and now <i>john</i> can make use of all formats. :)

**Comment by Vaelatern** [comment]
547da9b

**Comment by ratsch** [comment]
this worked for me: 
export CPP="gcc -E" 
./configure
