### ISSUE TITLE
Creating (big) debug pkgs fails with ENOMEM in i686 build env

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#11050]
### System

* xuname:  
  *Void 4.14.14_1 x86_64 AuthenticAMD uptodate rrrdFFFFF*
* package:  
  *`./xbp-src pkg linux4.14` in i686 build env*

### Expected behavior
Create the package
### Actual behavior
Fails with this error message:
```
=> Creating linux4.14-dbg-4.14.15_1.i686.xbps for repository /host/binpkgs/debug ...
xbps-create: ERROR: cannot write ./usr/lib/debug/usr/lib/modules/4.14.15_1/kernel/drivers/media/pci/ttpci/budget-ci.ko to archive: lzma compression failed: lzma_code() call returned status 11 Cannot allocate memory
```
### Steps to reproduce the behavior

It obviously [worked on the i686 builder](https://build.voidlinux.eu/builders/i686_builder/builds/7298/steps/shell_3/logs/stdio) so I'm wondering what's wrong on my side.
A complete strace log of running the xbps-create command is [here](https://gist.github.com/pullmoll/53fc8a5bd78af81d51ba7facb11819ab#file-xbps-create-log).
Perhaps someone has an idea what could cause this. Inside the chroot `ulimit -a` tells all relevant limits (data seg size, max memory size, virtual memory) are `unlimited` while `max locked memory` is `64k` - perhaps it's this one?

**Comment by ebfe** [comment]
```
1049  mmap2(NULL, 25169920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
1049  brk(0x59a93000)                   = 0x58291000
1049  mmap2(NULL, 25300992, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
1049  mmap2(NULL, 2097152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0xf39000
1049  munmap(0xf39000, 815104)          = 0
1049  munmap(0x1100000, 233472)         = 0
1049  mprotect(0x1000000, 135168, PROT_READ|PROT_WRITE) = 0
1049  mmap2(NULL, 25169920, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
1049  munmap(0x765fe000, 229376)  
```

**Comment by pullmoll** [comment]
@ebfe yes, there it fails, but why? :)

**Comment by pullmoll** [comment]
I think xbps-create, or libarchive for that matter, uses parallelism when compressing a package so perhaps it's due to 32 threads doing it in parallel and exhausting some limit this way on my box.

**Comment by ebfe** [comment]
Maybe simply running out of address space. How big is the file in
question? Other than that there's /proc/sys/vm/max_map_count that limits
the number of mappings.

**Comment by pullmoll** [comment]
The file is 252520 bytes. FWIW using `XBPS_PKG_COMPTYPE=gzip` works for me, so it's in the default `xz` compression.

**Comment by pullmoll** [comment]
After modifying the `srcpkgs/libarchive/patches/filter-xz-enable-threads.patch` to use at most 12 threads the packaging of `linux4.14-4.14.15` for `i686` succeeds here.

We should perhaps add a parameter to `xbps-create` to allow for limiting the threads to some maximum. Or alternatively find an upper limit by inspecting `/proc/sys/vm/max_map_count` and taking that into account... but how?

**Comment by ebfe** [comment]
Is it really max_map_count? (e.g. it should work after increasing it). Address space exhaustion seems more likely given that there aren't many mappings active per threads.

**Comment by pullmoll** [comment]
I have no clue which of the /proc/sys/vm limits is actually the reason for this. I don't know enough about the kernel vm and especially not for i686 or the linux32 mode we're using.

Perhaps a simple hard upper limit is sufficient in this case. I used 12 because my other box has 6 cores / 12 threads and never had this problem.

**Comment by pullmoll** [comment]
Solved.
