### ISSUE TITLE
Conky segfault with new version

### ISSUE THREAD

**Issue by tothler** [voidlinux/void-packages#11063]
### System

* xuname:  Void 4.14.14_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  conky-1.10.7_1

### Expected behavior
Conky runs without issue

### Actual behavior
Conky segfaults and terminates, if its config contains the option 'out_to_x = false'

### Steps to reproduce the behavior
```bash
echo 'conky.config = {
        out_to_console = true,
        out_to_x = false,
};

conky.text = [[ hi ]];' > testconkyconfig
conky --config=./testconkyconfig
```

This is a known upstream issue with conky. See [https://github.com/brndnmtthws/conky/issues/454](https://github.com/brndnmtthws/conky/issues/454). It has since been fixed upstream, but the fix is not included in the newest release, as of v1.10.7, which is currently the version provided by xbps.

The previous version, v1.10.6 does not exhibit this bug.  

I suggest either downgrading to v1.10.6 until the next release, or breaking the "no non-release commits" rule and using the newest commit.

**Comment by Vaelatern** [comment]
6864a1c14d

**Comment by tothler** [comment]
Much thanks, that was fast.
