### ISSUE TITLE
libxatracker need libllvm>=3.5.0_1

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1106]
libxatracker need libllvm>=3.5.0_1, but libllvm is not in Repo only libllvm3.6-3.6.0_1

[DEBUG] libxatracker-10.5.0_1: requires dependency 'libllvm>=3.5.0_1

**Comment by xtraeme** [comment]
```
[juan@leysa ~]$ xbps-query -R -ppkgver,repository libllvm
libllvm-3.5.1_4
http://repo.voidlinux.eu/current
[juan@leysa ~]$
```

**Comment by pulux** [comment]
Yes but not in void-packages/srcpkgs
