### ISSUE TITLE
libllvm not in void-packages/srcpkgs since 0c3416cd853c35ddd39e4ec9aafb348bded8e43b

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1107]
some packages depends on 'libllvm>=3.5.0_1' but libllvm can't build, only libllvm3.6 is in srcpkgs

**Comment by xtraeme** [comment]
Again, what packages? mesa is the only one and depends on *llvm*.

**Comment by xtraeme** [comment]
Even if **libllvm** was removed, if you build mesa it will link to **libllvm3.6** as expected.

I don't get what's your problem.

**Comment by pulux** [comment]
=> libclc-git-20141115_2: required dependencies:
   [host] git>=0: found 'git-2.3.2_1'.
   [target] python>=0: found 'python-2.7.9_6'.
   [target] libffi-devel>=0: found 'libffi-devel-3.2.1_1'.
   [target] zlib-devel>=0: found 'zlib-devel-1.2.8_6'.
   [target] llvm>=0: found 'llvm-3.6.0_1'.
   [target] clang>=0: found 'clang-3.6.0_1'.
   [target] ncurses-devel>=0: found 'ncurses-devel-5.9_9'.
=> libclc-git-20141115_2: running pre-build hook: 02-script-wrapper ...
=> libclc-git-20141115_2: running do_build ...
LINK utils/prepare-builtins
LLVM-LINK amdgcn--/lib/builtins.link.tahiti.bc
/usr/bin/ld: cannot find -ledit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:13: recipe for target 'utils/prepare-builtins' failed
make: *** [utils/prepare-builtins] Error 1
make: *** Waiting for unfinished jobs....
=> ERROR: libclc-git-20141115_2: failed to run do_build() at line 14

**Comment by pulux** [comment]
```
./xbps-src -N pkg libclc-git
=> libclc-git-20141115_2: required dependencies:
   [host] git>=0: found 'git-2.3.2_1'.
   [target] python>=0: found 'python-2.7.9_6'.
   [target] libffi-devel>=0: found 'libffi-devel-3.2.1_1'.
   [target] zlib-devel>=0: found 'zlib-devel-1.2.8_6'.
   [target] llvm>=0: found 'llvm-3.6.0_1'.
   [target] clang>=0: found 'clang-3.6.0_1'.
   [target] ncurses-devel>=0: found 'ncurses-devel-5.9_9'.
=> libclc-git-20141115_2: running pre-build hook: 02-script-wrapper ...
=> libclc-git-20141115_2: running do_build ...
LINK utils/prepare-builtins
OPT amdgcn--/lib/builtins.opt.tahiti.bc
/usr/bin/ld: cannot find -ledit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:13: recipe for target 'utils/prepare-builtins' failed
make: *** [utils/prepare-builtins] Error 1
make: *** Waiting for unfinished jobs....
=> ERROR: libclc-git-20141115_2: failed to run do_build() at line 14.
```

**Comment by xtraeme** [comment]
This is **unrelated** to what you are saying. libclc-git is broken.

So next time clarify what's the exact issue rather than opening useless PRs.

**Comment by pulux** [comment]
sorry
