### ISSUE TITLE
gparted doesn't start from the lxqt menu

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#11110]
### System

* xuname:  `Void 4.14.15_1 i686 GenuineIntel uptodate rFFFF`

* package:  `gparted-0.30.0_1`

### Expected behavior
It should be possible to start `gparted` from the `lxqt` menu...

### Actual behavior
It doesn't work. 😕 
Today I reinstalled a new system, using the `void-live-i686-lxqt` ISO.
These packages are installed:
````
[*] polkit-0.113_2
[*] polkit-qt5-0.112.0_2
[*] lxqt-policykit-0.12.0_1
[*] lxqt-sudo-0.12.0_1
````
After that I installed `gparted`, but it doesn't start from the `lxqt` menu.
So, I tried to rebuild the package with `xbps-src`, just to see... and I noticed these lines:
````
checking pkg-config is at least version 0.9.0... yes
checking for pkexec >= 0.102... not found
checking for gksudo... no
checking for gksu... no
checking for kdesudo... no
checking for xdg-su... no
````
It looks like something is missing... 🤔 

### Steps to reproduce the behavior
Just download & install a live ISO, then install `gparted` & try to run it from the `lxqt` menu.

**Comment by Piraty** [comment]
It needs a mechanism to get root's permission.
```
xbps-query -Rf gparted | grep -i "bin"
/usr/bin/gparted
/usr/bin/gpartedbin
/usr/bin/gparted-pkexec
```
Starting `gparted`, it complains about not having root's permission in an info-box.
But `gparted-pkexec` works on my system, and this should work on void-live too (void-live has a special [polkit file](https://github.com/voidlinux/void-mklive/blob/master/dracut/vmklive/adduser.sh#L40-L50)).
This means either `/usr/share/applications/gparted.desktop` could be adapted to use the `-pkexec`-version or `gparted` could be recompiled with one of your mentioned missin mechanisms provided (probably adding it's `*-devel` variant to `makdepends` should be enough) and configure should find it.

**Comment by cr6git** [comment]
I can run `sudo gparted` from the terminal, no problem with that.
I'm talking about the `gparted` icon in the `lxqt` menu, which corresponds to:
`/usr/share/applications/gparted.desktop`, which runs:

````
Exec=/usr/bin/gparted %f
Icon=gparted
Terminal=false
Type=Application
````
If you look at `/usr/bin/gparted` it's just a long script, not the real binary.

And `/usr/bin/gparted-pkexec` is different from the `.desktop` file:

````
#!/bin/sh
pkexec --disable-internal-agent "/usr/bin/gparted" "$@"
````

**Comment by cr6git** [comment]
Oops! I clicked the wrong button "Close and comment", I'm sorry.

**Comment by newbluemoon** [comment]
There is an `INSTALL.msg` which I think addresses this issue:

```
To run gparted through a desktop menu, a polkit authentication agent
must be running; for GNOME and KDE users it should be already installed,
otherwise you can install *lxpolkit* (from the lxsession package), which
is a lightweight polkit authentication agent.
```

**Comment by cr6git** [comment]
As mentioned earlier, these packages are installed:
````
[*] polkit-0.113_2
[*] polkit-qt5-0.112.0_2
[*] lxqt-policykit-0.12.0_1
[*] lxqt-sudo-0.12.0_1
````
I don't think I need another polkit / policykit.

**Comment by newbluemoon** [comment]
@cr6git sorry, I read from bottom to top and overlooked those lines in the initial post ;)
However, the `INSTALL.msg` appears to be wrong then, too.
I don’t know enough about polkit to give any advice, but maybe you could add a build option to use e.g. `gksudo` (as a workaround)?

**Comment by cr6git** [comment]
Looking at the recent [changes](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/gparted) for `gparted` in Arch, we can see something interesting in [this commit](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/gparted&id=9d9cf9e27ec80e902f0f1dd4378973201cba9537).
They were using a PKGBUILD very similar to Void's [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/gparted/template), but they modified it to remove things related to polkit, precisely! Have you noticed?

**Comment by newbluemoon** [comment]
I think the `sed` command in the template needs to be adjusted because `gparted.desktop.in.in` changed.
Currently it’s

```
sed -i "s:@gksuprog@ @installdir@/gparted %f:@installdir@/gparted-pkexec %f:g" gparted.desktop.in.in
```

but should be something like

`sed -i "s:@bindir@/gparted %f:@bindir@/gparted-pkexec %f:g" gparted.desktop.in.in`

**Comment by cr6git** [comment]
@newbluemoon yes! it was just that! 😃
