### ISSUE TITLE
Steam unable to log in

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-packages#1115]
So it appears that logging in to Steam using Void Linux is not possible anymore, at least not on the platforms on which I have tested this (x86-64, different machines)

To reproduce:

Fresh Void Linux base installation:

    # xbps-install void-repo-multilib void-repo-nonfree void-repo-multilib-nonfree
    # xbps-install -Su
    # xbps-install xorg xfce4 sddm zenity glibc-32bit libGL-32bit # this is a large one, take a break
    # xbps-install steam
    # useradd -m -G wheel,video username
    # passwd username
    # ln -s /etc/sv/sddm /var/service && reboot

Two additional steps are required for VirtualBox:

    # xbps-install virtualbox-ose-guest virtualbox-ose-guest-dkms
    # ln -s /etc/sv/vboxservice /var/service

Then log in, start Steam, and wait for it to finish downloading shit.
It will not load, due to #953 , which can be solved by running the following command as the user logged in (not root):

    $ rm -f $HOME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6

Then relaunch Steam, and attempt log in.
You should be met with a dialog saying: "Steam is having trouble connecting to the Steam servers", with two dialog buttons: "RETRY CONNECTION", and "CANCEL".

**Comment by dominikh** [comment]
I didn't test in a fresh VM, but on my existing system with an up-to-date version of Steam, and it's working fine.

**Comment by logenkain** [comment]
On Fri, Mar 13, 2015 at 11:35:45AM -0700, Dominik Honnef wrote:
> I didn't test in a fresh VM, but on my existing system with an up-to-date version of Steam, and it's working fine.
^this

Last reinstall I did was probably less than a month ago and I've had no
problems.  Though that one was installed with the XFCE image.

**Comment by necrophcodr** [comment]
Steam itself does not provide any useful debugging information when the error occurs, so on that side it's pretty much blank.
Attempting, on the machines I've tried this, to do a `steam --reset` has not worked either, even after deleing the `~/.local/share/Steam` directory.
So it would appear that something else is missing in this process, although I am not certain what.
I will note however that Steam HAS been working previously. This error only started occuring to me about (at most) two weeks ago.

**Comment by thypon** [comment]
I have the exactly same problem. I tried to put in a network namespace, seccomp/caps also to hide other processes but there is this problem since 3/4 days.

**Comment by xtraeme** [comment]
I'm able to reproduce the issue. I think this is related to libressl.

LD_PRELOADing libssl from ubuntu bootstrap makes it login successfully.

**Comment by necrophcodr** [comment]
@xtraeme how exactly do you work around it? I attempted, from what you wrote, to do the following:

    # LD_PRELOAD=$HOME/.local/share/Steam/ubuntu12_64/steam-runtime/i386/usr/lib/i386-linux-gnu/libssl3.so steam

Or

    # LD_PRELOAD=$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libssl3.so steam

However, to no avail. Result appears the same. What work around do you use?

**Comment by xtraeme** [comment]
Here's a working wrapper:

```
[juan@leysa ~]$ cat run-steam.sh 
#/bin/sh

STEAM32_BSTRAP=$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu
STEAM64_BSTRAP=$HOME/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu

LD_PRELOAD="$STEAM32_BSTRAP/libcrypto.so.1.0.0:$STEAM32_BSTRAP/libssl.so.1.0.0" steam
[juan@leysa ~]$
```

**Comment by necrophcodr** [comment]
I can confirm that the above posted wrapper by @xtraeme works around the issue for me.

That is, the issue is still present, but as of present the above work around can be used as a temporary fix.

**Comment by thypon** [comment]
Works for me. Could we push this in the repo?

**Comment by necrophcodr** [comment]
@thypon 
It is possible to patch the /usr/bin/steam shell script, however it seems this issue could probably be solved in a more efficient way.
It is also possible that this is an issue that should be solved upstream, however I doubt that would actually happen. One solution to this issue could be, for instance, to simply use the `STEAM_RUNTIME` environment variable, and fix issues that it would cause.
However, that is not a pleasant solution, even if it could be the most solid one.

**Comment by thypon** [comment]
Someone has debugged this problem? Maybe it is an libressl/openssl problem.

**Comment by necrophcodr** [comment]
@thypon 

It is. LibreSSL and OpenSSL are not API or ABI compatible.
