### ISSUE TITLE
cinnamon-screensaver fails to start

### ISSUE THREAD

**Issue by abenson** [voidlinux/void-packages#11223]
### System

* xuname:  Void 4.14.15_3 x86_64 GenuineIntel uptodate rFFFF
* package:  cinnamon-screensaver-3.6.1_1

### Expected behavior

cinnamon-screensaver daemon launches, can lock the screen.

### Actual behavior

cinnamon-screensaver fails.

~~~
$ cinnamon-screensaver
Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py", line 17, in <module>
    from util import utils
  File "/usr/share/cinnamon-screensaver/util/utils.py", line 7, in <module>
    import xapp.os
ModuleNotFoundError: No module named 'xapp'
~~~

**Comment by Johnnynator** [comment]
Damn, I new that i missed to check something.
Does installing the xapps package help? I will check it later if not.

**Comment by abenson** [comment]
I have xapps installed, it does not help.

**Comment by Johnnynator** [comment]
The problem is that our xapps doesn't have python support. I'm working on updating the template

**Comment by Johnnynator** [comment]
https://github.com/linuxmint/python-xapp is needed, I will make a PR for it.

**Comment by Johnnynator** [comment]
You can check if my https://github.com/Johnnynator/void-packages/tree/cinnamon-screensaver works for you. For me it just lets cinnamon crash.

**Comment by abenson** [comment]
That works fine here, and fixes the issue with screensaver. Not sure about
the crash on your end?

--
AndrewB
Knowing is Half the Battle.

**Comment by Johnnynator** [comment]
I assumed that it was specific to my system, so I will make a PR for now and investigate my issue later.
