### ISSUE TITLE
vlc: build deps missing

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1134]
vlc need to build additional pkgs in repo:

xvidcore,  x265, lame, libvp, libcdio-paranoia

**Comment by xtraeme** [comment]
Do you mean additional dependencies instead? because it builds just fine.

**Comment by pulux** [comment]
if build local an if the local repo miss these pkgs, build end with error.
```
MISSING: libvpx>=1.0.0_1
MISSING: libcdio-paranoia>=10.2_1
Transaction aborted due to unresolved dependencies.
[DEBUG] [pkgdb] released ok.
=> ERROR: Please see above for the real error, exiting...
```
if the repo has these pkgs, build runs fine.

**Comment by xtraeme** [comment]
so how about sending patches?

**Comment by xtraeme** [comment]
Anyway looks like your issue is that you are making clean builds.

Before building a package, it's assumed that you should run `./xbps-src clean`.

**Comment by pulux** [comment]
you are right
