### ISSUE TITLE
'xlint' says strange things

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#11397]
### System

* xuname:  `Void 4.15.1_1 x86_64-musl GenuineIntel uptodate rFFFFFFFFFFFFFFF`
  *output of ``xuname`` (part of xtools)*
* package:  `xtools-0.49_1`
  *affected package(s) including the version*

### Expected behavior
`xlint` should not complain about the `make_check_target` variable.
### Actual behavior
`xlint` keeps complaining that `make_check_target` is a custom variable!

### Steps to reproduce the behavior
I found this while I was trying to update [expect](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/expect/template) to 5.45.4...
````
$ xlint srcpkgs/expect/template
srcpkgs/expect/template:14: custom variables should use _ prefix: make_check_target="test"
````

But why??
It should be correct, according to: `common/build-style/gnu-configure.sh`
````
#
# This helper is for templates using GNU configure scripts.
#
do_check() {
	if [ -z "$make_cmd" ] && [ -z "$make_check_target" ]; then 
		if make -q check 2>/dev/null; then
			:
		else
			if [ $? -eq 2 ]; then
				msg_warn 'No target to "make check".\n'
				return 0
			fi
		fi
	fi

	: ${make_cmd:=make}
	: ${make_check_target:=check}

	${make_cmd} ${make_check_args} ${make_check_target}
}
````
I can **see** `${make_check_target}`

**Comment by Anachron** [comment]
@cr6git xlint is a tool from [xtools](https://github.com/chneukirchen/xtools) not from `void-packages`.
