### ISSUE TITLE
google-fonts-ttf should provide conflicted packages

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#11402]
google-fonts-ttf conflcits with 5 font packages, and noto-fonts-ttf conflicts with google-fonts-ttf.
google-fonts-ttf should `provides=` these to allow users to source these fonts from any package.

(plasma-integration depends on noto-fonts-ttf)

**Comment by ebfe** [comment]
Not sure if `provides=` is the right mechanism. According to https://github.com/voidlinux/void-packages/pull/4977  at least the separately packaged noto-fonts-ttf are more complete than the fonts in google-fonts-ttf. Maybe remove the files from google-fonts-ttf and `depend=` on the individual font packages?

**Comment by asergi** [comment]
Sorry for the delay, I missed this somehow. I added `noto-fonts-ttf` to `depends` just like `cantarell-fonts` (the GNOME font). Thanks.

Anyway, I don't think google-fonts-ttf should provide or depend on the conflicting packages (exceptions aside), the package itself would lose its meaning.
