### ISSUE TITLE
Liborcus update broke LibreOffice

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#11413]
### System

* xuname:  
Void 4.14.15_3 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  libreoffice-5.4.4.2_1

### Expected behavior
Being able to install libreoffice

### Actual behavior
```
libreoffice-5.4.4.2_1: broken, unresolvable shlib `liborcus-0.12.so.0'
libreoffice-5.4.4.2_1: broken, unresolvable shlib `liborcus-parser-0.12.so.0'
Transaction aborted due to unresolved shlibs.
```

### Steps to reproduce the behavior
`xbps-install libreoffice`

### Additionally
Commit https://github.com/voidlinux/void-packages/commit/bec1494615dc715bf1f4a68ef7a50183c4cf4e34 seems to have broken LibreOffice (updates liborcus to 0.13.2 while libreoffice still looks for 0.12-files.

**Comment by Anachron** [comment]
ping @pullmoll

**Comment by Hoshpak** [comment]
Libreoffice build is still ongoing: https://build.voidlinux.eu/waterfall
