### ISSUE TITLE
Package Request: prosody

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#1145]
Prosody is a fully featured XMPP server written in lua. I am trying to set it up with void linux on my raspberry pi b+ but a package would be much appreciated. I'm not sure how to package it myself.  

Dependencies: https://prosody.im/doc/depends  

Source code: https://prosody.im/doc/installing_from_source

**Comment by Duncaen** [comment]
@silvernode i added a prosody template. It would be great if you contribute changes to the configuration back, we need some sane defaults.

**Comment by silvernode** [comment]
Thanks for packaging this. in terms of the configuration can you be more specific?

**Comment by xtraeme** [comment]
xbps-query -R prosody
