### ISSUE TITLE
Firefox on musl crashes on password fields

### ISSUE THREAD

**Issue by Johnnynator** [voidlinux/void-packages#11532]
### System

* xuname:  
  * ``Void 4.14.16_1 x86_64-musl GenuineIntel uptodate rrrnDFFFFFFFFFFFFFFFF``
* package:  
  * firefox>=57*

### Expected behavior
Beeing able to input a password into a pw filed

### Actual behavior
Crashes once you even click on that field

### Steps to reproduce the behavior
Go to any site with a password field and try to input something

Can be worked around by disabling the sandbox https://github.com/gentoo/musl/issues/44 .

Also it seems to work on Alpine Linux (only quickly tested in an chroot), so it may be usefull to check the additional patches they use. https://github.com/alpinelinux/aports/tree/master/testing/firefox

**Comment by anarchpenguin** [comment]
I am unable to reproduce these crashes, when someone can actually give me a detailed step procedure to reproduce them I will be more then happy to track down and fix the problem. I just signed in with 59.0_beta11 from mozilla overlay and have no trouble what so ever.

**Comment by Vaelatern** [comment]
any plugins used?

**Comment by Johnnynator** [comment]
Nope happens with a clean installation.

**Comment by Johnnynator** [comment]
It seems to crash also when I try to open any RSS feeds.

**Comment by Uramekus** [comment]
If you disable seccomp it will stop crashing as a workaround, that said I'm not using Musl nowadays so i cant help on that one.

**Comment by Johnnynator** [comment]
I know, I even mentioned it in my initial post. I'm waiting ATM for the release of ff59 (this Tuesday afaik) and will see if it is still broken then.

**Comment by Johnnynator** [comment]
Log with MOZ_SANDBOX_LOGGING=1
https://gist.github.com/Johnnynator/8f9b15c405c60000fcf53f066f40d0d9

**Comment by Johnnynator** [comment]
resolved by removing dconf.

**Comment by cr6git** [comment]
Same problem for me using `firefox-59.0.2_1`

**Comment by stefson** [comment]
How do you remove dconf, is it done at compile time or via some env values at runtime?

**Comment by Johnnynator** [comment]
I was talking about removing the dconf package (gnome-base/dconf in gentoo. just dconf here in void).
But it may not be suitable for everyone and is actually not a really a good solution just a workaround that worked for me.
