### ISSUE TITLE
LXDM: system lookup error with harfbuzz 1.7.5

### ISSUE THREAD

**Issue by BroFreedom** [voidlinux/void-packages#11560]
### System

* xuname:  Void 4.14.18_1 x86_64 GenuineIntel notuptodate rrrrmmnDD
* package:  lxdm-0.5.3_1

### Expected behavior

LXDM appear after boot and allow to login

### Actual behavior

LXDM not appear at all and show this error in `/var/log/lxdm.log`:

`/usr/libexec/lxdm-greeter-gtk: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var`

### Steps to reproduce the behavior

Just need to update the harfbuzz library to 1.7.5.

**Comment by maxice8** [comment]
Works fine here.

**Comment by pullmoll** [comment]
First make sure your setup is up to date with `sudo xbps-install -Su`.
If the error goes away, close this issue, if not, we'll have to track down the cause.

**Comment by BroFreedom** [comment]
My system was fully updated with the latest packages when I've wrote this issue. So, this error still present.

**Comment by cavalier911** [comment]
glibc x86_64
lxdm-0.5.3_1  libharfbuzz-1.7.5_1  freetype-2.9_2
lxdm appears, log in works.
Other forums indicate the error is caused by outdated freetype

**Comment by BroFreedom** [comment]
I've forget about freetype... So, the error is caused by the presence of freetype-2.8. Upgrade to freetype 2.9 solve the problem.

Sorry for the convenient. I close the issue.
