### ISSUE TITLE
Firefox: update to 58.0.2 

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#11572]
````
[rj@voidlinux:~/void-packages]$ ./xbps-src update-check firefox 
firefox-58.0.1 -> firefox-58.0.2

**Comment by cavalier911** [comment]
An out-of-date browser is a security risk. 
The father of void linux, JuanRP a.k.a. xtraeme@voidlinux@voidlinux.eu  is no longer involved in the daily operation and maintenance of void linux. 
He is the maintainer of firefox and most of the packages in the repository. 
Who has volunteered to maintain/update his packages if he is ignoring his update list?

**Comment by maxice8** [comment]
On Sun, Feb 11, 2018 at 02:02:34PM -0800, cavalier911 wrote:
> An out-of-date browser is a security risk.
> The father of void linux, JuanRP a.k.a. xtraeme@voidlinux@voidlinux.eu is no
> longer involved in the daily operation and maintenance of void linux.
> He is the maintainer of firefox and most of the packages in the repository.
> Who has volunteered to maintain/update his packages if he is ignoring his
> update list?
> 
> 

Nobody, people just update as they see it, just make a PR

**Comment by Vaelatern** [comment]
@cavalier911 check the commit logs for firefox. People update stuff.

**Comment by cr6git** [comment]
@Vaelatern People update stuff, but it's not merged. See the long list of PRs... What's going on?

**Comment by Vaelatern** [comment]
We are busy. It helps when we check stuff and it's already good-to-merge, that gives us more time to check more PRs.
