### ISSUE TITLE
clang compiler produces huge volume of warnings

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#1158]
Hi

After a -Syu yesterday, the clang compiler produces a huge volume of warnings when the -Weverything
flag is specified. gcc seems to work OK. wgetpaste didn't so I put the error file here:
http://www.5b4az.org/clang.txt

**Comment by Gottox** [comment]
We won't disable warnings in our clang, all the more if you explicitly enable them with `-Weverything`.
