### ISSUE TITLE
vkpurge: misleading example when run without arguments

### ISSUE THREAD

**Issue by tac1ica** [voidlinux/void-packages#11638]
When run without arguments, vkpurge displays a misleading usage example:

`$ vkpurge`
`Usage: vkpurge <target> [<version>]`
(snip)
`Example:`
`	$ vkpurge list`
`	$ vkpurge rm 2.6.39.2`

The last line is wrong and should be

`	$ vkpurge rm 2.6.39_2`

instead.

**Comment by cr6git** [comment]
IMHO, for the example we should replace `2.6.39_2` with a more recent kernel release.
Why not `4.9.81_1` ?
