### ISSUE TITLE
licensechecker: wrong license

### ISSUE THREAD

**Issue by m-cz** [voidlinux/void-packages#11648]
* package:  
  licensechecker-1.2.0

### Expected state

https://github.com/boyter/lc/releases
>Now dual licensed under MIT and Unlicense

### Actual state

https://github.com/voidlinux/void-packages/blob/21f06ba5c67303926aa60dba11f99a2b05fa050b/srcpkgs/licensechecker/template#L11

[insert obligatory star wars prequel meme]

**Comment by Gottox** [comment]
![](https://media.giphy.com/media/7pHTiZYbAoq40/giphy.gif)

**Comment by Vaelatern** [comment]
aa9ef4d29b
