### ISSUE TITLE
Nvidia-384.98: DKMS module fails only on 4.15 kernel series.

### ISSUE THREAD

**Issue by chmod77** [voidlinux/void-packages#11660]
**### System**
Platform: x86_64
Kernel: linux4.15-4.15.3_1

**package:**  nvidia-384.98_3

**### Actual behavior**
nvidia DKMS module fails to build only on 4.15 series

**### Steps to reproduce the behavior**
sudo xbps-install -S linux4.15
sudo xbps-install -S linux4.15-headers

**What i Found:**
_"The problem seem related to Kernel Page Table Isolation is enabled for Meltdown prevention..."_
**The NVIDIA 390 Driver Is Playing Nicely With Linux 4.15 Kernel - Phoronix**
https://www.phoronix.com/scan.php?page=news_item&px=Linux-4.15-NVIDIA-390-Driver

**What i belive:**
1 - Upgrade nvidia to the new long lived stable series.  nvidia-390 (Pull is ready)
https://github.com/voidlinux/void-packages/pull/11403
or 
2 - Apply a patch and continue on 384 series

**Comment by fallenwizard** [comment]
https://github.com/voidlinux/void-packages/pull/11403

**Comment by chmod77** [comment]
[Resolved] #Nvidia works like a charm. Thanks for the updated! 

https://github.com/voidlinux/void-packages/pull/11403
