### ISSUE TITLE
Package Request : Flowblade - video editor

### ISSUE THREAD

**Issue by JesSch1023** [voidlinux/void-packages#11664]
Video Editor that uses G'MIC for processing/effects. 

"Flowblade is currently a 100% script application" Interesting!

https://jliljebl.github.io/flowblade/     Main Site

https://github.com/jliljebl/flowblade     GitHub

https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/DEPENDENCIES.md     Depends

I am pretty sure all of the dependencies are available in the Void Repos.

**Comment by maxice8** [comment]
i'll take a look

**Comment by maxice8** [comment]
@lemmi please close
