### ISSUE TITLE
LibreSSL 2.5.5 has a year 2038 problems affecting Mumble/Murmur

### ISSUE THREAD

**Issue by mkrautz** [voidlinux/void-packages#11675]
This is just an FYI.

A few users have reported to the Mumble project that the Murmur packages in 32-bit Void Linux (x86 and arm) will sometimes cause X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD errors when clients connect to the server.

TL;DR: Mumble and Murmur use self-signed certificates with long lifetimes. Certificates generated in 2018 will have notAfter dates in 2038. Older versions of LibreSSL (including Void's version 2.5.5) use time_t on Linux, which is 32-bit on 32-bit architectures of Linux. That is what causes the error.

My initial upstream bug report, in which it turned out the bug was already fixed in the tree (and in quite a few releases):
https://github.com/libressl-portable/portable/issues/389

This is upstream's fix:
https://github.com/libressl-portable/openbsd/commit/362ffef32c0fcae703d57838e9f5704240a63213

Note that the fix is included in libressl-v2.6.4, libressl-v2.6.3, libressl-v2.6.2 and libressl-v2.6.1.

I hope someone can bump the LibreSSL package to get this fixed. Thanks!

**Comment by ebfe** [comment]
Should be fixed with 20d23bbc9b4dd03f7f6387dbece18a25a83204eb
