### ISSUE TITLE
Package resquest: popcorn time

### ISSUE THREAD

**Issue by heartb1t** [voidlinux/void-packages#11717]
A torrent streamer of films. Under GPLv3.

Their site: https://popcorntime.sh
Github: https://github.com/popcorn-official/popcorn-desktop

**Comment by cr6git** [comment]
Did you look at [popcorn-desktop#quickstart](https://github.com/popcorn-official/popcorn-desktop#quickstart) ?
I don't see how to build this program.

**Comment by fallenwizard** [comment]
Popcorn Time is considered illegal in many juridictions, so please be aware of that if you want to package it for Void.

**Comment by fallenwizard** [comment]
IANAL but Popcorn Time is illegal in many juristdictions. The project will be in legal hot water if they accept this.

**Comment by chneukirchen** [comment]
Why would it be less illegal than providing transmission and mpv?

**Comment by heartb1t** [comment]
I don't think it infringes copyright in anyway, since they are not profiting off the shared media. Many other distributions provide it on their official repositories, I don't see why it would be a problem for the Void project, but I respect the decision and understand why you would think so.

**Comment by ErinVoid** [comment]
I would hope Void does not package this. The difference to transmission and mpv is their primary use is not to infringe copyright albeit they may be used for that purpose.

**Comment by heartb1t** [comment]
Neither is popcorn's time primary use. It would be copyright infringement if they profited from the movies, but that's not the case. I'm speaking by my country and my laws, so I understand why there is fear of adding it to the repos, it might be illegal in some countries. I'm closing the issue, thank you all for your responses.
