### ISSUE TITLE
Package Request: Plasma Vault

### ISSUE THREAD

**Issue by RaphyJake** [voidlinux/void-packages#11748]
KDE applet / application that lets you create quickly accessible encrypted folders. [ You can read more about it here.](https://www.omgubuntu.co.uk/2017/06/plasma-vault-create-encrypted-folder-linux)

https://github.com/KDE/plasma-vault

PS: I know it's a bad time to suggest this package considering that at the moment plasma is broken thanks to qt 5.10, but posting anyway just in case someone smarter than me was interested

**Comment by gspe** [comment]
I've just made a pull request #11863 for this package
