### ISSUE TITLE
qt5-styleplugins broken?

### ISSUE THREAD

**Issue by ncmprhnsbl** [voidlinux/void-packages#11768]
### System

* xuname:  
Void 4.14.19_1 x86_64 GenuineIntel uptodate rrFFF

* package:  
  qt5-styleplugins

### Expected behavior
sets qt5 theme to match gtk2 via enviroment variable: QT_QPA_PLATFORMTHEME='gtk2'

### Actual behavior
fails to set qt5 theme to match gtk2

### Steps to reproduce the behavior
see above

hopefully just needs to be rebuilt against the new qt5 (5.10)

**Comment by pullmoll** [comment]
Does it work again for you?

**Comment by ncmprhnsbl** [comment]
yes, working now, thank you.
