### ISSUE TITLE
 qt5-styleplugins is missing GTK theme

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#11839]
### System
Linux pc007 4.14.19_1 # 1 SMP PREEMPT Wed Feb 14 10:54:30 UTC 2018 x86_64 GNU/Linux
* xuname:  
Void 4.14.19_1 x86_64 GenuineIntel uptodate rr
* package:  
 qt5-styleplugins-5.0.0_5

### Expected behavior
qt5-styleplugins contains GTK theme
### Actual behavior
After latest QT update GTK theme is missing/broken.
All QT5 apps lost their GTK themeing.
### Steps to reproduce the behavior
In QT5-settings set theme as GTK -> click apply.
Theme is not applies in preview window.

**Comment by cr6git** [comment]
The last and only release 5.0.0 is very old (Jan 31, 2014).
See the list of [commits](https://github.com/qt/qtstyleplugins/compare/v5.0.0...master) since this tag.
We probably need to update the package.

**Comment by pullmoll** [comment]
For me and @ncmprhnsbl this works after the update (see #11768).
Is there any error output or is it that just the theme display won't change?

**Comment by direwolfie** [comment]
qt5ct now crashes when I select GTK2.
This is what appears in console:
`(qt5ct:7157): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'
(qt5ct:7157): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(qt5ct:7157): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
(qt5ct:7157): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(qt5ct:7157): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(qt5ct:7157): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(qt5ct:7157): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(qt5ct:7157): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'
(qt5ct:7157): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(qt5ct:7157): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(qt5ct:7157): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(qt5ct:7157): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault`

**Comment by ncmprhnsbl** [comment]
probably qt5ct also needs rebuilding..  
(i don't have it. i just use environment variable: QT_QPA_PLATFORMTHEME='gtk2' )

**Comment by pullmoll** [comment]
revbump can't hurt...

**Comment by direwolfie** [comment]
> probably qt5ct also needs rebuilding..
> (i don't have it. i just use environment variable: QT_QPA_PLATFORMTHEME='gtk2' )

Installing the new build of qt5ct fixed the issue for me.
Huge thanks!

QT_QPA_PLATFORMTHEME="qt5ct" - works better for me, as I can set the fonts so that they are antialiased/smooted properly.
