### ISSUE TITLE
SMPlayer does not start after latest QT update

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#11838]
### System
Linux pc007 4.14.19_1 # 1 SMP PREEMPT Wed Feb 14 10:54:30 UTC 2018 x86_64 GNU/Linux
* xuname:  
 Void 4.14.19_1 x86_64 GenuineIntel uptodate rr
* package:  
smplayer-18.1.0_1

### Expected behavior
SMPlayer starts with no issue.
### Actual behavior
SMPlayer does not start with errors:

` QObject::connect: No such signal MyApplication::commitDataRequest(QSessionManager)
This is SMPlayer v. 18.1.0 (revision 8885) running on Linux
(smplayer:26024): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplayManager'
(smplayer:26024): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(smplayer:26024): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
(smplayer:26024): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(smplayer:26024): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(smplayer:26024): GLib-GObject-WARNING **: invalid (NULL) pointer instance
(smplayer:26024): GLib-GObject-CRITICAL **: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
(smplayer:26024): GLib-GObject-WARNING **: cannot register existing type 'GdkDisplay'
(smplayer:26024): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(smplayer:26024): GLib-GObject-CRITICAL **: g_type_register_static: assertion 'parent_type > 0' failed
(smplayer:26024): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(smplayer:26024): GLib-GObject-CRITICAL **: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed 
Segmentation fault`
### Steps to reproduce the behavior
The issue occured after the latest update of QT libs.
1. Make sure system is uptodate
2. Start SMPlayer

**Comment by direwolfie** [comment]
Possibly related issue  #11839.

**Comment by Hoshpak** [comment]
I cannot reproduce this issue. Smplayer starts just fine on my system which is also up-to-date. It is very possible however that smplayer - as any software that depends on qt5 - should be rebuilt for the new qt5 version. This will happen anyway once #11807 is merged. You could try to rebuild the package yourself and install it on your system to check if that resolves the issue.

**Comment by direwolfie** [comment]
On removing config, it works.
Issue seems to be due to lack of GTK2 theme that was set in SMPlayer settings - #11839.
