### ISSUE TITLE
pdftk requires libgcc-6.3.0_5, that is missing

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#11832]
### System

* xuname:  `Void 4.15.4-chrysalis x86_64 GenuineIntel uptodate rrrmFF`

* package:  `pdftk-2.02_3`

### Expected behavior
Being able to install it.

### Actual behavior
The following error:
```
MISSING: libgcc-6.3.0_5
Transaction aborted due to unresolved dependencies.
```

### Steps to reproduce the behavior
`xbps-install pdftk`

**Comment by pullmoll** [comment]
`pdftk` was removed from the source tree because it depends on the no longer existing GNU java (gcj).
The xbps packages in the repository should have been / be removed as well.
