### ISSUE TITLE
owncloudclient out of date (2.3.4 --> 2.4.0)

### ISSUE THREAD

**Issue by oliver-cfc** [voidlinux/void-packages#11861]
repo version: https://download.owncloud.com/desktop/stable/owncloudclient-2.3.4.tar.xz
current version: https://download.owncloud.com/desktop/stable/owncloudclient-2.4.0.tar.xz

Current client gives a nagging notification saying 'update using your distro repo' (or something similar)

**Comment by m-cz** [comment]
There's already a PR #11561

**Comment by pullmoll** [comment]
14d5707d95541dadec165f2d50288ee843c74320
