### ISSUE TITLE
Build more packages from source

### ISSUE THREAD

**Issue by nmeum** [voidlinux/void-packages#1187]
Some packages are currently not built from source. Examples:
- ~~ghc~~
- libreoffice
- texlive
- lightzone
- ...

For obvious reasons it would be great if more of them would be built from source instead.

**Comment by xtraeme** [comment]
- ghc is built from source, I think you are confusing it with ghc-bin.
- the others are named `foo-bin` exactly for this reason, because they contain the binaries.

**Comment by chneukirchen** [comment]
Closing this, libreoffice and lightzone are built from source, and texlive is a whole other story.
