### ISSUE TITLE
redshift: default deps

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1188]
redshift has in template huge deps:

`"GConf-devel libXxf86vm-devel pygtk-devel python-xdg geoclue-devel>=0.12.0_7"`

Who need GeoClue and GConf in Default, redshift needs only `libXxf86vm-devel` to build others are optional.

What is the best way to provide the Minimal-Version?

**Comment by xtraeme** [comment]
Split the UI into a -gtk subpackage.

**Comment by pulux** [comment]
see #1195
