### ISSUE TITLE
Libressl 2.6 Updates

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#11911]
* [ ] FreeRADIUS
* [ ] Ice
* [x] MEGAsdk
* [x] android-tools
* [ ] bacula-common
* [x] badvpn
* [x] balsa
* [x] bind
* [x] bitchx
* [x] bitcoin
* [ ] bitlbee
* [x] boinc
* [x] borg
* [x] botan
* [ ] burp-server
* [x] burp2-server
* [ ] ca-certificates
* [x] calibre
* [x] cargo
* [x] ccnet
* [x] cgit
* [x] clamav
* [ ] collectd
* [ ] coturn
* [x] cryptsetup
* [x] crystal
* [x] ctpp2
* [x] curl
* [x] cyrus-sasl
* [x] dillo
* [x] dma
* [x] dovecot
* [x] easyrsa
* [ ] ecryptfs-utils
* [x] efl
* [x] eiskaltdcpp-qt
* [ ] ejabberd
* [x] elinks
* [x] encfs
* [ ] erlang
* [x] ettercap
* [x] facter
* [x] fdm
* [x] fetchmail
* [x] fossil
* [x] freerdp
* [ ] freshplayerplugin
* [x] gambit
* [x] gatling
* [x] gftp
* [x] git
* [x] git-crypt
* [x] git-series
* [ ] gkrellm
* [ ] glusterfs
* [x] godot
* [x] grub-customizer
* [x] gsoap
* [ ] gst-plugins-bad
* [ ] gst-plugins-bad1
* [ ] gwenhywfar
* [ ] h2o
* [x] haproxy
* [ ] hexchat
* [x] hfsprogs
* [ ] hitch
* [x] hostapd
* [ ] hplip
* [ ] httperf
* [ ] httrack
* [x] i2pd
* [ ] icecast
* [ ] icinga2
* [x] imapfilter
* [ ] inadyn
* [ ] inspircd
* [ ] ipmitool
* [ ] ipmiutil
* [x] iputils
* [x] irssi
* [x] isync
* [x] john
* [x] kea
* [x] keepalived
* [ ] kicad
* [ ] kvirc
* [ ] lastpass-cli
* [ ] ldapvi
* [x] ldns
* [x] lftp
* [x] libarchive
* [x] libesmtp
* [x] libetpan
* [x] libevent
* [x] libfetch
* [ ] libgda
* [x] libgit2
* [ ] libimobiledevice
* [ ] libmega
* [ ] libmongoose
* [ ] libmowgli
* [x] libostree
* [ ] libqtelegram-ae
* [x] libressl
* [x] libssh
* [x] libssh2
* [x] libstrophe
* [x] libtorrent
* [x] libtorrent-rasterbar
* [x] libu2f-host
* [x] libu2f-server
* [x] libucl
* [ ] libvncserver
* [ ] libwebsockets
* [x] lighttpd
* [x] links
* [x] linux4.14
* [x] linux4.15
* [x] litecoin
* [x] loudmouth
* [ ] lua51-luasec
* [ ] lua52-luasec
* [ ] luasec
* [x] lynx
* [ ] mailx
* [x] mairix
* [ ] marble
* [x] mariadb
* [ ] mbuffer
* [ ] megacmd
* [x] megatools
* [x] mit-krb5
* [ ] monero
* [ ] monero-core
* [ ] mongo-tools
* [x] mongodb
* [x] mongoose
* [ ] monit
* [ ] monitoring-plugins
* [x] mosh
* [ ] mosquitto
* [x] mpop
* [x] msmtp
* [x] mtree
* [ ] muchsync
* [x] mumble
* [ ] munge
* [x] mutt
* [ ] mutt-kz
* [x] mysql
* [ ] namecoin
* [x] neomutt
* [x] neon
* [x] net-snmp
* [x] netpgp
* [x] netsurf
* [ ] network-ups-tools
* [x] newsbeuter
* [x] nginx
* [x] ngircd
* [x] nix
* [x] nmap
* [x] nmh
* [x] nsd
* [x] ntp
* [x] nzbget
* [ ] open-isns
* [ ] open-vm-tools
* [ ] opendkim
* [x] openldap
* [x] openntpd
* [ ] opensc
* [x] opensmtpd
* [x] openssh
* [x] openvpn
* [x] openvswitch
* [x] opusfile
* [x] pam_ssh
* [ ] pen
* [ ] perl-Crypt-OpenSSL-Bignum
* [ ] perl-Crypt-OpenSSL-Random
* [x] perl-DBD-mysql
* [x] perl-Net-SSH2
* [x] perl-Net-SSLeay
* [x] pev
* [ ] pgadmin3
* [ ] phantomjs
* [x] php
* [x] pidgin-sipe
* [x] pjproject
* [x] pkcs11-helper
* [x] podofo
* [x] postfix
* [x] postgresql
* [x] prosody
* [x] pulseaudio
* [x] python
* [x] python-M2Crypto
* [x] python-cryptography
* [x] python-curl
* [x] python3
* [x] qca
* [x] qca-qt5
* [x] qingy
* [x] qt
* [x] qt5
* [x] qupzilla
* [x] qupzilla1
* [x] rdesktop
* [ ] rdis-git
* [x] retroshare
* [ ] rng-tools
* [x] rspamd
* [x] rtmpdump
* [x] ruby
* [x] rustup
* [x] s-nail
* [x] s3fs-fuse
* [x] s6-networking
* [x] scrypt
* [x] seafile-client-qt
* [x] seafile-libclient
* [x] serf
* [ ] sgfutils
* [ ] sitecopy
* [x] slrn
* [x] slurm-wlm
* [x] socat
* [x] spice
* [x] spice-gtk
* [ ] spiped
* [x] sqlcipher
* [x] squid
* [x] stunnel
* [x] swi-prolog
* [ ] swiften
* [x] sylpheed
* [x] synergy
* [x] sysdig
* [x] tcpdump
* [ ] tcpflow
* [ ] tectonic
* [ ] telepathy-salut
* [x] testssl.sh
* [x] thc-hydra
* [x] tinc
* [x] tlsdate
* [x] tnftp
* [x] tor
* [ ] tpm-tools
* [x] transmission
* [ ] trousers
* [x] ttyd
* [x] tvheadend
* [ ] ucspi-ssl
* [x] uget
* [x] umurmur
* [x] unbound
* [ ] vanitygen
* [ ] vboot-utils
* [ ] vde2
* [ ] virtualbox-ose
* [ ] virtuoso
* [x] vpn-ws
* [x] vsftpd
* [x] w3m
* [ ] warzone2100
* [ ] watchman
* [x] wget
* [x] wireshark
* [x] wpa_supplicant
* [x] wrk
* [ ] wvstreams
* [x] x11vnc
* [ ] xar
* [ ] xarcan
* [x] xbps
* [ ] xca
* [ ] xchat
* [ ] xorg-server
* [ ] yara
* [ ] ykpivmgr
* [ ] ympd
* [ ] zbackup
* [x] znc
* [x] zou

**Comment by maxice8** [comment]
gsoap has an update PR that can be used to rebuild against libressl: https://github.com/voidlinux/void-packages/pull/11183

**Comment by maxice8** [comment]
burp2-server has an update PR that can be used to rebuild against libressl: https://github.com/voidlinux/void-packages/pull/11386

**Comment by maxice8** [comment]
the seafile stuff has update PRs that can be used to rebuild against libressl: https://github.com/voidlinux/void-packages/pull/11355 https://github.com/voidlinux/void-packages/pull/11326

**Comment by maxice8** [comment]
newsbeuter is unmaintaned upstream, a maintained fork is available as newsboat, great opportunity to kill this package.

**Comment by maxice8** [comment]
rustup: https://github.com/voidlinux/void-packages/pull/11231

**Comment by maxice8** [comment]
ccnet: https://github.com/voidlinux/void-packages/pull/11349

**Comment by maxice8** [comment]
qt5 can make use of https://github.com/voidlinux/void-packages/pull/11113 , also kills protobuf update.

**Comment by maxice8** [comment]
newsbeuter should be ticked.

**Comment by maxice8** [comment]
python-M2Crypto should be ticked, https://github.com/voidlinux/void-packages/commit/848a38ce438f8c2518f03539bf82442f474f015d

**Comment by pullmoll** [comment]
The builders were lazy so I merged #11113 .. wait and see.

**Comment by Gottox** [comment]
Thanks @pullmoll :D

**Comment by ebfe** [comment]
All done except for #12094, #9146, #12087

**Comment by Gottox** [comment]
Thanks @ebfe! awesome work!
