### ISSUE TITLE
lxdm build broken on x86_64-musl

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#12015]
### Steps to reproduce the behavior

On x86_64-musl, build lxdm using gcc-7.3.0, install it, and try to connect.

Broken.

That's why I closed my pull request [#12003](https://github.com/voidlinux/void-packages/pull/12003).

**Comment by pullmoll** [comment]
*Broken* is a description which is not of too much use.
Does it segfault? Does it log error messages? Any further details?
You know you can `gdb lxdm` after installing the lxdm-dbg package to see where a crash happens.

**Comment by cr6git** [comment]
Forget what I said, it works perfectly! :sweat_smile: 
I probably missed something the last time... _nobody's perfect._
