### ISSUE TITLE
Package Request: CudaText 

### ISSUE THREAD

**Issue by 4goodapp** [voidlinux/void-packages#12054]
CudaText is a cross-platform text editor, fully open source, written in Lazarus:

https://github.com/Alexey-T/CudaText
www.uvviewsoft.com/cudatext/

**Comment by pullmoll** [comment]
From [How to compile program](http://wiki.freepascal.org/CudaText#How_to_compile_program)
+ install .lpk packages into Lazarus IDE (find all .lpk files, open them in IDE, install from Packages dialog)

We can't build packages which require an IDE for building. I fear you are on your own here.

**Comment by 4goodapp** [comment]
Thanks.
I think zou can close this issue now.
