### ISSUE TITLE
Missing gnome-3.16 packages

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#1207]
These packages are part of the gnome-3.16 release but not in void right now. See https://github.com/Gottox/void-packages/tree/gnome-3.16 for ongoing process. Help is welcome, too ;)

* [ ] accerciser
* [x] aisleriot
* [x] five-or-more
* [x] four-in-a-row
* [ ] gitg
* [ ] gnome-calendar
* [ ] gnome-characters
* [x] gnome-chess
* [ ] gnome-devel-docs
* [x] gnome-klotski
* [x] gnome-mahjongg
* [x] gnome-mines
* [x] gnome-nibbles
* [x] gnome-robots
* [ ] gnome-software
* [x] gnome-sudoku
* [ ] gnome-taquin
* [x] gnome-tetravex
* [ ] gnome-todo
* [x] hitori
* [x] iagno
* [x] lightsoff
* [x] orca
* [ ] polari
* [x] quadrapassel
* [x] swell-foop
* [x] tali

**Comment by pullmoll** [comment]
Updated the list with the games which are there now.
