### ISSUE TITLE
ghc-bin-7.8.4_1: broken, unresolvable shlib `libncursesw.so.5'

### ISSUE THREAD

**Issue by strake** [voidlinux/void-packages#1208]
Ghc 7.10.1 was released today, which I tried to build with xbps-src, which failed, so I tried to build ghc 7.8.4 which failed with same message. I did so with the latest void-packages in fresh masterdir.

Full build log [here](http://strake.me.uk/_files/logs/build/void-packages/16521.1.log).

/lib/libncursesw.so.5 is installed on host system.
I tried adding ncurses-libs to depends, makedepends, hostmakedepends, in vain.

**Comment by chneukirchen** [comment]
I have an updated template for ghc 7.10.1 and new ghc-bin, but pandoc
doesn't build on 7.10 yet, so I guess this will be delayed for a bit.
