### ISSUE TITLE
exa is not installable

### ISSUE THREAD

**Issue by TalviT** [voidlinux/void-packages#12091]
### System

* xuname:  
  Void 4.14.22_2 i686 GenuineIntel uptodate rF
* package:  
  exa-0.7.0_1 (A replacement for ls)

### Actual behavior
The package ist not installable.

### Steps to reproduce the behavior
Run `# xbps-install -S exa`
It outputs:
```
exa-0.7.0_1: broken, unresolvable shlib 'libhttp_parser.so.2.7.1'
Transaction aborted due to unresolvable shlibs.
```

**Comment by Duncaen** [comment]
The exa i686 build is currently broken.
https://github.com/ogham/exa/issues/301

**Comment by jnbr** [comment]
This can be fixed by running `cargo update --package datetime --precise 0.4.7` before `cargo build`. Not sure if this is a good idea.

**Comment by ebfe** [comment]
Could do it only on i686 only.

**Comment by ebfe** [comment]
Thanks @Duncaen @jnbr
