### ISSUE TITLE
Package Request: fox-devel 1.7 branch

### ISSUE THREAD

**Issue by jarbowski** [voidlinux/void-packages#1218]
http://www.fox-toolkit.org/

**Comment by xtraeme** [comment]
why? we do have the latest stable version.

**Comment by xtraeme** [comment]
Void does not package development versions unless a package needs it. I don't see any reason to pkg fox 1.7 (which is in development) right now.

**Comment by jarbowski** [comment]
It's because gogglesmm needs it.
