### ISSUE TITLE
cargo for musl - update distfile

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#12196]
The latest distfile https://repo.voidlinux.eu/distfiles/cargo-0.24.0-x86_64-unknown-linux-musl.tar.gz
needs libssl.so.43 and libcrypto.so.41 which are no longer available. It should probably be rebuilt against the latest libressl-2.6.

**Comment by chneukirchen** [comment]
Updating to cargo-0.25.0 should work too.
