### ISSUE TITLE
blind-1.1 is only available on musl for some reason

### ISSUE THREAD

**Issue by copyleftie** [voidlinux/void-packages#12221]
### System

* xuname:  
  `Void 4.15.7_BlackBox-copyleftie x86_64 GenuineIntel uptodate rFFF`
* package:  
  blind-1.1

### Expected behavior
`blind` should be available in the repo.

### Actual behavior
`blind` is available in the repo, but *only on musl*.

### Steps to reproduce the behavior
```
# run glibc Void and:

% xi blind
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
Unable to locate 'blind' in repository pool.
```

**Comment by Vaelatern** [comment]
The PR sucks. But it'll get built.
The makefile is particularly bad for a suckless project.
