### ISSUE TITLE
package request: mumble 1.3.0

### ISSUE THREAD

**Issue by scarybear** [voidlinux/void-packages#12281]
The development version of the VOIP client Mumble. I've tried compiling it myself but I run into issues using it with libressl

https://github.com/mumble-voip/mumble

My issue:

```
[hayden@x230 mumble]$ qmake -recursive main.pro
Reading /home/hayden/git/mumble/src/mumble_proto/mumble_proto.pro
Reading /home/hayden/git/mumble/3rdparty/speex-build/speex-build.pro
Reading /home/hayden/git/mumble/3rdparty/celt-0.7.0-build/celt-0.7.0-build.pro
Reading /home/hayden/git/mumble/3rdparty/celt-0.11.0-build/celt-0.11.0-build.pro
Reading /home/hayden/git/mumble/3rdparty/opus-build/opus-build.pro
Reading /home/hayden/git/mumble/src/mumble/mumble.pro
Project ERROR: pkg-config could not find package openssl
```

**Comment by maxice8** [comment]
> The development version of the VOIP client Mumble

any tempting reason to use the dev version ?

**Comment by scarybear** [comment]
Per person voice control is the big one, also some private servers just don't allow you to connect on the old version. I think just due to it eing in development for so long.

**Comment by Johnnynator** [comment]
Have you libressl-devel installed while attempting to compile mumble?

**Comment by scarybear** [comment]
Oh I see, I came over to Void from Arch so I just assumed devel packages were included with the main packages whoops. Anyway I still think it would be a decent adition to the main repos all considering.

**Comment by VargMon** [comment]
@scarybear, I also came from Arch, so I thought the `*-devel` files etc would already be there... but you can install `xtools` and then `xbps-install $(xnodev)` that should install all the missing -devel packages in your system. 

:*)

**Comment by VargMon** [comment]
Should @xtraeme do this???

**Comment by Gottox** [comment]
There's no 1.3 release yet.
