### ISSUE TITLE
Pulseaudio: add system wide service

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1230]
Headless server @ https://wiki.gentoo.org/wiki/PulseAudio

**Comment by nmeum** [comment]
Running Pulseaudio as a system wide service is actually not recommend. Doing so should only be considered in certain edge cases. Furthermore, additional users and groups are required to do so.

See also: The more or less official documentation http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/SystemWide/

**Comment by thypon** [comment]
In my configuration i need to use the audio in two different users.

**Comment by dominikh** [comment]
Feel free to write your own service ;) Void shouldn't provide for all the edge cases out there.
