### ISSUE TITLE
Package request: pragha

### ISSUE THREAD

**Issue by TalviT** [voidlinux/void-packages#12310]
"Pragha is a Lightweight Music Player for GNU/Linux."

Website: https://pragha-music-player.github.io/
Code repository: https://github.com/pragha-music-player/pragha

**Comment by VargMon** [comment]
This seems straightforward enough. BTW, cool media player

**Comment by VargMon** [comment]
:-)

**Comment by TalviT** [comment]
Awesome, thank you!

**Comment by maxice8** [comment]
@ebfe this can be closed

**Comment by VargMon** [comment]
You’re welcome my friend :)
