### ISSUE TITLE
xorriso-1.3.9_2: ERROR: SHA256 mismatch

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1240]
```
=> xorriso-1.3.9_2: verifying checksum for distfile 'xorriso-1.3.9.tar.gz'... 
=> ERROR: SHA256 mismatch for 'xorriso-1.3.9.tar.gz:'
ea7ee56cddd3638fcd15a0d6c6358765b359ba167536996560eec4f28a793f2c
=> ERROR: xorriso-1.3.9_2: couldn't verify distfiles, exiting...
```

**Comment by Gottox** [comment]
Damn. Don't have the old file anymore, I'd really like to know what's changed.

**Comment by Gottox** [comment]
They already did this in the past: 16a8baf04ae3e334754225f019a844866300761c

**Comment by pulux** [comment]
hm,
i found this on localy build. Normaly binpkgs are no touched until a new release is come. How can we find such thinks if there is still a valid binpkg? Is there any achive for old srcpkg´s?

**Comment by Gottox** [comment]
@pulux Yes, we keep the files on the build server. Unfortunately we moved the server some time ago and didn't kept the old srcfiles.
