### ISSUE TITLE
Newsbeuter: They broke podbeuter

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#1244]
The newsbeuter team doesn't make releases very often.  The current version has a segfault with podbeuter, which is part of newsbeuter.

I suggest we downgrade the package to the previous version if/until they make another proper release.

The current version is "r2.9", the last fully working version was "r2.8"
So if I want to downgrade, should I just add reverts above version as shown below?

reverts="r2.9"
version=r2.9

And if I understand this right, xbps will tell people who have this installed that it is downgrading, and it will also automagicaly update the template once a new revision is released? (As far as I'm aware, the r2.9 bump was done automatically.)

Thanks,

Logen Kain

**Comment by xtraeme** [comment]
I suggest you to tell them to fix the issue, it's not our problem if they break something :-)

**Comment by chneukirchen** [comment]
Just add the fixes of https://github.com/akrennmair/newsbeuter/pull/168 to
patches/?

**Comment by logenkain** [comment]
On Tue, Mar 31, 2015 at 02:18:12AM -0700, Christian Neukirchen wrote:
> Just add the fixes of https://github.com/akrennmair/newsbeuter/pull/168 to
> patches/?

How did I miss this?  Well, I'll be doing that soon.
