### ISSUE TITLE
Remove systemd builtoption

### ISSUE THREAD

**Issue by nmeum** [voidlinux/void-packages#1251]
After noticing todays April fools joke I remembered that we currently still have a systemd builtoption even though runit is our default init system. Most packages only ship with an runit service and I don't believe that anyone uses void linux with systemd. Actually I highly doubt that it works at all at the moment.

In order to reduce complexity I would therefore suggest that the systemd builtoption is removed entirely.

**Comment by thypon** [comment]
+1, even though i don't think gnome3 could work w/o systemd.

**Comment by bougyman** [comment]
Needless to say, I'm +1 on this for simplicity. However, a few thoughts.

1. Do we want to force an init on users? (I don't like that)
2. All of the runit service scripts work fine so long as runsvdir is monitoring /var/service, which it can do while systemd (or any other init) is PID1, if a user so chooses.
3. The gnome thing.

**Comment by nmeum** [comment]
> Do we want to force an init on users? (I don't like that)

Nope, other init system can be supported. But supporting systemd is actually kind of difficult since it is not just an init system but a system daemon. It also ships it's on implementation of sysctl, locale, udev, … and would thus require a completely different base-system.

> All of the runit service scripts work fine so long as runsvdir is monitoring /var/service, which it can do while systemd (or any other init) is PID1, if a user so chooses.

I never tried that but I would assume that you run into a lot of problems when doing that.

> The gnome thing.

Since I don't use gnome I am not really up to date on this issue. IIRC gnome3 added systemd as a dependency a while back, because they needed systemd-logind, right? Is there no solution to this yet? Does that mean that you can't run gnome3 without systemd? As in: You can't run gnome3 on void unless you actually use systemd as your init system?

**Comment by logenkain** [comment]
On Tue, Mar 31, 2015 at 04:16:21PM -0700, nmeum wrote:
> Since I don't use gnome I am not really up to date on this issue. IIRC gnome3 added systemd as a dependency a while back, because they needed systemd-logind, right? Is there no solution to this yet? Does that mean that you can't run gnome3 without systemd? As in: You can't run gnome3 on void unless you actually use systemd as your init system?
I thought the freeBSD folks were working on this, but yea, I haven't
been uptodate on gnome3 either.

**Comment by Gottox** [comment]
@nmeum We support Gnome3.14 without systemd.

Anyway, I don't think removing the systemd build option now is a good idea. I'd like to wait till the systemd alternatives (LoginKit, systemBSD) are becoming usable and we actually know how to handle them.

**Comment by xtraeme** [comment]
The systemd build option is still there because somebody could build void with systemd, as any other build option. I won't remove it for now, because it could be useful for testing systemd.

**Comment by nmeum** [comment]
So why did you remove base-system-systemd then?

**Comment by xtraeme** [comment]
Don't remember exactly, but the pkg could be resurrected.

**Comment by nmeum** [comment]
Well…that was the entire point if this bug report. If you want to support systemd then you need the base-system, you need people to test it and you need unit files. If you are not willing to do that then you might as well remove the builtoption entirely. :runner:
