### ISSUE TITLE
Package request: rxvt-unicode-terminfo (again!), aspell-pl, {fontconfig,freetype,cairo}-ultimate

### ISSUE THREAD

**Issue by skrzyp** [voidlinux/void-packages#1257]
While I'm leaving you at this weekend, I can't post any new templates until next Tuesday, so I'll leave some requests which may be good not only for me:

* [x] **rxvt-unicode-terminfo**: add `rxvt-unicode-256color` definition (it exists in ArchLinux's package)
* [ ] **aspell-pl**: dictionary of my language. But a little note: use [this dict files](http://sjp.pl/slownik/ort/) instead of GNU dictionaries, they're more recent and frequently updated.
* [ ] **fontconfig-ultimate**: bumping the #1053, but using [bohoomil/fontconfig-ultimate](https://github.com/bohoomil/fontconfig-ultimate). It really makes a very big (positive, ofc) difference in font rendering, mostly with [kori's infinality config](https://github.com/kori/shell.d/blob/master/infinality). Just try it yourself and decide to package it or not

At the end - Merry Easter :smiley:

**Comment by Gottox** [comment]
xbps-query -Rs rxvt-unicode-terminfo
[-] rxvt-unicode-terminfo-9.21_4 rxvt clone supporting Xft fonts and Unicode - terminfo data

**Comment by thypon** [comment]
#1053 <- duplicate.

**Comment by thypon** [comment]
#1554

**Comment by xtraeme** [comment]
All of them are now available.
