### ISSUE TITLE
fcitx-4.2.9.6_2 segfault on musl

### ISSUE THREAD

**Issue by yshui** [voidlinux/void-packages#12585]
Seems fcitx segfaults twice. Once in the program, then again in the segfault handler when it tries to get a stack trace.

**Comment by newbluemoon** [comment]
Did 4.2.9.6_1 work? Then perhaps the change to use libexecinfo is the culprit.

**Comment by yshui** [comment]
@newbluemoon Yep, _1 works

**Comment by newbluemoon** [comment]
I reverted it to use the execinfo patch again instead of libexecinfo. Perhaps you could already build the referenced PR and test it?

**Comment by newbluemoon** [comment]
@yshui No need to test anymore, it’s already merged. :)

**Comment by yshui** [comment]
Works now!
