### ISSUE TITLE
Package request: calibre

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1262]
Calibre is an ebook reader/collector

http://calibre-ebook.com/

**Comment by dominikh** [comment]
Duplicate of #248

**Comment by thypon** [comment]
Could we rename the other with standard syntax?

**Comment by dominikh** [comment]
> Something went wrong with that request. Please try again

Apparently not. Maybe someone else will have more luck.

**Comment by thypon** [comment]
Me had more luck :-P
