### ISSUE TITLE
numactl: can't build SHA256 mismatch

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1264]
```
=> numactl-2.0.10_2: verifying checksum for distfile 'numactl-2.0.10.tar.gz'... 
=> ERROR: SHA256 mismatch for 'numactl-2.0.10.tar.gz:'
dbdac8fe74f13b2e2864bba352f1597ab1d3345c8c485d7805f58d66f414db61
=> ERROR: numactl-2.0.10_2: couldn't verify distfiles, exiting...
```

**Comment by Gottox** [comment]
We don't have any sources to numactl anymore, so we can't create a diff to the original file.

**Comment by pulux** [comment]
Hm, the pkg `numactl` is in void repo, and I get the SHA mismatch error on build. In the moment I can't make a PR to fix the hash.  Please fix it, ty.

**Comment by bougyman** [comment]
I can get this to build if I make the hash right. What sources are missing, Gottox?
