### ISSUE TITLE
 broken, unresolvable multiple shlibs

### ISSUE THREAD

**Issue by freedomrun** [voidlinux/void-packages#12710]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
.. look at: terminal output at the bottom
* package:  
  *affected package(s) including the version*
.. look at: terminal output at the bottom

### Expected behavior
.. system update
### Actual behavior
.. look at: terminal output at the bottom
### Steps to reproduce the behavior (of course, if you have any of mentioned packages installed)
sudo xbps-install -Su

terminal output:
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
folks-0.11.4_1: broken, unresolvable shlib `libedataserver-1.2.so.22'
gnome-calendar-3.26.3_1: broken, unresolvable shlib `libedataserver-1.2.so.22'
gnome-contacts-3.28.0_2: broken, unresolvable shlib `libedataserver-1.2.so.22'
gnome-shell-3.28.0_1: broken, unresolvable shlib `libedataserver-1.2.so.22'
gnome-todo-3.28.0_1: broken, unresolvable shlib `libedataserver-1.2.so.22'
gnome-calendar-3.26.3_1: broken, unresolvable shlib `libedataserverui-1.2.so.1'
gnome-contacts-3.28.0_2: broken, unresolvable shlib `libedataserverui-1.2.so.1'
gnome-todo-3.28.0_1: broken, unresolvable shlib `libedataserverui-1.2.so.1'
gnome-online-miners-3.26.0_1: broken, unresolvable shlib `libgdata.so.19'
gnome-photos-3.26.3_1: broken, unresolvable shlib `libgdata.so.19'
shotwell-0.26.4_1: broken, unresolvable shlib `libgdata.so.19'
budgie-desktop-10.4_3: broken, unresolvable shlib `libgnome-desktop-3.so.12'
gnome-builder-3.26.4_2: broken, unresolvable shlib `libgspell-1.so.1'
budgie-desktop-10.4_3: broken, unresolvable shlib `libmutter-1.so.0'
budgie-desktop-10.4_3: broken, unresolvable shlib `libmutter-clutter-1.so'
budgie-desktop-10.4_3: broken, unresolvable shlib `libmutter-cogl-1.so'
Transaction aborted due to unresolved shlibs.

**Comment by maxice8** [comment]
we are currently heavily updating stuff to gnome-3.28 be patient as it is not an easy transition

**Comment by Gottox** [comment]
currently resolving. thanks for the report!

**Comment by maxice8** [comment]
also remove budgie-desktop because it is broken on the new libmutter, until this makes to upstream https://github.com/budgie-desktop/budgie-desktop/pull/1341

**Comment by freedomrun** [comment]
:( I`m currently using budgie-desktop. Thanks for advice.
