### ISSUE TITLE
keepassxc no auto-type

### ISSUE THREAD

**Issue by AngelFreak** [voidlinux/void-packages#12716]
### System

* xuname:  
  Void 4.14.26_1 x86_64 GenuineIntel uptodate rrrmFF
* package:  
  keepassxc 2.3.1

### Expected behavior
Auto-Type menu in application.
Auto-Type working
### Actual behavior
No Auto-Type menu in application.
Auto-Type is not working
### Steps to reproduce the behavior
xbps-install -Su keepassxc

### Notes

Auto-Type was working fine before system update.

**Comment by Piraty** [comment]
true.
I am investigating
