### ISSUE TITLE
ELOGIND, GVFS, UPOWER -  Void x86_64-MUSL

### ISSUE THREAD

**Issue by kenny-w7** [voidlinux/void-packages#12730]
I don't know where the little template thing went but its not loading for me O.o I've tried reloading the page, going back & clicking issue again.. odd.

Void Linux x86_64-MUSL

xuname:
Void 4.16.0rc6_1 x86_64-musl GenuineIntel uptodate rrnF

Packages definitely effected: Elogind, upower
Possibly effected packages: GVFS, mate-power-manager & xfce4-power-manager

Expected behaviour: Not sure

Actual behaviour: In DMESG:
elogind[1059]: Failed to create /elogind control group: No such file or directory
elogind[1059]: Out of memory.
upower[1543]: segfault at 8 ip 0000560ba1a9e970 sp 00007ffccec49ed0 error 4 in upowerd[560ba1a7e000+39000]

GVFS pulled elogind in on the last update & is now apparently required for GVFS, and ever since that I've been having some rather serious problems.
~
Lxsession-logout is taking FOREVER to load up & appears to also trigger the elogind error in dmesg, the elogind error is always in dmesg when I boot up before clicking on anything.
~
Mate-power-manager & xfce4-power-manager won't open up, I assume this is because of upower.
It appears polkit-elogind being installed does not seem to fix this either. Not quite sure what to do to be honest, I've been advised to create an "issue" on github from the void-linux forums.

**Comment by Gottox** [comment]
thanks for your report. Fixed upstream. `xbps-remove elogind; xbps-install -f polkit` should fix this issue for you.

**Comment by kenny-w7** [comment]
Its solved the power manager issue - no more errors in dmesg about upower or elogind after removing elogind,  lxsession-logout works normally, everything seems to be OK now :) 
Thank you all for working so quickly!!
