### ISSUE TITLE
Something wrong with Upower

### ISSUE THREAD

**Issue by kenny-w7** [voidlinux/void-packages#12804]
### System
Void x86_64-MUSL
* xuname:  
  Void 4.15.12_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  *affected package(s) including the version*
upower-0.99.7_2
### Expected behavior
for me to be able to use the power-managers.... 
### Actual behavior
Can't use the power managers.
### Steps to reproduce the behavior
steps to reproduce? I don't know how this isn't happening to everyone & not just me, simply do a fresh install of Void & try installing xfce4-power-manager or mate-power-manager, both won't read the battery & do weird things, for example mate-power-manager won't even open & instead gives me an error when trying to launch & an error in dmesg

in dmesg:
mate-power-mana[936]: segfault at 8 ip 00005632a3c6baf7 sp 00007ffc442d1480 error 4 in mate-power-manager[5632a3c53000+2c000]

When trying to launch mate-power-manager:

** (mate-power-manager:1258): WARNING **: 16:17:37.260: Failed to get brightness:
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not
provided by any .service files

(mate-power-manager:1258): libupower-glib-WARNING **: 16:17:37.280: up_client_get_devices failed:
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not
provided by any .service files
Segmentation fault

xfce4-power-manager will launch, BUT it won't read the battery.... LXDE's battery icons work though. This has been happening to me on & off for a few days now. If I re-install upower it will sometimes work, I think it may not be packaged right or something of that sort.

**Comment by abenson** [comment]
There was some weirdness with the upower0 -> upower replacement for me. What is the output of `sudo xbps-pkgdb upower`?

**Comment by Johnnynator** [comment]
> There was some weirdness with the upower0 -> upower replacement for me. What is the output of sudo xbps-pkgdb upower?

the upower0 problems are already solved. Also he stated the exact version number which is `upower`

**Comment by abenson** [comment]
When the package was replaced during the upgrade I had to force reinstall the package before it worked.

**Comment by abenson** [comment]
This is the issue I had: [upower.txt](https://github.com/voidlinux/void-packages/files/1839414/upower.txt)

I had to force reinstall it.

**Comment by abenson** [comment]
> fresh install of Void

Did you do a local install and upgrade or install directly from network?

**Comment by Johnnynator** [comment]
@abenson I could reproduce you behavior. Another revision bump should be able to fix it.

**Comment by kenny-w7** [comment]
Yea, doing the --force thing makes it work.

**Comment by Hoshpak** [comment]
The file `/etc/UPower/UPower.conf` was missing on my system, instead it was installed as `/etc/UPower/UPower.conf.new-0.99.7_2` and upower refused to start. I don't have the upower0 package around any more but perhaps the file ist provided by both packages and something went wrong while removing upower0 and installing upower. Fore reinstalling of upower led to the file being created and the issue went away.

**Comment by Gottox** [comment]
This may be an issue with the transitional package. for anyone finding this issue: ```xbps-install -f upower``` fixes this issue.
