### ISSUE TITLE
libavcodec-3.4.2_2: broken, unresolvable shlib `libvpx.so.4' 

### ISSUE THREAD

**Issue by kenny-w7** [voidlinux/void-packages#12847]
### System
Void Linux x86_64-MUSL
* xuname:  
  Void 4.15.12_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  *affected package(s) including the version*
libavcodec-3.4.2_2, libvpx-1.7.0_1

Packages that it stops me from re-installing:
alsa-plugins-ffmpeg dolphin-emu chromaprint ffmpeg ffmpeg-devel guvcview libavdevice libavformat libopenal libvlc mpv qt5-webengine vba-m xine-lib qt5-webview qupzilla qt5-webengine-devel python-PyQt5-webengine python3-PyQt5-webengine python3.4-PyQt5-webengine qt5-webview-devel qtcreator-full python3.4-PyQt5-webengine mpv-devel vlc vlc-devel phonon-qt5-backend-vlc phonon-backend-vlc yabause-gtk SFML libavfilter clementine thunderbird firefox-esr libavcodec gst-plugins-good1 pidgin

### Expected behavior
Expected behavior: It shouldn't stop me from installing things with libavcodec dependency :P 
### Actual behavior
Actual behavior: it stops me from installing other packages
### Steps to reproduce the behavior
I think everyone is experiencing this, just try xbps-install libavcodec / xbps-install -f libavcodec
or even just try to install one of these other packages listed above perhaps.

**Comment by kenny-w7** [comment]
Should I always report issues like this on Github? Obviously searching for any already-existing issues about these packages first... Just curious if this is something I should always report or if you guys already know about these things.

**Comment by Gottox** [comment]
please stand by, rebuild is in progress. :)

**Comment by kenny-w7** [comment]
Awesome! Thank you Gottox! 
So, should I always be reporting package conflicts to here?

**Comment by Johnnynator** [comment]
When you get a `unresolvable shlib` error then just wait a day because it will be most likely resolved by then.

**Comment by kenny-w7** [comment]
Yea. Next time I won't uninstall things in the hopes of making it work, as now I can't re-install mpv, vlc, etc until after I get the update for this libvpx thing. Any idea when this fixed package will hit the repo?

**Comment by espectalll** [comment]
Hey, I'm on GNU Void x86_64 and I've been dealing with this error for about a week (affected package: `gst-plugins-bad`), has it been fixed yet?

**Comment by Gottox** [comment]
`gst-plugins-bad` has been removed from the repositories. Uninstall it. :)
