### ISSUE TITLE
Package request: criu

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1289]
http://criu.org/Main_Page

Welcome to CRIU, a project to implement checkpoint/restore functionality for Linux in userspace.

Checkpoint/Restore In Userspace, or CRIU (pronounced kree-oo, IPA: /krɪʊ/, Russian: криу), is a software tool for Linux operating system. Using this tool, you can freeze a running application (or part of it) and checkpoint it to a hard drive as a collection of files. You can then use the files to restore and run the application from the point it was frozen at. The distinctive feature of the CRIU project is that it is mainly implemented in user space.

**Comment by Gottox** [comment]
I made a template some time ago, but it failed. If you want to tinker, here it is:

```
# Template file for 'criu'
pkgname=criu
version=1.5
revision=1
build_style=gnu-makefile
hostmakedepends="pkg-config protobuf-c protobuf"
makedepends="libbsd-devel protobuf-c-devel"
depends="python-ipaddr"
short_desc="Utility to checkpoint/restore a process tree"
maintainer="Enno Boland <eb@s01.de>"
license="GPL-2, LGPL-2"
homepage="http://criu.org/"
distfiles="http://download.openvz.org/criu/criu-$version.tar.bz2"
checksum=c848918d5b67f68efd25224bc4a7ffe9252d039fc6f3cc77c6309f6427448cdf
```

**Comment by thypon** [comment]
I think there is a problem with the makefile, there are floating patches around the mailing list. I think however i'll cherry-pick a makefile patch directly from github repository. https://github.com/xemul/criu

**Comment by Gottox** [comment]
The git repo suffers from the same issue.

**Comment by thypon** [comment]
I updated the dependencies and pass the build phase, even if it fails during install phase.

```
# Template file for 'criu'
pkgname=criu
version=1.5
revision=1
build_style=gnu-makefile
hostmakedepends="pkg-config protobuf-c protobuf python asciidoc xmlto"
makedepends="libbsd-devel protobuf-c-devel protobuf-devel"
depends="python-ipaddr"
short_desc="Utility to checkpoint/restore a process tree"
maintainer="Enno Boland <eb@s01.de>"
license="GPL-2, LGPL-2"
homepage="http://criu.org/"
distfiles="http://download.openvz.org/criu/criu-$version.tar.bz2"
checksum=c848918d5b67f68efd25224bc4a7ffe9252d039fc6f3cc77c6309f6427448cdf
```

**Comment by Gottox** [comment]
this is fixable, thanks for your help! :+1:

**Comment by Gottox** [comment]
#1296
