### ISSUE TITLE
System update fails because "MISSING: kexi>=3.1.0_2"

### ISSUE THREAD

**Issue by tuxlifan** [voidlinux/void-packages#12904]
### System

* xuname:  
>MISSING: kexi>=3.1.0_2
>Transaction aborted due to unresolved dependencies.
>Void 4.14.22_2 x86_64 GenuineIntel uptodate rFFFF

* package:  
`calligra[-sheets]-2.9.11_17` and `kexi-3.1.0_1`

### Expected behavior
`sudo xbps-install -Su` updates system

### Actual behavior
Error message:
> MISSING: kexi>=3.1.0_2
> Transaction aborted due to unresolved dependencies.

`xbps-query -Rs kexi` shows:
> kexi-3.1.0_1

### Steps to reproduce the behavior
* Install calligra-sheets-2.9.11_17
* run `sudo xbps-install -Su`

### Analysis

My best guess is that (with void-packages @ commit b55a555)
in `calligra/template`
>pkgname=calligra
>version=3.1.0
>revision=2
> [...]
> calligra-kexi_package() {
>         build_style=meta
>         depends="kexi>=${version}_${revision}"
>         short_desc+=" - Develop desktop db apps (transitional dummy package)"
> }

the depends evaluates to kexi>=3.1.0_2
while `kexi/template` only has:
>pkgname=kexi
>version=3.1.0
>revision=1

### Fix

Bumping the revision for kexi to 2 should fix this? @Johnnynator 
Tested locally by building kexi-3.1.0_2 with xpbs-src and installing with `xi`.

**Comment by Johnnynator** [comment]
Imo removing the exact version dependency would be more useful since there is no need for that version check.
