### ISSUE TITLE
Package Request: racket-doc

### ISSUE THREAD

**Issue by TeddyDD** [voidlinux/void-packages#12958]
Racket provides offline documentation in HTML withch is pretty useful.
Current racket package does not install this docs.

**Comment by TeddyDD** [comment]
Thank you :)

**Comment by TeddyDD** [comment]
@abenson Hi, I tried to install racket and docs today and racket-docs seems to be missing form repo. I tried to build it myself but I got an error:
```
./xbps-src pkg racket-doc
=> ERROR: racket-doc: missing racket-doc_package() function!
```
Should I reopen this issue or I'm doing something wrong?

**Comment by abenson** [comment]
There was a merge after mine (@pullmoll #12721)  that reverted my changes.

**Comment by abenson** [comment]
I'd reopen.

**Comment by TeddyDD** [comment]
Okay, I can't reopen this one so I'll create new issue.
