### ISSUE TITLE
dracut error 

### ISSUE THREAD

**Issue by porto99** [voidlinux/void-packages#12970]
* xuname:  
`Void 4.15.12_1 x86_64 GenuineIntel uptodate r`
* package:  
  *dracut*

Error message during kernel update to 4.15.12_1, but system still boots alright
```
dracut-install: ERROR: installing '=drivers/staging'
```
* Reproduce:
```
[root@xsnas etc]# dracut -q -fv /boot/initramfs-4.15.12_1.img.test 4.15.12_1
dracut: Executing: /usr/bin/dracut -q -fv /boot/initramfs-4.15.12_1.img.test 4.15.12_1
dracut: dracut module 'bootchart' will not be installed, because command '/sbin/bootchartd' could not be found!
[...]
dracut: dracut module 'biosdevname' will not be installed, because command 'biosdevname' could not be found!
dracut: *** Including module: bash ***
dracut: *** Including module: dash ***
dracut: *** Including module: i18n ***
dracut: *** Including module: drm ***
dracut-install: ERROR: installing '=drivers/staging'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.Jhx4gz/initramfs --kerneldir /lib/modules/4.15.12_1/ -m -s drm_crtc_init =drivers/gpu/drm =drivers/staging
dracut: *** Including module: btrfs ***
dracut: *** Including module: crypt ***
dracut: *** Including module: dm ***
```

**Comment by kenny-w7** [comment]
**I know this is not a fix**, but you can try mkinitcpio. Its quite easy, just install it & remove dracut.
https://wiki.archlinux.org/index.php/mkinitcpio

**Comment by Gottox** [comment]
Thanks for the report. I'm investigating.

**Comment by KeepBotting** [comment]
I am able to reproduce the error by following the steps in the OP.

xuname: `Void 4.15.12_1 x86_64 GenuineIntel uptodate rr`

Note that rebooting into the new kernel (4.5.12) after dracut has finished seems to work fine. Is there anything that this bug seems to affect?

```
[branon@netherworld ~]$ uname -a
Linux netherworld 4.15.12_1 #1 SMP PREEMPT Thu Mar 22 13:07:32 UTC 2018 x86_64 GNU/Linux
[branon@netherworld ~]$ uptime
 20:32:55 up 29 min,  2 users,  load average: 0.00, 0.00, 0.00
```

There seems to be some discussion about this over at the forum: https://forum.voidlinux.eu/t/dracut-failed/5132/10
