### ISSUE TITLE
/usr/bin/proxy is created both by libproxy and 3proxy

### ISSUE THREAD

**Issue by laserbat** [voidlinux/void-packages#12996]
### System

* xuname:  
  Void 4.16.0rc7_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
  libproxy-0.4.15_1, 3proxy-0.8.11_1

Installing both packages leads to errors when running xbps-pkgdb -a:

`ERROR: libproxy: hash mismatch for /usr/bin/proxy.
ERROR: libproxy: files check FAILED.`

**Comment by cr6git** [comment]
good catch @laserbat !

**Comment by Gottox** [comment]
Libproxy's proxy command: https://github.com/libproxy/libproxy/blob/master/utils/proxy.c

3proxy's proxy command: https://github.com/z3APA3A/3proxy/blob/devel/src/proxymain.cy

Proposal: remove libproxy's command or rename it to libproxy-proxy.

**Comment by cr6git** [comment]
@Gottox sorry, don't want to step on your toes, I let you take care of it. :innocent:
