### ISSUE TITLE
Missing dependency for Dropbox package?

### ISSUE THREAD

**Issue by ArniDagur** [voidlinux/void-packages#13081]
Could it be that package `libxslt` is a missing dependency for Dropbox? 

### System

* xuname:  
`Void 4.15.12_1 x86_64 GenuineIntel uptodate rr`
* package:  
  `dropbox-2015.10.28_2`

This is a fresh install of Void.

### Expected behavior
Dropbox works as expected.
### Actual behavior
Dropbox error log gives when started up:
```
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 1044, in boot_error
AssertionError

Original traceback:

Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 6601, in main_startup
  File "dropbox/client/main.pyc", line 2847, in run
  File "ui/common/uikit.pyc", line 702, in create_ui_kit
  File "dropbox/client/ui/qt/__init__.pyc", line 34, in <module>
  File "<_bootstrap_overrides>", line 166, in load_module
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
```
### Steps to reproduce the behavior
1. Install Dropbox with `xbps-install -S dropbox`
2. Open Dropbox

### Solution:
Install package `libxslt-1.1.32_1` with `xbps-install -S libxslt`. I did this and Dropbox stopped complaining.

**Comment by maxice8** [comment]
libxslt is in the depends of this package, it should have been installed with it and trying to remove it would cause XBPS to refuse to do so.

https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dropbox/template#L8

**Comment by maxice8** [comment]
But it isn't on the package available in the repos, a rebuild will catch it.

**Comment by maxice8** [comment]
Oh, the dependency was added on e3c83b2b83dbe854fdb4265ceaca36678a50a492 but wasn't revbump to rebuild it.

**Comment by ArniDagur** [comment]
Great, thanks a lot!

**Comment by ebfe** [comment]
f8fd05567380ffdf3260e2f47f0b53fb20cc176f
