### ISSUE TITLE
criu: multiple errors

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1310]
```
[gattuso@R2D2 ~]$ sudo criu check --ms
/proc/<pid>/map_files directory is missing.
Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
The sock diag infrastructure is incomplete.
Make sure you have:
 1. *_DIAG kernel config options turned on;
 2. *_diag.ko modules loaded (if compiled as modules).
sys/kernel/ns_last_pid sysctl is missing.
System call kcmp is not supported
prctl: PR_GET_TID_ADDRESS is not supported
Error (cr-check.c:227): Can'r fetch file owner UIDs: Invalid argument
/proc/sys/kernel/sem_next_id sysctl is missing.
Warn  (cr-check.c:581): Dirty tracking is OFF. Memory snapshot will not work.
/proc/<pid>/timers file is missing.
Warn  (tun.c:58): Skipping tun support check
Warn  (timerfd.c:44): timerfd: Skipping timerfd support check
Warn  (cr-check.c:296): Skipping mnt_id support check
```

@Gottox

**Comment by chneukirchen** [comment]
Andrea Brancaleoni <notifications@github.com> writes:

> ```
> [gattuso@R2D2 ~]$ sudo criu check --ms
> /proc/<pid>/map_files directory is missing.
> Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
> Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
> Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
> Error (libnetlink.c:37): ERROR -2 reported by netlink (No such file or directory)
> The sock diag infrastructure is incomplete.
> Make sure you have:
>  1. *_DIAG kernel config options turned on;
>  2. *_diag.ko modules loaded (if compiled as modules).
> sys/kernel/ns_last_pid sysctl is missing.
> System call kcmp is not supported
> prctl: PR_GET_TID_ADDRESS is not supported
> Error (cr-check.c:227): Can'r fetch file owner UIDs: Invalid argument
> /proc/sys/kernel/sem_next_id sysctl is missing.
> Warn  (cr-check.c:581): Dirty tracking is OFF. Memory snapshot will not work.
> /proc/<pid>/timers file is missing.
> Warn  (tun.c:58): Skipping tun support check
> Warn  (timerfd.c:44): timerfd: Skipping timerfd support check
> Warn  (cr-check.c:296): Skipping mnt_id support check
> ```

We need CONFIG_CHECKPOINT_RESTORE=y in the kernel for that.
Additionally, we need CONFIG_INET_UDP_DIAG=y.  We have everything else
according to http://criu.org/Installation.

Debian has this enabled by default, should do no harm.

**Comment by Gottox** [comment]
@xtraeme Can we enable that on our kernels?

**Comment by xtraeme** [comment]
Missing stuff has been added to 3.19.4 and 4.0.0_2:

```
[juan@leysa ~]$ sudo criu check
Warn  (cr-check.c:581): Dirty tracking is OFF. Memory snapshot will not work.
Looks good.
[juan@leysa ~]$ 
```
