### ISSUE TITLE
lm_sensors: no init service

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1313]
Should have an equivalent systemd service; no one for runit.

**Comment by chneukirchen** [comment]
Andrea Brancaleoni <notifications@github.com> writes:

> Should have an equivalent systemd service; no one for runit.

For the modules, just add them to /etc/modules-load.d

sensorsd or fancontrol is not packaged currently, speak up if you need that.

**Comment by thypon** [comment]
Not for now.
