### ISSUE TITLE
So since when is....

### ISSUE THREAD

**Issue by nunya-bizniz** [voidlinux/void-packages#13147]
Since when is Void Linux ran by a bunch of cowardly cuckolded Frenchmen & tranny Germans? Pathetic.
Here come the anime avatars to tell me I'm wrong :^^^^^^) LOL oh the fucking irony is just too rich!
Hahahahahaha, what a sad sack of shit you losers are. So much guilt that you've literally cut your penises off! SAD! Enjoy killing yourselves in the next 10-20 years when you realize that once you're 60+ you're going to look like a freakshow who's had too much plastic surgery & is going bald... Either that or the inbred Muslims who marry their first cousins religiously that you're importing will get you, they're not very fond of trannies I hear :^^^^^^^^^^^)

Just whatever you do, don't come to the rest of the civilised world as "refugees" after you've ruined your own countries, and stay the fuck out of east Asia, degenerate baizuo scumfucks.

Who knows, maybe some sane people will take up this project & it'll stop being such garbage one day, I won't hold my breath though, that's for sure! :^^^^^)

**Comment by Gottox** [comment]
Thanks mate, you're welcome!

**Comment by pullmoll** [comment]
Just wanted to add, now that I'm ___really___ drunk: yup! Had my fun. Live long and prosper.
I could have kept my mouth shut and will probably take my advice to self serious sometime soon. Who nose?
