### ISSUE TITLE
xbps-src (void linux) QuickStart failure on RPi

### ISSUE THREAD

**Issue by BrianHoldsworth** [voidlinux/void-packages#1315]
I'm using an RPi 2, ARMv7, with the corresponding image downloaded from the Void Linux [download link](http://www.voidlinux.eu/download/#raspberry-pi-2-armv7-hard-float). I followed the brief instructions given for cloning and bootstrapping xbps-src. All seems to go well, but I cannot execute any xbps-src commands. Fetch, Configure, Pkg, all respond with the same cryptic pair of error messages exactly as shown below:

ERROR unshare (Invalid argument)
ERROR unshare (Invalid argument)

Being a newbie to xbps-src, I'm not sure how to troubleshoot. I did not find an option for verbose output or logging. Any guidance would be much appreciated.

**Comment by xtraeme** [comment]
Please read this:

https://github.com/voidlinux/void-packages#the-xbps-source-packages-collection

The Raspberry Pi upstream linux kernel (3.18.x) seems to not enable CONFIG_USER_NS (user_namespaces(7)), which is required for `xbps-uunshare(8)` to work.

You'll have to use `xbps-uchroot(8)` or `proot(1)` via XBPS_CHROOT_CMD in void-packages/etc/conf.

**Comment by xtraeme** [comment]
Our Raspberry Pi linux kernel (3.18.11) now contains support for `user_namespaces(7)` as required by `xbps-uunshare(8)`.

Thanks.

**Comment by BrianHoldsworth** [comment]
Outstanding! You gotta love a Linux project that gives the Raspberry Pi first class treatment without endless debate and delays :)

**Comment by xtraeme** [comment]
The new kernel is being built right now:

http://build.voidlinux.eu/builders/armv7l_builder/builds/11973/steps/shell_3/logs/stdio

Once the build has finished you can upgrade and reboot. xbps-src should work without any tweaks with xbps-uunshare(8) now.

Cheers.
