### ISSUE TITLE
Package request: libaom

### ISSUE THREAD

**Issue by espectalll** [voidlinux/void-packages#13171]
`libaom` is the official Alliance for Open Media library for the AV1 codec, which is intended to replace VP9 and others alike. The source code is available at https://aomedia.googlesource.com/aom, and it uses CMake for building.

Also, `ffmpeg` has added support for `libaom` on `master`, which can be activated with the  `--enable-libaom` flag on `configure`. Should be a trivial change on the package template.

**Comment by maxice8** [comment]
I couldn't find a stable tarball, give me a link and i will package it.

Otherwise close this and re-open when a stable-release tarball can be provided.

**Comment by RX14** [comment]
https://aomedia.googlesource.com/aom/+archive/v0.1.0.tar.gz

**Comment by maxice8** [comment]
On Sun, Apr 29, 2018 at 05:47:12AM -0700, Chris Hobbs wrote:
> https://aomedia.googlesource.com/aom/+archive/v0.1.0.tar.gz
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

working on it

**Comment by RX14** [comment]
The 0.1.0 tag seems a bit old though (jun 2017!) given how new the codec is. Might not work with ffmpeg...

**Comment by maxice8** [comment]
it doesn't even include the new cmake build system and instead uses a custom shitty configure script.

i'll wait.

**Comment by arekm** [comment]
There is 1.0.0 now but above "stable" link isn't stable. md5 of tarball changes at every fetch.

**Comment by Johnnynator** [comment]
@arekm this is normal for tar balls from googlesource.com, the content should stay the same, only metadata changes. ( xbps-src supports to checksum only the content of a archive for this reason )

**Comment by maxice8** [comment]
libaom is already available.
