### ISSUE TITLE
Upower not providing dbus .service files - breaks mate-power-manager, brightness control, etc.

### ISSUE THREAD

**Issue by kylesusername** [voidlinux/void-packages#13202]
### System

* xuname:  
    Void 4.16.0_1 x86_64 GenuineIntel uptodate rrF
* package:  
mate-power-manager-1.18.2_1, upower-0.99.7_2, upower0-0.99.7_2
### Expected behavior
mate-power-manager launching, brightness control working, battery status showing on panel
### Actual behavior
mate-power manager crashing with 

** (mate-power-manager:12807): WARNING **: 02:12:24.265: Failed to get brightness: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files

(mate-power-manager:12807): libupower-glib-WARNING **: 02:12:24.277: up_client_get_devices failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
zsh: segmentation fault  mate-power-manager

### Steps to reproduce the behavior
Have laptop, run mate-power-manager. 

System was working fine a few days ago. First noticed problems when laptop would not suspend when closing the lid, it was controlled by mate-power-manager.

**Comment by silvernode** [comment]
Someone just came into IRC saying their battery icon was showing "not detected" in KDE. I am thinking this could be related.

**Comment by abenson** [comment]
What is the output of `xbps-pkgdb upower` ?

**Comment by kylesusername** [comment]
@abenson  

ERROR: upower: unexistent file /usr/lib/udev/rules.d/95-upower-wup.rules.
ERROR: upower: unexistent file /usr/share/dbus-1/system-services/org.freedesktop.UPower.service.
ERROR: upower: unexistent file /usr/share/dbus-1/interfaces/org.freedesktop.UPower.Wakeups.xml.
ERROR: upower: unexistent file /usr/share/locale/sv/LC_MESSAGES/upower.mo.
ERROR: upower: unexistent file /usr/share/locale/fr/LC_MESSAGES/upower.mo.
ERROR: upower: unexistent file /usr/share/locale/pl/LC_MESSAGES/upower.mo.
ERROR: upower: unexistent file /usr/share/locale/it/LC_MESSAGES/upower.mo.
ERROR: upower: files check FAILED.
ERROR: upower: unexistent file /etc/UPower/UPower.conf
ERROR: upower: conf files check FAILED.
Failed to check `upower': Operation not permitted

:o

I should clarify, I tried force reconfiguring all of the related packages which didn't seem to do anything. 

@silvernode yeah, that's what happened to me at first. The battery icon disappeared, and now the brightness controls don't work.

**Comment by abenson** [comment]
This seems to be related to the package replacement. try: `xbps-install -Sfy upower`.

**Comment by kylesusername** [comment]
@abenson  yep that worked! Thanks
