### ISSUE TITLE
Missing required firmware file for r8188eu module

### ISSUE THREAD

**Issue by BrianHoldsworth** [voidlinux/void-packages#1321]
This USB wireless module driver requires a separate firmware file which is not included in the void linux image. This is indicated in the dmesg output with an error like _Direct firmware load for rtlwifi/rtl8188eufw.bin failed_

__Workaround__: The firmware file can be pulled from Github.

~~~
sudo wget https://github.com/lwfinger/rtl8188eu/raw/c83976d1dfb4793893158461430261562b3a5bf0/rtl8188eufw.bin  -O /lib/firmware/rtlwifi/rtl8188eufw.bin
~~~

Reboot, and the module should be able to complete initialization.

**Comment by xtraeme** [comment]
This is part of `linux-firmware-network`:

```
[juan@pi2 ~]$ xbps-query -Rf linux-firmware-network|grep rtl8188eufw
/usr/lib/firmware/rtlwifi/rtl8188eufw.bin
[juan@pi2 ~]$
```
