### ISSUE TITLE
Elogind errors musl

### ISSUE THREAD

**Issue by sstt011** [voidlinux/void-packages#13281]
### System

* xuname:  
  Void 4.15.15_1 x86_64-musl GenuineIntel uptodate rF
* package:  
  elogind-253.3

### Expected behavior

Computer should boot and start GDM through `elogind` on an `musl` system (only `x86_64-musl` tested). 

### Actual behavior

**Expected behavior occurs on non-musl systems.**

Almost exactly the same as #10997,

    .... elogind[8822]: Cannot determine cgroup we are running in: No medium found
    .... elogind[8822]: Out of memory.

is displayed just before login and again after login (command line). A delay of approx. 10 seconds occurs after the second message. **This only occurs on musl systems.** (only `x86_64-musl` tested).

### Steps to reproduce the behavior

- Install `xorg-minimal` and `gnome`. 
- Enable services `dbus` and `gdm`. 
- Reboot.

**Comment by emacsomancer** [comment]
Unfortunately the only reason I had elogind installed was because it got pulled in as a dependency of something (nautilus?) and I 'solved' it by just uninstalling whatever pulled in elogind.

**Comment by cr6git** [comment]
@sstt011 Me? no clue... ask @cavalier911 / **cardinal** ([elogind-errors-on-boot-slower-login](https://forum.voidlinux.eu/t/elogind-errors-on-boot-slower-login/4399/3)) ? :thinking:

**Comment by pullmoll** [comment]
This patch has nothing to do with the crash, but only shields a comparison of a macro's value against a number with the prerequisite that this macro is defined at all. It's just *compiler cosmetics* in that sense.

Do you have `cgmanager` runinng, i.e. `sudo sv status cgmanager`?

**Comment by sstt011** [comment]
@pullmoll nope, it doesn't even exist:

    fail: cgmanager 

elogind was originally pulled in by GNOME.

So I installed it with `sudo xbps-install cgmanager`, linked it (`ln -s /etc/sv/cgmanager /var/service`) and rebooted.

And we do get a little further - still dosen't work, but there is a new error message:

    Failed to create /elogind control group: No such file or directory.

Very similar - both are about control groups. Thoughts anyone?

**Comment by pullmoll** [comment]
I admit I don't even exactly know which services you need to run to execute gdm.
Perhaps someone with more insight can tell what other service you need to install and run.
Or perhaps list your services with `ls /var/service/` and let's find out what's missing there.

**Comment by cr6git** [comment]
@sstt011 AFAIK `ConsoleKit2` needs `cgmanager`. For `elogind` I imagine it's the same?

**Comment by cr6git** [comment]
@sstt011 so, what's new?

**Comment by sstt011** [comment]
Closing this. Issue now in new org: https://github.com/void-linux/void-packages/issues/212
