### ISSUE TITLE
openmpi and openmpi-devel does not see fortran

### ISSUE THREAD

**Issue by AlexanderKoshkarov** [voidlinux/void-packages#13335]
### System

even when gfortran is present in the system, openmpi does not see it
(openmpi   3.0.1_1, openmpi-devel, 3.0.1_1)

### Expected behavior
% mpifort                                  
mpifort: fatal error: no input files
compilation terminated.

### Actual behavior
% mpifort 
--------------------------------------------------------------------------
No underlying compiler was specified in the wrapper compiler data file
(e.g., mpicc-wrapper-data.txt)
--------------------------------------------------------------------------

### Steps to reproduce the behavior
install gfortran and openmpi
run mpifort

### Fix
well, I am not really good at this, but probably one can change
`/usr/share/openmpi/mpifort-wrapper-data.txt`
to contain the line
`compiler=gfortran`

**Comment by AlexanderKoshkarov** [comment]
fix may be not sufficient...

**Comment by pullmoll** [comment]
gcc-fortran was not enabled at all when openmpi was built. Instead the environment FC and FCFLAGS was unset.
I changed that and now it looks as if gfortran is detected and used, so mpifort should work as expected.
If not, pleas re-open an issue describing the problem.
