### ISSUE TITLE
There's an upstream regression in zfsonlinux/zfs-0.7.7 → recommendation is downgrade to 0.7.6 until issue is resolved

### ISSUE THREAD

**Issue by datenwolf** [voidlinux/void-packages#13350]
A data corrupting regression has been discovered in upstream zfs-0.7.7. See https://github.com/zfsonlinux/zfs/issues/7401

The official recommendation from upstream is to downgrade to v0.7.6 until the issue has been resolved. v0.7.8 is expected to be released soon and a fix has been promised for that version.

**Comment by dg98** [comment]
ZFS v0.7.8 is released now

**Comment by Vaelatern** [comment]
ack.

**Comment by Vaelatern** [comment]
cfab393 722beb1
