### ISSUE TITLE
Package Issue: kdesu package does not include binary

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#13376]
### System

* xuname:  
  *Void 4.15.15_1 x86_64 GenuineIntel uptodate rrrmFFF*
* package:  
  *kdesu-5.43.0_1*

### Expected behavior
```kdesu``` should be a binary located somewhere in $PATH (e.g /usr/bin or /usr/local/bin)
### Actual behavior
There is no executable binary in $PATH which prevents applications like octoxbps from using it
example ```bash: kdesu: command not found```
### Steps to reproduce the behavior
```
$ xbps-install -S kdesu
$ kdesu -c <command>
```

**Comment by jnbr** [comment]
`/usr/lib/libexec/kf5/kdesu` is provided by `kde-cli-tools`

**Comment by silvernode** [comment]
Running ```/usr/lib/libexec/kf5/kdesu``` seems to work, I will need to file issues with the developer of octoxbps since that's what I am having issues with. It seems like kdesu used to be in another directory. I symlinked gku to /usr/bin/kdesu and octoxbps responded to that however gksu and kdesu use different arguments so of course it wouldn;t work.  octoxbps only seems to use gksu when using a gtk based desktop (strange).

**Comment by newbluemoon** [comment]
```
$ xlocate /usr/bin/kdesu
kde-runtime-4.14.3_11	/usr/bin/kdesu -> /usr/lib/kde4/libexec/kdesu
```

KDE4 symlinked kdesu, KDE5 apparently not. Perhaps it’s worth re-establishing that symlink in kde-cli-tools?

**Comment by silvernode** [comment]
> KDE4 symlinked kdesu, KDE5 apparently not. Perhaps it’s worth re-establishing that symlink in kde-cli-tools?
I want to say yes just because some applications expect it to be there and act strangely or don't work otherwise.
