### ISSUE TITLE
Package Request: qtcreator

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1337]
I'd love to see a qtcreator package. Newer versions require qt5. I tried building it locally, which failed after some time because of a missing qt5 help package. This, however, does not exist in voidlinux qt5. 
http://download.qt.io/official_releases/qtcreator/3.3/3.3.2/qt-creator-opensource-src-3.3.2.tar.gz

**Comment by bougyman** [comment]
Many qt5 packages exist. Did you build a void-packages template or just try to build manually?

**Comment by pullmoll** [comment]
I tried manually, because I did not yet understand what belongs in a void-packages template. I'd try myself, while I think I should first read some more examples before trying.

**Comment by pullmoll** [comment]
It looks like I need to add qt5-tools-devel for the help package. Building locally now and trying to get icons and desktop files installed as well.

**Comment by bougyman** [comment]
Are you going to contribute a pull request for it?
