### ISSUE TITLE
riot-desktop out of date

### ISSUE THREAD

**Issue by jtl999** [voidlinux/void-packages#13394]
### System

* xuname:  
`Void 4.15.15_1 x86_64 GenuineIntel uptodate rrrmF`
* package:  
riot-desktop-0.13.5_1

### Expected behavior
riot-desktop should be version 0.14 ([released](https://medium.com/@RiotChat/riot-im-web-0-14-is-here-18d88dc2a423) hours ago)

### Actual behavior
riot-desktop is version 0.13.5
### Steps to reproduce the behavior
`xbps-query -R riot-desktop |grep pkgver`

**Comment by maxice8** [comment]
> hours ago

wait until someone cares to Update or make the PR yourself, we have the void-updates system to notify us of packages that have new versions.

**Comment by zethra** [comment]
I'll get on that.

**Comment by zethra** [comment]
PR made #13412
