### ISSUE TITLE
acl-devel maybe broken on i686

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#1342]
acl builds ok, but after local build on i686, dependig pkg's can't find acl-devel, see #1341

**Comment by xtraeme** [comment]
Unless you post build logs I'll assume it's a local problem.

**Comment by xtraeme** [comment]
Ok, I see what's wrong:

```
├── acl-devel-2.2.52
│   ├── rdeps
│   └── usr
│       ├── include
│       │   ├── acl
│       │   │   └── libacl.h
│       │   └── sys
│       │       └── acl.h
│       ├── lib
│       │   ├── libacl.a -> /usr/lib/libacl.a
│       │   └── libacl.so -> /usr/lib32/libacl.so
```

**Comment by xtraeme** [comment]
I fixed the stupid build issues related to lib32 on x86.

You'll have to rebuild with -f attr and acl, enjoy.
