### ISSUE TITLE
cups: runs as root

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1347]
Right now cups runs as root. 

this is the `run` file:
```
#!/bin/sh
exec cupsd -f
```

The user and the group used shoudl be `cups:lp`

**Comment by bougyman** [comment]
Changed the label ot "Idea" when I saw other distributions (ubuntu, arch) run cups as root, and a cursory google search seems to imply it _has_ to run as root. Do you have an example of a distribution that runs cupsd with a non-root user? I would like to make it work non-root and binding to the :631 port isn't a major issue, i'm worried about what else it might need root for.

**Comment by chneukirchen** [comment]
bougyman <notifications@github.com> writes:

> Changed the label ot "Idea" when I saw other distributions (ubuntu,
> arch) run cups as root, and a cursory google search seems to imply it
> _has_ to run as root. Do you have an example of a distribution that
> runs cupsd with a non-root user? I would like to make it work non-root
> and binding to the :631 port isn't a major issue, i'm worried about
> what else it might need root for.

Everything I looked at seems to start cupsd as root.

-- 
Christian Neukirchen  <chneukirchen@gmail.com>  http://chneukirchen.org

**Comment by xtraeme** [comment]
Pointless.

**Comment by thypon** [comment]
Until we have a MAC system like ubuntu/fedora making cupsd non-root isn't pointless.
