### ISSUE TITLE
xterm won't start

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#13534]
### System

* package:  `xterm-332_1`
  *affected package(s) including the version*

### Actual behavior
After the last update of `xterm` [#13520](https://github.com/voidlinux/void-packages/pull/13520) it won't start (on `x86_64_musl`).
### Steps to reproduce the behavior
Install / update `xterm` and run it:
````
$ xterm
Error loading shared library libutempter.so.0: No such file or directory (needed by /usr/bin/xterm)
Error relocating /usr/bin/xterm: removeFromUtmp: symbol not found
Error relocating /usr/bin/xterm: addToUtmp: symbol not found
````

**Comment by Gottox** [comment]
does installing libutempter fix this issue?

**Comment by cr6git** [comment]
Yes it fixes the issue.
We must add `depends="libutempter"` to the template then.

**Comment by Gottox** [comment]
bd63cd7ac909117e93e113e3d5c73631a40bbc09
