### ISSUE TITLE
Thunderbird UI and dialog have no text

### ISSUE THREAD

**Issue by noblehelm** [voidlinux/void-packages#13533]
### System

* xuname:  *Void 4.15.15_1 x86_64 GenuineIntel uptodate rrFFFFF*
* package:  *thunderbird-52.7.0_1*

### Expected behavior
UI text, dialog should have text
### Actual behavior
No text is shown.
![Screenshot](https://i.imgur.com/Y1s2rG8.png)
### Steps to reproduce the behavior
* Install *thunderbird* and any i18n pack
* Open *thunderbird*

**Comment by Chocimier** [comment]
Can't reproduce. What is your _any_  i18n pack?

**Comment by noblehelm** [comment]
I tried four different packs:

* *thunderbird-i18n-en-US*
* *thunderbird-i18n-en-GB*
* *thunderbird-i18n-pt-BR*
* *thunderbird-i18n-ru*

It did not work. I tried launching thunderbird with --UILocale set to a different locale (matching the i18n packs installed) and still nothing shows up.

The only line that shows up in console when launching in it is this:

`[calBackendLoader] Using Thunderbird's builtin libical backend`

I understand something is wrong with my system, but I can't pinpoint what it is. For more info, here is my fontconfig config file:

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
	<alias>
		<family>serif</family>
		<prefer><family>Liberation Serif</family></prefer>
	</alias>
	<alias>
		<family>sans-serif</family>
		<prefer><family>Liberation Sans</family></prefer>
	</alias>
	<alias>
		<family>monospace</family>
		<prefer><family>Fantasque Sans Mono</family></prefer>
	</alias>
</fontconfig>


```

**Comment by noblehelm** [comment]
Yes, I tried removing the profile many times and it didn't work. I tried even launching thunderbird with a fresh profile with the --UIProfile flag. It also did not work.

I also tried altering, and even removing, my fontconfig file and it seems to have no effect on it.

**Comment by newbluemoon** [comment]
Please try to start thunderbird via

`LANG=C thunderbird`

Does that work?

**Comment by noblehelm** [comment]
Yes, I tried using `LANG=C` and it did not work.

I did run thunderbird using `strace` and I copied over all search matches to "font" (and a little bit around it to provide context): [here](https://ghostbin.com/paste/524gk).

**Comment by noblehelm** [comment]
Unfortunately, I couldn't figure out what was the problem behind this, so I backed up my data and did a full reinstall of the system. It works as intended now. Not sure why it was that way before.
With that said, I apologize for this. I'm closing this issue. Thanks in advance for the help.
