### ISSUE TITLE
Package Request: ttf-inconsolata

### ISSUE THREAD

**Issue by Wqer555** [voidlinux/void-packages#1355]
A fantastic programming font. 

http://levien.com/type/myfonts/inconsolata.html

**Comment by logenkain** [comment]
On Mon, Apr 20, 2015 at 03:05:02PM -0700, Wqer555 wrote:
> http://levien.com/type/myfonts/inconsolata.html

It is a nice looking font, but here is a quote from that page:

"It will be released under the new Open Font License of SIL."

This tells me that it technically doesn't have a license right now, I
would feel uncomfortable trying to put it into any distribution without
contacting the author first.

Not saying we can't do it, but I want to bring it to the attention of
anyone who decides to package it.

**Comment by chneukirchen** [comment]
logenkain <notifications@github.com> writes:

> On Mon, Apr 20, 2015 at 03:05:02PM -0700, Wqer555 wrote:
>> http://levien.com/type/myfonts/inconsolata.html
>
> It is a nice looking font, but here is a quote from that page:
>
> "It will be released under the new Open Font License of SIL."
>
> This tells me that it technically doesn't have a license right now, I
> would feel uncomfortable trying to put it into any distribution without
> contacting the author first.
>
> Not saying we can't do it, but I want to bring it to the attention of
> anyone who decides to package it.

Debian packages this as Open Font License SIL.  Should be fine.

-- 
Christian Neukirchen  <chneukirchen@gmail.com>  http://chneukirchen.org
