### ISSUE TITLE
Package request: gcalcli

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1361]
https://github.com/insanum/gcalcli

**Comment by teh-jazzman** [comment]
How about this:

    xbps-install -S python-pip
    pip install gcalcli

**Comment by thypon** [comment]
how about this

    xbps-install -S python-pip
    sudo pip install gcalcli

Would you run a custom python script from internet giving root priviledges during install phase? Packaging and distributions are a matter of trust and i don't trust python packages so much.
