### ISSUE TITLE
CopyAgent sha256sum mismatch

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1366]
The file Copy.tgz downloaded from https://copy.com/install/linux/Copy.tgz hash is f33c0297c2d8f7e90ec481beed88a918446a87507c9ea29f8feae21a4e85f72e
The template says
checksum=f474099d86baadd05758fa33164dae44b0127933f73c6a6a6e2f243bbf62bc42
Since there is no version number, I guess this will happen every now and then.

**Comment by bougyman** [comment]
It will, unfortunately.
