### ISSUE TITLE
Improvement: README.md distcc description

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1367]
With the given description alone, a build slave's distcc does not accept any connections, since it isn't configured to accept the host's IP address. Editing `/etc/distcc/clients.allow` on the slave and appending e.g. a network mask like `192.168.2.0/24` does not help, perhaps because this file isn't used at all by the service...

The script `/etc/sv/distccd/run` however has an explicit `--allow 127.0.0.1` parameter.

After manually appending another `--allow 192.168.2.0/24` it seems the host can now distribute compiler jobs to that slave. I'm not quite sure what should be improved: the documentation in README.md, the /etc/sv/distccd/run script or even something else.

To me it seems the /etc/sv/distccd/run script should check for and use `/etc/distcc/clients.allow`, just like the `${wrksrc}/packaging/RedHat/init.d/distcc` script does it. Or, alternatively, the clients.allow file should not be installed to avoid confusion.

A clarification if one has to increase XBPS_MAKEJOBS to account for the total number of cores, or if the xbps-src scripts handle that aspect would be helpful as well.

**Comment by xtraeme** [comment]
- Probably README.md and distcc/run must be improved and updated.
- XBPS_MAKEJOBS isn't automatic right now, but if you use distcc, you definitely shall set it.

**Comment by pullmoll** [comment]
I think the distcc syntax for `<hostname>/<jobs>` should be mentioned in README.md as well, i.e. how to define how many cores are to be used on a specific host.
I also think that adding localhost or the host's IP address to XBPS_DISTCC_HOSTS should be mentioned, because otherwise only the slaves are used to compile, if I'm not totally wrong on this.

**Comment by xtraeme** [comment]
@pullmoll any update on this?

**Comment by pullmoll** [comment]
The original issue was fixed long ago, i.e. you can (and should) modify `/etc/distcc/clients.allow` after installation.
The documentation in `README.md` part is TODO. I'll try to write a more realistic description, based on how I use it here, ASAP.
