### ISSUE TITLE
Rasperry Pi 2: cant install retroarch-1.7.1_1

### ISSUE THREAD

**Issue by vetzki** [voidlinux/void-packages#13672]
### System

* xuname:  
`Void 4.14.30_1 armv7l-musl  uptodate rrn`

* package:  
`retroarch-1.7.1_1`

### Expected behavior
- able to install package

### Actual behavior
- wont install:
```
[mv@void-live ~]$ sudo xbps-install -S retroarch
[*] Updating `https://repo.voidlinux.eu/current/musl/armv7l-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/armv7l-musl-repodata' ...
retroarch-1.7.1_1: broken, unresolvable shlib `libbrcmEGL.so'
retroarch-1.7.1_1: broken, unresolvable shlib `libbrcmGLESv2.so'
retroarch-1.7.1_1: broken, unresolvable shlib `libbrcmOpenVG.so'
Transaction aborted due to unresolved shlibs.
[mv@void-live ~]$ ls /opt/vc/lib/libbrcm*
/opt/vc/lib/libbrcmEGL.so  /opt/vc/lib/libbrcmGLESv2.so  /opt/vc/lib/libbrcmOpenVG.so  /opt/vc/lib/libbrcmWFC.so
```
note:
installing retroarch worked before, couldn't update because of above issue, so deinstalled retroarch and cant reinstall again

### Steps to reproduce the behavior
try to install retrorach on rasperry pi 2

**Comment by newbluemoon** [comment]
This is because rpi-userland (which the libraries belong to) doesn’t list them and so xbps-install cannot find them. The PR will fix this.
