### ISSUE TITLE
utox: new release out, links with toxcore 0.2

### ISSUE THREAD

**Issue by avoidr** [voidlinux/void-packages#13717]
New utox release is out and depends on toxcore 0.2. Please re-add package to repo.
https://github.com/uTox/uTox/releases/tag/v0.17.0
Revert #12826

@Spencer-H @maxice8

**Comment by maxice8** [comment]
On Sat, Apr 21, 2018 at 03:19:47PM -0700, avoidr wrote:
> New utox release is out and depends on toxcore 2. Please re-add package to
> repo.
> @Spencer-H @maxice8
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

working on it

**Comment by maxice8** [comment]
fucking git submodules

**Comment by maxice8** [comment]
and it's merged

**Comment by avoidr** [comment]
Thanks.
