### ISSUE TITLE
Package Request: openbox-patched

### ISSUE THREAD

**Issue by lainsce** [voidlinux/void-packages#13775]
https://github.com/dylanaraps/openbox-patched

A patched Openbox with the support for rounded corners.

Should be easy to port as it has a PKGBUILD for Arch Linux in that repo.

**Comment by cr6git** [comment]
@lainsce I added a build option in the template.

**Comment by lainsce** [comment]
Thanks!

**Comment by Vaelatern** [comment]
Ew ew ew.

**Comment by lainsce** [comment]
It's as my grandma said, "One's taste is unique, just like that old woman's fondness for phlegm".
So if you think it's "ew", at least be happy the PR was an optional thing inside the openbox pkg.

**Comment by lainsce** [comment]
Rest assured that this patchset does not destabilise the system with rogue stuff or bad code. :wink:

**Comment by Vaelatern** [comment]
Then it should be upstreamed.

**Comment by lainsce** [comment]
If the main devs accept such patches though. Openbox is "feature-complete" in their eyes.
