### ISSUE TITLE
X crash nvidia 390.25_1

### ISSUE THREAD

**Issue by AngelFreak** [voidlinux/void-packages#13798]
### System

* xuname:  
  Void 4.14.35_1 x86_64 GenuineIntel notuptodate rrrmFFF
* package:  
  nvidia 390.25_1

### Expected behavior
Xorg start.
### Actual behavior
Xorg cannot start. 
The nvidia 384.98 works fine
### Steps to reproduce the behavior
Install nvidia 390.25_1 on NVIDIA Corporation GM108M [GeForce 940MX].

Error from dmesg: 
x cannot start.
error nvidia Unkown symbol swiotlb_map_sg_attrs

**Comment by AngelFreak** [comment]
Should be fixed when merged: https://github.com/voidlinux/void-packages/pull/13771

**Comment by anko** [comment]
#13771 is merged, and X11 works for me with `xuname` `Void 4.16.7_1 x86_64 AuthenticAMD uptodate rrrrmmnF` with a 1050 Ti.

Confirm on your setup?

**Comment by AngelFreak** [comment]
Yes issue is now fixed.
