### ISSUE TITLE
Firefox tab crashes on login pages

### ISSUE THREAD

**Issue by fxkrait** [voidlinux/void-packages#13791]
Video: https://youtu.be/fAzN4ZHVnkU
### System

* xuname:  
  *Void 4.16.3_1 x86_64-musl GenuineIntel notuptodate r*
* package:  
  *firefox-59.0.2_3*

### Expected behavior
  Able to login to a website using form. 
  By either click on or using tab to move from
  user name to password form.
### Actual behavior
   Tab Crashes.
### Steps to reproduce the behavior
   Go to login page. 
   Click on user login form.
   Click on, or hit tab to reach password form.
   Tab crashes.

**Comment by Duncaen** [comment]
Same issue as https://github.com/voidlinux/void-packages/issues/11532.

If you reproduce the crash with the sandbox log that would be more usefull than a video.
`MOZ_SANDBOX_LOGGING=1 firefox`.

**Comment by fxkrait** [comment]
This is the error from log.

###!!! [Parent][MessageChannel] Error: (msgtype=0x150080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv

**Comment by fxkrait** [comment]
This issue is fixed in firefox 60.0_2
