### ISSUE TITLE
mame-tools/chdman not included in $PATH

### ISSUE THREAD

**Issue by breadcat** [voidlinux/void-packages#13835]
### System

* xuname:  
``Void 4.14.22_2 x86_64-musl GenuineIntel uptodate rrnF``
* package:  
``mame 0197``

### Expected behavior
``$ chdman
chdman - MAME Compressed Hunks of Data (CHD) manager 0.196 (unknown)
Usage:
   /usr/share/mame/chdman info: displays information about a CHD
   /usr/share/mame/chdman verify...``

### Actual behavior
``$ chdman
-bash: chdman: command not found``

### Steps to reproduce the behavior
Install the `mame` package, run chdman. This will fail.
`chdman` can be found in `/usr/share/mame/chdman`

My `$PATH` variable is currently set as `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin`

**Comment by pullmoll** [comment]
I'll check to see which, if not all, tools can be installed to `/usr/bin`.
If there are name conflicts, we'd have to rename them e.g. `imgtool` to `mame-imgtool`.
Of course you can simply add `/usr/share/mame` to your account's `$PATH` in e.g. `.profile`:
```
[ -d /usr/share/mame ] && export PATH="$PATH:/usr/share/mame"
```
