### ISSUE TITLE
rtl8723be from linux-4.16 has weak WiFi signal.

### ISSUE THREAD

**Issue by crocket** [voidlinux/void-packages#13832]
### System

* xuname:  
  *Void 4.15.15_1 x86_64 AuthenticAMD notuptodate hold rrrmDD*
* package:  
  *linux-4.16*

### Expected behavior

`options rtl8723be ant_sel=2` in `/etc/modprobe.d/rtl8723be.conf` should select the second antenna

### Actual behavior

`ant_sel` is ignored by linux-4.16. Linux-4.15 respects `ant_sel`.
When `ant_sel` is ignored, WiFi signal goes down from 64\~82 to 28\~30. 100 is the full signal strength.

I had to downgrade linux to 4.15 and lock it by executing `xbps-pkgdb -m hold linux`.

### Steps to reproduce the behavior

Install linux-4.16 by `xbps-install -Su`.

### Suggestion

I suggest downgrading linux to 4.15 or upgrading linux to a better version or patching linux4.16.

**Comment by Gottox** [comment]
Linux 4.15 is already EOL. I suggest reporting the issue to the upstream kernel and install linux-lts and/or linux4.14.

**Comment by crocket** [comment]
I guess I'll install linux-lts. I didn't know voidlinux has linux-lts.
