### ISSUE TITLE
xdiff from xtools has two issues.

### ISSUE THREAD

**Issue by crocket** [voidlinux/void-packages#13833]
1. `xtools` doesn't explicitly depend on vimdiff from vim.
2. `xdiff` executes `vimdiff` instead of `vimdiff -d`.

The following patch improves `xdiff`'s code.

```
--- xdiff.orig	2018-04-25 12:48:45.966078993 +0900
+++ xdiff	2018-04-25 12:48:06.912047894 +0900
@@ -2,7 +2,7 @@
 # xdiff [-u|-l] [DIR] - merge/diff/list XBPS .new-* files
 
 mergeutil() {
-	vimdiff "$1" "$2" && rm -vi "$1"
+	vimdiff -d "$1" "$2" && rm -vi "$2"
 }
 
 listutil() {
@@ -22,5 +22,5 @@
 DIR=${1:-/etc}
 
 for newfile in $(find "$DIR" -name '*.new-*_*'); do
-	$DIFF "$newfile" "${newfile%.new-*_*}"
+	$DIFF "${newfile%.new-*_*}" "$newfile" 
 done
```

**Comment by Vaelatern** [comment]
Open an issue or PR https://github.com/chneukirchen/xtools/

**Comment by crocket** [comment]
I created https://github.com/chneukirchen/xtools/pull/88 to fix xdiff.
But, xdiff template should be fixed in void-packages.

**Comment by crocket** [comment]
I also created https://github.com/voidlinux/void-packages/pull/13834 to fix xtools template.

**Comment by crocket** [comment]
This issue has moved to xtools.
