### ISSUE TITLE
Xwayland segfaults

### ISSUE THREAD

**Issue by espectalll** [voidlinux/void-packages#13931]
### System

* xuname:  
  ``Void 4.16.4_2 x86_64-musl GenuineIntel uptodate r``
* package:  
  `xorg-server-xwayland` 1.19.6_4

GPU is an Nvidia Geforce 9400M. Also notice how I'm using Musl.

### Expected behavior

`Xwayland` should start up and work, either when calling it manually or when used within e.g. GNOME Shell or Weston.

### Actual behavior

`Xwayland` only returns the following log when manually executed from e.g. a Weston session:

    glamor: EGL version 1.4 (DRI2):
    Segmentation fault

Further taking a look using `strace` I got [this log](http://dpaste.com/24KW3HX). ~~Because this is my first time reading such a thing, this is only my best guess, but I believe this is the specific problem:~~

    open("/lib/libOpenGL.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/local/lib/libOpenGL.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
    open("/usr/lib/libOpenGL.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

~~As far as I know, there is no package which contains `libOpenGL.so.0` on Musl Void.~~

**Updated**: At first I considered that it was due to the lack of `libOpenGL.so.0`, but further testing proved that this is very likely not the case. Most likely it has to do with Nouveau, but I don't know how to check this. 

### Steps to reproduce the behavior

1. Launch a Wayland session with e.g. Weston.
2. Open a terminal and run `Xwayland`.

**Comment by Johnnynator** [comment]
Works fine for me on my Laptop with only a Intel iGPU. Also `libOpenGL.so.0` is in the `nvidia-libs` package.

**Comment by espectalll** [comment]
I can't find any `nvidia-libs` package on Musl Void... because it's not built in the first place. I guess that's the issue? https://github.com/voidlinux/void-packages/blob/83513d36efafa739373a0f06d6f4f5e21f8dbb3e/srcpkgs/nvidia/template

**Comment by Johnnynator** [comment]
Oh yeah.. I totally missed that.

**Comment by Johnnynator** [comment]
You could dry to downgrade libepoxy to smth pre 1.5.0.

**Comment by espectalll** [comment]
Maybe, if that's a related issue. I didn't even know it exists, but it certainly is a dependency for `xorg-server-xwayland`... *but*...

I'm also noticing that some stuff with OpenGL fails. In particular, first I tried to use the `totem` media player, but it crashed after it tried to play any video track (audio works fine). `mpv` has no issues whatsoever.

Then I tried to use an OpenGL test, and I picked up `glmark2`. First time it segfaulted before working. The rest of times it worked fine, *except when trying to close by clicking on the close button*, where the whole computer hanged up.

None of these packages seem to depend on `libepoxy` from what I can tell.

**Comment by Johnnynator** [comment]
So the segfault is completely unrelated to your quoted part of the strace :D.

**Comment by espectalll** [comment]
No idea. Back to the `Xwayland` log, here's what immediately follows after trying to load `libOpenGL.so.0`: 

    epoll_ctl(3, EPOLL_CTL_ADD, 7, {0, {u32=4017521792, u64=140191750063232}}) = 0
    epoll_ctl(3, EPOLL_CTL_MOD, 7, {EPOLLIN, {u32=4017521792, u64=140191750063232}}) = 0
    ioctl(10, DRM_IOCTL_NOUVEAU_GEM_PUSHBUF, 0x7ffc2ec6ff50) = 0

Then it keeps increasing `brk` for a while, shows this error:

    open("/home/xerz/.cache/mesa_shader_cache/85/9dca46547c08d42de71ee0b2a7ba109a4f3adb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

Does a few more `brk`s and finally:

    futex(0x7f80f2012804, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x562657a40504, FUTEX_WAKE_PRIVATE, 1) = 1
    +++ killed by SIGSEGV +++

No idea where those addresses point to, neither what these futex are supposed to be or do.

Here's [a new log](https://paste.gnome.org/p85va2uex) for `totem` too... turns out, it looks quite familiar. To begin with, I've found this:

    ioctl(12, DRM_IOCTL_NOUVEAU_GEM_NEW, 0x7fff3d96a5d0) = 0
    open("/home/xerz/.cache/mesa_shader_cache/08/58e4b0e654df41a38cc0ea944053b59196f622", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

Next you get a lot of `brk`s with a futex repeated in between...

    futex(0x7f1d769d1e18, FUTEX_WAKE_PRIVATE, 1) = 1

In particular, at line 24421:

    futex(0x7f1d769d1e18, FUTEX_WAIT_PRIVATE, 1, NULL) = -1 EAGAIN (Resource temporarily unavailable)

and finally:

    madvise(0x55e3048e4000, 225280, MADV_DONTNEED) = 0
    futex(0x7f1d76802164, FUTEX_WAKE_PRIVATE, 1) = 1
    futex(0x55e3031b6304, FUTEX_WAKE_PRIVATE, 1) = 1
    +++ killed by SIGSEGV +++

I wish I understood this tbh.

**Comment by espectalll** [comment]
Trying to debug from both the debug repo and my self-built packages, but I can't stop getting a CRC mismatch error. Any help will be welcome.

**Comment by espectalll** [comment]
Well it doesn't happen anymore, for whatever reason... :woman_shrugging:
