### ISSUE TITLE
minetest: xbps-query displays wrong homepage

### ISSUE THREAD

**Issue by avoidr** [voidlinux/void-packages#13938]
I know that the homepage has been corrected in #10991, but after `xbps-install -S`, the wrong homepage is still displayed in `xbps-query -RS minetest`. I have no idea why this is happening. Any suggestions?

**Comment by Johnnynator** [comment]
It was only updated in the template but the package didn't get rebuilt yet. It will be once the version get updated.

**Comment by avoidr** [comment]
Ok, thank you!
