### ISSUE TITLE
dracut-047_4 for i686 is missing

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#13940]
### System

* package:  `dracut-047_4` for i686

### Expected behavior
````
# ./mklive.sh -a i686
````
Should work...

### Actual behavior
After the [last update](https://github.com/voidlinux/void-packages/commit/d82c735085360667944fe67182e42199fa2239c4) this package is missing:
````
# ./mklive.sh -a i686
[...]
[3/9] Installing void pkgs into the rootfs:
MISSING: dracut-047_4
Transaction aborted due to unresolved dependencies.
ERROR: Missing required binary packages, exiting...
````
:disappointed:

**Comment by Duncaen** [comment]
I'm sure that's because of the long build queue.

**Comment by Johnnynator** [comment]
@cr6git You probably can close this issue.

**Comment by cr6git** [comment]
Yes, solved ! :+1:
