### ISSUE TITLE
xfsprogs-4.16.0_1 has broken fsck.xfs

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#13955]
### System

* xuname:  
  * Void 4.16.5-chrysalis x86_64-musl GenuineIntel uptodate rFFF
* package:  
  * xfsprogs-4.16.0_1

### Expected behavior
To be able to perform `fsck.xfs` and boot the system without errors from it.

### Actual behavior
```
➤ fsck.xfs
/usr/bin/fsck.xfs: 9: /usr/bin/fsck.xfs: Syntax error: "(" unexpected
```
Boot process stalls because of that.

### Steps to reproduce the behavior
Install xfsprogs, enable fsck in fstab, reboot.

Previous version works OK.

**Comment by maxice8** [comment]
1	#!/bin/sh -f
     9	function repair2fsck_code() {

Found the problem

**Comment by maxice8** [comment]
cooking up a fix, just a sed to replace it with bash

**Comment by Vintodrimmer** [comment]
Thanks!

Why did it work with dash before?

**Comment by maxice8** [comment]
On Sun, Apr 29, 2018 at 11:59:03AM -0700, Vintodrimmer wrote:
> Thanks!
> 
> Why did it work with dash before?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

it didn't use bashisms anywhere, it started using the `function <name>` bashism, in POSIX you just do `name()`
