### ISSUE TITLE
nvi Segfault on i686

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#13950]
### System

* xuname:  `Void 4.16.4_1 i686 GenuineIntel uptodate rF`

* package:  `nvi-1.81.6_16`

### Expected behavior
Should work.
### Actual behavior
````
# vi
Segmentation fault
````

**Comment by abenson** [comment]
backtrace, etc?

**Comment by cr6git** [comment]
just made a new test today: it works flawlessly. :sweat_smile: 
I close this.
