### ISSUE TITLE
Thunderbird cannot open libwayland-egl.so.1

### ISSUE THREAD

**Issue by Chocimier** [voidlinux/void-packages#13976]
### System

* xuname:  
  Void 4.16.4_1 x86_64 GenuineIntel uptodate
* package:  
  thunderbird-52.7.0_1

### Expected behavior
It will start.
### Actual behavior
$ thunderbird 
XPCOMGlueLoad error for file /usr/lib/thunderbird/libmozgtk.so:
libwayland-egl.so.1: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

**Comment by Duncaen** [comment]
There was some file conflict between `wayland` and `libwayland-egl`, `xbps-install -f libwayland-egl` fixes it.

**Comment by Chocimier** [comment]
Shouldn't there be a revbump to pull correct dependency?

**Comment by maxice8** [comment]
> Shouldn't there be a revbump to pull correct dependency?

nothing about dependencies.

**Comment by Anachron** [comment]
Btw, the same thing happens on `firefox`, also gets fixed by installing ` libwayland-egl`.

**Comment by Duncaen** [comment]
Its exactly the same problem and happens to everything that links to wayland-egl.
