### ISSUE TITLE
apache-2.4.29_3 (x86_64)

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#13989]
Apache 2.4.29_3 failed to load mod_ssl

* package:  
  apache-2.4.29_3 

### Expected behavior
should load mod_ssl and work whithout errors

### Actual behavior
Cannot load /usr/libexec/httpd/mod_ssl.so into server: /usr/libexec/httpd/mod_ssl.so: undefined symbol: OPENSSL_malloc_init

### Steps to reproduce the behavior
Upgrade to apache 2.4.29_3

**Comment by maxice8** [comment]
Paging @Gottox , problably related to libressl rebuild
