### ISSUE TITLE
libXext - build fails when cross-compiling

### ISSUE THREAD

**Issue by jprjr** [voidlinux/void-packages#1399]
Hi there - 

I'm trying to cross-compile vim for x86_64-musl, and I'm hitting an error when it starts building libXext:

```
checking whether malloc(0) returns NULL... configure: error: in `/builddir/libXext-1.3.3':
configure: error: cannot run test program while cross compiling
```

It looks like there's a configure option where you can specify if malloc(0) returns NULL or not:

```
  --enable-malloc0returnsnull
                          malloc(0) returns NULL (default: auto)
```

AFAICT, musl returns a valid pointer for malloc(0), I think glibc is the same way - I'm not sure if the right answer is to just add `--enable-malloc0returnsnull` to the list of configure args.

**Comment by xtraeme** [comment]
This is the right way, thanks.
