### ISSUE TITLE
tar: build fails with unshare

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1403]
It needs `configure_args="... FORCE_UNSAFE_CONFIGURE=1"` or configure will fail; at least with `XBPS_CHROOT=proot`.

**Comment by xtraeme** [comment]
- What user is running xbps-src? `void-packages/common/chroot-style/proot.sh` does not use `-0` to make it uid:gid 0 aka root.
- What do you use in `etc/conf` ?

**Comment by pullmoll** [comment]
Oops, that was false information, sorry.
I had thought it was proot, but I copied a etc/conf where unshare is used.
My own account, member of group xbuilder. etc/conf looks like this:
```
XBPS_CHROOT_CMD=unshare
XBPS_CCACHE=yes
XBPS_MAKEJOBS=5
```
Error message is:
```shell
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
See `config.log' for more details
=> ERROR: tar-1.28_5: failed to run do_configure() at line 7.
```
With proot it works.

**Comment by xtraeme** [comment]
Assigned to @Gottox that contributed this part.

**Comment by xtraeme** [comment]
The `unshare` chroot-style should not use uid:gid 0, but rather the current euid:egid for the current user. This way there's no need to export this var to the GNU configure scripts.
