### ISSUE TITLE
Latest dash broke my xinitrc

### ISSUE THREAD

**Issue by loreb** [voidlinux/void-packages#14123]
### System

* xuname:  
  Void 4.16.6_1 x86_64-musl GenuineIntel uptodate r
* package:  
  dash-0.5.10_1

### Expected behavior
Xscreensaver etc stay in the background

### Actual behavior
Given enough subshell abominations dash waits for them!

### Steps to reproduce the behavior
```sh
#! /bin/sh
echo prechild
# Comment the following line and everything is ok
# In real life, this would be xscreensaver etc
sleep 12& # random child, which I expect the shell will *not* be waiting for!!!
echo spawned
(
echo sub
(
echo subsub
# iff not on battery!
on_ac_power || exec acpi -b
echo xinitrc whatever
# scripts to check for a few things I care about - eg did a new package land in void?
) &
echo spawned subsubshell
)
echo back to main shell
```

I expect the shell will not wait for the "sleep&", but dash does - it was ok yesterday and it's ok today with any shell I tried other than /bin/dash

**Comment by chneukirchen** [comment]
Reported upstream.

**Comment by Vintodrimmer** [comment]
I'd like to report that `bspwm`' doesn't work with new `dash` also. Had to fall back to `bash`.

**Comment by Vaelatern** [comment]
```
» xbps-query -RS dash
alternatives:
  sh:
        sh:/usr/bin/dash
        sh.1:/usr/share/man/man1/dash.1
architecture: x86_64
build-date: 2017-08-27 20:25 CEST
filename-sha256: 32733cea68dbe125ba7bc8f60652a033da5813711f709220ad5702bba6302673
filename-size: 70KB
homepage: http://gondor.apana.org.au/~herbert/dash/
installed_size: 183KB
license: BSD
maintainer: Juan RP <xtraeme@voidlinux.eu>
pkgver: dash-0.5.9.1_2
repository: https://repo.voidlinux.eu/current
shlib-requires:
        libc.so.6
short_desc: POSIX-compliant Unix shell, much smaller than GNU bash
source-revisions: dash:b963471b0e
```

Upstream is at that homepage.

**Comment by Vintodrimmer** [comment]
Can you report it, please?

My mail from Gmail got rejected for possibly containing a virus and one from Protonmail just says that it was unable to be delivered and suggests contacting the postmaster.

**Comment by maxice8** [comment]
> I'd like to report that bspwm doesn't work with new dash either.
Had to fall back to bash.

bspwm works fine here with latest dash. problably some specific configuration.

**Comment by Vintodrimmer** [comment]
Do you have it declared(?) in `bspwmrc`?
I.e. `#! /bin/dash`?

**Comment by maxice8** [comment]
On Sat, May 05, 2018 at 06:36:12AM +0000, Vintodrimmer wrote:
> Do you have it declared(?) in bspwmrc?
> I.e. #! /bin/dash?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

/bin/dash no but /bin/sh which is a symlink to dash yes.

**Comment by Vintodrimmer** [comment]
Interesting, though I'm not sure what to make of it.
I had `/bin/sh` and after update it just stopped working(as in no workspaces created, all rules and colors ignored) until I substituted it with `/bin/bash`.

I don't think there is anything unusual about my configuration.
```
#! /bin/bash

sxhkd &

bspc config border_width                3
bspc config window_gap                  7
bspc config top_padding                 0

bspc config split_ratio                 0.50
bspc config borderless_monocle          false
bspc config gapless_monocle             false
bspc config focus_follows_pointer       false
bspc config click_to_focus              none
bspc config ignore_ewmh_focus           true

bspc monitor -d i ii iii iv v vi vii viii ix x

bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled

# Theme
bspc config normal_border_color         "#98bbfb"
bspc config active_border_color         "#cab775"
bspc config focused_border_color        "#f6a299"
bspc config presel_feedback_color       "#f6a299"⏎
```

**Comment by maxice8** [comment]
> sxhkd &

i'd think this is the reason why,

here is mine

```
$ cat ~/etc/bspwm/bspwmrc
#!/bin/sh

bspc config border_width 1
bspc config pointer_follows_focus true

bspc config focused_border_color '#F75341'
bspc config normal_border_color '#2D2B28'

# Make all windows floating
bspc rule -a "*" state=floating

bspc rule -a '*:Firefox' desktop='^1'
bspc rule -a '*:firefox' private=on

# Create workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Adopt orphans
bspc wm -o
```

i start sxhkd without problems on my .xinitrc

```
$ cat /home/terran/etc/X11/xinitrc
setxkbmap br &
xset +fp /usr/share/fonts/misc 
xset +fp ~/.fonts
xset fp rehash
xset r rate 300 50 &
xrdb "${XDG_CONFIG_HOME}"/X11/xresources
for area in focus desktop clock mail memory battery volume music; do
	run-bar "$area"-bar &
done
mpd &
sxhkd &
xbanish &
bspwm &
rndw &
start-pulseaudio-x11 &
sudo sh -c 'echo 1 > /sys/class/backlight/intel_backlight/brightness' 
export DISPLAY=:0 && exec dbus-launch --exit-with-session xwait
# vim: ft=sh
```

**Comment by Vintodrimmer** [comment]
Thanks, it works that way!

Though I'd still blame newest dash update, as this change in default config was introduced around 3 bspwm versions ago and was working correctly prior to yesterday.

On an unrelated note, it's interesting how different everyone's configs and dotfiles are.

**Comment by maxice8** [comment]
> Though I'd still blame newest dash update, as this change in default config was introduced around 3 bspwm versions ago and was working correctly prior to yesterday.

it certainly has something to do with it

> On an unrelated note, it's interesting how different everyone's configs and dotfiles are.

it would be sligthly creepy to find people making identical dotfiles (assuming they don't have them on github/gitlab/somewhere)
