### ISSUE TITLE
Package request: texlive-2018

### ISSUE THREAD

**Issue by ibabushkin** [voidlinux/void-packages#14120]
### System
* xuname:  ` Void 4.15.15_1 x86_64 GenuineIntel uptodate rF`
* package:  `texlive-bin-2017_1`

### Expected behavior
A working `tlmgr` that installs packages etc.

### Actual behavior
The texlive maintainers switching the mirrors, necessiating an update to this year's release.

### Steps to reproduce the behavior
Install texlive 2017, marvel at the error message when doing `tlmgr install <somepkg>` as root.

### Workaround (non-satisfactory in many situations)
Running the following points `tlmgr` at the right repo, but using the new release would be less painful:
```sh
# tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
```

**Comment by Johnnynator** [comment]
i already opened a PR #13947 for Texlive 2018. Will hopefully merged Soon.

**Comment by newbluemoon** [comment]
This should have been fixed by #14048, but you’re still at `2017_1`.
And there’s already a PR for TeXLive 2018: #13947.

**Comment by Johnnynator** [comment]
@newbluemoon Nope. That change only fixes only works if the package gets newly installed and not for smth that was already installed before.

**Comment by newbluemoon** [comment]
@Johnnynator Yes, of course! Sorry, I was mistaken. ;)
