### ISSUE TITLE
NetworkManager native build

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#14260]
Next package failing: NetworkManager.
```
configure: error: "--enable-introspection aims to build the settings documentation. This requires GObject introspection for python (pygobject)
=> ERROR: NetworkManager-1.10.6_1: do_configure: '${configure_script} ${configure_args}' exited with 1
=> ERROR:   in do_configure() at common/build-style/gnu-configure.sh:7
```
I'm curious to see if this one also vanishes all of a sudden :-P

**Comment by maxice8** [comment]
Tried working on it once, gave up, cross-build is also fucked.

**Comment by pullmoll** [comment]
Got it working by removing the `!` before `"$PYTHON" -c 'from gi…`' in `configure` in the `pre_configure()` stage.
It seems as if this test with `!` is just plain wrong, since result code `0` should be ok.

Cleaning up the template and will push to master then.
