### ISSUE TITLE
dash 0.5.10 error

### ISSUE THREAD

**Issue by dinama** [voidlinux/void-packages#14282]
### System

* xuname:   Void 4.16.7_1 x86_64 GenuineIntel uptodate hold rrFFF
* package:  dash-0.5.10_3

### Error

```
$ cat test
foo='x\
y'
echo "$foo"

$ dash-0.5.10 test
xy

$ dash-0.5.9.1 test
x\
y

$ bash test
x\
y

```
[On this commit ](https://git.kernel.org/pub/scm/utils/dash/dash.git/commit/?id=ab1cecb4047864afb247a6ed691e7f59ce716f2c)

**Comment by dinama** [comment]
this error breaks compiling  other projects from sources, because Makefile is generated with errors broken 
need switching to previous version of dash or change it to bash (xbps-alternatives -s bash)

**Comment by chneukirchen** [comment]
Reported upstream.

**Comment by maxice8** [comment]
upstream patch https://git.kernel.org/pub/scm/utils/dash/dash.git/commit/?id=469c5fd4f57622b1a6571172898ab29430319d4a added.

```
$ cat /home/terran/bin/dash-test
#!/usr/bin/env dash
foo='x\
y'
echo "$foo"

$ xbps-query -S dash -p pkgver
dash-0.5.10.1_1

$ dash /home/terran/bin/dash-test
x\
y
```
