### ISSUE TITLE
nyx fails at startup with ModuleNotFoundError

### ISSUE THREAD

**Issue by copyleftie** [voidlinux/void-packages#14319]
### System

* xuname:  
  `Void 4.16.8_blackbox x86_64 GenuineIntel uptodate rFFFFF`
(I have tested on my musl-based fileserver and it's broken there too.)
* package:  
  `nyx-2.0.4_1`

### Expected behavior
`nyx` works.

### Actual behavior
```
% nyx
Traceback (most recent call last):
  File "/usr/bin/nyx", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by Johnnynator** [comment]
Can you try starting it after installing `python3-setuptools`?

**Comment by copyleftie** [comment]
Oh wow that was simple, thanks

**Comment by Johnnynator** [comment]
It still should be a dependency of it. I made a PR #14321
