### ISSUE TITLE
Font Awesome 5 update breaks icons

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#14361]
### System

* xuname:  
Void 4.16.3_1 x86_64 GenuineIntel uptodate rrrmFFFF
* package:  
font-awesome-5.0.10_1

### Expected behavior
All glyphs to be available like: http://epsi-rns.github.io/assets/posts/desktop/2017/04/font-03-awesome-xfontsel.png

### Actual behavior
Most glyphs are unavailable/broken: https://i.imgur.com/QI7ISqM.png

### Steps to reproduce the behavior
Download the font and inspect with `xfd -fa "Font Awesome 5 Free"`.

This issue breaks my lemonbar-script as most of the symbols are not working anymore.  I only display icons in my bar when something is wrong so I didn't recognize this issue until recently. 

## Relevant commits
https://github.com/voidlinux/void-packages/commit/e7d836ec69f5a0eab627b84082afe1d869d42964

**Comment by Anachron** [comment]
@cr6git since you made the update: Font-Awesome 5 is actually NOT an update to Font-Awesome 4. It rather is a rewrite of it and has different concept/functionality.

https://fontawesome.com/how-to-use/upgrading-from-4
Quote:
> Version 5 has been re-written and re-designed completely from scratch. We’ve tried to keep things as similar as possible to version 4, but there are a few steps you’ll need to do to upgrade.

The 4.7.0 version is still posted here: https://fontawesome.com/v4.7.0/

**Comment by Anachron** [comment]
Okay I've digged a bit deeper and it looks like the font is split into 3 parts: https://fontawesome.com/get-started/desktop

```
Font Awesome 5 Brands-Regular-400.otf
Font Awesome 5 Free-Regular-400.otf
Font Awesome 5 Free-Solid-900.otf
```

However, not all tools allow to supply 3 or more additional fonts to be loaded. This is bad!

**Comment by cr6git** [comment]
@Anachron done.

**Comment by Anachron** [comment]
I suggest packaging font-awesome 5 as a seperate pkg.  Can you do that? @cr6git
