### ISSUE TITLE
Emacs compiled without dbus support

### ISSUE THREAD

**Issue by lbolla** [voidlinux/void-packages#14364]
### System

* xuname:  
  Void 4.16.7_1 x86_64 GenuineIntel notuptodate rF

* package:  
  emacs 25.3

### Expected behavior
Emacs should be compiled with dbus support.

### Actual behavior
Instead, it's compiled with --without-dbus. If we really want to disable dbus support (why?), then also --without-gconf should be set as per this thread: https://lists.gnu.org/archive/html/emacs-devel/2012-07/msg00672.html

### Steps to reproduce the behavior
Start Emacs, see dbus started automatically, try to use notifications.el and see error message from Emacs.

**Comment by chneukirchen** [comment]
Only x11 is build without dbus, the gtk2 and gtk3 versions should be?

**Comment by lbolla** [comment]
@chneukirchen Indeed! Why this choice? Also, see mail thread linked above: presumably if disabling dbus support one also wants Emacs not to start it automatically, hence implying --without-gconf?

**Comment by lbolla** [comment]
I like the intent! But, for me, it looks like smtpmail requires "notifications.el" which requires "dbus" in order to work... So, I can't seem to be able to send emails without it...

**Comment by chneukirchen** [comment]
If you want the full desktop experience, just install emacs-gtk2 then?

**Comment by lbolla** [comment]
Yeah, that works. The mystery remains as to why Emacs requires dbus to send an email.
Thanks for your help!
