### ISSUE TITLE
xbps-src: can't use system_accounts= with name:uid:gid

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1450]
Trying to create a system account with a fixed uid and gid leads to the following error when installing the resulting package (here clamav):
```
/tmp/.xbps-script-gwMUuB: 31: export: clamav:132_homedir: bad variable name
```
The template has systemd_accounts="clamav:132:132", i.e. fixed uid and gid according to the docs.

So it looks like the code parsing for `<pkgname>_variable` in the template needs to strip anything after and including a colon, i.e. `pkgbase=${pkgname%%:*}`. I don't know where this piece of code is and therefore opened an issue.

Of course I do not really need to create a fixed uid/gid account at all and probably should't do that anyway.

**Comment by xtraeme** [comment]
You cannot use `user:uid:gid`, but you can use `user:id`, and `id` will be used for both `uid` and `gid`.

**Comment by pullmoll** [comment]
I misunderstood that section in Manual.md. Thanks for the clarification.
