### ISSUE TITLE
Missing dependency openresolv for wireguard

### ISSUE THREAD

**Issue by TehDaniel37** [voidlinux/void-packages#14517]
### System

* xuname:  
  Void 4.16.7_1 x86_64 GenuineIntel uptodate rrrrmmnFF
* package:  
  wireguard-0.0.20180514_1

### Expected behavior
Bring up a wireguard interface with `wg-quick mullvad-se1`.
### Actual behavior
Command fails with:
```bash
[#] ip link add mullvad-se1 type wireguard
[#] wg setconf mullvad-se1 /dev/fd/63
[#] ip address add 10.99.16.239/32 dev mullvad-se1
[#] ip address add fc00:bbbb:bbbb:bb01::10ef/128 dev mullvad-se1
[#] ip link set mtu 1420 dev mullvad-se1
[#] ip link set mullvad-se1 up
[#] resolvconf -a mullvad-se1 -m 0 -x
/usr/bin/wg-quick: line 73: resolvconf: command not found
[#] ip link delete dev mullvad-se1
```
### Steps to reproduce the behavior
- openresolv not installed
- try to bring up a wireguard interface with `wg-quick up <config>`

**Comment by TehDaniel37** [comment]
Opened a pull request here: #14518

**Comment by Piraty** [comment]
`openresolv` is not exactly mandatory to "bring up a wireguard interface". Just the `DNS=` field depends on it, so not everybody using wireguard is in need of this package.
