### ISSUE TITLE
Firefox needs update to 60.0.1

### ISSUE THREAD

**Issue by chmod77** [voidlinux/void-packages#14515]
**(Danger Bug) Long cycle collector pauses with an addon installed**
https://bugzilla.mozilla.org/show_bug.cgi?id=1449033

This bug result on a extreme lag when we type a text on input fields. Addons are in "toogle mode". Example:  the Ublock Origin, show and hide ads (randomic). For test: Just type www.google.com and press F5 (many times).

**Firefox 60.0.1 Relase Notes  (With The Fixs):**
https://www.mozilla.org/en-US/firefox/60.0.1/releasenotes/

**Thread on Firefox Official Sub on reddit**
Firefox 60.0.1 got released - fixes lags/performance issues caused by some 
https://old.reddit.com/r/firefox/comments/8jyj74/firefox_6001_got_released_fixes_lagsperformance/

**Comment by Gottox** [comment]
Aware; update will be pushed soon.

**Comment by Gottox** [comment]
Note: Performance regressions are by no means critical.

**Comment by Gottox** [comment]
https://github.com/voidlinux/void-packages/compare/ac44d9ea2bd6...b1d989b2edaf
