### ISSUE TITLE
vim fails to build on src

### ISSUE THREAD

**Issue by goosewood** [voidlinux/void-packages#14582]
### System

* xuname:  
Void 4.16.9_1 x86_64 GenuineIntel notuptodate hold rrrmF
* package:  
vim 8.1 or maybe python3-3.6.4_1/libgdbm?

### Expected behavior
Stock vim (no changes to the template) build without fail

### Actual behavior
"python3-3.6.4_1: broken, unresolvable shlib `libgdm.so.4'
transaction aborted due to unresoved shlibs
[full output](https://github.com/voidlinux/void-packages/files/2020601/output.txt)

### Steps to reproduce the behavior
./xbps-src pkg vim

**Comment by cr6git** [comment]
No, no problem for me.
Try: `xbps-src bootstrap-update`

**Comment by goosewood** [comment]
Oh boy, now the bootstrap is giving my errors. I'm just going to close it as I pretty sure my system is just trashed right now lol
