### ISSUE TITLE
falkon: update to qupzilla-2.2.6_3 orphans the package

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#14599]
### System

* xuname:  
  *Void 4.16.3_1 x86_64 GenuineIntel uptodate rrmDDDDDDDDFF*
* package:  
  *qupzilla-2.2.6_3 and falkon-3.0.1_2*

### Expected behavior
Update of the qupzilla meta package should leave falkon installed.

### Actual behavior

After updating the qupzilla package to qupzilla-2.2.6_3, xbps-remove -o wants to remove falkon.

```
# xbps-remove -on | grep falkon
falkon-3.0.1_2 remove x86_64 https://repo.voidlinux.eu/current 10031471 2185616
```
```
# xbps-query -S falkon | grep automatic
automatic-install: yes
```
### Steps to reproduce the behavior

Update the qupzilla package on a system that had it installed previously and doesn't already have falkon installed manually.

**Comment by asergi** [comment]
Everything is alright. You didn't notice it before because you kept both the new and the dummy package: `xbps-pkgdb -m manual falkon`.

**Comment by Hoshpak** [comment]
In what way is removing a package that I explicitely installed alright? As you mentioned, the transitional package was needed to keep the package installed, now a replaces has been added to the main package, causing the transitional package to be removed, in turn leading to both packages being removed. Are Void users expected to manually check for transitions and alter the state of transitioned packages manually each time they occur?

**Comment by Johnnynator** [comment]
Imo transitional packages shouldn't be removed since xbps-install cannot set a package that is pulled in by smth else as manual. Adding `replaces` to such a package will end in such problems.

**Comment by asergi** [comment]
> In what way is removing a package that I explicitely installed alright?

You didn't install `falkon` explicitly.

> Adding replaces to such a package will end in such problems.

`replaces` is not the problem. At a later time, if you want to remove the dummy package manually, then `xbps-remove -o` will try to remove `falkon` until you mark it as installed explicitly with: `xbps-pkgdb -m manual falkon`.

And thus we have come full circle.

**Comment by Hoshpak** [comment]
replaces is indeed the problem since it makes xbps remove the dummy package without user interaction. If I had removed the dummy package manually, I wouldn't even have mentioned it. 

Am 21. Mai 2018 11:00:07 MESZ schrieb Alessio Sergi <notifications@github.com>:
