### ISSUE TITLE
monero-gui: update of monero-core to 0.12.0.0_4 orphans the package

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#14600]
### System

* xuname:  
  *Void 4.16.3_1 x86_64 GenuineIntel uptodate rrmDDDDDDDDFF*
* package:  
  *monero-core-0.12.0.0_4 and monero-gui-0.12.0.0_4*

### Expected behavior

Update of the monero-core meta package should leave monero-gui intact.

### Actual behavior

monero-core is removed and `xbps-remove -o' wants to remove monero-gui afterwards:

```
# xbps-remove -on | grep monero-gui
monero-gui-0.12.0.0_4 remove x86_64 https://repo.voidlinux.eu/current 10044071 3520568
```
```
# xbps-query -S monero-gui | grep automatic
automatic-install: yes
```
 
### Steps to reproduce the behavior

Update monero-core on a system that had it installed previously and doesn't have monero-gui installed manually.

**Comment by asergi** [comment]
https://github.com/voidlinux/void-packages/issues/14599#issuecomment-390578843
