### ISSUE TITLE
WIP: gcc-8.1.0

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#14633]
Just a heads up: I'm testing `gcc-8.1.0` and how far I get with building packages with it.
https://github.com/pullmoll/void-packages/tree/gcc81

I already identified and fixed two packages which caused problems: https://github.com/voidlinux/void-packages/commit/62bbc8c737f9b21d476b8d3da3761c17bce5ac7c and https://github.com/voidlinux/void-packages/commit/193a17fe38a72246a3f319c93e7c464568212aef .

For the cross compilers I could not get `cross-arm-none-eabi` working and would leave that to its maintainer. At some point gcc tries to use `-float-abi=hard` and that of course fails.

The others seem to be fine and I'm currently trying to build the `base-chroot{,-musl}` with them.

I'm not sure how building the cross `gcc-fortran` will work so perhaps the merge should go in two steps, or gcc be revbumped after the cross compilers are built.

**Comment by pullmoll** [comment]
Packages built with gcc-8.1.0 as always are at https://repo.voidlinux.de/current/ (uploading now).
Cross `base-chroot{,-musl}` were built and seem ok.
Everything is looking good so far.
I think the transition will be smooth.

**Comment by pullmoll** [comment]
Stopped testing for now as I did not find a simple solution for curing the new kind of errors that gcc81 invented (alignment of `{u,}int64_t` on 32 bit architectures is/can be 4).

**Comment by chneukirchen** [comment]
What's exactly the error there? 64-bit arithmetic is emulated on x86, so it's fine to 4-byte align afaiu.

**Comment by pullmoll** [comment]
The problem is that several packages insist on the alignment of `int64_t` or `uint64_t` being 8, not 4. One of these libraries (MOJO) is 3rdparty for chromium and I described the problems in #14647.

**Comment by chneukirchen** [comment]
See https://src.fedoraproject.org/cgit/rpms/chromium.git/tree/chromium-66.0.3359.170-gcc8-alignof.patch for a fix.

**Comment by pullmoll** [comment]
@chneukirchen You are quite good at finding patches :)
I can start from scratch again and see how far I get with this patch.
It probably needs to be applied to other chromium using packages as well.

**Comment by chneukirchen** [comment]
I hope not too much other software depends on such silly alignof checks. :roll_eyes:

**Comment by pullmoll** [comment]
The good new: qt5 now builds for i686*.

Next funny error that shows when building `libodfgen`:
```
FillManager.cxx:105:14: error: unnecessary parentheses in declaration of 'wh' [-Werror=parentheses]
  char const *(wh[]) =
```
Funny syntax, sure, and I fear that quite a few packages will need to get a `-Wno-error` or explicitly `-Wno-error=parentheses`.

**Comment by pullmoll** [comment]
FYI A [directory of packages](https://misc.voidlinux.de/broken/) which are broken for `x86_64`, probably but not necessarily because of gcc8.

**Comment by pullmoll** [comment]
Looking at the [growing number of broken packages](https://misc.voidlinux.de/broken/) that gcc81 is accountable for I think we should wait for at least gcc-8.1.1.

I'd like to stop here because trying to go on further requires me patching and hacking around problems which in most cases upstream should solve.
