### ISSUE TITLE
xbps-src: suggest to combine distcc and ccache

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1468]
You can rather easily combine the tools `distcc` and `ccache` by specifying the environment variable `CCACHE_PREFIX="distcc"`. This is mentioned in distcc(1).

So when `XBPS_DISTCC=yes` and also `XBPS_CCACHE=yes`, xbps-src could just set `CCACHE_PREFIX="/usr/bin/distcc"`.

I believe the current setup, i.e. prefixing `$PATH` with `/usr/lib/ccache/bin` and later with `/usr/lib/distcc/bin`, makes ccache effectively useless. See the last paragraph in man distcc(1) section **`USING DITSCC WITH CCACHE`** for the reason.

The corresponding section of xbps-src could thus instead be like this:
```shell
    if [ -n "$XBPS_DISTCC" ]; then
        if [ -n "$XBPS_CCACHE" ]; then
            export CCACHE_PREFIX="/usr/bin/distcc"
        else
            DISTCCPATH="/usr/lib/distcc/bin"
            export PATH="$DISTCCPATH:$PATH"
        fi
        export DISTCC_DIR="$XBPS_HOSTDIR/distcc-${XBPS_CROSS_BUILD:-${XBPS_MACHINE}}"
        export DISTCC_HOSTS="$XBPS_DISTCC_HOSTS"
        mkdir -p $DISTCC_DIR
    fi
```
I'm testing here with `./xbps-src pkg qt5` and it looks like it's working as expected, i.e. it distributes jobs to my slave and also updates and uses hostdir/ccache-x86_64.

What do you think? Or are you sure the combination of distcc and ccache already works right and I am wrong?

P.S.: I use `watch CCACHE_DIR=hostdir/ccache-x86_64 ccache -s` to see what's going on.

**Comment by xtraeme** [comment]
Looks good, please submit a proper patch.
