### ISSUE TITLE
Package Request - Othman

### ISSUE THREAD

**Issue by anarchomoh** [voidlinux/void-packages#14709]
Hi

Could I please request Othman to be packaged for Void? 

The link is: https://github.com/ojuba-org/othman/releases

Thank you.

**Comment by Johnnynator** [comment]
The Licensing currently is not clear.
https://github.com/ojuba-org/othman/issues/15

**Comment by anarchomoh** [comment]
Hi
The English one is translated here:
https://github.com/ojuba-org/othman/commit/29d8909c5212430d673e329a53853067f5dbdce8

**Comment by Johnnynator** [comment]
@anarchomoh This is the "Waqf" General Public License and not the Waqf Public License v2.

**Comment by anarchomoh** [comment]
@Johnnynator Sorry - unsure what the difference is but I found it in Debian and thought I would request it for Void.  Please do not include if there is any issue - don't want Void to experience any problems.

**Comment by Johnnynator** [comment]
The License probably would be fine. It is just that at least I can not verify it.
You can leave this issue open. Maybe someone can clarify what the License allows and does not allow (and therefore if we can ship it or not)

**Comment by Johnnynator** [comment]
Will check what version is in debian and what License is listed there.

**Comment by Johnnynator** [comment]
Debian redistributes it as `non-free` which probably means that we could it too.

**Comment by anarchomoh** [comment]
Thank you, if it's in non-free in Void that'd be great as well. I'm trying to get more Muslim users of Linux to use Void.
