### ISSUE TITLE
gns3-server and aiohttp

### ISSUE THREAD

**Issue by yaoghu** [voidlinux/void-packages#14736]
Firstly,aiohttp v2.x is required for gns3-server but the provided version is v3.x....this causes gns3-server not to function properly...and by not function,i mean not work at all.

Secondly,apparently gns3-gui and gns3-server have to be in the same version in order to work.The issue is that gns-gui provided by the repo is at v2.1.5 and gns3-server is at v2.1.4.

Temporary Soln: i currently got it to work by installing gns3-gui,gns3-server and PyQt5 in a virtualenv(which is not necessary) through pip.Also make sure gcc and python3-devel is installed(both of which can be found in the repo)

Hope this gets fixed...maybe downgrade aiohttp to 2.x and update gns3-server to v2.1.5

**Comment by Johnnynator** [comment]
I'll take a look at it. I think updating everything to 2.1.6 should be also Ok?

**Comment by Johnnynator** [comment]
Lel, `gns3-server` is even set to broken because of that aiohttp reason.

**Comment by Johnnynator** [comment]
`gns3-server-2.1.6` still requires aiohttp < 3.0 :(

**Comment by yaoghu** [comment]
yeah...requirements.txt in the gns3-server repo states a version >=2.2.0 and <2.4.0 is required.
