### ISSUE TITLE
Package Request - i8kutils

### ISSUE THREAD

**Issue by anarchomoh** [voidlinux/void-packages#14765]
Hi 
Could I please request that i8kutils be packaged for Void?  I have an old Dell laptop and the fan's driving me insane.  This will help in controlling the fan.  Thanks.

https://github.com/vitorafsr/i8kutils

The Debian packages are on: https://launchpad.net/i8kutils

**Comment by maxice8** [comment]
i'll take a look.

**Comment by abenson** [comment]
done did

**Comment by abenson** [comment]
Well, it's not merged yet ;]
