### ISSUE TITLE
pycharm: white window

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#14858]
### System

* xuname:  **Void 4.16.13-chrysalis x86_64 GenuineIntel uptodate rrFFFF**

* package:  **pycharm-community-2018.1.3_1**
I have experienced the same behavior with 2017 version too.

### Expected behavior
Getting a starting window of the IDE with text visible.

### Actual behavior
Pycharm starts but the window is completely white.
![Screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-06-02-17%3A22%3A07-screenshot.png)

### Steps to reproduce the behavior
1. install pycharm
2. run it

**Comment by maxice8** [comment]
can't reproduce, installed , did first-time configuration and created a project.

**Comment by Vintodrimmer** [comment]
Then it must be on my end. Have any idea what may cause this?
