### ISSUE TITLE
ping/ping6: shouldn't be suid

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1487]
```
cap_net_raw+ep
```

Should be enough

**Comment by Ypnose** [comment]
xtraeme enabled setuid when <code>CAP_NET_RAW</code> wasn't preserved in tarballs. I noticed this issue by myself after installed some RPis.
https://github.com/voidlinux/void-packages/commit/0efc3f574d3b120f3a9de43d898625eb9c592629

**Comment by chneukirchen** [comment]
Caps should be set in post-install hook.

**Comment by Ypnose** [comment]
@chneukirchen I meant in rootfs tarballs.

**Comment by thypon** [comment]
Maybe we could put iputils outside base-system and then outside the rootfs.

**Comment by thypon** [comment]
here a patch for tar https://bugzilla.redhat.com/show_bug.cgi?id=771927#c30 to support caps

**Comment by thypon** [comment]
#1492 here the patch to support acl/xattrs in tar

to test it's simple as:
```
# tar -c --acls --xattrs --xattrs-include='security.capability' -f - -C /usr/bin/ beep | tar -x --acls --xattrs --xattrs-include='security.capability' -f - -C .
# getcap beep
beep = cap_dac_override,cap_sys_tty_config+ep
```

**Comment by thypon** [comment]
http://marc.info/?l=linux-netdev&m=142909881500927 this patch to ping should also solve the problem. It's alredy in upstream but not in a stable release.

**Comment by chneukirchen** [comment]
Since 1ecacb8db.
