### ISSUE TITLE
python dependency hooks cause python-WTForms failure

### ISSUE THREAD

**Issue by maxice8** [voidlinux/void-packages#14921]
error: no commands supplied
=> ERROR: python3-WTForms-2.2_1: pre-pkg_07-python-requires: 'python$pver -c 'import setup; print("
".join(setup.params["install_requires"]))'' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/07-python-requires.sh:11
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:251
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
=> ERROR: python3-WTForms-2.2_1: pre-pkg_07-python-requires: '( cd "$wrksrc"; python$pver -c 'import setup; print("
".join(setup.params["install_requires"]))' )' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/07-python-requires.sh:11
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:251
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47
=> ERROR: python3-WTForms-2.2_1: pre-pkg_07-python-requires: 'requires=$( ( cd "$wrksrc"; python$pver -c 'import setup; print("
".join(setup.params["install_requires"]))') )' exited with 1
=> ERROR:   in hook() at common/hooks/pre-pkg/07-python-requires.sh:11
=> ERROR:   in run_func() at common/xbps-src/shutils/common.sh:21
=> ERROR:   in run_pkg_hooks() at common/xbps-src/shutils/common.sh:251
=> ERROR:   in main() at common/xbps-src/libexec/xbps-src-prepkg.sh:47

**Comment by maxice8** [comment]
cc @Gottox

**Comment by Gottox** [comment]
ah :D
