### ISSUE TITLE
Package request: public-inbox

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#14922]
https://public-inbox.org/INSTALL.html

This needs a bunch of perl modules we don't have yet.

**Comment by maxice8** [comment]
> lots of perl modules

sounds like a job for me.

**Comment by maxice8** [comment]
if only the website didn't timeout on me like x.org and freedesktop.org :c

**Comment by chneukirchen** [comment]
```
* Date::Parse                   deb: libdatetime-perl
                                rpm: perl-Time-ParseDate

* Email::MIME                   deb: libemail-mime-perl
                                rpm: perl-Email-MIME

* Email::MIME::ContentType      deb: libemail-mime-contenttype-perl
                                rpm: perl-Email-MIME-ContentType

* Encode::MIME::Header          deb: libencode-perl
                                rpm: perl-Encode

Where "deb" indicates package names for Debian-derived distributions and
"rpm" is for RPM-based distributions (only known to work on Fedora).

Numerous optional modules are likely to be useful as well:

  - Plack                      deb: libplack-perl
                               rpm: perl-Plack, perl-Plack-Test,
                               (for HTML/Atom generation)

  - URI::Escape                deb: liburi-perl
                               rpm: perl-URI
                               (for HTML/Atom generation)

  - Search::Xapian             deb: libsearch-xapian-perl
                               rpm: perl-Search-Xapian
                               (for NNTP service or gzipped mbox over HTTP)

  - IO::Compress::Gzip         deb: perl-modules (or libio-compress-perl)
                               rpm: perl-PerlIO-gzip
                               (for gzipped mbox over HTTP)

  - DBI                        deb: libdbi-perl
                               rpm: perl-DBI
                               (for gzipped mbox over HTTP)

  - DBD::SQLite                deb: libdbd-sqlite3-perl
                               rpm: perl-DBD-SQLite
                               (for NNTP service or gzipped mbox over HTTP)

  - Danga::Socket              deb: libdanga-socket-perl
                               rpm: perl-Danga-Socket
                               (for bundled HTTP and NNTP servers)

  - Net::Server                deb: libnet-server-perl
                               rpm: perl-Net-Server
                               (for HTTP/NNTP servers as standalone daemons)

  - Filesys::Notify::Simple    deb: libfilesys-notify-simple-perl
                               rpm: perl-Filesys-Notify-Simple
                               (for public-inbox-watch)

  - Inline::C[7]               deb: libinline-c-perl
                               (speeds up spawning on Linux
                                (see public-inbox-daemon(8))

  - Plack::Middleware::ReverseProxy

                               deb: libplack-middleware-reverseproxy-perl
                               rpm: perl-Plack-Middleware-ReverseProxy
                               (ensures redirects are correct when running
                                behind nginx or Varnish)

  - Plack::Middleware::Deflater

                               deb: libplack-middleware-deflater-perl
                               rpm: perl-Plack-Middleware-Deflater
                               (saves bandwidth on responses)
```

**Comment by maxice8** [comment]
Filesys::Notify::Simple -> https://github.com/voidlinux/void-packages/pull/14925
Date::Parse -> Perl-TimeDate
Email::Mime | Email:: MIME::Header | Email::MIME::ContentType-> https://github.com/voidlinux/void-packages/pull/14923
URI::Escape -> perl-URI
DBI -> perl-DBI
DBD::SQLite -> perl-DBD-SQLite
IO::Compress::Gzip -> IO::Compress -> perl (core module)
Net::Server -> perl-Net-Server

**Comment by newbluemoon** [comment]
@maxice8 there aren’t too many modules left to package, but in case you’re busy with other stuff I could help out. Just let me know. :)

**Comment by chneukirchen** [comment]
I have perl-Search-Xapian and perl-Plack in the works, but still many deps missing:

Warning: prerequisite Apache::LogFormat::Compiler 0.33 not found.
Warning: prerequisite Cookie::Baker 0.07 not found.
Warning: prerequisite Devel::StackTrace::AsHTML 0.11 not found.
Warning: prerequisite HTTP::Entity::Parser 0.17 not found.
Warning: prerequisite HTTP::Headers::Fast 0.18 not found.
Warning: prerequisite Hash::MultiValue 0.05 not found.
Warning: prerequisite Stream::Buffered 0.02 not found.
Warning: prerequisite Test::Requires 0 not found.
Warning: prerequisite Test::TCP 2.15 not found.
Warning: prerequisite WWW::Form::UrlEncoded 0.23 not found.

**Comment by newbluemoon** [comment]
Working on Cookie::Baker.

**Comment by newbluemoon** [comment]
Working on Apache::LogFormat::Compiler now.

**Comment by newbluemoon** [comment]
In the module chain for Apache::LogFormat::Compiler there’s POSIX::strftime::GNU (`build_style=perl-ModuleBuild`) but it fails with

```
Building POSIX-strftime-GNU
ld: unrecognized option '-Wl,-z,relro'
ld: use the --help option for usage information
Error: no compiler detected to compile 'lib/POSIX/strftime/GNU/XS.c'.  Aborting
```

Still trying to figure this out...

**Comment by maxice8** [comment]
> @newbluemoon  there aren’t too many modules left to package, but in case you’re busy with other stuff I could help out. Just let me know. :)

Feel free

**Comment by newbluemoon** [comment]
Test::Requires is in the repo already (perl-Test-Requires).

**Comment by newbluemoon** [comment]
I think there’s something wrong with the `perl-ModuleBuild` build style when source code is actually compiled.

There are only two packages in the repo which do this until now: perl-Params-Classify and perl-Params-Validate. However, the cross-compiled packages are incomplete: they’re missing the stuff under `/usr/lib/perl5/...` including the `.so` file which doesn’t get compiled because wrong flags are used: like `-mtune=generic`. I couldn’t find those flags in the builddir so I assume Module::Build must add them somewhere.

Trying to create packages for perl-Time-TZOffset and perl-POSIX-strftime-GNU doesn’t even work in a native build.

**Comment by chneukirchen** [comment]
I have these now, will push later.
