### ISSUE TITLE
Unable to update streamlink

### ISSUE THREAD

**Issue by maxice8** [voidlinux/void-packages#14978]
### Expected behavior

Update streamlink

### Actual behavior

CONFLICT: python3-pycryptodome-3.6.1_1 with installed pkg python3-crypto-2.6.1_9 (matched by python3-crypto>=0)
Transaction aborted due to conflicting packages.
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...

### Steps to reproduce the behavior
Package streamlink-0.13.0 and update it

**Comment by asergi** [comment]
We are at `python3-pycryptodome-3.6.1_3`.

**Comment by asergi** [comment]
ceb03534dd77b352f9978d990930b437af8f6e14
5c5ccaca7eda4a9a44a3650f87017beb0b3dbb3a
