### ISSUE TITLE
Organisation movement

### ISSUE THREAD

**Issue by solbjorn** [voidlinux/void-packages#15030]
Maybe Void should even migrate to GitLab since GitHub refused to help with regaining access (-> and led to all this) and now is under Microsoft at all?

_(please close this if it's incorrect for any reason)_

**Comment by Johnnynator** [comment]
Moving to GitLib would be a lot of work.
Void uses Travis ci extensively and Travis only supports GitHub.

Moving to any other platform is currently out of scope and would require a lot of work.

**Comment by Johnnynator** [comment]
Also double of #14390
