### ISSUE TITLE
GitHub issue movement

### ISSUE THREAD

**Issue by sstt011** [voidlinux/void-packages#15043]
There are many issues/pull requests on here that I want/need. As the GitHub org is being moved from voidlinux to void-linux, issues/pull requests will be closed, etc. However, users that have been inactive/deleted will not migrate their issues/pull requests. Is it OK if I reopen them in the new org instead? eg #231 is a deleted user.

_Please close once a solution is found. I'm not sure if this is the right place for this, is it?_

**Comment by Gottox** [comment]
Thanks for participation!

It's perfectly fine to reopen actual issues on the new org. Nevertheless, I'd like to avoid moving package requests. They didn't scale, most of them were ignored anyway.

**Comment by sstt011** [comment]
@Gottox Thanks! Ok, I wont move PR's. But thanks anyway!

**Comment by Vaelatern** [comment]
Should note that package requests are a type of issue, and separately that
pull requests should follow us if at all relevant

**Comment by Anachron** [comment]
how about creating a simple text file with pkg requests and close all remaining requests?

**Comment by Gottox** [comment]
or a single issue with

* [ ] check
* [ ] box
* [ ] for
* [ ] every requested package
