### ISSUE TITLE
eyeD3 is missing pathlib dependency

### ISSUE THREAD

**Issue by borjator** [voidlinux/void-packages#15071]
### System

* xuname:  
  *Void 4.16.12_1 x86_64 GenuineIntel notuptodate rFF*
* package:  
  *eyeD3-0.8.5_1*

### Expected behavior
eyeD3 requires *pathlib* and it's not listed as a dependency. In fact there is no *pathlib* package for Python 3; there are two packages for pathlib in the repositories (*python-pathlib* and *python-pathlib2*) but both are for Python 2.

### Actual behavior
```
Traceback (most recent call last):
  File "/usr/bin/eyeD3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pathlib' distribution was not found and is required by eyeD3
```
### Steps to reproduce the behavior
Just launch eyeD3 with no arguments and you'll get the above error.

**Comment by cr6git** [comment]
According to http://pathlib.readthedocs.io/en/1.0.1/

"This module has been included in the Python 3.4 standard library after PEP 428 acceptance.
You only need to install it for Python 3.3 or older."

**Comment by cr6git** [comment]
````
$ sudo xbps-install python3-pip

Name        Action    Version           New version            Download size
python3-pip install   -                 10.0.1_1               837KB 

Size to download:              838KB
Size required on disk:        4931KB
Space available on disk:      9847MB

Do you want to continue? [Y/n] y
...
python3-pip-10.0.1_1: installed successfully.

$ sudo pip install pathlib
Collecting pathlib
  Downloading https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz (49kB)
    100% |████████████████████████████████| 51kB 619kB/s 
Installing collected packages: pathlib
  Running setup.py install for pathlib ... done
Successfully installed pathlib-1.0.1

$ eyeD3
Nothing to do

$ eyeD3 --version
0.8.5
````
:slightly_smiling_face:

**Comment by borjator** [comment]
I know I can install eyeD3 using pip (even locally); but if there's a package for it I'd rather do it using the package manager.

**Comment by Johnnynator** [comment]
@borjator I'll take a look at fixing the eyeD3 package this evening.

**Comment by cr6git** [comment]
@Johnnynator uh? why pip is a problem?

**Comment by Johnnynator** [comment]
`sudo pip install` will put files into the root directory that will not be tracked by xbps and it is possible that it will be overwritten by some xbps package in the future and may or may not end in some conflicts and issues.
I would recommend to use pip only for virtualenv and not really for system wide installations.

**Comment by borjator** [comment]
@cr6git If you want to use `pip` to install something because it's not packaged for Void and you don't want to use a virtualenv because it's a utility such as eyeD3, then I'd recommend you install it like this: `pip install --user eyeD3`. In this way you will install the Python packages locally for your user and you'll have `eyeD3` in your path (`~/.local/bin`).
