### ISSUE TITLE
dhcp: soliciting a DHCP lease

### ISSUE THREAD

**Issue by samukhin** [voidlinux/void-packages#15161]
x86_64-musl, 4.16.14_1 kernel, dhcpcd version: 7.0.2

```
$ dhcpcd enp2s0
DUID 00:01:00:01:22:b5:97:e3:40:16:7e:9c:8b:cb
enp2s0: IAID 7e:9c:8b:cb
enp2s0: soliciting an IPv6 router
enp2s0: soliciting a DHCP lease
enp2s0: using IPv4LL address 169.254.180.66
enp2s0: adding route to 169.254.0.0/16
enp2s0: adding default route
forked to background, child pid 889
```

the same issue with dhclient

**Comment by cr6git** [comment]
What is the issue?

**Comment by samukhin** [comment]
[4171](https://github.com/voidlinux/void-packages/issues/4171):

> No connection, no web pages in browser, message saying network connection error instead. xbps-install can't connect to repo.

**Comment by samukhin** [comment]
but for example on void live (20171007) with 6.11.5 dhcpcd and 4.12.13_1 kernel everyrthing is ok

**Comment by cr6git** [comment]
I don't know...
Take a look at [#13243](https://github.com/voidlinux/void-packages/pull/13243), we have an update for dhcpcd version 7.0.5b.
