### ISSUE TITLE
Valgrind has a virtual non-existent dependency glibc-dbg

### ISSUE THREAD

**Issue by GiedriusS** [voidlinux/void-packages#1516]
Valgrind fails to install:
MISSING: glibc-dbg>=2.21<2.22
Transaction aborted due to unresolved dependencies

glibc-dbg doesn't exist and srcpkgs/glibc/template says on line 27 that "Force creation of -dbg pkg, required by valgrind" so that dependency should probably be just removed. But for some reason after removing it valgrind fails to build with: "checking for the kernel version... unsupported (4.0.1_3) \ configure: error: Valgrind works on kernels 2.4, 2.6" so probably more then that has to be changed.

**Comment by chneukirchen** [comment]
`xbps-install void-repo-debug`

**Comment by GiedriusS** [comment]
First time heard about this. That fixed this.
