### ISSUE TITLE
Latest kernels in the 4.9 and 4.16 series panic on boot

### ISSUE THREAD

**Issue by loreb** [voidlinux/void-packages#15172]
### System

* xuname:  
  Void 4.15.15_3 x86_64-musl GenuineIntel uptodate r
* package:  
  linux4.16-4.16.14_1 and linux-lts-4.9_2

### Expected behavior
system boots

### Actual behavior
Both kernels panic before requesting the passphrase (I have encrypted lvm with non encrypted /boot)
Screenshots:
![4 9](https://user-images.githubusercontent.com/2369930/41471007-aad82892-70b2-11e8-97f4-226235af8d32.jpg)
![4 16](https://user-images.githubusercontent.com/2369930/41471017-b29d3004-70b2-11e8-9bf3-7f68360d5442.jpg)

In /etc/default/grub I have
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 rd.auto=1 cryptdevice=/dev/sda8 root=/dev/mapper/pool-root slub_debug=P page_poison=1"
Not sure what other info may be useful about my setup, it's straight from the void wiki; in case do let me know.

Fwiw, the following kernels work just fine:
[*] linux4.13-4.13.15_1 The Linux kernel and modules (4.13 series)
[*] linux4.14-4.14.49_1 The Linux kernel and modules (4.14 series)
[*] linux4.15-4.15.15_3 The Linux kernel and modules (4.15 series)

As well as a few others that were waiting for vkpurge.

### Steps to reproduce the behavior
turn the power on, select one of those kernel with grub, boot

**Comment by abenson** [comment]
Do you have a separate `/boot` partition?

**Comment by loreb** [comment]
:man_facepalming: 
You're right, a dracut+update_grub later everything works fine, thank you!
