### ISSUE TITLE
 {"msg": "template error while templating string: unexpected char u'\\xa0' 

### ISSUE THREAD

**Issue by Strijd** [voidlinux/void-packages#15204]
Hi
I just installed voidlinux and having issues with running my ansible code in virtual-env
I keep getting this this error 
`error while templating string: unexpected char u'\\xa0' `
When running in other distros or docker container it works as expected 
Any suggetsions ? 

loclae:
```

LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8


```
terminal : st
thanks

**Comment by Duncaen** [comment]
Wrong repository → https://github.com/void-linux/void-packages

And it would help if you provide more informations, like the used architecture, libc and what program actually gives this output.

**Comment by Strijd** [comment]
@Duncaen of course and sorry for that. 
voilinux 4.19.29_1  CPU: Intel i7-8700K (6) @ 4.700GHz
program is ansible --version 2.7.8 under virtualenv
ldd (GNU libc) 2.29

**Comment by Vaelatern** [comment]
You should read more closely.
