### ISSUE TITLE
xbps-src: bootstrap needs zip + unzip

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1529]
When trying to `./xbps-src zap && ./xbps-src bootstrap` the following error is shown:
```
=> ERROR: zip is not a bootstrap package and cannot be built without it.
=> ERROR: Please install bootstrap packages and try again.
=> ERROR: gcc-4.9.2_3: failed to transform dependency zip
```
Same happens for unzip after adding `bootstrap=yes` to `srcpkgs/zip/template`
So it looks like both packages should have this flag set now?

**Comment by xtraeme** [comment]
Hmm no, this is my fault... fixing

**Comment by chneukirchen** [comment]
I just did a bootstrap on aarch64 and ran into this again?

**Comment by chneukirchen** [comment]
(The bootstrapping also built java and go...)

**Comment by dominikh** [comment]
Similar issue here. xbps-src doesn't complain, but gcc does:

```
configure: error: cannot find neither zip nor jar, cannot continue
Makefile:18297: recipe for target 'configure-target-libjava' failed
```

Same as for @chneukirchen, it tries to build support for Java and Go.
