### ISSUE TITLE
nm and wpa

### ISSUE THREAD

**Issue by mrgreen3** [voidlinux/void-packages#1540]
Can see that dhcpcd is only run if nm is not installed, but nm requires wpa_supplicant which is trying to start. Does the service needs removing from list in dracut/service.sh?

**Comment by xtraeme** [comment]
This is not the proper repository, you are talking about *void-mklive* and your issue was fixed long ago in *void-mklive* the official repository:

```
[juan@leysa void-mklive]$ git show f0592dcd5e78dbffa8d853043a5d122a792310b5
commit f0592dcd5e78dbffa8d853043a5d122a792310b5
Author: Juan RP <xtraeme@gmail.com>
Date:   Tue Apr 7 10:23:33 2015 +0200

    dracut/services: do not enable wpa_supplicant.

```
