### ISSUE TITLE
bash_completion "bash: words: bad array subscript"

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#1558]
https://bugs.launchpad.net/ubuntu/+source/bash-completion/+bug/1289597

**Comment by GiedriusS** [comment]
Do you want someone to add that patch to bash-completion? Is it fixed in upstream?

**Comment by xtraeme** [comment]
More details please? otherwise I'll close it.

**Comment by dicktyr** [comment]
the link describes the problem and solution clearly

what details would like?
