### ISSUE TITLE
Package request: ffado

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#1561]
Drivers and tools for FireWire-based audio devices

http://www.ffado.org/
http://www.ffado.org/files/libffado-2.2.1.tgz

I've been trying to package this (and its dependencies) myself
but I'm just not familiar enough with the process

@Duncaen kindly packaged one dependency (libdbus-c++)
and I was hoping to do the rest myself
but the way is not clear enough to me
and I'd be grateful for help

**Comment by Duncaen** [comment]
a06e219ff10d0b8a520cffb5022ae4a445b11489
