### ISSUE TITLE
xbps-src: forgets -a arch together with -N

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1597]
When running e.g. `./xbps-src -a armv7hf -N pkg base-system` only the first few packages like `base-files-0.122_1` and `cross-vpkg-dummy-0.20_1` are built for armv7l, the following packages are built for x86_64. If both options are not supposed to work together, perhaps an option clash check should be in place?

For now I'm using the tricky line:
```
source srpkgs/base-system/template && for p in $depends; do ./xbps-src -a armv7hf pkg $p; done
```

**Comment by xtraeme** [comment]
This is the expected behaviour with -N.

When you use -N, the host needs some dependencies to build the cross compiler... this is what you are seeing.

**Comment by pullmoll** [comment]
Oh, I didn't wait for the process to finish.
So this is a non-issue and can be closed?

**Comment by xtraeme** [comment]
Yes
