### ISSUE TITLE
Idea: make xbps-src detect try to cross build noarch=yes packages

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1598]
Right now there is code like
```
if [ -z "$CROSS_COMPILE" ]; then 
coreutils-doc_package() {
...
}
fi
```
in place which prevents cross building coreutils, because the symlinked package is missing.

If instead the packaging script would check for both `-n $CROSS_COMPILE` and `$noarch = "yes"` and just return 0, shouldn't that be sufficient?

The noarch package could be downloaded from the repo in this case and integrated into a local repository for convenience.

Or it could perhaps be built using the native arch...

**Comment by xtraeme** [comment]
The issue with coreutils is that this needs `help2man`, therefor it's only built in the native case.

Your suggestion won't improve the current state.

**Comment by thypon** [comment]
Given it's a noarch package we could build with the current architecture and register in the alien architecture automatically.

**Comment by pullmoll** [comment]
thyphon: That's what I meant to suggest, i.e. keep the coreutils-doc_package() even for $CROSS_COMPILE and automagically build `noarch=yes` packages using the host architecture. I think that could solve my issues with `./xbps-src -a armv7hf -N base-system`.

**Comment by xtraeme** [comment]
You don't seem to get it :-)

The `coreutils-doc` subpkg is only built in the native case because this needs `help2man`. `help2man` executes the binary with `--help` to generate a manual page.

In cross compilation you cannot execute the binaries for the `target` architecture.

**Comment by pullmoll** [comment]
I don't want to cross build the coreutils-doc part of coreutils/template, but I want the coreutils-<version>.xbps itself, no less. I don't want to run it, I just need the base package being built :)

And building the base package fails because the file system symlink coreutils-doc -> coreutils doesn't resolve to a function in the template if cross building. That's all.

Or do you say cross building coreutils itself shouldn't be possible? I don't think so, because otherwise the package would have nocross=yes.
