### ISSUE TITLE
rpi-kernel: add rtl8192cu

### ISSUE THREAD

**Issue by lemmi** [voidlinux/void-packages#1617]
ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
this works with x64 kernel but not on rpi2. 
i poked around a bit and couldn't quite find out how the kernel build is done in detail, so i request some of the pros to handle that matter. prefereably before sunday. it'll be crucial to the value of my mother's birthday gift.

**Comment by xtraeme** [comment]
This module is already availble in `rpi2-kernel`.

**Comment by xtraeme** [comment]
Could you please provide some details? afaik the module is already there:

```
[juan@pi2 ~]$ find /usr/lib/modules/3.18.14_1/ -name rtl8192\*
/usr/lib/modules/3.18.14_1/kernel/drivers/net/wireless/rtl8192cu
```

**Comment by lemmi** [comment]
i digged around a bit and indeed the driver gets loaded, but for some reason on
  - x64: driver gets loaded, devices appear, but don't work.
  - rpi: driver gets loaded, but only eth device appears, iw list doesn't show anything. 

could this be a missing firmware? in the mean time openelec  and xbian were able to get it running right away. i can have a further look into it on the weekend.

**Comment by xtraeme** [comment]
Could you paste dmesg and/or verify that you've got `linux-firmware-network` installed?

**Comment by xtraeme** [comment]
Any news about this one?

**Comment by lemmi** [comment]
so.. managed to get a hold of the device again. it seems the standard kernel driver won't work. 
http://askubuntu.com/questions/509498/is-there-a-standard-wifi-driver-for-the-edimax-ew-7811un
this link tells most of the story so far.
sadly i wasn't able to compile these old drivers on a current kernel as some interfaces changed. 
https://github.com/dz0ny/rt8192cu seems to be a good starting point. this compiles but the device doesn't show up with wireless extensions.
http://elinux.org/RPi_edimax_EW-7811Un
has a link for a rpi specific driver for what it's worth.
> this works with x64 kernel but not on rpi2.

this is not correct. i didn't fully test it back then, but the device showed up at that time, but is a useless as under the arm kernel

**Comment by thypon** [comment]
shouldn't this bugreport fixed upstream?

**Comment by lemmi** [comment]
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=b0f85fa11aefc4f3e03306b4cd47f113bd57dcba
maybe we just can sit this one out.

**Comment by lemmi** [comment]
i'll give this another run as soon as i get my hands on that device again.

**Comment by lemmi** [comment]
Ok, this finally works here on kernel 4.4+.
