### ISSUE TITLE
Transaction aborted due to unresolved shlibs.

### ISSUE THREAD

**Issue by biopsin** [voidlinux/void-packages#1619]
Hi,
did a "dist-upgrade" and was presented with

libavcodec-2.6.3_1: broken, unresolvable shlib `libvpx.so.1'
virtualbox-ose-4.3.28_1: broken, unresolvable shlib `libvpx.so.1'
Transaction aborted due to unresolved shlibs.

I then ran the solution posted by Juan
for f in $(xbps-query -s '' -p transaction|cut -d ':' -f1); do sudo xbps-pkgdb $f; done

but it did not help this time..

**Comment by xtraeme** [comment]
`libvpx-1.4.0` and its reverse dependencies are being rebuilt right now, see http://build.voidlinux.eu

There's no issue, you'll have to wait until the revdeps are rebuilt.
