### ISSUE TITLE
Package Request: Guitarix

### ISSUE THREAD

**Issue by AlexKraak** [voidlinux/void-packages#1625]
http://guitarix.org/

**Comment by cr6git** [comment]
I'm working on it.

**Comment by cr6git** [comment]
I don't know what more I can do.

**Comment by cr6git** [comment]
Hey! I just found this [old PR](https://github.com/voidlinux/void-packages/pull/2673/commits/1ea16be80a80bb600c0c4e868c3a9a6d72238ffa) for guitarix. 

@thypon this has not been merged ? I don't understand, can't find the package.

**Comment by thypon** [comment]
Removed in 4e4f51b23d6d7d0eb95fb1215610a40ab40cc10e by @xtraeme . Since I don't use the package anymore and there is not way to inform the maintainer via email that the package is broken (on toolchain/glibc revbump) I didn't catch that.

**Comment by newbluemoon** [comment]
@cr6git With the added symlinks in the referenced PR your guitarix2 package builds just fine :)

But I think there are more platforms for which SSE should be disabled, so maybe disable it for all platforms but i686/x86_64:


```
case "$XBPS_TARGET_MACHINE" in
	i686*|x86_64*) ;;
	*) --disable-sse;;
esac

```

**Comment by cr6git** [comment]
Well done @newbluemoon ! 
I think you are right about SSE, this is exactly the same on the Audacity [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/audacity/template#L20).

**Comment by cr6git** [comment]
I'm trying to build the [latest release](https://sourceforge.net/projects/guitarix/files/guitarix/) 0.36.1. 
For now, cross compilation fails: 
````
[ 582/1029] cxx: src/gx_head/engine/ladspaback.cpp -> build/default/src/gx_head/engine/ladspaback.o
In file included from ../src/gx_head/engine/ladspaback.cpp:19:0:
/usr/aarch64-linux-musl/usr/include/lrdf.h:8:10: fatal error: raptor.h: No such file or directory
 #include <raptor.h>
          ^~~~~~~~~~
compilation terminated.
Waf: Leaving directory `/builddir/guitarix-0.36.1/build'
^C
Interrupted 
=> ERROR: guitarix2-0.36.1_1: failed to run do_build() at line 13.
=> ERROR: xbps-src: a failure has ocurred! exiting...
````

**Comment by cr6git** [comment]
@newbluemoon incredible! I just found this old PR [#7398](https://github.com/voidlinux/void-packages/pull/7398) ahah! we have already discussed this. 
😄

**Comment by Johnnynator** [comment]
@cr6git Take a look at the old template. You can add `$XBPS_CROSS_BASE/usr/include/raptor2` to your CFLAGS so the raptor header does get found.

**Comment by cr6git** [comment]
Ah ok! but it fails anyway. 
````
Waf: Leaving directory `/builddir/guitarix-0.36.1/build'
Build failed: LADSPA load test failed: Error loading shared library default/src/ladspa/ladspa_guitarix.so: Exec format error
=> ERROR: guitarix2-0.36.1_1: failed to run do_build() at line 13.
````

**Comment by newbluemoon** [comment]
When removing the load test from the build script the build goes through. I just have no idea if that’s a wise thing to do.

```
if [ -n "$CROSS_BUILD" ]; then
        post_configure() {                                                                                                                                                                              
                # don’t test load the ladspa plugin when cross compiling
                sed -i -e "s/\(features='cxx cshlib\) test_loadable/\1/" src/ladspa/wscript
        }   
fi
```

**Comment by cr6git** [comment]
ok, this morning I'll look into it!

**Comment by cr6git** [comment]
I guess I can ignore this: 
````
=> guitarix2-0.36.1_1: running pre-pkg hook: 99-pkglint ...
=> WARNING: guitarix2-0.36.1_1: libgxw.so.0 not found in common/shlibs!
=> WARNING: guitarix2-0.36.1_1: libgxwmm.so.0 not found in common/shlibs!
=> WARNING: guitarix2-0.36.1_1: libgxw.so.0 not found in common/shlibs!
=> WARNING: guitarix2-0.36.1_1: libgxwmm.so.0 not found in common/shlibs!
=> guitarix2-0.36.1_1: running do-pkg hook: 00-gen-pkg ...
````

**Comment by newbluemoon** [comment]
Those libraries only have to be added to common/shlibs if other packages need to link against them. I don’t think that’s the case. :)

**Comment by cr6git** [comment]
There is a problem with `armv7hf` as you can see...

**Comment by maxice8** [comment]
@lemmi plz
