### ISSUE TITLE
Package Request: Godot engine

### ISSUE THREAD

**Issue by mar1n3r0** [voidlinux/void-packages#1642]
Godot is an advanced, feature packed, multi-platform 2D and 3D game engine. It provides a huge set of common tools, so you can just focus on making your game without reinventing the wheel.

Godot is is completely Free and Open Source under the very permissive MIT License. No strings attached, no royalties, nothing. Your game is yours, down to the last line of engine code.

http://www.godotengine.org/wp/download/

https://github.com/okamstudio/godot/wiki/compiling_linux

Tried following the instructions but as far as my limited knowledge goes it requires openssl instead of libressl...

P.S. The 32bit binary for windows works through wine.

**Comment by thypon** [comment]
libressl is not ABI compatible but is (more or less) API compatible to openssl. I'll give a shot later today.

**Comment by beefcurtains** [comment]
It seems to build just fine here, give me a few minutes and I'll push a test branch.

**Comment by beefcurtains** [comment]
https://github.com/beefcurtains/void-packages/commit/8c0c009e6506f4dc3314704843deacaf923bce1c

Unfortunately, scons doesn't standardize any targets so making a generic recipe along the lines of ``./configure && make && make install`` isn't possible here.

**Comment by thypon** [comment]
Why a stub build-style?

**Comment by beefcurtains** [comment]
The answer to that is one comment ahead of you. Perhaps it's better not to specify a build_style at all, but I wasn't aware that doing so is allowed. On one hand, having a scons style allows one to easily find templates for scons projects, create specific hooks, and improve the style for the common case (if it exists). On the other hand, this doesn't appear to be necessary yet at first glance.

**Comment by thypon** [comment]
If it doesn't nothing usefull i think you could remove and rebase safely.

**Comment by beefcurtains** [comment]
That's not really a problem, I'd rather do it with 12 templates (you counted wrong) than 1200.

**Comment by codingHahn** [comment]
Any news on this?

**Comment by newbluemoon** [comment]
@codingHahn 

From [https://godot.readthedocs.io/en/stable/development/compiling/compiling_for_x11.html](https://godot.readthedocs.io/en/stable/development/compiling/compiling_for_x11.html):

> There are known optimisation issues when using GCC 6 (both to compile for X11 and to cross-compile for Windows with MinGW). Until those issues are fixed in Godot’s source, or the compiler is made more forgiving again, it is advised not to use GCC 6 to compile Godot as release builds will trigger crashes.

**Comment by codingHahn** [comment]
I got it to build and will submit the template tomorrow. @Vaelatern @cr6git @Gottox How should I name the package? ```godot```, ```godot-engine```, ```godot2``` etc. and should I create a template for godot 3, which is in prerelease right now?

**Comment by cr6git** [comment]
@codingHahn looking at the [homepage](https://godotengine.org) and their [github](https://github.com/godotengine/godot) the name is `godot` , and the [pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=godot) uses this name too.

**Comment by codingHahn** [comment]
Ok. It will be called ```godot```. But the issue I am hving now is that their scons has no ```install``` option and the template with using just the default scons build-style. So the result never gets put into a package. I am trying with this template now: https://gist.github.com/codingHahn/5c5062ded9db779622575496fc40473b
Suprise. It does not work

**Comment by codingHahn** [comment]
I am having an other problem. When it does the install with this template https://gist.github.com/codingHahn/845d979be3ea36c37ac32a71aaab3543 . It fails with:
```
=> godot2-2.1.4_1: running pre-install hook: 00-lib32 ...
=> godot2-2.1.4_1: running pre-install hook: 02-script-wrapper ...
=> godot2-2.1.4_1: running do_install ...
=> ERROR: godot2-2.1.4_1: vinstall: cannot find '/builddir/godot-2.1.4-stable/bin/godot.x11.opt.tools.*.llvm'...
=> ERROR: godot2-2.1.4_1: failed to run do_install() at line 12.
```
I have read in the docs that it should extend wildcards. Why doesn't it? What did I do wrong?

**Comment by newbluemoon** [comment]
I think you’re using `vbin` wrong. You have

    vbin ${wrksrc}/bin/"godot.x11.opt.tools.*.llvm" godot

but see `common/environment/setup/install.sh`:

```
_vbin() {
        local file="$1" targetfile="$2"

        if [ $# -lt 1 ]; then
                msg_red "$pkgver: vbin: 1 argument expected: <file>\n"
                return 1
        fi

        vinstall "$file" 755 usr/bin "$targetfile"
}
```

`vbin` installs the first argument and renames it if there is an optional second one. So maybe the way to go is using a for loop.

And I think you shouldn’t use `vbin ${wrksrc}/bin/...`, just `vbin bin/...`.

**Comment by codingHahn** [comment]
I tried it without ```${wrksrc}``` too but it did not help. The problem is that the executable is either called ```godot.opt.tools.64.llvm``` or ```godot.opt.tools.32.llvm``` therefor  I tried to use the wildcard to accomodate for that. How could I get this working with all architectures?

**Comment by newbluemoon** [comment]
Now I understand. ;) Thought there were multiple binaries. You can try to use the `case` statement to select the architecture. All 64 bit architectures use `godot.opt.tools.64.llvm` and the rest (32 bit) use the other one. 
Something like

```
case "$XBPS_TARGET_MACHINE" in
        x86_64*|aarch64*) vbin bin/godot.opt.tools.64.llvm godot;;
        *) vbin bin/godot.opt.tools.32.llvm godot;;
esac
```

**Comment by newbluemoon** [comment]
Regarding openssl: scons checks if the version is >=1.1.0 (it needs 1.0.x) and fails because libressl is at 2.5.5 atm. But its API is compatible to openssl 1.0.1 so it should work. When removing the openssl check with

```
post_extract() {
        sed -i -e "/openssl_version =/,+4d" platform/x11/detect.py
}
```

it builds just fine without the builtin openssl. :)

But then
```
=> godot-2.1.4_1: running post-install hook: 06-strip-and-debug-pkgs ...
   Stripped executable: /usr/bin/godot
=> ERROR: godot-2.1.4_1: non-PIE executable found in PIE build: /usr/bin/godot
=> ERROR: godot-2.1.4_1: failed to run post-install_06-strip-and-debug-pkgs() at line 58.
```

Adding `-fPIE`, `-fPIC`, or `-pie` to `CFLAGS` or `CXXFLAGS` doesn’t help. :(

**Comment by codingHahn** [comment]
When building with nopie=yes the build fails with 
```
[100%] clang-4.0: error: unknown argument: '-no-pie'
scons: *** [bin/godot.x11.opt.tools.64.llvm] Error 1
scons: building terminated because of errors.
=> ERROR: godot-2.1.4_1: failed to run do_build() at line 7.
```
what do you propose?

**Comment by newbluemoon** [comment]
I meant adding `nopie=yes` to the template. Sorry if it was unclear.

**Comment by codingHahn** [comment]
I did exactly this, but it still isn't working.

**Comment by newbluemoon** [comment]
Strange, it’s working for me. I used your template with some slight modifications:

```
# Template file for 'godot'
pkgname=godot
version=2.1.4
revision=1
wrksrc="${pkgname}-${version}-stable"
build_style=scons
depends="libXcursor libXinerama freetype alsa-lib zlib libXrandr"
hostmakedepends="scons pkg-config clang"
makedepends="
 alsa-lib-devel freetype-devel glu-devel libXcursor-devel
 libXinerama-devel libXrender-devel libXrandr-devel libressl-devel pulseaudio-devel"
short_desc="A multiplatform 2D and 3D engine"
maintainer="Nick Hahn <nick.hahn@hotmail.de>"
license="MIT"
homepage="https://www.godotengine.org/"
distfiles="https://github.com/godotengine/${pkgname}/archive/${version}-stable.tar.gz"
checksum=07cf3b01367d5ea53805f144bc60711bd79efb53f1f88d57d6a706e6944de8d7
make_build_args="use_llvm=yes platform=x11 tools=yes target=release_debug colored=yes pulseaudio=no"
nopie=yes

post_extract() {
        sed -i -e "/openssl_version =/,+4d" platform/x11/detect.py
}

do_install() {
        vlicense LICENSE.txt
        vinstall ${FILESDIR}/godot.desktop 644 usr/share/applications/
        vinstall logo.png 644 usr/share/pixmaps/ godot.png

        case "$XBPS_TARGET_MACHINE" in
                x86_64*|aarch64*) vbin bin/godot.x11.opt.tools.64.llvm godot;;
                *) vbin bin/godot.x11.opt.tools.32.llvm godot;;
        esac
}
```

**Comment by codingHahn** [comment]
This is my template. Maybe I am missing something: https://gist.github.com/codingHahn/66021aea8e94ed77d81bb0288e38c5b7

**Comment by newbluemoon** [comment]
Just tried to rebuild the package and got the same error as you. But this morning the package was built successfully! I have it right here. What’s going on? Trying to remember if I did something differently...

**Comment by codingHahn** [comment]
It worked for me too if you built the package already and then retriggred the build. It exits normally then. Maybe a case statement in ```common/environment/build/hardening.sh``` is needed to accomodate for the diffrences between gcc and clang. I think the line 27 is important. Maybe if we could get this compiler aware.

**Comment by newbluemoon** [comment]
> It worked for me too if you built the package already and then retriggred the build.

Yes, that’s it :)

And I also think the difference in `-no-pie` vs. `-nopie` is worth mentioning!

**Comment by newbluemoon** [comment]
Just realized that I put `-pie` in `CFLAGS`/`CXXFLAGS`, but it’s a linker option so it belongs in `LDFLAGS` (order matters!). Now with

CFLAGS+=" -fPIE -fPIC"                                                                                                                                                                             
CXXFLAGS+=" -fPIE -fPIC"
LDFLAGS+=" -pie"

a pie executable is built and everything is OK! :)

**Comment by newbluemoon** [comment]
> Maybe a case statement in common/environment/build/hardening.sh is needed to accomodate for the diffrences between gcc and clang.

But when thinking about it: doesn’t the build system determine which compiler it uses? Can `hardening.sh` know about that decision then?

**Comment by Johnnynator** [comment]
Patch for musl if anyone is interested (I only tested the minesweeper template)

```
--- joystick_linux.cpp  2017-12-12 21:28:08.263329050 +0100
+++ platform/x11/joystick_linux.cpp     2017-12-12 21:29:25.500336429 +0100
@@ -42,6 +42,10 @@
 #include <libudev.h>
 #endif

+#if !defined(__GLIBC__)
+#include <byteswap.h>
+#endif
+
 #define LONG_BITS (sizeof(long) * 8)
 #define test_bit(nr, addr) (((1UL << ((nr) % LONG_BITS)) & ((addr)[(nr) / LONG_BITS])) != 0)
 #define NBITS(x) ((((x)-1) / LONG_BITS) + 1)
```

**Comment by codingHahn** [comment]
I now retriggered the build with your fixes and your (points at @Johnnynator ) patch. I will report back when it is finished

**Comment by codingHahn** [comment]
This can now be closed

**Comment by codingHahn** [comment]
@newbluemoon How would i write a for loop that iterates over all files in a directory?

**Comment by newbluemoon** [comment]
E.g. something like

```
for f in /path/to/dir/*; do
    ls $f
done
```

**Comment by codingHahn** [comment]
Thanks. I am using that to write a template for exporting godot projects

**Comment by codingHahn** [comment]
@cr6git This can be closed now
