### ISSUE TITLE
Package Request: RStudio

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#1655]
"RStudio is an integrated development environment (IDE) for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management."

There's a commercial (business) version and an opensource version.
http://www.rstudio.com/products/rstudio/

Binary & Tarball downloads for Ubuntu/Debian/OpenSUSE/RHEL/OSX/Win.
http://www.rstudio.com/products/rstudio/download/

RStudio is a frontend for R "free software environment for statistical computing and graphics".
https://github.com/voidlinux/void-packages/tree/adfaf103a8ecf77d610343de7fe7dea53dcef38e/srcpkgs/R

**Comment by pullmoll** [comment]
Here's a start at a template. It fails finding some required dependencies and tells to run some script in `./dependencies`, which of course wouldn't work on Void (debian, yum, rpm installer scripts). I gave up for now, so if someone else wants to give it a try?
```shell
# Template file for 'RStudio'
pkgname=RStudio
version=0.99.441
revision=1
wrksrc=${pkgname,,*}-${version}
build_style=cmake
configure_args="-DLIBR_LIBRARIES=${XBPS_CROSS_BASE}/usr/lib/R -DQT5_QMAKE=${XBPS_CROSS_BASE}/usr/bin/qmake-qt5"
hostmakedepends="cmake R qt5-quickcontrols hunspell
 qt5-plugin-mysql qt5-plugin-pgsql qt5-plugin-sqlite qt5-plugin-odbc"
makedepends="boost-devel libressl-devel pam-devel libuuid-devel zlib-devel
 qt5-qmake qt5-devel qt5-declarative-devel qt5-location-devel
 qt5-quick1-devel qt5-sensors-devel qt5-svg-devel qt5-webkit-devel"
depends="R"
short_desc="Integrated development environment (IDE) for R"
maintainer="John Doe <john.doe@example.com>"
license="GPL-3"
homepage="http://www.rstudio.com/products/rstudio/"
distfiles="https://github.com/rstudio/rstudio/archive/v${version}.tar.gz>${pkgname}-${version}.tar.gz"
checksum=86b6c1228162423625c3114b3da89c7c2eb64be3b5ee0be126a268af1b1ade99
```

**Comment by JayVii** [comment]
I'm still research & trying... It may need Java (jdk) in order to run. I'll report back ASAP. Thank you very much for taking the time :)

**Comment by pullmoll** [comment]
I'm working in it - again. It seems I almost got it. The file `https://s3.amazonaws.com/rstudio-dictionaries/core-dictionaries.zip` has to be included in the distfiles. I don't think qt4 is the choice, because it is EOL at the end of this year.

I'll create a pr once I got it working, or I'll post the template that still fails when I give up :)

**Comment by pullmoll** [comment]
This requires a new package R-devel for the libR.so to link against. I'll add a pr for this first, then I can continue trying to get this beast to build.

**Comment by pullmoll** [comment]
FWIW even with the R-devel package I eventually get tons of linking errors. I think there are still some bits missing in the Java section.

This package is not fun. If anyone wants to pick up where I fainted out... :)

**Comment by JayVii** [comment]
Dang :/ Thanks for your efforts, though... Greatly appreciated :)
I'll fiddle with it, but I highly doubt i will be of much help about that one.

**Comment by JayVii** [comment]
No updates on this, I suppose?
Is #1720 still the issue?

**Comment by pullmoll** [comment]
I gave up on this. A copy of latest `srcpkgs/RStudion/template` can [be found here](http://sprunge.us/OHBd).
The R-devel package would be trivial, but I think you can just as well use `R` itself.

**Comment by ebfe** [comment]
Using a R package build with `--enable-R-shlib` the binaries from the official
.deb package seem to work.

**Comment by JayVii** [comment]
@ebfe I can confirm!
I just added the `--enable-R-shlib` flag to the R-tempalte, compiled it and RStudio works for me now. (Maintainer of "R": @chneukirchen )
```
# Template file for 'R'
pkgname=R
version=3.2.4
revision=3
nocross=yes
nopie=yes
build_style=gnu-configure
configure_args="--docdir=/usr/share/doc/R rdocdir=/usr/share/doc/R
 --with-system-zlib --with-system-bzlib --with-system-pcre --with-system-xz
 --with-lapack --with-blas --enable-R-shlib
 LIBnn=lib"
hostmakedepends="gcc-fortran pkg-config perl less"
makedepends="libgomp-devel readline-devel libXmu-devel libXt-devel
 libpng-devel libjpeg-turbo-devel tiff-devel cairo-devel icu-devel
 lapack-devel blas-devel zlib-devel bzip2-devel pcre-devel liblzma-devel
 libcurl-devel"
depends="xdg-utils less"
short_desc="System for statistical computation and graphics"
maintainer="Christian Neukirchen <chneukirchen@gmail.com>"
license="GPL-2"
homepage="http://www.r-project.org/"
distfiles="http://cran.r-project.org/src/base/R-3/${pkgname}-${version}.tar.gz"
checksum=bafd405fe9c2fe3bbe47a8a7730ad120f03b7df9fb0f61674fca19cf061dd350

pre_configure() {
        export R_BROWSER=/usr/bin/xdg-open
        export R_PDFVIEWER=/usr/bin/xdg-open
}
```

I didn't compile Rstudio, though. I downloaded one of the [Tarballs](https://download1.rstudio.org/rstudio-0.99.893-amd64-debian.tar.gz), which contains a "bin/" folder. This does contain a working RStudio binary (however, you have to link your system's `/usr/lib/R/library` to `/usr/lib64/R/lib` at least on x86_64)

If Rstudio, still can't be compiled, this could at least be used for an "rstudio-bin" package.

**Comment by ebfe** [comment]
Last 2 commits on https://github.com/ebfe/void-packages/commits/rstudio-desktop "seem" to work but it's very sketchy and usr/lib/rstudio/lib/*.so generate false dependencies (or maybe we should symlink them to our /usr/lib versions).

**Comment by Vaelatern** [comment]
#4224

**Comment by chneukirchen** [comment]
Got merged.
