### ISSUE TITLE
Idea for xbps-install: remove <pkg>.new_<version>_<release> config files if unchanged

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1668]
In order to reduce the mess when force reinstalling packages, `config.new...` files that did not change (same hash?) could be removed afterwards.
For additional user friendlyness the `config.new...` files where only some lines were added to the original (diff output check for just '<' lines?) could be removed as well.

**Comment by xtraeme** [comment]
Please submit this PR to the `xbps` repo instead :-)
