### ISSUE TITLE
Package request: fcron

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1672]
"Fcron is a periodical command scheduler which aims at replacing Vixie Cron, so it implements most of its functionalities.

But fcron makes no assumptions on whether your system is running all the time or regularly : you can, for instance, tell fcron to execute tasks every x hours y minutes of system up time or to do a job only once in a specified interval of time.

Fcron has also much more functionalities : you can also set a nice value to a job, run it depending on the system load average and much more !"

Particularly pursued for notebook usage where the system isn't always on.

**Comment by chneukirchen** [comment]
(cronie with anacron works well for this usecase already, btw.)

**Comment by thypon** [comment]
I used on my previous installation and it works quite well / has a nice user interface.
