### ISSUE TITLE
Idea: template shlibs="libxyz.so.99"

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1690]
In order to overcome the frequent problems with pull requests adding to the end of `common/shlibs` where this file was already modified since the requester made his changes and committed the pull request, instead some template variable `shlibs="libxyz.so.99"` containing one or more shlibs for the specific package to register could be parsed and `common/shlibs` could be updated accordingly.

If a new shlibs entry was appended this way, the modified `common/shlibs` should then be pushed to the repository by the admin applying the pull request (or their own package) along with the package.

This can probably even be automated through git hooks, while I have no idead how I would do that.

**Comment by bougyman** [comment]
I don't see how this solution addresses the problem of someone committing to common/shlibs before you. Same conflict would happen.

**Comment by pullmoll** [comment]
You are right, this can never be bullet proof. At best it would reduce the number of conflicts due to the lower number of committers (collaborators vs. external contributors).

**Comment by beefcurtains** [comment]
Or it could be a ``shlibs.d`` with a file for each package that ships shlibs, or a ``shlibs`` file right next to the template with the same format.

**Comment by pullmoll** [comment]
I think it would be better to keep shlib dependencies in one place, though. `common/shlibs.d` seems very acceptable to me, since parsing or grepping there should be not too different from grepping in a single file.
