### ISSUE TITLE
gajim does not start after installation

### ISSUE THREAD

**Issue by mattiasgiese** [voidlinux/void-packages#1695]
Heya,

after installing gajim i get the following error while starting:

```
WARNING: Couldn't write lextab module 'pycparser.lextab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/lextab.py'
WARNING: yacc table file version is out of date
WARNING: Couldn't create 'pycparser.yacctab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/yacctab.py'
Traceback (most recent call last):
  File "gajim.py", line 131, in <module>
    logging_helpers.init(sys.stderr.isatty())
  File "/usr/lib/python2.7/site-packages/gajim/common/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/lib/python2.7/site-packages/gajim/common/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
  File "/usr/lib/python2.7/site-packages/gajim/common/logging_helpers.py", line 22, in <module>
    import i18n
  File "/usr/lib/python2.7/site-packages/gajim/common/demandimport.py", line 95, in _demandimport
    return _import(name, globals, locals, fromlist, level)
  File "/usr/lib/python2.7/site-packages/gajim/common/i18n.py", line 54, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by cavalier911** [comment]
Hi,
Starts on x86_64 glibc with lxde
First run after install:
[rj@voidlinux ~]$ gajim
WARNING: Couldn't write lextab module 'pycparser.lextab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/lextab.py'
WARNING: yacc table file version is out of date
WARNING: Couldn't create 'pycparser.yacctab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/yacctab.py'

** (gajim:1362): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (gajim:1362): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (gajim:1362): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
creating /home/rj/.cache/gajim directory
creating /home/rj/.local/share/gajim directory
creating /home/rj/.config/gajim directory
creating /home/rj/.cache/gajim/vcards directory
creating /home/rj/.cache/gajim/avatars directory
creating /home/rj/.config/gajim/pluginsconfig directory
creating logs database
creating cache database
creating /home/rj/.local/share/gajim/certs directory
creating /home/rj/.config/gajim/localcerts directory
/usr/lib/python2.7/site-packages/gajim/roster_window.py:6554: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  self.window.show_all()

Regular start:
[rj@voidlinux ~]$ gajim
WARNING: Couldn't write lextab module 'pycparser.lextab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/lextab.py'
WARNING: yacc table file version is out of date
WARNING: Couldn't create 'pycparser.yacctab'. [Errno 13] Permission denied: '/usr/lib/python2.7/site-packages/pycparser/yacctab.py'

** (gajim:1397): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (gajim:1397): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (gajim:1397): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
/usr/lib/python2.7/site-packages/gajim/roster_window.py:6554: Warning: g_object_set_qdata: assertion 'G_IS_OBJECT (object)' failed
  self.window.show_all()

**Comment by mattiasgiese** [comment]
Regenerating my locales fixed the problem. Thanks @cavalier911!

**Comment by biopsin** [comment]
tried to regenarate locale but my error remained
"UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 4: invalid start byte"

solution was to follow this
https://python-nbxmpp.gajim.org/changeset/9cbf8b322d8ba99bb7ef95115422d8954e91eead

**Comment by Joshuaalbert** [comment]
@biopsin Could you give instructions? The link is dead.

**Comment by biopsin** [comment]
Sorry Joshua, I can't be more helpfull ,to long a go for me to remember, I did change from utf-8 to encoding='ISO-8859-1' ..uhm somewhere
