### ISSUE TITLE
ebtlables broken on musl

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1700]
Shouldn't we provide a `nomusl` flag to early disable the musl compilation?

**Comment by beefcurtains** [comment]
No. It should be fixed. ebtables still exists in your kernel when you swap out one libc for another.

**Comment by thypon** [comment]
@Gottox is the current mantainer. I think however that a flag like that could help other "non portable" projects.

**Comment by beefcurtains** [comment]
You need the userspace utility to configure ebtables in the kernel. The kernel doesn't care what libc you're using, but the utility was probably never tested with anything other than glibc. I think it was also missing on Alpine last time I checked.

**Comment by thypon** [comment]
It was missing also on voidlinux before i start using it. I ask @Gottox  to package it because libvirtd didn't start cleanly without. Maybe there are alternatives to ebtables, i'm not an expert.

**Comment by beefcurtains** [comment]
[Thanks.](https://github.com/voidlinux/void-packages/pull/1702)
