### ISSUE TITLE
Request to update mps-youtube

### ISSUE THREAD

**Issue by griffrog** [voidlinux/void-packages#1707]
The latest version of mps-youtube works with the current youtube API, but hasn't been updated in the repos.

**Comment by logenkain** [comment]
On Mon, Jun 01, 2015 at 11:19:43AM -0700, Horatio Ignatius wrote:
> The latest version of mps-youtube works with the current youtube API, but hasn't been updated in the repos.

Thanks for the heads up, I'll get on that right now.
