### ISSUE TITLE
Package Request: Kingsoft WPS Office [ALPHA]

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#1711]
"Established in 1989, KINGSOFT Office is a leading global developer of office software solutions, developing productivity applications for the consumer and enterprise markets. With over 800 million registered users worldwide, its flagship product WPS Office (“best Microsoft Office alternative…” – CNET) is one of the world’s most popular cross-platform office suites supporting iOS and Android, as well as Windows and Linux PCs."
http://wps-community.org/download.html

Packages are available as .deb/.rpm/.tar.xz for both 32- & 64-bit.
The .tar.xz contains already functional binaries and a fonts-installer script. This should (in theory) make a really simple script.

WPS is still in Alpha for linux. Not sure, if that matters, but I guess it's worth mentioning.
AFAIK, this is non-free software (no source-files available).

**Comment by dominikh** [comment]
> In order to distribute Kingsoft Office you need to agree the LICENSE AGREEMENT OF KINGSOFT OFFICE FOR LINUX COMMUNITY, click here for details.

> According the license, you have to send an email to inform us you are distributing this product.

> You are only allowed to distribute the “Product” provided by Kingsoft as a whole on an AS IS basis. The distributed “Product” shall only be the unmodified complete version provided by Kingsoft

And yes, it's non-free software.

**Comment by JayVii** [comment]
Rather than distributing, it would probably be possible to create a pseudo-package or a script, that downloads the .tar.xz from the website, moves the binaries in "/usr/bin/" or "/opt/wps-office/" & runs the font-installer-script. Could be as simple as a bash-script.

**Comment by the-maldridge** [comment]
Is there an answer to the above license issue question?

**Comment by the-maldridge** [comment]
@xtraeme at your convenience I believe this is ready for review.
