### ISSUE TITLE
python: undefined symbol: pam_start when trying to launch cinnamon-settings

### ISSUE THREAD

**Issue by kylesusername** [voidlinux/void-packages#1732]
As the title suggests, when trying to launch cinnamon-settings, the error is 
`python: undefined symbol: pam_start`

This is with `cinnamon-2.4.8_2`, `python-2.7.10_3`, `python-pam-0.1.4_5`.

I suspect it is a similar issue to [https://github.com/voidlinux/void-packages/issues/914] , but installing/having gcc installed didn't fix it.

Maybe it's time to head back to Awesome, or onto dwm.

**Comment by xtraeme** [comment]
You've been hit by the incomplete transition to `/usr/sbin` as symlink transition.

Fix: `xbps-reconfigure -f python`

**Comment by kylesusername** [comment]
I don't believe so, as running `xbps-reconfigure -f python` and `xbps-reconfigure -f python-pam` don't  fix the problem. As part of the debugging, I tried fully removing and then fully installing Cinnamon. I've also ried `xbps-reconfigure -f *cinnamon*` which also didn't fix the problem despite reconfiguring all parts of cinnamon.

**Comment by xtraeme** [comment]
Is your system fully uptodate?

**Comment by kylesusername** [comment]
@xtraeme Yes, it is. Fully up-to-date x86_64.

**Comment by kylesusername** [comment]
Fixed now.
