### ISSUE TITLE
Dracut not booting

### ISSUE THREAD

**Issue by Mentha** [voidlinux/void-packages#1748]
Yesterday, I've updated a few packages, rebooted, dracut complains not founding my root file-system, saying that could not boot because could not find my dev/disk/by-uuid, but is there, is the boot partition. 

Read how to debug, not being able to resolve my problem, having a spare HD, downloaded the latest base i686 ISO which I also could not boot to the installer(kernel panic error), as an alternative, got the previous one.

Installed, made the updates and rebooted, the same boot error as before from dracut, I've tried to hold the base-utils package in a re-installation, because I know that this was one of the few packages that I first updated in my original installation, but gave me the same error as the first ISO that I've downloaded.

I can't resolve my problem being honest.

**Comment by thypon** [comment]
Hi @Mentha . We are currently in the middle of a transition to unified `/usr/{bin,sbin}` directory. It's possible that dracut (or runit) could't find some executable to terminate the initial phase boot.
Could you give me your fs layout configuration to replicate your setup?

**Comment by xtraeme** [comment]
I just fixed this here: https://github.com/voidlinux/void-packages/commit/3316ae505385c8b59d67abbd5918891d65b05468

Please update via `xbps-install -Suv` and try to regenerate the initramfs.

**Comment by xtraeme** [comment]
Fixed with up-to-date `base-files` and `eudev` packages.

Thanks
