### ISSUE TITLE
Package Request: brackets

### ISSUE THREAD

**Issue by Mentha** [voidlinux/void-packages#1755]
Requesting a new package, Brackets, Adobe's IDE for the web.
https://github.com/adobe/brackets

Thank you.

**Comment by mar1n3r0** [comment]
It's been requested previously... https://github.com/voidlinux/void-packages/issues/1142

I have tried to make a template myself but am not proficient enough as of yet.

**Comment by asergi** [comment]
Duplicate #1142.
