### ISSUE TITLE
xbps-src: is not using muslrepo.voidlinux.eu/current

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1756]
When setting up the masterdir for a `x86_64-musl` build (`./xbps-src -m musl binary-bootstrap x86_64-musl), instead of looking for packages at `http://muslrepo.voidlinux.eu/current` packages are searched for at the generic `http://repo.voidlinux.eu/current` first, where this error happens:
`ERROR: [reposync] failed to fetch file `http://repo.voidlinux.eu/current/x86_64-musl-repodata': Not Found`

In the second step the repodata is then downloaded from `http://muslrepo.voidlinux.eu/current/x86_64-musl-repodata`.

As a consequence(?) the noarch package `xbps-triggers-0.97_1.noarch.xbps` is fetched from a _local_ repository, if available, and the signature verification fails.

Here's the output of a try to `binary-bootstrap x86_64-musl`:
```shell
$ ./xbps-src -m /tmp/musl binary-bootstrap x86_64-musl
=> Installing bootstrap from binary package repositories...
[*] Updating `http://repo.voidlinux.eu/current/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `http://repo.voidlinux.eu/current/x86_64-musl-repodata': Not Found
[*] Updating `http://muslrepo.voidlinux.eu/current/x86_64-musl-repodata' ...
`/mnt/data/void/binpkgs' repository has been RSA signed by "pullmoll@voidlinux.de"
Fingerprint: 95:6e:94:54:eb:d7:29:a7:fe:25:97:d3:b8:f3:6b:bc
Do you want to import this public key? [Y/n] 
```
As you can see it tries to use the `xbps-triggers-0.97_1.noarch.xbps` from the local repo.

I think the same happens on travis-ci.org (see #1720) and also think that in no case local packages should be used when a binary-bootstrap is commenced?

Currently I have no idea how to stop it asking for using the local repo.

**Comment by xtraeme** [comment]
- repo.voidlinux.eu/current only contains repos for glibc
- muslrepo.voidlinux.eu/current only contains repos for musl

What I'm seeing here is just the expected behaviour, afaik

**Comment by pullmoll** [comment]
Non issue.
