### ISSUE TITLE
Tracking bug: templates broken due to 101839b6e

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#1779]
In 101839b6e CFLAGS/LDFLAGS passing was changed, which resulted in template modifications.

A bulk build on aarch64 shows that these package need fixing:

- [x] 2bwm
- [x] cd-discid
- [x] i3blocks
- [x] lemonbar
- [x] mopag-git
- [x] quark-git
- [x] sic-git
- [x] smu
- [x] stfl
- [x] sxhkd
- [x] thingmenu-git
- [x] xtitle
- [x] capstone
- [x] cvsps2
- [x] comic-git
- [x] dumpet
- [x] dvtm
- [x] frankenwm
- [x] horst
- [x] ii
- [x] libCello
- [x] libfetch
- [x] ms-sys
- [x] nestopia
- [x] odo
- [x] pcsc-tools
- [x] physlock
- [x] rsstail
- [x] sandy
- [x] signify
- [x] st
- [x] tabbed
- [x] thinglaunch-git
- [ ] vis-git
- [x] wmutils-core
- [x] xautolock
- [x] xcape
- [x] xcmenu-git

Paging @logenkain @hanspolo @uggedal @Ypnose.

**Comment by uggedal** [comment]
i3blocks and xtitle should be fixed.

**Comment by Ypnose** [comment]
Thanks for the bump. I'll "take care" of my pkgs and also modify all my *-git.

**Comment by xtraeme** [comment]
cdrtools was built 4 days ago... and it builds just fine, removing it.

**Comment by xtraeme** [comment]
I vote to remove those useless -git pkgs!

**Comment by thypon** [comment]
+1 for git packages

**Comment by Ypnose** [comment]
Dunno if they're useless, but yeah I will modify my pkgs (when I have time). If you can't wait a few days, simply obliterate them.

**Comment by xtraeme** [comment]
- thinglaunch-git can be replaced by the released 2.4 version ( @Ypnose )
- xcmenu-git can be replaced by the 0.1.0 released version ( @Duncaen )

**Comment by xtraeme** [comment]
All my packages have been fixed.

I won't touch the others :-)

**Comment by Ypnose** [comment]
I'm on it xtraeme (started slowly yesterday).

**Comment by Duncaen** [comment]
I can replace `xcmenu-git` with version 0.1, but i dont use it anymore and its not well written, removing it would be also ok for me.

**Comment by Ypnose** [comment]
Hehe. Already replaced (but still fixing it with musl).

**Comment by Ypnose** [comment]
<code>comic-git</code> was removed.

**Comment by beefcurtains** [comment]
Ok to replace ``frankenwm-git`` with ``frankenwm-1.0``?

**Comment by xtraeme** [comment]
:+1:

**Comment by Ypnose** [comment]
<code>frankenwm</code> was replaced.
