### ISSUE TITLE
Package request: crystal-lang

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1781]
http://crystal-lang.org/

A native ruby-like language.

**Comment by thypon** [comment]
crytstal-lang requires crystal-lang compiler to compile itself: someone knows how to solve?

**Comment by beefcurtains** [comment]
With just the information from that site:
* Use the Ruby compiler with the latest version that worked with it
* Use that Crystal compiler to build crystal 0.1.0
* Use that Crystal compiler to build crystal 0.2.0
...and so on.

**Comment by thypon** [comment]
A little overkill.

**Comment by teh-jazzman** [comment]
As far as I can tell at a glance [from the documentation](http://crystal-lang.org/docs/installation/from_source_repository.html) they want others to at least use the compiler from their binary releases to build the sources but they only provide it for x86_64. It is alpha software, so that may change in the future.

**Comment by beefcurtains** [comment]
Or wait for the gentoo ebuild and port that.

**Comment by aeosynth** [comment]
bump. how are other self hosted languages built?

**Comment by LVMBDV** [comment]
I had the same question before I even saw this issue. I asked it in the IRC channel and it seems the correct approach would be to make the `crystal-bin` package first, then the source package `crystal`. I guess I will try my hand at it.

```
08:32 <lvmbdv> i have a question, it says "Compiled: The software needs to be compiled before being used, even if it is software that is not needed by the whole system."
08:33 <lvmbdv> what if a package needs a binary of itself to be compiled? (like language compilers written in their own language e.g. crystal)
08:34 <maldridge> generally you have thing-bin and thing
08:34 <maldridge> yarn and yarn-bin are examples of this
08:34 <lvmbdv> oh i see
08:34 <lvmbdv> -bin doesn't have to be statically compiled, right?
08:34 <maldridge> -bin just has to work
08:35 <maldridge> the only thing that's permitted to depend on it is the build of the native one
08:35 <lvmbdv> that's how i should do it then
08:36 <lvmbdv> first, make the package crystal-bin then make the package crystal which depends on crystal-bin
08:36 <maldridge> yes, that would be the ideal
08:36 <maldridge> you could also look at what go does if that makes sense
08:37 <lvmbdv> alright, thanks maldridge 
```

**Comment by Vaelatern** [comment]
Be sure to add a build-option so you don't need to rely on the pre-provided binary, but instead rely on the crystal package itself. In the `yarn-bin` case it's necessary to keep it around for some reason, but hopefully crystal will be more stable once we have it at all.

**Comment by aeosynth** [comment]
@LVMBDV thanks for packaging crystal, there's just one thing missing - the `shards` package manager

**Comment by LVMBDV** [comment]
I had it on my mind while I was working on `crystal`, will be ready (hopefully) soon.

**Comment by aeosynth** [comment]
i would personally prefer it all in one package, like `nodejs` and `npm`, `elixir` and `mix`, but in the end it probably doesn't matter.

**Comment by LVMBDV** [comment]
Alright, will make it an update to crystal along with some other things.

**Comment by aeosynth** [comment]
@thypon this issue can be closed :tada:

**Comment by maxice8** [comment]
@lemmi please close dis
