### ISSUE TITLE
VirtualBox broken after update

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#1788]
I updated and couldn't run VirtualBox anymoar. So I tried to `xbps-reconfigure
-f` it, but it failed. Then I tried to uninstall and reinstall it, but failed
with teh same errors:

    # xbps-install virtualbox-ose
    
    Name                Action    Version           New version            Download size
    virtualbox-ose-dkms install   -                 4.3.28_3               - 
    virtualbox-ose      install   -                 4.3.28_3               - 
    
    Size required on disk:          82MB
    Free space on disk:            704GB
    
    Do you want to continue? [Y/n] 
    
    [*] Downloading binary packages
    
    [*] Verifying package integrity
    virtualbox-ose-dkms-4.3.28_3: verifying RSA signature...
    virtualbox-ose-4.3.28_3: verifying RSA signature...
    
    [*] Running transaction tasks
    virtualbox-ose-dkms-4.3.28_3: unpacking ...
    virtualbox-ose-4.3.28_3: unpacking ...
    
    [*] Configuring unpacked packages
    virtualbox-ose-dkms-4.3.28_3: configuring ...
    DKMS module 'virtualbox-ose-4.3.28' already added, skipping.
    Building DKMS module 'virtualbox-ose-4.3.28' for kernel-4.0.5_1... FAILED!
    DKMS module 'virtualbox-ose-4.3.28' failed to build, please check /var/lib/dkms
    for errors in the log file.
    virtualbox-ose-dkms-4.3.28_3: installed successfully.
    virtualbox-ose-4.3.28_3: configuring ...
    Created vboxusers () system group.
    Updating GTK+ icon cache for /usr/share/icons/hicolor...
    Updating MIME database...
    Updating shared-mime-info database...
    virtualbox-ose-4.3.28_3: post-install message:
    ========================================================================
    You should also add your user to the 'vboxusers' group to be able
    to use some VirtualBox features, e.g USB.
    ========================================================================
    virtualbox-ose-4.3.28_3: installed successfully.
    
    0 downloaded, 2 installed, 0 updated, 2 configured, 0 removed.

And at `/var/lib/dkms/virtualbox-ose/4.3.28/build`

    # tail make.log 
    DKMS make.log for virtualbox-ose-4.3.28 for kernel 4.0.5_1 (x86_64)
    Sun Jun  7 02:16:37 BRT 2015
    make: Entering directory '/usr/src/kernel-headers-4.0.5_1'
    Makefile:612: arch/x86/Makefile: No such file or directory
    make: *** No rule to make target 'arch/x86/Makefile'.  Stop.
    make: Leaving directory '/usr/src/kernel-headers-4.0.5_1'

**Comment by xtraeme** [comment]
Upgrade your system with `xbps-install -Suv`, make sure there are no regular files in `/usr/sbin`, reboot; `xbps-reconfigure -f virtualbox-ose-dkms` and it should work again.

I won't accept any issue related to the the `/usr/sbin` merge unless the user has already updated completely the system.

**Comment by xtraeme** [comment]
Also see https://groups.google.com/forum/#!topic/voidlinux/iZXamHmohQ4

**Comment by ayghor** [comment]
I had already done teh `xbps-install -Su`. But did it again just in case. Also removed stuff from `/usr/sbin`, as you instructed, it was a directory and became a symlink after reboot. `xbps-reconfigure -f` failed with teh same error.

**Comment by xtraeme** [comment]
See the url I posted above... you'll have to either remove /var/lib/dkms and xbps-reconfigure or run dkms manually.

**Comment by ayghor** [comment]
I tried running it manually, but got teh same makefile error. Will try to move /var/lib/dkms.

And moving /usr/sbin also messed up some packages, like apache, which had binaries there.

**Comment by ayghor** [comment]
No luck

    # cd /var/lib
    # xbps-reconfigure -f virtualbox-ose-dkms
    virtualbox-ose-dkms: configuring ...
    Added DKMS module 'virtualbox-ose-4.3.28'.
    Building DKMS module 'virtualbox-ose-4.3.28' for kernel-4.0.5_1... FAILED!
    DKMS module 'virtualbox-ose-4.3.28' failed to build, please check /var/lib/dkms
    for errors in the log file.
    virtualbox-ose-dkms: configured successfully.
    # cat dkms/virtualbox-ose/4.3.28/build/make.log 
    DKMS make.log for virtualbox-ose-4.3.28 for kernel 4.0.5_1 (x86_64)
    Sun Jun  7 03:10:33 BRT 2015
    make: Entering directory '/usr/src/kernel-headers-4.0.5_1'
    Makefile:612: arch/x86/Makefile: No such file or directory
    make: *** No rule to make target 'arch/x86/Makefile'.  Stop.
    make: Leaving directory '/usr/src/kernel-headers-4.0.5_1'

**Comment by ayghor** [comment]
Made it again to be sure:

    # cd /var/lib/
    # rm -rf dkms/
    # xbps-reconfigure -f virtualbox-ose-dkms
    virtualbox-ose-dkms: configuring ...
    Added DKMS module 'virtualbox-ose-4.3.28'.
    Building DKMS module 'virtualbox-ose-4.3.28' for kernel-4.0.5_1... FAILED!
    DKMS module 'virtualbox-ose-4.3.28' failed to build, please check /var/lib/dkms
    for errors in the log file.
    virtualbox-ose-dkms: configured successfully.
    # cat dkms/virtualbox-ose/4.3.28/build/make.log 
    DKMS make.log for virtualbox-ose-4.3.28 for kernel 4.0.5_1 (x86_64)
    Sun Jun  7 03:29:23 BRT 2015
    make: Entering directory '/usr/src/kernel-headers-4.0.5_1'
    Makefile:612: arch/x86/Makefile: No such file or directory
    make: *** No rule to make target 'arch/x86/Makefile'.  Stop.
    make: Leaving directory '/usr/src/kernel-headers-4.0.5_1'

**Comment by ayghor** [comment]
Also tried this:

    # dkms build -m virtualbox-ose -v 4.3.28 -k $(uname -r)
    
    Kernel preparation unnecessary for this kernel.  Skipping...
    
    Building module:
    cleaning build area....
    make KERNELRELEASE=4.0.5_1 -C /lib/modules/4.0.5_1/build M=/var/lib/dkms/virtualbox-ose/4.3.28/build....(bad exit status: 2)
    Error! Bad return status for module build on kernel: 4.0.5_1 (x86_64)
    Consult /var/lib/dkms/virtualbox-ose/4.3.28/build/make.log for more information.

**Comment by xtraeme** [comment]
Make sure `/usr/sbin` is a symlink, otherwise dkms won't work.

**Comment by ayghor** [comment]
It is

**Comment by ayghor** [comment]
# ls -lha /usr
    total 156K
    drwxr-xr-x 12 root root 4.0K Jun  7 02:54 .
    drwxr-xr-x 17 root root 4.0K Jun  7 03:44 ..
    drwxr-xr-x  2 root root  36K Jun  7 03:44 bin
    drwxr-xr-x 67 root root  12K Jun  7 03:44 include
    drwxr-xr-x 71 root root  68K Jun  7 03:44 lib
    drwxr-xr-x  2 root root 4.0K Jun  6 16:17 lib32
    lrwxrwxrwx  1 root root    3 Dec  5  2014 lib64 -> lib
    drwxr-xr-x 11 root root 4.0K Jun  7 03:16 libexec
    drwxr-xr-x  7 root root 4.0K Dec  5  2014 local
    lrwxrwxrwx  1 root root    3 Jun  7 02:48 sbin -> bin
    drwxr-xr-x  2 root root 4.0K Jun  7 02:47 sbin.old
    drwxr-xr-x  2 root root 4.0K Jun  7 02:42 sbin_bkp
    drwxr-xr-x 77 root root 4.0K Jun  7 03:44 share
    drwxr-xr-x  5 root root 4.0K Jun  7 03:08 src

**Comment by xtraeme** [comment]
Ok, I see what's the issue... fix incoming.

Thanks.

**Comment by ayghor** [comment]
Yay!

**Comment by xtraeme** [comment]
Wait until this build finishes and upgrade, hopefully the vbox modules will be built correctly this time.

Thanks

**Comment by ayghor** [comment]
modules are built and VirtualBox actually started, but I'm getting ERROR messages on startup:

    modprobe: ERROR: could not insert 'vboxguest': No such device
    modprobe: ERROR: could not insert 'vboxsf': No such device

**Comment by thypon** [comment]
@ayghor maybe you should insert these modules in modprobe manually.

**Comment by ayghor** [comment]
# modprobe vboxguest
modprobe: ERROR: could not insert 'vboxguest': No such device

**Comment by ayghor** [comment]
same for vboxsf

    # modprobe vboxsf
    modprobe: ERROR: could not insert 'vboxsf': No such device

**Comment by teh-jazzman** [comment]
It sounds as if you installed the VirtualBox guest additions packages `virtualbox-ose-guest` and `virtualbox-ose-guest-dkms` on your host machine. That will not work as they are designed to be installed in a void guest system running inside VirtualBox.

**Comment by ayghor** [comment]
oh! I see! ty!
