### ISSUE TITLE
libGL: missing shlibs entries?

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1791]
When building libGL the following warnings are printed:
```
=> WARNING: mesa-ati-dri-10.5.7_1: libXvMCgallium.so.1 not found in common/shlibs!
=> WARNING: mesa-nouveau-dri-10.5.7_1: libXvMCgallium.so.1 not found in common/shlibs!
=> WARNING: mesa-opencl-10.5.7_1: libMesaOpenCL.so.1 not found in common/shlibs!
```
I'm not sure if and which entry should be added to `common/shlibs`to fix these warnings. Can one so-name reference multiple packages?

**Comment by xtraeme** [comment]
Those shared libs are not expected to be linkable, i.e no other pkg will be linked explicitely against them.

The warnings are just there but should be really ignored.
