### ISSUE TITLE
gtk+3-3.16.4_1: breaks midori,xombrero

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#1818]
gtk+3-3.16.4_1  changes permissions of /usr/share/glib-2.0/schemas/gschemas.compiled to 600
Regular user can't start midori or xombrero due to (Permission denied) to read gschemas.compiled
`[pid   817] open("/usr/share/glib-2.0/schemas/gschemas.compiled", O_RDONLY) = -1 EACCES (Permission denied)`
Changing permissions to 644 allows regular user to start midori or xombrero 
`chmod 644 /usr/share/glib-2.0/schemas/gschemas.compiled`

**Comment by xtraeme** [comment]
This file has correct permissions on my system:
```
-rw-r--r-- 1 root root 34741 jun 11 09:37 /usr/share/glib-2.0/schemas/gschemas.compiled
```

I think you were hit by the temporary umask issue that I introduced with `/etc/login.defs` and `/etc/profile`, that was fixed past week.

Please change the permissions manually and make sure `/etc/profile` has `umask 022`.

**Comment by cavalier911** [comment]
<blockquote>I think you were hit by the temporary umask issue that I introduced with /etc/login.defs and /etc/profile, that was fixed past week.</blockquote>
Yep, umask 022 in /etc/profile prevents gtk+3 install from changing gschemas.compiled permissions from 644.
I have a modified /etc/profile and should have manually merged /etc/profile.new-0.128_1 after installing base-files-0.128_1.x86_64.xbps  
Thanks
