### ISSUE TITLE
Package request: linux-ck

### ISSUE THREAD

**Issue by phikal** [voidlinux/void-packages#1831]
The linux-ck patches by Con Kolivas and includes the [Brain Fuck Scheduler](http://ck.kolivas.org/patches/bfs/bfs-faq.txt), which has been reported to improve performance.

Link here: http://users.on.net/~ckolivas/kernel/

**Comment by thypon** [comment]
The Con Kolivas patchset is outdated often, moreover the BFQ io scheduler, usually annexed, is being merged in mainline. You can obtain similar things with #1824 ulatencyd remaining in user space.

**Comment by beefcurtains** [comment]
Agree with Thypon, latest stable and lts should be good enough for everyone *winkyface*
