### ISSUE TITLE
Bug: xbps-src bootstrap fails building ncurses without root permissions (tries to mkdir -p /usr/lib/pkgconfig)

### ISSUE THREAD

**Issue by kylesusername** [voidlinux/void-packages#1833]
When trying to `xbps-src bootstrap` , it fails trying to make ncurses.

Here is the error message:

`=> ncurses-5.9_14: running do_configure ... `
`mkdir: cannot create directory '/usr/lib/pkgconfig': Permission denied`
`=> ERROR: ncurses 5.9_14: failed to run do_configure at line 25.`

Looking through the srcpkgs/ncurses/template, there are several tries to read and write from the root directory rather than the void-packages directory. All attempted writes to the rootfs fail and end the `bootstrap`.

Also, I can't seem to find the 'label' feature on github.

**Comment by beefcurtains** [comment]
This has been in there since March, strange that this error never occurred before. Nevertheless it should work for you now, please do a ``git pull`` and retry.

**Comment by kylesusername** [comment]
`=> Installed bootstrap successfully!`
Awesome, thanks for that patch.
