### ISSUE TITLE
Bug: xbps-src pkg st fails

### ISSUE THREAD

**Issue by kylesusername** [voidlinux/void-packages#1837]
When building `st` from source via void-packages, the build fails
`In file included from st.c:29:0:`
`/usr/include/X11/Xft/Xft.h:39:22: fatal error: ft2build.h: No such file or directory`
` #include <ft2build.h>`

`=> ERROR: st-0.5_4: failed to run do_build() at line 8.`

The file `<ft2build.h>` exists at `/usr/include/freetype2/ft2build.h`, but the `#include` is looking in the wrong place, where it should be `#include <freetype2/ft2build.h>`. This appears to be an issue with `Xft.h`, and probably affects all software using it.

**Comment by xtraeme** [comment]
https://github.com/voidlinux/void-packages/issues/1779
