### ISSUE TITLE
gettext: compiling for musl doesn't build libintl.so

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1840]
Compiling gettext for musl doesn't build any `libintl.so*` libraries or symlinks, though common/shlibs tells there should be a `libintl.so.9` installed by `gettext-0.19.2_1`.

The contents of my `gettext-libs-0.19.4_9.x86_64-musl.xbps` after building gettext for musl locally is:
```
-rw-r--r-- root/root      1216 2015-06-16 06:58 ./props.plist
-rw-r--r-- root/root      2025 2015-06-16 06:58 ./files.plist
-rwxr-xr-x 0/0         1290160 2015-06-16 06:58 ./usr/lib/libgettextlib-0.19.4.so
-rwxr-xr-x 0/0          330680 2015-06-16 06:58 ./usr/lib/libgettextpo.so.0.5.3
-rwxr-xr-x 0/0          277160 2015-06-16 06:58 ./usr/lib/libgettextsrc-0.19.4.so
lrwxrwxrwx 0/0               0 2015-06-16 06:57 ./usr/lib/libgettextsrc.so -> libgettextsrc-0.19.4.so
lrwxrwxrwx 0/0               0 2015-06-16 06:58 ./usr/lib/libgettextpo.so.0 -> libgettextpo.so.0.5.3
lrwxrwxrwx 0/0               0 2015-06-16 06:58 ./usr/lib/libgettextpo.so -> libgettextpo.so.0.5.3
lrwxrwxrwx 0/0               0 2015-06-16 06:57 ./usr/lib/libgettextlib.so -> libgettextlib-0.19.4.so
```
No libintl.so* whatsoever.
The strange thing is there are `/usr/lib/libintl.so*` files in my the binary bootstrapped musl masterdir in `/tmp/musl`:
```
lrwxrwxrwx 1 1000 1000    16 21. Mai 11:47 /tmp/musl/usr/lib/libintl.so -> libintl.so.8.1.3
lrwxrwxrwx 1 1000 1000    16 21. Mai 11:47 /tmp/musl/usr/lib/libintl.so.8 -> libintl.so.8.1.3
-rw-r--r-- 1 1000 1000 43512 21. Mai 11:48 /tmp/musl/usr/lib/libintl.so.8.1.3
```
but `XBPS_TARGET_MACHINE=x86_64-musl xbps-query -Ro /usr/lib*/libintl.so*` doesn't tell where these files come from. So no x86_64-musl package contains libintl.so.8.1.3 despite it being there in the masterdir? How can it be?

Am I doing something wrong?
IIRC I read somewhere that one has to create a symlink from the old libintl.so to have the new one built, i.e. some kind of cyclic dependency that needs to be handled...

**Comment by xtraeme** [comment]
```
[juan@/home/juan/projects/void-packages/masterdir-musl /]$ xbps-query -o /usr/lib/libintl.so\*
gettext-libs-0.19.4_9: /usr/lib/libintl.so.8.1.3 (regular file)
gettext-libs-0.19.4_9: /usr/lib/libintl.so.8 -> /usr/lib/libintl.so.8.1.3 (link)
gettext-libs-0.19.4_9: /usr/lib/libintl.so -> /usr/lib/libintl.so.8.1.3 (link)
[juan@/home/juan/projects/void-packages/masterdir-musl /]$
```

The configure option `--disable-nls` in gettext completely disables building the libintl library. Musl provides a POSIX gettext implementation, but some packages rely completely on the GNU implementation.

**Comment by pullmoll** [comment]
I see no `--disable-nls` in the template, though.

Also in [this build log](http://sprunge.us/hVKa) you can read `checking whether NLS is requested... yes` and `checking whether to use NLS... yes`.
