### ISSUE TITLE
lxappearance/obconf: segfault

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#1844]
<a href="http://git.io/vLsk5"> strace -eopen lxappearance</a>

<a href="http://git.io/vLsZb"> strace -eopen obconf</a>

**Comment by beefcurtains** [comment]
Unable to reproduce. Please create a new user/homedir and retry.

**Comment by cavalier911** [comment]
I added a new user,logged in,still segfaults. I have two X86_64 installs on 2 different computers and they both have this problem.
Linux voidlinux 4.0.5_2 #1 SMP PREEMPT Sun Jun 7 07:24:04 UTC 2015 x86_64 GNU/Linux

**Comment by Duncaen** [comment]
Standard question, is /usr/sbin a symlink?

**Comment by cavalier911** [comment]
Yes, /usr/sbin is a symlink to /usr/bin
[rj@voidlinux ~]$ ls -la /usr
total 152
drwxr-xr-x  11 root root  4096 Jun  7 20:35 .
drwxr-xr-x  22 root root  4096 Jun 12 09:47 ..
drwxr-xr-x   2 root root 49152 Jun 16 11:20 bin
drwxr-xr-x   2 root root  4096 Apr 26 12:17 certs
drwxr-xr-x  33 root root  4096 Apr 29 20:39 include
drwxr-xr-x  83 root root 61440 Jun 16 02:04 lib
drwxr-xr-x   2 root root  4096 Jun 12 09:47 lib32
lrwxrwxrwx   1 root root     3 Apr  8 04:08 lib64 -> lib
drwxr-xr-x  12 root root  4096 Jun 11 11:33 libexec
drwxr-xr-x   7 root root  4096 Apr  8 04:08 local
lrwxrwxrwx   1 root root     3 Jun  7 20:21 sbin -> bin
drwxr-xr-x 101 root root  4096 Jun 15 03:01 share
drwxr-xr-x   6 root root  4096 Jun  8 21:02 src

**Comment by ncmprhnsbl** [comment]
have same segfault with obconf
note standard lxappearance is unaffected   (guess only with lxappearance-obconf)
on laptop x86_64 install circa january2015 uptodate 4.0.5
usr/sbin is  not a symlink(everything in it is)
on more recent virtualbox x686 install /usr/sbin  is a symlink
and obconf segfaults there too

obconf-qt works np

at time of update when this started occurring,
of obconfs direct dependencies, these were updated:
libopenbox-3.6_1
gtk+-2.16
gdk-pixbuf
glibc

**Comment by cavalier911** [comment]
lxappearance segfaults on this iso: 
http://repo.voidlinux.eu/live/current/void-live-x86_64-20150615-lxde.iso

**Comment by cavalier911** [comment]
Solution is in this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1231693
Changes in openbox-3.6-1 require rebuilding obconf and lxappearance-obconf 
`./xbps-src pkg obconf`
`./xbps-src pkg lxappearance-obconf`
`xdowngrade hostdir/binpkgs/obconf-2.0.4_2.x86_64.xbps`
`xdowngrade hostdir/binpkgs/lxappearance-obconf-0.2.2_1.x86_64.xbps`
No more segfault :+1:
