### ISSUE TITLE
criu errors

### ISSUE THREAD

**Issue by sajeeshsidh** [voidlinux/void-packages#1851]
Hi,

Am using kernel 3.10 and up merged all patches except https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=e4a0d3e72 mentioned at http://criu.org/Upstream_kernel_commits.
Cross compiled protobuf, protobuf-c and criu for armv7l.

I also commented 
//      ret |= check_aio_remap();
//      ret |= check_fdinfo_lock();
from cr-check.c.
Above mentioned checks are mandatory?

Even with above changes, cr-check gives warn as : Warn  (cr-check.c:582): Dirty tracking is OFF. Memory snapshot will not work.
Now, criu dump gets stuck at prepare_tsock in parasite-syscall.c.

criu tool info.
Version: 1.6
GitID: v1.6-31-g46270d1

Any kind of help would be much appreciated.

thank you.
Sajeesh

**Comment by xtraeme** [comment]
There's no linux 3.10 available in the official void repositories...

**Comment by sajeeshsidh** [comment]
Kernel is not cloned from void repo... Its a custom kernel used for our project.

last few lines of logs are given below..

(00.268387) Collecting fds (pid: 1240)
(00.268441) ----------------------------------------
(00.268737) Found 15 file descriptors
(00.268803) ----------------------------------------
(00.268948) Dump private signals of 1240
(00.269066) Dump private signals of 1350
(00.269159) Dump private signals of 1469
(00.269232) Dump private signals of 1470
(00.269302) Dump shared signals of 1240
(00.269408) Parasite syscall_ip at 0xb1d01000
(00.269848) Putting parasite blob into 0xb6c99000->0xb26a3000
(00.270029) Dumping GP/FPU registers for 1240
(00.270128) Putting tsock into pid 1240

**Comment by xtraeme** [comment]
If it's a custom kernel it's up to you to make sure it works with criu, there's no issue here. Our linux3.18, linux3.19 and linux4.0 kernels work just fine with criu.
