### ISSUE TITLE
i3wm will not start (musl-x86_64)

### ISSUE THREAD

**Issue by MatthewAllan93** [voidlinux/void-packages#1882]
I installed the musl x86_64 iso base system after that i installed xorg-minimal, installed libEGL and a few other programs. Then installed i3wm and put "exec i3" in the .xinitrc file. Tried to start xorg with startx and then it will say the connect to x server lost.

However I have tried numerous window managers in my .xinitrc file and they start successfully; just not i3wm.

**Comment by oliver-cfc** [comment]
I have the same issue and I hope this isn't leading anyone down a rabbit hole but the first thing i3 does is look for ~/.i3 and if it's not there run i3-config-wizard.

If I run that at the command line, I should get a "not running X" (or whatever) error but instead I get:
# i3-config-wizard
i3-config-wizard: mkdir(~/.i3) failed: No such file or directory

so I wonder if that is causing the timeout somewhere.

**Comment by MatthewAllan93** [comment]
I already have my .i3 folder in home folder, but if i run i3-config-wizard. It says the same about no such file or directory

**Comment by xtraeme** [comment]
Works for me in a new installation... there's no issue after all.

![shot-2015-06-23_12-56-35](https://cloud.githubusercontent.com/assets/860073/8304572/785a86c2-19a7-11e5-943b-c05776a43f39.jpg)
