### ISSUE TITLE
chromium: disable hotwording?

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#1892]
chromium-43.0.2357.130_1 unconditionally loads a binary blob that possibly has access to the microphone.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=786909

**Comment by Gottox** [comment]
for some context:
* https://code.google.com/p/chromium/issues/detail?id=500922
* https://security-tracker.debian.org/tracker/TEMP-0786909-A21526

**Comment by Gottox** [comment]
and :+1: for disabling it

**Comment by chneukirchen** [comment]
Thanks to gottox for writing my bug report while I was at lunch. :)

**Comment by xtraeme** [comment]
:+1:

**Comment by beefcurtains** [comment]
:+1: for disabling NaCl, too. The blob was ineffective on Debian because they build chromium without it.

**Comment by dominikh** [comment]
:-1: to disabling NaCl.

**Comment by thypon** [comment]
If NaCl is enabled then another site could load another binary blob. What i have to say it's that this binary blob (if runs on NaCl) is sandboxed then it isn't an issue more then the tons of non free javascript you run in your browsers.

**Comment by dominikh** [comment]
Random sites cannot load NaCl unless you explicitly enable it via a flag. By default, only Chrome store entries can use NaCl. Also, it's sandboxed. I'm not sure to what degree they can use browser APIs without asking. hotwording apparently didn't have to ask for microphone access? But that might still be a presumptious exception that Google set for themselves.

**Comment by thypon** [comment]
Then (security wise) the only different thing with javascript in other sites is that this code uses mic features Opt-out and not Opt-in as other software.

@beefcurtains debian is unaffected because they release once every 2 years :-)

**Comment by thypon** [comment]
@dominikh NaCL apps are autoloaded as you see in http://www.naclbox.com/gallery/falcon-3

**Comment by chneukirchen** [comment]
Not enabled by default anymore.
