### ISSUE TITLE
mozjs17: broken library and script names

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1894]
Something with configuring mozjs17 version number goes wrong.
+ The dynamic library coming out of the build is `libmozjs-.so`
+ The configure script is just `js-configure`, not `js17-configure` as it is used in the -devel package

I have no real clue which part of the build system could be responsible for this bug.
It is possibly the new perl-5.22 (#1850), because in `configure` the MOZJS_MAJOR_VERSION is derived from MOZILLA_VERSION which in turn is returned by a perl script in the configure line `… $PERL $srcdir/config/milestone.pl -topsrcdir $srcdir`

**Comment by pullmoll** [comment]
It looks like some deprecated warning output of perl-5.22 is coming in the way of the expected output.
I ran the `milestone.pl` script manually and got this:
```shell
perl /tmp/glibc/builddir/mozjs17.0.0/js/src/config/milestone.pl -topsrcdir /tmp/glibc/builddir/mozjs17.0.0/js/src
defined(@array) is deprecated at /tmp/glibc/builddir/mozjs17.0.0/js/src/config/milestone.pl line 58.
	(Maybe you should just omit the defined()?)
17.0.4esrpre
```

I think the `configure` script of mozjs17 expected to see only the line `17.0.4esrpre`. Has this to be solved manually or is it a matter of redirecting perl's deprecated warnings or disabling them by default?

**Comment by xtraeme** [comment]
Fixed by @chneukirchen
