### ISSUE TITLE
Proposal/RFC: Make Haskell packages use Stackage

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#1910]
Right now we have several Haskell modules which we build as static
binaries, but using cabal-install which will use the most recent
suitable version of their dependencies, making the build nonreproducible
(and possibly breaking future builds due to regressions).

I'm packaging stack https://github.com/commercialhaskell/stack
and propose to use it instead for building these packages, tracking the Stackage
LTS releases, which are a versioned, tested list of Haskell modules
that work together.  Upon updating the templates, we can then fix a LTS
version for each package and rebuild it at any later point.

Currently Stackage uses GHC 7.8 for the LTS-2.x, but LTS-3.x should
use GHC 7.10 and will be out when GHC 7.10.2 is ready, which should be in a
few days.

We currently have just a few Haskell packages, so this move won't be
hard, but should greatly simplify future maintenance.

We'll need to make sure our GHC is compatible with the Stackage LTS
one, but it's generally a good idea not to package the lasest release
anyway as we have found out with GHC 7.10 since upstream packages need
quite some time to adopt.

Comments?

**Comment by xtraeme** [comment]
100% agreed :+1:

**Comment by Gottox** [comment]
:+1:

**Comment by chneukirchen** [comment]
Now implemented, hsb2hs and pandoc use it already.

Will extract a build-style given more experience with it.
