### ISSUE TITLE
qtcreator fails to run project

### ISSUE THREAD

**Issue by beefcurtains** [voidlinux/void-packages#1915]
Steps to reproduce:
1. Open qtcreator
2. Click on your project
3. Click the green "play" button

Expected results:
* project runs

Actual result:
* :-1: error: The Qt version is invalid: qmake does not exist or is not executable
* :-1: error: The qmake command "/usr/lib/qt/bin/qmake" was not found or is not executable.

qmake exists in ``/usr/bin``, not sure why it tries to find it in /usr/lib/qt/bin. Same result with ``qtcreator-full``.

**Comment by pullmoll** [comment]
Verified with my local setup after moving the old `$HOME/.config/QtProject` directory to a backup location, it works like expected, i.e. auto detects the install Qt5 and /usr/bin/qmake, detects compiler and debugger and creates a `Desktop Kit` entry which can be used to configure existing *.pro files.

I think you have an old configuration where you used Qt4, thus the `/usr/lib/qt/bin/qmake`. You can either clean up the `Tools -> Options -> Build & Run` tabs `Qt Versions` and perhaps `Compilers` and/or `Debuggers` and finally fix up your `Kits` settings.
Alternatively you can remove the `$HOME/.config/QtProject` directory and start QtCreator again.

**Comment by beefcurtains** [comment]
I've always used qt5 with the project I'm working on, but moving ``$HOME/.config/QtProject`` out of the way worked. Thanks a bunch!
