### ISSUE TITLE
Sane can't be crosscompiled.

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1921]
#1598 Similar issue for sane-udev-rules.

**Comment by xtraeme** [comment]
The issue is that in cross compilation we'd need to use the host utils to generate the udev rules file.... right now this subpkg is completely skipped and only built in the native case.

**Comment by thypon** [comment]
Could we solve this one in xbps-src? If the package is noarch and you are crosscompiling and the version_revision is == repository(version_revision) then try to download/register from repository instead of building.

**Comment by xtraeme** [comment]
This won't resolve the issue. The pkg must be changed to generate the udev rules file somehow in the cross compilation case.

**Comment by asergi** [comment]
Fixed https://github.com/voidlinux/void-packages/commit/f85368242c4ffe7f8a176a470508c64432b3b7e8.
