### ISSUE TITLE
RTorrent/libtorrent links are down

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1924]
https://github.com/rakshasa/rtorrent/issues/295

Maybe we should move to github releases.

**Comment by thypon** [comment]
@pullmoll it fixes also rtorrent?

**Comment by pullmoll** [comment]
Not yet, I'm working on it. The libtorrent is just the first step of two.

**Comment by tonkazoid** [comment]
just saw this topic here... https://github.com/voidlinux/void-packages/pull/2026

**Comment by pullmoll** [comment]
@tonkazoid #2024 fixes most cross build and *-musl issues, except for armv6hf-musl.
You should rebase your patch on this update and create a new pr.

**Comment by tonkazoid** [comment]
https://github.com/voidlinux/void-packages/pull/2027
i should drink more coffee... and look closer to open pullrequests and issues :p

**Comment by thypon** [comment]
Should be fixed right now
