### ISSUE TITLE
xbps-src: no need to remove auto deps with -t

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1930]
I wonder if when `$XBPS_TEMP_MASTERDIR` is set, is there any need to remove auto (cross) deps? As soon as `xbps-uchroot -O` returns the masterdir should be in a clean state again, or am I missing something?

**Comment by xtraeme** [comment]
It does already with -t, what's the issue are you seeing?

**Comment by pullmoll** [comment]
I think I saw messages like `<pkgname>: removing autodeps` after a package was built with the `-t` option.

These messages are generated by `common/xbps-src/shutils/pkgtarget.sh` function `remove_pkg_autodeps()` AFAICT. I wonder if it is necessary to xbps-remove packages if they will be gone anyway once the overlay is gone?

**Comment by xtraeme** [comment]
Removing autodeps is still necessary when dependencies of a pkg are being built, because it's still a child of the same xbps-uchroot process.

What you are seeing is just the expected behaviour.

**Comment by pullmoll** [comment]
Ok, I misunderstood that part then.
