### ISSUE TITLE
unexpected umasks

### ISSUE THREAD

**Issue by lemmi** [voidlinux/void-packages#1941]
at the moment i'm using bash with the system files nearly untouched. the following happens:
```bash
user@foo$ ssh user@bar  # or normal login
user@bar$ umask
0022
user@bar$ su
root@bar$ umask
0077
...
user@foo$ ssh root@bar
root@bar$ umask
0022
```
this is getting me in all sorts of trouble as some packages don't use fixed permissions to install files. rxvt-unicode-terminfo for example. also there was a pkgdb update somewhere in that timeframe and my user can't use xbps-query anymore.

this problem might even go beyond the scope of umask because /etc/profile isn't sourced again for root.

i'm not quite sure about the best approach to fix this, but i think the current state is broken. thoughts?

**Comment by xtraeme** [comment]
Use `su -` or `su -l` to execute a login shell.

**Comment by xtraeme** [comment]
Another way to fix this would be modifying `/etc/pam.d/su{.-l}` and override the `umask` setting there (to 022).

**Comment by lemmi** [comment]
i digged arount a bit and some points stood out:

1. `login.defs` has set `UMASK 077`
2. `/etc/profile` sets `umask 022`
3. `/etc/profile` is set as a configuration file, yet we have `/etc/profile.d/`. i'd like to remove it `conf_files` for the same reasons `/etc/bash/bashrc` is not in there.
4. bash sources either `/etc/profile` or `/etc/bash/bashrc`. i'd like to a a script to `/etc/profile.d/` to source the systemwide bashrc and also move the bash_completion.sh to the bashrc.d folder.

anyway. in the current configuration i have very different results depending on how i gain root access.

**Comment by chneukirchen** [comment]
IMO (1) should be reverted, home directories have been world-readable for a long time, also on other distros.

**Comment by beefcurtains** [comment]
Sure, but there's probably a reason why that was done. No need to revert anything on a whim.

**Comment by xtraeme** [comment]
The commit from above should set umask to 022 when executing `su` or `su -l`.

Let me know if that's enough for you.

**Comment by xtraeme** [comment]
Fixed a while ago... thanks.
