### ISSUE TITLE
xbps-src: create sources/by_sha256/<checksum>

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1952]
Whenever I see the next package downloading the same `gcc-4.9.3.tar.gz`, e.g. for the cross compilers, or other big files just because the package has a different name, I wonder if it would be easy enough to:

1. for every successfully downloaded distfile (after chksum verification) create a hard link from the file file to `.../sources/by_sha256/<checksum>`.
2. whenever a distfile is to be downloaded, first check for its sha256 hash in `.../sources/by_sha256/<checksum>` and, if it exists, create a hard link from there to the current packages' distfile.

This shouldn't be too difficult to integrate into `common/hooks/do-fetch/00-distfiles.sh`.
It would certainly save some space, time and bandwidth.

I touched the `00-distfiles.sh` for the proposed XBPS_DISTFILES_MIRROR stuff, so I may have to rebase that one afterwards.

If no one beats me to it, I may try to create a pr for this idea sometime soon.

**Comment by xtraeme** [comment]
Seems a good idea :+1: 

Please do!

**Comment by teh-jazzman** [comment]
How about prepending the distfile name to the sha256 string? There is the chance, however slim it may be, that two completely different files have the same checksum.

**Comment by beefcurtains** [comment]
Then git will have a problem, since commits could then be fraudulent. We'll know long before hand when it's time to switch to another algo.

**Comment by teh-jazzman** [comment]
git considers the chance of two commit hashes clashing so unlikely that as far as I know it simply ignores it. Since git works in a very distributed manner over many different states it has little other options that to trust the hashes.

In this case however a clash can be completely prevented with only very little additional effort. I think that at least is worth considering.

**Comment by beefcurtains** [comment]
What if the name differs but the file is the same? I think that's worth considering, too. Typically if you're paranoid about collisions, the solution is to also use the length the file.

**Comment by teh-jazzman** [comment]
A valid point. But I would assume that any one distfile would always come from the same source and thus have the same filename. If two packages were taking them from different locations for some reason it would not be too bad if they were kept twice. It would at least work reliably.

**Comment by Gottox** [comment]
sha256sums have 256 bit. Assuming that sha256 is a perfect hash function (not proven), this means the probability of a match between two random files is 115792089237316195423570985008687907853269984665640564039457584007913129639936 to 1.

Also read this: http://stackoverflow.com/a/4014407

It's even more likely to win lottery for a year in a row.

Please refrain from adding needless extra checks.

**Comment by pullmoll** [comment]
I believe an SHA256 collision is a tad less likely as Microsoft releasing Windows 10 under the GPL 3, the hell freezing, Barack Obama marrying Wladimir Putin and me staying sober for more than a year at the same time.

And even if this extremely improbable case would happen, the worst thing you would see was that one of the two packages which use a distfile with a colliding chksum would not build, because the files which should be there are not.

I'm more concerned with the question what happens if hard links don't work, because the underlying file system doesn't support them. The code should still make it possible to fetch the expected distfiles...

**Comment by beefcurtains** [comment]
Then use symlinks.

Also, when SHA256 is broken, you likely won't hear it from us first. Sorry to disappoint :joy_cat:

**Comment by Gottox** [comment]
We'll switch the cipher once it's not good enough for git, okay? :stuck_out_tongue:

**Comment by dominikh** [comment]
On the other hand, if two packages used the same distfile but with different names, I'd like to know about that.

**Comment by beefcurtains** [comment]
Build everything, find files with 2 or more links.

**Comment by chneukirchen** [comment]
1) Git uses SHA1.

2) Just symlink the name to the SHA256-file, what's the problem?

**Comment by Gottox** [comment]
SHA!? OMG THAT'S TOTALLY UNSAFE! :tongue:

**Comment by pullmoll** [comment]
@chneukirchen The advantage of hardlinks is they can't be dangling, as opposed to softlinks.
After implementing it, I don't see a problem using hardlinks, because if they wouldn't work the simply behaves as it did before.
