### ISSUE TITLE
cogl: sometimes fails in parallel build mode

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#1961]
I saw this only once or twice, but here's a case: [cogl-1.20.0_1 build fails](http://pastebin.com/x9UF7yUK)
This happened when `cogl` was built as a dependency for `cinnamon` using an `x86_64-musl` masterdir.

It fails expecting a temporary GIR scanner output in `/tmp/.cache/g-ir-scanner/.cache-version.tmp`, which was not (yet) there.

The second time round the build worked, perhaps for the now existing ccache contents. I built with `-t`, so it was no continue, but fresh build.

I wonder if to rectify this a `disable_parallel_build=yes` is advised, or if there's another way. It's no huge package, so serializing it won't hurt too much.

**Comment by xtraeme** [comment]
Unless you fix the issue in Makefile.am or automake, the only way to workaround it is `disable_parallel_build`.

**Comment by pullmoll** [comment]
The problem seems to be gone, perhaps due to libtool being updated to 2.4.6 or cogl being updated to 1.22.0. I built it 7 times without failure.
