### ISSUE TITLE
Package request: QupZilla

### ISSUE THREAD

**Issue by flatr0ze** [voidlinux/void-packages#1968]
QupZilla

http://www.qupzilla.com QupZilla is a new and very fast lightweight Qt WebKit Browser.

More info at: http://qt-apps.org/content/show.php/QupZilla?content=145693

Would be nice to have an .xbps for it since it's quite long/tricky to build it yourself.

Thank you...

**Comment by flatr0ze** [comment]
That was super-fast!
Thank you folks so much!

**Comment by pullmoll** [comment]
Not yet done, though, because it fails to build with the new Qt-5.5.0
I'll try to fix the issue now.

**Comment by pullmoll** [comment]
Fixed and built for x86_64, x86_64-musl and i686. Enjoy.
