### ISSUE TITLE
Package request: Kadu

### ISSUE THREAD

**Issue by flatr0ze** [voidlinux/void-packages#1969]
http://www.kadu.im Kadu Instant Messenger

We don't have a pre-packaged Qt-based IM on Void Linux which would support OTR out of the box.
Kadu is very nice, I would like to recommend it as an alternative to pidgin.

Thanks.

**Comment by pullmoll** [comment]
I tried and made a pkg for one dependency, injeqt-devel. It seems ok so far.

The next dependecy which is not yet in Void is `libgadu` and this one doesn't work yet, because the downloads for `libgadu-1.2.1.tar.gz` don't work at all. I can download some of the links via my web browser, but not with xbps-src. It seems to be an issue with the amazonaws cloud where the files are really stored. It may be temporary, however it is a show stopper for now.

**Comment by pullmoll** [comment]
Ok, solved that problem. It was me having a wrong version=1.21.1 in the template where it should have bee 1.12.1
Let's see what else kadu needs to compile.

**Comment by pullmoll** [comment]
Please let us know if this package works for you and if `kadu-devel` doesn't contain anything that is required for normal use.

Myself I don't use instant messaging and thus did not test more than the bare start up is working.

**Comment by flatr0ze** [comment]
Thank you very much for taking time to build this package for Void, @pullmoll 
I'm running the musl x86_64 version; the building process went fine, but when I launched it, Kadu has given me 7 errors in separate popups

```
Cannot load sql_history plugin library: Cannot load library /usr/lib/kadu/plugins/libsql_history.so: (Error loading shared library libhistory.so: no such file or directory (needed by /usr/lib/kadu/plugins/libsql_history.so)
```

And a similar error message 6 more times (for libsms, libqt4_docking, libphonon_sound, etc).
The files that Kadu reports as missing actually lay within /usr/lib/kadu/plugins, right next to the files that require them, as mentioned in the popup error message. I suppose it has something to do with the PATH variable. But I'm not that good with complex programs, so won't try to guess further.

As for the functionality, I managed to add my account, connect to the server. The OTR functionality seems to be present, but I was unable to see any messages in the chat window that I was sending. 

Still better than pidgin.

**Comment by pullmoll** [comment]
You could have tried the release version, i.e. just do `sudo xbps-install -S kadu`, if you use `sudo`.
I didn't see those popup messages when trying the released kadu package.
When installing I see this:
```
[*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...
x86_64-repodata: 825KB [avg rate: 11GB/s]
[*] Updating `http://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/debug/x86_64-repodata' ...
x86_64-repodata: 349KB [avg rate: 28MB/s]

Name         Action    Version           New version            Download size
kadu-data    install   -                 2.1_1                  3213KB 
injeqt       install   -                 1.0.1_1                62KB 
libotr       install   -                 4.1.0_3                39KB 
libgadu      install   -                 1.12.1_3               86KB 
libmpdclient install   -                 2.10_1                 32KB 
phonon-qt5   install   -                 4.8.3_3                156KB 
kadu         install   -                 2.1_1                  3109KB 

Size to download:             6701KB
Size required on disk:          37MB
Free space on disk:             57GB

Do you want to continue? [Y/n] 
```
After installing I removed the previous configuration with `rm -rf ~/.kadu` and when I run kadu it presents the `Kadu Wizard`, all without warnings or errors so far.

**Comment by pullmoll** [comment]
I will try in qemu with an x86_64-musl installation to see if I can reproduce your experience.

**Comment by beefcurtains** [comment]
Musl has no need for ldconfig

**Comment by pullmoll** [comment]
It then looks like the Qt5 way of adding search paths for libraries (plugins) is not working right with musl libc. This has to be a general problem and needs fixing in Qt5, not in this package.

**Comment by flatr0ze** [comment]
You're right @pullmoll, it's the thing with musl. I remember having this problem with it not being able to locate shared objects.

After reinstalling kadu and the related packages I still get the error.
But your wrapper idea worked just fine, now I'm able to use it.
Thank you so very much!
