### ISSUE TITLE
linux*: signing of modules

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#1981]
We currently build with CONFIG_CHECK_SIGNATURE=y and CONFIG_MODULE_SIG_ALL=y
which seems to result in the first module load failing with
```
[    1.206364] dm_mod: module verification failed: signature and/or required key missing - tainting kernel
```
The signatures seem to be appended to the .ko files(?), this probably our stripping kills them...

Also note that we throw the key away, so we cannot produce signed 3rd-party modules.

IMO this signing stuff isn't worth it. We verify integrity of our kernel by means of XBPS, and signing is more interesting for shipping just a few modules and prohibiting people to compile their own---we build almost everything as modules.

**Comment by thypon** [comment]
:+1: there is no added security given loading modules is a privileged operation + it breaks dkms scheme.

On the other hand secureboot kernel/bootloader signing could remove installation barriers and increase boot security.

**Comment by pullmoll** [comment]
:+1: for disabling broken configuration options.

**Comment by chneukirchen** [comment]
`# CONFIG_MODULE_SIG is not set` for some time now.
