### ISSUE TITLE
Package request: parole

### ISSUE THREAD

**Issue by xocn** [voidlinux/void-packages#1986]
# Parole Media Player
> Parole is a modern simple media player based on the GStreamer framework and written to fit well in the Xfce desktop. It is designed with simplicity, speed and resource usage in mind.

More information available at http://docs.xfce.org/apps/parole/start
Packages (tar.bz2) in http://archive.xfce.org/src/apps/parole/
Requirements in http://docs.xfce.org/apps/parole/introduction#requirements

**Comment by beefcurtains** [comment]
Implicit request for libxfce4ui built against GTK+3
