### ISSUE TITLE
Package request: hddtemp

### ISSUE THREAD

**Issue by 7185** [voidlinux/void-packages#1990]
hddtemp
======
hddtemp is a small utility that gives you the temperature of your hard drive by reading S.M.A.R.T. informations (for drives that support this feature).

Website: https://savannah.nongnu.org/projects/hddtemp/

**Comment by asergi** [comment]
https://github.com/voidlinux/void-packages/commit/57c37a9b0287ef715a312f73baf4d8c37d7513f3
