### ISSUE TITLE
tesseract-ocr moved to GitHub

### ISSUE THREAD

**Issue by dominikh** [voidlinux/void-packages#2010]
Our tesseract-ocr package builds from code.google.com. However, the project moved to GitHub a while ago, and our 3.02.02 version is over 2 years old, upstream has 3.04.00.

The new home is https://github.com/tesseract-ocr.

/cc @pullmoll

**Comment by pullmoll** [comment]
I'm working on it.

**Comment by pullmoll** [comment]
Done. Please merge after peer review - I'm away doing paid work :)

**Comment by dominikh** [comment]
Thanks.
