### ISSUE TITLE
travis: run xlint last

### ISSUE THREAD

**Issue by dominikh** [voidlinux/void-packages#2017]
1. xlint is great, but it's not perfect. It has false positives. It's a tool intended for human consumption, not for machines to make decisions
2. Even when there's xlint errors, people care more about actual build errors. I don't want to work around xlint just to know if the package cross-compiles correctly.

Thus, xlint should run last, not first. It should still fail the build, so that people don't ignore it, but only after packages were actually built.

/cc @Gottox

**Comment by pullmoll** [comment]
:+1:
