### ISSUE TITLE
texlive{2014,2015}: package layaureo not found

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#2034]
http://ctan.org/pkg/layaureo

**Comment by chneukirchen** [comment]
wfm:
```
juno ~% tlmgr search --global layaureo
tlmgr: package repository http://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet
layaureo - A package to improve the A4 page layout.
juno ~% sudo tlmgr install layaureo
[sudo] Password: 
tlmgr: package repository http://mirrors.concertpass.com/tex-archive/systems/texlive/tlnet
[1/1, ??:??/??:??] install: layaureo [135k]
tlmgr: package log updated: /opt/texlive/2015/texmf-var/web2c/tlmgr.log
running mktexlsr ...
done running mktexlsr.
running mtxrun --generate ...
done running mtxrun --generate.
```

**Comment by thypon** [comment]
Shouldn't be integrated in the main package?

**Comment by chneukirchen** [comment]
no?  We only package the installer.

**Comment by thypon** [comment]
k, closing this one. I'd like a texlive full package.

**Comment by chneukirchen** [comment]
Creating a 3.3GB package which will be outdated daily doesn't sound reasonable. :)

**Comment by svenper** [comment]
Only a small part of that actually is binaries. The majority is docs, localization and fonts. E.g. in the arch linux repos texlive-bin is under 50MB. The Void solution is arguably more elegant, but doesn't work for musl, unfortunately. At least the core binaries could be split to another package?
