### ISSUE TITLE
clang++ cannot link with exceptions enabled

### ISSUE THREAD

**Issue by vtoc** [voidlinux/void-packages#2042]
clang++ can not link any binaries that could throw exceptions anymore. For example:

```c++
#include <iostream>
#include <string>

void hello(std::string s)
{
    std::cout << "Hello " << s << std::endl;
}

int main(void)
{
    hello("world");
}
```

```
$ clang++ -o foo foo.cc && ./foo                
/usr/bin/ld: /tmp/foo-a6b68d.o: undefined reference to symbol '_Unwind_Resume@@GCC_3.0'
/lib64/libgcc_s.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Disabling exceptions "works":

```

$ clang++ -fno-exceptions -o foo foo.cc && ./foo
Hello world
```

Verbose
```
$ clang++ -v -o foo foo.cc
clang version 3.6.2 (tags/RELEASE_362/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9
Found candidate GCC installation: /usr/lib64/gcc/x86_64-unknown-linux-gnu/4.9.3
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/clang" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -main-file-name foo.cc -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -target-linker-version 2.25 -v -dwarf-column-info -resource-dir /usr/bin/../lib/clang/3.6.2 -internal-isystem /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9 -internal-isystem /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9/x86_64-unknown-linux-gnu -internal-isystem /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9/backward -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/clang/3.6.2/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/jw/dev -ferror-limit 19 -fmessage-length 108 -mstackrealign -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/foo-0b4e7f.o -x c++ foo.cc
clang -cc1 version 3.6.2 based upon LLVM 3.6.2 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9
 /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9/x86_64-unknown-linux-gnu
 /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../include/c++/4.9/backward
 /usr/local/include
 /usr/bin/../lib/clang/3.6.2/include
 /usr/include
End of search list.
 "/usr/bin/ld" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o foo /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../lib64/crt1.o /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../lib64/crti.o /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/crtbegin.o -L/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9 -L/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../lib64 -L/usr/bin/../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../.. -L/usr/bin/../lib -L/lib -L/usr/lib /tmp/foo-0b4e7f.o -lstdc++ -lm /usr/bin/../lib/clang/3.6.2/lib/linux/libclang_rt.builtins-x86_64.a -lc /usr/bin/../lib/clang/3.6.2/lib/linux/libclang_rt.builtins-x86_64.a /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/crtend.o /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9/../../../../lib64/crtn.o
/usr/bin/ld: /tmp/foo-0b4e7f.o: undefined reference to symbol '_Unwind_Resume@@GCC_3.0'
/lib64/libgcc_s.so.1: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by chneukirchen** [comment]
This seems to be a problem in calling the linker, if you link/assemble with gcc, it works:

```
juno /tmp% clang++ -c z.cc
juno /tmp% gcc -o z z.o -lstdc++ 
juno /tmp% ./z
Hello world
```

`clang++ z.cc -lgcc_s` works too...

**Comment by chneukirchen** [comment]
... this is due to `llvm/files/patches/cfe/cfe-008-remove-lgcc-when-using-compiler-rt.patch` from @jprjr.

Please stop breaking non-musl archs by adding musl-patches unconditionally.

**Comment by chneukirchen** [comment]
I don't see why we need that patch even on musl, because the same thing doesn't work, and with `-lgcc_s`, it does...

**Comment by thypon** [comment]
Maybe we could generalize a little adding a patches/musl subdirectory to avoid breaking good old stable glibc packages.

**Comment by chneukirchen** [comment]
Yes, perhaps we could also have per-arch patch dirs... @xtraeme ?

**Comment by Gottox** [comment]
How about solving that through `#ifdef`s? I believe, that it's easier to get such patches upstream.

**Comment by chneukirchen** [comment]
AFAIU this patch is completely redundant.

**Comment by chneukirchen** [comment]
Cross-building clang is currently broken for me, with or without this patch due to

```
llvm[1]: Compiling libllvm.cpp for Release build (PIC)
llvm[1]: Linking Release Shared Library libLLVM-3.6.so
/builddir/llvm-3.6.2.src/build/Release/lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.o): In function `llvm::RTDyldMemoryManager::registerEHFrames(unsigned char*, unsigned long, unsigned long)':
/builddir/llvm-3.6.2.src/lib/ExecutionEngine/RuntimeDyld/RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager16registerEHFramesEPhmm+0x4): undefined reference to `__register_frame'
/builddir/llvm-3.6.2.src/build/Release/lib/libLLVMRuntimeDyld.a(RTDyldMemoryManager.o): In function `llvm::RTDyldMemoryManager::deregisterEHFrames(unsigned char*, unsigned long, unsigned long)':
/builddir/llvm-3.6.2.src/lib/ExecutionEngine/RuntimeDyld/RTDyldMemoryManager.cpp:(.text._ZN4llvm19RTDyldMemoryManager18deregisterEHFramesEPhmm+0x4): undefined reference to `__deregister_frame'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/builddir/llvm-3.6.2.src/Makefile.rules:1199: recipe for target '/builddir/llvm-3.6.2.src/build/Release/lib/libLLVM-3.6.so' failed
```

**Comment by xtraeme** [comment]
I'm against adding per-arch patches, they will lead to unmergeable patches for upstream and will cause confusion.

pkgsrc also discussed this multiple times for >10 years now and the conclusion is that conditionalizing patches based on arch or another characteristic is not the way to go.

If any of those llvm patches is causing the link issue it should be really removed.

**Comment by jprjr** [comment]
I've got a an updated package I've been working on that should fix this problem. I think I'll be finished with it in the next few days 

On July 29, 2015 1:47:20 AM CDT, Juan RP <notifications@github.com> wrote:
>I'm against adding per-arch patches, they will lead to unmergeable
>patches for upstream and will cause confusion.
>
>pkgsrc also discussed this multiple times for >10 years now and the
>conclusion is that conditionalizing patches based on arch or another
>characteristic is not the way to go.
>
>If any of those llvm patches is causing the link issue it should be
>really removed.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/voidlinux/void-packages/issues/2042#issuecomment-125859601

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chneukirchen** [comment]
I will remove `patches/cfe/cfe-008-remove-lgcc-when-using-compiler-rt.patch` once I've verified that this still works on glibc and musl.

**Comment by chneukirchen** [comment]
Ok, I think the actual culprit is `cfe-002-default-runtime-compiler-rt.patch`, because when I use `--rtlib=libgcc`, everything works fine with both glibc and musl.

@jprjr what was the reason for this patch?

**Comment by jprjr** [comment]
The long-term plan was to move to an llvm/compiler-rt/libc++/c++abi/etc stack that's independent of libgcc. It turns out building all of that is pretty complicated. I vote to remove that offending patch. At some point I'll figure out how to package it all and do a full, complete llvm/libc++/etc package sometime in the future 

On August 11, 2015 6:38:36 AM CDT, Christian Neukirchen <notifications@github.com> wrote:
>Ok, I think the actual culprit is
>`cfe-002-default-runtime-compiler-rt.patch`, because when I use
>`--rtlib=libgcc`, everything works fine with both glibc and musl.
>
>@jprjr what was the reason for this patch?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/voidlinux/void-packages/issues/2042#issuecomment-129846880

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chneukirchen** [comment]
Ok, my plan is so far:

1) remove 002, so libgcc will be used by default, which should work on glibc+musl.
2) change 008 to always use `-lgcc_eh`, so compiler-rt should work too, then.

By keeping to upstream defaults, I hope this breaks less stuff in total, while people experimenting with compiler-rt can still use it, even with `-static`.

We currently cannot build using libgcc* without having an alternative to libstdc++ (this would be a worthwhile project however).

**Comment by jprjr** [comment]
+1

On August 11, 2015 7:03:36 AM CDT, Christian Neukirchen <notifications@github.com> wrote:
>Ok, my plan is so far:
>
>1) remove 002, so libgcc will be used by default, which should work on
>glibc+musl.
>2) change 008 to always use `-lgcc_eh`, so compiler-rt should work too,
>then.
>
>By keeping to upstream defaults, I hope this breaks less stuff in
>total, while people experimenting with compiler-rt can still use it,
>even with `-static`.
>
>We currently cannot build using libgcc* without having an alternative
>to libstdc++ (this would be a worthwhile project however).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/voidlinux/void-packages/issues/2042#issuecomment-129851079

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
