### ISSUE TITLE
kdepimlibs build error [x86_64, musl]

### ISSUE THREAD

**Issue by wyrex** [voidlinux/void-packages#2048]
When I run "./xbps-src -E pkg kde" after some time build fails during kdepimlibs gpgme++ compilation . The error is:
```
error: #error GPGME was compiled with 
_FILE_OFFSET_BITS = 64, please see the section "Largefile support (LFS)" in 
the GPGME manual.
```
_FILE_OFFSET_BITS=64 ./xbps-src -E pkg kde doesn't make difference, also #define _FILE_OFFSET_BITS 64 in source code doesn't make difference.

**Comment by xtraeme** [comment]
Fixed with #2115
