### ISSUE TITLE
Conky Has Lua, But No Bindings For Lua

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#2061]
Cairo and imlib2 bindings for Lua are missing from the Conky package, despite that lua-devel is listed as a dependency in the template.

They can be compiled into Conky with the following options:
--enable-imlib2 --enable-lua-cairo --enable-lua-imlib2

**Comment by antonio-malcolm** [comment]
OK, I think I have solved this, by working from source.

**Warning Order: it is non-trivial!**

I will update after some testing, and confirm it's working, and provide an explanation and dependency diagram.

**Comment by antonio-malcolm** [comment]
**Debrief**  

OK, it works!  
The dependency chain is a bit complicated, and I had to edit configs in the source code for each, and for Conky, to build and run it successfully.

Please note, Conky is now hosted at Github (and appears to have been for a few years, at least), and the documentation is rather sparse- what little of it is current, that is (since they moved to cmake); _README.cmake_ is the only useful bit of documentation I found, the rest is irrelevant. _README.md_ is incomplete fluff- most of the links go nowhere, and the wiki is also outdated. tolua++ is, itself, a bit dated, hence why this wasn't trivial- this required some digging around. It should be much easier for someone to simply copy the resulting and brief instructions, here. 

(You're welcome.)

Conky requires two packages, which aren't currently available via xbps, in order to build its lua bindings for Cairo and  imlib2, and each of the two requires a different version of the lua development package.

Here's a breakdown of the requirements, with side notes (from higher to lower level):

Conky (requires tolua++, tolua, MUST use lua51-devel to build the lua-bindings

tolua++ (aka, toluapp, hasn't seen a decent update since 2010 (there were some minor changes made in 2013), requires tolua and lua51-devel)

tolua (requires lua-devel)
lua-devel (available via xbps)
lua51-devel (available via xbps)
 
And, here's a bit of a diagram:
```
          conky  
        /   |   \  
 tolua++ ---|---> tolua                
    |       |       |  
    |       |   lua-devel  
    |       |                 
   lua51-devel  
```
To make this work, I edited two config files (one each, within the tolua++ and conky git clones).
(tolua detects, and configures itself for, the most recent lua package available.)

In the tolua++ (toluapp) project source, I edited _config_linux.py_, entire contents, like so:  

```
## This is the linux configuration file
# use 'scons -h' to see the list of command line options available

# Compiler flags (based on Debian's installation of lua)
CCFLAGS = ['-I/usr/include/lua5.1', '-ansi', '-Wall', '-fPIC']

# this is the default directory for installation. Files will be installed on
# <prefix>/bin, <prefix>/lib and <prefix>/include when you run 'scons install'
#
# You can also specify this directory on the command line with the 'prefix'
# option
#
# You can see more 'generic' options for POSIX systems on config_posix.py

prefix = '/usr/local'
LIBS = ['lua5.1', 'dl', 'm']

```

In the conky project source, I edited _cmake/ConkyPlatformChecks.cmake_, line 254, like so:

```
pkg_search_module(LUA REQUIRED lua5.1 lua-5.1)
```  

Configuration options for conky can be viewed and modified via ccmake.
I enabled the following options, in addition to what was already enabled:  

```
BUILD_IMLIB2
BUILD_LUA_CAIRO                                                                                                                                                                                                
BUILD_LUA_IMLIB2                                                                                                                                                                                             
BUILD_LUA_RSVG
BUILD_XDBE
BUILD_XSHAPE
```

On more thing to note, as of the most recent conky, the config file uses lua syntax.
That was the only additional catch I encountered.

Conky source is here: https://github.com/brndnmtthws/conky
tolua source is here: https://github.com/LuaDist/tolua
tolua++ source is here: https://github.com/LuaDist/toluapp

**Comment by xtraeme** [comment]
Care to submit a proper pull request with those changes? thanks.

**Comment by antonio-malcolm** [comment]
Fixed with latest update.
