### ISSUE TITLE
libressl 2.2.1 fallout

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#2062]
Missing packages still requiring libcrypto.so.32:

- [x] newsbeuter-r2.9_3: FTBFS -lbeuter @logenkain
- [x] opensc-0.15.0_1: SHA256 mismatch for 'opensc-0.15.0.tar.gz:' 399b2107a69e3f67e4e76dc2dbd951dbced8e534b1e0f919e176aea9b85970d7 @xtraeme 
- [x] rdis-git-20150224_2: still uses git clone @xtraeme 
- [x] tcpdump-4.7.4_2: fetching hangs here @xtraeme 
- [x] vboot-utils-44.7077_3: ERROR: vboot-utils-44.7077_3: cannot find release-R44-7077.B.tar.gz @Gottox

**Comment by xtraeme** [comment]
100% completed, thanks!
