### ISSUE TITLE
Package Request: fcitx-mozc (request to re-open)

### ISSUE THREAD

**Issue by scottro11** [voidlinux/void-packages#2080]
http://download.fcitx-im.org/fcitx-mozc/

This is a Japanese input module for fcitx, which is already a package.  

Thank you for your consideration

**Comment by scottro11** [comment]
This can be closed, I was able to get fcitx-anthy to build on VoidLinux.

**Comment by scottro11** [comment]
Although, as mentioned in 2015, I was able to get fcitx-anthy to build (see http://srobb.net/jpninpt.html#VoidLinux), upstream anthy development seems to have ceased. The fcitx-mozc package seems to be preferred by most Japanese users.

**Comment by mvf** [comment]
@scottro11 Thank you for reporting this. `fcitx-mozc` is now available. ARM users will have to build natively until `fcitx` can be cross-compiled. I can see why people seem to prefer it over `ibus` though, ended up switching myself. :smile:

**Comment by maxice8** [comment]
can be closed ? @lemmi

**Comment by scottro11** [comment]
Yes, I thought I had commented here, I must have done it on forums.  Thank you, the package is there, and works perfectly.

**Comment by maxice8** [comment]
please close then
