### ISSUE TITLE
Package Request: geany-plugins

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#2108]
http://plugins.geany.org/
https://github.com/geany/geany-plugins/releases
I'm especially interested in [GeanyLatex-Plugin](http://frank.uvena.de/en/Geany/geanylatex/) & [GeanyMarkdown](http://plugins.geany.org/markdown.html)

The question is, whether it is wise to create one "geany-plugins" package with all of them loaded in or individual ones.

**Comment by beefcurtains** [comment]
Depends on how often they're updated. If the updates are in sync, you might as well package them with one template. Otherwise, one template per distfile is easy and efficient.

**Comment by JayVii** [comment]
There seems to be one release for every geany-update (roughly one per year, except for 2011). So one template is a valid option.

**Comment by beefcurtains** [comment]
Doing multiple configure/build/install passes in a single template is still a pita, though.

**Comment by JayVii** [comment]
Their [README](https://github.com/geany/geany-plugins/blob/master/README) hints a way to compile all plugins at once.
If all dependencies are satisfied, it should build all of them, without too many **option** passes.
But i cannot say for sure, now. I'll have a look at it, as soon time allows.
The reason for me opening this request, in the first place is lack of time. But i'll get to it myself ASAP, if nobody packaged it in the meantime.
