### ISSUE TITLE
chromium: enable widevine support

### ISSUE THREAD

**Issue by LockeAnarchist** [voidlinux/void-packages#2111]
widevide is the plugin used for chrome to work with sites like netflix and others HTML5-DRM enabled sites.

This is the patch used in Arch Linux that allows Widevine to be loaded in to Chromium:

https://projects.archlinux.org/svntogit/packages.git/plain/trunk/chromium-widevine.patch?h=packages/chromium

**Comment by Gottox** [comment]
I'm not sure about that one. It should be a build option at least.

**Comment by LockeAnarchist** [comment]
This is the only way to watch Netflix on Linux currently, yesterday I tried everything and in the end was forced to use Chrome (copied chrome folder to ~). :-P

**Comment by Gottox** [comment]
Ah, after reading the packages AND the PKGBUILD I understand, that it does not add support DRM support in Chromium but at least enables people to add DRM if they *really* want.

I'm fine with that, but only @xtraeme can decide on that as he's the maintainer.

**Comment by LockeAnarchist** [comment]
Yes, widevine is the plugin that enables DRM support, this patch enables widevine plugin support.

**Comment by xtraeme** [comment]
No objection.
