### ISSUE TITLE
Package Request: apulse

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#2118]
https://github.com/i-rinat/apulse
PulseAudio emulation for ALSA.
> Project is in stale state since its proclamation. The main objective, working Skype test call, is reached. I don't have any plans for further development.

However, there seems to be someone, maintaining and updating an [Ubuntu-PPA](https://launchpad.net/~kirillshkrogalev/+archive/ubuntu/apulse). Maybe his Source ([Currently 0.1.6](https://launchpad.net/~kirillshkrogalev/+archive/ubuntu/apulse/+files/apulse_0.1.6.orig.tar.gz)) can be of use.

Edit:
Although the Readme-file on i-rinat's github says it is in stale state, he seems to be more or less active on it -> [apulse-commits](https://github.com/i-rinat/apulse/commits/master)

**Comment by thypon** [comment]
```
$ xbps-query -Rs skype
[*] skype-32bit-4.3.0.37_3          P2P software for high-quality voice communication (32bit)
[-] libskypetab-ng-32bit-20140614_1 A program that adds tabs to Skype for Linux - shared LD_PRELOAD library (32bit)
[-] skype_oss_wrapper-32bit-0.1_1   Fake libpulse.so library that mimics pulseaudio behavior for skype (32bit)
[-] skypetab-ng-32bit-20140614_1    A program that adds tabs to Skype for Linux (32bit)
```

Apulse description:
```
The main objective, working Skype test call, is reached. I don't have any plans for further development.
```

We alredy have skype_oss_wrapper for this reason but feel free to package it if you really need.

**Comment by JayVii** [comment]
@thypon this doesn't only work with skype. It can be used for literally any app that may require pulseaudio :) it is quite versatile.
