### ISSUE TITLE
qtox or filteraudio-git or xbps are broken

### ISSUE THREAD

**Issue by dominikh** [voidlinux/void-packages#2122]
Trying to install qtox results in

```
qtox-1.1_4: broken, unresolvable shlib `libfilteraudio.so'
Transaction aborted due to unresolved shlibs.
```

despite `libfilteraudio.so` existing in the `filteraudio-git` package, as well as being recorded in `common/shlibs`. 

Now, `common/shlibs` includes `libfilteraudio.so` instead of the correct `libfilteraudio.so.0`. Also, `libfilteraudio.so` is in the `filteraudio-git` package, not the `filteraudio-git-devel` package. That'd be at least two mistakes in the `filteraudio-git` package. 

The errors in the `filteraudio-git` package aside, there might also be a bug in either xbps or xbps-src, as `filteraudio-git` is not providing any shlibs:

```
dominikh-pc ~ $ xbps-query -R 'filteraudio-git>=20150416_1'
architecture: x86_64
build-date: 2015-07-27 11:20 UTC
filename-sha256: 631c4f540f331bcda8d66c5010e782345e6116c8e8c97057562660537ad9bf70
filename-size: 85KB
homepage: https://tox.im
installed_size: 185KB
license: 3-clause-BSD
maintainer: Stefan Mühlinghaus <jazzman@alphabreed.com>
pkgver: filteraudio-git-20150416_2
repository: http://repo.voidlinux.eu/current
shlib-requires:
	libc.so.6
short_desc: Lightweight audio filtering library for TOX
source-revisions: filteraudio-git:d7de109
```

xbps-src should handle invalid entries in `common/shlibs` in some way. And so should xbps.

/cc @xtraeme to figure out if xbps should still be able to resolve this shlib (and if so, if a separate issue for xbps should be filed), also to comment on xbps-src's behaviour.
/cc @thypon because he changed the `common/shlibs` entry in 0898aafbc63a6e515fb34be8534746fdae95aefe and is the last person to update both `qtox` and `filteraudio-git`
/cc @teh-jazzman because he's the maintainer of the packages.

P.S. The complete output of `xbps-install -dn qtox`: http://sprunge.us/ZShh

**Comment by xtraeme** [comment]
xbps works as expected, why?

1- filteraudio must set `shlib_provides=libfilteraudio.so` because unversioned sonames are ignored by xbps-src
2- qtox effectively needs `libfilteraudio.so`.
