### ISSUE TITLE
ladspa-sdk - Error in create template

### ISSUE THREAD

**Issue by diogoleal** [voidlinux/void-packages#2123]
I'm creating a template for mlt whose dependence on the ladspa-sdk, but to compile it for arch x86_64-musl, this occurring the error below.

```./xbps-src -a x86_64-musl pkg ladspa-sdk ```

```
=> ladspa-sdk-1.13_4: running pre-configure hook: 02-script-wrapper ...
=> ladspa-sdk-1.13_4: running pre-build hook: 02-script-wrapper ...
=> ladspa-sdk-1.13_4: running do_build ...
make: Entering directory '/builddir/ladspa_sdk/src'
../bin/listplugins
make: ../bin/listplugins: Command not found
makefile:70: recipe for target '/tmp/test.wav' failed
make: *** [/tmp/test.wav] Error 127
make: Leaving directory '/builddir/ladspa_sdk/src'
```

**OBS**. I could not reproduce this error for x86_64

**Comment by pullmoll** [comment]
Instead of cross-compiling for x86_64-musl, you can use a separate masterdir for x86_64-musl builds:
```
./xbps-src -m musl-masterdir zap
./xbps-src -m musl-masterdir binary-bootstrap x86_64-musl
./xbps-src -m musl-masterdir pkg ladspa-sdk
```
I can build ladspa-sdk with x64_64-musl this way, even though its a noarc package.

**Comment by diogoleal** [comment]
@pullmoll Thanks!
