### ISSUE TITLE
Package Request: libiw

### ISSUE THREAD

**Issue by userx-bw** [voidlinux/void-packages#2127]
iw developer package for i3status support - to use in i3 wm wifi access needed use of devel 

thanks

PS I don't think this an be deleted. as I found out that it is included in you network-tools-devel 

Cancel this order / request
sorry

**Comment by beefcurtains** [comment]
``libiw`` should be split out of ``wireless_tools``, but ``i3status`` should already work.

**Comment by xtraeme** [comment]
```
[juan@leysa void-packages]$ xbps-query -Rs libiw -p shlib-requires|grep i3
i3status-2.9_2: libiw.so.29 (http://repo.voidlinux.eu/current)
```

`wireless_tools{,-devel}` are already there and `i3status` is linked to `libiw`.

There's no issue.
