### ISSUE TITLE
Using SPDX titles for licenses.

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#2154]
https://spdx.org/licenses/

**Comment by beefcurtains** [comment]
How does ``Public Domain`` fit into this?

**Comment by chneukirchen** [comment]
Public Domain is not a license. ;P

**Comment by beefcurtains** [comment]
True. I'd recommend substituting pd with ``CC0-1.0`` because pd isn't as widely recognized internationally. That is, if this idea has any chance of being implemented :grinning:

**Comment by Gottox** [comment]
superseded by #12219
