### ISSUE TITLE
qmake: could not exec '/usr/lib/qt/bin/qmake': No such file or directory

### ISSUE THREAD

**Issue by beefcurtains** [voidlinux/void-packages#2156]
This always worked just fine, but now it doesn't. What happened?

**Comment by pullmoll** [comment]
Works for me.
```
$/usr/lib/qt/qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib
```
Do you have both Qt and Qt5 installed?
Then there is the `qtchooser` package and `/usr/bin/qmake` symlinks to `qtchooser`.

**Comment by beefcurtains** [comment]
No, only qt5 and a bunch of programs that use it.

**Comment by pullmoll** [comment]
Then it's `/usr/lib/qt5/bin/qmake` :hammer:

**Comment by beefcurtains** [comment]
It works now. Here's what I did:
```
cd /etc/xdg/qtchooser
rm default.conf
ln -s 5.conf default.conf
```
No idea why it changed, I've never done anything with qtchooser until just now.
