### ISSUE TITLE
"xbps_install chromium" fails [pentium 4]

### ISSUE THREAD

**Issue by jackg2** [voidlinux/void-packages#2163]
i have installed void-live-i686-20150713-lxde.iso to hd on a p4.
xbps_install chromium fails after loading libspeex..sig [from memory].
i can't try a 64bit machine at present, but guess it must work.

**Comment by Gottox** [comment]
At which point does it fail? Can you provide any output?

**Comment by jackg2** [comment]
i would love to, my machine became unusable [investigating another bug], and i need to re-install before returning to this, but not today.

**Comment by jackg2** [comment]
ok, i used output divert to a file [i think]:-

1 package will be downloaded:

  chromium-43.0.2357.132_1 
9 packages will be installed:

  libXScrnSaver-1.2.2_3 
  re2-20140304_1 
  libwebp-0.4.3_2 
  libxslt-1.1.28_5 
  snappy-1.1.1_2 
  dotconf-1.3_2 
  speech-dispatcher-0.8.3_1 
  libspeex-1.2rc2_5 
  chromium-43.0.2357.132_1 

Size to download:               43MB
Size required on disk:         202MB
Free space on disk:             18GB


[*] Downloading binary packages
Do you want to continue? [Y/n] 
ERROR: [trans] failed to download `chromium-43.0.2357.132_1' package from `http://repo.voidlinux.eu/current': Not Found

looks like the 32-bit repo has a file missing.

**Comment by Gottox** [comment]
@xtraeme seems like an issue with your delete script again.

The file is there now, as chromium was updated recently. Can you retry?

**Comment by xtraeme** [comment]
There's no issue here, repository data is outdated and it's trying to download an unexistent package.

Solution: `xbps-install -S foo`

**Comment by jackg2** [comment]
postscript to #2163:  my error.  i should have known that the chromium package was not missing, but removed to make way for a newer version.  if the default behaviour of xbps-install was to do an automatic update of the local list of packages, then i would not have reported this.  why is "-S" not the default, given that you do not keep older versions?
