### ISSUE TITLE
firefox crashes [pentium 4]

### ISSUE THREAD

**Issue by jackg2** [voidlinux/void-packages#2164]
i have installed void-live-i686-20150713-lxde.iso to hd on a p4.
when i am browsing the void wiki [https://github.com/voidlinux/documentation/wiki] when I click on the "xbps" link, firefox crashes [reproduces]
i can't try a 64bit machine at present, but guess it must work.

**Comment by Gottox** [comment]
Can you provide the output when you run firefox from the terminal? strace and stacktrace would be nice too.

**Comment by jackg2** [comment]
no.  i tried, but realized that i was running as root [stupid], and had not created an ordinary user.  when i logged out, i could no longer login as root:  the screen froze after accepting the root password and reboots were no better.  i am forced to re-install void and start again.  i will return to this, but not today.

**Comment by thypon** [comment]
Closing for now, for no interactivity.
