### ISSUE TITLE
chromium-pepper-flash: link to google-chrome .deb not working

### ISSUE THREAD

**Issue by Grauwolf** [voidlinux/void-packages#2240]
> % sudo xbps-install -f chromium-pepper-flash
>                                                         
> Name                  Action    Version           New version            Download size
> chromium-pepper-flash reinstall 18.0.0.209_5      18.0.0.209_5           -
>
> Size required on disk:          403B
> Free space on disk:           5264MB
>
> Do you want to continue? [Y/n] y
>
> [*] Downloading binary packages
>
> [*] Verifying package integrity
> chromium-pepper-flash-18.0.0.209_5: verifying RSA signature...
>
> [*] Running transaction tasks
> chromium-pepper-flash-18.0.0.209_5: unpacking ...
>
> [*] Configuring unpacked packages
> chromium-pepper-flash-18.0.0.209_5: configuring ...
> looking up dl.google.com
> connecting to dl.google.com:80
> requesting http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_44.0.2403.130-1_amd64.deb
> http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_44.0.2403.130-1_amd64.deb: Not Found
> sha256sum: chromium-pepper-flash.deb: No such file or directory
> chromium-pepper-flash.deb: FAILED open or read
> sha256sum: WARNING: 1 listed file could not be read
> Error while extracting
> ERROR: chromium-pepper-flash-18.0.0.209_5: [configure] INSTALL script failed to execute the post ACTION: Operation not permitted

**Comment by Gottox** [comment]
pepperbot was running in broken mode. Fixed.
