### ISSUE TITLE
build_pie does not propagate through libtool

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#2275]
For full protection, all shared libraries in a RELRO setup need to be
linked with "-z now".  Currently, we pass this via "-specs" to
LDFLAGS.  Unfortunately, our libtool drops the -specs argument, so
only the binaries itself get built with "-z now", but libraries the
programs may use don't.

I see several possible solutions:
- Patch libtool, ala http://lists.gnu.org/archive/html/bug-libtool/2013-10/msg00000.html
- Pass "-z now" via $LDFLAGS (we need to check if this is ignored for static libs) in common/environment/configure/build-pie.sh

Affected packages (only the first .so has been tested for each):

- [x] ConsoleKit2: /usr/lib/security/pam_ck_connector.so
- [x] at-spi2-core: /usr/lib/libatspi.so.0.0.1
- [x] avahi-compat-libs: /usr/lib/libdns_sd.so.1.0.0
- [x] avahi-libs: /usr/lib/libavahi-core.so.7.0.2
- [x] dbus-libs: /usr/lib/libdbus-1.so.3.8.13
- [ ] enlightenment: /usr/lib/enlightenment/modules/fileman_opinfo/linux-gnu-x86_64-ver-serious-0.19/module.so
- [x] eudev-libgudev: /usr/lib/libgudev-1.0.so.0.2.0
- [x] eudev-libudev: /usr/lib/libudev.so.1.6.3
- [x] f2fs-tools: /usr/lib/libf2fs.so.0.0.0
- [ ] firejail: /usr/lib/firejail/libtrace.so
- [x] gawk: /usr/lib/gawk/fork.so
- [x] gvfs: /usr/lib/gio/modules/libgioremote-volume-monitor.so
- [ ] irssi-perl: /usr/lib/perl5/x86_64-linux-thread-multi/auto/Irssi/TextUI/TextUI.so
- [x] irssi: /usr/lib/irssi/modules/libirc_proxy.so
- [x] libblkid: /usr/lib/libblkid.so.1.1.0
- [ ] libcaja: /usr/lib/libcaja-extension.so.1.4.0
- [x] libcryptsetup: /usr/lib/libcryptsetup.so.4.7.0
- [x] libfdisk: /usr/lib/libfdisk.so.1.1.0
- [x] libhaveged: /usr/lib/libhavege.so.1.1.0
- [ ] liblightdm-gobject: /usr/lib/liblightdm-gobject-1.so.0.0.0
- [ ] liblightdm-qt: /usr/lib/liblightdm-qt-3.so.0.0.0
- [ ] liblightdm-qt5: /usr/lib/liblightdm-qt5-3.so.0.0.0
- [x] liblzma: /usr/lib/liblzma.so.5.2.1
- [x] libmagic: /usr/lib/libmagic.so.1.0.0
- [ ] libmarco: /usr/lib/libmarco-private.so.0.0.0
- [ ] libmate-panel: /usr/lib/libmate-panel-applet-4.so.1.0.1
- [x] libmount: /usr/lib/libmount.so.1.1.0
- [x] libpulseaudio: /usr/lib/libpulse-simple.so.0.1.0
- [ ] librygel: /usr/lib/librygel-server-2.6.so.2.0.4
- [x] libsmartcols: /usr/lib/libsmartcols.so.1.1.0
- [ ] libupower-glib1: /usr/lib/libupower-glib.so.1.0.4
- [x] libuuid: /usr/lib/libuuid.so.1.3.0
- [x] libvarnishapi: /usr/lib/libvarnishapi.so.1.0.0
- [ ] mate-notification-daemon: /usr/lib/mate-notification-daemon/engines/libcoco.so
- [ ] mate-polkit: /usr/lib/libpolkit-gtk-mate-1.so.0.0.0
- [ ] mate-settings-daemon: /usr/lib/mate-settings-daemon/libmouse.so
- [ ] ntfs-3g: /usr/lib/libntfs-3g.so.86.0.0
- [x] nvi: /usr/lib/libvi.so.0.0.0
- [x] openvpn: /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so
- [x] pam-libs: /usr/lib/libpamc.so.0.82.1
- [x] pam-userdb: /usr/lib/security/pam_userdb.so
- [x] pam: /usr/lib/security/pam_tally2.so
- [x] polkit: /usr/lib/libpolkit-gobject-1.so.0.0.0
- [x] procps-ng: /usr/lib/libprocps.so.5.0.0
- [x] pulseaudio: /usr/lib/libpulsecore-6.0.so
- [x] qtcreator: /usr/lib/qtcreator/plugins/libDesigner.so
- [x] rsyslog-gnutls: /usr/lib/rsyslog/lmnsd_gtls.so
- [x] rsyslog-gssapi: /usr/lib/rsyslog/lmgssutil.so
- [x] rsyslog-mysql: /usr/lib/rsyslog/ommysql.so
- [x] rsyslog-postgresql: /usr/lib/rsyslog/ompgsql.so
- [x] rsyslog: /usr/lib/rsyslog/imdiag.so
- [ ] rygel: /usr/lib/rygel-2.6/plugins/librygel-mpris.so
- [x] sqlite: /usr/lib/libsqlite3.so.0.8.6
- [ ] subtle: /usr/lib/ruby/site_ruby/2.2.0/subtle/subtlext.so
- [x] sudo: /usr/libexec/sudo/group_file.so
- [x] udisks2: /usr/lib/libudisks2.so.0.0.0
- [x] unbound: /usr/lib/libunbound.so.2.3.7
- [x] varnish: /usr/lib/varnish/libvcl.so
- [ ] vte-python: /usr/lib/python2.7/site-packages/gtk-2.0/vtemodule.so
- [x] vte: /usr/lib/libvte.so.9.2800.2
- [x] wireless_tools: /usr/lib/libiw.so.29
- [x] xfsprogs: /usr/lib/libhandle.so.1.0.3
- [ ] xorg-server: /usr/lib/xorg/modules/libshadow.so

Also, we should compute the full DT_NEEDED tree of all build_pie
packages and make them build_pie too.

**Comment by chneukirchen** [comment]
I think passing "-z now" is the easiest fix here...

**Comment by xtraeme** [comment]
@chneukirchen passing `-z now` via `LDFLAGS` seems ok to me.

Thanks

**Comment by chneukirchen** [comment]
For rebuilds, verify the mentioned file is built with BIND_NOW:

    readelf -d masterdir/destdir/pam-1.2.1/usr/lib/security/pam_* |grep BIND

**Comment by chneukirchen** [comment]
So, for full protection of all PIE binaries installed on my system, we also need to make the following packages build_pie=yes:

```
LuaJIT acl alsa-lib atk attr bullet bzip2 cairo device-mapper
efl elementary expat fontconfig freetype fribidi fuse gdk-pixbuf
glib glibc gmp graphite gtk+ json-c libEGL libGL libICE libSM libX11
libXScrnSaver libXau libXaw libXcomposite libXcursor libXdamage libXdmcp
libXext libXfixes libXfont libXft libXi libXinerama libXmu libXp libXpm
libXrandr libXrender libXt libXtst libXxf86vm libasyncns libbsd libcap-ng
libcgmanager libdb libdrm libepoxy libevent libffi libflac libfontenc
libgbm libgcc libglapi libgpm libgssglue libharfbuzz libidn libjpeg-turbo
libkeyutils libkmod libmnl libnfsidmap libnih libnl3 libogg libpcre
libpng libsamplerate libseccomp libsndfile libssh2 libstdc++ libtirpc
libunwind libutempter libvorbis libxcb libxkbcommon libxshmfence lzo
mit-krb5-libs ncurses-libs pango pixman popt readline wayland xcb-util
xcb-util-image xcb-util-keysyms xcb-util-renderutil xcb-util-wm zlib
```

**Comment by thypon** [comment]
I'd drop the "-specs" entirily. Right now it's not supported even on clang and make the exchange between gcc/clang harder.

**Comment by chneukirchen** [comment]
We cannot drop -specs because it's the only way to pass these arguments correctly.

Clang support will need to replace these CFLAGS/LDFLAGS with something it understands.

**Comment by pullmoll** [comment]
I'm currently working on the qtcreator update to 3.5.0
What would I need to do to have BIND_NOW used in its libs? As far as I understand, in other packages you just set LDFLAGS to include `-z now` or is it `-Wl,-z now`?

With Qt5 projects I guess I would have to modify QMAKE_LDFLAGS.

Or even better yet: patch the Qt5-5.5.0 mkspec file `/usr/lib/qt5/mkspecs/common/g++-unix.conf` to include the `-z now`!?

**Comment by chneukirchen** [comment]
LDFLAGS passed to cc should include `-Wl,-z,now`.

I don't think it's a good idea at this point to hardcode it, at least until we decide to go full PIE.

**Comment by pullmoll** [comment]
Ok, so setting `QMAKE_LFLAGS_SHLIB+=" -Wl,-z,now"` seems to work for qmake based projects. When linking *.so files the `-Wl,-z,now` is among the parameters. qtcreator should now be ok.

**Comment by chneukirchen** [comment]
The qmake build-style could check for build_pie perhaps.

**Comment by pullmoll** [comment]
There is no qmake build-style yet. Packages use gnu-makefile call qmake in pre_configure().

**Comment by thypon** [comment]
#2317 CMake has a similar problem of qmake. I can't find a workaround yet.

**Comment by chneukirchen** [comment]
I think all relevant packages have been rebuilt in the meantime.

We use `-z now` in LDFLAGS for the time being.
