### ISSUE TITLE
nodejs throws "Illegal Instruction" on Raspberry Pi B+

### ISSUE THREAD

**Issue by mikroskeem** [voidlinux/void-packages#2299]
Hello! node.js is broken on Raspberry Pi B+ (ARMv6 cpu)  
Arch Linux ARM had [same problem](http://archlinuxarm.org/forum/viewtopic.php?f=15&t=8478).

```
[mark@endhole ~]$ node
Illegal Instruction
[mark@endhole ~]$ node --version
v0.12.7
[mark@endhole ~]$ node --v8-options
target arm v6 vfp3 hard
ARMv7=1 VFP3=1 VFP32DREGS=1 NEON=0 SUDIV=0 UNALIGNED_ACCESSES=1 MOVW_MOVT_IMMEDIATE_LOADS=0 USE_EABI_HARDFLOAT=1
Usage:
...
```

This [patch might help](https://github.com/archlinuxarm/PKGBUILDs/blob/master/community/nodejs/arm.patch)

**Comment by Gottox** [comment]
Shamelessly stealing patches from @archlinuxarm.
