### ISSUE TITLE
Dependency cycle

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2303]
When trying to build xfce4 for x86_64-musl from source (`./xbps-src -N …`) I see this cycle:
```
garcon
|
+- xfce4-dev-tools
     |
     +- gtk-doc
          |
          +- gnome-doc-utils
               |
               +- gsettings-desktop-schemas
                    |
-->                 +- gobject-introspection
                         |
                         +- cairo
                              |
                              +- libGL
                                   |
                                   +- eudev
                                       |
-->                                    +- gobject-introspection
```
The loop starts at gobject-introspection which eudev requires as well.
For a simple fix perhaps gir should be disabled in eudev. (Works after zap + binary-bootstrap x86_64-musl)

**Comment by xtraeme** [comment]
`eudev` does not enable the `gir` build option by default:

```
[juan@leysa void-packages]$ ./xbps-src show-options eudev
=> eudev-3.1.2_2: the following build options are set:
   gir: Enable support for gobject introspection data (OFF)
[juan@leysa void-packages]$
```

**Comment by pullmoll** [comment]
Strange, but you are of course right, there is no `build_options_default="gir"`. I don't remember what I changed to get it compile in the second try, except I did zap and binary-bootstrap.

Is it possible that the XBPS_PKG_OPTIONS from a package earlier in the chain were still set?

**Comment by xtraeme** [comment]
Could be possible, I'll check myself just to verify.

**Comment by pullmoll** [comment]
gsettings-desktop-schemas has default `gir` for non-cross builds...

**Comment by pullmoll** [comment]
I can't reproduce this anymore.
