### ISSUE TITLE
Package Request: IceCat

### ISSUE THREAD

**Issue by xfausto** [voidlinux/void-packages#2310]
IceCat is the GNU version of the Firefox browser.

https://www.gnu.org/software/gnuzilla/

**Comment by pullmoll** [comment]
I made a template based on firefox and also a set of patches.
I got it to compile (for glibc), however linking libxul currently fails.
If anyone wants to help out here's the branch: https://github.com/voidlinux/void-packages/compare/master...pullmoll:icecat

**Comment by xfausto** [comment]
@pullmoll If I recall correctly, you needed to have more than 4G of available memory to do this, or create a swap file, but I'll review it in my machine.

**Comment by xfausto** [comment]
You can also review the PKGBUILD of icecat https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=icecat

**Comment by pullmoll** [comment]
It's not a memory problem, but some object file seems to be generated without -fPIC and can't be linked to others. The exact error messages escapes me, but I had no quick fix.

Thanks for the arch build rules, but I fear they don't help here...

**Comment by xfausto** [comment]
Slackware users had the same problem http://www.linuxquestions.org/questions/slackware-14/icecat-won't-build-in-latest-current-4175540830/ It seems prevalent among 31.X releases of Firefox and thus IceCat.

**Comment by pullmoll** [comment]
Thank you! I'll try to use their patch and see if it links now.

**Comment by xfausto** [comment]
@pullmoll There was a similar bug currently discussed in IceCat mai list, and it seems the problem relies in newer versions of gcc:
- http://lists.gnu.org/archive/html/bug-gnuzilla/2015-07/msg00041.html

**Comment by pullmoll** [comment]
I applied that patch, but it doesn't fix the error output.
I think I'll just go and try to remove the spyblock@gnu.org addon from the default build, because it causes trouble and doesn't seem to work, according to the comment you linked to.

**Comment by xfausto** [comment]
@pullmoll No problem, I think most of the users opt to disable Spyblock and use another extension like ublock or similar.

**Comment by pullmoll** [comment]
Yeah. Personally I use adblock edge with firefox. The packaging is working now and the annoying message is gone. I'll create the pr and merge it later on.

Should there be any problems you're welcome to create a new issue and I'll try to take care of it.
