### ISSUE TITLE
Vagrant Package Is Missing Required Templates

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#2339]
When attemtping to build a base Vagrant box from a Virtualbox vm (via command _vagrant package --base_), I discovered there are templates missing from the package, by way of the following error:
```
/usr/lib/vagrant/gems/vagrant-1.7.4/lib/vagrant/util/template_renderer.rb:61:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/vagrant/gems/vagrant-1.7.4/templates/package_Vagrantfile.erb (Errno::ENOENT)_
```

In other words, Vagrant cannot generate the necessary Vagrantfile when given the _package_ command, because no template for doing so is available.

Furthermore, in the XBPS template file, there is this find and delete line (which I believe has caused my issue, specifically):

```
find ${DESTDIR} -type f -name \*.erb -delete
```

This is probably a *bad* idea, as Vagrant uses these to autogenerate configuration files, a feature which is part of its core feature set.

There are quite a few of these find and delete lines in there. We might be a bit more cautious about that...

(SURE, we can manually create this initial Vagrantfile (after all, it contains only the vm's MAC addy) and pass it in, as a parameter, to _package_, but that seems a bit silly, considering the aforementioned autogeneration as part of Vagrant's core. Also, given the aforementioned find and delete lines, I have no idea to what extent various things might be missing, which could lead to issues, down the road, while creating, configuring and running Vagrant boxes.)

Looking into /usr/lib/vagrant/gems/vagrant-1.7.4/template, when compared to the project github page,  there is quite a bit missing.

The following subdirectories are missing from the package:
commands
config
guests
nfs
provisioners

The following files are missing from the package (which caused my error):
package_Vagrantfile.erb

I've removed the find and delete line, as a file change proposal, and linked that to this issue.
The templates directory, under the project repo, can be viewed here:
https://github.com/mitchellh/vagrant/tree/master/templates

**Comment by thypon** [comment]
https://github.com/mitchellh/vagrant/blob/master/LICENSE

The license isn't needed.

The erb files was missing since i tested the package only with prepared Vagrantfile(s) from my library. Thank for the quickfix.
