### ISSUE TITLE
Vagrant Package Needs bsdtar

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#2340]
New error when running _vagrant package_:
```
The executable 'bsdtar' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

I installed bsdtar separately, and that fixes the issue.
I've added _bsdtar_ to depends, as a file change proposal, and linked that to this issue.

**Comment by thypon** [comment]
probably you could create a pull request.

**Comment by antonio-malcolm** [comment]
Yeah, doing that now. Still familiarizing myself with XBPS and the procdure for pull requests, reviews, commits and such, so bear with me, thanks ;o)
