### ISSUE TITLE
Package request: palemoon

### ISSUE THREAD

**Issue by skrzyp** [voidlinux/void-packages#2387]
[Pale Moon](https://www.palemoon.org/) browser, a conservative Firefox fork (yes, now it's a pure fork, not only a rebranding - it has own release cycle and different codebase), with classic UI, lack of "modern" "features" like Pocket integration, and some other improvements.

**Comment by Duncaen** [comment]
Until browser developers get their act together and only work on ONE browser I refuse to waste my time patching their software.
https://github.com/MoonchildProductions/Pale-Moon/issues/366

**Comment by crocket** [comment]
one browser? Do you mean palemoon and basilisk?

**Comment by Gottox** [comment]
Nope, not in the mood to get threats..

**Comment by skrzyp** [comment]
Just for reference, can I get a backstory about that? :)

**Comment by crocket** [comment]
palemoon developers refused to support musl, so void-packages maintainers refused to include palemoon, too.

**Comment by Hoshpak** [comment]
They also refuse to support current gcc versions which makes it unfit to be included in a rolling release distribution.

**Comment by Gottox** [comment]
For reference: https://github.com/jasperla/openbsd-wip/issues/86

**Comment by Gottox** [comment]
Void packages lots of stuff that refuses to support musl ( == proper standards).

In contrast to openbsd-wip, which only distributes build instructions, (this is why the linked issue isn't reasonable) we ship binaries. That means the threats that were done to the linked repository actually apply to Void if we would add palemoon with system libraries.
