### ISSUE TITLE
Passing "setxkbmap" to .xinitrc crashes X

### ISSUE THREAD

**Issue by Xisiqomelir** [voidlinux/void-packages#2391]
Issue: When certain arguments beyond launching the DE/WM are passed in .xinitrc, X starts and then crashes.

To reproduce (void-live-x86_64-20150713.iso):
1) Install base system
2) xbps-install -S xorg lxqt 
3) edit ~/.xinitrc to `exec startlxqt`
4) startx will launch lxqt without issue
5) exit lxqt
6) edit ~/.xinitrc to `exec startlxqt & setxkbmap dvorak`
7) startx will launch lxqt to a black screen then it will crash.

MATE also suffers from this issue, so it is not lxqt-specific.

**Comment by Duncaen** [comment]
Your xinitrc should look something like this.
```
#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
setxkbmap dvorak &
exec startkxqt
```

**Comment by Xisiqomelir** [comment]
Reversing the order of operation fixed it, thanks Duncaen.
