### ISSUE TITLE
firefox conflicts with firefox-esr while updating

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#2392]
```
[*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
[*] Updating `http://repo.voidlinux.eu/current/debug/x86_64-repodata' ...
CONFLICT: firefox-esr-38.2.1_1 with installed pkg firefox-40.0.2_3
Transaction aborted due to conflicting packages.
```

Log output: https://gist.github.com/0e0dbae4070096850818

Got no time to fix atm as I'm sick :/

**Comment by uggedal** [comment]
How were you able to install both at the same time since `firefox-esr` conflicts with `firefox`?

**Comment by cavalier911** [comment]
Add to firefox template: `conflicts="firefox-esr>=0"`

**Comment by Gottox** [comment]
Both browser were installed side by side as the conflicts flag was missing. I was unable to remove firefox-esr and had to remove firefox first, firefox-esr afterwards, and reinstall firefox to solve this issue.

**Comment by Gottox** [comment]
This rather belongs to xbps than void-packages. Closing.
