### ISSUE TITLE
Package Request: Uzbl

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#2399]
http://www.uzbl.org/

Well... everyone else is requesting browsers....

**Comment by dominikh** [comment]
The last release (according to github.com/uzbl/uzbl/releases, which is the repo that github.com/Dieterbe/uzbl (from http://www.uzbl.org/get.php) redirects to) is from 2012. 

I can't tell how active uzbl development is, it seems to be on and off with huge gaps inbetween. Either way, without a recent release, there's no point in packaging it. The version from 2012 is certainly not worth packaging.

**Comment by logenkain** [comment]
On Fri, Aug 28, 2015 at 09:34:27AM -0700, Dominik Honnef wrote:
> The last release (according to github.com/uzbl/uzbl/releases, which is the repo that github.com/Dieterbe/uzbl (from http://www.uzbl.org/get.php) redirects to) is from 2012. 
> 
Oh good point, I didn't notice the date.

**Comment by cgag** [comment]
What about it being from 2012 makes it not worth packaging?  Just curious, I don't really have a strong opinion either way, but if people use it seems like a package would be nice, curious what I'm missing.

**Comment by logenkain** [comment]
On Sat, Aug 29, 2015 at 10:36:33PM -0700, Curtis Gagliardi wrote:
> What about it being from 2012 makes it not worth packaging?  Just curious, I don't really have a strong opinion either way, but if people use it seems like a package would be nice, curious what I'm missing. 

That's also a great point.  uzbl is weird though, the github is somewhat
active, no idea why they haven't added a release in so long.

But back to your point, I suppose even a dead project from 2002 can be
valuable.

**Comment by dominikh** [comment]
The version from 2012 is horribly out of date, to the point that it will not compile or work with our version of webkit. Also, most resources for uzbl – scripts, documentation and the like – will not work with that version.

**Comment by dominikh** [comment]
It looks like uzbl has picked up development again:

> but a release hasn't been tagged yet. A few more things to do yet.

Happy to pick this up again when the release has happened.

**Comment by logenkain** [comment]
On Thu, Oct 01, 2015 at 01:30:54PM -0700, Dominik Honnef wrote:
> It looks like uzbl has picked up development again:
> 
> > but a release hasn't been tagged yet. A few more things to do yet.
> 
> Happy to pick this up again when the release has happened.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/issues/2399#issuecomment-144838997

Yea, I've been following it, sounds like a release might happen within
the reasonable future.

**Comment by logenkain** [comment]
UZBL has finally updated just a few hours ago.  Anyone willing to package it still?

**Comment by Vaelatern** [comment]
Seems there are 3 flavors. Also depends on `webkit/webkit.h` but I can't xlocate it.

**Comment by ebfe** [comment]
@logenkain can you give this a try https://github.com/ebfe/void-packages/blob/uzbl/srcpkgs/uzbl/template?
