### ISSUE TITLE
help2man (perl): failure with musl libc

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2425]
With musl libc help2man tries to encode a document using an `$user_encoding` value of `UTF-8-CODE-UNITS` in line 56 of `/usr/bin/help2man`.

The exact error message is:
```
Unknown encoding 'UTF-8-CODE-UNITS' at /usr/bin/help2man line 56.
```
This happens when e.g. trying to build `bison` for musl libc.

The value for this encoding is reported to be contained in `/usr/lib/libc.so` and `/usr/lib/libc.a` in a `x86_64-musl` masterdir, so it seems to be legitimate.

I think perl::Encode needs to handle this specific value for musl libc in some way. Perhaps add a patch for `cpan/Encode/lib/Encode/Alias.pm` for additional valid encodings for musl libc? i don't know too much perl, so perhaps @xtraeme or whoever knows perl can help here.

**Comment by pullmoll** [comment]
FWIW: I now confirmed that adding an alias
    `define_alias( qr/^UTF-8-CODE-UNITS$/i          => '"UTF-8"' );`
to the `init_aliases` function in `cpan/Encode/lib/Encode/Alias.pm` solves the problem with building bison for musl libc.

**Comment by pullmoll** [comment]
The same encoding name issue seems to hit Python as well.
Perhaps the update of musl libc to 1.1.11 should be inspected more closely.

IMHO it can't really be necessary to patch a lot of packages depending on a libc, or can it?

If the issue can be identified and fixed in musl-1.1.11, we can avoid #2426 and more..

**Comment by pullmoll** [comment]
Further investigating in the musl-1.1.11 source coide I see these lines in `src/internal/locale_impl.h`
```
#define CURRENT_UTF8 (!!__pthread_self()->locale->cat[LC_CTYPE])

#undef MB_CUR_MAX
#define MB_CUR_MAX (CURRENT_UTF8 ? 4 : 1)
```

And in `src/locale/langinfo.c` function `__nl_langinfo_nl()` this macro is used to decide whether to return `"UTF-8-CODE-UNITS"` or `"UTF-8"`.
```
        if (item == CODESET)
                return MB_CUR_MAX==1 ? "UTF-8-CODE-UNITS" : "UTF-8";
```

So `__pthread_self()->locale->cat{LC_CTYPE]` would have to be non-zero to make the function return `"UTF-8"`.

Does this mean we __must__ set `LC_CTYPE` to some value in the chroot environment to get sane results?

**Comment by xtraeme** [comment]
The musl author told me that he will change the code to return "UTF-8".

Stay tuned.

**Comment by pullmoll** [comment]
Great. I could get everything to work as before by patching above function to return "UTF-8" for both cases. Perhaps we should temporarily have a fixed musl-1.1.11_2, unless 1.1.12 is to appear very soon?

**Comment by xtraeme** [comment]
I don't think 1.1.12 will be released in the upcoming days. We could patch musl meanwhile.

**Comment by pullmoll** [comment]
I'll take care of it.

**Comment by xtraeme** [comment]
Err, sorry didn't read your comment until now :-)

**Comment by pullmoll** [comment]
Hehe.. Thank you! I can take care of making a coffee now :)
