### ISSUE TITLE
Package request: vis. suckless vi-like editor

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#2434]
https://github.com/martanne/vis

dunno if there are released tarballs yet

**Comment by pullmoll** [comment]
@radare Would you please ask Marc André Tanner for a release, if you still want this packaged?

**Comment by radare** [comment]
Ok ill try

**Comment by asergi** [comment]
Already there. See #3265.

**Comment by radare** [comment]
Awesome 👍
