### ISSUE TITLE
Package Request: Cyberfox 64-bit Web Browser

### ISSUE THREAD

**Issue by Bojinx** [voidlinux/void-packages#2435]
Home Page:  https://cyberfox.8pecxstudios.com/

http://sourceforge.net/projects/cyberfox/files/Zipped%20Format/

https://github.com/InternalError503/cyberfox

**Comment by thypon** [comment]
This #2387 ?

Could you point out why we need to package a different themed firefox?

Extracted from the main site:
```
- Choose From Two Styles
- Processor Based Optimization
- Portable
- Additional Features
```

**Comment by chneukirchen** [comment]
Void Linux: the distro with more browsers than users.

**Comment by skrzyp** [comment]
Cyberfox makes sense only on Windows. It does only provide a Windows 64-bit build, among some other minor tweaks.
And, compared to Palemoon, it's not enough to package it, where PM is a full-fledged Firefox fork with own source tree…

**Comment by the-maldridge** [comment]
Closed as this will not be considered at this time, and its ancient.
