### ISSUE TITLE
package request: xf86-video-amdgpu

### ISSUE THREAD

**Issue by pullis** [voidlinux/void-packages#2475]
http://cgit.freedesktop.org/xorg/driver/xf86-video-amdgpu/.

I'm not sure if this is already available from some other package, at least I didn't find it. I have kernel4.2 and newest firmware installed but xorg doesn't show amdgpu in drivers list and  ```X :0 -configure``` says no devices to configure. ```lsmod | grep -i amdgpu``` shows amdgpu modules are loaded and dmesg shows that there are amdgpu logs.

I can launch X (to lxdm login screen) using old xorg.conf but one of my monitors flickers really badly making it impossible to read anything. 

musl x86_64

**Comment by xtraeme** [comment]
That's right, we have not packaged `xf86-video-amdgpu` yet. Will package a git snapshot soon.
