### ISSUE TITLE
Package request: Calibre

### ISSUE THREAD

**Issue by nonolander** [voidlinux/void-packages#248]
Hi !

Thanks to Ypnose i open this topic to request the packager of void linux to include Calibre (http://calibre-ebook.com/) into your official repositories. I searched but i didn't find any ebook software in your repo, then i suggest you this.

Nonolander

**Comment by thypon** [comment]
winter is coming

```
index: added `calibre-2.50.1_1' (x86_64).
index: 4 packages registered.
```

**Comment by thypon** [comment]
#3555
