### ISSUE TITLE
libGL: fails to build because of llvm is missing R600 target

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2505]
The updated llvm-3.7.0 does no longer have an R600 target.
Trying to build libGL fails with this error message:
```
checking for RADEON... yes
checking for RADEON... yes
configure: error: LLVM R600 Target not enabled.  You can enable it when building the LLVM
                      sources with the --enable-experimental-targets=R600
                      configure flag
=> ERROR: libGL-10.6.6_1: failed to run do_configure() at line 7.
```

**Comment by thypon** [comment]
R600 isn't available anymore; the new unified architecture is named AMDGPU. It's better to upgrade to the new libGL or downgrade llvm.

**Comment by xtraeme** [comment]
No downgrades please, mesa-11 is near the corner and should be released in 2 weeks. We can just wait.

**Comment by thypon** [comment]
@pullmoll you could currently try packaging ftp://ftp.freedesktop.org/pub/mesa/11.0.0/
