### ISSUE TITLE
ca-certificates + chroot.sh: bad encoded filename

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2513]
When trying to build the `ca-certificates` package, I now get an interesting error in `00-gen-pkg`:
```
=> ca-certificates-20150426_3: running do-pkg hook: 00-gen-pkg ...
=> Creating ca-certificates-20150426_3.noarch.xbps for repository /host/binpkgs ...
xbps-create: ERROR: cannot write ./usr/share/ca-certificates/mozilla/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.crt to archive: Can't translate pathname './usr/share/ca-certificates/mozilla/TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.crt' to UTF-8 Invalid or incomplete multibyte or wide character
=> ERROR: ca-certificates-20150426_3: failed to run do-pkg_00-gen-pkg() at line 92.
```
I know I successfully built this same package a couple of weeks ago, when I added the removal of expired certificates inspired by BLFS, so it's not the package itself.

This error message occurs since my recent addition of `LC_ALL=C`  to `common/xbps-src/shutils/chroot.sh`!

I temporarily removed that here and `ca-certificates` builds again. I don't think we have a locale `C.UTF-8` available, so perhaps it is better to revert the addition of `LC_ALL=C` and try to take care of other locale related errors in the respective packages.

Or perhaps unset LC_ALL in `common/hook/do-pkg/00-gen-pkg.sh`?

**Comment by pullmoll** [comment]
Confirmed: Modifying `common/hooks/do-pkg/00-gen-pkg.sh` to
```
LC_ALL= xbps-create \
…
```
also solves the problem. I don't know which is the right thing to do, though. @xtraeme ?

**Comment by chneukirchen** [comment]
I think there is a bug in xbps hiding here: locale should have zero effect on the storage of filenames, which are simply binary strings.

**Comment by pullmoll** [comment]
I agree. It may result from some internal conversion of the filenames for the plist, but I couldn't find a possible location in xbps sources at a quick glance. From tomorrow I'm away for 7-14 days (hospital) so I can't look any further and wish you good luck on this.

**Comment by xtraeme** [comment]
The issue is not xbps, rather libarchive. It cannot handle utf8 characters
with the C locale. So that unsetting LC_ALL for xbps-create(1) seems the
right way to me.

@pullmol take care man, its appreciated all the work you put on it.

**Comment by pullmoll** [comment]
Perhaps `xbps-create/main.c` could `setenv("LC_ALL", "")` or `setlocale(LC_ALL, "")` or both?

**Comment by chneukirchen** [comment]
Can you check if LC_COLLATE and LC_CTYPE is enough? Setting all of them will remove localized error messages (not sure we use them).
