### ISSUE TITLE
Package Request: spectrwm

### ISSUE THREAD

**Issue by sdoubleyou** [voidlinux/void-packages#2553]
https://github.com/conformal/spectrwm
spectrwm is a small dynamic tiling window manager for X11

**Comment by diogoleal** [comment]
spectrwm is in Void
https://github.com/voidlinux/void-packages/tree/master/srcpkgs/spectrwm

**Comment by sdoubleyou** [comment]
thx :+1:

**Comment by sdoubleyou** [comment]
there are no xlock and libswmhack, or not?

**Comment by skrzyp** [comment]
There are some other lockers, like slock or trollock.
