### ISSUE TITLE
musl bug: glib trap on g_logv

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#2583]
```
Program received signal SIGTRAP, Trace/breakpoint trap.
g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7fffffffe2e0) at gmessages.c:1046
1046    in gmessages.c
```

This happens every time i start ulatencyd on musl.

**Comment by thypon** [comment]
These traps happens also on glibc, the difference is that on musl exits on trap while it doesn't on glibc.

**Comment by chneukirchen** [comment]
Doesn't this work as expected?

> Logs an error or debugging message.
> If the log level has been set as fatal, the abort() function is called to terminate the program.

> G_LOG_LEVEL_ERROR is always fatal.

Reopen if still relevant.
