### ISSUE TITLE
openbsd-netcat: replace with libressl/apps/nc

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#2595]
libressl 2.3.0 contains a portable version of openbsd nc with TLS support.
From reading the manpages, it seems it gained TLS support compared to Debian's openbsd-netcat, however DCCP support and CRLF sending was removed.

I'd be in favor to replace openbsd-netcat with this modern and maintained version, and make it a subpkg of libressl when we go to 2.3.0.

**Comment by thypon** [comment]
+1

**Comment by ebfe** [comment]
#2595

**Comment by ebfe** [comment]
#3967

**Comment by Vaelatern** [comment]
libressl-netcat now in repos.

**Comment by chneukirchen** [comment]
Thanks.
