### ISSUE TITLE
Package Request: Kdenlive

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#2610]
https://kdenlive.org/

I'm sick of using Ubuntu for video editing, but I get lost quick when it comes to KDE crap.  Looking at their website says one thing... a look at how Arch did it looks completely different.  In either case it seems like there are a lot of packages required to get this to work.

**Comment by jnbr** [comment]
#5586

**Comment by jnbr** [comment]
#5586 is merged.
