### ISSUE TITLE
calligra-krita: missing runtime-dependency oxygen-icons

### ISSUE THREAD

**Issue by lemmi** [voidlinux/void-packages#2616]
i can only speak for krita, but i would assume that some other packages could be missing this one aswell. i had a look at the template, but i'm not quite sure where to put it :)

**Comment by xtraeme** [comment]
I cannot reproduce this even without oxygen-icons. Can you show a screenshot?

**Comment by lemmi** [comment]
krita spits out a warning about missing oxygen-icons and icons are missing all over the place.
![krita](https://cloud.githubusercontent.com/assets/2631530/10252497/19b7c3ec-6938-11e5-9537-aae64e2ee670.png)

**Comment by asergi** [comment]
Obsolete. `calligra-krita` is no more.
