### ISSUE TITLE
Our default $PATH

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#2629]
I compared our $PATH to some other distros, and noticed:

- [ ] /usr/local comes after /usr, which makes it useless to override Void binaries
- [ ] bin comes before sbin, which is unusual
- [ ] we still have non-/usr paths in there, how long do we want to keep that?

FTR:
- Arch: `PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"`
- Debian: `PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`
- RedHat: `PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/games"`

**Comment by bougyman** [comment]
+1 to moving /usr/local/{sbin,bin} to the front of the line.

**Comment by xtraeme** [comment]
No objections, lgtm :+1:

**Comment by chneukirchen** [comment]
Should we kick out /sbin:/bin too? It could break for non-usrmoved machines.

**Comment by xtraeme** [comment]
Indeed, makes sense @chneukirchen

**Comment by uggedal** [comment]
+1 to `/usr/local` first and removal of `/sbin:/bin`

**Comment by chneukirchen** [comment]
So,

```
-PATH="/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/bin:/sbin"
+PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"
```

**Comment by thypon** [comment]
@chneukirchen  given when you chroot inside something /sbin:/bin and the current PATH were used i think the conservative way it's better.

**Comment by chneukirchen** [comment]
FTR, Fedora 23 (post UsrMove) doesn't include /bin either.

**Comment by thypon** [comment]
Archlinux doesn't include either and it breaks containers/chroots mainly. Leaving wouldn't harm nobody.

**Comment by chneukirchen** [comment]
If they are at the end, they don't cost anything really.

**Comment by chneukirchen** [comment]
I'll put /usr/bin in front of /usr/sbin, so `which` results in the non-sbin path.

**Comment by chneukirchen** [comment]
`PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin"`
