### ISSUE TITLE
Can't update because unresolvable shlib in libvlc

### ISSUE THREAD

**Issue by paddy-garcia** [voidlinux/void-packages#2652]
When I try to run "xbs-install -Syu" I get this:

libvlc-2.2.1_9: broken, unresolvable shlib `liblua.so.5.2'
Transaction aborted due to unresolved shlibs.

I can't update only if I have vlc and libvlc installed, without them I can update but I can't install vlc for the same reasons above.

**Comment by pullmoll** [comment]
It is fixed by rebuilding vlc with a version dump http://build.voidlinux.eu/changes/16963
