### ISSUE TITLE
lumina missing dependency

### ISSUE THREAD

**Issue by zemoth** [voidlinux/void-packages#2715]
Installig lumina by doing 'xbps-install -S xorg lumina' doesn't work, it still requires dbus.

Shouldn't this be added to the lumina depends?

**Comment by Vaelatern** [comment]
@chneukirchen Can you please confirm or close this issue?

**Comment by chneukirchen** [comment]
```
% xbps-query --fulldeptree -Rx lumina |grep dbus
dbus-libs-1.10.8_1
dbus-x11-1.10.8_1
```

This is not more broken than any other dbus using program.
