### ISSUE TITLE
pafy/youtube-dl: unable to find moduel youtube_dl

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#2722]
Pafy decided to drop their stream code in favor of youtube_dl.  Well, it now requires the youtube_dl module to build so I added it to hostmakedepends.

Pafy can't seem to find it during build, and I'm a bit at a loss of what to do.

**Comment by Duncaen** [comment]
The youtube-dl package doesn't contain the `youtube_dl` module in `/usr/lib/python{2.7,3.4}/site-packages`.
Maybe you can create subackages for `python-youtube-dl` and `python3.4-youtube-dl` and keep the youtube-dl package with the binary or install the youtube-dl binary as part of the python package?
