### ISSUE TITLE
lumina-0.8.6_2: checksum fail

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2727]
I get `1333877c8e004f7e394f88a150d98116dba5b8c3b5c2a3988eac33f9d70f248e`
The template has `checksum=3cbe83615b965f1b888d5b76aef0606bdc7c9a9a8219e22a4175f4b8cf0783fc`

I don't want to change it without someone taking a look what changed without version bump?

**Comment by chneukirchen** [comment]
Perhaps the tag name changed upstream to v.8.6-Release?

**Comment by pullmoll** [comment]
The file `0.8.6-Release.tar.gz` also has the first sha256sum.
It looks more like they changed the contents of the release tarball since Aug 23.

**Comment by chneukirchen** [comment]
ugh. I guess we'll have to bump it then.

**Comment by pullmoll** [comment]
Hmm.. this failed because the existing file in the `hostdir/sources/lumina-0.8.6` directory has the previous checksum. We need to remove it manually.

**Comment by pullmoll** [comment]
Reopening, because the build servers need to get rid of the old version.

**Comment by pullmoll** [comment]
Package was updated.
