### ISSUE TITLE
libtool version outdated

### ISSUE THREAD

**Issue by WKuipers** [voidlinux/void-packages#2733]
The latest stable version of libtool is 2.4.6 according to the [GNU website](https://www.gnu.org/software/libtool/). The version in the repository is 2.4.2.
I have a feeling this could be fixed by changing one number

**Comment by xtraeme** [comment]
You are feeling incorrectly, our libtool contains some patches for cross compilation that need to be adapted to newer versions.

It's not too important if we are still using 2.4.2.

**Comment by xtraeme** [comment]
#2785 has a libtool 2.4.6 update that is being verified.

**Comment by xtraeme** [comment]
libtool-2.4.6 pushed
