### ISSUE TITLE
libxbps links to too new glibc after xbps-install -Su

### ISSUE THREAD

**Issue by boomlinde** [voidlinux/void-packages#2775]
I issued an `xbps-install -Su` the other day and have since been unable to use the xbps tools, which fail with messages like `xbps-install: /usr/lib32/libc.so.6: version 'GLIBC_2.22' not found (required by /usr/lib32/libxbps.so.2)`. `ldconfig -v` reveals that `libc.so.6 -> libc-2.21.so`. The package list agrees (`<string>glibc-2.21_9</string>`)

Here is some info from the package list:

* glibc: http://76931b7d35420ff8.paste.se/
* libxbps: http://0f4835d80756b24d.paste.se/

What would be the most graceful way to recover from this? I would downgrade libxbps and xbps (it looks like I have older versions in the cache), but can't use my xbps binaries to do so.

**Comment by xtraeme** [comment]
I'm aware of this issue and I'm working in a proper fix.

**Comment by Gottox** [comment]
duplicate of https://github.com/voidlinux/xbps/issues/124

**Comment by boomlinde** [comment]
Thanks, that did the trick
