### ISSUE TITLE
xf86-video-fbturbo: not found in rpi2 musl

### ISSUE THREAD

**Issue by pickfire** [voidlinux/void-packages#2783]
Hi, I had looked into https://github.com/voidlinux/documentation/wiki/Raspberry-Pi, it seemed that the package `xf86-video-fbturbo` doesn't exist. (and some xorg-* too)

**Comment by pickfire** [comment]
Thanks, but it seems that `xorg-apps` and `xorg-font` doesn't work too.

**Comment by xtraeme** [comment]
I've bumped them and those are being built currently: see http://build.voidlinux.eu

Cheers

**Comment by pickfire** [comment]
Nice builder but bad documentation, I guess I have to improve it to make it the Arch Wiki's competitor.

The `xbps` seems similar to `pacman` and `apt-get`, is there a need to make the command so long?

**Comment by Duncaen** [comment]
@pickfire If you think xbps-install is to long add add an alias like `alias xi="xbps-install"` or install the `xtools`[0] package which has `/usr/bin/xi` and `/usr/bin/xq` and some other usefull tools for working with xbps like `xlocate` to search files in packages. 
http://www.voidlinux.eu/usage/xbps/

**Comment by pickfire** [comment]
@Duncaen thanks, that came in my mind too, but I am just suggesting it to be shorter.

@xtraeme `omxplayer` isn't in musl.

A few questions:

1. After installing `xf86-video-fbturbo`, I still can't get Xorg to work, there is an error `No screens found` and the FAQ of xorg said that the error is related to the driver which is `xf86-video-fbturbo`.

2. Is drm available in the kernel for raspberry pi 2?

**Comment by stpx** [comment]
@pickfire `omxplayer` is now in the musl repo.

**Comment by pickfire** [comment]
After installing what in the wiki said required, I still can't get X to work.

**Comment by xtraeme** [comment]
@pickfire fixed with the newest xorg-server.

**Comment by pickfire** [comment]
@xtraeme Thanks, I wil try it. If I Recall Correctly, I can't find `xorg-apps` in xbps.

**Comment by xtraeme** [comment]
That was fixed days ago... and @Duncaen already tested it on rpi2/musl.

**Comment by pickfire** [comment]
Thanks, I tested it and it works.

I am not sure why firefox does not play videos, maybe I didn't installed gstreamer correctly.

For the other software, everything works fine and fast.

**Comment by xtraeme** [comment]
firefox needs the gst-plugins-xxx1 pkgs to play some video codecs.

**Comment by pickfire** [comment]
Thanks @xtraeme

Why is there a lot of `*-devel` packages, what are they for, if I recall correctly, it is similar to debian but I can't find that in arch?

**Comment by xtraeme** [comment]
Because void splits development files into its own packages, to reduce
dependencies
and size of the installed base system.

Arch, on the other hand does not split packages for development, so that
you've got all files
provided by the software, and more dependencies that are only required to
build the software,
not to run it.


2015-10-26 12:12 GMT+01:00 Ivan Tham <notifications@github.com>:
