### ISSUE TITLE
Skype cannot be built for x86_64

### ISSUE THREAD

**Issue by yuy168** [voidlinux/void-packages#2791]
Noticing that skype wasn't in the xbps repos, but was in void-packages for some reason,  I tried installing it through ./xbps-src. It appears to work but I get the error message in my title. 

Steps to reproduce:

Attempt to install skype through the aforementioned method

Am I doing something utterly stupid or is something up here?

**Comment by Duncaen** [comment]
These binaries are the only ones skype provides, no way to get a 64bit version.

**Comment by yuy168** [comment]
I'm able to run skype on my other 64bit Linux distros (Ubuntu, Arch, Gentoo. etc.) How would I go about getting it working here? Is it not possible?

**Comment by dominikh** [comment]
skype is in the void repos, but since it's only available as a 32 bit application, you need to enable the multilib repository and install skype-32bit.

```
# xbps-install -Su void-repo-multilib-nonfree
# xbps-install -Su skype-32bit
$ skype
```

**Comment by Duncaen** [comment]
`xbps-install -S void-repo-multilib-nonfree`
http://www.voidlinux.eu/usage/xbps/#subrepositories

**Comment by yuy168** [comment]
Already have that installed and am still unable to use skype. I've read the section you linked, I've synced multiple times already. Am I overlooking something?

**Comment by dominikh** [comment]
You could begin by stating what "unable to use skyoe" means. What happens when you launch skype?

**Comment by yuy168** [comment]
Nevermind, I did not see dominkhs post. Apolgies for my spelling mistake. It turns out it was me simply not realizing it should have been "skype-32bit" and reading Dominkh's post cleared that up. I think this issue can be declared solved.

**Comment by dominikh** [comment]
Great. Enjoy.
