### ISSUE TITLE
Package Request: Plymouth

### ISSUE THREAD

**Issue by Spencer-H** [voidlinux/void-packages#2792]
Would it be possible to package plymouth (the boot splash program) for void. Trying to install it myself seems a bit too daunting for me as it is normally best handled by the distro's packaging system. I was staring at the spinning logo on Void's homepage and it occurred to me that it would make a perfect plymouth splash. Sadly I have no way to install it (that I feel safe doing).

**Comment by ebfe** [comment]
96cd364ee1f3165774a7278557438fbf778cda0a
