### ISSUE TITLE
Package request: slack

### ISSUE THREAD

**Issue by TheDoctorsLife** [voidlinux/void-packages#2801]
Slack now has ubuntu and fedora downloads, so linux has its love now.
http://slack.com

**Comment by dominikh** [comment]
What's the license? Does it allow redistribution?

**Comment by TheDoctorsLife** [comment]
I wasn't able to find it on their website, but I have sent an email to them in regards to it.

**Comment by dominikh** [comment]
Any update?

**Comment by TheDoctorsLife** [comment]
No, going to try another email

**Comment by diogoleal** [comment]
This package already exist in repo.
I sent a version update. #4679
