### ISSUE TITLE
X spontaneously crashes, returns to login screen

### ISSUE THREAD

**Issue by TurtleKitty** [voidlinux/void-packages#2806]
Usually when I'm clicking on something in Chromium.  The error in /var/log/messages is consistent after each crash:

console-kit-daemon[823]: GLib-CRITICAL: g_hash_table_foreach_remove_or_steal: assertion 'version == hash_table->version' failed

I ran xbps-install -Su recently, so I should be fairly up-to-date.

Let me know what other information might help.

**Comment by xtraeme** [comment]
` xbps-query -s glib`

**Comment by TurtleKitty** [comment]
# xbps-query -s glib
[*] avahi-glib-libs-0.6.31_23 Avahi glib shared libraries
[*] dbus-glib-0.104_1         GLib bindings for D-Bus
[*] garcon-0.4.0_1            Glib/GIO freedesktop.org compliant menu implementation
[*] glib-2.46.1_1             The GNU library of C routines
[*] glib-networking-2.46.1_1  Network-related giomodules for glib
[*] glibc-2.22_1              The GNU C library
[*] glibc-devel-2.22_1        The GNU C library - development files
[*] glibc-locales-2.22_1      The GNU C library - locale data files
[*] goffice-0.10.24_1         Document-centric objects and utilities for GLib and Gtk+
[*] json-glib-1.0.4_1         A JSON parser for GLib-based libraries and applications
[*] libgusb-0.2.7_2           GLib wrapper around libusb1
[*] libmm-glib-1.4.12_1       Mobile broadband modem management service - GLib library
[*] libupower-glib1-0.9.23_10 Abstraction for enumerating power devices - runtime library
[*] poppler-glib-0.36.0_1     PDF rendering library - GLib bindings
[*] taglib-1.9.1_4            Library for accessing ID tags in various media files
[*] telepathy-glib-0.24.1_1   Library for GLib-based Telepathy components

**Comment by TurtleKitty** [comment]
This fixed itself at some point in the past.
