### ISSUE TITLE
Package Request: zen-kernel

### ISSUE THREAD

**Issue by muddmaker** [voidlinux/void-packages#2814]
[Zen](https://github.com/zen-kernel/zen-kernel) is a patchset for the linux kernel that includes the [BFS](https://en.wikipedia.org/wiki/Brain_Fuck_Scheduler) and several other cool additions that improve responsiveness. There is also [liquorix](http://liquorix.net/), which is a distribution of zen and contains more information about what this patchset contains.

**Comment by TheDoctorsLife** [comment]
+1

**Comment by SametSisartenep** [comment]
I'm working on this at the moment. I'll ping you as soon as I get it working, so I can make a PR if the team is interested. :wink:

**Comment by pullmoll** [comment]
If you ask me, kernel patchsets are unlikely to make it into the main repository for the prevalent reason: maintenance. But then I'm not then one to decide whether or not.

I wouldn't spend too much time on it, if I were you. ;-/

**Comment by SametSisartenep** [comment]
Well, I'd like to use it as main kernel, so it wouldn't be such a burden personally. But you're right, I mean, I also asked on IRC last week and the team told me something similar.

Maybe I could create a separate repo with the `srcpkgs/linux{,-4.7,-4.7-headers,-4.7-dbg}-zen` packages, just in case someone else needs it or is interested in contributing (to fix the automation, as it prompts for each option in the zen patchset, for example.)

**Comment by SametSisartenep** [comment]
Just uploaded the templates here -> https://github.com/SametSisartenep/void-zen-linux.

It's not fully automated though, you still need to enter some options. I'll fix that ASAP.

**Comment by chneukirchen** [comment]
We have enough issues keeping up with mainline kernels, so closing this.

Experienced users can easily build their own kernels or kernel packages.

**Comment by Arzte** [comment]
For anyone stumbling on this thread who is interested in using the zen kernel, clone the void-packages repo, then doing the following steps.

1. Go to https://pkgbuild.com/~heftig/zen-patches/ and download the latest kernal ``.diff`` that is in the void repo. EG. ``zen-4.14.15-f695616ca01b187a24635fe51e10c17dc5bccaa2.diff.xz``
2. Decompress the zen diff using xz 
``xz -d zen-4.14.15-f695616ca01b187a24635fe51e10c17dc5bccaa2.diff.xz``
3. Move the uncompressed diff file into the patches folder of the latest kernel
``mv ~/Downloads/zen-4.15.6-b2aeef502aac59383cbab0c7902472e030e37c29.diff void-packages/linux4.15/patches``
4. Open the latest kernel's template into a editor (EG ``void-packages/srcpkgs/linux4.15``)
5. On line 23 (at time of writing) change ``_kernver="${version}_${revision}"`` to ``_kernver="${version}-zen_${revision}"`` (for convince later you can also bump the ``revision=`` by one number)
6. pkg the new configuration, run in void-packages
``./xbps-src pkg linux4.15``
7. You'll be asked some config questions, General rule of thumb, if you don't know what it does, don't change it (or let it default) *generally* most of the options are about zen specfic stuff, such as the CPUI sqeduler(Mu_QSS), or drive sqeduler (BFS) and can be enabled. If you are unsure, you can google it, but I'd still recommend not changing anything unless you **know** what it does. (DON'T ENABLE DEBUG SETTINGS UNLESS SOMEONE TELLS YOU TO)
8. Let it build for awhile, it isn't quick.
9. Once it finishes building (finally) its time to install it.
``xbps-install --repository=hostdir/binpkgs linux4.15``
10. Once installed, revert all changes with ``git revert --hard`` (will reset your entire repository, be careful)
11. Once a new kernel version comes out, run ``git pull -ff`` in the void-packages dir.
12. Rinse and Repeat
