### ISSUE TITLE
wine: wine doesn't find the wine-gecko package

### ISSUE THREAD

**Issue by jarbowski** [voidlinux/void-packages#2831]
wine iexplore https://www.winehq.org
fixme:winediag:start_process Wine Staging 1.7.53 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:ole:CoResumeClassObjects stub
fixme:ntdll:__syscall_NtLockFile I/O completion on lock not implemented yet
fixme:urlmon:InternetBindInfo_GetBindString not supported string type 20
err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
fixme:secur32:schannel_get_mac_algid unknown algorithm 200
fixme:secur32:schannel_get_kx_algid unknown algorithm 12
fixme:wininet:create_cache_entry INTERNET_FLAG_NEED_FILE is not supported correctly
Could not load wine-gecko. HTML rendering will be disabled.
err:mshtml:HTMLDocument_Create Failed to init Gecko, returning CLASS_E_CLASSNOTAVAILABLE
fixme:ole:CoCreateInstance no instance created for interface {00000000-0000-0000-c000-000000000046} of class {25336920-03f9-11cf-8fd0-00aa00686f13}, hres is 0x80040111
fixme:ieframe:handle_navigation_error Navigate to error page
err:ole:CoReleaseMarshalData IMarshal::ReleaseMarshalData failed with error 0x8001011d

wine32bit wine-gecko and wine-mono are installed on my void 64bit machine

**Comment by jarbowski** [comment]
everything is okay since the wine-gecko 2.40 update

**Comment by dominikh** [comment]
Closing this issue as it seems to be resolved.
