### ISSUE TITLE
armv7hf cross toolchain problem

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#2834]
```
$ make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOADADDR=0x00008000 -j16 uImage       
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CC      scripts/mod/empty.o
as: unrecognized option '-EL'
scripts/Makefile.build:258: recipe for target 'scripts/mod/empty.o' failed
make[2]: *** [scripts/mod/empty.o] Error 1
scripts/Makefile.build:403: recipe for target 'scripts/mod' failed
make[1]: *** [scripts/mod] Error 2
Makefile:557: recipe for target 'scripts' failed
make: *** [scripts] Error 2
make: *** Waiting for unfinished jobs....
```

This works with ubuntu cross toolchain.

**Comment by espositom221** [comment]
hi,
if change PATH enviroment i have thie error

    export PATH=/usr/armv7l-linux-gnueabihf/usr/bin/:$PATH

    CC      scripts/mod/empty.o
    MKELF   scripts/mod/elfconfig.h
    HOSTCC  scripts/mod/modpost.o
    as: unrecognized option '--64'
    scripts/Makefile.host:108: recipe for target 'scripts/mod/modpost.o' failed
    make[2]: *** [scripts/mod/modpost.o] Error 1
    scripts/Makefile.build:403: recipe for target 'scripts/mod' failed

**Comment by xtraeme** [comment]
Should be fixed with recent cross-* pkgs, fixed by @chneukirchen
