### ISSUE TITLE
in gcc-4.9.3_2, ar is wrongly installed [armv7l]

### ISSUE THREAD

**Issue by 5paceToast** [voidlinux/void-packages#2846]
Ar is installed into `/usr/bin/armv7l-linux-gnueabihf-gcc-ar`.
Many tools (including libtool) expect it to be available as `armv7l-linux-gnueabihf-ar`.

Discovered while compiling neovim.

Temporary solution (potentially valid full solution as well, nothing wrong with a compat symlink):
`ln -s /usr/bin/armv7l-linux-gnueabihf-gcc-ar /usr/bin/armv7l-linux-gnueabihf-ar`

**Comment by 5paceToast** [comment]
Applies to ranlib as well (exactly the same situation).

**Comment by xtraeme** [comment]
```
[juan@leysa ~]$ xbps-query -Rf cross-armv7l-linux-gnueabihf|egrep '/usr/bin/arm.*(ar|ranlib)'
/usr/bin/armv7l-linux-gnueabihf-ranlib
/usr/bin/armv7l-linux-gnueabihf-gcc-ar
/usr/bin/armv7l-linux-gnueabihf-gcc-ranlib
/usr/bin/armv7l-linux-gnueabihf-ar
[juan@leysa ~]$
```

Both ar and ranlib are installed correctly (from binutils) and the gcc variants as well (gcc-xxx). Can't see what's the issue.

**Comment by 5paceToast** [comment]
Void (in my case) is on an armv7l system (Raspberry Pi 2).

Probably should have specified that it isn't a cross package, but rather the native variant.

```sh
toast@toast-rpi ~ $ xbps-query -f gcc | egrep '/usr/bin/arm.*(ar|ranlib)'
/usr/bin/armv7l-linux-gnueabihf-gcc-ar
/usr/bin/armv7l-linux-gnueabihf-gcc-ranlib
toast@toast-rpi ~ $ 
```

**Comment by xtraeme** [comment]
Fixed, thanks :+1:

**Comment by 5paceToast** [comment]
No problem :+1: :)
