### ISSUE TITLE
Package request: ripit

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2861]
Homepage: http://www.suwald.com/ripit/about.php
Distfile: http://suwald.com/ripit/ripit-3.9.0.tar.bz2

I'm no good at perl and packaging perl scripts. Can someone package it for me?

**Comment by chneukirchen** [comment]
Does this do something "abcde" which we already have doesn't?

**Comment by pullmoll** [comment]
I haven't checked. I didn't know abcde until now and will give it a try.

**Comment by pullmoll** [comment]
abcde works ok for me.
