### ISSUE TITLE
freetype: enable subpixel rendering

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#2864]
AFAIK, Microsoft patents for subpixel rendering are expired and many distributions are shipping freetype with the feature enabled. It's a simple diff:

    --- include/freetype/config/ftoption.h.orig	2015-10-30 21:51:44.619963988 +0100
    +++ include/freetype/config/ftoption.h	2015-10-30 21:51:51.505045118 +0100
    @@ -92,7 +92,7 @@
       /* This is done to allow FreeType clients to run unmodified, forcing     */
       /* them to display normal gray-level anti-aliased glyphs.                */
       /*                                                                       */
    -/* #define FT_CONFIG_OPTION_SUBPIXEL_RENDERING */
    +#define FT_CONFIG_OPTION_SUBPIXEL_RENDERING
     
     
       /*************************************************************************/

**Comment by gregf** [comment]
:+1: The patents expired a year or two ago, and debian is shipping with this enabled now.

**Comment by xtraeme** [comment]
https://bugs.archlinux.org/task/35274

Resuming: enabling this by default as Arch did was rejected by upstream, and enabling subpixel rendering made some fonts render even worse than using defaults.

:-1:

**Comment by sramov** [comment]
Not if you configure it properly:

    <?xml version="1.0"?>
    <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
    <fontconfig>
      <match target="font">
        <edit mode="assign" name="antialias">
          <bool>true</bool>
        </edit>
        <edit mode="assign" name="autohint">
          <bool>false</bool>
        </edit>
        <edit mode="assign" name="hinting">
          <bool>true</bool>
        </edit>
        <edit mode="assign" name="hintstyle">
          <const>hintfull</const>
        </edit>
        <edit mode="assign" name="lcdfilter">
          <const>lcddefault</const>
        </edit>
        <edit mode="assign" name="rgba">
          <const>rgb</const>
        </edit>
      </match>
    </fontconfig>

**Comment by chneukirchen** [comment]
Obsoleted by freetype-2.7.

**Comment by stobenski** [comment]
We still need ``FT_CONFIG_OPTION_SUBPIXEL_RENDERING`` in freetype-2.7 for subpixel rendering. Without it you will have grayscale only and none of ``truetype:interpreter-version=*`` options will help you.

**Comment by chneukirchen** [comment]
Hm, the interpreter-version change the "slurryness", but you are right that only grayscale-rendering is used. Perhaps that's why it looks like crap.
