### ISSUE TITLE
Package request: rinse

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#2876]
http://anonscm.debian.org/cgit/collab-maint/rinse.git/

Utility to bootstrap rpm based distributions: like debootstrap but for rpm based distros.

**Comment by maxice8** [comment]
Hope i didn't took too long.

**Comment by maxice8** [comment]
@pullmoll this can be closed

**Comment by pullmoll** [comment]
Closing, see https://github.com/voidlinux/void-packages/commit/d34ad7264e30bce797287d987ebbcaf2cd1df037
