### ISSUE TITLE
drbd-utils: checksum changed + cross is broken

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2880]
The checksum of the distfile changed without the version also being updated.

As a measure to cure such situations, I implemented a new variable `obsolete_checksum="..."` which explicitly deletes a specific `sha256` digest and its hard links from the file cache.

However, the package now
+ needs libxslt or to be more specific the binary `xsltproc`
+ does no longer cross compile, because `drbdsetup` is compiled for the target arch

See #2878

**Comment by xtraeme** [comment]
Fixed by @pullmoll
