### ISSUE TITLE
Package request: Ted

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#2888]
http://www.nllgg.nl/Ted/

I would make my own template but I honestly can't figure out how to make them

**Comment by samuelchodur** [comment]
I'm working on a template for this, but I am getting an error thrown that I can't figure out. Many *.c files have a line: "#include <appDebugon.h>" which is causing: "fatal error: appDebugon.h: No such file or directory".

The header referenced is located in 'builddir/Ted-2.23/include', but I am unsure on how to get it to be recognized. If you comment out that include directive, compilation moves on, but that doesn't seem the correct way to handle this.

I am not sure if this is a problem that can be solved in the template file, or if it is something the author of Ted needs to address.

**Comment by pullmoll** [comment]
Try adding `CFLAGS="-I./include"` in the body of `template`. Perhaps also `CXXFLAGS="${CFLAGS}"`, depending on whether or not c++ / g++ is used.
