### ISSUE TITLE
Broken Package: valadoc-git

### ISSUE THREAD

**Issue by DaveDavenport** [voidlinux/void-packages#2895]
valadoc-git package is currently uninstallable as it looks for libvala-0.28  so file. The current version of libvala is 0.30.  A rebuild of the package would be sufficient to fix this (tested).

Is there a way to make the template in a way it triggers a rebuild when vala-devel updates?

Error:
```
valadoc-git-20150113_2: broken, unresolvable shlib `libvala-0.28.so.0'
````

**Comment by xtraeme** [comment]
There's no way currently, but you can get what packages link to a specific shared library with xbps-query(1):

`$ xbps-query -Rs libvala -p shlib-requires`

Fixed in f51907f

Thanks
