### ISSUE TITLE
Conflict during update

### ISSUE THREAD

**Issue by paddy-garcia** [voidlinux/void-packages#2928]
When i'm trying to do xbps-install -Syu I get this error:

Found inetutils-whois-1.9.4_4 (update) in repository http://repo.voidlinux.eu/current
Found whois-5.2.10_2 (update) in repository http://repo.voidlinux.eu/current
CONFLICT: inetutils-whois-1.9.4_2 with whois-5.2.10_2 in transaction
Transaction aborted due to conflicting packages.

**Comment by xtraeme** [comment]
Update to xbps-0.50 and let me know if you can still reproduce it.

**Comment by biopsin** [comment]
After update to xbps-0.50 started to suffer same error:
CONFLICT: nvidia-352.55_2 with installed pkg xorg-server-1.17.4_2 (matched by xserver-abi-video>19)
Transaction aborted due to conflicting packages.

**Comment by xtraeme** [comment]
Fixed: https://github.com/voidlinux/void-packages/commit/588e13c6f1a111d697baf551db664317e13ca537

Thanks!
