### ISSUE TITLE
alsa update to 1.1.0 breaks steam and games

### ISSUE THREAD

**Issue by lemmi** [voidlinux/void-packages#2949]
https://gist.github.com/anonymous/8aad53c56b6d602c7dca

downgrading to 1.0.29 fixed the problem.

**Comment by xtraeme** [comment]
Downgrading just alsa-lib ?

**Comment by lemmi** [comment]
I downgraded 
> alsa-lib
> alsa-lib-32bit
> alsa-plugins-jack
> alsa-utils
this was everything I had installed with alsa in the name. my guess is alsa-lib would be enough.

**Comment by pullmoll** [comment]
I also had no sound in any X11 application after the upgrade of alsa-lib.

Starting the (new?) alsa service fixed the problem: `ln -sv /etc/sv/alsa /var/service`

**Comment by lemmi** [comment]
i had no problem with that. mpv, firefox, mpd were still working.

**Comment by pullmoll** [comment]
Ok, I thought it might be related. I don't use steam.

**Comment by lemmi** [comment]
so it's a steam problem, i'm closing this.
https://github.com/ValveSoftware/steam-for-linux/issues/4139
