### ISSUE TITLE
Package Request: FreeCAD

### ISSUE THREAD

**Issue by karl-nilsson** [voidlinux/void-packages#2955]
Site: http://www.freecadweb.org/
Source: https://github.com/FreeCAD/FreeCAD
Build Instructions (outdated): http://www.freecadweb.org/wiki/index.php?title=CompileOnUnix

> FreeCAD is a parametric 3D modeler made primarily to design real-life objects of any size. Parametric modeling allows you to easily modify your design by going back into your model history and changing its parameters. FreeCAD is open-source and highly customizable, scriptable and extensible.

There are a few dependencies which need to be packaged:
* [xerces-c](https://xerces.apache.org/xerces-c/) - I'm working on this one
* [Coin3d](https://bitbucket.org/Coin3D/coin/)
* [Quarter](https://bitbucket.org/Coin3D/quarter)
* [Pivy](https://bitbucket.org/Coin3D/pivy)
* [pyside-tools](https://github.com/PySide/Tools)

IMHO, it's worth waiting for the release of FreeCAD v0.16, because it replaces SoQt (unmaintained) with Quarter.

Additionally, Coin3D v3.13 requires patching to build, the alternative is waiting for the 4.0 release. Pivy and Quarter depend on Coin3D

**Comment by yopito** [comment]
FYI xerces-c has just been added into void-packages git repo today.

**Comment by karl-nilsson** [comment]
Just out of curiosity, is there any reason why you didn't include any of the configure options in xerces-c? Here's what I've got so far:

https://github.com/karl-nilsson/void-packages/blob/libxerces/srcpkgs/libxerces-c/template

**Comment by yopito** [comment]
I'm not the packager of xerces-c (@pullmoll does), just your notifier ;)

IMHO, the (already) merged packaging of xerces-c uses rather standard options, just for the needs of its dependancy (package enigma, see #3006 )

Last build output of xerces-c package: http://build.voidlinux.eu/builders/x86_64_builder/builds/18826/steps/shell_3/logs/stdio shows:

```
349 configure: Report:
350 configure:   File Manager: POSIX
351 configure:   Mutex Manager: POSIX
352 configure:   Transcoder: icu
353 configure:   NetAccessor: curl
354 configure:   Message Loader: inmemory
```
I don't know if all the possible configure options needs to be available via options  in the xerces-c packaging. 

For FreeCAD, you need specific build options of xerces-c ?

BTW, I see these points in your WIP packaging (but I'm a not yet a packaging expert !):
* both `create_wrksrc=yes` and `post_extract()` are useless 
* `depends` probably don't need to be fed
* `provides` is probably useless too

**Comment by pullmoll** [comment]
@karl-nilsson I don't know if supporting that much of configuration is really needed. Do your requirements for `xerces-c` differ from the dependencies and settings I've chosen?
AFAICT `enigma` is quite unspecific in regards of the actual configuration of `xerces-c`.

You know that having a lot of build options still doesn't allow different packages to have different sets of options for *their version of xerces-c*? There can be only one version with the default settings (optionally per arch) in the repository.

**Comment by karl-nilsson** [comment]
@pullmoll afaik, freecad doesn't have any specific requirements wrt xerces-c.

**Comment by Vaelatern** [comment]
#4270
