### ISSUE TITLE
Catalyst driver fails to build against linux 4.2

### ISSUE THREAD

**Issue by Quickthorpe** [voidlinux/void-packages#2959]
The currently packaged catalyst driver can't be build against the linux 4.2 kernel. It complains about a missing kernel header file (*i387.h*). It compiles just fine against the 4.1 kernel.

This problem was already addressed by the [Manjaro guys](https://forum.manjaro.org/index.php?topic=24756.0). The [problem](https://lkml.org/lkml/2015/5/5/576): a heavy rewrite of some kernel source files starting with the 4.2 kernel. Besides many other related changes, *i387.h* got rewritten to *api/fpu.h*.

There's a [patch provided by philm](https://github.com/manjaro/packages-extra/commit/b331dc0b0a0bbbc44c16260c250194d4845295c8). Can we use it in Void?

**Comment by pullmoll** [comment]
Please report if the fix is applied correctly.

**Comment by Quickthorpe** [comment]
Yes it builds now. Nice!
