### ISSUE TITLE
Package conflict between xorg and nvidia

### ISSUE THREAD

**Issue by AlexKraak** [voidlinux/void-packages#2961]
I get this error.
CONFLICT: nvidia-352.55_3 with installed pkg xorg-server-1.18.0_1 (matched by xserver-abi-video>19_1)
Transaction aborted due to conflicting packages.

**Comment by Duncaen** [comment]
You have to set `xorg-server` and the packages listed with `xbps-query -s xf86-*` on hold with `xbps-pkgdb -m hold $PKG` until nvidia releases an update.
https://twitter.com/VoidLinux/status/664695910484570112

**Comment by AlexKraak** [comment]
When i do `xbps-pkgdb -m hold ` followed by the list of packages nothing seems to happen

**Comment by xtraeme** [comment]
```
# xbps-pkgdb -m hold xorg-server
# xbps-pkgdb -m hold xf86-input-foo
# xbps-pkgdb -m hold xf86-video-foo
```
