### ISSUE TITLE
Package Issue: HPLIP don't work correctly

### ISSUE THREAD

**Issue by KhazAkar** [voidlinux/void-packages#2966]
From running hp-systray from terminal + no icon for it on menu + hplip don't add entry in CUPS
"warning: GUI mode disabled in build.
error: hp-systray requires Qt4 GUI and DBus support. Exiting."

**Comment by pullmoll** [comment]
You can use HPLIP via console only: `hp-setup -h` for help and e.g. `hp-setup -i 192.168.100.99` for an ethernet-connected printer in a local network. Some of the (many) modules required to build the HPLIP GUI are missing in Void Linux. There are some outdated version of packages required and noone took the time to try to package this cruft.

I looked into this myself months ago and sticked up.

Once you configured your printer, you can manage it via CUPS' web interface at localhost:631 in your favorite browser.

**Comment by xtraeme** [comment]
Unexistent issue
