### ISSUE TITLE
missing .so files when installing spotify

### ISSUE THREAD

**Issue by yuy168** [voidlinux/void-packages#2969]
Hello yet again.

=> WARNING: spotify-0.9_8: libgcrypt.so.11 not found in common/shlibs!
=> WARNING: spotify-0.9_8: libgtk-x11-2.0.so.0 not found in common/shlibs!
=> WARNING: spotify-0.9_8: libgdk-x11-2.0.so.0 not found in common/shlibs!

I get this error at the pre-pkg hook, and then install exits. Hopefully this is in the right place. If I need to provide more info please tell me.

**Comment by Duncaen** [comment]
Its just a warning, you can ignore that if there is an error its something else.
If you just want to install spotify you can actually do that by activating the nonfree repository.
```
xbps-install -S void-repo-nonfree
xbps-install -S spotify
```

**Comment by yuy168** [comment]
That's strange, because the program seems to not be installed, which is why I thought this was odd. On further investigation it seems the pkgdb is locked, so perhaps it's installing in the background?

**Comment by Duncaen** [comment]
xbps-src does not install the package, it builds it and stores it in `hostdir/binpkgs/nonfree`.
I guess somehow there is an old process of xbps-src running in the background.

**Comment by yuy168** [comment]
Nevermind, force-reinstalling the repo fixed it.

**Comment by yuy168** [comment]
And thanks  for clarifying that. I should probably read the documentation more thoroughly

**Comment by pullmoll** [comment]
#1 RTFM
#2 Beer
#3 forgot ... errr Acetylaldehyd

**Comment by xtraeme** [comment]
Unexistent issue
