### ISSUE TITLE
99-pkglint: meta package issues

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#2970]
Some templates now generate an error when dependency only parts are to be packaged:
```
=> ERROR: elfutils-0.161_3: PKGDESTDIR is empty and build_style != meta
=> ERROR: elfutils-0.161_3: cannot continue with installation!
```
The same happens for `git-all` where I could fake a `build_style=meta` in the `git-all_package()` function to continue with the install.

**Comment by xtraeme** [comment]
This is how it's expected to work, packages that don't install any files must set `build_style=meta`.
