### ISSUE TITLE
Package Request: mlocate

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#2973]
home: https://fedorahosted.org/mlocate/
source: https://fedorahosted.org/releases/m/l/mlocate/mlocate-0.26.tar.xz

mlocate is a locate/updatedb implementation. The 'm' stands for "merging": updatedb reuses the existing database to avoid rereading most of the file system, which makes updatedb faster and does not trash the system caches as much.

note: Arch's findutils package does not include locate
https://wiki.archlinux.org/index.php/Core_utilities#locate
https://www.archlinux.org/packages/core/x86_64/findutils/files/

**Comment by Duncaen** [comment]
```
# Template file for 'mlocate'
pkgname=mlocate
version=0.26
revision=1
build_style=gnu-configure
configure_args="--program-prefix=m --localedir=/var/lib/mlocate"
hostmakedepends=""
makedepends=""
depends=""
short_desc="Merging locate/updatedb implementation that reuses the database"
maintainer="Duncaen <duncaen@voidlinux.eu>"
license="GPL-3"
homepage="https://fedorahosted.org/mlocate/"
distfiles="https://fedorahosted.org/releases/m/l/mlocate/mlocate-${version}.tar.xz"
checksum=3063df79fe198fb9618e180c54baf3105b33d88fe602ff2d8570aaf944f1263e

alternatives="
 locate:locate:/usr/bin/mlocate
 locate:updatedb:/usr/bin/mupdatedb
 locate:locate.1:/usr/share/man/man1/mlocate.1
 locate:updatedb.8:/usr/share/man/man8/mupdatedb.8
 locate:updatedb.conf.5:/usr/share/man/man5/mupdatedb.conf.5
 locate:mlocate.db.5:/usr/share/man/man5/mmlocate.db.5"
```

**Comment by stpx** [comment]
I did... I'm a little confused on the `findutils` alternatives as well.

**Comment by Duncaen** [comment]
Maybe just add `--program-prefix=f` to `findutils` and put `xargs` and `find` respectively in its own group.
`busybox` provides `xargs` and `find` and could be added as alternatives too.
