### ISSUE TITLE
Upgrade request: claws-mail 3.13.0 (11-October-2015)

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#2975]
Please upgrade the *existing* **claws-mail** package (originally requested in issue #975) to the new 3.13.0 (11-October-2015) version.  You can download it here: http://www.claws-mail.org/releases.php :bowtie: Thanks!

**Comment by stpx** [comment]
claws-mail updated to 3.13.0. 2272ca1b576548d9184df940a3a47c296f1f00b6

**Comment by sunaku** [comment]
Wonderful! :smiley_cat:  Next time I'll try submit a PR to save you some time, thanks. :bow:
