### ISSUE TITLE
Package Request: lilypond

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#2987]
http://lilypond.org/

> LilyPond is a music engraving program, devoted to producing the highest-quality sheet music possible. It brings the aesthetics of traditionally engraved music to computer printouts. LilyPond is free software and part of the GNU Project.

**Comment by Vaelatern** [comment]
Dependency list fails during configure...

`ERROR: Please install required programs:  International New Century Schoolbook fonts (make sure the fc-list utility can see them, or use --with-ncsb-dir) mf-nowin mf mfw mfont mpost kpsewhich metapost CTAN package (texlive-metapost) guile-config (guile-devel, guile-dev or libguile-dev package) or guile1-config (guile1-devel package) libguile (libguile-dev, guile-devel or guile-dev package). GUILE-with-rational-bugfix t1asm pkg-config perl gs texi2html dblatex bibtex pdflatex pdfetex pdftex etex epsf.tex lh CTAN package (texlive-lang-cyrillic or texlive-texmf-fonts) pngtopnm convert zip rsync`

The biggest one is it needs texlive stuff. I'm waiting for my computer to get past `=> lilypond-2.18.2_1: installing target dependency 'texlive-bin-2015_1' ...` 20 minutes and waiting.

**Comment by maxice8** [comment]
solved by 6d92c2b2cff3b19fc3b61068a593d97d112b3448 and ec8e5b7d97da86ef32636b4b74297f16924b31f1 

@the-maldridge
