### ISSUE TITLE
sxhkd out of sync with bspwm

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#2990]
please update sxhkd (and keep in sync with bspwm)

the example sxhkdrc with bspwm is for a newer version of sxhkd

specifically the pointer bindings fail

	super + button{1-3}
	    ; bspc pointer -g {move,resize_side,resize_corner}
	
	super + @button{1-3}
	    bspc pointer -u

in contrast to the old syntax

	super + button{1-3}
	    bspc pointer -g {move,resize_side,resize_corner}
	
	super + !button{1-3}
	    bspc pointer -t %i %i
	
	super + @button{1-3}
	    bspc pointer -u

**Comment by tonkazoid** [comment]
https://github.com/baskerville/bspwm/commit/803392e98510684d7b5a3d15f19bc3854d58b267
this was added Apr 6. The latest bspwm version is 0.9 from Mar 20.
Either try to get baskerville to release a new version or us this https://github.com/baskerville/bspwm/blob/a1dc440d7ddee0de1c3fb7b09fd2c504a9e3dffd/examples/sxhkdrc (example from Jan 21, 2014)

**Comment by dicktyr** [comment]
I'm sorry
I was confused
(running two systems, different versions, sleep deprivation...)

it looks like they are indeed in sync
