### ISSUE TITLE
xbps-src fails with Makefile variables and blackquotes shell ?

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#2992]
While packaging application PasswordSafe with glibc on i686, I've encoutered a really weird comportment on the way Makefile's variables are handled.
Sorry for this long post, try to detail as much as possible what's happening.

* pwsafe-0.97BETA/src/ui/wxWidgets/Makefile contains (only relevant lines):
```
132 LIBS=`$(WX_CONFIG) --debug=no --unicode=yes --inplace --libs` -lcore -los -lcore -luuid -lXtst -lX11 -l$(YBPERS_LIBS)
142 LDFLAGS:=$(LIBS) -L$(LIBPATH) $(LINKERFLAGS) $(LDFLAGS)
158 LDFLAGS:=$(LIBS) -L$(LIBPATH) $(LINKERFLAGS) $(XERCESLIBFLAGS) $(YBPERS_LIBPATH_FLAGS) $(LDFLAGS)
159 CPPFLAGS:=$(CXXFLAGS) $(CPPINC) $(GCCFLAGS) $(DEBUGFLAGS) $(OPTFLAGS) $(WARNINGFLAGS) $(XERCESCPPFLAGS) $(YUBIFLAGS) $(CPPFLAGS)

212 $(OUTPUTPATH)/$(PROGRAM):	$(OBJECTS) $(LIBRARIES)
213          $(CXX) -o $@ $(OBJECTS) $(LDFLAGS)
214
215 $(OBJECTPATH)/%.o : %.cpp
216         $(CXX) -c -o $@ $(CPPFLAGS) $<

```

* xbps-src fails to build:
```
$ ./xbps-src zap
$ ./xbps-src binary-bootstrap
$ ./xbps-src -f pkg passwordsafe
[...]
g++ -std=c++11 -fPIC -Wall -I.. -DLINUX -std=c++11 -fPIC -Wall -I.. -DLINUX     -O0 -g -ggdb -DUNICODE -DUSE_XML_LIBRARY=XERCES -DWCHAR_INCOMPATIBLE_XMLCH -D_DEBUG -DDEBUG -O -DUNICODE -DUSE_XML_LIBRARY=XERCES -DWCHAR_INCOMPATIBLE_XMLCH -DNDEBUG -c XML/Xerces/XSecMemMgr.cpp -o ../../obj/unicoderelease/core/XML/Xerces/XSecMemMgr.o
g++ -o GCCUnicodeRelease/pwsafe GCCUnicodeRelease/passwordsafeframe.o \
       [...] \
       GCCUnicodeRelease/SelectionCriteria.o  \
       -Wl,--as-needed -Wl,-z,relro 
GCCUnicodeRelease/passwordsafeframe.o: In function `PasswordSafeFrame::OnExitClick(wxCommandEvent&)':
passwordsafeframe.cpp:(.text+0x190): undefined reference to `wxWindowBase::Close(bool)'
```

* *BUT* a manual make within the xbps-src's chroot produces a different behaviour and achieve the build:
```
$ ./xbps-src chroot
=> Using `/build/packages/hostdir/binpkgs/passwordsafe.local' as local repository.
[yopito@/build/packages/masterdir /]$ cd builddir/pwsafe-0.97BETA/
[yopito@/build/packages/masterdir pwsafe-0.97BETA]$ make rpmbuild
[...]
g++ -c -o GCCUnicodeRelease/SelectionCriteria.o -std=c++11 -I/usr/lib32/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -DUNICODE -DNDEBUG -I../.. -fPIC  -O -Wall -DUSE_XML_LIBRARY=XERCES -DWCHAR_INCOMPATIBLE_XMLCH SelectionCriteria.cpp
g++ -o GCCUnicodeRelease/pwsafe GCCUnicodeRelease/passwordsafeframe.o \
       [...] \
       GCCUnicodeRelease/SelectionCriteria.o  \
       `/usr/bin/wx-config-3.0 --debug=no --unicode=yes --inplace --libs` -lcore -los -lcore -luuid -lXtst -lX11 -lykpers-1 -L../../../lib/unicoderelease  -lxerces-c -L../../../lib/unicoderelease `/usr/bin/wx-config-3.0 --debug=no --unicode=yes --inplace --libs` -lcore -los -lcore -luuid -lXtst -lX11 -lykpers-1 -L../../../lib/unicoderelease  
building unicoderelease all
[...]
```

So building via xbps-src make variable expansion behaves differently: For some reason, Makefile's variables are not evaluated or can't be used.

* I've tried to replace backquotes expression with `"$(shell command)"` without any difference.

* I've started with a new hostdir/masterdir, but it made no differences.

So does this problem might be related to xbps-src build system ?

Thanks for any comment, thought or advice.

**Comment by pullmoll** [comment]
What happens if you run make with the same parameters that xbps-src uses?
This will be `${makejobs}`, `${make_build_args}` and `${make_build_target}`, which depend on the build_style and your `etc/conf` settings.

You could see them if you add a `do_build()` function to your template like
```
do_build() {
        echo "make ${makejobs} ${make_build_args} ${make_build_target}"
        make ${makejobs} ${make_build_args} ${make_build_target}
}
```

The lines 142 and 158 in your Makefile use `declaration time expansion` of variables with the `:=` assignment. I don't know for sure what happens, if the make parameters contain `LDFLAGS=...`. It may be the that command line parameters take precedence over the internal variables and thus `LDFLAGS` does not contain `$(LIBS)` etc.

**Comment by yopito** [comment]
Thanks for your reply and many thanks for your thoughts .

**If** I add the definition of `do_build()` in my template as you suggested, echo's output is (only) "`make -j1 rpmbuild`" (as ~ expected) .... and the xbps-src's build succeeds !
(my template is using "`build_style=gnu-makefile`" and "`make_build_args="rpmbuild"`").

So you're probably right regarding the troubles with Makefile's variable expansion. Indeed, I didn't take care before that xbps-src presets some env in `common/build-style/gnu-makefile.sh` (if I understand well): 
```
[...]
do_build() {
        : ${make_cmd:=make}

        ${make_cmd} \
                CC="$CC" CXX="$CXX" LD="$LD" AR="$AR" RANLIB="$RANLIB" \
                CPP="$CPP" AS="$AS" OBJDUMP="$OBJDUMP" CFLAGS="$CFLAGS" \
                LDFLAGS="$LDFLAGS" \
                ${makejobs} ${make_build_args} ${make_build_target}
}
[...]
```
I will investigate more deeply within this week and feedback about this.

**Comment by pullmoll** [comment]
IMHO the Makefile's line 213 should look like
```
         $(CXX) -o $@ $(OBJECTS) $(LDFLAGS) -L$(LIBPATH) $(LIBS) $(LINKERFLAGS) $(XERCESLIBFLAGS) $(YBPERS_LIBPATH_FLAGS)
```
i.e. it should have all libraries and linker paths appended.

The lines 142 and 158 should go away. Then setting `LDFLAGS=...` in the invocation of make won't break the linking stage.

**Comment by yopito** [comment]
With your comments, the GNU make manual and some tests, I feel a little less stupid : I was mixing 2 concepts :
* make's variable definition with command like `$ make VAR1=value1 ...`,
* use of variable from shell's environment  with command like `$ VAR1=value1 make ...`

I'm not clever enough to discuss on xbps-src's choice to redefine make's variable from command-line is the right design or not.
In the other hand, only the passwordsafe's Makefiles are is little weird/silly with it, that is about 1 of 6000 packages ... ;)

But might `void-packages/Manual.md` should warn a little bit about it ?

Anyway, I know what I have to fix now to be xbps-src compliant.
Please close this (non)issue, sorry for the noise.

regards - Pierre

More details about these 2 concepts (what I've saw):

`void-packages/common/build-style/gnu-makefile.sh` uses `make` with this kind of invocation:
```
${make_cmd} ... LDFLAGS="$LDFLAGS" ...
```
which means that the Makefefile's variable `LDFLAGS` is (re)**defined** from command-line (overriden in GNU make's terminology), with the value of the shell variable `$LDFLAGS` in this case.
Then, any define of `LDFLAGS` within a Makefile is simply ignored, this is the way `make` works.
Debug command:
```
$ ./xbps-src chroot
$ cd /builddir/pwsafe-0.97BETA
$ make -p -n LDFLAGS=fooyopito -C src/ui/wxWidgets unicoderelease 
[...]
# command line
LDFLAGS=fooyopito
```


If defining `LDFLAGS` from shell environment, the result is of course complely different:
```
$ ./xbps-src chroot
$ cd /builddir/pwsafe-0.97BETA
$ LDFLAGS=envyopito make -p -n -C src/ui/wxWidgets unicoderelease
[...]
# makefile (from 'Makefile', line 158)
LDFLAGS := `/usr/bin/wx-config-3.0 --debug=no --unicode=yes [...]` \ 
         -lcore -los -lcore -luuid -lXtst -lX11 -lykpers-1 -L../../../lib/unicodedebug \ 
         -lxerces-c -L../../../lib/unicodedebug envyopito
```

overriden in GNU make terminology) from command-line.
So any definition of `LDFLAGS` in `src/ui/wxWidgets/Makefile` is simply ... ignored.

**Comment by xtraeme** [comment]
This is work the `gnu-makefile` build style is supposed to work, overring the vars via `make` arguments.

If that does not work as you've found, you'll need to use custom `do_{build,install}` functions.
