### ISSUE TITLE
Package Request: spim

### ISSUE THREAD

**Issue by avoidr** [voidlinux/void-packages#3012]
http://pages.cs.wisc.edu/~larus/spim.html
https://sourceforge.net/projects/spimsimulator/files/

>spim is a self-contained simulator that runs MIPS32 programs. It reads and executes assembly language programs written for this processor. spim also provides a simple debugger and minimal set of operating system services. spim does not execute binary (compiled) programs.

**Comment by pullmoll** [comment]
See #2932

**Comment by avoidr** [comment]
Sorry, didn't think of searching first.
