### ISSUE TITLE
perl-rename: alternative for rename

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#3017]
another candidate for xbps-alternatives

**Comment by dominikh** [comment]
What other package provides `rename` from perl-rename?

**Comment by dicktyr** [comment]
> What other package provides `rename` from perl-rename? 

util-linux

**Comment by dominikh** [comment]
Ah. But they provide entirely different interfaces. Alternatives are for programs with an identical base-set of functionality and interface. For example, all the awks support the same basic awk syntax and CLI flags. If a package depends on "awk", it could work with gawk or mawk equally. util-linux rename and perl-rename do not share any common interface and aren't alternatives for each other.

**Comment by dicktyr** [comment]
fair enough
thanks
