### ISSUE TITLE
python3.4-sympy broken

### ISSUE THREAD

**Issue by eyedeeemm** [voidlinux/void-packages#3038]
Fix is simple, change the mpmath symlink:
lrwxrwxrwx 1 root root 12 Sep  4 15:08 mpmath -> ../../mpmath
to
lrwxrwxrwx 1 root root 9 Nov 22 15:33 mpmath -> ../mpmath

Not sure if I'm reporting this to the right place but I thought I'd try to chip in

**Comment by asergi** [comment]
d272fe5
