### ISSUE TITLE
Package Request: npm

### ISSUE THREAD

**Issue by paddy-garcia** [voidlinux/void-packages#3048]
https://www.npmjs.com/

A package manager for javascript.

**Comment by 7185** [comment]
From your website:
>The npm command-line tool is bundled with Node.js. If you have it installed, then you already have npm too. If not, go download Node.js. 

What's the point of an npm package? Is the `nodejs` package not suitable for you?

**Comment by paddy-garcia** [comment]
Ops, my bad! Debian had a stand alone package and I didn't see that npm is already in nodejs package.
