### ISSUE TITLE
Runit: ntpd broken

### ISSUE THREAD

**Issue by jarbowski** [voidlinux/void-packages#3052]
Had to uninstall ntp, rm /etc/ntp.conf, rm /etc/sv/ntpd, rm /etc/sv/isc-ntpd and reinstall ntp to make it work properly. Now, ntpd is a symlink to isc-ntpd.

**Comment by Duncaen** [comment]
`xbps-alternatives -s ntp` or `xbps-pkgdb ntp` would have done it, if you dont have xbps-alternatives you have to update.

**Comment by jarbowski** [comment]
Ok, some kind of possible. Don't know the goals of the distro but if this thing is known, it would have been in a text log after upgrading. Am I wrong?

**Comment by Duncaen** [comment]
Normally it should be done automatically after the ntp update that introduced it.

**Comment by jarbowski** [comment]
ok, so it failed.

**Comment by xtraeme** [comment]
no details no bug
