### ISSUE TITLE
pulseaudio overriding alsactl restore

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#309]
It appears that the problem I have with alsa not restoring mixer settings for my secondary sound card is caused by pulseaudio, either overriding alsactl restore or preventing it from working. I found this work-around on the internet:

restore_alsa()
{
 while [ -z "$(pidof pulseaudio)" ]; do
  sleep 0.5
 done
 sudo alsactl -f /var/lib/alsa/asound.state restore 
}
restore_alsa &

This I have in my .bashrc but only works when I start X, so maybe better in .xinitrc

**Comment by thypon** [comment]
was this fixed in PA 5?

**Comment by nkcyham** [comment]
Hi,

Only libpulseaudio is installed on my desktop so I don't really know
if the problem still exists.

Thank you.

--
Best Regards
Neoklis - Ham Radio Call:5B4AZ
http://www.5b4az.org/

 was this fixed in PA 5?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by cr6git** [comment]
@ghost what's the point of adding links to Hamradio here? 

Seriously, we are at `pulseaudio-11.1` now, it's time to close this.

**Comment by Coding-Doctors** [comment]
@cr6git in regards to the lower portion of @ghost's message, it looks to be their signature for their email at the time, since they replied to this issue via. email, a feature of github.

**Comment by cr6git** [comment]
@Coding-Doctors it was humorous: I know ghosts doesn't exist anyway. 😉 

I started to review all the old issues, to see if the problems are solved or not.
