### ISSUE TITLE
Add Swift compiler packages

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#3113]
https://swift.org/source-code/#core-libraries

**Comment by chneukirchen** [comment]
Source is not yet up and the binaries seem to use "llvm 3.8", so I guess this will take some time.

Interesting tho.

**Comment by radare** [comment]
Everything is in GitHub now: https://github.com/apple/swift

**Comment by radare** [comment]
Instructions to build on void:
```
xbps-install ninja
 git clone https://github.com/apple/swift.git swift
 git clone https://github.com/apple/swift-llvm.git llvm
 git clone https://github.com/apple/swift-clang.git clang
 git clone https://github.com/apple/swift-lldb.git lldb
 git clone https://github.com/apple/swift-cmark.git cmark
 git clone https://github.com/apple/swift-llbuild.git llbuild
 git clone https://github.com/apple/swift-package-manager.git swiftpm
 git clone https://github.com/apple/swift-corelibs-xctest.git
 git clone https://github.com/apple/swift-corelibs-foundation.git
cd swift
utils/build-script -j12
```

**Comment by radare** [comment]
For me (hexacore box) took about 2-3h and required 25GB of disk and 20GB of ram to build. but at least it's confirmed that swift build fine in void :P

**Comment by jannisch** [comment]
@radare this package request is pretty old now but could you create it if you already have some experience with swift? I'd love to try swift but not everyone has got 20GB of RAM :smiley:

**Comment by radare** [comment]
Swift 2.2 has been released today and there are packages for ubuntu/debian. So i guess we can grab the build recipe and the release tarballs now instead of using the git and build without debug symbols will probably take less memory

**Comment by radare** [comment]
https://github.com/apple/swift/releases/tag/swift-2.2-RELEASE

**Comment by radare** [comment]
https://github.com/apple/swift-corelibs-foundation/releases/tag/swift-2.2-SNAPSHOT-2015-12-22-a

**Comment by radare** [comment]
I read a blog post bulding it in rpi. So i guess this has been improvied. I have zero time for doing anything roght now. So if unwanna get it go for it

**Comment by radare** [comment]
Here's the archlinux package:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=swift-language

**Comment by radare** [comment]
wip here https://github.com/radare/void-packages/blob/swift/srcpkgs/swift/template

**Comment by radare** [comment]
see https://github.com/voidlinux/void-packages/pull/3893

it's working for me :)

**Comment by jannisch** [comment]
Thanks, I will try this too. Travis just failed.

**Comment by radare** [comment]
yeah, but i dont know why, maybe a race condition caused by the symlinks? also it will be good to know if that thing builds with musl and arm

**Comment by jannisch** [comment]
I have the same issue, it executes `utils/build-script-impl` from `builddir/swift/` which does not exist instead of `builddir/swift-swift-2.2-RELEASE/`
Have you run a `./xbps-src clean`?

**Comment by jannisch** [comment]
This symlink is wrong: `swift -> swift-swift-swift-2.2-RELEASE`.
Submitted a fix [here](https://github.com/radare/void-packages/pull/2/filesl), hope this is correct because I don't know bash too well.

**Comment by radare** [comment]
thanks! it worked for me because i already did that symlink  in one of many run attempts O:) should be fine now

**Comment by jannisch** [comment]
You're welcome. Considering arches: i686 is only beeing used for legacy applications today, I think we don't need to support it. Apple does not use glibc at all in their operating systems, can you try a cross build for `x86_64-musl`?

**Comment by Vaelatern** [comment]
Void supports i686, x86_64, and various arm platforms.

**Comment by jannisch** [comment]
@Vaelatern do you mean i686 needs to be supported, too? I only wanted to cover this particular package in my statement. Moreover, the Travis builds like [this one](https://travis-ci.org/voidlinux/void-packages/jobs/118109798) don't work on i686 yet as desired and I suspect that swift is only targetted at 64-bit architectures.
Or if you want to stress that there are several arm platforms as well.. I did not mention them because I don't know so much about arm or on which arm platforms swift could work.

**Comment by Vaelatern** [comment]
Unless there is a very good reason for a particular package to not work on a particular platform, the expectation is any package will work on any platform. As such, until proven otherwise, aspire to the standard of the package working on any platform Void supports.

**Comment by jannisch** [comment]
Thanks, I misunderstood the contributing guide. It says the following:
> Once you successfully build the package at least on x86 (building it on armv* is recommended too) you can start a pull request.

I think we should include the information of your last comment there.

One thing I noticed is that the [[WIP] Openstack](https://github.com/voidlinux/void-packages/pull/3641) pull request also includes a package called `swift` (it is an Openstack component).

**Comment by radare** [comment]
Yes there are two swift thats why debian named the pkg swift-2.2

The same happened with node and debian is naming the bin nodejs which sucks hard

Imho the swift lang will be more important than the other swift so if at any point we package the other one we can change the name of the other. Most ppl will expect to get the compiler.

Same happens with go, that is not a game what most ppl will expect to get installed

**Comment by jannisch** [comment]
My thoughts about this:
- it's hard to decide about future potential because both are young and have their competitors (OpenNebula and golang)
-  OpenStack is definitely built for datacenters and enterprise environments, Void is not because it does not provide backports due to its rolling release model.
- if every OpenStack package was named `openstack-...` it would also be easier to search them

After all I would prefer to give this compiler package the `swift` name.

**Comment by radare** [comment]
+1

On 25 March 2016 at 02:48, Jannis Christ <notifications@github.com> wrote:

> My thoughts about this:
>
>    - it's hard to decide about future potential because both are young
>    and have their competitors (OpenNebula and golang)
>    - OpenStack is definitely built for datacenters and enterprise
>    environments, Void is not because it does not provide backports due to its
>    rolling release model.
>    - if every OpenStack package was named openstack-... it would also be
>    easier to search them
>
> After all I would prefer to give this compiler package the swift name.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/voidlinux/void-packages/issues/3113#issuecomment-201105184>
>



-- 
--pancake

**Comment by Vaelatern** [comment]
The other package doesn't exist yet, feel free to give whatever name you like to this one. Notice that there are two packages named `slurm`, on is `slurm-wlm` because it had to change name to  The other will adapt. I just disagree with you on a particular point: OpenStack is definitely built for datacenters. Other than a limited number of tools so far, there is no reason Void couldn't be there too.

**Comment by jannisch** [comment]
@Vaelatern this issue is solved now.
