### ISSUE TITLE
ibus-anthy doesn't show up in ibus.

### ISSUE THREAD

**Issue by rogerbraun** [voidlinux/void-packages#3166]
After installing ibus-anthy 1.5.7_1, it doesn't show up in the ibus preferences and can't be added. Reverting to ibus-anthy 1.5.6_1 resolves the problem.

**Comment by 7185** [comment]
Might be related to what I noted here: https://github.com/voidlinux/void-packages/commit/5389061641d5fdbe1febdd28ec7a9afa062b6859#commitcomment-12419190
