### ISSUE TITLE
firefox: enable gtk3 build option by default

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#3189]
According to [this bugreport](https://bugzilla.mozilla.org/show_bug.cgi?id=1227024#c0) gtk3 support is ready for shipping but has been disabled to keep update easy.

We do not have this problem in Void so I guess it is safe get rid of gtk2 in ff.

**Comment by Gottox** [comment]
Let me clarify: firefox still links against gtk2 AND gtk3, so consider this lower priority.

**Comment by radare** [comment]
+1 for gtk3
