### ISSUE TITLE
nodejs package uses LTS version, stable version is not packaged.

### ISSUE THREAD

**Issue by rogerbraun** [voidlinux/void-packages#3193]
I saw that the nodejs package does not use the regular stable version (5.3) but the older LTS (4.x) branch. Simply updating to the new version does work, but maybe it would be better to have two packages, one for the LTS branch and one for the stable version.

**Comment by Gottox** [comment]
Reason is that our libressl patch hasn't been ported t node-js-5.x yet. Once that works, we update to current stable. But we aren't in a hurry, node-4 is supported for some time.

If you rely on node-5 features use tools like nvm.

**Comment by ebfe** [comment]
stable is now in the repo
