### ISSUE TITLE
Package Request: ttf-indic-fonts

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#3196]
This package provides fonts for Indian languages.  :man_with_turban:

Please port from Arch Linux at https://www.archlinux.org/packages/extra/any/ttf-indic-otf/

It's a simple tarball extraction into `/usr`, no binaries to compile and no dependencies. :runner:

**Comment by Duncaen** [comment]
added in 172542d, couldn't find the license to verify that its GPL like the arch PKGBUILD mentions.
Do you maybe know more about it?

**Comment by sunaku** [comment]
:+1: Thanks, yes it's GPL. :statue_of_liberty: There is an overall `gpl.txt` file for the entire package and further `README.*` files for each font under the `indic/OpenType/doc/` folder inside the source tarball located at http://www.indlinux.org/downloads/files/indic-otf-0.2.tar.gz

**Comment by sunaku** [comment]
One more thing: could we mention "fonts" in the package name (e.g. "indic-**fonts**-otf" or better yet "indic-**fonts**" :sparkles:)?  I ask because all other font packages mention "font" in their name. :necktie:

**Comment by Duncaen** [comment]
Normally we stick to the upstream name.
@xtraeme what do you think, should I add a prefix/suffix?

**Comment by sunaku** [comment]
:memo: I would prefer a complete rename (to just "indic-fonts") over adding a prefix/suffix.
