### ISSUE TITLE
Be able to open jnlp files

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#3226]
Seems it's a `javaws` program that doesn't seem to come with OpenJDK. Perhaps it comes with icedtea.

Java Web Start. Definitely packaged with `icedtea-web`.

**Comment by Vaelatern** [comment]
Okay, I'm packaging icedtea.

**Comment by phalenor** [comment]
+1

**Comment by chneukirchen** [comment]
Please use the voting feature an don't spam +1.

**Comment by dominikh** [comment]
You could also just use the Oracle JRE.

**Comment by Vaelatern** [comment]
I never packaged icedtea-web.
Thankfully #4715 has it, and has it merged.
