### ISSUE TITLE
Package Request: pasystray

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#3244]
[PulseAudio System Tray](https://github.com/christophgysin/pasystray)
> pasystray allows setting the default PulseAudio source/sink and moving streams on the fly between sources/sinks without restarting the client applications.

I was able to successfully build & install this software from source manually, but creating a Void package for it has been very challenging. :cold_sweat:  In fact, this is as far as I've gotten before giving up :confounded: and I hope it helps!

```sh
# Template file for 'pasystray'
pkgname=pasystray
version=0.5.2
revision=1
build_style=configure
hostmakedepends="pkg-config intltool automake"
makedepends="gtk+3-devel pulseaudio-devel"
short_desc="PulseAudio System Tray"
maintainer="Juan RP <xtraeme@voidlinux.eu>"
license="GPL-2"
homepage="https://github.com/christophgysin/pasystray"
distfiles="${homepage}/archive/${pkgname}-${version}.tar.gz"
checksum=0cb574843bd7883c51291de03cca237e53a89821d6965c8413dd89e42d8ffc3e

post_extract() {
  # the downloaded archive is doubly named: pasystray-pasystray-0.5.2
  mv "$(dirname "$wrksrc")/${pkgname}-$(basename "$wrksrc")" "$wrksrc"
}

pre_configure() {
  ./bootstrap.sh ${configure_args}
}
```

**Comment by stpx** [comment]
Closed via 416674cf870a31aa49690923a3719426bcc4b4fa.
