### ISSUE TITLE
Package request: N1 email client

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#3252]
https://www.nylas.com/N1

it's an electron-based app, so it depends on nodejs and the electron-bin or electron-prebuilt packages

**Comment by radare** [comment]
There are binary packages for debian and redhat now https://invite.nylas.com/download/

**Comment by Vaelatern** [comment]
Do they not offer source?

**Comment by radare** [comment]
of course, as everything in github:

https://github.com/nylas/N1 <https://github.com/nylas/N1>

and they make pretty frequent tarball releases:

https://github.com/nylas/N1/releases <https://github.com/nylas/N1/releases>

**Comment by chneukirchen** [comment]
Upstream dead:

> Nylas Mail was officially sunset in August and re-licensed under MIT. Nylas is no longer maintaining
> Nylas Mail, and 2.0.31 is the last public release.
