### ISSUE TITLE
screenfetch: output can't detect OS correctly

### ISSUE THREAD

**Issue by rtlanceroad** [voidlinux/void-packages#3255]
if you guys run screenfetch in terminal, you will find the following:

OS: Unknown Version: 1.0

This is just because --> lsb_release . the code in screenfetch

distro_detect=( $(lsb_release -sirc) )

Hopefully someone can fix it.

**Comment by stpx** [comment]
`screenFetch` needs to be patched as well. (#3256)

**Comment by stpx** [comment]
Closed via a48f9d61a014b9b85c2472c850fdf947f418ff67 and   321218c22ec9b55b342237df990874f98f76acf1.

**Comment by rtlanceroad** [comment]
I dont think it works(screenFetch-3.7.0_4). look at my screenshot:

https://scrot.moe/image/aSBl

it makes thing worse....
cc @stpx @pullmoll

**Comment by pullmoll** [comment]
I think my part of the story already has all I can do: make lsb_release support multiple options after one dash (-).

**Comment by pullmoll** [comment]
We have two different strings in lsb_release:
```
-i (identifier) is "VoidLinux"
-d (description) is "Void Linux"
```
The latter contains a blank, the former doesn't. I think screenfetch should be using the `identifier` in its case/esac switches.

**Comment by rtlanceroad** [comment]
@stpx Thanks for the typo fix, now it works.
