### ISSUE TITLE
libvirt seems broken with musl

### ISSUE THREAD

**Issue by ohanar** [voidlinux/void-packages#3333]
I am unable to connect to libvirtd from virsh on an x86_64-musl install:
```
# libvirtd
2016-01-08 00:26:52.014+0000: 19772: info : libvirt version: 1.2.21
2016-01-08 00:26:52.014+0000: 19772: error : virNetSocketReadWire:1595 : End of file while reading data: I/O error
---
$ virsh -c qemu:///system
error: failed to connect to the hypervisor
error: Unable to encode message header
```
If needed, here is libvirtd with debugging enabled: https://gist.github.com/ohanar/0a6ae79f22878ff69b84.

**Comment by thypon** [comment]
`portablexdr` isn't working so good actually. libvirtd works, the virsh component and all the xdr connections are flaky, instead.

**Comment by ohanar** [comment]
You're right. I successfully got things working when building against libtirpc (which needed some more patching to actually work). I'll clean things up and submit a pull request or two tomorrow.

**Comment by ohanar** [comment]
See #3340 and #3341
