### ISSUE TITLE
Recent -Syu update broke wpa_supplicant runit files

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#3343]
Hi

I carried out an xbps-install -Syu yesterday but then I could not connect by wifi to the internet. The problem was that runit's service configs for wpa_supplicant ("config" and "run") specify the wifi interface as wlan0 while it is wlp2s0. I edited these files and it now connects, but what I am not sure how it worked previously, as I don't remember ever having to edit runit service files. Perhaps I am missing something?

**Comment by Duncaen** [comment]
For some reason `dhcpcd` changed its default and deactivated the `wpa_supplicant` hook by default.
`ln -s /usr/share/dhcpcd/hooks/10-wpa_supplicant /usr/libexec/dhcpcd-hooks/`

The `wpa_supplicant` runit servers is conflicting with `dhcpcd` if the `wpa_supplicant` hook is activated.
And to change the interface in the `wpa_supplicant` service, you just change `WPA_INTERFACE=wlp2s"` in the `conf` file.

**Comment by nkcyham** [comment]
OK thanks Duncaen!

**Comment by sunaku** [comment]
Confirmed. :+1: Adding a `WPA_INTERFACE=wlp1s0` line to the `/etc/sv/wpa_supplicant/conf` file and restarting the wpa_supplicant service fixed the problem for me. :smiley_cat:
