### ISSUE TITLE
asunder: missing dependency "cdparanoia" + missing suggested programs like flac

### ISSUE THREAD

**Issue by Varkolac** [voidlinux/void-packages#3345]
The website (http://littlesvr.ca/asunder/) lists the following dependencies for asunder, however cdparanoia does not get installed with it nor does xbps suggest the optional packages:

Linux
GTK 2.4 or greater
Libcddb 0.9.5 or greater
Cdparanoia
LAME (optional for MP3 support)
Vorbis-Tools (optional for Ogg Vorbis support)
FLAC (optional for FLAC support)
Opus (optional for Opus support)
WavPack (optional for WavPack support)
mpcenc (optional for Musepack support) (not in Void repos anyway)
neroAacEnc (optional for AAC support) (not in Void repos anyway)
mac (optional for Monkey's Audio support) (not in Void repos anyway)

**Comment by Vaelatern** [comment]
ecad755
