### ISSUE TITLE
Proposal: New metadata field "changelog"

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3355]
I propose to add an optional string to each package which contains a
URL pointing to the changelog of a program by upstream, ideally for
the particular release if available.

I think this is useful
1) for users, since we don't package changelogs in the package
2) for maintainers, since they don't need four clicks on every version change to see if anything needs works

Now start bikeshedding about the name.  I like `changelog`.

**Comment by chneukirchen** [comment]
It's a bit annoying that adding this really requires a XBPS patch...

**Comment by tac1ica** [comment]
As the average Joe user I'd consider this feature as the next best thing right after a switch in xbps-query to print the changelog :)

**Comment by maxice8** [comment]
xbps-create got -c/--changelog , any plans to continue this ?

**Comment by maxice8** [comment]
changelog is now a thing!

**Comment by ebfe** [comment]
> changelog is now a thing!

No it isn't.
