### ISSUE TITLE
stack (Haskell build tool) cannot install ghc

### ISSUE THREAD

**Issue by vesten** [voidlinux/void-packages#3359]
There appears to be a missing dependency on libtinfo.so.5.

Installing stack:
   xbps-install stack

and creating a new project:
   cd ~/devel/haskell/
   stack new foo
   cd foo/
   stack setup

results in:
   /home/vesten/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
make[1]: *** [install_packages] Error 127
make: *** [install] Error 2

**Comment by chneukirchen** [comment]
Install ghc from void repo, too. The stack one will only work on Debian.

**Comment by vesten** [comment]
But that then means one cannot easily switch between different versions of
ghc, e.g. multiple local projects targeting various library and compiler
verisons. This is a great loss.

Its also ironic as I'm trying to replace Debian with Void.

**Comment by chneukirchen** [comment]
This is not really a Void problem, see https://github.com/commercialhaskell/stack/issues/1575

If you really want to, you can hack a symlink from libtinfo.so.5 to libncurses.so.6.0 in /usr/lib. Your warranty is void. ;)

**Comment by vesten** [comment]
You're absolutely right. Thanks for the link. I'll  go with the ghc from the repo and try to wait out a fix from the stack team. Thanks for your help.
