### ISSUE TITLE
Package request: Libreoffice (musl)

### ISSUE THREAD

**Issue by wyrex** [voidlinux/void-packages#3368]
Currently libreoffice-bin is only for i686 and x86_64 versions, it would be useful program but not available in musl.

**Comment by dominikh** [comment]
Not likely to happen in the foreseeable future. For libreoffice-bin, we depend on the binaries that Libreoffice provides. They do not provide any for musl. We'd have to build libreoffice from source. Which we are also unlikely to do, or we wouldn't have the -bin package in the first place.

**Comment by pullmoll** [comment]
We now have libreoffice built from source and available for musl libc as well.
