### ISSUE TITLE
base-files: reconsider /etc/profile.d/xdg-user-dirs.sh

### ISSUE THREAD

**Issue by dominikh** [voidlinux/void-packages#3374]
I argue that /etc/profile.d/xdg-user-dirs.sh in its current form is a bad idea. It will pollute a user's home with directories such as Pictures and Templates, just because e.g. XFCE (which depends on xdg-user-dirs*) is installed, even if that user doesn't use XFCE, or a graphical environment, at all. In fact, it even pollutes root's home once root logs on.

Our shell shouldn't assume that everybody is using a graphical session; or in fact the XDG layout.

**Comment by xtraeme** [comment]
I agree. Perhaps we could move this file to the `xdg-user-dirs` package?

**Comment by dominikh** [comment]
@xtraeme how does that fix anything? Moving `/etc/profile.d/xdg-user-dirs.sh` to a different package doesn't change the fact that once that package is installed, the script will execute for all users, even those that do not use X; including root.

My point was that the file shouldn't exist in `/etc/profile.d`, ever.

**Comment by Duncaen** [comment]
Can we put it in `/etc/X11/xinit/xinitrc.d`?
