### ISSUE TITLE
mutt: build broken / relocation R_X86_64_32S against `.rodata'

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#3386]
$ ./xbps-src pkg mutt
    [*] Updating `http://repo.voidlinux.eu/current/x86_64-repodata' ...
    [...]
    => mutt-1.5.24_3: installing target dependency 'libsasl-devel-2.1.26_4' ...
    => mutt-1.5.24_3: running pre-build hook: 02-script-wrapper ...
    => mutt-1.5.24_3: running pre_build ...
    cc -DMD5UTIL -O2 -pipe  -specs=/void-packages/common/environment/configure/gccspecs/hardened-ld -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -Wl,-z,relro     -L/usr/lib -o mutt_md5 mutt_md5-md5.o  
    /usr/bin/ld: mutt_md5-md5.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
    mutt_md5-md5.o: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:645: recipe for target 'mutt_md5' failed
    make: *** [mutt_md5] Error 1
    => ERROR: mutt-1.5.24_3: failed to run pre_build() at line 53.

**Comment by Duncaen** [comment]
@xtraeme @chneukirchen should this be fixed in `xbps-src`, to include `-fPIC` in `$BUILD_CFLAGS`?

**Comment by chneukirchen** [comment]
I saw this issue with a few other pkg as well, and I guess that would be an easy fix. (Really: apply hardening flags to BUILD_* too.)

**Comment by pullmoll** [comment]
Just be aware that it may collide with inline assembly code for x86 which tries to access CPU flags or the RDTSC command, because %ebx or %rbx can't be clobbered with -fPIC enabled.
