### ISSUE TITLE
cross-* toolchains: don't work outside chroots.

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3395]
These are the paths our cross gcc try to find as(1):

```
"/usr/lib/gcc/armv7l-linux-gnueabihf/4.9.3/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/4.9.3/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/4.9.3/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/4.9.3/../../../../armv7l-linux-gnueabihf/bin/armv7l-linux-gnueabihf/4.9.3/as"
"/usr/lib/gcc/armv7l-linux-gnueabihf/4.9.3/../../../../armv7l-linux-gnueabihf/bin/as"
```

The last path is effectively `/usr/armv7l-linux-gnueabihf/bin/as`, but our assembler is in `/usr/armv7l-linux-gnueabihf/USR/bin/as`.

Inside chroots, there is a `bin -> usr/bin` symlink, but on a normal install there is nothing to create that link.

Furthermore, `cross-armv7l-linux-gnueabihf` provides `/usr/bin/armv7l-linux-gnueabihf-as`, but
`/usr/armv7l-linux-gnueabihf/usr/bin/as` is in `cross-armv7l-linux-gnueabihf-libc`...

I think the `<triple>-gcc` should just call `<triple>-as` to assemble instead of these path shegenians... but as a first remedy we could add the bin-link to some pkg for now.

**Comment by chneukirchen** [comment]
It seems the cross tool chains add these links, but they don't end up in the packages?

```
        for f in include lib bin; do
                if [ ! -d ${_sysroot}/usr/${f} ]; then
                        mkdir -p ${_sysroot}/usr/${f}
                fi
                if [ ! -h ${_sysroot}/${f} ]; then
                        ln -sfr ${_sysroot}/usr/${f} ${_sysroot}/${f}
                fi
        done
```

**Comment by chneukirchen** [comment]
... because it's removed below again:

```
        rm -rf ${DESTDIR}/${_sysroot}/{sbin,bin,lib,etc,var}
```

**Comment by chneukirchen** [comment]
Other distros seem to use `/usr/SYSROOT/bin` directly btw.

**Comment by xtraeme** [comment]
The issue is that sysroot is being used as rootfs for xbps, and base-files needs `/bin` as a symlink to `/usr/bin`.

The correct fix would be keeping the `/bin` symlink that is being removed later on in the templates.

Thanks

**Comment by chneukirchen** [comment]
So #3399 is good? Then I can update the other tool chains too.
