### ISSUE TITLE
Cannot flash void-beaglebone-20151110.img.xz

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#3420]
Hi,

I tried to flash void-beaglebone-20151110.img.xz to an uSD card but tar fails to open it:

sha256sum void-beaglebone-20151110.img.xz 
0951c9ce00ec3b7e868ee942883e99aa4f2329ad8ae9107466b546ab87bf6d08  void-beaglebone-20151110.img.xz (this is correct).
tar xvfJp void-beaglebone-20151110.img.xz -C rootfs
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

Don't know if I am doing something wrong, as I just followed instructions in the wiki. And by the way, the instructions suggest downloading a version that is not available any more:
wget http://repo.voidlinux.eu/live/current/void-beaglebone-20150713.img.xz

My thanks in advance

**Comment by Gottox** [comment]
```
unxz void-beaglebone-20151110.img.xz 
dd if=void-beaglebone-20151110.img of=/dev/DEVICE bs=16M
```

**Comment by nkcyham** [comment]
Thank you, it worked OK

--
Best Regards
Neoklis - Ham Radio Call:5B4AZ
http://www.5b4az.org/
