### ISSUE TITLE
Package request: 3D CAD tools

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#3466]
I've started working on it, but have not been able to get far due to the sheer number of other dependencies and my personal projects.
So far I'm looking at [FreeCAD](http://www.freecadweb.org/) and [HeeksCAD](https://sites.google.com/site/heekscad/home).

Both rely on [libarea](https://github.com/danielfalck/libarea/) which [has not yet tagged a release](https://github.com/danielfalck/libarea/issues/17).
Both also rely on [OpenCASCADE](http://www.opencascade.com/) ([download page](http://www.opencascade.com/content/latest-release)) (and HeeksCAD is known to work with [OpenCASCADE Community Edition](https://github.com/tpaviot/oce) so perhaps that is an option for both of them.)

Further, HeeksCAD relies on [OpenCAMLib (OCL)](https://github.com/aewallin/opencamlib) which looks abandoned, but should still work with HeeksCAD which does have recent activity.

FreeCAD looks more modern and supported, but relies on [many libraries](http://www.freecadweb.org/wiki/index.php?title=Third_Party_Libraries). The ones not yet packaged are  [Coin3d] (https://bitbucket.org/Coin3D/coin/wiki/Home), [SoQt](https://bitbucket.org/Coin3D/soqt), and the aforementioned OpenCASCADE.

I'll come back to this issue when I have time to resume packaging these CAD suites.

**Comment by Vaelatern** [comment]
With git commits, yes, but they are discouraged.

**Comment by Spencer-H** [comment]
True but if there are no releases, and it has been a little bit since anyone contributed to that repo.

**Comment by Vaelatern** [comment]
Fair. If you want to get started, by all means. I have no WIPs on the above.

**Comment by Vaelatern** [comment]
OpenCascade is probably the scariest piece of software on the list.

**Comment by Vaelatern** [comment]
Relevant to #2955

**Comment by ke7ofi** [comment]
I'm currently working on a package for OpenSCAD, so that should help fill the - [takes off sunglasses] - Void.

**Comment by ke7ofi** [comment]
Of course, that's contingent on me being a competent package creator/maintainer, which is probably too much to ask for.

**Comment by Vaelatern** [comment]
#3684

**Comment by karl-nilsson** [comment]
@Vaelatern the FreeCAD wiki is outdated, SoQT has been replaced with Quarter, which resides in the FreeCAD repository.
http://forum.freecadweb.org/viewtopic.php?f=8&t=733&start=80#p117634

Also, FreeCAD works fine with OpenCASCADE Community Edition, so I recommend using it over OpenCASCADE proper.

**Comment by yopito** [comment]
Thanks for these inputs. I'm currently trying to package freecad these days. Anybody is working on it too ?

**Comment by Vaelatern** [comment]
#4270

**Comment by Vaelatern** [comment]
Freecad has been merged. https://git.io/vKtuS
