### ISSUE TITLE
xbps fails to download with ~ in name

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#3471]
wps-office WIP: https://gist.github.com/3fc26249d6cbd37f1cda
On my machine, during testing, it hangs indefinitely on `requesting http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5460%7ea20p1_x86_64.tar.xz`
If I manually run: `xbps-uhelper fetch "http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5460%7ea20p1_x86_64.tar.xz"` then it again hangs.
But if I run `xbps-uhelper fetch 'http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5460%7ea20p1_x86_64.tar.xz'` then the download happens.
The line in question that does the download is in `common/hooks/do-fetch/00-distfiles.sh`, line 153.

**Comment by pullmoll** [comment]
Downloading the unescaped filename inside double quotes works fine for me:
```
xbps-uhelper fetch "http://kdl.cc.ksosoft.com/wps-community/download/a20/wps-office_10.1.0.5460~a20p1_x86_64.tar.xz"
```
albeit damn darn slow (87KB/s).

Why would you want to escape the tilde in the filename? IMO escaping of special characters in an URL is an issue which the protocol handling software should take care of and not the user.

**Comment by Vaelatern** [comment]
I don't escape it in some versions and do in others. It doesn't work for me either way.

**Comment by Vaelatern** [comment]
Now it works. Magic.
