### ISSUE TITLE
gcc: create libgcc-devel

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3472]
We currently split out `libgcc`, but the `crt*.o` from /usr/lib/gcc/x86_64-unknown-linux-gnu/4.9 is in `gcc`.

I propose to split this off into a `libgcc-devel`. We already split off all the other libs.

Currently `clang` depends on `gcc` because of these things, but it really needs these few files only.

(E.g. debian has something similar with https://packages.debian.org/sid/libgcc-4.9-dev)

**Comment by xtraeme** [comment]
Makes Sense. Go ahead, cheers!
