### ISSUE TITLE
virt-manager missing python-requests dep

### ISSUE THREAD

**Issue by cosmoduff** [voidlinux/void-packages#3473]
![virt-manager_error](https://cloud.githubusercontent.com/assets/13722100/12599081/f1b04c4a-c45c-11e5-9d34-68f636647c24.png)
The virt-manager package is missing the dependency for python-requests and fails to open without installing it manually.

Duplicate:

Install virt-manager without installing python-requests and attempt to run.

**Comment by xtraeme** [comment]
Fixed in #3475
