### ISSUE TITLE
Package apache-ant Shouldn't Require OpenJDK if Oracle JDK Is Already Installed

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#3485]
Ant should work fine with Oracle's JDK, so installing the OpenJDK seems redundant. Most folks don't need both installed.

**Comment by xtraeme** [comment]
apache-ant/template:
```
depends="virtual?java-runtime"
```

This effectively depends on a virtual package named "java-runtime" which is provided by oracle-jre and openjdk-jre.

**Comment by antonio-malcolm** [comment]
Was this the actual fix, or just a response? Because, this is still an issue, if it's trying to install the openjdk package, when the oracle package is already installed. Simply asserting "this line exists in the template" doesn't correct it.

**Comment by xtraeme** [comment]
I explained you why there's no issue. The `apache-ant` package depends on the virtual package `java-runtime`, this virtual package is *provided* (provides obj) by either `oracle-jre` or `openjdk-jre`.

**Comment by antonio-malcolm** [comment]
Have you even tested this?
It's fine, I suppose. We can always opt for the ant binary, direct from Apache.

**Comment by xtraeme** [comment]
Being the author of xbps/xbps-src I can guess how all this stuff works.

If no installed pkg providing this virtual pkg, the first one available in repos is used as dependency by default. If you don't want openjdk just specify oracle-jre first on `xbps-install`:

```
$ xbps-install ... oracle-jre apache-ant
```

And alternatively remember there's `xbps-alternatives(1)` to use the default jdk/jre implementation.

**Comment by antonio-malcolm** [comment]
I ALREADY HAVE the oracle-jdk installed.
When installing the apache-ant package, xbps also wants to install openjdk. It doesn't appear to care that you're the author. (I'm sure you know your software, but I've yet to see perfect software, so...).

Really, it's fine. Apache's binary does the job.

**Comment by xtraeme** [comment]
You are not reading what I'm saying:

- `oracle-jdk` and `openjdk` provides `java-environment` NOT `java-runtime`
- `oracle-jre` and `openjdk-jre` provides `java-runtime` NOT `java-environment`
- `apache-ant` depends on `java-runtime` and NOT `java-environment`

Why `oracle-jdk` nor `openjdk` provide `java-runtime` is something I don't know. I didn't package them!

**Comment by antonio-malcolm** [comment]
I have the JRE installed with the JDK (which has been par for the course, for as long as I can remember). 

I did notice, after the last update to the JDK, I had to manually set my environment (which was not needed, previously). Perhaps something there has changed?
