### ISSUE TITLE
dracut reports missing module for amdgpu

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#3505]
Hi

I tried to produce a new initramfs to load amdgpu instead of radeon and I got the following:

dracut: Possible missing firmware "radeon/boniare_mc.bin" for kernel module "amdgpu.ko"

amdgpu is loaded and its working but there seems to be a typo somewhere, I couldn't find it, as the right name for this blob would be "bonaire_mc.bin". I am hoping this might have something to do with a previous issue I reported: #2916 opened on Nov 7, 2015 by nkcyham 

My thanks in advance

**Comment by xtraeme** [comment]
Hmm indeed, it's a typo that is only available in the 4.3.x series:

```
[juan@leysa void-packages]$ modinfo -k 4.3.5_1 amdgpu|grep bon
firmware:       radeon/boniare_mc.bin
```

I can make a patch to correct the firmware filename, or make a symlink in the linux-firmware-amd pkg.

The linux4.4 pkg seems to have fixed this issue.

Thanks!

**Comment by xtraeme** [comment]
Fixed thanks!

**Comment by nkcyham** [comment]
Muchias gracias Juan, for the quick fix!

Micro$oft takes weeks... ;-)

--
Best Regards
Neoklis - Ham Radio Call:5B4AZ
http://www.5b4az.org/
