### ISSUE TITLE
Update request: Firefox

### ISSUE THREAD

**Issue by Varkolac** [voidlinux/void-packages#3513]
Current version in the repos is 43.0.4, the latest stable one 44.0.

**Comment by LonCJ** [comment]
Firefox-ESR is also out of date.  Latest stable release is 38.6.0.

**Comment by xtraeme** [comment]
I'm aware it's outdated, there's a build issue on musl platforms that needs to be resolved.

There's no need to submit Problem Reports for outdated packages, and it was released less than a week ago.
