### ISSUE TITLE
memtest86+ 5.01 is broken. Which way to fix it ?

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#3526]
XBPS package of memtest86+ fails to start tests on both physical and VM.
Official (upstream) binary is fine while beeing  booted in the same conditions, ie from grub on VoidLinux systems (http://www.memtest.org/download/5.01/memtest86+-5.01.bin.gz).

According to Fedora packaging (http://pkgs.fedoraproject.org/cgit/rpms/memtest86+.git/tree/) and official forum (http://forum.canardpc.com/threads/83443-Memtest86-V5.01-crashes-with-gcc-4.7.2-or-later) , it's related to gcc > 4.7.

Fedora packaging has patches to fix build from source.

I can provide a PR to fix it, but with which way ?
1. reuse the Fedora patches (I'm not sure to fully understand their effects)
2. repackage the official memtest86+ binary, do not build it at all 

Which option do you prefer ?

**Comment by xtraeme** [comment]
A patch that makes this work is always preferred.

Thanks.

**Comment by yopito** [comment]
OK, thanks for the advice. I will PR ASAP.
