### ISSUE TITLE
octave: configure failed when building from sauce

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#3539]
I just noticed that octave was built without X11, OpenGL and stuff. So I
decided to fix this. However, `./xbps-src configure octave` is failing
even without my mods:

```
configure: error: A BLAS library was detected but found incompatible with your Fortran 77 compiler settings.
=> ERROR: octave-4.0.0_1: failed to run do_configure() at line 7.
```

Note teh `fPIC` messages on config.log, included below. My first guess:
lapack was built without it. And it's template seem to explicitly set
it.

Logs:
[xbps-src_configure_octave.log](https://github.com/voidlinux/void-packages/files/118683/xbps-src_configure_octave.log.txt)
[config.log](https://github.com/voidlinux/void-packages/files/118684/config.log.txt)

<3

**Comment by ayghor** [comment]
octave is also missing docs:

```
octave:2> help plot
error: unable to open /usr/share/octave/4.0.0/etc/macros.texi for reading
error: called from
    __makeinfo__ at line 103 column 5
    help at line 102 column 22
```

**Comment by asergi** [comment]
The problem is fortran. Just add `nopie=yes` to the octave template.

**Comment by xtraeme** [comment]
The configure issue has been fixed, please submit another PR if there are more issues.

**Comment by ayghor** [comment]
nice! thank you!
