### ISSUE TITLE
Package request: openCryptoki

### ISSUE THREAD

**Issue by xaduha** [voidlinux/void-packages#3557]
http://sourceforge.net/projects/opencryptoki

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opencryptoki

https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/opencryptoki/default.nix#L31

Couldn't build it, probably has something to do with autotools configuration in bootstrap.sh.

**Comment by ebfe** [comment]
This relies on the ancient des_* functions that have been deprecated >10 years ago in OpenSSL and have been removed from libressl.

**Comment by Vaelatern** [comment]
Can they readily be patched out?
