### ISSUE TITLE
gnuplot package does not provide gnuplot command

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#3578]
Teh gnuplot package does not provide teh gnuplot command! Instead,
gnuplot-x11 is provided, breaking scripts.

Currently, octave fails to build documentation because of this.

Perhaps a wrapper script could be installed, to select from available
gnuplot flavours.

**Comment by chneukirchen** [comment]
You can install gnuplot-wx for now, but I guess using alternatives would be nicer.

**Comment by ayghor** [comment]
gnuplot-wx worked! Thanks!

Still, I would expect gnuplot package to provide teh gnuplot command.

**Comment by chneukirchen** [comment]
Alternatives implemented in e8ec6e3.
