### ISSUE TITLE
Add hardened and tiny base system

### ISSUE THREAD

**Issue by trufae** [voidlinux/void-packages#3638]
Many people is opting out to use Alpine just because it comes with musl and hardened compilation (ASLR/PIE/fstackprotect) with selinux/.. kernel. For Docker or just embedded systems.

**Comment by thypon** [comment]
Actually voidlinux is compiled with hardened [hardening.sh](https://github.com/voidlinux/void-packages/blob/master/common/environment/configure/hardening.sh) [hardened-cc1](https://github.com/voidlinux/void-packages/blob/master/common/environment/configure/gccspecs/hardened-cc1) [hardened-ld](https://github.com/voidlinux/void-packages/blob/master/common/environment/configure/gccspecs/hardened-ld) exactly like alpine, plus it provides glibc/musl options and a sane package alternatives system.

If i have to say a reason alpine is getting traction for docker is they provide tagged releases.

Having it as a base system for docker with grsec patches applied isn't as straightforward as running voidlinux btw:
- https://forums.grsecurity.net/viewtopic.php?f=3&t=4238
- https://forums.grsecurity.net/viewtopic.php?f=3&t=4052

You have to pax-mark the executables inside each container to run them.

**Comment by Gottox** [comment]
ASLR/PIE/fstackprotect is already enabled on void. (see the `checksec` tool)

selinux is not though.

**Comment by Vaelatern** [comment]
There is `base-system-busybox`

**Comment by cr6git** [comment]
So, what's the point of keeping this issue open?
