### ISSUE TITLE
Which version of xorg-server is compatible with Catalyst?

### ISSUE THREAD

**Issue by GGMethos** [voidlinux/void-packages#3642]
I know that to install a particular version of a package you would use xbps-install -Sf xorg-server.16.1 but the output is that it's unable to locate it in the repository.

How would I revert back to a previous version of xorg-server able to run Catalyst?

**Comment by Vaelatern** [comment]
You would compile the package yourself, if you don't have it in your cache (and you could use `xdowngrade` to revert to a previous xorg-server).

**Comment by xtraeme** [comment]
This repository `http://archive.voidlinux.eu/glibc/2015-11-09/current/` contains the latest xorg-server-1.17.x version.

Remove `xorg-server`, add this repository to xbps and then install `xorg-server-1.17.4_2`.
You'll also have to install the input drivers i.e `xf86-input-evdev` or any other that is compatible with this xorg-server version.
