### ISSUE TITLE
RFC: dealing with glibc updates

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3644]
I'd like to see an official agreement how we want to manage glibc patches.

In 1147c6c, patches were imported from LFS and named "upstream patches", but there is at least one patch which is not upstream (and tweaks nscd paths for hardly a good reason...), and the others do not correspond directly to upstream patches.

I'd propose instead to write a small script to export the current glibc release branch as patches on top of the last release, so we end up with the 16 official patches that have been applied upstream and their proper commit messages: `https://sourceware.org/git/?p=glibc.git;a=patch;h=refs/heads/release/2.22/master;hp=refs/tags/glibc-2.22` and we can update our patch sets on demand then.

Alternatively, we could just take above URL and store it as a single patch.

I don't think we should import other distro's idiosyncrasies and instead stay close to mainline.
(I think our glibc-disable-rwlock-elision.patch is obsolete too, due to use of --disable-lock-elision)

Pinging @xtraeme @pullmoll.

**Comment by pullmoll** [comment]
I thought it was ok to take LFS patches, since I did this before and it was accepted by Juan.
I agree that the nscd paths patch is probably not necessary or even bad. As far as I understand it it's trying to achieve FHS compability, which we do not follow (generally)?

The script to keep patches from upstream in synch is a good idea IMO. Perhaps this could be generalized and integrated into the update-check script, i.e. check for new patches as well, if a specific patch update file is found besides the template?

**Comment by chneukirchen** [comment]
First draft:

```sh
#!/bin/sh
# glibc-patches VERSION - fetch glibc upstream patches
version=${1?no version given}
curl -sL "https://sourceware.org/git/?p=glibc.git;a=patch;h=refs/heads/release/${version}/master;hp=refs/tags/glibc-${version}" | sed '/Subject/s,/[0-9]*\],],' | csplit -f glibc-upstream- -b '%02d.patch' -s - '/^From /' '{*}'
rm glibc-upstream-00.patch
```

**Comment by pullmoll** [comment]
:+1: 
IMO this should be kept in srcpkgs/glibc and in a first step replace the patches I imported.
I think @xtraeme won't hardly disagree and whether or not some kind of auto detection is required can be discussed later on.

**Comment by pullmoll** [comment]
Should we be concerned about this http://dnsviz.net/d/sourceware.org/dnssec/ or this http://dnssec-debugger.verisignlabs.com/sourceware.org when retrieving patches from `sourceware.org`?

**Comment by chneukirchen** [comment]
glibc 2.23 is out now, this would be a good chance to implement this.

**Comment by pullmoll** [comment]
I tried with glibc-2.23 now and there are already 16 patches.

However, we need to apply them in reverse order. Currently glibc-upstream-02.patch fails because there all following patches also modify ChangeLog and 02 needs the 03 patch, etc.

Is it possible to modify the URL to return the list in reverse order?

**Comment by ebfe** [comment]
Ping. There are currently 15 patches for 2.24. At least one (arm only) CVE fixed.

**Comment by chneukirchen** [comment]
Does the script work? I can fix it else.

**Comment by ebfe** [comment]
It pulls down some patches, though there are quote a few conflicts when applying them. Not sure whats wrong yet.

**Comment by ebfe** [comment]
https://sourceware.org/git/?p=glibc.git;a=commit;h=ea23815a795f72035262953dad5beb03e09c17dd

This patch gets mangled somehow and  no longer applies. Encoding issue? In theory this patch could be skipped, but then all the following patches are rejected since the Changelog entries no longer apply :/

**Comment by chneukirchen** [comment]
Looks like gitweb breaks the encoding ~_~

Perhaps we should just use repo.or.cz.

This works fine with -Np1:

```
#!/bin/sh
# glibc-patches VERSION - fetch glibc upstream patches
version=${1?no version given}
curl -sL "http://repo.or.cz/glibc.git/patch/glibc-${version}..release/${version}/master" | sed '/^Subject/s,/[0-9]*\],],' | csplit -f glibc-upstream- -b '%02d.patch' -s - '/^From /' '{*}'
rm glibc-upstream-00.patch
``

**Comment by ebfe** [comment]
#4764

**Comment by chneukirchen** [comment]
Can you add the script, too? Then close this issue.
