### ISSUE TITLE
Missing vim-common-7.4.1046_1

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#3670]
```
;) sudo xbps-install vim-huge
MISSING: vim-common-7.4.1046_1
Transaction aborted due to unresolved dependencies.
```

**Comment by ebfe** [comment]
Only happening on x86_64.

    [-] vim-7.4.1046_1                  Vim editor (vi clone)
    [-] vim-common-7.4.1376_1           Vim editor (vi clone) - common files
    [-] vim-huge-7.4.1046_1             Vim editor (vi clone) - Huge (all features enabled, using Python 2)
    [-] vim-huge-python3-7.4.1046_1     Vim editor (vi clone) - Huge (all features enabled, using Python 3)
    [-] vim-x11-7.4.1046_1              Vim editor (vi clone) - with access to X11 selection

The x86_64_builder is stuck on the chromium 48 build since yesterday. vim-common is noarch so i guess it got updated by another builder and now the repo is inconsistent?

**Comment by Vaelatern** [comment]
Now fixed on `x86_64`
