### ISSUE TITLE
Package Request: python3-devel

### ISSUE THREAD

**Issue by akbiggs** [voidlinux/void-packages#3692]
https://www.python.org/downloads/source/

We currently have a python-devel package in the repository, but no corresponding python3-devel.

This makes installing neovim's python support more painful, since you have to download and build the python 3 source code.

**Comment by Duncaen** [comment]
`xbps-query -RS python3.4-devel`

**Comment by akbiggs** [comment]
ah, shoot. I search for python-devel and python3-devel on the repos page, so I mistakenly assumed this didn't exist.

Would it be possible to alias this to python3-devel as well for consistency, or is there a reason we're sticking to specific versions here?
