### ISSUE TITLE
Package request: rr

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#3694]
http://rr-project.org/

Build dependencies:

* gcc-c++
* gcc-multilib
* python-pexpect
* pkg-config
* cmake
* libz-devel
* make
* gdb

For running it requires performance counters, which are not supported on Virtualbox, but will be  eventually supported I guess

See https://github.com/mozilla/rr/wiki/Building-And-Installing

**Comment by chneukirchen** [comment]
I tried packaging this once, then realized it didn't run on any CPU I had.

Also the build system is a massive PITA because you can't pass custom CFLAGS at all without breaking anything.

Last template: http://sprunge.us/YfNH

**Comment by ebfe** [comment]
#3697

**Comment by radare** [comment]
👍
