### ISSUE TITLE
System packages for libreoffice

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#3716]
This is a list of packages which libreoffice downloads now and that could become `--with-system-*` in the `./configure` call to reduce the time it takes to build; currently it takes about 3hrs 10min for x86_64

- [x] clucene-devel (for musl the file /usr/include/CLucene/analysis/cjk/CJKAnalyzer.h is missing)
- [x] libwps-devel (updated to 0.4.3; seems to work now)
- [x] hyphen-devel (we have version 2.8.8; always downloaded, but links against system hyphen)
- [x] CoinMP-1.7.6
- [x] collada2gltf (libreoffice uses git master-cb1d97788a; using git master-bc1fe2adaf; need -devel subpackage)
- [x] libe-book-0.1.2
- [x] Firebird-2.5.4.26856-0 (we have 2.5.5.26952; seems to work)
- [x] libfreehand-0.1.1
- [x] xmlsec1-1.2.14 (we have xmlsec1-1.2.20; it isn't recognized and always built internally)
- [x] lp_solve_5.5 (we have lpsolve-5.5.2.0; seems to work now)
- [x] mdds_0.12.1 (new package mdds0-0.12.1 available now)
- [x] libmwaw-0.3.7 (seems to work now)
- [x] OpenCOLLADA (libreoffice uses git master-6509aa13af; works with master-05bdf47679)
- [x] libixion10-0.9.1 (0.9.x branch for libreoffice)
- [x] libixion-0.11 (prerequisite for liborcus; not yet useful for libreoffice-5.1.0.3)
- [x] liborcus10-0.9.2 (0.9.x branch for libreoffice)
- [x] liborcus-0.11 (from git master-9d43dc689b; not yet useful for libreoffice-5.1.0.3)
- [x] ucpp-1.3.2
- [x] libgltf-0.0.2 (we have version 0.0.2; link fails with `undefined reference to 'libgltf::gltf_get_camera_pos(libgltf::glTFHandle*, glm::detail::tvec3<float>*, glm::detail::tvec3<float>*, glm::detail::tvec3<float>*)'`)

I'll see if and which of these packages can be added to Void.
You're of course welcome to help and mark newly available packages here.

**Comment by pullmoll** [comment]
Not required but currently defined makedepends
- [ ] serf-devel (we have neon and it is used for WebDAV)

**Comment by bra1nwave** [comment]
We have `libgltf` in the repo, so it can be marked too.

**Comment by pullmoll** [comment]
Closing because the packages are now available or can't be made external (without too much trouble).
