### ISSUE TITLE
Package request: acpi_call

### ISSUE THREAD

**Issue by Varkolac** [voidlinux/void-packages#3724]
https://github.com/mkottman/acpi_call

kernel module for Thinkpad advanced battery features

Last commits (+ release) were years ago.

**Comment by Vaelatern** [comment]
So you know, we do have `tp_smapi-dkms` that should do similar.

**Comment by Varkolac** [comment]
`tlp` recommends installing both. If I understand it correct `acpi-call` adds features for Sandy Bridge or newer processors

**Comment by Vaelatern** [comment]
Appears your assumption is correct, `acpi-call` is necessary for newer hardware.

**Comment by Vintodrimmer** [comment]
Any progress?

**Comment by damadmai** [comment]
As #5452 (which is based on mkottman/acpi_call & all additions to it I have found so far) is now merged, this package request is fullfilled & the issue can be closed.
