### ISSUE TITLE
Package Request: etckeeper

### ISSUE THREAD

**Issue by SirDoctors** [voidlinux/void-packages#3727]
https://github.com/joeyh/etckeeper

If this can be made to call its two install hooks, `etckeeper pre-install` & `etckeeper post-install` that be awesome.

**Comment by diogoleal** [comment]
I sent a PR for this request #4744

**Comment by arete** [comment]
hi @diogoleal  have update you pull request with the  new version.

**Comment by espositom221** [comment]
the last update of pull request #4744  not is related to etckeeper.
 @diogoleal you can update you branch to  https://github.com/arete/void-packages/commit/db9b4482321c2b8855deca453c31ed4f4693d1b7 ?

**Comment by diogoleal** [comment]
This issue is completed #6173
