### ISSUE TITLE
Package request: python bindings for mlt

### ISSUE THREAD

**Issue by tom-i** [voidlinux/void-packages#3752]
Hi, I would like to install flowblade, but one of the non-existing package is python bindings for MLT.

More here:
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/DEPENDENCIES.md

Thanks a lot :)

**Comment by ebfe** [comment]
Actually there was a change (43ab9819b773dbe361555ad78f122046c1832a77) recently to enable this, the commit however doesn't seem to have any effect on the resulting package.

**Comment by Vaelatern** [comment]
Can you provide a link to any package for this? I know we don't have one, but I can't find source online.
