### ISSUE TITLE
Can't remove xf86-input-evdev

### ISSUE THREAD

**Issue by ke7ofi** [voidlinux/void-packages#3758]
For background, I'm switching to libinput so my TrackPoint works right. As I understand it, libinput depends on the kernel or library part of evdev (not sure which), but xf86-input-evdev's functionality is replaced by libinput. When I try to remove that package, though, I get:

```
~$ xr xf86-input-evdev
xf86-input-evdev-2.10.1_1 (remove) breaks installed pkg `xorg-input-drivers-7.6_3'
xf86-input-evdev-2.10.1_1 (remove) breaks installed pkg `xorg-minimal-1.1_2'
Transaction aborted due to unresolved dependencies.
```

How can I convince them to stop complaining?

**Comment by Vaelatern** [comment]
You can uninstall both of the reverse dependencies, since they are meta-packages and exist to bring in a known set of other packages. Just be aware that they are both pulling in other packages so if you `xbps-remove -o` after, you will remove any packages installed with those meta-packages.

**Comment by Vaelatern** [comment]
That said I have `libinput` alongside `xf86-input-evdev` on my Thinkpad right now.

**Comment by Varkolac** [comment]
You could also force the removal with the `-F` flag.

**Comment by ke7ofi** [comment]
It looks like my options are to manually reinstall the metapackage deps or to leave xf86-input-evdev installed and tell X to use libinput somehow. How does one do the latter?

**Comment by Varkolac** [comment]
Installing `xf86-input-libinput` should do.

**Comment by ke7ofi** [comment]
That doesn't seem to have enabled middle-button scrolling (which, if the ArchWiki is to be believed, it should).

**Comment by Vaelatern** [comment]
What works wrong on your trackpoint anyway?

**Comment by ke7ofi** [comment]
Middle button scrolling is disabled. I know I can fix it with .xinitrc and evdev, but want to do this the "clean" way.

**Comment by Vaelatern** [comment]
Fair. I have, called in `.xinitrc`
```
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200 
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
synclient TouchpadOff=1
```

**Comment by ke7ofi** [comment]
I'll do that temporarily, but it would be nice to find a more permanent solution.

**Comment by ke7ofi** [comment]
Also, does the last one turn off the touchpad off? I keep it on for when drift becomes a problem.

**Comment by Vaelatern** [comment]
@Duncaen not sure this contains an idea, can you expound?

**Comment by ke7ofi** [comment]
Anyway, is it possible to make xorg-minimal depend on evdev OR libinput?

**Comment by Vaelatern** [comment]
I don't think so, but we could have a subpackage that depends on evdev instead... but that is just messy.

**Comment by Duncaen** [comment]
xbps supports virtual packages, you could add `virtualpkg=xf86-input-evdev:xf86-input-libinput` into `/etc/xbps.d/foo.conf`, to kill the dependency.

`man xbps.d`

**Comment by chneukirchen** [comment]
xorg-minimal uses xf86-input-libinput now, so this is obsolete.

Don't install xorg-input-drivers if you know better.
