### ISSUE TITLE
Idea: how to solve the timestamp-macros issue

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#3774]
I believe it would be possible to patch `gcc / g++` such that when preparing the values for the `__DATE__`, `__TIME__` and `__DATETIME__` macros, it would look for a certain environment variable – perhaps `XBPS_SOURCE_DATE_EPOCH` – and take its value instead of the seconds since the Epoch which `time(2)` returns.

The source file creating the macro values seems to be `libcpp/macro.c` in the `gcc` package. In line 348 there is `tt = time(NULL);` which reads the current time. It is then translated to local with `tb = localtime(&tt);` and if this succeeds, formatted and stored in the fields `pfile->date` and `pfile->time`.

So if we here look at the environment like with:
```
        char* sourcedate = getenv("XBPS_SOURCE_DATE_EPOCH");
        if (sourcedate)
                tt = (time_t) atoll(sourcedate);
        else
                tt = time(NULL);
```

we should be fine.

The pre-configure hook then could simply check `$XBPS_USE_BUILD_MTIME` and either `unset XBPS_SOURCE_DATE_EPOCH` or `export XBPS_SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH`.

**Comment by ebfe** [comment]
https://gcc.gnu.org/ml/gcc-patches/2015-06/msg02210.html

**Comment by pullmoll** [comment]
Yep, we could simply use that patch https://gcc.gnu.org/ml/gcc-patches/2015-06/txtLtaPOCTgpq.txt
We must however then make sure that for `XBPS_USE_BUILD_MTIME` the variable `SOURCE_DATE_EPOCH` is unset.

**Comment by pullmoll** [comment]
Done. See #3787
