### ISSUE TITLE
luasec-0.6_1.x86_64 breaks SSL/TLS in prosody-0.9.10_1.x86_64

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#3778]
After upgrading to latest luasec-0.6_1 package and restarting prosody xmpp clients can't connect using STARTTLS anymore (error: server doesn't support TLS).
Downgrading to previous luasec-0.5.1_1.x86_64 fixes the issue.

**Comment by mdkuser** [comment]
This is what prosody logs as an error when luasec-0.6_1 is installed:

"error	Unable to initialize TLS: LuaSec (required for encryption) was not found"

**Comment by mdkuser** [comment]
According to:

http://comments.gmane.org/gmane.comp.lang.lua.general/120782

luasec-0.6 adds support for only lua-5.2 and lua-5.3 but prosody requires lua-5.1
so please add luasec-0.5.1 as an additional package named something like lua51-sec to fulfill prosodys dependecies.
Thank you!

**Comment by mdkuser** [comment]
just confirmed with the prosody develeopers: for latest stable prosody release 0.9.x lua5.1 is required and luasec-06 won't work with lua5.1.
Once prosody-0.10 is released luasec-0.6 is supported as prosody-0.10 supports lua5.2

So my suggestion is, please add luasec-0.5.1 as luasec51-0.5.1 and make it a dependency of prosody-0.9.x or update the prosody-0.9.x package to prosody-0.10 (I'd prefer the first, since 0.10 is not stable yet).
Thanks.

**Comment by Duncaen** [comment]
Thanks for your help, I tried to fix it yesterday but couldn't find the reason.
I added `lua51-luasec` and `prosody` depends now on it.

53ae19e009b379cf7f7b76bf264a19a87bd31637

**Comment by mdkuser** [comment]
You are welcome. 
Thank you for quick response and action fixing the issue.
I confirm it works with new lua51-luasec package and prosody package revision.

However your new lua51-luasec package conflicts with luasec package if luasec is updated after lua51-luasec is installed, the same error with prosody, not beeing able to find luasec happens. So to fix it prosody needs to be upgraded first that will install new lua51-luasec dependency, then remove luasec and the reinstall lua51-luasec (and never install luasec again while lua51-luasec is installed)

**Comment by mdkuser** [comment]
# xbps-query -f lua51-luasec
/usr/lib/lua/5.1/ssl.so
/usr/share/lua/5.1/ssl.lua
/usr/share/lua/5.1/ssl/https.lua
/usr/share/licenses/lua51-luasec/LICENSE


# xbps-query -f luasec
/usr/lib/lua/5.1/ssl.so
/usr/share/lua/5.1/ssl.lua
/usr/share/lua/5.1/ssl/https.lua


luasec-0.6 should be installing to /usr/lib/lua/5.2/ and /us/share/lua/5.2/ssl
or if luasec should be marked conflicting with lua51-luasec and vice versa (if xbps can handle this)


Anyway prosody now works with lua51-luasec installed. Tank you for fixing. 
Much appreciated your quick support!

**Comment by Duncaen** [comment]
Added `lua52-luasec` in 0cc7eebeffd028b145e759b86ab955b35f0b919b
And changed `luasec` to Lua version 5.3 in 728cedc4c852e4414acbab7975526d907c5836ed
