### ISSUE TITLE
CoinMP installs files to /destdir/CoinMP-${version}

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#3779]
$ xls CoinMP | grep destdir
    /destdir/CoinMP-1.8.3/usr/share/coin/doc/CoinMP/Makefile
    /destdir/CoinMP-1.8.3/usr/share/coin/doc/CoinMP/example.c

cc @pullmoll

**Comment by pullmoll** [comment]
I'll take care of it.
