### ISSUE TITLE
qmc2 installs files into /destdir/qmc2-${version}

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#3780]
$ xls qmc2 | grep destdir
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_sv.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_fr.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_it.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_pt.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_ro.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_de.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_pl.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_de.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_el.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_es.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_fr.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_pt.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qt_sv.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_pl.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_es.qm
    /destdir/qmc2-0.61/usr/share/qmc2/lng/qmc2_us.qm

cc @pullmoll

**Comment by Vaelatern** [comment]
4d0f1e3eb

**Comment by pullmoll** [comment]
Thank you @Vaelatern !
