### ISSUE TITLE
llvm: hardening flags leak into llvm-config --cflags output

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#3816]
$ llvm-config --cflags
    -I/usr/include -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g  -fPIC -Wall -W -Wno-unused-parameter -Wwrite-strings -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

**Comment by pullmoll** [comment]
We should be using the new `GCC_SPECS` environment of `gcc` to pass the specs instead of modifying the `CFLAGS` and `CXXFLAGS`. I think this is all in `common/environment/configure/hardening.sh`.

**Comment by chneukirchen** [comment]
I thought about this, but it will break using ccache and distcc so far.

**Comment by chneukirchen** [comment]
For now, we should just filter the flags as in the other packages.

**Comment by ebfe** [comment]
ccache might be fixable by using `extra_files_to_hash=<specfile>`. don't know about distcc.

**Comment by chneukirchen** [comment]
No, ccache needs to be taught to look at the current environment.

**Comment by chneukirchen** [comment]
Perhaps a full-fledged cc wrapper will be a better solution, esp. when we want to support clang.

Perhaps looking at nixos (and pkgsrc) could be interesting: https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/cc-wrapper

**Comment by mpu** [comment]
I also noticed that several optimization levels appear in the output. I think it would be nice to let this choice to the user of `llvm-config`, for example, it is convenient to build without optimizations for debugging purposes.
