### ISSUE TITLE
freetype with infinality flag fails to build (xbps-src)

### ISSUE THREAD

**Issue by iliketousetransmissionformytorrents** [voidlinux/void-packages#3829]
Following the documentation (https://wiki.voidlinux.eu/Infinality), all but freetype builds with the infinality patch set.

```
@voidlinux [void-packages]: ./xbps-src -o ultimate pkg freetype
(...)
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file ChangeLog.rej
patching file include/freetype/ftlcdfil.h
Hunk #1 FAILED at 250.
1 out of 1 hunk FAILED -- saving rejects to file include/freetype/ftlcdfil.h.rej
=> ERROR: freetype-2.6.3_1: failed to run post_extract() at line 28.
```

Again, the cairo and fontconfig files do build as they should.

**Comment by Vaelatern** [comment]
This patch was written for a previous version of the software, `2.6.2` instead of the current `2.6.3`

**Comment by Duncaen** [comment]
The patch is outdated, this is why its a build option and not enabled by default.
There is now new commit to https://github.com/bohoomil/fontconfig-ultimate you could fix it yourself or use an older freetype version.

**Comment by Vaelatern** [comment]
This is a problem in the upstream for that patch set. https://github.com/bohoomil/fontconfig-ultimate/pull/136

**Comment by transtorrent** [comment]
@Duncaen 
@Vaelatern 
Thank you, I wasn't aware.

**Comment by onodera-punpun** [comment]
https://github.com/bohoomil/fontconfig-ultimate/pull/136

There is a patch/PR I've been using for a while now, works perfectly.

**Comment by subsonik** [comment]
Bohoomil has since released his 2016-03-29 patchset, which applies just fine against freetype 2.6.3. Unfortunately, the patches fails to apply to fontconfig 2.11.1, while applying successfully to 2.11.94.

Can we update fontconfig 2.11.94? I know it's not technically considered "stable" but every other distro uses it as stable, and 2.11.1 was released in early 2014.

**Comment by Vaelatern** [comment]
[Not nearly every distro.](https://packages.gentoo.org/packages/media-libs/fontconfig)

**Comment by subsonik** [comment]
OK, *every* distro was a slight exaggeration. :p

And actually, after checking, the majority of the top distros on distrowatch.com seem to use 2.11.1. My bad!

**Comment by kachsheev** [comment]
I resolved problem, but I think it's a crutch.
[template.copy.txt](https://github.com/voidlinux/void-packages/files/237948/template.copy.txt)

**Comment by maoamid** [comment]
can you explain please how to apply this patch? ty

**Comment by Vaelatern** [comment]
A diff would be more useful to understand your solution.

**Comment by kachsheev** [comment]
You rewrite template file in freetype directory using my one and build
package. But it can't work with fontconfig building.

2016-06-11 19:23 GMT+03:00 maoamid <notifications@github.com>:
