### ISSUE TITLE
/etc permission review

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3839]
I noticed we have some too permissive permissions in `/etc`, and I fixed wpa_supplicant.conf already in 87aef0f.

*Please*, review your `/etc` to check if any files are
- world-readable which *possibly* can contain secrets (should be `-rw-r-----` then)
- group-writable, but just configuration (should be `-rw-r--r--` then)

and mention them here for review

**Comment by biopsin** [comment]
not shure what's suppose to be what, but please browse my list https://app.box.com/s/w4x38osrx405kcw63u8pgzhjsy42018f
