### ISSUE TITLE
Package request: python-gi, GTK3 python bindings

### ISSUE THREAD

**Issue by tom-i** [voidlinux/void-packages#3842]
Hello guys again.
You rock, you solve MLT Python bindings (new package's working well), but for running Flowblade it needs "python-gi GTK3 Python bindings" as it is on the 1st row in dependency list here:
https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/DEPENDENCIES.md

Is it possible to add that to Voidlinux too?

Thanks a lot.

Tom

**Comment by asergi** [comment]
`xbps-query -Rs python-gobject`

**Comment by tom-i** [comment]
Thank you.
