### ISSUE TITLE
before webkit rebuilds: vpx + webp rebuilds

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3844]
Tracking bug to do so-bumps in liubvpx and libwebp:

- [x] SDL2_image-2.0.1_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] chromium-48.0.2564.116_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] darktable-2.0.2_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] efl-1.16.1_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] gst-plugins-bad1-1.6.3_2: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] gthumb-3.4.2_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] kde-runtime-4.14.3_3: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] libgraphicsmagick-1.3.23_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] libmagick-6.9.3.7_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] libpurple-telegram-1.2.5_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] openimageio-1.5.24_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] python-Pillow-3.1.1_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] python3.4-Pillow-3.1.1_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] qt5-imageformats-5.5.1_3: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] qt5-webkit-5.5.1_3: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] webkit2gtk-2.10.7_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] webkitgtk-2.4.9_4: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] webkitgtk2-2.4.9_4: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] weston-1.9.0_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] weston-x11-1.9.0_1: libwebp.so.5 (http://repo.voidlinux.eu/current)
- [x] weston-xwayland-1.9.0_1: libwebp.so.5 (http://repo.voidlinux.eu/current)

- [ ] avidemux-2.6.12_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] firefox-45.0_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] firefox-esr-38.7.0_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] gst-plugins-bad-0.10.23_13: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] gst-plugins-good1-1.6.3_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] icecat-38.6.0_2: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] icecat-devel-38.6.0_2: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] libavcodec-2.8.6_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] libvpx-tools-1.4.0_2: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] thunderbird-38.6.0_2: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] toxcore-git-20160131_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] toxic-0.7.0_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] utox-0.5.1_2: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] virtualbox-ose-5.0.16_1: libvpx.so.2 (http://repo.voidlinux.eu/current)
- [ ] xpra-0.16.2_1: libvpx.so.2 (http://repo.voidlinux.eu/current)

**Comment by asergi** [comment]
Unfortunately, webkit already gone. Anyway, I have the libwebp rebuild in my stash from some time now. I just need to find the time to push it. Will probably do in the night since it takes several hours.

**Comment by ebfe** [comment]
libvpx now also done
