### ISSUE TITLE
xine-lib: build fails

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#3849]
I see an error regarding `relocation for R_X86_64_PC32` when trying to build `xine-lib` and was not able to fix it. For example `nopie=yes` does not solve it.

Here's the build log: http://sprunge.us/NiYS

**Comment by Vaelatern** [comment]
This problem persists when trying to build agains ffmpeg, in #3788 .

**Comment by Duncaen** [comment]
http://mail-index.netbsd.org/tech-toolchain/2016/03/07/msg002745.html

**Comment by pullmoll** [comment]
So https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65248#c6 suggests we are on our own with gcc4.9
Perhaps it's time to create a gcc5 branch and see if pkgsrc can be compiled with it... which is not in any way trivial.

**Comment by chneukirchen** [comment]
Is building xine-lib with visibility disabled an option instead?

**Comment by pullmoll** [comment]
We could perhaps fake (or disable) the check if `$CC supports __attribute__(( visibility("protected") ))`.
The flag seems to be `cc_cv_attribute_visibility_protected` ... I'm giving it a try.
