### ISSUE TITLE
ntp-4.2.8p6_1.x86_64 logs segmentation fault errors related to glibc-2.23_1.x86_64

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#3850]
ntp-4.2.8p6_1 on a 64 bit voidlinux system (virtual machine) with glibc-2.23_1 floods the logs with lots of error messages as follows:

`
kernel: [  160.359175] ntpd[2928]: segfault at 7f3a68749462 ip 00007f3a67709f38 sp 00007f3a67684558 error 4 in libc-2.22.so[7f3a67686000+19b000]
`

**Comment by ebfe** [comment]
Can't reproduce. Is this still an issue?

**Comment by mdkuser** [comment]
Seems it's now not an issue anymore. Can't tell which ntp update fixed it.
Thanks for having a look at it. Issue solved.
