### ISSUE TITLE
WIP: Qt5 5.6.0

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#3853]
The new version 5.6.0 has changes which require a little more work as usual to be done

+ [x] some (musl) patches became obsolete or need to be adapted
+ [x] `qtquick1` is gone; there will be no `qt5-quick1{,-devel}` package anymore
+ [x] the `qt5-doc` hackery stopped working; remove `qt5-doc` subpackage from `qt5`
+ [x] Create new pkg `qt5-doc` and depend on `qt5-tools-devel` and what else is needed
+ [x] besides `qt5-quickcontrols` there is a new subpkg `qt5-quickcontrols2`
+ [x] new dependency: `qtwebengine` needs `libXScrnSaver-devel` (at least)
+ [x] `qtwebkit` is gone as part of the main archive; remove `qt5-webkit{,-devel}` from `qt5`
+ [x] `qtwebkit` is is still available for `5.6.0` as a separate tarball; build new pkgs `qt5-webkit{,-devel}`
    + See: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/qt5-webkit
+ [x] create a new subpkg `qt5-examples` after removing the `-nomake examples` option

**Comment by pullmoll** [comment]
After trying to upgrade from `5.5.1` to `5.6.0` without success (due to now missing subgpkgs) instead create a new package `qt56-5.6.0`.
Use `/usr/lib/qt56` as the prefix and rename anything `qt5` to `qt56` to allow parallel installation and upgrading of dependent packages one after another.

**Comment by equalsraf** [comment]
FYI I was testing the Qt 5.6.0 binaries earlier and ran into this issue https://github.com/QupZilla/qupzilla/issues/1870#issuecomment-189643688

**Comment by asergi** [comment]
@pullmoll about the upgrade problem: if haven't got it wrong, I had a similar issue back when upgrading IPython to 4.0.

As a workaround, just add to the `qt5` template: `replaces="qt5-doc<5.6.0 qt5-foo<5.6.0"`, where `qt5-foo` is the now non-exisisting subpackage.

So, this way there is no need to rename (unless there are other reasons).
Hope it helps.

**Comment by pullmoll** [comment]
@asergi I'm stuck with the try to rename, because I get wrong dependencies to qt5-* packages in the qt56-branch due to duplicates in common/shlibs.

Now that at least qt5-webkit-5.6.0 builds I'm trying again to replace qt5.

I'll give the `replaces="...` at try. Thanks!

**Comment by pullmoll** [comment]
The PR now builds successfully on `x86_64`, `x86_64-musl` and `i686`.
I tested the `x86_64` build with `xbps-install -S -R /path/to/myrepo` and everything went well.
I could run `qupzilla` and also `qtcreator` and build a rather large project.

So from my point of view this WIP is done now.

**Comment by xtraeme** [comment]
@pullmoll great, ty!

**Comment by pullmoll** [comment]
Done with #3855
