### ISSUE TITLE
OpenSC: undefined symbol ENGINE_load_gost

### ISSUE THREAD

**Issue by xaduha** [voidlinux/void-packages#3865]
When used with a working cardreader and a card

`$ pkcs11-tool -L`

`pkcs11-tool: symbol lookup error: /usr/lib/opensc-pkcs11.so: undefined symbol: ENGINE_load_gost`

Looks like GOST was either removed or reworked in LibreSSL

https://en.wikipedia.org/wiki/LibreSSL#Old_insecure_features

But OpenSC still expects OpenSSL options like OPENSSL_NO_GOST

https://github.com/OpenSC/OpenSC/blob/5dd806815de8ee56c4458a6a00ec7404aa6241b8/src/pkcs11/openssl.c#L183-L185

I don't know what a proper solution should be, probably a local patch, not an upstream one.

**Comment by xaduha** [comment]
[patch.txt](https://github.com/voidlinux/void-packages/files/180484/patch.txt)

Fixes it for me, since I don't need GOST.

**Comment by Vaelatern** [comment]
Seems like an upstream patch would be in order, for OpenSC.
