### ISSUE TITLE
p7zip has potentially become nonfree software

### ISSUE THREAD

**Issue by dominikh** [voidlinux/void-packages#3870]
We've recently bumped p7zip from version 9.38.1 to 15.09. Version 15.09 has support for the RAR5 format, by using the nonfree unrar code. Also, we now list the license as "LGPL-2.1, unrar", and the unrar license reads as such:

    The decompression engine for RAR archives was developed using source 
    code of unRAR program.
    All copyrights to original unRAR code are owned by Alexander Roshal.

    The license for original unRAR code has the following restriction:

    The unRAR sources cannot be used to re-create the RAR compression algorithm, 
    which is proprietary. Distribution of modified unRAR sources in separate form 
    or as a part of other software is permitted, provided that it is clearly
    stated in the documentation and source comments that the code may
    not be used to develop a RAR (WinRAR) compatible archiver.

This effectively makes p7zip, as long as the unrar support is enabled, nonfree software and should be moved to the nonfree repo. Debian etc apparently solve it by having two packages, p7zip and p7zip-rar, one of which is nonfree. One can probably just move `/usr/lib/p7zip/Codecs/Rar.so` into the p7zip-rar package (haven't tested it).

/cc @chneukirchen

**Comment by chneukirchen** [comment]
FWIW, 9.38 contained the code with this license already.

The license is non-free in terms of DFSG/OSD, but it is not a problem to distribute binaries nor sources.

I don't mind it split out (since unrar is in nonfree already), go ahead.

**Comment by dominikh** [comment]
Yes, it's fine to distribute it. Just as it's fine to distribute all the things in the nonfree repo. But the repo is explicitly about not being free in the DFSG sense.

I'll split it out.

**Comment by chneukirchen** [comment]
It's also fine to modify and distribute modified versions, so it's not really like the other packages in nonfree.

I did not know we care about DFSG in particular (else we'd need to remove quite a bit of GFDL docs too), so perhaps this could be clarified.

Currently `Manual.md` says "`nonfree`: Repository for closed source packages."

**Comment by dominikh** [comment]
You can't take the code and modify it in certain ways. In my books, that's nonfree. (In the same vein that "this code mustn't be used for evil" isn't free.)

We're not as strict as DFSG, no, but they're useful guidelines.

**Comment by Vaelatern** [comment]
a26875c

**Comment by dominikh** [comment]
Oops, thanks.
