### ISSUE TITLE
Package request: HTML-XML-utils

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#3871]
(((yesterday I asked for 'pdmenu': being that 'issue' immediately satisfied but already closed, I wish to thank here! you all are fantastic!!)))

another software that I often used in my script is [HTML-XML-utils](http://www.w3.org/Tools/HTML-XML-utils/) by W3C, a number of simple utilities for manipulating HTML and XML files 

[HTML-XML-utils manual](http://dev.man-online.org/man1/hxextract/)
perhaps also be interesting for others? ..

**Comment by ebfe** [comment]
#3872
