### ISSUE TITLE
Package request: iselect

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#3876]
[OSSP iselect](http://www.ossp.org/pkg/tool/iselect/)
a little but (I belive) very useful utility for the console and scripting.

not updated for years but still a valid program that I would like to use.
as such an alternative I know [percol](https://github.com/mooz/percol) but 'cause this is being written in python, for performance reasons I tend to prefer 'iselect'..

**Comment by chneukirchen** [comment]
Try peco, which is like percol but in Go and already packaged.

**Comment by paoloschi** [comment]
ah, interesting! I did not know 'peco', I'm testing now ..
however 'iselect' allows multiple selection and possibility of different action (via definable hotkey) for each selection made..
I'm not finding these things in 'Peco' anyway thanks for the hint!

**Comment by paoloschi** [comment]
ah yes, multiple selection is also possible in 'peco', I apologize for my inobservance !!
