### ISSUE TITLE
Make Python 3 as the default Python

### ISSUE THREAD

**Issue by onlurking** [voidlinux/void-packages#3877]
Void is still using python2 as the default, Python 2 is being deprecated since it's final release "2.7" which came out in 2010, after that they released only bugfixes mostly.
What about use Python 3 for the default Python? Arch already uses Python 3, [Fedora](https://fedoraproject.org/wiki/Changes/Python_3_as_Default) and even [Ubuntu](https://wiki.ubuntu.com/Python) is already moving to Python 3.

**Comment by the-maldridge** [comment]
Moving forwards without consideration for what is left behind is always foolish.  There are several key packages that are not available on python3 yet which are core dependancies for a large amount of software (python-mysqldb comes to mind).

If you wish to see a complete list, just look here: https://python3wos.appspot.com/

My personal vote is to hold at 2.7 until at the very least python-mysqldb or replacement is available, and until ansible is available on python3 (strictly my site is also waiting on python-ldap to be brought up as well).

**Comment by onlurking** [comment]
Not a problem if you distribute the packages as "python2-package" instead of the default "python-package", and update all the softwares depends to use the "python2-package" version, this is how Arch handle this.

The problem with python2 will be the migration, better now than late because it will be a lot harder to migrate to python3 in the future.

**Comment by the-maldridge** [comment]
I look forward to seeing your PR.

**Comment by chneukirchen** [comment]
Python 2 scripts should use python2 in shebang and python 3 uses python3, and we package all available libs anyway, so this really is a non-issue.
