### ISSUE TITLE
Python shebangs

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#3879]
Python shebang lines should explicitly mention the Python version used.

On my system, this is violated by 

- [ ] /usr/bin/bno_plot.py:#! /usr/bin/env python
- [ ] /usr/bin/d-feet:#!/usr/bin/python
- [ ] /usr/bin/dstat:#!/usr/bin/env python
- [ ] /usr/bin/gdbus-codegen:#!/usr/bin/python
- [ ] /usr/bin/git-clang-format:#!/usr/bin/env python
- [ ] /usr/bin/gnome-tweak-tool:#!/usr/bin/env python
- [ ] /usr/bin/gsettings-schema-convert:#!/usr/bin/env python
- [ ] /usr/bin/gtester-report:#!/usr/bin/python
- [ ] /usr/bin/gtk-builder-convert:#!/usr/bin/env python
- [ ] /usr/bin/mountstats:#!/usr/bin/env python
- [ ] /usr/bin/mpaste:#!/usr/bin/python
- [ ] /usr/bin/nfsiostat:#!/usr/bin/python
- [ ] /usr/bin/purple-remote:#!/usr/bin/env python
- [ ] /usr/bin/purple-url-handler:#!/usr/bin/env python
- [ ] /usr/bin/pygmentize:#!/usr/bin/python
- [ ] /usr/bin/svgtoipe:#!/usr/bin/env python

**Comment by Gottox** [comment]
We can add a post_install hook to rewrite the shebangs.

**Comment by ebfe** [comment]
usr/bin/avahi-bookmarks:#!/usr/bin/python
usr/bin/avahi-discover:#!/usr/bin/python
usr/bin/chardetect:#!/usr/bin/python
usr/bin/csscapture:#!/usr/bin/python
usr/bin/csscombine:#!/usr/bin/python
usr/bin/cssparse:#!/usr/bin/python
usr/bin/cvs2bzr:#!/usr/bin/python
usr/bin/cvs2git:#!/usr/bin/python
usr/bin/cvs2svn:#!/usr/bin/python
usr/bin/econnman-bin:#!/usr/bin/python
usr/bin/gajim:exec "/usr/bin/python" -OO $APP.py "$@"
usr/bin/gajim-history-manager:exec "/usr/bin/python" -OO $APP.py "$@"
usr/bin/gajim-remote:exec "/usr/bin/python" -OO $APP.py "$@"
usr/bin/grc:#! /usr/bin/python
usr/bin/grcat:#! /usr/bin/python
usr/bin/gtkdoc-depscan:#!/usr/bin/python
usr/bin/hamster-service:#!/usr/bin/python
usr/bin/itstool:#!/usr/bin/python -s
usr/bin/keyring:#!/usr/bin/python
usr/bin/kupfer:PYTHON="/usr/bin/python"
usr/bin/kupfer-exec:PYTHON='/usr/bin/python'
usr/bin/pygmentize:#!/usr/bin/python
usr/bin/pyrsa-decrypt:#!/usr/bin/python
usr/bin/pyrsa-decrypt-bigfile:#!/usr/bin/python
usr/bin/pyrsa-encrypt:#!/usr/bin/python
usr/bin/pyrsa-encrypt-bigfile:#!/usr/bin/python
usr/bin/pyrsa-keygen:#!/usr/bin/python
usr/bin/pyrsa-priv2pub:#!/usr/bin/python
usr/bin/pyrsa-sign:#!/usr/bin/python
usr/bin/pyrsa-verify:#!/usr/bin/python
usr/bin/speedometer:#!/usr/bin/python
usr/bin/sphinx-apidoc:#!/usr/bin/python
usr/bin/sphinx-autogen:#!/usr/bin/python
usr/bin/sphinx-build:#!/usr/bin/python
usr/bin/sphinx-quickstart:#!/usr/bin/python
usr/bin/unidecode:#!/usr/bin/python
usr/bin/xml2po:#!/usr/bin/python

**Comment by ebfe** [comment]
usr/bin/ovs-vlan-test:#! /usr/bin/python
usr/bin/tragesym:#!/usr/bin/python
usr/bin/ovs-bugtool:#! /usr/bin/python
usr/bin/dbufstat.py:#!/usr/bin/python
usr/bin/hp-uninstall:#!/usr/bin/python
usr/bin/caribou-preferences:  datadir="$(/usr/bin/python -c "from gi.repository import GLib; print ':'.join(GLib.get_system_data_dirs())")"
usr/bin/caribou-preferences:/usr/bin/python -c "
usr/bin/ovn-docker-overlay-driver:#! /usr/bin/python
usr/bin/storm:#!/usr/bin/python
usr/bin/ffado-diag:#!/usr/bin/python
usr/bin/nfsiostat:#!/usr/bin/python
usr/bin/idjc:#! /usr/bin/python
usr/bin/hp-logcapture:#!/usr/bin/python
usr/bin/crit:#!/usr/bin/python
usr/bin/dtrace:#!/usr/bin/python
usr/bin/xen-ringwatch:#!/usr/bin/python
usr/bin/cinnamon-extension-tool:#!/usr/bin/python
usr/bin/gtester-report:#!/usr/bin/python
usr/bin/pyscss:#!/usr/bin/python
usr/bin/xentrace_format:#!/usr/bin/python
usr/bin/pump:# value for /usr/bin/python, /usr, etc.
usr/bin/pump:PYTHON=/usr/bin/python
usr/bin/pygobject-codegen-2.0:exec /usr/bin/python $codegendir/codegen.py "$@"
usr/bin/mpaste:#!/usr/bin/python
usr/bin/ovs-dpctl-top:#! /usr/bin/python
usr/bin/xen-bugtool:#!/usr/bin/python
usr/bin/units_cur:#!/usr/bin/python
usr/bin/ovn-docker-underlay-driver:#! /usr/bin/python
usr/bin/arc_summary.py:#!/usr/bin/python
usr/bin/libglade-convert:#!/usr/bin/python
usr/bin/ovs-l3ping:#! /usr/bin/python
usr/bin/pcsc-spy:#! /usr/bin/python
usr/bin/pyCecClient.py:#! /usr/bin/python
usr/bin/bokken:#!/usr/bin/python
usr/bin/gdbus-codegen:#!/usr/bin/python
usr/bin/ovs-test:#! /usr/bin/python
usr/bin/ovs-pcap:#! /usr/bin/python
usr/bin/hp-upgrade:#!/usr/bin/python
usr/bin/xencons:#!/usr/bin/python
usr/bin/g-ir-annotation-tool:#!/usr/bin/env /usr/bin/python
usr/bin/dropbox:#!/usr/bin/python
usr/bin/ovs-tcpundump:#! /usr/bin/python
usr/bin/ffado-mixer:#!/usr/bin/python
usr/bin/d-feet:#!/usr/bin/python
usr/bin/g-ir-scanner:#!/usr/bin/env /usr/bin/python
usr/bin/hp-doctor:#!/usr/bin/python
usr/bin/arcstat.py:#!/usr/bin/python
usr/bin/ibus-setup:exec /usr/bin/python /usr/share/ibus/setup/main.py $@
usr/bin/ovs-parse-backtrace:#! /usr/bin/python

**Comment by ebfe** [comment]
usr/bin/gnome-time-tracker:#!/usr/bin/env python
usr/bin/a2x.py:#!/usr/bin/env python
usr/bin/a2x:#!/usr/bin/env python
usr/bin/statnot:#!/usr/bin/env python
usr/bin/scons-2.4.1:#! /usr/bin/env python
usr/bin/scons-time-2.4.1:#!/usr/bin/env python
usr/bin/scons-time:#!/usr/bin/env python
usr/bin/gnome-tweak-tool:#!/usr/bin/env python
usr/bin/gespeaker:env python gespeaker.py
usr/bin/asciidoc.py:#!/usr/bin/env python
usr/bin/anki:#!/usr/bin/env python
usr/bin/sconsign-2.4.1:#! /usr/bin/env python
usr/bin/dstat:#!/usr/bin/env python
usr/bin/scons:#! /usr/bin/env python
usr/bin/bleachbit:#!/usr/bin/env python
usr/bin/scan-view:#!/usr/bin/env python
usr/bin/deheader:#!/usr/bin/env python
usr/bin/mmaker:#!/usr/bin/env python
usr/bin/hamster-cli:#!/usr/bin/env python
usr/bin/asciidoc:#!/usr/bin/env python
usr/bin/unoconv:#!/usr/bin/env python
usr/bin/hamster-time-tracker:#!/usr/bin/env python
usr/bin/sconsign:#! /usr/bin/env python
usr/bin/svgtoipe:#!/usr/bin/env python
usr/bin/gupnp-binding-tool:#! /usr/bin/env python
usr/bin/hp-config_usb_printer:#!/usr/bin/env python
usr/bin/CTK-run:#!/usr/bin/env python
usr/bin/gtk-builder-convert:#!/usr/bin/env python
usr/bin/hp-probe:#!/usr/bin/env python
usr/bin/lv2specgen.py:#!/usr/bin/env python
usr/bin/garchive:#! /usr/bin/env python
usr/bin/hp-scan:#!/usr/bin/env python
usr/bin/btplay:#!/usr/bin/env python
usr/bin/hotshot2calltree:#!/usr/bin/env python
usr/bin/bno_plot.py:#! /usr/bin/env python
usr/bin/hp-pkservice:#!/usr/bin/env python
usr/bin/mono-heapviz:#!/usr/bin/env python
usr/bin/hp-wificonfig:#!/usr/bin/env python
usr/bin/hp-firmware:#!/usr/bin/env python
usr/bin/hp-sendfax:#!/usr/bin/env python
usr/bin/blueman-browse:#!/usr/bin/env python
usr/bin/hp-unload:#!/usr/bin/env python
usr/bin/hp-timedate:#!/usr/bin/env python
usr/bin/hp-plugin:#!/usr/bin/env python
usr/bin/blueman-report:#!/usr/bin/env python
usr/bin/blueman-sendto:#!/usr/bin/env python
usr/bin/hp-diagnose_plugin:#!/usr/bin/env python
usr/bin/run-single-task:#!/usr/bin/env python
usr/bin/purple-remote:#!/usr/bin/env python
usr/bin/hp-faxsetup:#!/usr/bin/env python
usr/bin/mountstats:#!/usr/bin/env python
usr/bin/run-game:#!/usr/bin/env python
usr/bin/hp-makecopies:#!/usr/bin/env python
usr/bin/hp-devicesettings:#!/usr/bin/env python
usr/bin/telepathy-gabble-xmpp-console:#!/usr/bin/env python
usr/bin/blueman-manager:#!/usr/bin/env python
usr/bin/hp-fab:#!/usr/bin/env python
usr/bin/cppcheck-htmlreport:#!/usr/bin/env python
usr/bin/hp-print:#!/usr/bin/env python
usr/bin/hp-colorcal:#!/usr/bin/env python
usr/bin/purple-url-handler:#!/usr/bin/env python
usr/bin/ulatency-gui:#!/usr/bin/env python
usr/bin/hp-info:#!/usr/bin/env python
usr/bin/vigra-config:#!/usr/bin/env python
usr/bin/ulatency:#!/usr/bin/env python
usr/bin/gsettings-schema-convert:#!/usr/bin/env python
usr/bin/jack_control:#!/usr/bin/env python
usr/bin/hp-makeuri:#!/usr/bin/env python
usr/bin/iceca:#!/usr/bin/env python
usr/bin/hp-align:#!/usr/bin/env python
usr/bin/blueman-adapters:#!/usr/bin/env python
usr/bin/hp-levels:#!/usr/bin/env python
usr/bin/ladish_control:#!/usr/bin/env python
usr/bin/hp-linefeedcal:#!/usr/bin/env python
usr/bin/xenmon.py:#!/usr/bin/env python
usr/bin/hp-systray:#!/usr/bin/env python
usr/bin/hp-setup:#!/usr/bin/env python
usr/bin/blender-thumbnailer.py:#!/usr/bin/env python
usr/bin/a2j_control:#!/usr/bin/env python
usr/bin/lou_harnessGenerator:#!/usr/bin/env python
usr/bin/aot-compile:#!/usr/bin/env python
usr/bin/g-ir-annotation-tool:#!/usr/bin/env /usr/bin/python
usr/bin/hwmixvolume:#!/usr/bin/env python
usr/bin/seaf-cli:#!/usr/bin/env python
usr/bin/hp-diagnose_queues:#!/usr/bin/env python
usr/bin/qpaeq:#!/usr/bin/env python
usr/bin/atari-hd-image:#!/usr/bin/env python
usr/bin/hp-printsettings:#!/usr/bin/env python
usr/bin/hp-query:#!/usr/bin/env python
usr/bin/blueman-applet:#!/usr/bin/env python
usr/bin/g-ir-scanner:#!/usr/bin/env /usr/bin/python
usr/bin/hp-clean:#!/usr/bin/env python
usr/bin/hp-testpage:#!/usr/bin/env python
usr/bin/hp-pqdiag:#!/usr/bin/env python
usr/bin/blueman-assistant:#!/usr/bin/env python
usr/bin/blueman-services:#!/usr/bin/env python
usr/bin/hatari_profile.py:#!/usr/bin/env python
usr/bin/hp-check:#!/usr/bin/env python
usr/bin/bup:#!/usr/bin/env python

**Comment by ebfe** [comment]
That should be all (x86_64 and noarch packages).

**Comment by Vaelatern** [comment]
With 830ca26 and 6606995 and 05b15f6 it seems the easy fix is just to revbump any packages suffering from this issue. Either that or simply close the issue knowing that future packges won't have these problems.

**Comment by Vaelatern** [comment]
@chneukirchen @Gottox
Move to close this issue due to no longer being relevant.
