### ISSUE TITLE
07-rewrite-python-shebang.sh hook broken

### ISSUE THREAD

**Issue by asergi** [voidlinux/void-packages#3912]
Simply doesn't work as intended.
It always rewrite `#!/usr/bin/python2.7`, even for Python 3.x modules.
```
=> WARNING: python3.4-pytz: multiple python versions defined!
=> WARNING: python3.4-pytz: using 2.7 for shebang   Unversioned shebang replaced by '#!/usr/bin/python2.7': /usr/lib/python3.4/site-packages/pytz/tzfile.py
```
To reproduce that, make sure to remove the `pre_build` function from the `python-pytz` template (that's why the update to version 2016.3 worked, even though the hook is broken).

Please, also note that in many python-foo templates the shebangs were already stripped (since they're useless in non-executable scripts).
When this hook will be ok, those tricks will be unncessary and gradually removed in the future.

Please do **not** update python modules till this hook is fixed.

(Sorry, I'm away home and can't do more for now.)

/cc @Gottox

**Comment by Gottox** [comment]
Thanks, on it.

**Comment by Gottox** [comment]
6606995831a0e1ef40cd9f68a1d02f38ec4dd524

please recheck.

**Comment by asergi** [comment]
Works now. Thanks.
