### ISSUE TITLE
Update Qupzilla to 2.0.0

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#3946]
Qupzilla just released version 2.0.0 with QtWebEngine
http://blog.qupzilla.com/2016/03/qupzilla-200-released-with-qtwebengine.html

Maintainer of [template](https://github.com/voidlinux/void-packages/blob/a74304b9719f6157c750dd68832ce37aeb2bd7e0/srcpkgs/qupzilla/template): @pullmoll 

An update would be greatly appreciated :)

(I couldn't check, if the template needs major adjustments, since Qupzilla needs 15+ hours to compile on my Intel Atom)

**Comment by pullmoll** [comment]
This requires some additions to qt5 first, because 5.6.0 introduced new modules.

I'm working on it.

**Comment by pullmoll** [comment]
It's upgraded to 2.0.0 now. Seems to work fine here.

**Comment by JayVii** [comment]
Thanks for the quick update!
Does work, except for [Issue 3962](https://github.com/voidlinux/void-packages/issues/3962)
