### ISSUE TITLE
Openbox & svg icons

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#3947]
[short version]
was Openbox (musl) built with svg support?

[full version]
I've installed Void by bootstrap on a BTRFS sub-volume.
first I've installed all the [base-packages](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/base-system/template)+kernel+grub.
afterwards xorg+openbox+tint2+spacefm+gnome-icon themes as a base for my desktop..
happens to me to have no rendering of svg icons in openbox menu, tint2 panel and so on..
packages 'librsvg' and 'librsvg-utils' are installed.
if I switch to the tty1 I see a long list of warnings like this, one for each icon to load:

    ***** Imlib2 Developer Warning ***** :
        This program is calling the Imlib call:

        imlib_free_image();

        With the parameter:

        image

        being NULL. Please fix your program.
    ObRender-Message: Cannot load image "/usr/share/icons/hicolor/scalable/apps/tint2.svg" from file "/usr/share/icons/hicolor/scalable/apps/tint2.svg"

**Comment by Vaelatern** [comment]
Not by default, but the code is in the template. You can build it yourself if you like, but I feel we should probably do so by default.

**Comment by paoloschi** [comment]
ah well, it's as I imagined..
I think I will wait for official implementation.
as for me, this issue can be closed....
