### ISSUE TITLE
xbps feature request

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#3950]
before trying Void, I'd read in the official wiki that xbps has the "ability to execute pre/post install/remove/update scriptlets"
probably I had misunderstood the meaning of such declaration..

now, as I'm trying to complete my transition from Debian to Void, seems to me that I can't do with xbps an operation that instead I did with dpkg since I've put my root system on Btrfs:
in Debian, through a 'hook' placed precisely between the successful completion of all packages download and the beginning of the installation and configuration jobs, dpkg allows me to make a automatic Btrfs snapshot, thus only if it is indeed the case!
in fact, if I perform snapshots systematically before each xbps-install/remove operation but then I say 'no' to the confirmation to continue or xbps can not proceed by itself, then I will have done a totally useless snapshot..

as a partial workaround, I thought I could maybe scripting a first xbps simulated session (--dry-run) and then, only if the action will be continued, to proceed making a manual BTRFS snapshot followed by a second noninteractive xbps session (--yes option)..
..just an idea, not tried this yet but seems to me that would be certainly be more desirable if xbps would allow to interact during his actions, based on certain events, similar to the pre/post-invoke dpkg mechanism (..)

(as a side note, just curious: I noticed that dpkg is present in the official packages but I can not imagine how dpkg can be usefull or can interact inside a Void system....)

**Comment by chneukirchen** [comment]
There are no user hooks currently, write your own wrappers.  You could also check if xbps did anything and then remove the snapshot again. ;)

dpkg is useful to build .deb packages on Void.

**Comment by xtraeme** [comment]
This is not the place to request features for the pkg manager (xbps).

Use https://github.com/voidlinux/xbps instead.

Thanks.
