### ISSUE TITLE
Utilize the pull-request and issue templates feature

### ISSUE THREAD

**Issue by Arzte** [voidlinux/void-packages#3956]
https://github.com/blog/2111-issue-and-pull-request-templates

As a note to any one who does this, you can use html comments for instructions in the templates. Since Markdown respects html formatting, this means unless your viewing it raw, you wouldn't see the note you leave to pr and issue creators.

**Comment by Vaelatern** [comment]
The issue is we don't have just one sort of issue or one sort of PR, any framework possible would be too restricting or ill-suited to our use case.

**Comment by chneukirchen** [comment]
We do this for some time now.
