### ISSUE TITLE
Package request: Backupninja

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#3961]
despite Void already offers a number of backup solutions, I've not found one that fits for me as a functional [Backupninja](https://labs.riseup.net/code/projects/backupninja/repository) alternative..

**Comment by ebfe** [comment]
Please give this a try #3963

**Comment by paoloschi** [comment]
@ebfe if the invitation is addressed to me, I do not know how I can give it a try
(I do not have a build env..)

**Comment by ebfe** [comment]
It's easy to set up (if you want to):

    # setup build environment
    git clone https://github.com/voidlinux/void-packages
    cd void-packages
    ./xbps-src binary-bootstrap
    # checkout the pull-request
    git fetch origin pull/3963/head:backupninja
    git checkout backupninja
    # build package
    ./xbps-src pkg backupninja
    # install
    sudo xbps-install -R hostdir/binpkgs/backupninja backupninja

**Comment by paoloschi** [comment]
really easy, you were right! :-)
thanks for teaching ..

all performed successfully regarding compilation.

to test the backupninja performance I used my configuration and project-scripts I have always used in Debian (..) 
the first run of backupninja failed with the error:

    Debug: check_perms /etc/backup.d
    Debug: perms: drwxr-xr-x
    Debug: gperm: r-x
    Debug: wperm: r-x
    Configuration files must not be world writable/readable! Dying on file /etc/backup.d
    Fatal: Configuration files must not be world writable/readable! Dying on file /etc/backup.d

so I think the template directive

    15 +make_dirs="/etc/backup.d 0755 root root"

should be changed so that the directory `/etc/backup.d` it is created with permissions 0700

after I manually done a chmod, my first 'rdiff' backup has succeeded perfectly :-)

**Comment by paoloschi** [comment]
yes, it is correct: 0750 is sufficient, It does not seem necessary to put mode bits at 0700
it works now!

**Comment by ebfe** [comment]
Thanks, for testing
