### ISSUE TITLE
SSL bug in qt5-webengine

### ISSUE THREAD

**Issue by JayVii** [voidlinux/void-packages#3962]
The new Qupzilla 2.0.0 (now using qtwebengine) can not connect to google-related https-sites (including google.com and youtube.com). I mailed the Qupzilla developers and got following answer:
> Hi,
> that's a bug with QtWebEngine build.
> Please report to your distribution.

I searched for said issue and found following:
[Qupzilla: Broken SSL for some sites](https://github.com/QupZilla/qupzilla/issues/1870)
[Patch that supposedly fixes this issue from KaOS](https://github.com/KaOSx/main/blob/master/qtwebengine/nss321.diff)

Original mail-conversation with developer:
> Hi,                                                                                                                            
> that's a bug with QtWebEngine build. Please report to your distribution.                                                       
>                                                                                                                               
> David                                                                                                                          
>                                                                                                                                
> On Sat, Apr 2, 2016 at 7:22 PM,  <janwey.git@gmail.com> wrote:                                                                 
> Operating System:       Linux                                                                                                
> Application Version:    2.0.0                                                                                                
> Qt Version:     5.6.0 (built with 5.6.0)                                                                                     
> WebKit Version:         QtWebEngine                                                                                          
>                                                                            
>                                                                                                                              
> whenever I try to reach a google-website (including everything chrome/chromium related, youtube, google.com, ...), I receive 
following error:                                                                                                               
> "SSL connection error                                                                                                        
> ERR_SSL_PROTOCOL_ERROR"                                                                                                      
>                                                                                                                              
> Other browsers (chromium, firefox, netsurf) work on these domains, as well as previous versions of Qupzilla.                 
> Restarting the browser and rebooting the whole device didn't help either.

**Comment by pullmoll** [comment]
I can very well connect to https://google.com here, and also to https://youtube.com with QupZilla 2.0.0.

Perhaps it's a configuration issue on your side?
Did qupzilla tell you it created a backup of your data (browsedata-backup.db) due to a format change?
Do you use a (transparent) proxy?
You might try to create a new profile and see if https://google.com then works for you.

I have no idea what else to look for. There is no certificate management in QupZilla and the system ca-certificates will most probably be used as is.

**Comment by JayVii** [comment]
I created a new profile for Qupzilla yet again - just to make sure.
I also tried the quicknanobrowser, you mentioned.

In both cases, I can not connect to either [google.com](https://google.com) or [youtube.com](https://youtube.com).

For debug purposes, I have the outputs of both browsers, navigating to youtube.com below. Eventhough I'm not sure if it even matters...
Quicknanobrowser (qt5-examples):
```
js: Font from origin 'http://d3hp9ud7yvwzy0.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.qt.io' is therefore not allowed access.
js: /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```
By the way: I can not connect to chromestatus.com with a QtWebEngine browser, either (obviously, a google-site as well).


So, if it's my end and new profiles didn't help, what else could it be? As mentioned in my mail already, other browsers work perfectly fine.

**Comment by ebfe** [comment]
quicknanobrowser and qupzilla load https://google.com and https://youtube.com without problems here.
Both seem to use the certs in /etc/ssl/certs (that ca-certificates). @JayVii you might want to try  `update-ca-certificates -f` to populate /etc/ssl/certs.

**Comment by JayVii** [comment]
```
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
170 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```
Restarted Qupzilla afterwards, but the issue still persists.
Same goes for quicknanobrowser.

**Comment by ebfe** [comment]
What does `strace -e file -f qupzilla https://google.com |& grep /etc/ssl` say?

**Comment by JayVii** [comment]
```
λ ~/ strace -e file -f qupzilla https://google.com |& grep /etc/ssl

[pid  4499] open("/etc/ssl/openssl.cnf", O_RDONLY <unfinished ...>
[pid  4499] open("/etc/ssl/certs/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 98
[pid  4499] statfs("/etc/ssl/certs/", {f_type="EXT2_SUPER_MAGIC", f_bsize=4096, f_blocks=58746578, f_bfree=51249077, f_bavail=48259151, f_files=14934016, f_ffree=14530503, f_fsid={339931133, -227310382}, f_namelen=255, f_frsize=4096, f_flags=4128}) = 0
[pid  4499] stat("/etc/ssl/certs/749e9e03.0", {st_mode=S_IFREG|0644, st_size=1923, ...}) = 0
```

**Comment by pullmoll** [comment]
If you use NetworkManager to connect to the internet, you could go the network configuration and try to set the connection's IPv6 settings to `automatic, DHCP only`, i.e. the fourth entry. Then disconnect and connect again to see if that helps.

My dialog is German, the entry name is guessed :)

**Comment by ebfe** [comment]
Can reproduce now on x86_64-musl.

**Comment by ebfe** [comment]
google.com is refusing the ClientHello from the browser with an TLSv1.1 Record Layer: Alert (Level: Fatal, Description: Inappropriate Fallback). Maybe something went wrong with all the libressl patches that somehow only affects musl?

**Comment by JayVii** [comment]
I'm using wpa_supplicant & wpa_gui, but i'll try NetworkManager.
Also, i'm **not** using musl.

Again, all other browsers work perfectly fine.

**Comment by ebfe** [comment]
Connection attempt is made with TLSv1.2 but the browser drops the connection after receiving ServerKeyExchange. Then it tries TLSv1.1 with TLS_FALLBACK_SCSV which google.com refuses since it supports TLSv1.2. Question is why does the first attempt only fail on some systems...

**Comment by ebfe** [comment]
First attempt fails if server chooses TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite. qupzilla works on x86_64 for me because it doesn't advertise support for that cipher suite, on x86_64-musl it does and fails. No idea what cause the difference in behaviour and even less why it happens on non-musl for @JayVii.

**Comment by pullmoll** [comment]
Looking up the certificate `/etc/ssl/certs/749e9e03.0` it is `/etc/ssl/certs/QuoVadis_Root_CA_1_G3.pem` and verifying that with openssl results in an error here
```
jbu@box:~$ openssl verify -crl_check /etc/ssl/certs/QuoVadis_Root_CA_1_G3.pem 
/etc/ssl/certs/QuoVadis_Root_CA_1_G3.pem: C = BM, O = QuoVadis Limited, CN = QuoVadis Root CA 1 G3
error 3 at 0 depth lookup:unable to get certificate CRL
```

I have no idea if this could be the root cause, though.

**Comment by ebfe** [comment]
I think a certificate error would produce a different error.

**Comment by pullmoll** [comment]
> I think a certificate error would produce a different error message.

Well, you're probably right. The 3 certificates listed above all produce the same message with `openssl verify -crl_check`. I wonder why https://google.com seems to offer a different root CA to me compared to what @JayVii gets to see.

**Comment by pullmoll** [comment]
Perhaps the best solution to this problem was to create a `qupzilla1` package equal to the previous `qupzilla` for those who have problems with 2.0.0 or newer.

**Comment by JayVii** [comment]
thanks @pullmoll

**Comment by JayVii** [comment]
Okay, I'm in a different location (different network), with a different machine (also x86_64, non-musl), just installed Qupzilla-2.0.0 on here to see if it's my machine or not...
But I have the same issue on THIS machine.

**Comment by pullmoll** [comment]
This issue now hit me as well with the new https://repo.voidlinux.eu certificates and I applied the "chimera build" build successfully here to fix it. The coming qt5-5.6.0_7 should solve it for everyone.

**Comment by JayVii** [comment]
@pullmoll this fixed the issue, for me at least.
[Screenshot of Google working correctly](http://i.imgur.com/jvM6Eha.png)

**Comment by pullmoll** [comment]
Thanks for testing and glad we have it fixed for now.
