### ISSUE TITLE
Package Request: Geary, GNOME e-mail client

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#3983]
Minimalistic but in my opinion really good e-mail client by GNOME.
https://wiki.gnome.org/Apps/Geary

**Comment by Vaelatern** [comment]
[-] geary-0.10.0_1 A lightweight email program for the GNOME desktop

**Comment by 38github** [comment]
Sorry forgot to mention for the musl version, if that is possible.

**Comment by Vaelatern** [comment]
Resolved with 9f92a0e
