### ISSUE TITLE
Package Request: Mint Menu for MATE.

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#3985]
https://bitbucket.org/ubuntu-mate/mate-menu

**Comment by cr6git** [comment]
THIS PROJECT HAS MOVED TO: https://github.com/ubuntu-mate/mate-menu

**Comment by cr6git** [comment]
It's done.

**Comment by 38github** [comment]
Thank you very much!

**Comment by cr6git** [comment]
Yeah, an the [update for mate-menu](https://github.com/voidlinux/void-packages/pull/12713) _is rotting away_, in the long list of PRs... :unamused:

**Comment by cr6git** [comment]
:smiley: Updated in [f1fa2ed](https://github.com/voidlinux/void-packages/commit/f1fa2ed1aafaafd86d9380be196b4865c93e0493) just a couple of hours ago! :tada:
