### ISSUE TITLE
dbus: dbus-uuidgen not run on install

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#3993]
It seems in a recent version of the dbus package a regression has happened and the dbus-uuidgen program does not get run during the package install.

**Comment by Vaelatern** [comment]
I do not believe we ever ran `dbus-uuidgen` during install, going back to the systemd days at least.

That said, it might be a good idea.

**Comment by the-maldridge** [comment]
If my understanding is correct, it should be done on line 7 of this file: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dbus/INSTALL

However, I had to manually run it on a fresh install before dbus was usable.

**Comment by Vaelatern** [comment]
This matches my experience. Anybody else know if the line has been acting correctly? @Duncaen you have noticed this behaviour as well, when I asked for help on starting dbus programs, if I recall correctly.

**Comment by xtraeme** [comment]
dbus-uuidgen is run in its runit service.

Thanks

**Comment by xtraeme** [comment]
Err sorry, I meant that `dbus-uuidgen` is already in its INSTALL script.

**Comment by xtraeme** [comment]
@the-maldridge INSTALL scripts are run before or after the unpacking phase.

- in `pre` the action is run *before* unpacking.
- in `post` the action is run *after* unpacking, and runs in the *configuration* phase.

xbps separates those two phases. If you are setting XBPS_ARCH or XBPS_TARGET_ARCH, the configuration phase might be skipped.

Take a look at void-mklive/mkrootfs.sh for details.

**Comment by the-maldridge** [comment]
While it is in the INSTALL script, it is not actually generating the uuid.  This is reproducable in a new void install quite readily by trying to install dbus, starting it, and then trying to use something that depends on it like awesome.  On request I can build a VM and get the exact error, but it appears to be something generic out of dbus.
