### ISSUE TITLE
libreoffice, libetonyek: build broken by liblangtag-0.6.0 update

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4004]
In file included from /usr/include/liblangtag/lt-ext-module.h:23:0,
                     from /usr/include/liblangtag/langtag.h:20,
                     from /builddir/libreoffice-5.1.0.3/i18nlangtag/source/languagetag/languagetag.cxx:31:
    /usr/include/liblangtag/lt-tag.h:56:14: error: use of enum '_lt_tag_filter_t' without previous declaration
     typedef enum _lt_tag_filter_t lt_tag_filter_t;
                  ^
    /usr/include/liblangtag/lt-tag.h:56:46: error: invalid type in declaration before ';' token
     typedef enum _lt_tag_filter_t lt_tag_filter_t;
                                                  ^
    /builddir/libreoffice-5.1.0.3/solenv/gbuild/LinkTarget.mk:189: recipe for target '/builddir/libreoffice-5.1.0.3/workdir/CxxObject/i18nlangtag/source/languagetag/languagetag.o' failed
    make[1]: *** [/builddir/libreoffice-5.1.0.3/workdir/CxxObject/i18nlangtag/source/languagetag/languagetag.o] Error 1

**Comment by pullmoll** [comment]
I think it's probably just a matter of moving the `typedef enum _lt_tag_filter_t lt_tag_filter_t;` after the definition of the enum. Trying here and will push a fix if it helps.

**Comment by pullmoll** [comment]
Should be fixed with http://build.voidlinux.eu/changes/24220
