### ISSUE TITLE
Package oracle-jdk Does Not Update Correctly

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#4016]
After updating the oracle-jdk package, I noticed a few things:

1.) It breaks eclipse, which can't find the JRE... this may be separate issue; specifically, with needing to update eclipse.ini or /etc/eclipse/java_home during a Java update, _however, is most likely because of items 2.) and 3.)_...

2.) It does not update the symlinks under `/usr/bin`.

3.) It does not remove the previous version (but removes the contents of the `bin` and `jre/lib/amd64` subdirectories).

Per item 2.), for reference, after updating to oracle-jdk, v1.8.0_77, here are the symlinks, under `/usr/bin`\- notice, symlinks point to the previoius version, which, per item 3.), of course, will not work:

```
java -> ../lib/jvm/jdk1.8.0_73/bin/java
java-rmi.cgi -> ../lib/jvm/jdk1.8.0_73/bin/java-rmi.cgi
javac -> ../lib/jvm/jdk1.8.0_73/bin/javac
javadoc -> ../lib/jvm/jdk1.8.0_73/bin/javadoc
javafxpackager -> ../lib/jvm/jdk1.8.0_73/bin/javafxpackager
javah -> ../lib/jvm/jdk1.8.0_73/bin/javah
javap -> ../lib/jvm/jdk1.8.0_73/bin/javap
javapackager -> ../lib/jvm/jdk1.8.0_73/bin/javapackager
javaws -> ../lib/jvm/jdk1.8.0_73/bin/javaws
```

And, per item 3.), the contents of `/usr/lib/jvm` (notice, v1.8.0_73 is still present- however, the `bin` and `jre/lib/amd64` subdirectories are empty):

```
jdk1.8.0_73
jdk1.8.0_77
oracle-jdk -> jdk1.8.0_77
oracle-jdk-vars.sh
```

**Comment by antonio-malcolm** [comment]
BTW, performed a force remove (a la `xbps-remove -F`) and resintalled, which corrected the issues... but that feels like a somewhat messy way of updating a package.

**Comment by Gottox** [comment]
```xbps-alternatives -s oracle-jdk``` after an update should fix that too.

cc @xtraeme: The oracle-jdk alternatives change with every update. I'm considering that an xbps issue.

**Comment by xtraeme** [comment]
@Gottox you can create symlinks to the real cmd for alternatives:

```
 jdk:/usr/bin/ControlPanel:/usr/lib/jvm/jdk${_longVersion}/bin/ControlPanel
```

to
```
 jdk:/usr/bin/ControlPanel:/usr/lib/jvm/oracle-jdk/bin/ControlPanel
```

/usr/lib/jvm/oracle-jdk/bin/ControlPanel -> /usr/lib/jvm/jdk${_longVersion}/bin/ControlPanel

**Comment by Gottox** [comment]
@xtraeme: Suggestion: Treat alternatives as ordinary files of packages, this way they are automaticly removed, recreated or left untouched if the links stays the same.

**Comment by Gottox** [comment]
@xtraeme There was a reason why I didn't do that. Can't remember atm.

**Comment by Gottox** [comment]
See https://github.com/voidlinux/xbps/issues/139
