### ISSUE TITLE
lxc-2.0.0_1.x86_64 and liblxc-2.0.0_1.x86_64 stopped working

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#4018]
After upgrading lxc and liblxc from 1.1.5_1 to 2.0.0_1 guests cannot be started anymore.

Error message in log file is:

lxc-start 20160411103428.395 ERROR    lxc_cgfsng - cgfsng.c:all_controller s_found:431 - no systemd controller mountpoint found
lxc-start 20160411103428.395 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start 20160411103428.409 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'guest'
lxc-start 20160411103433.414 ERROR    lxc_start_ui - lxc_start.c:main:344 - The container failed to start.

downgrading to lxc and liblxc to version 1.1.5_1 fixes the issue.

**Comment by mdkuser** [comment]
According to:  [1] LXC-2.x requires a systemd cgroup mount (need to confirm that).
The new LXC-2.0 package should address this by creating and mounting the new cgroup.
Manually this can be done by:

`mkdir /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd /sys/fs/cgroup/systemd`


[1] http://comments.gmane.org/gmane.linux.kernel.containers.lxc.general/11396

**Comment by mdkuser** [comment]
I confirm the above fixes the issue, but the cgroup is lost after system reboot.
Please instruct how to make that changes permanent.
I still think that should be done via package installer script.

**Comment by mdkuser** [comment]
I found another workaround, installing libcmanager, cgmanager and dbus and enabling cgmanager and dbus in runit fixes the issue as well without the need of creating the systemd cgroup.

Now I am confused.

**Comment by mdkuser** [comment]
BTW: cgmanager requires dbus, which should be added as dependency for the cgmanager package.

**Comment by xtraeme** [comment]
There are multiple ways to mount the systemd cgroup:

1- via /etc/fstab
2- via /etc/rc.local

I can confirm this systemd cgroup is required to be able to start unprivileged containers.

**Comment by bitshark** [comment]
I am having this issue ,with unpriv'd containers.  xtraeme has been very generous with his time to help me get it working, but I've been unable to do so even though we've followed pretty much identical steps.

I kept getting this error no matter what I did (for unpriv containers -- containers as root work fine)...
```bash
     lxc-start 20160417191855.541 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
      lxc-start 20160417191855.541 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for ubuntu
      lxc-start 20160417191855.541 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:431 - no systemd controller mountpoint found
lxc-start: cgfsng.c: all_controllers_found: 431 no systemd controller mountpoint found
      lxc-start 20160417191855.542 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start: start.c: lxc_spawn: 1079 failed initializing cgroup support
      lxc-start 20160417191855.542 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'ubuntu'
```

What's wierd though is a did a chmod a+rwx to the /sys/fs/cgroup/systemd directory (which I created and mounted as root), and now it looks like I get a step further when I have the unpriv user try to boot the container...

```bash
      lxc-start 20160417193631.985 INFO     lxc_start - start.c:lxc_init:488 - 'ubuntu' is initialized
      lxc-start 20160417193631.986 DEBUG    lxc_start - start.c:__lxc_start:1302 - Not dropping cap_sys_boot or watching utmp
      lxc-start 20160417193631.986 INFO     lxc_start - start.c:resolve_clone_flags:999 - Cloning a new user namespace
      lxc-start 20160417193631.986 INFO     lxc_cgroup - cgroup.c:cgroup_init:68 - cgroup driver cgroupfs-ng initing for ubuntu
      lxc-start 20160417193631.986 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:435 - no freezer controller mountpoint found
lxc-start: cgfsng.c: all_controllers_found: 435 no freezer controller mountpoint found
      lxc-start 20160417193631.986 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
lxc-start: start.c: lxc_spawn: 1079 failed initializing cgroup support
      lxc-start 20160417193631.987 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'ubuntu'
```

I opened a github issue with lxcfs since I can't seem to resolve this on my own so far... https://github.com/lxc/lxcfs/issues/106

Steps I took:
1. Set up /etc/subuid and /etc/subgid
2. Create the ~unpriv_user/.config/lxc/default.conf with the gid mappings
3. Created and mount the systemd directory as detailed above
4. Even tried modifying the perms on that directory with minor success but container will not boot unpriv, now has the "freezer" error.

**Comment by xtraeme** [comment]
With https://github.com/voidlinux/void-packages/commit/8e394e3e5c1fd38e6a16effb544de6659c557c63 I can successfully boot any distro with systemd.

Make sure to upgrade and then create/start the unprivileged container.

**Comment by xtraeme** [comment]
Also I noticed that a proper consolekit session is required to be able to start unprivileged containers.

Make sure that `ck-list-sessions` prints an ACTIVE session, otherwise run a session with `ck-launch-session`.

**Comment by mdkuser** [comment]
I confirm it's working now.

**Comment by mdkuser** [comment]
Thanks for fixing

**Comment by mdkuser** [comment]
Need to reopen, latest update breaks lxc-autostart. Manually starting guests works...

**Comment by mdkuser** [comment]
uninstalling ConsoleKIt2 solves the issue, I am running non prvilileged containers started as root.
When ConsoleKit is installed but no symlink in /var/services it will be started anyway and this seems to prevents automatic startup of unprivileged guests started by root.

**Comment by mdkuser** [comment]
lxc-autostart still not working it fails with the following error message in the log:

`lxc-autostart 20160426155517.167 ERROR    lxc_cgfsng - cgfsng.c:all_controllers_found:431 - no systemd controller mountpoint found
  lxc-autostart 20160426155517.167 ERROR    lxc_start - start.c:lxc_spawn:1079 - failed initializing cgroup support
  lxc-autostart 20160426155517.175 ERROR    lxc_start - start.c:__lxc_start:1329 - failed to spawn 'guest'`

It seems we still haven't fixed cgroup issue yet.

**Comment by xtraeme** [comment]
As said previously, a proper consolekit session is required to fix this issue.

IIRC an upcoming consolekit2 version will probably fix this.

**Comment by mdkuser** [comment]
I have the recent consolekit2 package installed and it shows an active session, however it does not fix the lxc-autostart issue.
The strange thing is, while it is not working aut system init, doing a sv restart lxc-autostart will work (and does not log any errors)...

**Comment by Duncaen** [comment]
The `lxc-autostart` doesnt wait for either consolekit2 or cgmanager.
Maybe try to change `/etc/sv/lxc-autostart` to:
```
#!/bin/sh
sv check cgmanager >/dev/null || exit 1
lxc-autostart || exit 1
exec chpst -b lxc-autostart pause
```

**Comment by mdkuser** [comment]
Thanks for the tip Duncaen. It's now working after changing the /etc/sv/lxc-autostart as you suggested.
I guess this should be corrected in the lxc package too and cgmanager should be added as a dependency of lxc.
This issue can be maked as solved.
