### ISSUE TITLE
Firefox sometimes crash

### ISSUE THREAD

**Issue by elroncio** [voidlinux/void-packages#4036]
Sometimes, when I search stuff from the address bar, firefox close without a warning.
Running it from a terminal I get this:

`
(process:6055): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
firefox: res_query.c:262: __libc_res_nquery: asserzione "(hp != NULL) && (hp2 != NULL)" non riuscita.
[Child 6055] ###!!! ABORT: Aborting on channel error.: file /builddir/firefox-45.0.2/ipc/glue/MessageChannel.cpp, line 1861
[Child 6055] ###!!! ABORT: Aborting on channel error.: file /builddir/firefox-45.0.2/ipc/glue/MessageChannel.cpp, line 1861
`

I found some bug report about this:
https://bbs.archlinux.org/viewtopic.php?id=209340
https://sourceware.org/bugzilla/show_bug.cgi?id=13013

I get the same error from transmission too.

**edited by @Gottox** fixed links

**Comment by thebonaestest** [comment]
I'm having a similar problem. Occasionally when I move tabs around or between windows firefox will crash. I've had this problem before, and I quick fixed it by downgrading GTK, but that isn't a long term solution.

Relevant console output:
`(process:7188): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
console.error: 
  Message: TypeError: this.sandbox is undefined
  Stack:
    receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-child.js:77:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/child.js:67:37

console.error: 
  Message: TypeError: this.sandbox is undefined
  Stack:
    receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-child.js:77:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/child.js:67:37

console.error: 
  Message: TypeError: this.sandbox is undefined
  Stack:
    receive@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/worker-child.js:77:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
messageReceived@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/remote/child.js:67:37


(firefox:7143): Gdk-CRITICAL **: gdk_window_peek_children: assertion 'GDK_IS_WINDOW (window)' failed
[Child 7188] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-aurora-l64-ntly-000000000000/build/src/ipc/glue/MessageChannel.cpp, line 1839
[Child 7188] ###!!! ABORT: Aborting on channel error.: file /builds/slave/m-aurora-l64-ntly-000000000000/build/src/ipc/glue/MessageChannel.cpp, line 1839
`

I'm not really sure what to make of it

**Comment by Vaelatern** [comment]
Which version of firefox are you both running? (`xbps-query -s firefox` output please)

**Comment by elroncio** [comment]
Mine is firefox-46.0_2

**Comment by thebonaestest** [comment]
Firefox (developer version) 46.0a2

**Comment by ebfe** [comment]
Still an issue?

**Comment by Gottox** [comment]
I haven't experienced any crashes in the last few weeks. Reopen if still relevant.
