### ISSUE TITLE
Package Request: cgrep

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4038]
# Template file for 'cgrep'
    pkgname=cgrep
    version=6.6.3
    revision=1
    build_style=haskell-stack
    hostmakedepends="ghc stack"
    stackage=""    # ?
    makedepends="" # ?
    depends=""     # ?
    short_desc="A context-aware grep for source codes"
    maintainer="Michael Gehring <mg@ebfe.org>"
    license="GPL-2"
    homepage="https://awgn.github.io/cgrep/"
    distfiles="https://github.com/awgn/cgrep/archive/v${version}.tar.gz"
    checksum=50216341ba024e6a6b6192ff879ed6b8bc8be5255010e0bbbf6fb36d1c495225

**Comment by chneukirchen** [comment]
stackage= should be the latest lts version from stackag.org/lts

also conflicts="codesearch"
