### ISSUE TITLE
php: crypt() segfaults on musl

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4039]
echo '<?php print crypt("foo", "bar") ?>' | php
    Segmentation fault (core dumped)

     #0  0x000055a426db980e in zif_crypt (execute_data=<optimized out>, return_value=0x7fc67aa12090) at /builddir/php-7.0.5/ext/standard/crypt.c:328
     #1  0x000055a426eec65d in ZEND_DO_ICALL_SPEC_HANDLER () at /builddir/php-7.0.5/Zend/zend_vm_execute.h:586
     #2  0x000055a426ee179b in execute_ex (ex=<optimized out>) at /builddir/php-7.0.5/Zend/zend_vm_execute.h:414
     #3  0x000055a426f350c7 in zend_execute (op_array=0x7fc67aa772a0, op_array@entry=0x7fc67aa790e0, return_value=return_value@entry=0x7fc67aa12030) at /builddir/php-7.0.5/Zend/zend_vm_execute.h:458
     #4  0x000055a426ea1ef3 in zend_execute_scripts (type=type@entry=8, retval=0x7fc67aa12030, retval@entry=0x0, file_count=file_count@entry=3) at /builddir/php-7.0.5/Zend/zend.c:1427
     #5  0x000055a426e431c0 in php_execute_script (primary_file=0x7ffdcca4a790) at /builddir/php-7.0.5/main/main.c:2487
     #6  0x000055a426f36d38 in do_cli (argc=2, argv=0x55a42774eee0) at /builddir/php-7.0.5/sapi/cli/php_cli.c:974
     #7  0x000055a426c8a1a9 in main (argc=2, argv=0x55a42774eee0) at /builddir/php-7.0.5/sapi/cli/php_cli.c:1344

https://forum.voidlinux.eu/t/php-7-crypt/511

**Comment by Duncaen** [comment]
http://git.alpinelinux.org/cgit/aports/tree/main/php/fix-crypt.patch
