### ISSUE TITLE
base-files: man page for vkpurge(1)

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#4058]
I'll get on one based on the help and PR it later, just tracking this here.

**Comment by Duncaen** [comment]
bump :stuck_out_tongue:

**Comment by Vaelatern** [comment]
Ah, hello there.

**Comment by Vaelatern** [comment]
https://github.com/voidlinux/void-packages/commit/ee376bb7d46dbd7a1c7ad8db21a2c102f5df4c83
