### ISSUE TITLE
openssh: split into ssh and sshd

### ISSUE THREAD

**Issue by jannisch** [voidlinux/void-packages#4085]
The openssh package is obviously one of the most common packages in all Linux distributions.

However, in common server setups only the `sshd` application is required and on the other hand, on Notebooks and PCs only the client application `ssh` is needed, because users usually don't need remote access to such devices.

Due to this fact I suggest to split the `openssh` package into one package that provides the server application, service files, etc and another package that provides the client application.
If we still included both of them in `base-system` or let them depend on each other, there wouldn't be a practical change but the user would have the possibility to uninstall them seperately.

I first wanted to hear your thoughts before submitting a PR so please don't hesitate to share them.

**Comment by ebfe** [comment]
> installed_size: 4495KB

Is it really worth it?

**Comment by jannisch** [comment]
Well, I don't really care about disk space. I try to keep the amount of unnessary files and folders as low as possible and was annoyed to read `sshd` every time I do something in `/etc/ssh` or `/etc/sv`.
But I definitely see your point.

**Comment by xtraeme** [comment]
If you look at the git log you'll see that we've had openssh-{client,server} already, but it's useless. Both are useful to have by default.

I won't split them again.

Thanks!
