### ISSUE TITLE
Openvswitch

### ISSUE THREAD

**Issue by elroncio** [voidlinux/void-packages#4096]
Openvswitch package don't create folder `/etc/openvswitch` and default DB file `/etc/openvswitch/conf.db`

**Comment by Vaelatern** [comment]
Please give more details about how to notice this error?

**Comment by elroncio** [comment]
You can get the same error with: `ovsdb-server`
However it's not a bug. I didn't notice that both files are created if and only if you run the runit service at least once. (lines 3-4)
[https://github.com/voidlinux/void-packages/blob/master/srcpkgs/openvswitch/files/ovsdb-server/run](url)

**Comment by Vaelatern** [comment]
A very fair point. I'll look into it.

**Comment by Vaelatern** [comment]
Since the package is supposed to be used as a server, it is fully acceptable for the runit script to create the database. That's just the way this software works.
