### ISSUE TITLE
Update Warsow to 2.1

### ISSUE THREAD

**Issue by cmcsun** [voidlinux/void-packages#4097]
Hi, just asking because I really do want to play the newest version of Warsow (2.1) but compiling it from source is giving me errors after I try to run it (might just be something on my end or I'm doing something wrong) and I noticed the void package is quite old (v1.5).

Any chance we can update it?

https://www.warsow.gg/download

If so, thank you!

**Comment by ebfe** [comment]
Please give #4099 a try.
