### ISSUE TITLE
brasero cd burner missing dependancies

### ISSUE THREAD

**Issue by chriscamacho** [voidlinux/void-packages#4109]
brasero says its missing toc2cue and cdrdao using

xbps-query -R -o "*/toc2cue"
xbps-query -R -o "*/cdrdao"

and these files don't apear to be in the repo

I think it was missing some other stuff too ?  but there were packages for them which should probably be actual dependencies (sorry can't remember what they were)

**Comment by ebfe** [comment]
#4108
