### ISSUE TITLE
cdrecord -scanbus failure

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#4127]
Hi,

I am trying to set up a script that uses cdrecord to burn cd's. Since cdrecord no longer supports opening drive by dev number, I removed the -dev=/dev/sr0 from the command line in the script. However cdrecord cannot find the device "automagically", as the man page says:

[1747][root@5b4az:/home/neoklis]> cdrecord -scanbus
Cdrecord-ProDVD-ProBD-Clone 3.01 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2015 Joerg Schilling
cdrecord: No such file or directory. Cannot open '/dev/pg*'. Cannot open or use SCSI driver.
cdrecord: For possible targets try 'cdrecord -scanbus'.
cdrecord: For possible transport specifiers try 'cdrecord dev=help'.

[1748][root@5b4az:/home/neoklis]> cdrecord dev=help
Cdrecord-ProDVD-ProBD-Clone 3.01 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2015 Joerg Schilling
Supported SCSI transports for this platform:

Transport name:         sg
Transport descr.:       Generic transport independent SCSI
Transp. layer ind.:
Target specifier:       bus,target,lun
Target example:         1,2,0
SCSI Bus scanning:      supported
Open via UNIX device:   not supported

Transport name:         pg
Transport descr.:       SCSI transport for ATAPI over Parallel Port
Transp. layer ind.:
Target specifier:       bus,target,lun
Target example:         1,2,0
SCSI Bus scanning:      supported
Open via UNIX device:   not supported

Transport name:         ATA
Transport descr.:       ATA Packet specific SCSI transport
Transp. layer ind.:     ATAPI:
Target specifier:       bus,target,lun
Target example:         ATAPI:1,2,0
SCSI Bus scanning:      supported
Open via UNIX device:   not supported

Transport name:         ATA
Transport descr.:       ATA Packet specific SCSI transport using sg interface
Transp. layer ind.:     ATA:
Target specifier:       bus,target,lun
Target example:         1,2,0
SCSI Bus scanning:      supported
Open via UNIX device:   not supported

Transport name:         RSCSI
Transport descr.:       Remote SCSI
Transp. layer ind.:     REMOTE:
Target specifier:       rscsi@host:bus,target,lun
Target example:         REMOTE:rscsi@host:1,2,0
SCSI Bus scanning:      supported
Open via UNIX device:   not supported

Also, CD's burned with the original script cannot be mounted in my linux machine but they work ok in my neighbor's windoze box. CD's burned a few weeks ago work ok on my linux machine. 

Has something changed recently, effecting cdrecord and mounting CD's burned by it?

**Comment by Vaelatern** [comment]
Latest change was on January 15th, feb1426f18f4c4c586508c2b12bf420532638c64 and 59910bbfc60b60c5fe159e80c3291521acfc3d61
Neither of these was a version bump. Are you sure cdrecord won't work with the `-dev` option?

**Comment by nkcyham** [comment]
cdrecord works with the -dev= option but it keeps saying the the option is "unintentional and not supported", so I decided to change things to eliminate the message. But I ended up with the problem of "cdrecord: No such file or directory. Cannot open '/dev/pg*'. Cannot open or use SCSI driver." I can put back the -dev= option to make the script work, but I have the problem of not being able to mount the burned CD in void, while in widoze it works. 

I really want to know if I can do something about "Cannot open '/dev/pg*'" etc, which doesn't look right to me.

**Comment by nkcyham** [comment]
Some further info: I tried running cdrecord -scanbus in Puppy Linux and it works. I also tried opening the CD I burned in Void and it works OK in Puppy. I then rebooted into Void and tried opening the CD - it worked! But then I tried poweroff and boot again into Void - could not open the CD. Tried opening in Puppy, it worked. Poweroff in Puppy and reboot to Void - cannot open CD. It only works in Void when I open it first in puppy and then reboot into void without poweroff or opening the cdrom dirve drawer. So it seems that puppy does something to the cdrom drive that makes it work and that it persists into void only with reboot without poweroff or opening the cdrom drive drawer.

Phew!! I can't make much sense of this, hope someone will!

**Comment by cavalier911** [comment]
@nkcyham 
Verify sg kernel module is loaded.
```
[rj@voidlinux ~]$ sudo cdrecord  -scanbus`
Cdrecord-ProDVD-ProBD-Clone 3.01 (x86_64-unknown-linux-gnu) Copyright (C) 1995-2015    Joerg Schilling
Linux sg driver version: 3.5.36
Using libscg version 'schily-0.9'.
scsibus0:
	0,0,0	  0) 'ATA     ' 'Maxtor 6Y200P0  ' '1BW0' Disk
	0,1,0	  1) *
	0,2,0	  2) *
	0,3,0	  3) *
	0,4,0	  4) *
	0,5,0	  5) *
	0,6,0	  6) *
	0,7,0	  7) *
scsibus2:
	2,0,0	200) *
	2,1,0	201) 'ATA     ' 'WDC WD6400AAKS-0' '3B01' Disk
	2,2,0	202) *
	2,3,0	203) *
	2,4,0	204) *
	2,5,0	205) *
	2,6,0	206) *
	2,7,0	207) *
scsibus3:
	3,0,0	300) 'ATA     ' 'SAMSUNG HD103SI ' '1118' Disk
	3,1,0	301) *
	3,2,0	302) *
	3,3,0	303) *
	3,4,0	304) *
	3,5,0	305) *
	3,6,0	306) *
	3,7,0	307) *
scsibus5:
	5,0,0	500) 'TSSTcorp' 'CDDVDW SH-S223F ' 'SB00' Removable CD-ROM
	5,1,0	501) *
	5,2,0	502) *
	5,3,0	503) *
	5,4,0	504) *
	5,5,0	505) *
	5,6,0	506) *
	5,7,0	507) *
```

**Comment by nkcyham** [comment]
Thanks! It wasn't.

Now I have to find out why....

**Comment by cavalier911** [comment]
@nkcyham 
When I installed cdtools I had same problem as you
I found solution by looking at archlinux cdrtools pkgbuild.
```
# autoload 'sg' module needed by cdrecord
  install -d -m755 "$pkgdir"/usr/lib/modules-load.d/
  echo sg > "$pkgdir"/usr/lib/modules-load.d/cdrecord.conf
```
I used the same commands in terminal on void excluding "$pkgdir" to force sg to auto-load on boot.

**Comment by nkcyham** [comment]
Thanks! It worked for me too...

**Comment by Vaelatern** [comment]
f72ffb307e1ce6c32fef616fa21c8e4e906c8212
