### ISSUE TITLE
runit writing to disk continually on desktop but not laptop

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#4137]
Hi

I updated void on both my desktop and laptop machines today. On rebooting the desktop, I found that conky indicated a steady write to the hard disk (SSD) at a rate of ~120 kB/s. iotop confirms this. I traced the writes to some file in /run/runit/runsvdir/current/supervise/ being updated every second.

This is not happening to my laptop, with a near identical install of void, as the /run/runit/runsvdir/current/supervise/ directory strangely does not exist. This is odd as I did an -Syu on both of them a little while ago. Also significant, this continuous writing was not happening to my desktop before the update, I would have seen it in conky.

Cannot find out what is wrong, if anything - well, one of the two, desktop or laptop, must have something wrong relating to runit...

My thanks in advance for any help!

**Comment by Vaelatern** [comment]
Which file in `/run/runit/runsvdir/current/supervise/`?

**Comment by nkcyham** [comment]
@Vaelatern 

Its status, stat and pid. status is binary, pid is blank and stat says down.
With my limited knowledge of runit, could this mean that after the -Syu some process started by runit has failed and runsv is trying to restart it?

Thanks for the help!

**Comment by Duncaen** [comment]
There shouldn't be a `supervise` folder in `/run/runit/runsvdir/current/`.
Maybe attach the output of `ps aux | grep runsv`.

**Comment by nkcyham** [comment]
@Duncaen 
root       683  0.0  0.0   4224  1272 ?        Ss   18:21   0:00 runsvdir -P /run/runit/runsvdir/current log:  supervise: warning: unable to stat control/u: not a directory runsv supervise: fatal: unable to start ./run: file does not exist runsv current: fatal: unable to start ./run: file does not exist runsv supervise: warning: unable to stat control/u: not a directory runsv current: fatal: unable to start ./run: file does not exist runsv supervise: fatal: unable to start ./run: file does not exist 
root       698  0.1  0.0   4072  1112 ?        Ss   18:21   0:01 runsv supervise
root       699  0.1  0.0   4072  1196 ?        Ss   18:21   0:01 runsv current
root       700  0.0  0.0   4072   636 ?        Ss   18:21   0:00 runsv dhcpcd
root       701  0.0  0.0   4072   680 ?        Ss   18:21   0:00 runsv uuidd
root       702  0.0  0.0   4072   676 ?        Ss   18:21   0:00 runsv dbus
root       703  0.0  0.0   4072   696 ?        Ss   18:21   0:00 runsv dcron
root       704  0.0  0.0   4072   660 ?        Ss   18:21   0:00 runsv agetty-tty6
root       705  0.0  0.0   4072   700 ?        Ss   18:21   0:00 runsv agetty-tty4
root       706  0.0  0.0   4072   656 ?        Ss   18:21   0:00 runsv udevd
root       707  0.0  0.0   4072   700 ?        Ss   18:21   0:00 runsv sshd
root       709  0.0  0.0   4072   636 ?        Ss   18:21   0:00 runsv agetty-tty1
root       712  0.0  0.0   4072   664 ?        Ss   18:21   0:00 runsv alsa
root       726  0.0  0.0   4072   636 ?        Ss   18:21   0:00 runsv gpm
root       729  0.0  0.0   4072   676 ?        Ss   18:21   0:00 runsv acpid
root       730  0.0  0.0   4072   636 ?        Ss   18:21   0:00 runsv agetty-tty2
root       731  0.0  0.0   4072   712 ?        Ss   18:21   0:00 runsv ntpd
root       738  0.0  0.0   4072   636 ?        Ss   18:21   0:00 runsv wpa_supplicant
root       739  0.0  0.0   4072   688 ?        Ss   18:21   0:00 runsv agetty-tty5
root       740  0.0  0.0   4072   652 ?        Ss   18:21   0:00 runsv agetty-tty3
root      2519  0.0  0.0  10768  2180 pts/0    S+   18:34   0:00 grep runsv

**Comment by Duncaen** [comment]
The processes `runsv current` and `runsv supervise` shoudln't be there.
Please provide `ls -lsa /run/runit/runsvdir/current/`

**Comment by nkcyham** [comment]
@Duncaen 
[1841][root@5b4az:/home/neoklis]> ls -lsa /run/runit/runsvdir/current
0 lrwxrwxrwx 1 root root 27 May  5 18:21 /run/runit/runsvdir/current -> /etc/runit/runsvdir/current

**Comment by Duncaen** [comment]
With the trailing `/` i want to see the content.

**Comment by nkcyham** [comment]
@Duncaen 
Sorry about that:

[1842][root@5b4az:/home/neoklis]> ls -lsa /run/runit/runsvdir/current/
total 12
4 drwxr-xr-x 3 root root 4096 May  5 16:46 .
4 drwxr-xr-x 4 root root 4096 Mar 30 09:21 ..
0 lrwxrwxrwx 1 root root   13 Jan  4 17:22 acpid -> /etc/sv/acpid
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty1 -> /etc/sv/agetty-tty1
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty2 -> /etc/sv/agetty-tty2
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty3 -> /etc/sv/agetty-tty3
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty4 -> /etc/sv/agetty-tty4
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty5 -> /etc/sv/agetty-tty5
0 lrwxrwxrwx 1 root root   19 Apr 26 07:17 agetty-tty6 -> /etc/sv/agetty-tty6
0 lrwxrwxrwx 1 root root   12 Jan  5 05:22 alsa -> /etc/sv/alsa
0 lrwxrwxrwx 1 root root   27 Feb  2 20:40 current -> /etc/runit/runsvdir/current
0 lrwxrwxrwx 1 root root   13 Jan  5 06:18 dbus -> /etc/sv/dbus/
0 lrwxrwxrwx 1 root root   13 Jan  5 05:22 dcron -> /etc/sv/dcron
0 lrwxrwxrwx 1 root root   14 Jan  8 21:39 dhcpcd -> /etc/sv/dhcpcd
0 lrwxrwxrwx 1 root root   11 Jan  5 05:22 gpm -> /etc/sv/gpm
0 lrwxrwxrwx 1 root root   12 Jan  5 05:22 ntpd -> /etc/sv/ntpd
0 lrwxrwxrwx 1 root root   12 Jan  4 17:22 sshd -> /etc/sv/sshd
4 drwx------ 3 root root 4096 May  5 18:44 supervise
0 lrwxrwxrwx 1 root root   13 Apr 26 07:17 udevd -> /etc/sv/udevd
0 lrwxrwxrwx 1 root root   13 Jan  4 17:22 uuidd -> /etc/sv/uuidd
0 lrwxrwxrwx 1 root root   22 Jan  5 05:22 wpa_supplicant -> /etc/sv/wpa_supplicant

**Comment by Duncaen** [comment]
Any idea why there is a link `/run/runit/runsvdir/current/current > /run/runit/runsvdir/current`?
If you remove it, it should be fixed.

**Comment by nkcyham** [comment]
@Duncaen 

Thanks! I stop, thankfully, before ruining my SSD.... but I also had to delete the stray supervise directory before it worked.

I honestly have no idea how this happened. All I did was to update with xbps-install -Syu. The link and directory could not have been created accidentally, or deliberately, since I had such little knowledge of runit. 

Well, all is well that ends well....

**Comment by nkcyham** [comment]
I just thought, it may have happened to others but unless they have disk i/o monitoring, as in conky, it might not be noticed.
