### ISSUE TITLE
Request: Calf plugins for Musl

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#4140]
They seem to be available for Glibc but not for musl. There are more plugins only available for glibc.

**Comment by ebfe** [comment]
72d110f08886bf3a4eb97c76eb2e112f9c0b18d6

**Comment by Vaelatern** [comment]
@38github does this close the issue?

**Comment by 38github** [comment]
Guys, you are amazing! Yes, it did work! :D
