### ISSUE TITLE
Package request: Teamspeak

### ISSUE THREAD

**Issue by Kyuzial** [voidlinux/void-packages#4144]
http://www.teamspeak.com/
We already have necessary deps : qt5 and libxkbcommon-x11.

**Comment by webmaster0** [comment]
Will this package ever be added?

**Comment by Johnnynator** [comment]
The package is in the repositority. This issue can normally be closed.
https://github.com/voidlinux/void-packages/blob/7df296fdb23fd06f7f26725c35e4b7e4f59878f0/srcpkgs/teamspeak3/template

**Comment by webmaster0** [comment]
Oh ok I didnt't know that. But why is teamspeak only available as source package? I didn't find it with `xbps-query -Rs teamspeak3`.

**Comment by Duncaen** [comment]
https://github.com/voidlinux/void-packages/pull/5353#issuecomment-267761768

**Comment by Johnnynator** [comment]
@webmaster0 AS I said in edit2, void Linux doesn't have the allowance to redistribute teamspeak
