### ISSUE TITLE
Package request: linux-libre

### ISSUE THREAD

**Issue by kazblox** [voidlinux/void-packages#4146]
https://www.fsfla.org/ikiwiki/selibre/linux-libre/

Seems interesting as it is a project to deblob everything requiring proprietary binaries to function from the Linux kernel. Not viable in the long run for normal computers, but it would make great usage for Libreboot machines that do run Void...

**Comment by chneukirchen** [comment]
We are currently not interested in providing another line of kernels.

**Comment by FrostKnight** [comment]
Is this still the case? because I would also have interest in having linux-libre although the long term support versions only of course...

**Comment by notabug123** [comment]
How about now? I am really interested in a libre Linux/BSD distro, and I would hop over at once if you started supporting it
