### ISSUE TITLE
RFC: increase musl libc's DEFAULT_STACK_SIZE

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4147]
As it turns out even an increasing number of patches for several core libraries which try to reduce the stack frame footprint of some of their functions doesn't help to entirely avoid crashes of some applications with musl libc.

The default stack size is defined in `musl-1.1.14/src/internal/pthread_impl.h` as

```
#define DEFAULT_STACK_SIZE 81920
```

We could try with a substantially increased size to see if this helps failing libraries like `pixman` and `cairo` (#4133) causing `SpaceFM` to crash, and `libfaad2` (#2461) causing `firefox` and `icecat` to crash.

The required size would probably be at least 256K, i.e.

```
#define DEFAULT_STACK_SIZE 262144
```

judging by the size of the structures the mentioned libraries expect to reside in the stack frame.

If we try, and at the same time remove the patches for `libfaad2`, `pixman` and `cairo` (pending), we would need some users to try out applications using these libraries on a musl Void Linux installation.

**Comment by richfelker** [comment]
The current default was chosen empirically such that it solved real-world problems, and such that further incremental increase (without going much larger) did not solve any additional real-world problems. It also allows a fairly reasonable/typical buffer size, 64k, plus sufficient additional room for a few call frames and ability to use libc functions with on-stack buffers.

Really programs should not be using the stack for large buffers to begin with, but if they are, they need to declare their need for a large stack.

**Comment by xtraeme** [comment]
@richfelker I suppose that you are saying that applications should use `pthread_attr_setstacksize()` instead?

**Comment by pullmoll** [comment]
Making all applications which use e.g. `libfaad2`, `pixman` or `cairo` call `pthread_attr_setstacksize()` in their startup code is not really feasible IMO, or less feasible than patching the libraries.

**Comment by richfelker** [comment]
That's why I think the right fix is probably getting rid of the huge on-stack buffers and making them use malloc.

**Comment by xtraeme** [comment]
Hmm true, makes sense.

**Comment by pullmoll** [comment]
As far as I understood the intention of the large on-stack buffers in e.g. pixmap, the intention was to avoid the overhead of malloc()/free() up to some limit. pixman for example allocates an even bigger buffer if the one in the stack is not sufficient, and then free()s the pointer, if its address is different from the on-stack thing.

So far there were no problems with turning such buffers into `static __thread` allocated, which is a little less invasive than changing the code to use malloc()/free().

**Comment by ebfe** [comment]
So while I agree that applications should set proper stack sizes, currently they don't and we might be in for a lot of ugly patches. IIRC C++11 std::thread and the c11 thread api don't allow setting stack sizes, with glib GThread it's only possible using deprecated apis. 

The buffers in question are ~32KB, I'm not sure that qualifies as huge. Most instances of this has been in low level graphics/audio code and changing them to use malloc has some performance implications.

What are the downsides to bumping up the default stack size a bit?

**Comment by richfelker** [comment]
The downside to increasing default stack is that it uses a lot more memory (commit charge) for setups with lots of threads and imposes heavy limits on the total number of threads that can exist in a 32-bit address space. In theory you could manually decrease from the default to avoid those problems, but nobody is going to do that because there's no good way to know whether decreasing leaves enough space for the implementation's own needs.

In general I agree with the principle of using on-stack buffers for performance when they're small; the problem is just that these libs have the thresholds utterly wrong. If you've got an N-byte buffer, you're going to spend >C*N cycles using it, and C>1 for non-heavily-vectorized uses. Trying to avoid a malloc that takes 50-100 cycles does not make sense when N is 64k or so.

**Comment by ebfe** [comment]
> The downside to increasing default stack is that it uses a lot more
> memory (commit charge) for setups with lots of threads and imposes
> heavy limits on the total number of threads that can exist in a 32-bit
> address space. 

Hmm, since glibc defaults to 8MB I would have assumed that
applications for which this is relevant would already explicitly set
the thread stack size?

**Comment by ebfe** [comment]
abd62a8a47c055dc78ef2fc9ee078503d2a34749

**Comment by Duncaen** [comment]
For chromium 8MB is probably too much, @ncopa is trying it with 2MB I think.
Android is using 1MB, Mac OS X has a comment that 512K (the default for threads) is not enough, they use 8MB too.

**Comment by Duncaen** [comment]
http://www.openwall.com/lists/musl/2017/01/03/1
`a facility to increase default thread
stack size via pthread_setattr_default_np have also been added in this
release`

**Comment by ebfe** [comment]
5d65448221af12296f7ef2339ced92771bb465b4

**Comment by ptman** [comment]
Another library: https://github.com/esnme/ultrajson/issues/254#issuecomment-315025672

**Comment by deed02392** [comment]
@richfelker can you give reference to how the current size of 80K was chosen? It seems to be causing a multitude of issues in lots of programs. When you say programs should request larger stack sizes when necessary, do you mean literally setting the stack size at runtime?

**Comment by jart** [comment]
For what it's worth, Google's systems were designed to use a 64kb stack and tcmalloc.

**Comment by daurnimator** [comment]
> When you say programs should request larger stack sizes when necessary, do you mean literally setting the stack size at runtime?

I recall there was a discussion that a minimum bound should be the maximum theorectical size of a UDP packet, i.e. 65,507 bytes. That way you can call `recv` with a stack allocated buffer and then copy the actual size (usually after parsing) to some heap-allocated buffer: this may make use of various libc functions, so another minimum bound is size of startup code + size of udp buffer + size of libc functions + some extra stack frames. As it happened, ~80k fit this criteria (among others).
