### ISSUE TITLE
qt5-svg{,-devel}-5.6.0_8 pollute '/'

### ISSUE THREAD

**Issue by asergi** [voidlinux/void-packages#4152]
Both packages contain an unwanted file: `'/builddir/qt-everywhere-opensource-src-5.6.0/qtsvg/examples/svg/richtext/textobject/files/heart.svg'` which pollute '/'.

/cc @pullmoll

**Comment by pullmoll** [comment]
Strange how this file made it into the xbps. I'll just add a `rm -rf $DESTDIR/builddir` to the cleaning functions for subpkg and devel.
