### ISSUE TITLE
Update chromium from 49.x to 50.x

### ISSUE THREAD

**Issue by ThePierrezou** [voidlinux/void-packages#4156]
Hi,
This update is needed, sicne then, some flaws has been discovered.
I would like to modify the template to update it, but I would need to test it before making a PR, and compilling chromium on my computer would take to much time, sorry.
Can someone do it, please ?
Thanks
ThePierrezou

**Comment by xtraeme** [comment]
Well, the patches for musl need to be adapted for new major versions... so that it's not that simple.

Anyway I'm updating the package.
