### ISSUE TITLE
WPA_Supplicant fails to run with default config if wireless interface isn't wlan0

### ISSUE THREAD

**Issue by TheDoctorsLife** [voidlinux/void-packages#4158]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/wpa_supplicant/files/wpa_supplicant/run#L4 I been manually editing this line, in order to fix this for my machine, but this breaks on every update since the service file gets changed.

Output of ip link:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s10: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:1f:16:4a:3f:a6 brd ff:ff:ff:ff:ff:ff
3: wlp7s0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 00:26:5e:4d:2a:91 brd ff:ff:ff:ff:ff:ff
```
As you can see my wireless interface is wlp7s0, which isn't wlan0 as set it the wpa_supplicant run file. My desktop has the same issue.

**Comment by xtraeme** [comment]
`echo WPA_INTERFACE=myif0 > /etc/sv/wpa_supplicant/conf`
