### ISSUE TITLE
Package request: Budgie Desktop

### ISSUE THREAD

**Issue by ghost** [voidlinux/void-packages#4162]
https://solus-project.com/budgie

Budgie is the flagship desktop of the Solus Operating System.

**Comment by Vaelatern** [comment]
Seems a `gnu-makefile` project, source at https://github.com/solus-project/budgie-desktop and the latest release at https://github.com/solus-project/budgie-desktop/archive/v10.2.5.tar.gz
Just in case someone gets to this before I do.

**Comment by ebfe** [comment]
27e2bdf5c00cc8777c921e9fd142fc42714b8d46
