### ISSUE TITLE
hardcoded wpa_supplicant interface in runit file

### ISSUE THREAD

**Issue by WKuipers** [voidlinux/void-packages#4163]
In `/etc/sv/wpa_supplicant/run` there is a hardcoded flag -i ${WPA_INTERFACE:=wlan0}, which causes wpa_supplicant to break whenever it is updated as I have to change it to wlp3s0 on my system

I would suggest either not overwriting this file like other config files or using a different way of getting the correct interface

**Comment by xtraeme** [comment]
`echo WPA_INTERFACE=wlp3s0 > /etc/sv/wpa_supplicant/conf`
