### ISSUE TITLE
dhcpcd: broken autoIP lease

### ISSUE THREAD

**Issue by demiaster** [voidlinux/void-packages#4170]
since last version dhcpcd 6.11.0_1

    % ip a
    ...    
    3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether ... brd ff:ff:ff:ff:ff:ff
    inet 169.254.104.33/16 brd 169.254.255.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::78b6:26b4:f75c:bbbd/64 scope link 
       valid_lft forever preferred_lft forever
    ...

**Comment by ebfe** [comment]
Fixed with `dhcpcd-6.11.0_2`?

**Comment by demiaster** [comment]
yes
