### ISSUE TITLE
dhcpcd 6.11.0 not working, receiving truncated packets

### ISSUE THREAD

**Issue by mrdomino** [voidlinux/void-packages#4171]
Could be related to / a duplicate of #4170. I don't know enough to be sure.

After upgrading from 6.10.3 to 6.11.0, I see lots of "$dev: soliciting a DHCP lease" and "$dev: truncated packet (280) from $routerip" in the logs, and I wind up with a link-local address after dhcpcd gives up. I downgraded to 6.10.3 and the issue disappeared. This happens on both my wired and wireless interfaces.

If it helps, I also happen to be running dnsmasq on this machine as a DNS cache, and I'm on 4.5.3_3 glibc x86_64.

**Comment by thypon** [comment]
#4170

**Comment by zqqw** [comment]
I put the 4.4 kernel and header files on hold before updating.
Then I updated everything else  on 10th May 2016 using:
xbps-install -Syu
which updated the 4.5 kernel, dhcpcd and wpa_supplicant among other items.
After rebooting I had no wireless connection.

-rw-r--r-- 1 root root   450448 Mar 31 06:51 wpa_supplicant-2.5_4.i686.xbps
-rw-r--r-- 1 root root      512 Mar 31 06:52 wpa_supplicant-2.5_4.i686.xbps.sig
-rw-r--r-- 1 root root   450624 May  8 14:54 wpa_supplicant-2.5_6.i686.xbps
-rw-r--r-- 1 root root      512 May  8 14:55 wpa_supplicant-2.5_6.i686.xbps.sig

-rw-r--r-- 1 root root   149584 Apr 20 11:04 dhcpcd-6.10.3_1.i686.xbps
-rw-r--r-- 1 root root      512 Apr 20 11:05 dhcpcd-6.10.3_1.i686.xbps.sig
-rw-r--r-- 1 root root   150920 May  9 19:06 dhcpcd-6.11.0_1.i686.xbps
-rw-r--r-- 1 root root      512 May  9 19:07 dhcpcd-6.11.0_1.i686.xbps.sig

wlp7-on is this, the conf file has the AP security details, and dhcpcd isn't run by runit as a central process:
#!/bin/bash

ip link set wlp7s0 up
wpa_supplicant -B -P /run/wpa_supplicant_wlp7s0.pid -i wlp7s0 -D nl80211,wext \
-c /opt/wireless/wpa_supplicant_wlp7s0.conf
sleep 10
dhcpcd -4  -t 0 -K  wlp7s0

$ sudo wlp7-on
Password:
Successfully initialized wpa_supplicant
DUID 00:01:00:01:1e:8b:0c:8b:00:0d:88:8b:11:85
wlp7s0: IAID df:8d:fc:d8
read_lease: truncated lease
wlp7s0: soliciting a DHCP lease
wlp7s0: probing for an IPv4LL address
wlp7s0: using IPv4LL address 169.254.144.156
wlp7s0: adding route to 169.254.0.0/16
wlp7s0: adding default route
forked to background, child pid 932

No connection, no web pages in browser, message saying network connection error instead. xbps-install can't connect to repo.
iw dev wlp7s0 scan can find the wireless AP.
I also rebooted and switched to the alternative 4.4 kernel entry on the Grub menu with the same result, so it doesn't look like the kernel is a problem.
$ sudo dhcpcd --rebind wlp7s0
DUID 00:01:00:01:1e:8b:0c:8b:00:0d:88:8b:11:85
wlp7s0: IAID df:8d:fc:d8
wlp7s0: soliciting an IPv6 router
read_lease: truncated lease
wlp7s0: soliciting a DHCP lease
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: using IPv4LL address 169.254.144.156
wlp7s0: adding route to 169.254.0.0/16
forked to background, child pid 1088

$ sudo dhcpcd --renew
Password:
dev: loaded udev
DUID 00:01:00:01:1e:8b:0c:8b:00:0d:88:8b:11:85
wlp7s0: IAID df:8d:fc:d8
enp2s0: waiting for carrier
enp2s0: carrier acquired
enp2s0: adding address fe80::ff03:9788:6d63:82da
enp2s0: IAID db:13:a5:d1
enp2s0: carrier lost
enp2s0: deleting address fe80::ff03:9788:6d63:82da
wlp7s0: soliciting an IPv6 router
read_lease: truncated lease
wlp7s0: soliciting a DHCP lease
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: using IPv4LL address 169.254.144.156
wlp7s0: adding route to 169.254.0.0/16
forked to background, child pid 1179

$ sudo dhcpcd --renew  -L
sending signal USR1 to pid 1179
dev: loaded udev
DUID 00:01:00:01:1e:8b:0c:8b:00:0d:88:8b:11:85
wlp7s0: IAID df:8d:fc:d8
enp2s0: waiting for carrier
read_lease: truncated lease
wlp7s0: soliciting a DHCP lease
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: soliciting an IPv6 router
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: truncated packet (280) from 192.168.1.254
wlp7s0: no IPv6 Routers available
wlp7s0: truncated packet (280) from 192.168.1.254
timed out
forked to background, child pid 1204

$ sudo dhcpcd --dumplease wlp7s0
read_lease: truncated lease
wlp7s0: dhcp_dump: No such file or directory
wlp7s0: dhcp6_dump: No such file or directory
$ sudo xbps-rindex  -a ~/xbps-pkgs/dhcpcd-6.10.3_1.i686.xbps
index: added `dhcpcd-6.10.3_1' (i686).
index: 3 packages registered.
$ sudo xbps-install -Sf --repository=~/xbps-pkgs dhcpcd
[*] Updating `https://repo.voidlinux.eu/current/i686-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/i686-repodata': Transient resolver failure

Name   Action    Version           New version            Download size
dhcpcd downgrade 6.11.0_1          6.10.3_1               -

Size required on disk:         386KB
Free space on disk:             19GB

Do you want to continue? [Y/n] y

[*] Downloading binary packages

[*] Verifying package integrity
dhcpcd-6.10.3_1: verifying SHA256 hash...

[*] Running transaction tasks
dhcpcd-6.10.3_1: unpacking ...

[*] Configuring unpacked packages
dhcpcd-6.10.3_1: configuring ...
dhcpcd-6.10.3_1: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.

$ sudo wlp7-on
Successfully initialized wpa_supplicant
sending commands to master dhcpcd process

Still didn't work.

$ sudo xbps-rindex  -a ~/xbps-pkgs/wpa_supplicant-2.5_4.i686.xbps
index: added `wpa_supplicant-2.5_4' (i686).
index: 4 packages registered.
$ sudo xbps-install -f --repository=/home/steve/xbps-pkgs wpa_supplicant

Name           Action    Version           New version            Download size
wpa_supplicant downgrade 2.5_6             2.5_4                  -

Size required on disk:        1338KB
Free space on disk:             19GB

Do you want to continue? [Y/n] y

[*] Downloading binary packages

[*] Verifying package integrity
wpa_supplicant-2.5_4: verifying SHA256 hash...

[*] Running transaction tasks
wpa_supplicant-2.5_4: unpacking ...

[*] Configuring unpacked packages
wpa_supplicant-2.5_4: configuring ...
wpa_supplicant-2.5_4: installed successfully.

0 downloaded, 1 installed, 0 updated, 1 configured, 0 removed.

Now it works again and I have a wireless connection.
I'm using 32 bit Void Linux with GLIBC. I didn't see much about truncated packets online but could there be a conf file setting for the packet length?

**Comment by renatoaguiar** [comment]
I'm having the same issue, but only for one specific network. I tried dhclient on the same network and it worked fine.

Not sure if it helps, but the number in the message is different in my case: "truncated packet (297) from...".

**Comment by renatoaguiar** [comment]
Wireshark can completely parse the dhcp response, so it should not be a network issue.

**Comment by zqqw** [comment]
I just retried upgrading dhcpcd which saw the truncated lease error return. Then I downgraded that which restored normal operation, and upgraded wpa_supplicant. Wireless is still working, so I'm not sure what happened before but it looks confined to the dhcpcd package.

**Comment by Vagabond** [comment]
I am seeing this as well after upgrading dhcpd the other day. Glibc/x64.

**Comment by renatoaguiar** [comment]
It is a dhcpcd bug: http://roy.marples.name/projects/dhcpcd/tktview?name=3f10c9b871

**Comment by renatoaguiar** [comment]
I've created a PR (#4180) with the upstream patch for this issue.

I didn't have a chance to verify yet since I don't have access to the broken network right and I should not have access to it in less than 30 hours from now :(

Could someone else verify it meanwhile?

**Comment by xtraeme** [comment]
Should be fixed in #4180
