### ISSUE TITLE
libreoffice website version, newer than package version

### ISSUE THREAD

**Issue by chriscamacho** [voidlinux/void-packages#4182]
Libreoffice keeps nagging to be updated, but I'd rather update via package manager...

packaged version 5.0.4.2
version on Libreoffice website  5.1.2.2

**Comment by ebfe** [comment]
You probably have the `libreoffice-bin` package installed. That package no longer exists and has been replaced by `libreoffice` which is at version 5.1.2.2.

**Comment by chriscamacho** [comment]
Just a suggestion would it be possible to update libreoffice-bin to install libreoffice and then uninstall libreoffice-bin - it could then sooner be purged from the repository without fear of disturbing peoples machines, not sure how an end user is expected to just somehow know that one package has been replaced with another ?

**Comment by ebfe** [comment]
@pullmoll `replaces=libreoffice-bin` should dtrt?

**Comment by pullmoll** [comment]
`libreoffice-bin` was already removed by @xtraeme after some weeks of `libreoffice` availability.
`libreoffice` had a `conflicts="libreoffice-bin>=0"` line before, but now has no `replaces="libreoffice-bin"`.

I don't know if a replaces makes sense or is advised for a no longer existing package. I guess @xtraeme would have put it in place otherwise?

**Comment by chriscamacho** [comment]
I checked my sisters machine, that also had this package, its likely a number of system have been left with libreoffice-bin

**Comment by Vaelatern** [comment]
Yes, all machines with libreoffice now need to change which package they install.

An upgrade path would be good.

**Comment by pullmoll** [comment]
So should we create a fake libreoffice-bin which switches to libreoffice?

**Comment by Duncaen** [comment]
I don't think there is a way if updating and replacing the same package in one transaction. iirc `replaces` only works for dependencies of a package that are installed in automatic mode, so a package pulls in the new dependency and the old obsolete one is removed in the same transaction.

**Comment by chriscamacho** [comment]
okay, this is probably just a bit simplistic but can you make a "upgrade" for libreoffice-bin, that contains/runs a simple script to install libreoffice and then uninstalls libreoffice-bin - or am I missing something ?

**Comment by Vaelatern** [comment]
You mean a one-file `libreoffice-bin` that runs `xbps-install libreoffice && xbps-remove libreoffice-bin` in the INSTALL for the package?

**Comment by chriscamacho** [comment]
Essentially I guess so, but I have no idea of the impact or advisability, just seemed a simple solution

**Comment by pullmoll** [comment]
It depends on if the INSTALL runs inside the xbps transaction or afterwards.
In case it's during the transaction, it would probably fail or even deadlock, because the update tries to remove the currently updated package...

I fear there is no easy way around this essential problem - yet.

**Comment by chriscamacho** [comment]
okay this is going to sound even lamer and suckier.....!
Fork and sleep ?

**Comment by Vaelatern** [comment]
You are right. It is lamer and suckier. As well as racier (imagine installing texlive-bin after this) and still does not avoid the essential issues.

Adding a one-time runit script that then removes itself on successful run might work, but seems extremely hacky.

**Comment by Duncaen** [comment]
Wen cant do this, we dont know if the internet is connected, the repository is in sync and if its not there might be broken dependencies (libreoffice has a lot) if we don't do a full update.

I had something in mind by mapping the old package to the new package by `virtualpkg` in base-files, on the next update the version of the new one would be higher and gets installed and the old one gets uninstalled by `replaces`.
But this might end in a cycle, maybe its best to have a new feature for cases like this in xbps.

**Comment by Vaelatern** [comment]
Perhaps an `replace_with` variable in xbps to direct xbps to replace a given package with another.

**Comment by xtraeme** [comment]
What's so hard about using `xbps-install -Sf libreoffice` ?

**Comment by Vaelatern** [comment]
It doesn't get caught in a `-u`

**Comment by teh-jazzman** [comment]
Is there a way to identify obsolete packages or would I have to script that myself?

**Comment by yopito** [comment]
you mean for installed package on a running system ? `xbps-install -Sun`  for instance. See `xbps-install(1)` man page.

**Comment by chriscamacho** [comment]
that didn't pick up libreoffice for me - I run this sans -n practically every day...

**Comment by Duncaen** [comment]
I will lock this now, yes there is currently no way to automatically install a renamed package while removing the old one.
If someone wants to come up with a patch or a good idea how to add this to xbps a new issue should be opened.

@teh-jazzman i dont think there is a tool or flag that does this at the moment, you could get a list of installed packages and its repository `xbps-query -p repository -s ''` and then query the repository for each package to see if its still there.
