### ISSUE TITLE
Package request: Sublime text - Musl

### ISSUE THREAD

**Issue by mrneilypops** [voidlinux/void-packages#4186]
https://www.sublimetext.com/

**Comment by Vaelatern** [comment]
When they provide their source code, that's an option. Until then, it's glibc only.
https://forum.sublimetext.com/t/source-code-for-sublime-text/5033/3

**Comment by Vaelatern** [comment]
The correct and possible avenue is asking sublime text themselves to release a version linked against musl's libc. There is nothing anybody else can do.

**Comment by mrneilypops** [comment]
Thanks for the info.

**Comment by Vaelatern** [comment]
Alternately you can use the xlaunch script in this PR: https://github.com/chneukirchen/xtools/pull/41/files
and run sublime text using glibc. It's possible.
