### ISSUE TITLE
xbattmon bug fixed

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#4187]
Hi

I sent a bug report to upsteam for a bug in xbattmon. It was fixed next day! Here is the relevent email from the upstream programmer:

> Hi
>
> There is a bug in the xbattmon source code: in xbattmon.c.html at line 303, the error message string is incorrect: PATH_BAT_CAP. It should be of course PATH_AC_ONLINE. No doubt a copy-paste error, I do a lot of these myself! :-(
>
> The problem is that PATH_AC_ONLINE is #define'd as /sys/class/power_supply/AC/online but in my system that is /sys/class/power_supply/ADP0/online. So I was getting "No such file or directory" for the wrong missing file. I fixed it by modifying #define PATH_AC_ONLINE to /sys/class/power_supply/ADP0/online and xbattmon works OK.
>
> Thank you.

Thanks for the report.  I've fixed the first bug.

I also reverted another commit so you can change PATH_AC_ONLINE and
PATH_BAT_CAP by editing config.mk instead of diving into the source.

Cheers,
Dimitris

I thought I should report this here.

**Comment by Duncaen** [comment]
I update the template if there is a new release, I don't think its worth to add a patch just to fix the warning.
Anyways thank you for reporting this issue upstream.
