### ISSUE TITLE
Shlib unresolved depency glib2.8

### ISSUE THREAD

**Issue by n0kkasiili** [voidlinux/void-packages#4228]
I tried to build package that depends on libX11-devel and ended up this error.

> [DEBUG]  libX11-1.6.3_2: requires dependency 'glibc>=2.8_1': installed `glibc-2.23_1'.
> [DEBUG] Added `libX11-1.6.3_2' into the dependency list (https://repo.voidlinux.eu/current)
> MISSING: libcrypto35>=2.2.2_1
> MISSING: libssl35>=2.2.2_1

I think glib version is marked wrong because newest is 2.23 or there is something that i dont understand.

**Comment by Vaelatern** [comment]
No, that is totally fine.
The other lines are the important ones. `makedepends="libressl-devel"`

**Comment by Vaelatern** [comment]
turns out the solution was to `rm -rf hostdir masterdir` and start over with a `binary-bootstrap`

**Comment by chneukirchen** [comment]
`./xbps-src zap` is made for this. :)

**Comment by Vaelatern** [comment]
He had zapped. Zap doesn't remove hostdir. There are some insiduous bugs caused by old stuff in the hostdir. Don't know why.
