### ISSUE TITLE
grub: GRUB_DISABLE_LINUX_RECOVERY variable should be GRUB_DISABLE_RECOVERY

### ISSUE THREAD

**Issue by amak79** [voidlinux/void-packages#4229]
The current `srcpkgs/grub/files/grub.default` sets the `GRUB_DISABLE_LINUX_RECOVERY` variable. This is incorrect[1] and is not respected when `grub-mkconfig` is run. The variable should be `GRUB_DISABLE_RECOVERY`.

[1] http://git.savannah.gnu.org/cgit/grub.git/commit/?id=219b35646a0c71fe95d8997a79c474b1ab96bf87

**Comment by TheDoctorsLife** [comment]
I can make a pr for this.
