### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#4235]
I'm trying to download teh pic

[https://fbcdn-photos-c-a.akamaihd.net/hphotos-ak-xtp1/t31.0-0/p180x540/10869744_466542436829483_962241804861542526_o.jpg](https://fbcdn-photos-c-a.akamaihd.net/hphotos-ak-xtp1/t31.0-0/p180x540/10869744_466542436829483_962241804861542526_o.jpg)

which is, as you can notice, on a facebook cdn. I can get it without problems using firefox, but not with my Rails app or curl. Other non-void systems are not experiencing this problem.

**EDIT**: I can curl other `https://` sites, even other facebook servers:

[https://scontent.xx.fbcdn.net/v/t1.0-9/q82/p720x720/11174788_466542983496095_5654121608021671987_n.jpg?oh=2c65688eceda9d4c3519a6f24444bd61&oe=57E6AA85](https://scontent.xx.fbcdn.net/v/t1.0-9/q82/p720x720/11174788_466542983496095_5654121608021671987_n.jpg?oh=2c65688eceda9d4c3519a6f24444bd61&oe=57E6AA85)

```
[rogi@SkyLittleSystem ~]$ curl 'https://fbcdn-photos-c-a.akamaihd.net/hphotos-ak-xtp1/t31.0-0/p180x540/10869744_466542436829483_962241804861542526_o.jpg'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by Vaelatern** [comment]
Your system date is wrong and your consistent spelling of "the" makes it hard to read what you say without cringing.

**Comment by Vaelatern** [comment]
Actually, your clock is right.

**Comment by ayghor** [comment]
Actually, my clock is wrong according to [time.is](http://time.is/):

> Your clock is 9 minutes and 44.3 seconds ahead.

But fixing it didn't solve teh issue.

**Comment by ebfe** [comment]
Still an issue?

**Comment by ayghor** [comment]
Can't update my packages right now, but I bet it still is!

**Comment by Vaelatern** [comment]
Is still relevant.
The cert roots itself from https://baltimore-cybertrust-root.digicert.com
Except that I do not believe the url itself to be correct. I can curl the above page without problem. The [digicert.com check](https://www.digicert.com/help/) fails with
```
SSL Certificate is not trusted

The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.
```

Thus I believe the problem to not be with us, but with the link posted.

**Comment by ayghor** [comment]
I don't really know much bout ssl and stuff, but note that at teh tiem I could open it with firefox on void and curl on other systems.

**Comment by Vaelatern** [comment]
Well, the chain of trust for that site is not well established. Our curl cares. Apparently firefox does not.
