### ISSUE TITLE
glm: no cmake files

### ISSUE THREAD

**Issue by 7185** [voidlinux/void-packages#4240]
This is basically the same bug as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812855

.cmake files are not installed, so when I try to build a project using cmake, I get an error: 
```
 Could not find a package configuration file provided by "glm" with any of 
 the following names:

    glmConfig.cmake
    glm-config.cmake
```

You can see that those files are present in the archlinux package: https://www.archlinux.org/packages/community/any/glm/files/

Thanks

**Comment by Vaelatern** [comment]
Turns out `glm` needs the cmake step done in https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/glm but I'm trying to do it in the context of our cmake build style
