### ISSUE TITLE
Atom .desktop icon path change

### ISSUE THREAD

**Issue by shaggytwodope** [voidlinux/void-packages#4247]
It seems the path for the icon changed for some reason in a recent update.

In the current [.desktop](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/atom/patches/desktop.patch) file it is pointing to:
`/usr/share/atom/resources/app/resources/atom.png`

I believe it is now located in:
`/usr/share/atom/resources/app.asar.unpacked/resources/atom.png`

**Comment by ebfe** [comment]
Looks like the [patch](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/atom/patches/desktop.patch) needs adjustment.

**Comment by thypon** [comment]
fixed
