### ISSUE TITLE
Last update of poppler broke libreoffice 

### ISSUE THREAD

**Issue by ThePierrezou** [voidlinux/void-packages#4249]
HI,
Here the error : 

> Found poppler-0.44.0_1 (update) in repository https://repo.voidlinux.eu/current
Found poppler-glib-0.44.0_1 (update) in repository https://repo.voidlinux.eu/current
libreoffice-5.1.3.2_1: broken, unresolvable shlib `libpoppler.so.60'
Transaction aborted due to unresolved shlibs.

The commit which broke libreoffice : https://github.com/voidlinux/void-packages/commit/ecd1f47fd7423043887ec2532d0f7f8b29796b89

EDIT : didn't see this commit : https://github.com/voidlinux/void-packages/commit/b6de7b5b4d66bb75ba6736bb2c2fc69c96d5d297 
Probably need to wait the build server to compile it.

**Comment by ebfe** [comment]
See https://build.voidlinux.eu/waterfall for progress.

**Comment by ebfe** [comment]
Should work again.
