### ISSUE TITLE
Package Request: KDE 5

### ISSUE THREAD

**Issue by Spencer-H** [voidlinux/void-packages#4260]
I've poked around trying to package this myself, but I can't figure out how I'd go about it. With some help explaining how I should structure the packages I might be able to, but it would probably be better if someone more experienced did so.

**Comment by Vaelatern** [comment]
@subsonik was doing work on this

**Comment by subsonik** [comment]
I've since moved over to bspwm and haven't played around with KDE much recently but feel free to hit me up on IRC (SaveTheRobots) and I'll be happy to offer whatever assistance I can. :)

**Comment by Vaelatern** [comment]
@subsonik You still have an open PR, is it a dep of KDE5?

**Comment by subsonik** [comment]
#3989 is a dependency of KDE5, yes.

**Comment by realiddqd** [comment]
So, no one  working on kde5? I myself tryed to compile kde5 but failed cuz im ordinary user. Not like i want to change distro because of kde5, but i suffer tearing on cinnamon with nvidia blob and would like to see painless kde as my DE.

**Comment by Vaelatern** [comment]
@realiddqd Eventually someone might care and will also put forth effort to make that caring a reality. Until then, no, nobody is really working on KDE5.

**Comment by dutsky** [comment]
I hope i'll to that. I've already packaged kf5 + plasma for myself. But there are a lot of things to do and quality of my work is awful and I don't have any ideas how to safely put it to official void-packages :)

I hope I'll finish it.

**Comment by Vaelatern** [comment]
@dutsky We welcome your contribution!

**Comment by 5paceToast** [comment]
For anyone interested, there's a tracker issue over at #4963 . Probably makes sense to close this.

**Comment by Vaelatern** [comment]
This can stay open until the merge is complete.

**Comment by maxice8** [comment]
is it complete ?
