### ISSUE TITLE
LLVM: llvm-config leaks a build path

### ISSUE THREAD

**Issue by mpu** [voidlinux/void-packages#4263]
When running `llvm-config --cxxflags` a path from the chroot is leaked. This causes compilation errors for software that uses llvm-config to build and link with LLVM. I'm also not sure about the presence of both -O2 and -O3 in the output, maybe the optimization level should not be specified at all.

Here is the complete output of the above command:

    -I/usr/include -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -std=c++11 -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS

**Comment by ebfe** [comment]
#3816
