### ISSUE TITLE
Use 'tags' to classify templates

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#427]
Tags can be used to put packages in the right repository. e.g.:

```
pkgname=foopkg
...
tags='nonfree games'
```

this will put the package into the nonfree repository.

hooks can use this information to gain meta information about the package. The ```tags``` field must not have any influence on the configure or build process.

there will be no list of allowed keywords in tags, nevertheless there will be a list of recommended keywords. Such as:

* games
* office
* nonfree
* debug
* devel
* base
* ...

**Comment by thypon** [comment]
Close +1
