### ISSUE TITLE
package request: spotify and spotify-tunigo extensions for mopidy

### ISSUE THREAD

**Issue by miltonbabbitt** [voidlinux/void-packages#4273]
Mopidy extensions for browsing and playing music from Spotify.

https://github.com/mopidy/mopidy-spotify
https://pypi.python.org/pypi/pyspotify
https://github.com/trygveaa/mopidy-spotify-tunigo
https://github.com/trygveaa/python-tunigo

**Comment by allan** [comment]
use python pip to install mopidy extensions:

    # xbps-install python-pip python-devel libffi-devel void-repo-nonfree
    # xbps-install -S libspotify-devel
    # pip install Mopidy-Spotify
    # pip install Mopidy-Spotify-Tunigo
