### ISSUE TITLE
lldb conflicts with python2.7-six

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4281]
Both ship `/usr/lib/python2.7/site-packages/six.py`

**Comment by Vaelatern** [comment]
https://gist.github.com/829a84efbafaa483ccf7a1cf85dd8d54
Identical checksums and on a cursory glance the files look the same too.
My impression is they just bundle it. http://blog.gmane.org/gmane.comp.debugging.lldb.devel/month=20160501
Suggestion is to make `lldb` depend on `python-six` and remove the file within `lldb`.

**Comment by chneukirchen** [comment]
+1
