### ISSUE TITLE
ts conflicts with moreutils

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4282]
```
moreutils-0.59_1        /usr/bin/ts
ts-0.7.6_1              /usr/bin/ts
moreutils-0.59_1        /usr/share/man/man1/ts.1
ts-0.7.6_1              /usr/share/man/man1/ts.1
```

**Comment by Vaelatern** [comment]
They really have nothing to do with each other. `moreutils` uses `ts` as a filter for working with timestamps and `ts` is a task spooler for basic job management in a multiuser environment.

**Comment by Vaelatern** [comment]
Possible fixes:
- Rename one of the implementations to be `taskspool` or `timestamps` or something.
- Make a `moreutils` subpackage `moreutils-ts` which conflicts with `ts`.
I favor the second.

**Comment by Gottox** [comment]
I'm favoring an epic battle to the death between the maintainers of moreutils and ts. Loser has to rename the binary. Or the maintainers just decide: @lemmi vs @chneukirchen.

**Comment by lemmi** [comment]
i see moreutils als a convenient toy collection. i'm a little busy atm, but i'll get to it asap.

**Comment by lemmi** [comment]
moreutils also ships a parallel tool which i renamend to moreutils-parallel. any objections to just doing the same thing with ts and adding a install message that these two things are renamend?

**Comment by Vaelatern** [comment]
That sounds reasonable. Be sure to link this issue in your PR.

**Comment by Vaelatern** [comment]
Or, rewriting both packages to provide alternatives for `ts`

**Comment by lemmi** [comment]
alternatives don't really make sense. the tools don't have much in commen from what i gathered.

**Comment by Vaelatern** [comment]
They are not the classic alternative groups, but to allow a person to decide which has the short name has advantages like short names.

**Comment by Gottox** [comment]
Feel free to rename it :+1:
