### ISSUE TITLE
figlet conflicts with figlet-fonts

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4283]
```
figlet-2.2.5_3          /usr/share/figlet/banner.flf
figlet-fonts-20150508_1 /usr/share/figlet/banner.flf
```

**Comment by Vaelatern** [comment]
They don't seem to be nearly the same font. It appears that `figlet` itself has the international version at 31897 characters and `figlet-fonts` has just an English verison at 7599 characters, less than a third of the one in `figlet`.
Suggested fix is to remove the one in `figlet-fonts`. With a positive reply, I'll do so.

**Comment by chneukirchen** [comment]
+1.
