### ISSUE TITLE
Libreoffice/i686 fails to compile

### ISSUE THREAD

**Issue by fanfani** [voidlinux/void-packages#4287]
hello there, 

as discussed on the void linux forum (see https://forum.voidlinux.eu/t/libreoffice-on-i686), there is currently no option to install libreoffice on 32-bit systems, as the source package fails to compile with unit test errors and (of course) binary packages are not available. The problem has ben noted since version 5.1.2 of libreoffice.

I would like to see this resolved, since libreoffice is a very popular free office suite, and perhaps an important package for any desktop system. Moreover, 32-bit PCs are still widespread and far from being deprecated.

Best way to fix this, i don't know: googling around i found some it looks like folks from other distros are having the same issue (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=815292).

Options i can think of:

- Fix the code somehow and add a patch in the void source repo
- File a bug upstream
- Fallback to a previous working version of libreoffice
- Add an option to compile/install both "still" (stable release) and "fresh" (bleeding edge release) versions of libreoffice (hoping "still" does not show the same error)

Greetings,
Emiliano

**Comment by pullmoll** [comment]
I disabled the failing unit test for a try. Now i686 build passes. Of course this means the resulting binary may be broken, if it was not the unit test itself which was wrong in the first place.

Take care and, if possible, please try to verify that the functionality which failed in the unit test works ok for you.

**Comment by fanfani** [comment]
...thank you!

well, i'm not sure what the test actually means, however i did this: created a new writer document, added an OLE shape, rotated it, and exported the document. everything worked as expected.

**Comment by pullmoll** [comment]
I think the sequence is import, export, import again. The second import seems to be different from the first one and has some different x coordinate according to the Cppunit test log. Perhaps you can look at the coordinates of the shape in the first and the second import to see the difference.

I'm not sure if it really matters, you just have to keep in mind that officially this binary didn't pass the tests. So please don't blame me, if you produce broken documents with it :hand:

**Comment by pullmoll** [comment]
BTW 5.1.4.2 is out and I'll be testing if i686 is still broken there.

**Comment by fanfani** [comment]
> I think the sequence is import, export, import again.

did that. no noticeable change in shape attributes (size, position, color, etc)

**Comment by pullmoll** [comment]
FWIW I searched for the failing test in the source tree and here's the code:
```
DECLARE_OOXMLEXPORT_TEST(testFlipAndRotateCustomShape, "flip_and_rotate.odt")
{
    xmlDocPtr pXmlDoc = parseExport("word/document.xml");
    if (!pXmlDoc)
        return;
    // there should be no flipH and flipV attributes in this case
    assertXPathNoAttribute(pXmlDoc, "//a:xfrm", "flipH");
    assertXPathNoAttribute(pXmlDoc, "//a:xfrm", "flipV");
    // check rotation angle
    assertXPath(pXmlDoc, "//a:xfrm", "rot", "13500000");
    // check the first few coordinates of the polygon
#ifndef MACOSX /* Retina-reatled rounding rountrip error
                * hard to smooth out due to the use of string compare
                * instead of number */
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[1]/a:pt", "x", "2351");
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[1]/a:pt", "y", "3171");
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[2]/a:pt", "x", "1695");
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[2]/a:pt", "y", "3171");
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[3]/a:pt", "x", "1695");
    assertXPath(pXmlDoc, "//a:custGeom/a:pathLst/a:path/a:lnTo[3]/a:pt", "y", "1701");
#endif
}
```
So at least on MACOSX there is a known rounding error happening, which is why these specific lines are disabled. I guess if the i686 build failure persists, which is what I expect, I'll rather add a patch to also disable the x and y coordinate checks for I686 being defined (or whatever macro we have to check for the build type).

The rounding error may be visible on the i686 for some processor archtiecture internal reasons which we won't be able to track down.
