### ISSUE TITLE
Package Request : nodejs lts package 4.4.x

### ISSUE THREAD

**Issue by espositom221** [voidlinux/void-packages#4293]
Hi is possible add nodejs lts version, not all package are comaptible with 6.1.x.
regards

**Comment by Gottox** [comment]
Can you provide examples? Which packages aren't working?

I try to avoid the python2 vs python3 situation with node here.

**Comment by Anachron** [comment]
Just use any node version manager like everybody else does :P

**Comment by Gottox** [comment]
no reply in 4 months

closed.
