### ISSUE TITLE
Package Request: Charfbuzz

### ISSUE THREAD

**Issue by PlanetGit1** [voidlinux/void-packages#4297]
Hello everyone,

I would like to know if it's possible to include charfbuzz in void linux instead of harfbuzz. This package is better because it's written in C language compared to the original one.

https://github.com/sylware/charfbuzz

Thank you for taking my demand into account

**Comment by ayghor** [comment]
Don't know anything bout harfbuzz, but charfbuzz says:

> This is a *partial* C90ish port of harfbuzz

This mean it is *partial*ly better? Or that it offers *partial* functionality?

It also has a FIXME file with a known (possibly rare) race condition.

Is there any other reason to substitute harfbuzz with charfbuzz, except for it being written (*partially?*) in C? Harfbuzz seems to be much more actively developed, even though it is written in C++.

**Comment by PlanetGit1** [comment]
It does actually support only roman languages, that's why it's partial. Work is going forward on that side.
The possibly rare race condition is in harfbuzz not in Charfbuzz but the developer decided to mention it.
Charfbuzz is an alternative for those who want to work in C only and it is actively supported by the developer.

**Comment by Vaelatern** [comment]
Definitely not "instead of". Possibly as an option you can try out.

**Comment by PlanetGit1** [comment]
Yes, I was thinking about it as an option. I should have turned the sentence otherwise, sorry for the bad comprehension.

**Comment by mhosken** [comment]
Why do you care whether it's pure C on the inside. On the outside, harfbuzz looks like it is a simple C library. The fact they are using C++ language internally isn't evident. No name munging no linking to stdc++ etc. Just pretend it's C and all will be well. Sounds crazy to create lots of bugs by trying to rewrite what works fine.

**Comment by PlanetGit1** [comment]
Making a distro with less bugs as possible is a good thing to do.
By converting harfbuzz in C the developper did detect and correct a bug. 
Linus Torvalds who works on the kernel also explained why it's better to use C, you can find what he said here : http://harmful.cat-v.org/software/c++/linus
So it will not create bugs to use Charfbuzz, it's the exact opposite because it will takeoff a bug and make voidlinux better !!!

**Comment by Vaelatern** [comment]
I'll quote again: "C90ish *partial port* of harfbuzz"

**Comment by PlanetGit1** [comment]
It's not abandonned, work is in progress.

**Comment by mhosken** [comment]
My concern is that there is a real danger here of yet another partially implemented opentype engine that sort of works but doesn't for all fonts. We have plenty of those already and it means that OpenType becomes merely OpenTypeIsh and, particularly for the more obscure scripts, users suddenly find that your system just won't work for them for no apparent reason. If you want to port, then please port all of it, including all the shapers. TIA.

**Comment by Vaelatern** [comment]
Last commit at end of year 2015. Seems abandoned.

**Comment by pullmoll** [comment]
Sorry, but with [this FIXME](https://github.com/sylware/charfbuzz/blob/master/FIXME) the package does not seem stable enough to be considered non-alpha.

**Comment by PlanetGit1** [comment]
Well, the idea is to propose it as an option for those who want to work with it. It's a feature for developpers and those who want to give it a try. And as I said it correct some bugs so it's not a regression, it's the opposite.
By default harfbuzz will stay in place so there is no impact at all for anybody except those who will install Charfbuzz.
No modification is necessary anywhere in the distro, you just have to propose it in the package list of xbps and it's done.
The creator of Charfbuzz use it perfectly on debian 8 and he just dropped it inside with no modification at all....

**Comment by mhosken** [comment]
It's great that the development of charfbuzz found some bugs in harfbuzz. But, assuming the bugs that charfbuzz fixes were reported to harfbuzz, they are now fixed there too. So charfbuzz still gains us nothing and due to lack of feature parity, will cause problems for users.

**Comment by PlanetGit1** [comment]
I let you imagine all the bugs which are waiting to be discovered in harfbuzz ;)
Developers could help over developers when they do an excellent job. Don't you think so ?
With all the points I gave here combining to the fact that it has no impact for those who don't use Charfbuzz there is no reason to not put it in the distro. This code is written in C which is far more better than C++ .

**Comment by Gottox** [comment]
We won't replace harfbuzz with an incomplete and untested rewrite.

Feel free to reopen once charfbuzz is at a usable state.
