### ISSUE TITLE
Package Request: Apache Cloudstack

### ISSUE THREAD

**Issue by kulinacs** [voidlinux/void-packages#4305]
Unpackaged Dependencies:
- [ ] Apache Tomcat 6
- [ ] Python MySQLdb
- [ ] jsvc
- [ ] augeas-devel (Missing symlink in augas)
- [ ] libmysql-java
- [ ] libcommons-daemon-java
- [ ] vlan

**Comment by Vaelatern** [comment]
Oh man.
Out of curiosity, what's your use case for Cloudstack?

**Comment by the-maldridge** [comment]
@Vaelatern: https://lug.utdallas.edu/

**Comment by Vaelatern** [comment]
Can you provide a link to the `vlan` project?

**Comment by the-maldridge** [comment]
If I had to guess, its referring to this: https://packages.debian.org/jessie/vlan.  Most of those deps are pulled from the debian/control file on thier version of the CloudStack packages.

**Comment by the-maldridge** [comment]
As the UTD LUG no longer intends to consume this package, I motion to close this bug.  There are a number of serious code quality issues with the cloudstack project which make it unsuitable for packaging.
