### ISSUE TITLE
OctoXBPS: notifier binary missing

### ISSUE THREAD

**Issue by aarnt** [voidlinux/void-packages#4310]
Hi, version 0.2.0 is lacking the "octoxbps-notifier" binary.
If you go to "./notifier/octoxbps-notifier" src-path you'll see another project file you can generate with "qmake".
I think it's a good idea to pack the two binaries in the same package.
The notifier is a useful tool that sits in the notification area and goes from green to red when there are new updates in the distro, so users can upgrade them without the need to start octoxbps (although still watching a graphical output).

**Comment by ebfe** [comment]
be08db4932492de3eb533972db343d3afd52dce2
