### ISSUE TITLE
Update libpng to 1.6.23

### ISSUE THREAD

**Issue by Kayssyn** [voidlinux/void-packages#4311]
Please update libpng to 1.6.23: tarball for version 1.6.21 is no longer available
ftp://ftp.simplesystems.org/pub/libpng/png/src/libpng16/

**Comment by ebfe** [comment]
Please update your repo, is [1.6.22](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/libpng/template) still there

**Comment by Kayssyn** [comment]
Thank you!

**Comment by ebfe** [comment]
2c9ed48c94452f9048ae4a477d7f874f3dd2c2e1
