### ISSUE TITLE
Qt5: non-PIE executable in PIE build

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4313]
When trying to upgrade qt5 to qt5-5.6.1 this error comes up:
```
   Stripped executable: /usr/lib/qt5/bin/qmake
=> ERROR: qt5-qmake-5.6.1_1: non-PIE executable found in PIE build: /usr/lib/qt5/bin/qmake
=> ERROR: qt5-qmake-5.6.1_1: failed to run post-install_06-strip-and-debug-pkgs() at line 58.
```
Now qmake is a special executable, because it is built first and then used to bootstrap the rest of the build process. I don't know if and how to change that. It has been this way before and qt5 obviously is a package where both types of executables should coexist, no?

We certainly don't want to set `nopie=yes` for qt5 just because `06-strip-and-debug-packages` fails for this (and probably some more bootstrap) binaries.

Anyone got an idea how to get around this?

Edit: it looks like `nostrip_files="qmake"` could be used to skip that check in `common/hooks/post-install/06-strip-and-debug-packages.sh`. This variable is not documented in the manual and judging by its name I doubt its intention is to allow mixed non-PIE/PIE builds?

Edit2: `nostrip_files` doesn't seem to work here... *sigh*

**Comment by pullmoll** [comment]
ping @chneukirchen

**Comment by chneukirchen** [comment]
I'm at it. Gentoo has a fix.

**Comment by pullmoll** [comment]
Great. Is it like that qmake has to be rebuilt after its use for bootstrapping?

**Comment by chneukirchen** [comment]
Not sure why that happens, Gentoo also patches it out but it seems to work now.

**Comment by pullmoll** [comment]
Yep, except that for some reason the i686  build bot has not enough memory. It used to build there before...

Anyway, now the update to 5.6.1 should be possible. I'm going to try here first.
