### ISSUE TITLE
update infinality ultimate - xbps-src fontconfig failed

### ISSUE THREAD

**Issue by maoamid** [voidlinux/void-packages#4322]
./xbps-src -o ultimate pkg freetype
return 
patching file include/freetype/ftlcdfil.h
Hunk #1 FAILED at 250
Error: freetype-2.6.3_1: failed to run post_extract() at line 28

**Comment by ebfe** [comment]
#3829

**Comment by maoamid** [comment]
ty

**Comment by maoamid** [comment]
if I apply the patch a have problems with ./xbps-src -o ultimate pkg fontconfig:

error: fontconfig-2.11.1_6: failed to install 'freetype-devel-' dependency (error 2)
