### ISSUE TITLE
Difficulties trying different grafix drivers

### ISSUE THREAD

**Issue by nkcyham** [voidlinux/void-packages#4337]
Hi

I am trying to test different grafix drivers for my Radeon HD8400E
controller in my Compulab fit-PC4 box. I first incorrectly installed
the nvidia-364.19_2 package but of course it would not do so I 
removed it and re-instated the amdgpu driver. But it seems the the
nvidia package was not completely removed - nvidia-libs-364.19_2
was not removed. I tried to remove it manually but it didn't work:

```
nvidia-libs-364.19_2 (remove) breaks installed pkg `MesaLib-devel-11.2.2_2'
nvidia-libs-364.19_2 (remove) breaks installed pkg `SDL-1.2.15_10'
nvidia-libs-364.19_2 (remove) breaks installed pkg `cairo-1.14.6_2'
nvidia-libs-364.19_2 (remove) breaks installed pkg `libva-glx-1.7.0_1'
nvidia-libs-364.19_2 (remove) breaks installed pkg `mpv-0.17.0_2'
nvidia-libs-364.19_2 (remove) breaks installed pkg `webkitgtk2-2.4.11_2'
nvidia-libs-364.19_2 (remove) breaks installed pkg `xorg-server-1.18.3_2'
Transaction aborted due to unresolved dependencies.
```

I now wonder if this is a required package, for a machine that has
a Radeon GPU and whether it was installed as a dependency.

I tried to install catalyst, but I have the following problem:

```
CONFLICT: catalyst-15.302_1 with installed pkg xorg-server-1.18.3_2 (matched by xserver-abi-video>19_1)
Transaction aborted due to conflicting packages.
```

How can I fix this, if it is possible?

My thanks in advance!

**Comment by Duncaen** [comment]
https://wiki.voidlinux.eu/Proprietary_Video_Drivers#Switching_back_to_the_open_source_drivers_2

**Comment by nkcyham** [comment]
Thanks Duncaen

It didn't really work because of some cyclic? depenmdencies loop:
```
xbps-install libEGL
SDL-1.2.15_10: broken, unresolvable shlib `libGL.so.1'
cairo-1.14.6_2: broken, unresolvable shlib `libGL.so.1'
libva-glx-1.7.0_1: broken, unresolvable shlib `libGL.so.1'
mpv-0.17.0_2: broken, unresolvable shlib `libGL.so.1'
webkitgtk2-2.4.11_2: broken, unresolvable shlib `libGL.so.1'
xorg-server-1.18.3_2: broken, unresolvable shlib `libGL.so.1'
Transaction aborted due to unresolved shlibs.
```

```
xbps-install libEGL
cairo-1.14.6_2: broken, unresolvable shlib `libEGL.so.1'
libva-glx-1.7.0_1: broken, unresolvable shlib `libEGL.so.1'
mpv-0.17.0_2: broken, unresolvable shlib `libEGL.so.1'
webkitgtk2-2.4.11_2: broken, unresolvable shlib `libEGL.so.1'
Transaction aborted due to unresolved shlibs.
```
I just uninstalled xorg and several packages related to it and installed again,
it worked this time. However I found out more relating to another issue I
reported, about the very slow rendering of wire frames by one of my own 
apps, xnec2c: with nvidia-libs installed, it renders a lot faster than with
libGL/libEGL installed. This also happens if I remove firmware blobs intended
for the KABINI GPU's, so I think libGL/libEGL don't play well with KABINI
firmware involved. This happens in other distros too, Arch and Debian tested.
