### ISSUE TITLE
Circular dependency openldap, libsasl, mit-krb5, openldap, ...

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4338]
There's a circular dependency which shows when you try to build e.g. `openldap` with `./xbps-src -N pkg openldap`. Right now you can only build one of the packages without `-N` to break out of the circle.

**Comment by Vaelatern** [comment]
Options:

- Revert #4277.
- Make #4277 a build option.
- Build option to build `libsasl` with `mit-krb5` support. Just tested this, only disables GSSAPI support by default.

I'm happiest with that last option.

**Comment by the-maldridge** [comment]
As its most common to use LDAP with Kerberos, I'd rather not accept any solution which breaks that pairing.

**Comment by Vaelatern** [comment]
@the-maldridge Do you think the third solution in my list above is reasonable? Circular dependencies are not very nice things to keep around, and a solution must be found.

**Comment by the-maldridge** [comment]
@Vaelatern I am concerned that your solution defeats the entire point of building libsasl with krb5 in the first place.  Without GSSAPI support there isn't much use in actually having something which requires GSS-SPNEGO to be useful.

**Comment by pullmoll** [comment]
Just thinking out loud: perhaps it is possible to detect a loop in `xbps-src` dependency tracking. When a package in the list of dependencies to be built is hit a second time, disregard the `-N` and build it with *foreign* dependencies.

Later on the specific package should be built again, this time with the required *local* packages, because it is still in the dependecy list.

This does not solve the singular case where the main repo would have to be built from scratch. This still would need human intervention.

**Comment by chneukirchen** [comment]
xbps itself cannot deal with cyclic dependencies currently.

(e.g. xbps-remove -o will return in infinite loops.)

**Comment by Vaelatern** [comment]
I'm in favor of a "bootstrap" buildopt for any case where cycling dependencies make sense, for the human intervention case.

**Comment by chneukirchen** [comment]
Are you sure building libsasl without mit-krb5 breaks anything?

Note that cyrus-sasl and cyrus-sasl-modules-gssapi are built in different templates.

**Comment by the-maldridge** [comment]
I'm pretty sure I'm running the only site that is using most of the sasl stuff since I'm the one that PR'd a fair deal of the kerberos stuff in.  Lets try building libsasl without mit-krb5 and see what happens.  If it breaks we'll revisit it and come up with a different solution.
