### ISSUE TITLE
qt5-webkit: infinite audio/video length and impossibility to rewind

### ISSUE THREAD

**Issue by 0rdy** [voidlinux/void-packages#4360]
After the last update qt5-webkit video/audio playback is working, but now I got another trouble.
![1466659627](https://cloud.githubusercontent.com/assets/9018005/16292754/f56886e2-391c-11e6-9c11-c7ef5e39a495.png)

**Comment by pullmoll** [comment]
This seems to be an old, known bug: https://github.com/QupZilla/qupzilla/issues/1461
I have no clue how I could fix this on our end of things.

**Comment by asergi** [comment]
Sorry, didn't mean to close the issue. Waiting for confirmation.

**Comment by pullmoll** [comment]
The problem is gone. Now qutebrowser requires the plugin gst-plugin-good1 to play the HTML5 videos.
Perhaps qutebrowser should get a depends="gst-plugin-good1" then.

**Comment by 0rdy** [comment]
Yes, it works now. Thank you for fix.

**Comment by cavalier911** [comment]
Trying to play any radio station on radionomy.com or tunein.com locks up on my system.
Youtube is unstable, sometimes there is no audio. 
A package I built using[ template](https://github.com/voidlinux/void-packages/commit/8660957a77e90eb10af81a8d89d2def88eae924e) that has nothing more than qt5-multimedia-devel added to makedepends has none of these problems. 
Using qutebrowser and otter-browser on x86_64 system.

**Comment by The-Compiler** [comment]
@cavalier911 That's a QtWebKit issue - not much you can do unfortunately.
