### ISSUE TITLE
qtractor-0.7.8 non-PIE executable found

### ISSUE THREAD

**Issue by biopsin** [voidlinux/void-packages#4362]
=> qtractor-0.7.8_1: running post-install hook: 06-strip-and-debug-pkgs ...
   Stripped executable: /usr/bin/qtractor_vst_scan
=> ERROR: qtractor-0.7.8_1: non-PIE executable found in PIE build: /usr/bin/qtractor_vst_scan
=> ERROR: qtractor-0.7.8_1: failed to run post-install_06-strip-and-debug-pkgs() at line 58.

build it with nopie, but some magic would be nice:)

**Comment by pullmoll** [comment]
Adding a `do_make()` function like the one following solves the issue for me:
```
do_build() {
        make LFLAGS="$LDFLAGS" ${make_build_args} ${makejobs}
}
```
Another way might be to patch `src/Makefile.qtractor_vst_scan` to add a line
```
LFLAGS=$LDFLAGS
```
using `sed` in a `pre_build()` function...

**Comment by biopsin** [comment]
thank you for showing alternatives, Maintainers call.

**Comment by pullmoll** [comment]
The package is now updated.
