### ISSUE TITLE
firefox: patch fix-gcc-tests.patch fails (firefox47.0)

### ISSUE THREAD

**Issue by predme** [voidlinux/void-packages#4368]
[Gist](https://gist.github.com/predme/5ef36c9b9b89d3efa7a26b7a966dd776)

**Comment by Vaelatern** [comment]
I'm not sure what the problem is. A patch for an earlier version of firefox doesn't apply to a later version of firefox. Closing as not constructive since whomever next updates firefox will have to update or remove that patch anyway.
