### ISSUE TITLE
New subpackage: xorg-server-xdmx

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#4374]
This subpackage is usefull to create remote multidesktop setups.

**Comment by cr6git** [comment]
@thypon What's new since 26 June 2016 ? 
Have you tried to create a template for `xorg-server-xdmx` ? 

Is this package still requested ?

**Comment by thypon** [comment]
It would be a nice addition. I never tried though.

**Comment by cr6git** [comment]
I'm currently working on it.

**Comment by cr6git** [comment]
@thypon I hope that's what you wanted.
