### ISSUE TITLE
Make less default manpager

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4375]
I propose to patch mdocml to use less by default.

It's part of the base-system anyway, and you hear nothing about complaints about this difference to other distros.

**Comment by Vaelatern** [comment]
I propose instead a default shell profile to set `$PAGER` to less, since that is both less work and user changeable if they really want to get rid of `less`

**Comment by chneukirchen** [comment]
it would at least need to set `$MANPAGER` instead.

**Comment by chneukirchen** [comment]
Also users wanting to get rid of less can just set MANPAGER=more.

Let the non-standard usecases be more work. :)
