### ISSUE TITLE
Package request: slstatus

### ISSUE THREAD

**Issue by ribmo** [voidlinux/void-packages#4389]
I'd like to request @drkh5h's [`slstatus`][1] as a Void package to complement dwm, etc.

> slstatus is a suckless and lightweight status monitor for window managers which use WM_NAME as statusbar (e.g. DWM).

https://github.com/drkh5h/slstatus

If there are no takers, I may be able to get familiar with packaging for Void and put something together myself in the coming weeks.

Thanks.

[1]: https://github.com/drkh5h/slstatus

**Comment by drkh5h** [comment]
@ribmo That would be really nice yeah! But do you think it is a good idea, as the configuration is done by recompiling?

**Comment by ribmo** [comment]
@drkh5h One of the beauties of Void's packaging system is that packages can be locally compiled/installed from source. This makes it trivial to maintain a custom [config.h][2] or just [tweak config.def.h via sed at build time][1]. :)

It's easy to maintain personal configuration and patches for other suckless Void-packages in this way ([dwm][3], [st][4], [ii][5], [dmenu][6], etc.) — it's great to be able to keep customisation in my own branch and have the upstream packages managed/updated via Void's xbps package manager (along with their deps).

However, I reckon a binary would be useful even limited to some simple, stable defaults like memory, CPU, disk usage. Perhaps even just the date/time if there are too many variables involved.

[1]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/st/template#L17
[2]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dwm/files/config.h
[3]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dwm
[4]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/st
[5]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/ii
[6]: https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dmenu

**Comment by drkh5h** [comment]
@ribmo ok you convinced me, do it!

**Comment by ribmo** [comment]
Ok, I'll look into this when I have some time.

[Void's contribution guidelines][1] state that only version-releases are accepted — not git revisions.

> Please note that we do not accept any packages containing non-release versions such as specific git- or svn-revisions anymore.

@drkh5h Do you have any plans to make an official release any time soon? Could you be persuaded to? ;)

[1]: https://github.com/voidlinux/void-packages/blob/master/CONTRIBUTING.md

**Comment by drkh5h** [comment]
@ribmo I can just make an 1.0 now :smile: as it is in an acceptable state at the moment.

**Comment by ribmo** [comment]
@drkh5h Awesome — thank you!

**Comment by drkh5h** [comment]
@ribmo I will do it today

**Comment by drkh5h** [comment]
@ribmo I will do it today

**Comment by drkh5h** [comment]
@ribmo done! sorry about the delay, but now I released v1.0! https://github.com/drkh5h/slstatus/releases/tag/v1.0

**Comment by ribmo** [comment]
Thanks @drkh5h!
