### ISSUE TITLE
Need a musl patch which fixes pthread_exit code to match kernel behavior

### ISSUE THREAD

**Issue by jasonwilliams200OK** [voidlinux/void-packages#4392]
Please apply a patch to musl-libc, which fixes the pthread_error code issue.

musl-libc commit: http://git.musl-libc.org/cgit/musl/commit/?id=384d103d94dba0472a587861f67d7ed6e8955f86
(refers to bug in this doc: https://www.kernel.org/doc/Documentation/robust-futex-ABI.txt)

Alpine port: https://github.com/alpinelinux/aports/commit/8b4bc947a74e8ca71490014a622ae0d8e4e72bcc

Original issue: dotnet/coreclr#5872

**Comment by Gottox** [comment]
Looks reasonable.
