### ISSUE TITLE
Kodi does not build on i686

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#4397]
Currently kodi is not built on i686. The template file documents this fact and references this failing build:

http://build.voidlinux.eu/builders/i686_builder/builds/21640

The log shows the following error:

make[1]: Entering directory '/builddir/xbmc-16.0-Jarvis/addons/skin.confluence/media'
/builddir/xbmc-16.0-Jarvis/tools/depends/native/TexturePacker/bin/TexturePacker -dupecheck -input . -output Textures.xbt
Makefile:15: recipe for target 'Textures.xbt' failed
make[1]: *** [Textures.xbt] Segmentation fault
make[1]: Leaving directory '/builddir/xbmc-16.0-Jarvis/addons/skin.confluence/media'
Makefile:302: recipe for target 'skins' failed
make: *** [skins] Error 2

I could reproduce this issue with xbps-src on one of my computers although the build process took which felt like ages on a weak Intel Atom CPU. However I'm completely clueless about the reason (programming error, bug in glibc or some library it is linked against?) for this segfault. TexturePacker segfaults as soon as the binary is started not matter what arguments are passed to it.

Since I'm really interested in trying void on my media center PC which only supports the i686 architecture, I would be really interested in getting a working build for kodi on i686 so if there's anything I could do to help debug this issue, please let me know. I guess building Texturepacker alone with debugging symbols would be a good start but the build system of kodi is so complex that I couldn't find a way to do that.

**Comment by the-maldridge** [comment]
Its worth pointing out that even when we could build Kodi for i686 it didn't work.  I tried a little over a year ago and there were consistent issues starting it.  I think Kodi has largely moved on from i686 and while it isn't exactly helpful to your case, I can say that a raspberry pi running void makes a very nice media frontend.

**Comment by Hoshpak** [comment]
Thanks for chiming in. Since other distributions offer working packages of kodi for i686, I didn't want to believe that it would be impossible to fix this issue. Instead of trying to debug the actual kodi code, I looked at how other distributions (notable Arch Linux and Christian Marillat for deb-multimedia) build their kodi packages. I came to the conclusion that building TexturePacker statically is causing the issue on i686. I am currently testing a patch which I will submit as a pull request once I could properly test it.

Of course this does not fix the other issue documented in #3302 you mentioned but I'm confident that I will find a way to solve this.

**Comment by xtraeme** [comment]
Simply getting rid of `--libdir=/usr/lib32` from `$configure_args` should be enough to get this working, AFAIK.

**Comment by Hoshpak** [comment]
Yes, that would indeed make the resulting build be able to find the proper userdata directory. I just confirmed that by removing $configure_args from the template, added all arguments from there manually except for --libdir and rebuilding the package.

**Comment by Vaelatern** [comment]
26f9506
