### ISSUE TITLE
Package request: python-pygame

### ISSUE THREAD

**Issue by archaeme** [voidlinux/void-packages#4400]
Homepage: http://pygame.org/news.html
Source: http://pygame.org/ftp/pygame-1.9.1release.tar.gz

**Comment by archaeme** [comment]
Some things that I've found while trying to build the package:
* linux/videodev.h should be changed to libv4l1-videodev.h in src/camera.h

**Comment by archaeme** [comment]
Made a PR for the package: https://github.com/voidlinux/void-packages/pull/4402

**Comment by ebfe** [comment]
0c046358d8fb8138e592480e1c0ba1e6f80d5eab

**Comment by archaeme** [comment]
Thanks for closing this issue.  Didn't realize this was still open...
