### ISSUE TITLE
Proposal to remove broken dcron

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#4405]
I propose that we remove dcron from the repos as it does not seem to actually provide scheduled job execution.  If it does by some means provide this it certainly doesn't do so in a way that is compatible with anacron as the manual would suggest it does.

The key issue is quite simple, it does not run jobs that are scheduled.

**Comment by Gottox** [comment]
Can you explain how you schedule your jobs? What exactly does not work?

**Comment by the-maldridge** [comment]
This would seem to be a case of the different crons not being completely feature complete while still being alternatives to each other.  Only cronie uses /etc/cron.d for drop in files, it seems all others read only the /etc/crontab file or users's specific crontab files.

**Comment by Vaelatern** [comment]
They are alternatives to enable quick switching between them. It's features like these that make that necessary.
