### ISSUE TITLE
Package request: bdf2psf

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#4414]
Debian utility to convert BDF font files to PSF format.
* https://packages.debian.org/sid/bdf2psf
* https://aur.archlinux.org/packages/bdf2psf/

> This package provides a command-line converter that can be used in scripts to build console fonts from BDF sources automatically. The converter comes with a collection of font encodings that cover many of the world's languages. The output font can use a different character encoding from the input. When the source font does not define a glyph for a particular symbol in the encoding table, that glyph position in the console font is not wasted but used for another symbol.
>
> When deciding about the position in the font for a particular glyph, the converter takes into account that in text video modes the video adapter copies the eighth column of the glyph matrix of symbols positioned in the pseudographic area to the ninth column. In order to create fonts for text video modes, the width of the glyph matrix of the source BDF font should be seven, eight, or nine pixels; otherwise the converter creates fonts suitable for framebuffer only.

**Comment by chneukirchen** [comment]
Added n 8ccbf66

**Comment by sunaku** [comment]
Thanks! :bow: Could you include the `/usr/share` directory as well? :information_desk_person: I'm unable to use bd2psf without it:

```sh
$ bdf2psf --fb bdf/Tamzen10x20r.bdf+bdf/Tamzen10x20b.bdf /usr/share/bdf2psf/standard.equivalents /tmp/symbols20160702-30025-tdzyq4 190 psf/Tamzen10x20.psf
bdf2psf: /usr/share/bdf2psf/standard.equivalents: No such file or directory
```

**Comment by chneukirchen** [comment]
Oops 6549895

**Comment by sunaku** [comment]
It works perfectly now, thanks! :joy_cat:
