### ISSUE TITLE
Package request: Google Noto Fonts

### ISSUE THREAD

**Issue by aeosynth** [voidlinux/void-packages#4436]
https://www.google.com/get/noto/

> Google has been developing a font family called Noto, which aims to support all languages with a harmonious look and feel.

i use noto fonts for the unicode support. on arch there are three packages: `noto-fonts`, `noto-fonts-cjk`, `noto-fonts-emoji`.

**Comment by Vaelatern** [comment]
Is it possible to install in your home directory on a base install (no compilation or make tools available)?
If so, it won't be accepted.

**Comment by aeosynth** [comment]
will try in my vm

**Comment by aeosynth** [comment]
wouldn't this fall under quality requirement 1?

> 1. System: The software **should** be installed system-wide, not per-user.

this is a system font

**Comment by Vaelatern** [comment]
xtraeme refuses to allow fonts that are not compiled in some way into the repo. I can't find the PR where he was harsh on this.

**Comment by ribmo** [comment]
@xtraeme Could exceptions be made for Noto? It is more valuable than just another typeface IMO.

> When text is rendered by a computer, sometimes characters are displayed as “tofu”. They are little boxes to indicate your device doesn’t have a font to display the text.
> 
> Google has been developing a font family called Noto, which aims to support all languages with a harmonious look and feel. Noto is Google’s answer to tofu. The name noto is to convey the idea that Google’s goal is to see “no more tofu”. Noto has multiple styles and weights, and freely available to all. The comprehensive set of fonts and tools used in our development are available in our GitHub repositories. 

I had planned to put together a package for this soon. I will probably still maintain a package locally for my own use but I certainly think others would benefit from it being in the repo.

**Comment by teh-jazzman** [comment]
I'm curious. What makes the Noto fonts more valuable than any other font? Just the fact that they, amongst themselfs, provide most glyphs in the unicode standard? There are other fonts that do that, Unifont for example.

**Comment by ribmo** [comment]
@teh-jazzman, yeah that's exactly what I liked about Noto. I wasn't aware of others so I'll check out Unifont, thanks.

Also, Noto's emoji support is nice. It's nice to be able to read emails from friends and family without squares or empty spaces.

**Comment by kurumushi** [comment]
notosans and notoserif are already in the void package tree. They are included in google-fonts-ttf.

**Comment by gotwf** [comment]
And imho this is one thing that sucks about void.  Installing a bazillion fonts just to get the ONE font you want.   Unifont is neither ttf nor otf, correct?  So it is not really a replacement for Noto.  

Of course Noto just happens to be my preferred sans/serif font.  Hence why this caught my eye and am weighing in with a 'me too' that it would be nice to have Noto font package.

**Comment by teh-jazzman** [comment]
For the protocol: I have nothing against Noto. I was merely pointing out that if your goal is to remove the "tofu" characters in foreign texts, Unifont will do that for you for about 12 MB. To get the same result with the Noto family, you would have to insall ALL Noto fonts, weighing about 500 MB. If you want a specific Noto font because you like its look&feel, go ahead install it. But in that case you don't need the whole 500 MB family package. A void package would be overkill for the same reason unless you want to create 100+ packages for each individual font. Aside from that, installing fonts is not hard. Just download the ones you want to have and install them by hand. There will never be packages for every free font out there and a discussion about which font is more important than another is futile to begin with.

**Comment by gotwf** [comment]
Obviously fonts can be installed per user in local fonts dir.  As can locally compiled source code.  This is a convenience issue.  Folks with a specific itch will break out pkgs for the fonts/software that scratches it.  Others can install the entire google font package.  Just like some window managers are packaged, e.g. bspwm, i3, etc., while others are not.  So popularity does have an affect here. 

But hey, I am just offering my opinion, wh/perhaps more appropriately belongs in context of issue #4649.  I have already compiled my preferred WM and installed Noto locally.  So it's no skin off of my nose.  It may, however, be some skin off a less experienced user's nose.  Hence the whole pkg manager 'craze'.  Pkg manager?  We don't need no stinkin' package manager.  Real men compile from source code.  Yeah, I have heard that argument bitd.  So where does Void want to be along that continuum?

P.S.; I don't know about your numbers there but my Noto weighs in at just under 20MB.  And looks a lot nicer ;D

**Comment by teh-jazzman** [comment]
As I said, I'm not against packaging Noto. I know it is a lot more convinient to just install a package as opposed to installing anything manually.

The problem I see here is this: Google claims that Notos main feature is to provide glyphs for all languages. However, no one Noto font does this. Noto is a font family with 100+ fonts for different languages (See https://www.google.com/get/noto/). If you really want complete coverage you need to install all of them. The combined ZIP-Download for the complete family is 472.6 MB in size.

If you just want complete glyph coverage, Noto fonts can achieve this, but would be very big for that purpose. On the other hand, If you want Noto as a regular font, you probably just want one and a complete package with all of them would be unneccessary overkill.

**Comment by asergi** [comment]
ce14b4e
