### ISSUE TITLE
Error while configuring python-2.7

### ISSUE THREAD

**Issue by elroncio** [voidlinux/void-packages#4480]
When I update python-2.7 I get this error:

```
[*] Configuring unpacked packages
python-2.7.12_1: configuring ...
Byte-compiling python code in usr/lib/python2.7...
Compiling usr/lib/python2.7/site-packages/pexpect/async.py ...
  File "usr/lib/python2.7/site-packages/pexpect/async.py", line 16
    transport, pw = yield from asyncio.get_event_loop()\
                             ^
SyntaxError: invalid syntax
```

**Comment by Duncaen** [comment]
This should not break, its there but asyncio shouldn't be used with python2.7 code.
https://github.com/pexpect/pexpect/issues/290

**Comment by asergi** [comment]
`async.py` is only used with python3. You can safely ignore it.

Anyway, removed the problematic file from the python2 package to avoid all the fuss.
