### ISSUE TITLE
Synergy unstable in recent versions

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#4503]
I use Synergy software to share mouse+kbd between two machines both Void glibc x86_64.
I did the same thing along the two previous years, when I was using Debian Sid, experiencing an almost perfect reliability of Synergy.

When recently I migrated from Debian to Void, I repeated the same installation and configuration of Synergy on the same hardware but now the server 'synergys' nine times out of ten crashes when I execute operations with the clipboard in the client machine.

Enabling debugging on DEBUG2 level I got same logs that many users, regardless of operating system, have long reported to the Synergy developers about the same issue
(possibly see https://github.com/symless/synergy/issues/4735 and really really many others..)

my point here is the following: why no problem when I was using Debian?
and a possible explanation catches my eyes:

  Void pkgver: **synergy-1.7.6_2**
  when Debian considers still unstable **synergy-1.4.16**, the version currently installed on Sid!!

..and, in the issue I linked above, a Gentoo(!) user says "For me Copy/paste was working reliably untill version 1.7.2. With 1.7.3 it works 10% of time"
as also a user, I conclude that the latest versions of Synergy are for sure particularly unstable and that the choice of Debian to stay with a so old version is quite significant..

I am convinced this is not an Void issue so recede Synergy in Void to a version that has evidence of stability is in some way considerable??

**Comment by Vaelatern** [comment]
Debian routinely chooses to stay on old versions of software to ensure maximum stability, regardless of what the current stable release of the software is. We choose to stay on the current stable release of software for the most part, trusting upstream to only mark releases they are sure of as 'stable'

We install the latest stable version. If we need to roll it back for stability, that's a different matter.
@ebfe, you have bumped the package recently, do you have an opinion?

**Comment by ebfe** [comment]
> @ebfe, you have bumped the package recently, do you have an opinion?

No opinion. I stopped using it after looking into the source.

**Comment by Vaelatern** [comment]
The linked issue says it'd be cleaned up with 1.7.6, the version we have. Is this not the case?

**Comment by paoloschi** [comment]
I found out now that was released a  **v1.8.1-stable** a few days ago
https://github.com/symless/synergy/releases/latest

**Comment by ebfe** [comment]
pullmoll bumped it to 1.8.2, 49ec2e3435358751877b355f3878cacfee22bcc5. Let's hope that helps.

**Comment by paoloschi** [comment]
I confirm that YES, due to the recent update, I have not had disconnection using the clipboard function anymore :-)

time to close this one and sorry for the noise, since it was not a Void issue..
