### ISSUE TITLE
python-M2Crypto-0.25.1_1 needs python-typeshed ?

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#4523]
the recent `python-M2Crypto-0.25.1_1` installs the file `/usr/lib/python2.7/site-packages/M2Crypto/util.py` which contains this portion of code

```
[..]
15  # This means "Python 2.7 or higher" so it is True for py3k as well
16  py27plus = sys.version_info[:2] > (2, 6)  # type: bool
17
18  from M2Crypto import m2, six
19  if py27plus:
20      from typing import AnyStr, Tuple, Union  # noqa
21      # see https://github.com/python/typeshed/issues/222
22      AddrType = Union[Tuple[str, int], str]
[..]
```

a python program that worked before, now complains it can not import the `typing` module (see line 20).

if I understand correctly, `python-M2Crypto-0.25.1_1` now needs the `python-typeshed` libraries, that do not seem to be present in the main repository..

**Comment by Vaelatern** [comment]
This seems to be correct.
