### ISSUE TITLE
kpcli-3.0_1: Missing Dependencies

### ISSUE THREAD

**Issue by kurumushi** [voidlinux/void-packages#4531]
kpcli-3.0_1 should have the following dependencies added:

perl-Term-ReadLine-gnu
perl-XML-Parser

Without these installed, the program will not run or open files.

`No usable Term::ReadLine::* modules found.
This list tried: Term::ReadLine::Gnu, Term::ReadLine::Perl, Term::ReadLine::Perl5`

`Couldn't load the file ./KeePass.kdbx: Cannot load XML library to parse database: Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at /usr/share/perl5/vendor_perl/File/KeePass.pm line 1135.`

**Comment by slmingol** [comment]
I recently ran into this issue as well, unclear why where the `kpcli` was complaining about missing Term::ReadLine. I did a `brew reinstall kpcli` to resolve it.
