### ISSUE TITLE
May not need srcpkgs/boost/patches/libressl-2.3.patch

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#4552]
e4rat-lite failed to build due to an error concerning a stray endif using the Void binary package.
I built this later version of boost from source modifying the template, (1hr 50m on a 1.8GHz P4M):
pkgname=boost
version=1.61.0
revision=1
checksum=a547bd06c2fd9a71ba1d169d9cf0339da7ebf4753849a8f7d6fdb8feee99b640

When I looked at the source code the patch was already in there, so I think the error with the older version could be because the patch was applied when it wasn't needed. But as it was an 80MB download I didn't get the older version source to check.
I was going to try and make an e4rat-lite package and look more at  this issue later, but then my HDD failed an fsck at boot due to file system corruption which could be due to using e4rat-lite-realloc so that has been reconsidered, although it worked very well at reducing the boot time from 53s to 37s. I had repeated file system corruption events in Debian 7 using EXT4 and fedora-readahead.

**Comment by xtraeme** [comment]
We are not using boot-1.61 yet, so this issue is non existent currently.
