### ISSUE TITLE
Package request: acmetool

### ISSUE THREAD

**Issue by jsumners** [voidlinux/void-packages#4567]
https://github.com/hlandau/acme

This is a tool written in Go that facilitates acquiring, and maintaining, SSL certificates through letsencrypt.org

**Comment by Vaelatern** [comment]
Could be a good alternative to `certbot`... that package is difficult to get the dependencies for.

**Comment by jsumners** [comment]
I didn't know about `certbot`. But `acme` makes things really, *really*, simple. It's default execution is to renew previously requested certificates. And it stores said certificates in a known location in pem format recognizable by all the major HTTP servers and HAProxy.

**Comment by Vaelatern** [comment]
b2af500
