### ISSUE TITLE
Package Request: uMurmur

### ISSUE THREAD

**Issue by phikal** [voidlinux/void-packages#4569]
[Repository](https://github.com/umurmur/umurmur) / [Homepage](http://umurmur.net/)

uMurmur is a simple and small implementation of a Mumble server, used for voice chat. The only problem I have when trying to build it (Raspberry Pi B, musl) is that it's complaining that polarssl is missing when running `./configure`.

**Comment by Duncaen** [comment]
Added a runit service in 0da779d8e57e27d89c43301114211b76d20a775a.
