### ISSUE TITLE
Followup PIE Tracking Bug

### ISSUE THREAD

**Issue by Vaelatern** [voidlinux/void-packages#4572]
This is a followup from #4227 to remind us these package are still exhibiting errors related to PIE:

A great many many many packages have been fixed. These are the few remaining that we were tracking before.

- [x] boinc
- [x] boswars
- [x] brother-brscan3
- [x] celestia-glut
- [x] celestia-gtk
- [x] gtk-theme-config
- [x] gnome-shell
- [x] hooktftp
- [x] lm_sensors
- [x] mumble
- [x] nestopia
- [x] openjdk
- [x] openmpi
- [x] opensonic
- [x] rdis-git
- [x] swift
- [x] syslinux
- [x] tiv
- [x] tracker
- [x] xonotic

**Comment by pullmoll** [comment]
I think `hookftp` and `swift` can only be solved with `nopie=yes`.
I don't know `go` and whether there is an option to build PIE executables.
Now `swift` is a story on its own and it isn't my story :smile_cat:

**Comment by pullmoll** [comment]
There are more...
- [ ] psutils-p17_3
- [ ] python-PyQt4-4.11.4_2
- [ ] iniparser-4.0_3

**Comment by Duncaen** [comment]
Its possible to build go with PIE, but you need to change how go is bootstrapped and build the standard library with PIE enabled.
Its not easy with the current go template and how its bootstrapped, alpine has it working but they have a seperate go-bootstrap without PIE to build go.

**Comment by Vaelatern** [comment]
Can it be done with a build option?

**Comment by pullmoll** [comment]
Waiting for @thypon or someone else to look at #4733 and merge it, then we should be through the packages that currently build at all.

**Comment by Vaelatern** [comment]
For `hooktftp` I'm looking in to fixing the build to use the go build style.

**Comment by Vaelatern** [comment]
Given up, it really is not structured that way. For the sake of time, just marked nopie, to be sorted out later.

**Comment by Vaelatern** [comment]
Until more are found, if any are left, this issue is closed! Massive thanks to @pullmoll for all the work on this.
