### ISSUE TITLE
P2P support in wpa_supplicant

### ISSUE THREAD

**Issue by moinejf** [voidlinux/void-packages#4576]
P2P support is not enabled in wpa_supplicant
To enable it, please, in the config, add

CONFIG_WPS2=y
CONFIG_P2P=y
CONFIG_AP=y

Thanks

**Comment by Vaelatern** [comment]
Are these kernel configurations?

**Comment by moinejf** [comment]
On Mon, 08 Aug 2016 05:38:49 -0700
Toyam Cox <notifications@github.com> wrote:

> Are these kernel configurations?

No.
In the wpa_supplicant source, they are in wpa_supplicant/.config
(copied and adjusted from wpa_supplicant/defconfig).
In the void-packages, these definitions should go in

	wpa_supplicant/files/config

-- 
Ken ar c'henta�	|	      ** Breizh ha Linux atav! **
Jef		|		http://moinejf.free.fr/

**Comment by Vaelatern** [comment]
So why not open a PR?

**Comment by moinejf** [comment]
I will try to do it...

**Comment by moinejf** [comment]
I will try to do it...

**Comment by moinejf** [comment]
I will try to do it...

**Comment by moinejf** [comment]
I will try to do it...

**Comment by moinejf** [comment]
I will try to do it...

**Comment by moinejf** [comment]
I will try to do it...
