### ISSUE TITLE
qt5 cross tester wanted

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4579]
I have no hardware to test armv6l or armv7l and couldn't get a `qemu-arm` setup for `rpi` working with the void rootfs. :sob:

Could someone who has a `rpi` or `rpi2` running with void (glibc or musl) test one of the packages at:
http://repo.voidlinux.de/current/qt5-cross/ or http://muslrepo.voidlinux.de/current/qt5-cross/

It should suffice to install the `qt5-examples` package and run e.g. `/usr/share/qt5/examples/webview/minibrowser/minibrowser` to see if the cross built qtwebengine works. The `gl` demos may be a good test as well, because I don't know if the `-opengl es2` configuration is correct.

Or alternatively: is there a HOWTO describing what's needed to get `qemu-arm` to run Void?

**Comment by ayghor** [comment]
I has a rpi right here, just has to install void on it. Will do this tomorow!

**Comment by pullmoll** [comment]
I found my beaglebone black bord. I created an SD card as described in the [WIKI](https://wiki.voidlinux.eu/Beaglebone), but the board does not want to boot it.

The beaglebone rootfs, MLO and u-boot.img are supposed to run on the beaglebone black, no?

Too bad, otherwise I could have tested things here...

**Comment by ayghor** [comment]
installing...

**Comment by ayghor** [comment]
I just found that I'm lacking a sd card writer and my android(tm) smartphone is not really smart at all. Sorry for that! I'll try to get teh sd card hw later today!

**Comment by pullmoll** [comment]
Never mind.. I got qemu-system-arm boot into void via a foreign kernel and can now setup xorg etc. to test the qt5 armv6l images.

**Comment by Vaelatern** [comment]
So issue is closed?

**Comment by pullmoll** [comment]
Not yet, no. I'd be happy if someone could test it on real hardware.

**Comment by pullmoll** [comment]
It sort of worked on my beaglebone black. Should suffice for a first test, more to come.
