### ISSUE TITLE
Issue: Rakudo fails to update

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#4585]
[*] Running transaction tasks
rakudo-2016.03_1: updating to 2016.07.1_1 ...
rakudo-2016.07.1_1: unpacking ...
ERROR: rakudo-2016.07.1_1: [unpack] failed to extract file `./usr/share/perl6/short/F6FD7A4346B3BB0E3124991926D729836808DA54/3FD70CCCD6914FAEC8  AFAE6F97AF461A3EE1588': Not a directory
ERROR: rakudo-2016.07.1_1: [unpack] failed to extract files: Not a directory
ERROR: rakudo-2016.07.1_1: [unpack] failed to unpack files from archive: Not a directory

**Packages before rakudo update fine but the upgrade process is halted once it hits the rakudo error.**

**Comment by chneukirchen** [comment]
Remove the packages first, then reinstall.

Didn't have time to debug what happens there.
