### ISSUE TITLE
valgrind: the helgrind tool seems broken on Void

### ISSUE THREAD

**Issue by CMB** [voidlinux/void-packages#4608]
I'm using valgrind's helgrind tool to track down some race conditions.
I noticed that it was giving a bunch of spurious false positives.  In other
words, it was complaining about races that I could prove do not exist.
So I wrote a very simple little program to test it.
This program doesn't have a race condition, yet helgrind complains about one.

I ran it on a Gentoo VM for comparison, and helgrind works fine there.
It found no races.

Here's my simple test.
http://the-brannons.com/foo2.c

And here's my log from valgrind on Void:
http://the-brannons.com/29282.log

I am running valgrind 3.11.0_4.

**Comment by chneukirchen** [comment]
I think this is because of the musl patch that changes `VG_Z_LIBC_SONAME` unconditionally.

@duncaen?
