### ISSUE TITLE
Unresolvable shlib liborcus-0.11.so.0 for libreoffice

### ISSUE THREAD

**Issue by tudurom** [voidlinux/void-packages#4653]
`liborcus` was updated to version 12 but libreoffice wants v.11. xbps keeps complaining about this and won't let me install anything.

**Comment by pullmoll** [comment]
Wait a minute, or rather several. The fix is building now:
https://build.voidlinux.eu/builders/x86_64_builder/builds/25267/steps/shell_3/logs/stdio

**Comment by pullmoll** [comment]
Should be solved now.

**Comment by tudurom** [comment]
Fixed, thanks!
