### ISSUE TITLE
ffmpegthumbnailer error

### ISSUE THREAD

**Issue by shaggytwodope** [voidlinux/void-packages#4659]
Not sure what other file managers may use this for thumbnails, but it's broken for me in ranger. Giving me the error `Error: Failed to get buffer from filter Resource temporarily unavailable` if I run the command `ffmpegthumbnailer -i videofile.mp4 -o test.png` manually. It generates a black image file with 0 byte size.

As far as I can tell the latest release is giving me the same error as mentioned here: https://github.com/dirkvdb/ffmpegthumbnailer/issues/124 . It appears to be fixed with the current master.

**Comment by pullmoll** [comment]
I hope upstream will then release 2.1.3 soon. 2.1.2 was released just a couple of days ago. I don't think it's worth trying to temporarily create a git based release, as we try to avoid that.

**Comment by shaggytwodope** [comment]
@pullmoll It's a good policy, no argument here. But just for knowledge sake, what situations is it acceptable to use git based releases?

**Comment by Vaelatern** [comment]
Generally we accept git releases when the software is old and the project is unlikely to have more activity, in which case we want the latest that the authors released.

**Comment by dirkvdb** [comment]
I just released ffmpegthumbnailer-2.2.0

**Comment by pullmoll** [comment]
Thanks @dirkvdb for the quick fix and @Duncaen for updating before I could even take a look :-)

**Comment by shaggytwodope** [comment]
Thank you everyone, it all works wonderfully. @dirkvdb thanks for the amazing tool and @pullmoll & @Duncaen for making void awesome.
