### ISSUE TITLE
Package request: neovim

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#466]

**Comment by steski** [comment]
@bougyman were you waiting for a release? I ask because I packaged this just to try out  and just came across this request.

**Comment by cgag** [comment]
+1 on this request

**Comment by steski** [comment]
Still no release

**Comment by cgag** [comment]
Is that a problem?  I've seen a few *-git packages that are just git snapshots.  I think that'd be really useful to have for neovim.

**Comment by steski** [comment]
The first public release is due by the end of this month
