### ISSUE TITLE
Missing `libtinfo.so.5`

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#4662]
Some programs expect this so to be present. In my case, it was _elm_, installed via `npm install -g elm`.

Searching on teh interwebs, I found that _ncurses_ lib was split and symlinking this to `libncurses.so.5` could work. Void has `libncurses.so.6`, but it seems to have worked anyway.

**Comment by chneukirchen** [comment]
This is a Debianism you can hack around locally with a symlink.
