### ISSUE TITLE
fish-shell depends on python

### ISSUE THREAD

**Issue by logankaser** [voidlinux/void-packages#4663]
Fish shell depends on python(2.7) for much of its core functionality
like completions and man page scanning.

Without python install it make this know by via errors very often, every launch and run of man for example.
While most users already have python installed, it is not installed by default on void and needs to be added
to fish's deps.

**Comment by aeosynth** [comment]
the error message is fixed: https://github.com/fish-shell/fish-shell/issues/3588

python should be added as an optional dependency only imo

**Comment by aeosynth** [comment]
https://github.com/fish-shell/fish-shell/issues/3609#issuecomment-264125988

> The fish bespoke completion set has pretty good coverage already, so that you don't lose much by omitting manpage competitions.

**Comment by aeosynth** [comment]
with the 2.5.0 release, fish no longer errors when python is not installed. @logankaser can this issue be closed?

**Comment by logankaser** [comment]
Yes. Thank you.
