### ISSUE TITLE
mpg123: strange build error with alsa

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4671]
When trying to build mpg123, I see a strange error from `src/libout123/modules/alsa.c` including `alsa/asoundlib.h`
```
In file included from /usr/include/alsa/asoundlib.h:56:0,
                 from src/libout123/modules/alsa.c:25:
/usr/include/alsa/timer.h:108:19: error: field 'tstamp' has incomplete type
  snd_htimestamp_t tstamp; /**< Time stamp of each event */
```
The type is defined in `alsa/global.h` like this:
```
typedef struct timespec snd_htimestamp_t;`
```
and I can't see why this typedef should not be in scope when `alsa/timer.h` is included.
The header `alsa/asoundlib.h` includes `alsa/global.h` long before `alsa/timer.h`

Is there anyone with an idea how to solve this problem?

**Comment by chneukirchen** [comment]
Does adding `#include <time.h>` help?

**Comment by pullmoll** [comment]
Nope, it does not. I also tried `#include <sys/time.h>` to no avail.

**Comment by pullmoll** [comment]
It seems that for some not obvious reason `struct timespec` is not defined when `alsa/global.h` is included, but I can't see why.

**Comment by chneukirchen** [comment]
Probably related to the comment in alsa.c.

Adding `#include <time.h>` *before* _POSIX_SOURCE in src/libout123/modules/alsa.c fixes the build here.

**Comment by pullmoll** [comment]
DUH! Indeed, this is the way to fix it. Thanks!

**Comment by chneukirchen** [comment]
I wonder when exactly this broke, tho.

**Comment by pullmoll** [comment]
I know I compiled mpg123 about 3-4 weeks ago for the last time.
I regularly try to build all my installed packages from scratch, or even all packages, to see if and which errors pop up.
