### ISSUE TITLE
Retire armv6?

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4672]
We've checked ARM revisions, and only Raspberry Pi 1 needs armv6, newer Pi and other common ARM boards use armv7.

It is thus questionable to run armv6 builders, perhaps the resources could be freed to run aarch64 or mips builders instead.

We should look at the traffic stats to see how many people use armv6.

**Comment by Gottox** [comment]
I don't think we're there yet:
```
[root@build nginx]# grep -F /Jul/2016 access.log | grep -cF void-rpi-
3607
[root@build nginx]# grep -F /Jul/2016 access.log | grep -cF void-rpi2-
431
```

**Comment by Gottox** [comment]
For Aug it's telling a different story, but both are still significant.
```
[root@build nginx]# grep -F /Aug/2016 access.log | grep -cF void-rpi-
195
[root@build nginx]# grep -F /Aug/2016 access.log | grep -cF void-rpi2-
307
```

**Comment by ayghor** [comment]
nooo my rpi1 =o(

**Comment by chneukirchen** [comment]
Now we only need to figure out how many rpi2 users have downloaded plain rpi. ;)

**Comment by Vaelatern** [comment]
I use an rpi v1!
I don't see the case for retiring the arch. It's not like armv6 takes so much more developer effort than armv7.

**Comment by Gottox** [comment]
rpi1 is a perfect target for void. We provide a small and fast system in contrast to all the other distributions. And the sold units won't disappear magically. I think that we should stick with armv6.

**Comment by Gottox** [comment]
A general thought: We should never drop support ( = stop running the buildserver) for a platform except if the userbase is very small and maintaining gets too time consuming.

For armv6 it's pretty easy: If it builds on armv7, the chances are high that it will build for armv6 too.

**Comment by chneukirchen** [comment]
Proposal rejected.

**Comment by ayghor** [comment]
yay!
