### ISSUE TITLE
glib: musl quark_init_on_demand.patch incomplete?

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4683]
It looks like the patch `srcpkgs/glib/patches/quark_init_on_demand.patch` does not catch all cases where `quark_ht` is expected to be already initialized.

This can be seen when e.g. building NetworkManager for musl and the call from gtype.c:2752 to initialize the `static_quark_type_flags` fails with an assertion in `g_hash_table_lookup()`.

It seems we don't catch a specific order of functions being called here and miss the initialization of `quark_ht` in that sequence. Perhaps all places where the initialization is expected to have happened should just check if it really had?

I tried to modify the patch along these lines without success. As always help is welcome.

**Comment by Gottox** [comment]
@pullmoll are you in contact with the alpine guys? Maybe they have similiar problems.

**Comment by pullmoll** [comment]
See #4693
