### ISSUE TITLE
postfix: TLS support broken

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#4686]
After upgrading postfix on my glibc 64 bit system from version postfix-3.1.1_1.x86_64 to  postfix-3.1.2_1.x86_64 SSL/TLS/STARTLS is no longer supported, the error I get in the maillog is:

2016-08-29T13:33:27.697773+02:00 localhost postfix/smtpd[2397]: initializing the server-side TLS engine
2016-08-29T13:33:27.698105+02:00 localhost postfix/smtpd[2397]: warning: Digest algorithm "md5" not found
2016-08-29T13:33:27.698183+02:00 localhost postfix/smtpd[2397]: warning: disabling TLS support

**Comment by mdkuser** [comment]
downgrading to postfix-3.1.1_1.x86_64 solves the issue

so there must be something wrong with the postfix-3.1.2_1.x86_64 package...

**Comment by Gottox** [comment]
This is the diff between 3.1.1 and 3.1.2. There were changes regarding ssl. https://gist.github.com/71a7b3a3297ac7ecea2eec3fb4333787

**Comment by ebfe** [comment]
Due to the `#ifdef OPENSSL_VERSION...` OPENSSL_add_all_algorithms isn't called anymore, thus missing md5?

**Comment by Gottox** [comment]
libressl has `OPENSSL_VERSION_NUMBER	0x20000000L`... So expect a big ifdef-mess in the near future... :/

**Comment by Gottox** [comment]
I'm preparing a patch that reverts most of the openssl changes in postfix.

**Comment by ebfe** [comment]
Adding `|| defined LIBRESSL_VERSION_NUMER` is probably easier.

**Comment by mdkuser** [comment]
Thank you for looking into this issue and your swift response. Much appreciated.

**Comment by Gottox** [comment]
@ebfe true

**Comment by Gottox** [comment]
@mdkuser please check if postfix-3.1.2_2 fixes this issue.

**Comment by mdkuser** [comment]
i confirm it's working. Thank you for the quick fix! Much appreciated.
