### ISSUE TITLE
Perl 5.24 fallout

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4687]
- [x] @chneukirchen need to check if overriding PERL5LIB for Module::Build is sane (looks like it)
- [x] libmagick-perl-6.9.5.7_1 URL is 404, perhaps update to 7 already.
- [ ] some packages use explicit shlib_requires, would be nicer to force-link them to -lperl.
- [x] collectd-5.5.2_1 needs readdir_r treatment
- [x] znc cross build
- [x] perl-Term-ReadLine-Gnu cross
- [x] perl-Math-BigInt-GMP cross
- [x] perl-Tk-804.033_1 no X11 found
- [x] config changed, harmful?: usemultiplicity=undef (may be relevant for embedded perls, but is on), use64bitint=undef, uselongdouble=undef, removed PERL_NEW_COPY_ON_WRITE (afaics just renamed), USE_64_BIT_ALL USE_64_BIT_INT (64bit is used when available by default)

**Comment by pullmoll** [comment]
- [ ] gtk-doc-1.20_2 `Experimental pop on scalar is now forbidden at /usr/bin/gtkdoc-mkdb line 4743, near "};"` when e.g. building cinnamon.
