### ISSUE TITLE
Package request: python-axolotl

### ISSUE THREAD

**Issue by teldra** [voidlinux/void-packages#4694]
There are a couple of dependencies. Possibly incl. protobuf.

Multidevice End-to-End encryption for Gajim via its OMEMO Plugin.

https://github.com/tgalal/python-axolotl
https://github.com/tgalal/python-axolotl-curve25519

**Comment by teldra** [comment]
https://github.com/teldra/void-packages/tree/python-axolotl
https://github.com/teldra/void-packages/tree/python-axolotl
https://github.com/teldra/void-packages/tree/python-protobuf

i think, this package needs a version bump to protobuf-3.0.0 
would that be possible? @xtraeme

**Comment by Vaelatern** [comment]
Why do you think that is the requirement?

**Comment by teldra** [comment]
nope, my mistake, sry, 
it just needs protobuf >=2.6 and everythings seems fine.
ohne dependency needs a release. i asked upstream dev.

**Comment by ebfe** [comment]
b91826ae453da82aab4f16ef08fe0576ba98aac2
