### ISSUE TITLE
oracle-jdk package is FUBAR

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/void-packages#4704]
When last updating the oracle-jdk package, a symlink is created pointing to v1.8.0_101, however, the latest package is v1.8.0_91. Also, older jdk packages are not removed during install.

Removing the package and reinstalling results in the sha256sum checksum failing, meaning I can't reinstall it, either.

**Comment by antonio-malcolm** [comment]
OK, it also looks like removing the package removes only the contents of `bin` and `jre', under each jdk version directory.

This package has always had issues. Do you guys want a new maintainer for this package? I work with Java fairly extensively.

**Comment by chneukirchen** [comment]
If you want to maintain openjdk instead, gladly take it please. ;)

**Comment by antonio-malcolm** [comment]
This is for oracle-jdk.

**Comment by antonio-malcolm** [comment]
(I don't use openjdk, because we use oracle-jdk at the day job, and while I'm building an open-sourced app framework, and can use whichever of the two I want, I have NO idea how anyone else will use the framework, so I just stick with oracle, for now... though I'd GREATLY prefer using the open-sourced option.)

**Comment by antonio-malcolm** [comment]
Ok, looking at the template file, I wonder if there's not _too much_ being done to install this package.
To circumvent this, I manually installed, by adding Oracle's JDK package to `/usr/local/lib`, setting the `$JAVA_HOME` environment variable, and adding that to the `$PATH` variable, then calling it a day. That works, with absolutely no issues. I can understand, maybe there's a bit more to be done than that, for the Void package, but I _know_ it's not as complicated as you're currently making it.

**Comment by pullmoll** [comment]
Hmm.. the `srcpkgs/openjdk/template` function `do_build()` couldn't be much simpler.
What do yo mean by doing *too much*?
A lot of the template is taking care of xbps-alternatives, there are patches for gcc-4.9.x and linux4.1 and some more, but nothing seems too much to me. Not that I am in any way java affine, though.
