### ISSUE TITLE
Broadcom-wl-dkms fails to install the DKMS module under Linux kernel 4.7.2.

### ISSUE THREAD

**Issue by Pizza-Boy** [voidlinux/void-packages#4708]
Installing and using `linux4.6` and `linux4.6-headers` fixes the issue.

I suspect that the headers for 4.7.2 might be out of date but I don't really know enough about this stuff to be sure.

**Comment by cavalier911** [comment]
Add[ linux47.patch](https://git.io/vi4Wa) from manjaro to broadcom-wl-dkms/patches 
Rebuild/install package on x86_64 glibc system: 
 `broadcom-wl-dkms-6.30.223.271_3: configuring ...`
` DKMS module 'wl-6.30.223.271' already added, skippng.`
 `Skipping kernel-4.7.1_2. kernel-headers package not installed...`
 `Building DKMS module 'wl-6.30.223.271' for kernel-4.7.2_1... done.`
 `Installing DKMS module 'wl-6.30.223.271' for kernel-4.7.2_1... done.`
 `Regenerating initramfs, please wait...`
 `dracut: dracut module 'cifs' depends on 'network', which can't be installed`
 `broadcom-wl-dkms-6.30.223.271_3: installed successfully.`

**Comment by Vaelatern** [comment]
25ff298
