### ISSUE TITLE
OpenShot - missing 'select' and 'razor' modes in edit toolbar

### ISSUE THREAD

**Issue by tom-i** [voidlinux/void-packages#4709]
I wanted to try OpenShot, but I can't find 'Select' and 'Razor' modes in edit toolbar. 
You can see it in this wiki page:
http://www.openshotusers.com/help/1.3/en/ar01s04.html#sect2_15

Actual situation in mine OpenShot looks:
![openshot_misstools](https://cloud.githubusercontent.com/assets/16342114/18232847/c25a9d44-72d8-11e6-8f86-713218f5bd69.png)

**Comment by ebfe** [comment]
Outdated manual?

**Comment by tom-i** [comment]
Yes, that razor mode is now in context menu, when you right-click on "blue slide" in timeline some menu about splitting appears. So you can separate to 2 parts, or keep left or right one.

So close issue.
