### ISSUE TITLE
LLVM: fix dynamic linking

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4722]
In b7b6c837ae079d340fb02e6e59719e1f2f3e6e7d I had to turn of dynamic linking of LLVM tools which bloated up the package.

Find a way to reverse this setting without breaking stuff.

**Comment by chneukirchen** [comment]
Upstream bug: https://llvm.org/bugs/show_bug.cgi?id=22952

**Comment by chneukirchen** [comment]
One approach is to use BUILD_SHARED_LIBS=ON, which will build 118 .so libraries, but with bind_now this makes launching a lot slower...

**Comment by pullmoll** [comment]
Then stripping ` -Wl,-z,now` from LDFLAGS for llvm would be sufficient? Loading libraries as required instead of always (monolithic) everything maybe has its own pros.

**Comment by chneukirchen** [comment]
I think it will be slower, but making an exclusion to bind_now here may be an option indeed.

I'm not so fond of versioning all these libs tho... but we could try it.

**Comment by pullmoll** [comment]
I'll give it a try locally.
