### ISSUE TITLE
puppet: broken dependencies

### ISSUE THREAD

**Issue by nonchip** [voidlinux/void-packages#4729]
```
    # xbps-install puppet
    MISSING: ruby>=2.2<2.3
    Transaction aborted due to unresolved dependencies.
```

```
    # xbps-query -Rs ruby
    [-] ruby-2.3.1_1           Ruby programming language
    [-] ruby-devel-2.3.1_1     Ruby programming language - development files
```

**Comment by pullmoll** [comment]
So `srcpkgs/puppy/template` needs to be updated, iff puppet works with ruby-2.3.1 as well. Otherwise we'd need to create e.g. legacy `ruby2.2` and `ruby2.2-devel` packages to make puppet happy.

**Comment by pullmoll** [comment]
I did an update to `puppet-4.6.2` now using facter-3.4.1` with new dependencies on `cpp-hocon-0.1.2` and `leatherman-0.9.0`. Can you give `puppet-4.6.2_1` a try and tell if it works for you?

**Comment by nonchip** [comment]
works
