### ISSUE TITLE
Firefox opens __notepad.exe__ as default editor for `.yml` files.

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#4732]
I noticed that Firefox's default behaviour when opening files has improved with teh last update, like opening Vim for text files and stuff, without requiring manual tweaking. However, it also came to my attention that it will open __notepad.exe__ (via wine) to view/edit `.yml`files.

Is this behaviour expected? Feels like creepy pasta.

```
[rogi@SkyLittleSystem ~]$ xbps-query -s firefox
[*] firefox-48.0.2_1 Lightweight gecko-based web browser
```

Also: Another day (yesterday?) I stumbled into some native program opening __Internet Explorer__ to view a (`.gif`?) file. IE popped up without errors, but showing nothing more than a blank page.

**Comment by chneukirchen** [comment]
http://askubuntu.com/questions/323437/how-to-prevent-wine-from-adding-file-associations/400430#400430

**Comment by ayghor** [comment]
Sorry I didn't even google about, I need to sleep.
