### ISSUE TITLE
libreoffice conflicts with libreoffice-i18n-de

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4734]
both contain (incomplete list):

	/usr/lib/libreoffice/share/config/soffice.cfg/dbaccess/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/sfx/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/uui/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/filter/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/xmlsec/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/svt/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/fps/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/formula/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/svx/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/vcl/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/desktop/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/cui/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/dbreport/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/scanner/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/smath/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/spropctrlr/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/swriter/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/BasicIDE/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/sbibliography/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/sabpilot/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/sdraw/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/schart/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/scalc/ui/res/de.zip
	/usr/lib/libreoffice/share/config/soffice.cfg/modules/simpress/ui/res/de.zip
	...

cc @pullmoll

**Comment by ebfe** [comment]
I guess this is due to libreoffice being configured with `--with-lang='en-US de es fr it pl pt'`. So we can remove the matching libreoffice-i18n-XX packages?

**Comment by Duncaen** [comment]
https://github.com/voidlinux/void-packages/issues/4183

**Comment by pullmoll** [comment]
I'll take care. I think adding a blacklist to libreoffice-i18-n is easier than removing entries, because the list of default languages may change over time.

**Comment by pullmoll** [comment]
Jeez.. the lack of coffee on my pare is obvious.

**Comment by ebfe** [comment]
Thanks. The conflicting packages are still installable right now (though a revision behind). Not sure how/who can remove the old packages from the repo.

**Comment by pullmoll** [comment]
Next libreoffice is coming now, including new i18n.
