### ISSUE TITLE
WIP: building Void with gcc-6.2.0

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4748]
I managed to bootstrap gcc-6.2.0 for x86_64 and [here is how](http://misc.voidlinux.de/gcc-6.2.0-bootstrap.txt).
The shell code is not tested but merely a hint what to do. :cactus: 
Note that gcc-go seems to be broken and is disabled.

#### Build logs:
 + [bootstrap.log](http://misc.voidlinux.de/bootstrap.log)
 + [base-system.log](http://misc.voidlinux.de/base-system.log)
 + [gcc.log](http://misc.voidlinux.de/gcc.log) (gcc additional languages)
 + [xorg-minimal.log](http://misc.voidlinux.de/xorg-minimal.log) (contains some unrelated pkgs)
 + [xorg.log](http://misc.voidlinux.de/xorg.log)
 + [lxde.log](http://misc.voidlinux.de/lxde.log)
 + [mklive.log](http://misc.voidlinux.de/mklive.log) (pkgs required to run mklive.sh)
 + [cinnamon.log](http://misc.voidlinux.de/cinnamon.log)

**Comment by pullmoll** [comment]
Successfully built packages are updated every now and then at http://repo.voidlinux.de/current
Live ISOs for testing are updated every now and then at http://repo.voidlinux.de/live

**Comment by pullmoll** [comment]
Next failing package is `qt` (Qt4), `3rdparty/javascriptcore`

```
../3rdparty/javascriptcore/JavaScriptCore/wtf/HashTable.h:264:83: error: 'template<class T, class U> void QT
WTF::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)' conflicts with a previous declaration
     template<typename T, typename U> inline void swap(pair<T, U>& a, pair<T, U>& b)
…
/usr/include/c++/6.2/bits/stl_pair.h:403:5: note: previous declaration 'template<class _T1, class _T2> void
std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&)'
     swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
     ^~~~
```

**Comment by pullmoll** [comment]
Idea: Perhaps we can keep `gcc-4.9.4` as `gcc4` and use it for pkgs like `qt`. With the gcc option `--with-default-libstdcxx-abi=gcc4-compatible` for `gcc6` this may work out.

**Comment by pullmoll** [comment]
It seems that a lot of patches for musl made it into `gcc-6.2.0` and so I stripped everything that failed from `gcc-5.4.0-musl.diff` for a the resulting `gcc-6.2.0-musl.diff` which looks like this:

```diff
# HG changeset patch
# Parent 90a7a3809a7ccb60e357b5e88382260877f82257
Use the generic implementation of libstdc++ primitives when we're on musl, not the glibc one.

diff -r 90a7a3809a7c libstdc++-v3/configure.host
--- a/libstdc++-v3/configure.host	Thu Dec 24 11:22:15 2015 -0500
+++ b/libstdc++-v3/configure.host	Thu Dec 24 11:24:45 2015 -0500
@@ -266,6 +266,13 @@
     os_include_dir="os/bsd/freebsd"
     ;;
   gnu* | linux* | kfreebsd*-gnu | knetbsd*-gnu)
+    # check for musl by target
+    case "${host_os}" in
+      *-musl*)
+        os_include_dir="os/generic"
+        ;;
+      *)
+
     if [ "$uclibc" = "yes" ]; then
       os_include_dir="os/uclibc"
     elif [ "$bionic" = "yes" ]; then
@@ -281,6 +281,9 @@
       os_include_dir="os/gnu-linux"
     fi
     ;;
+
+    esac
+    ;;
   hpux*)
     os_include_dir="os/hpux"
     ;;
diff -r 30a957f60ddb gcc/ginclude/stddef.h
--- a/gcc/ginclude/stddef.h	Thu Dec 24 11:24:45 2015 -0500
+++ b/gcc/ginclude/stddef.h	Thu Dec 24 11:24:47 2015 -0500
@@ -184,6 +184,7 @@
 #ifndef _GCC_SIZE_T
 #ifndef _SIZET_
 #ifndef __size_t
+#ifndef __DEFINED_size_t /* musl */
 #define __size_t__	/* BeOS */
 #define __SIZE_T__	/* Cray Unicos/Mk */
 #define _SIZE_T
@@ -200,6 +201,7 @@
 #define ___int_size_t_h
 #define _GCC_SIZE_T
 #define _SIZET_
+#define __DEFINED_size_t /* musl */
 #if (defined (__FreeBSD__) && (__FreeBSD__ >= 5)) \
   || defined(__DragonFly__) \
   || defined(__FreeBSD_kernel__)
@@ -218,6 +220,7 @@
 typedef long ssize_t;
 #endif /* __BEOS__ */
 #endif /* !(defined (__GNUG__) && defined (size_t)) */
+#endif /* __DEFINED_size_t */
 #endif /* __size_t */
 #endif /* _SIZET_ */
 #endif /* _GCC_SIZE_T */
# HG changeset patch
# Parent 90228af47e55eb338c7f672e4aca5ac81cf5f14c
A fix for libgomp to correctly request a POSIX version for time support.

diff -r 90228af47e55 libgomp/config/posix/time.c
--- a/libgomp/config/posix/time.c	Thu Dec 24 11:24:47 2015 -0500
+++ b/libgomp/config/posix/time.c	Thu Dec 24 11:24:49 2015 -0500
@@ -29,6 +29,8 @@
    The following implementation uses the most simple POSIX routines.
    If present, POSIX 4 clocks should be used instead.  */
 
+#define _POSIX_C_SOURCE 199309L /* for clocks */
+
 #include "libgomp.h"
 #include <unistd.h>
 #if TIME_WITH_SYS_TIME
diff -r b08d4bc3d2ba libgcc/unwind-dw2-fde-dip.c
--- a/libgcc/unwind-dw2-fde-dip.c	Thu Dec 24 11:24:49 2015 -0500
+++ b/libgcc/unwind-dw2-fde-dip.c	Thu Dec 24 11:24:51 2015 -0500
@@ -46,6 +46,10 @@
 #include "unwind-compat.h"
 #include "gthr.h"
 
+#if !defined(inhibit_libc) && defined(HAVE_LD_EH_FRAME_HDR) && defined(TARGET_DL_ITERATE_PHDR)
+# define USE_PT_GNU_EH_FRAME
+#endif
+
 #if !defined(inhibit_libc) && defined(HAVE_LD_EH_FRAME_HDR) \
     && (__GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 2) \
 	|| (__GLIBC__ == 2 && __GLIBC_MINOR__ == 2 && defined(DT_CONFIG)))
diff -r 1f375ed3689f gcc/gcc.c
--- a/gcc/gcc.c	Thu Dec 24 11:24:53 2015 -0500
+++ b/gcc/gcc.c	Thu Dec 24 11:24:56 2015 -0500
@@ -860,7 +860,7 @@
 #ifndef LINK_SSP_SPEC
 #ifdef TARGET_LIBC_PROVIDES_SSP
 #define LINK_SSP_SPEC "%{fstack-protector|fstack-protector-all" \
-		       "|fstack-protector-strong|fstack-protector-explicit:}"
+		       "|fstack-protector-strong|fstack-protector-explicit:-lssp_nonshared}"
 #else
 #define LINK_SSP_SPEC "%{fstack-protector|fstack-protector-all" \
 		       "|fstack-protector-strong|fstack-protector-explicit" \
# HG changeset patch
# Parent 76b553fabcf19eec5df2df7f05ce15a4bf8c3996
Support for mips-linux-musl.

diff -r 76b553fabcf1 gcc/config/mips/linux.h
--- a/gcc/config/mips/linux.h	Thu Dec 24 11:25:02 2015 -0500
+++ b/gcc/config/mips/linux.h	Thu Dec 24 11:25:04 2015 -0500
@@ -31,6 +31,13 @@
 #undef UCLIBC_DYNAMIC_LINKER32
 #define UCLIBC_DYNAMIC_LINKER32 \
   "%{mnan=2008:/lib/ld-uClibc-mipsn8.so.0;:/lib/ld-uClibc.so.0}"
+
+#undef MUSL_DYNAMIC_LINKER32
+#define MUSL_DYNAMIC_LINKER32 "/lib/ld-musl-mips%{EL:el}%{msoft-float:-sf}.so.1"
+#undef MUSL_DYNAMIC_LINKER64
+#define MUSL_DYNAMIC_LINKER64 "/lib/ld-musl-mips64%{EL:el}%{msoft-float:-sf}.so.1"
+#define MUSL_DYNAMIC_LINKERN32 "/lib/ld-musl-mipsn32%{EL:el}%{msoft-float:-sf}.so.1"
+
 #undef UCLIBC_DYNAMIC_LINKER64
 #define UCLIBC_DYNAMIC_LINKER64 \
   "%{mnan=2008:/lib/ld64-uClibc-mipsn8.so.0;:/lib/ld64-uClibc.so.0}"
# HG changeset patch
# Parent 971d410411735f0b04eb07236659097986926213
Support for powerpc-linux-musl.

diff -r 971d41041173 gcc/config.gcc
--- a/gcc/config.gcc	Fri Dec 25 08:44:09 2015 -0500
+++ b/gcc/config.gcc	Fri Dec 25 09:42:16 2015 -0500
@@ -2464,6 +2464,10 @@
 	    powerpc*-*-linux*paired*)
 		tm_file="${tm_file} rs6000/750cl.h" ;;
 	esac
+        case ${target} in
+            *-linux*-musl*)
+                enable_secureplt=yes ;;
+        esac
 	if test x${enable_secureplt} = xyes; then
 		tm_file="rs6000/secureplt.h ${tm_file}"
 	fi
diff -r 9555ffb5873b gcc/config/aarch64/aarch64-linux.h
--- a/gcc/config/aarch64/aarch64-linux.h	Thu Dec 24 11:25:06 2015 -0500
+++ b/gcc/config/aarch64/aarch64-linux.h	Thu Dec 24 11:25:09 2015 -0500
@@ -32,6 +32,8 @@
 #undef  CC1_SPEC
 #define CC1_SPEC GNU_USER_TARGET_CC1_SPEC ASAN_CC1_SPEC
 
+#define MUSL_DYNAMIC_LINKER "/lib/ld-musl-aarch64.so.1"
+
 #define CPP_SPEC "%{pthread:-D_REENTRANT}"
 
 #define LINUX_TARGET_LINK_SPEC  "%{h*}		\
diff -r a522e4b04c77 gcc/config/microblaze/microblaze.h
--- a/gcc/config/microblaze/microblaze.h	Thu Dec 24 11:25:11 2015 -0500
+++ b/gcc/config/microblaze/microblaze.h	Thu Dec 24 11:25:13 2015 -0500
@@ -218,6 +218,12 @@
 #undef PTRDIFF_TYPE
 #define PTRDIFF_TYPE "int"
 
+#undef SIZE_TYPE
+#define SIZE_TYPE "unsigned int"
+
+#undef PTRDIFF_TYPE
+#define PTRDIFF_TYPE "int"
+
 #define CONSTANT_ALIGNMENT(EXP, ALIGN)					\
   ((TREE_CODE (EXP) == STRING_CST  || TREE_CODE (EXP) == CONSTRUCTOR)	\
    && (ALIGN) < BITS_PER_WORD						\
diff -r f2936ad874dd gcc/config/sh/linux.h
--- a/gcc/config/sh/linux.h	Fri Sep 28 16:32:03 2012 +1000
+++ b/gcc/config/sh/linux.h	Thu Dec 24 11:25:15 2015 -0500
@@ -64,7 +64,14 @@
 
 #define TARGET_ASM_FILE_END file_end_indicate_exec_stack
 
+#if TARGET_BIG_ENDIAN_DEFAULT /* BE */
+#define MUSL_DYNAMIC_LINKER_E "eb"
+#else
+#define MUSL_DYNAMIC_LINKER_E
+#endif
+
 #define GLIBC_DYNAMIC_LINKER "/lib/ld-linux.so.2"
+#define MUSL_DYNAMIC_LINKER "/lib/ld-musl-sh" MUSL_DYNAMIC_LINKER_E ".so.1"
 
 #undef SUBTARGET_LINK_EMUL_SUFFIX
 #define SUBTARGET_LINK_EMUL_SUFFIX "_linux"
Do not use weak references on any targets for gthread. Necessary on musl, safe elsewhere.

diff -r e180e4cfc879 libgcc/gthr.h
--- a/libgcc/gthr.h	Thu Dec 24 11:25:15 2015 -0500
+++ b/libgcc/gthr.h	Thu Dec 24 11:25:17 2015 -0500
@@ -136,10 +136,8 @@
 /* The pe-coff weak support isn't fully compatible to ELF's weak.
    For static libraries it might would work, but as we need to deal
    with shared versions too, we disable it for mingw-targets.  */
-#ifdef __MINGW32__
 #undef GTHREAD_USE_WEAK
 #define GTHREAD_USE_WEAK 0
-#endif
 
 #ifndef GTHREAD_USE_WEAK
 #define GTHREAD_USE_WEAK 1
```

This makes `cross-*musl*` pkgs compile, but this stripped down patch is not yet validated. Need to double check, if all stripped parts are really included in the gcc-6.2.0 files that were to be patched, or if I stripped too much.

**Comment by pullmoll** [comment]
I can't get `cross-i686-pc-linux-gnu` to build. After the compiler bootstrap (building `xgcc`), the configure tests tell me this:
```
Configuring in i686-pc-linux-gnu/libmpx
configure: creating cache ./config.cache
checking for --enable-version-specific-runtime-libs... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for target support for Intel MPX runtime library... yes
checking for a BSD-compatible install... /builddir/.xbps-cross-i686-pc-linux-gnu/wrappers/install -c
checking whether build environment is sane... yes
checking for i686-pc-linux-gnu-strip... /usr/i686-pc-linux-gnu/bin/strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for i686-pc-linux-gnu-gcc... /builddir/cross-i686-pc-linux-gnu-0.21/gcc-bootstrap/./gcc/xgcc -B/builddir/cross-i686-pc-linux-gnu-0.21/gcc-bootstrap/./gcc/ -B/usr/i686-pc-linux-gnu/bin/ -B/usr/i686-pc-linux-gnu/lib/ -isystem /usr/i686-pc-linux-gnu/include -isystem /usr/i686-pc-linux-gnu/sys-include   
checking for C compiler default output file name... 
configure: error: in `/builddir/cross-i686-pc-linux-gnu-0.21/gcc-bootstrap/i686-pc-linux-gnu/libmpx':
configure: error: C compiler cannot create executables
See `config.log' for more details.
make[1]: *** [Makefile:10452: configure-target-libmpx] Error 1
make[1]: Leaving directory '/builddir/cross-i686-pc-linux-gnu-0.21/gcc-bootstrap'
make: *** [Makefile:860: all] Error 2
=> ERROR: cross-i686-pc-linux-gnu-0.21_4: failed to run do_build() at line 96.
```

This is of course a show stopper, because without this I can't build gcc-multilib.

Anyone got an idea what to do?

**Comment by pullmoll** [comment]
I now successfully created `gcc-6.2.0_1.i686.xbps` etc. using the separate masterdir approach:
```
./xbps-src -m masterdir-x86 binary-bootstrap
./xbps-src -m masterdir-x86 pkg gcc
```
and had set the `XBPS_HOSTDIR` to where the x86_64 pkgs are collected.
Now I should be able to build `gcc-multilib`.. I hope :smile:

**Comment by pullmoll** [comment]
Next step: `gcc-multilib` fails to build when trying to build the `ppl_lcdd` program. Since this is is under `demos/ppl_lcdd` I'll try to disable building the demos to see what happens next.

**Comment by pullmoll** [comment]
Fixed packages `pkg-config` and `xbps` which failed in `./xbps-src bootstrap` inside a gcc6 environment. These bugs occured in a `./xbps-src bootstrap` I tried inside a qemu image installed from a live ISO.

**Comment by pullmoll** [comment]
Now more than 5190 of about 6750 packages are built.
I think that by tomorrow afternoon I can post a list of pkgs which need fixes.

A show stopper is e.g. firebird (a libreoffice dependency), which I got to compile with an updated version, while it fails to run some test after the successful build :(

And of course firefox-esr, firefox and icecat.

**Comment by pullmoll** [comment]
**FYI** After the trouble with qtwebkit that ships with `qt-4.8.7` above, I'm now working on separating `qt-webkit` from `qt` by creating a new `qt-webkit-2.3.4` package.

The idea and the patches are taken from the Arch Linux team's pkg [qtwebkit](https://www.archlinux.org/packages/extra/x86_64/qtwebkit/)
For consistency with qt5 the pkgname for Void will be `qt-webkit`.

This new `qt-webkit-2.3.4` now builds with both, gcc4 and gcc6 and so the packages depending on `libQtWebKit.so.4` can be revbumped and built with a new makedepends `qt-webkit-devel`. Then we should be set to build all the kde4 stuff with gcc6, perhaps after some more fixing.

**Comment by pullmoll** [comment]
**Update:** kde4 built with gcc6. Uploading live images now.

**Comment by pullmoll** [comment]
Current status:

arch | pkgs built
--------|--------
x86_64 | 6538
i686 | 6157

**Comment by chneukirchen** [comment]
Do you have a list of things missing?

**Comment by chneukirchen** [comment]
Arch has gcc-go 6.2.1, what's wrong with yours?

**Comment by pullmoll** [comment]
I don't have a current list of things missing. I try to build all pkgs and add fixes when I see them failing.
I can run a build of the remaining things with logging and upload that log.

The build of gcc-go in the bootstrap failed due to (as it seems) syntax errors in the go sources.

I could try to use gcc-6.2.1 instead of 6.2.0 to see if that fixes it.

**Comment by pullmoll** [comment]
The first failing packages (building from z to a)

- [ ] xmlrpc-c `x86_64-unknown-linux-gnu-ar: Command not found`
- [ ] xen `core/stringextra.c:189:18: error: nonnull argument 's' compared to NULL [-Werror=nonnull-compare]`<br/>
    `sbegin  = s ? s : ___strtok;`
- [ ] xcruiser `undefined reference to `XtWidgetToApplicationContext'` and lots more of this kind
- [ ] xautolock `src/engine.c:214:17: error: storage size of 'status' isn't known`<br/>
    `union wait  status;      /* childs process status */`
- [ ] xar `lib/ext2.c:142:17: error: 'EXT2_ECOMPR_FL' undeclared (first use in this function)`
- [ ] wvstreams `streams/wvstream.cc:910:22: error: cannot convert 'IWvStreamCallback {aka std::tr1::function<void()>}' to 'bool' in assignment`<br/>
    `si.wants.readable = readcb;`
- [ ] winusb `/usr/bin/ld: MainPanel.o: relocation R_X86_64_32S against symbol `_ZTV9MainPanel' can not be used when making a shared object; recompile with -fPIC`
- [ ] vinagre `vinagre/vinagre-bookmarks-ui.c:331:12: error: format not a string literal, argument types not checked [-Werror=format-nonliteral]`
- [ ] grilo-plugins `-Werror=format-nonliteral`

**Comment by chneukirchen** [comment]
Yes, I think gcc 6.2.1 contains important fixes.

**Comment by pullmoll** [comment]
Well, then it's time to zap everything and start over :)

**Comment by pullmoll** [comment]
In http://ftp.gnu.org/gnu/gcc/ there is no gcc-6.2.1 yet.

**Comment by chneukirchen** [comment]
Overview of changes: https://gcc.gnu.org/git/?p=gcc.git;a=shortlog;h=c2103c17

Not sure why they do it...

**Comment by pullmoll** [comment]
The patched repository I'm using is now at https://github.com/pullmoll/void-packages-gcc6.2.1

The x86_64 bootstrap worked ok and now building `base-system` etc.

**Comment by pullmoll** [comment]
Starting over with gcc-6.2.1
