### ISSUE TITLE
ffmpeg - package out of date: 2.8.7 < 3.1.3

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#4755]
https://ffmpeg.org/download.html#releases

> # FFmpeg 3.1.3 "Laplace"
>
> 3.1.3 was released on 2016-08-26. It is the latest stable FFmpeg release from the 3.1 release branch, which was cut from master on 2016-06-26.
> 
> It includes the following library versions:
> 
>       libavutil      55. 28.100
>       libavcodec     57. 48.101
>       libavformat    57. 41.100
>       libavdevice    57.  0.101
>       libavfilter     6. 47.100
>       libavresample   3.  0.  0
>       libswscale      4.  1.100
>       libswresample   2.  1.100
>       libpostproc    54.  0.100

**Comment by Vaelatern** [comment]
#3788

**Comment by Vaelatern** [comment]
vlc refuses to release a 3.0 compatible release, it's still in beta. Since upgrading ffmpeg would break vlc, we have not yet upgraded. See the age of my PR.

**Comment by sunaku** [comment]
Thanks, that makes more sense: it's unlike Void to lag behind the edge of technology like this. :relieved: 

I reported this issue because searching for "ffmpeg" under issues turned up nothing relevant :sweat: but I now realize that I should have _also_ searched PRs to find yours #3788. :disappointed:  Sorry for the noise.

**Comment by Vaelatern** [comment]
This issue is to remain open until we either package the newest vlc or keep ffmpeg2 around as a dedicated package

**Comment by ebfe** [comment]
Since the vlc  build system has support for downloading and linking against it's own copy of ffmpeg, why don't we use just that?

**Comment by chneukirchen** [comment]
IMO vendoring would be ok in this case, to not hold the rest of the system back.

**Comment by pullmoll** [comment]
Perhaps the BLFS patches can help fix the issue?
See http://www.linuxfromscratch.org/blfs/view/svn/multimedia/vlc.html
and specifically http://www.linuxfromscratch.org/patches/blfs/svn/vlc-2.2.4-ffmpeg3-1.patch

I'm currently fighting with the other patch to enable gcc6 to build vlc.

**Comment by chneukirchen** [comment]
If that works, it looks very noninvasive, just a renaming.

**Comment by pullmoll** [comment]
Yup, it's not that much what is changed.
The gcc6 patch is much more invasive.

**Comment by asergi** [comment]
#3788
