### ISSUE TITLE
$pkgname.googlecode.com dowload locations failing

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4762]
It looks like code.google.com is removing archives.
The list of packages which (may) need `distfiles` updates:
- [ ] blazeblogger
- [x] bmkdep
- [x] chroot-distcc
- [ ] clamz
- [x] distcc
- [ ] dnsmap
- [x] fbterm
- [ ] gmock
- [ ] gmtk
- [ ] gnome-colors-icon-theme
- [ ] gnome-mplayer
- [ ] gperftools
- [x] gtest
- [x] gtkdialog
- [ ] ibus
- [ ] key-mon
- [x] libmp4v2
- [ ] libpam-google-authenticator
- [x] libproxy
- [ ] librlog
- [ ] lua-luadbi
- [ ] m2m-aligner
- [ ] mitlm
- [ ] mongoose
- [x] mp3check
- [x] pingus
- [ ] radamsa
- [ ] serf
- [ ] touchegg
- [ ] wmii
- [x] wvdial
- [ ] wvstreams
- [x] xar

**Comment by jcjordyn130** [comment]
True
