### ISSUE TITLE
gnubg: build broken

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4783]
x86_64{,-musl}

    ...
    checking whether python headers are sufficient... yes                                                            
    checking for x86 cpuid  output... unknown                                                                        
    checking for x86-AVX xgetbv  output... unknown                                                                   
    checking for x86 cpuid 0x00000001 output... unknown                                                              
    checking whether mmx is supported... ./configure: line 15967: 0xunknown: 
     value too great for base (error token is "0xunknown")                                                                                                    
    => ERROR: gnubg-1.05.000_2: failed to run do_configure() at line 7.

**Comment by chneukirchen** [comment]
Terrible crap in autoconf... I'll dig into it.
