### ISSUE TITLE
dracut-network depends on dhclient

### ISSUE THREAD

**Issue by tastytea** [voidlinux/void-packages#4792]
`dracut: dracut module 'network' will not be installed, because command 'dhclient' could not be found!`

Please add dhclient to dracut-network dependencies

**Comment by Vaelatern** [comment]
Steps to reproduce?

**Comment by tastytea** [comment]
- install dracut-network
 - install module which needs dracut-network (https://github.com/dracut-crypt-ssh/dracut-crypt-ssh in my case)
 - run dracut --force

**Comment by Duncaen** [comment]
or just add network the the modules and see this error appearing, valid issue that came up in voidlinux/void-mklive too.
https://github.com/voidlinux/void-mklive/pull/68#r61679570
