### ISSUE TITLE
skype-32: can't find libQtWebKit.so.4 

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#4803]
@pullmoll 
I think the problem is related to 38bad673  
Forum report:
https://forum.voidlinux.eu/t/transaction-aborted-due-to-unresolved-shlibs-skype-solved/1097

**Comment by Gottox** [comment]
as a workaround install qt-webkit-32bit-2.3.4_1

**Comment by cavalier911** [comment]
Thanks for the reply.

**Comment by Gottox** [comment]
Should be fixed in upstream too.
