### ISSUE TITLE
Cutegram: symbol lookup error

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#4805]
xbps-install -S Cutegram
cutegram
cutegram: symbol lookup error: /usr/lib/libtelegramqml.so.1: undefined symbol: _ZTV14GeoChatMessage

**Comment by pullmoll** [comment]
@Duncaen nostrip=yes for TelegramQML perhaps?

**Comment by pullmoll** [comment]
I reverted `libqtelegram-ae` to version 6.1, because obviously 10.0.0 does not work with the version of Cutegram we have.

You may have to force install it, i.e. `xbps-install -S -f libqtelegram-ae`

**Comment by silvernode** [comment]
Just getting the word out there that there was a problem. No big hassle here! Thanks for fixing it so quickly.
