### ISSUE TITLE
thunderbird: unresolvable shlib

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#4808]
thunderbird-45.3.0_2: broken, unresolvable shlib `libhunspell-1.3.so.0'

**Comment by Vaelatern** [comment]
Thunderbird is being updated as we speak to resolve this. please see https://build.voidlinux.eu/waterfall

**Comment by ebfe** [comment]
Rebuilds are finished for all archs. Feel free to reopen if you still see this issue.
