### ISSUE TITLE
CouchDB 2.0 now uses hard-coded Erlang path

### ISSUE THREAD

**Issue by jannisch** [voidlinux/void-packages#4809]
I just tried to update CouchDB to the 2.0 release but they changed a _lot_ so I thought it might be useful to open a public issue here. Hopefully @arete also joins the conversation.

The [release notes](http://docs.couchdb.org/en/latest/whatsnew/2.0.html) already announce a _New streamlined build system written for Unix-like systems and Microsoft Windows._

You can find my try to update the template [here](https://github.com/jannisch/void-packages/commit/3d9e0dd7cf71b9799be64fe96ef8045b978a3cb1). It successfully builds CouchDB 2.0.0, but into the default `rel/couchdb/` directory which also ships a whole erlang installation. The problem is that the `couchdb` binary uses a hard-coded path to this installation, which the folks over at #couchdb irc confirmed:

> 19:33 < jannis> Hello, I currently try to package CouchDB 2.0 for Void Linux but I can't find a way to set the path of my Erlang installation (I don't want to ship the one in rel/), do you know how to do this? Thanks!
> 19:34 <+Wohali> jannis: Right now we don't support running couchdb against the system-installed Erlang. Patches welcome.
> 19:40 < jannis> Wohali: ok thanks. So you removed the "--with-erlang=" argument, right? I just wonder because this was used in the 1.6.1 package template
> 19:49 <+Wohali> jannis: most of the conifgure options are removed.

Looking forward to your thoughts about this circumstance.

**Comment by pullmoll** [comment]
If the system `erlang-19.0` is ABI compatible with the one CouchDB 2.0 expects or ships, it should be possible to simply remove or ignore the `rel/…/erlang` libraries and binaries in the `do_install()` stage and instead create symbolic links to the system erlang.

Of course a clean fix would be to re-implement the `--with-erlang`, if anyone wants to do that.

**Comment by jannisch** [comment]
Unfortunately I don't know if it's ABI compatible but a symlink is a great idea. On the other hand the expected path is pretty strange when you launch it from `/usr/bin`:
```
~ % couchdb
cat: /usr/bin/../releases/start_erl.data: No such file or directory
/usr/bin/couchdb: 29: exec: /usr/bin/../erts-/bin/erlexec: not found
```
 So a symlink would be required in _/usr_ I guess and also this `start_erl.data` is annoying.

I try to have a look at their build system in the next few days.

**Comment by pullmoll** [comment]
Now `/usr/releases/start_erl.data` (path simplified) is certainly nothing for a symlink target.
It could perhaps be `/usr/lib/erlang/releases/start_erl.data` or something along that line.
And also `/usr/erts-/bin/erlexec` is definitely bad.
It should be possible to set some prefix to at least shift these target paths from `/usr` to e.g. `/usr/lib{,exec}/erlang` or `/usr/lib{,exec}/couchdb` or the like.
Good luck on trying to get that straight!

**Comment by jannisch** [comment]
Yes, I agree.
Thanks for the wishes, other volunteers are still welcome 😄

**Comment by arete** [comment]
This is archlinux. Solution
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/couchdb
I try to create pkg couchdb2.
In repo is usefuel have couchdb 1.6 and 2.0?

**Comment by jannisch** [comment]
I just discovered that `/usr/bin/couchdb` isn't actually a binary file so it can be patched easily, but this is not done in Arch at all for some reason.
@arete you can clone into my branch which I linked in the first post of this thread as a starting point. There is no need to support 1.6 since the 2.0 API is 99% backwards compatible (official statement)

**Comment by arete** [comment]
@jannisch  i have update the package pull request #4855

**Comment by jannisch** [comment]
Thanks, it seems to cause a lot of problems however.
* are you sure that `nopie` is required? I can't find anything about that in the Arch PKGBUILD.
* do you have an idea why musl and all ARM achitectures won't build?

**Comment by arete** [comment]
Hi,
i try to build with pie `CFLAGS="-fPIE -pie" make release` but not work.
The result binary couchjs not is pie.
I have talk on #couchdb irc channel, and rnewson suggest me to hack rebar.config.script
https://www.irccloud.com/pastebin/MdPUvDOs/
I have try to hack rebar.config.script, but without success.
 

> ``

**Comment by arete** [comment]
@jannisch if you can debug rebar build,
run this command `CFLAGS="-fPIE -pie" ./bin/rebar -v compile`

for cross build is need to set  to rebar REBAR_TARGET_ARCH

for now i try to cross build, PIE next run

**Comment by jannisch** [comment]
Thanks for the diff and the effort behind it. I could fix the problem and created a PR in your fork.

**Comment by jannisch** [comment]
With this code building at least successfully begins:
```  sh
if [ "$CROSS_BUILD" ]; then
	export REBAR_TARGET_ARCH=${XBPS_CROSS_TRIPLET}
fi
```

But it soon fails because of wrong include paths so the following is also necessary:
```
pre_build() {
  sed -i 's/jsapi/js\/jsapi/g' $(find src/couch/priv/couch_js -type f)
}
```

I first tried it with x86_64-musl which will then throw some other crazy errors, on armv7hf it even fails because of unrecognized compiler flags.
Maybe there is one major issue behind this but I'm a bit frustrated now.

**Comment by jannisch** [comment]
Did you have some time to continue with the cross build @arete? Maybe we could think about releasing the update for x86-glibc architectures, the build tool will also be improved in future releases.

**Comment by arete** [comment]
ok, i for now have push native build, nocross

**Comment by jannisch** [comment]
I guess you have to add a `only_for_archs="x86_64"` now.

**Comment by arete** [comment]
Hi i have update pull request.
regards
