### ISSUE TITLE
ffmpeg 3.0 fallout

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4816]
- [x] 2016-09-22 c3b7e9d hedgewars: mark broken.
- [x] 2016-09-22 c5871ec kodi: mark broken.
- [x] 2016-09-22 44639b5 k3b: mark broken.
- [x] 2016-09-22 bdae381 bomi: mark broken.
- [x] 2016-09-22 ef37982 dolphin-emu: mark broken.
- [x] 2016-09-22 fd19a83 libextractor: mark broken.
- [x] 2016-09-22 0fe6219 motion: mark broken.
- [x] 2016-09-22 c57bb62 guvcview: mark broken.
- [x] 2016-09-22 9ba9dfb freerdp: mark broken.
- [x] 2016-09-22 48dcf56 osg: mark broken.
- [x] 2016-09-22 8018650 mlt: mark broken.
- [x] 2016-09-22 80ff8fd xine-lib: mark broken.

**Comment by chneukirchen** [comment]
Many thanks to @pullmoll and @asergi for the fixes. :tada:

**Comment by pullmoll** [comment]
To avoid duplicate efforts: working on osg now.
