### ISSUE TITLE
qt5 on aarch64

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4817]
Not sure why it even builds qtwebengine, i think we moved that out? @pullmoll 

/builddir/qt-everywhere-opensource-src-5.6.1/qtwebengine/src/3rdparty/chromium/third_party/webrtc/base/bitbuffer.cc:1:0: error: unknown value 'x86-64' for -march

https://build.voidlinux.eu/builders/aarch64-musl_builder/builds/263/steps/shell_3/logs/stdio

**Comment by chneukirchen** [comment]
(I see, we moved webkit from qt 4...)

Still don't get why It builds on armv7 but not on aarch64. More investigation need.

**Comment by pullmoll** [comment]
Yeah, qtwebkit was removed from qt4, not qt5.

I think the problem is in this line:
```
Error: unrecognized option -march=x86-64
```
Shouldn't that be `-march=x86_64`?
I don't know where it comes from

**Comment by pullmoll** [comment]
I'll try a local cross build for aarch64 to see where this comes from or what causes it.
Actually cross compiling qt5 doesn't help too much, because packages are not prepared to use a cross-qt5 environment. See #4588

**Comment by pullmoll** [comment]
Now I built qt5 for `-a aarch64` on my box without error.

For musl it may be a case value of `aarch64-*-gnu` or similar where it doesn't detect the host triplet or sysroot as `aarch64`.

Next is trying to build for `-a aarch64-musl` here.

**Comment by pullmoll** [comment]
Hmm... not so good:
```
ERROR: musl-legacy-compat-0.3_1: the RSA signature is not valid!
```

**Comment by pullmoll** [comment]
Now built for musl as well. No errors.
I think the failing build on the aarch64 builders is for the **host** and fails because of some broken package(s). Perhaps all that is missing is a `repository=...` entry to let them fetch pkgs from the master repo?

**Comment by chneukirchen** [comment]
I didn't realize it needed a host build first. I'll do a manual host build (we also needed this for go for obscure reasons.)

**Comment by pullmoll** [comment]
Funny enough also the gcc-6.2.1 problems to build gccgo seem to originate from it using gcc-4.9.4's gccgo.
