### ISSUE TITLE
findutils updatedb gfind and find - high CPU usage on BTRFS

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#4829]
gfind uses up to 89% CPU for several minutes, switching my CPU fans to high speed.
It also slows down other desktop processes noticeably.
This is with BTRFS, I didn't see this amount of CPU use on EXT4.
It starts automatically as a dcron job or can be run manually via sudo updatedb.
From 'top'
```
Tasks: 177 total,   2 running, 175 sleeping,   0 stopped,   0 zombie
%Cpu(s): 52.3 us, 43.4 sy,  0.0 ni,  0.0 id,  3.9 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  1028592 total,    85028 free,   536084 used,   407480 buff/cache
KiB Swap:  1116956 total,   974472 free,   142484 used.   294652 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1294 root      20   0  142900 140772   2192 R 87.3 13.7   2:03.36 gfind
  663 root      20   0  158136  41912  15300 S  4.2  4.1   3:26.53 Xorg
    7 root      20   0       0      0      0 S  1.3  0.0   0:10.77 rcu_preempt
```
A similar problem was observed using the 'find' command searching Linux source, but the CPU usage isn't attributed to the find process or apparently any other process.
```
$ find . -type f -exec grep -nH " umount2" '{}' \;

Tasks: 162 total,   1 running, 161 sleeping,   0 stopped,   0 zombie
%Cpu(s): 72.6 us, 25.4 sy,  0.0 ni,  0.0 id,  2.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1028592 total,   355720 free,   131764 used,   541108 buff/cache
KiB Swap:  1116956 total,  1116956 free,        0 used.   737232 avail Mem
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  668 root      20   0  130636  46348  16308 S  3.9  4.5   0:16.92 Xorg
  926 zqqw     20   0    4788   2428   2060 S  3.3  0.2   0:08.88 find
    7 root      20   0       0      0      0 S  1.3  0.0   0:03.75 rcu_preempt
```
I don't think file compression features are enabled, I simply selected BTRFS at installation for my main partition.
/proc/mounts
/dev/sda2 / btrfs rw,relatime,space_cache,subvolid=5,subvol=/ 0 0
Boot time reduced from 53s on EXT4 to 45-46s on BTRFS though.

**Comment by zqqw** [comment]
I have the findutils and mlocate packages installed, but hadn't realised the overlap between the features and what was actually in operation.
findutils includes these files:
/etc/updatedb.conf
/etc/cron.daily/updatedb
/usr/bin/gfind
/usr/bin/glocate
/usr/bin/gupdatedb
/usr/bin/gxargs
/usr/share/man/man1/glocate.1
/usr/share/man/man1/gfind.1
/usr/share/man/man1/gxargs.1
/usr/share/man/man1/gupdatedb.1
/usr/share/man/man5/glocatedb.5

mlocate includes these:
/etc/cron.daily/mupdatedb
/usr/bin/mlocate
/usr/bin/mupdatedb
/usr/share/man/man1/mlocate.1
/usr/share/man/man1/mupdatedb.1
/usr/share/man/man5/mmlocate.db.5
/usr/share/man/man5/updatedb.conf.5

$ ls -l /usr/bin/locate
lrwxrwxrwx 1 root root 7 Mar 16  2016 /usr/bin/locate -> glocate
$ ls -l /usr/bin/mlocate
-rwxr-sr-x 1 root mlocate 38336 Dec  3  2015 /usr/bin/mlocate
$ ls -l /usr/bin/glocate
-rwxr-xr-x 1 root root 79540 Dec 30  2015 /usr/bin/glocate
$ ls -l /usr/bin/updatedb
lrwxrwxrwx 1 root root 9 Mar 16  2016 /usr/bin/updatedb -> gupdatedb
$ ls -l /usr/bin/gupdatedb
-rwxr-xr-x 1 root root 10464 Dec 30  2015 /usr/bin/gupdatedb
$ ls -l /usr/bin/mupdatedb
-rwxr-xr-x 1 root root 46532 Dec  3  2015 /usr/bin/mupdatedb

So when I ran updatedb and locate I was using gupdatedb and glocate from findutils, not mupdatedb and mlocate from the mlocate package.
man updatedb or man locate also shows the pages from findutils, as does man gupdatedb or man glocate.
For mlocate, the specific commands mupdatedb and mlocate, plus man mupdatedb and man mlocate need to be used. mupdatedb does use the same /etc/updatedb.conf file
but (I think) maintains a separate database.
The problems with find also relate to the findutils package, so this is the problem here it seems, not mlocate.

So there is a problem but it relates to findutils in combination with BTRFS, not mlocate.
Removing the /etc/cron.daily/updatedb file and using mlocate not locate provides a workaround to the locate issues for now.
The findutils cron file isn't as good as the mlocate one as it doesn't have nice and ionice set. 
Using gupdatedb with nice wouldn't block other processes although it still used all available CPU:
$ sudo nice --adjustment=19 ionice -c 2 -n 7 updatedb
Tasks: 170 total,   2 running, 168 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.3 us, 47.2 sy, 47.5 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1028592 total,   283040 free,   169496 used,   576056 buff/cache
KiB Swap:  1116956 total,  1116956 free,        0 used.   665888 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1656 root      39  19   36692  34716   2288 R 90.4  3.4   0:26.62 gfind

Possibly there are alternatives to find & grep too, ack might work instead although I haven't tried yet.

**Comment by Duncaen** [comment]
You can use `xbps-alternatives` to switch between the two implementations:
`xbps-alternatives -g locate -l` to list alternatives for the `locate` group.
`xbps-alternatives -g locate -s mlocate` to set `mlocate` as the `locate` group alternative.
This will make `/usr/bin/locate` to point to `/usr/bin/mlocate`.

**Comment by zqqw** [comment]
Thanks for the tip, that worked. ack also works and searched faster than my find command, although it still used all available CPU - it also looks like cgroups can throttle CPU usage of processes.

**Comment by zqqw** [comment]
$ sudo cgcreate -g cpu:zqqw 
$ ls /sys/fs/cgroup/cpu/zqqw/
cgroup.clone_children  cgroup.procs  cpu.cfs_period_us  cpu.cfs_quota_us  cpu.rt_period_us  cpu.rt_runtime_us  cpu.shares  cpu.stat  notify_on_release  tasks
$ sudo su
/# echo 50000 >/sys/fs/cgroup/cpu/zqqw/cpu.cfs_quota_us
/# cat /sys/fs/cgroup/cpu/zqqw/cpu.cfs_quota_us
50000
$ sudo cgexec -g cpu:zqqw ack "umount2"

Tasks: 173 total,   2 running, 171 sleeping,   0 stopped,   0 zombie
%Cpu(s): 50.3 us, 10.9 sy,  0.0 ni, 27.5 id,  9.9 wa,  0.0 hi,  1.3 si,  0.0 st
KiB Mem :  1028592 total,    64088 free,   521636 used,   442868 buff/cache
KiB Swap:  1116956 total,  1105308 free,    11648 used.   340936 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 1293 root      20   0   10020   7488   3660 R 50.0  0.7   0:47.29 ack /usr/bin/ac
  669 root      20   0  161540  76432  29896 S  3.9  7.4   3:01.91 Xorg
 
And the search completed quietly in the background without switching the fans to high speed.
mupdatedb seems to do an incremental update so is much more efficient than gupdatedb.
It occurs to me now that the faster boot time indicates that BTRFS has improved the HDD data transfer speed. This has resulted in commands that were previously limited by disk access to run faster and now they are limited by CPU performance, so I should adjust to this new performance balance.
Therefore this isn't really a bug so I'm closing it, but I  think that findutils would definitely be improved by using nice in /etc/cron.daily/updatedb like in the mupdatedb equivalent, so it wouldn't block other desktop processes. Possibly maximum CPU usage could be throttled using cgroups, but some users might want it to run at maximum speed though.
