### ISSUE TITLE
update to Postgresql 9.6

### ISSUE THREAD

**Issue by arete** [voidlinux/void-packages#4850]
Hi,for next version of postgresql 9.6, is need update current
package or create another/alternative postgresql9.6
From 9.5 -> 9.6 is necessay an dump/restore.

**Comment by chneukirchen** [comment]
I think we had plans to add packages like postgresql95 postgresql96 because of that...

**Comment by arete** [comment]
Hi,
i try this plan
- [ ] upgrade postgresql -> 9.6.0 meta-package like linux package
- [ ] create new postgresql96 and relative sub-pckgs
- [ ] create new postgresql95 and relative sub-pckgs

**Comment by chneukirchen** [comment]
What's the plan for  postgresql-libs?

**Comment by arete** [comment]
For postgresql-libs can use the last version, 
the incopatibility is for postgresql server.

**Comment by chneukirchen** [comment]
We have 9.6.
