### ISSUE TITLE
Please update sddm to version 0.14.0

### ISSUE THREAD

**Issue by ackalker** [voidlinux/void-packages#4851]
Please update the `sddm` package to upstream version `0.14.0`. Version `0.13.0_1` which is currently in Void Linux has an annoying bug where on `sddm` startup, the password input box below the user icon does not have keyboard focus, which requires me to click inside the input box before I can log in. This issue was fixed in the latest version.

**Comment by chneukirchen** [comment]
f4b1f1b1f9c

**Comment by ackalker** [comment]
Thank you :)
