### ISSUE TITLE
sddm: /etc/sddm.conf should be marked as configuration file

### ISSUE THREAD

**Issue by ackalker** [voidlinux/void-packages#4852]
Sorry for not warning about that in #4851: `sddm` now apparently ships with its own `/etc/sddm.conf` file. I hope no-one has had their sddm configuration blown away by this change, please mark `/etc/sddm.conf` as configuration file.
Note: see also https://github.com/voidlinux/xbps/issues/209

**Comment by chneukirchen** [comment]
f0f6f76ae

**Comment by ackalker** [comment]
Thanks again :)
