### ISSUE TITLE
mysql-client/mariadb-client: Please build with libreadline

### ISSUE THREAD

**Issue by wAmpIre** [voidlinux/void-packages#4897]
With libreadline there's tab completion, ATM it isn't there ;)

**Comment by Hoshpak** [comment]
I can't currently see if and when that changed since github won't show me the history but currently both packages are built against readline-devel and I have verified that tab completion works with mariadb-client on one of my Void VMs. Is there anything else I'm missing or could this issue be closed?

**Comment by wAmpIre** [comment]
Hi!

Some information from my VM:

# xbps-query -l | grep -i "maria\|mysql\|readline"
ii libmariadbclient-10.1.17_1    Fast SQL database server, drop-in replacement for MySQL - client library
ii mariadb-10.1.17_1             Fast SQL database server, drop-in replacement for MySQL
ii mariadb-client-10.1.17_1      Fast SQL database server, drop-in replacement for MySQL - client binaries
ii perl-Term-ReadLine-Gnu-1.34_3 Perl extension for the GNU readline/history library
ii readline-6.3.008_4            The GNU Readline Library

So, mariadb-client is installed, also readline.

# file `which mysql`
/usr/bin/mysql: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=d99a41360260dc827098563c37b1fa827c181a4b, stripped
# ldd `which mysql`
	linux-gate.so.1 (0xb73d6000)
	libpthread.so.0 => /usr/lib32/libpthread.so.0 (0xb73b5000)
	libz.so.1 => /usr/lib32/libz.so.1 (0xb739e000)
	libdl.so.2 => /usr/lib32/libdl.so.2 (0xb7399000)
	libssl.so.38 => /usr/lib32/libssl.so.38 (0xb7343000)
	libcrypto.so.37 => /usr/lib32/libcrypto.so.37 (0xb7186000)
	libncursesw.so.6 => /usr/lib32/libncursesw.so.6 (0xb711a000)
	libgcc_s.so.1 => /usr/lib32/libgcc_s.so.1 (0xb70fc000)
	libc.so.6 => /usr/lib32/libc.so.6 (0xb6f47000)
	/lib/ld-linux.so.2 (0xb73d9000)

As you can see there's no "readline". On an other Debian VM ldd on "mysql" of mariadb-client shows readline:

# ldd `which mysql` | grep readl
	libreadline.so.5 => /lib/x86_64-linux-gnu/libreadline.so.5 (0x00007fddf98ce000)

On Void VM (same on Debian) the client tells me:

# mysql --help | grep readline
mysql  Ver 15.1 Distrib 10.1.17-MariaDB, for Linux (i686) using readline 5.1

So, yes, it's build with readline (at least it show that) - but tab completion does still NOT work... I'm a little bit confused as I don't know what to try/test/look for next.

Thanks for your reply!

**Comment by Hoshpak** [comment]
Please try to connect with "--auto-rehash" or enable that option in your my.cnf. That's what was necessary to get tab completion at least on my Debian jessie box and it works the same for mariadb on Void for me. Unless of course I am mistaken and we are talking about a different tab completion feature.

**Comment by wAmpIre** [comment]
Sorry for the delay. It didn't work, I deinstalled mariadb-client, installed mysql-client and... it worked!

Then I reinstall mariadb-client, and now it works as expected but I don't know why :-/

So, I close this bug.
