### ISSUE TITLE
davfs2 : bug

### ISSUE THREAD

**Issue by lecarrera** [voidlinux/void-packages#4899]
After update davfs2, first a libneon problem. After neon update, davfs2 doesn't mount, and no errors shown.

**Comment by pullmoll** [comment]
Confirmed. It (neon) segfaults in `libssl.so.38.0.0`. I'll try to track that down and fix `neon`.

**Comment by pullmoll** [comment]
It's in this function:
```
ne_ssl_context *ne_ssl_context_create(int mode)
{
    ne_ssl_context *ctx = ne_calloc(sizeof *ctx);
    if (mode == NE_SSL_CTX_CLIENT) {
        ctx->ctx = SSL_CTX_new(SSLv23_client_method());
        ctx->sess = NULL;
        /* set client cert callback. */
        SSL_CTX_set_client_cert_cb(ctx->ctx, provide_client_cert);
        /* enable workarounds for buggy SSL server implementations */
        SSL_CTX_set_options(ctx->ctx, SSL_OP_ALL);
        SSL_CTX_set_verify(ctx->ctx, SSL_VERIFY_PEER, verify_callback);
    } else if (mode == NE_SSL_CTX_SERVER) {
        ctx->ctx = SSL_CTX_new(SSLv23_server_method());
        SSL_CTX_set_session_cache_mode(ctx->ctx, SSL_SESS_CACHE_CLIENT);
#ifdef SSL_OP_NO_TICKET
        /* disable ticket support since it inhibits testing of session
         * caching. */
        SSL_CTX_set_options(ctx->ctx, SSL_OP_NO_TICKET);
#endif
    } else {
        ne_free(ctx);
        return NULL;
    }
    return ctx;
}
```
IIRC the `SSLv23_client_method()` was removed recently. There is no checking if `ctx->ctx` is `NULL` after the call and this is why the call to `SSL_CTX_set_client_cert_cb(ctx->ctx, provide_client_cert);` segfaults.

So the SSLV23_client_method() has to be replaced with something else...

**Comment by pullmoll** [comment]
The problem was a missing initialization of the SSL engine due to another `OPENSSL_VERSION_NUMBER` comparison which failed for libressl.

The condition `OPENSSL_VERSION_NUMBER < 0x10100000` always has to be accompanied by `&& !defined(LIBRESSL_VERSION_NUMBER)`, because libreoffice seized the OPENSSL_VERSION_NUMBER and sets it to a value which confuses downstream...

Long story short: if you update neon again, things should be working ok.

**Comment by Gottox** [comment]
@pullmoll is there something left to do?

**Comment by Gottox** [comment]
no answer in three weeks. reopen if there's any still issue.
