### ISSUE TITLE
syntax error while installing python-2.7.1_2

### ISSUE THREAD

**Issue by nonchip** [voidlinux/void-packages#4902]
```
python-2.7.12_2: configuring ...
Byte-compiling python code in usr/lib/python2.7...
Compiling usr/lib/python2.7/site-packages/gevent/_socket3.py ...
  File "usr/lib/python2.7/site-packages/gevent/_socket3.py", line 183
    def makefile(self, mode="r", buffering=None, *,
                                                  ^
SyntaxError: invalid syntax

Updating ldconfig(8) cache...
python-2.7.12_2: updated successfully.
```

**Comment by ebfe** [comment]
Can't reproduce. `/usr/lib/python2.7/site-packages/gevent/_socket3.py` doesn't belong to any package.
We do have `/usr/lib/python3.4/site-packages/gevent/_socket3.py` in python3.4-gevent (note the 3.4 in the path). Looks like you installed the python3 version of python-gevent manually into the 2.7 site-packages path?

**Comment by nonchip** [comment]
not to my knowledge, but maybe it was pulled as some `pip` dependency?

**Comment by ebfe** [comment]
> not to my knowledge, but maybe it was pulled as some `pip` dependency?

Possible.

**Comment by nonchip** [comment]
well, ok, then i guess i'll clean it up using pip and close this one, package seems fine.

**Comment by chneukirchen** [comment]
You should not use pip in such a way that it will install into that directory...

**Comment by nonchip** [comment]
well, i did not tell it to, so unless that's somehow the default, it shouldn't have done it...
