### ISSUE TITLE
aarch64 builders and qt5

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4904]
It seems as if the aarch64 builders are trying to build qt5 in non-cross mode and fail because (part of) the build system thinks it is on x86_64? Look at the output of the qt5 bootstrap stage2:

```
Running configuration tests (phase 2)...
Done running configuration tests.

   Configure summary

Build type:    linux-g++ (x86_64, CPU features: mmx sse sse2)
```

Is this already wrong?

I can successfully cross compile qt5 on x86_64 for aarch64, so the problem must be in how the non-cross build is set up.

**Comment by chneukirchen** [comment]
Manual rebuild is ongoing, I dunno why we need to do that...

**Comment by chneukirchen** [comment]
And I think this is the host qt.

**Comment by pullmoll** [comment]
So the builders are x86_64?

**Comment by pullmoll** [comment]
Is this perhaps due to XBPS_KEEP_ALL being set and the qt5 build directory being polluted with aarch64 files?

**Comment by pullmoll** [comment]
Issue was solved.
