### ISSUE TITLE
Trouble building FLTK-based app - hardened-cc1 not found

### ISSUE THREAD

**Issue by willbprog127** [voidlinux/void-packages#4906]
Greetings,

When trying to build an FLTK app that builds fine on most other Linux and most BSD installations, I get the following error:

```
c++: error: /void-packages/common/environment/configure/gccspecs/hardened-cc1: No such file or directory
```
I've searched the repo for anything 'hardened' related to gcc or c++ but don't see anything.

:information_source: System Info
    ---
uname -a: `Linux 4.7.6_1 #1 SMP PREEMPT Fri Sep 30 09:20:55 UTC 2016 x86_64 GNU/Linux`
gcc-c++-4.9.4_1
fltk-1.3.3_4
    ---
https://github.com/voidlinux/void-packages/issues/4309 seems to be similar

Thanks

:smile:

**Comment by pullmoll** [comment]
The build server is currently broken, so it may take some time until `fltk-1.3.3_5` is ready.

**Comment by willbprog127** [comment]
@pullmoll Thank you! :smile:
