### ISSUE TITLE
Package request: qmmp

### ISSUE THREAD

**Issue by NimGangstaCat** [voidlinux/void-packages#4913]
`qmmp` could be considered like the Qt replacement of gtk-based multimedia player `audacious`, which could be great on LXQt.

![](http://qmmp.ylsoftware.com/images/qmmp-0.9_full_3.png)

- http://qmmp.ylsoftware.com/
- https://wiki.lxde.org/en/LXDE-Qt#Accessories
- https://blog.lxde.org/?p=1095

**Comment by pullmoll** [comment]
Oops, typo: the version is 1.1.4 not 1.1.14

**Comment by NimGangstaCat** [comment]
And maybe default to the "simple interface" to be equal to gtk-based audacious if the default can be changed somehow at compile time? That would be perfect with others non-skinned Qt applications on LXQt. I'm thinking to qupzilla or qbittorrent.

Thank you for your work :)

**Comment by pullmoll** [comment]
If you find anything how runtime or compile-time configuration defaults can be defined, please let us know. I'm too busy to look for this :)
