### ISSUE TITLE
Move linux-lts to 4.4

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4918]
As of 2016-09-11, kernel 3.14 is EOLed.

I propose we move linux-lts to kernel 4.4, the currently newest LTS release.

**Comment by chneukirchen** [comment]
I also propose we remove old kernels ten:
- linux3.14
- linux4.3
- linux4.5
- linux4.6

**Comment by chneukirchen** [comment]
Would be nice if @xtraeme could +1 this. ;)

**Comment by thypon** [comment]
please do.

**Comment by chneukirchen** [comment]
Will keep 3.14 package around for a bit in case LTS people find regressions.
