### ISSUE TITLE
New package requests: fcitx and fcitx-sunpinyin

### ISSUE THREAD

**Issue by rtlanceroad** [voidlinux/void-packages#492]
I need fcitx and fcitx-sunpinyin (yeah, I am chinese guy)  to input, but they are not in the repo. Hope someone can build.

**Comment by dominikh** [comment]
31f26d4468d3d5afd33de7a432133d6c6c29a36b added fcitx. Is there anything left to do? Is fcitx-sunpinyin part of our fcitx package? Do you even still care/use Void? (if you don't, please close the issue.)

**Comment by rtlanceroad** [comment]
@dominikh I am still using it. :)  Thanks for informing me. I'll close it.

**Comment by rtlanceroad** [comment]
Fcitx has natively build-in pinyin support, no need to add fcitx-sunpinyin to be honest. Fcitx-sunpinyin is a seperate package for implementing fcitx to have better support for Chinese. It's not bad if you add it. What do you think? ^^

**Comment by dominikh** [comment]
One can certainly try to add it. Of course, we'd also have to add sunpinyin, if fcitx-sunpinyin wants to use it.
