### ISSUE TITLE
kdepim: broken (since gpgme-1.7.0 update?)

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4937]
The package `kdepim` does no longer compile. It seems that `CXXFLAGS="-std=c++11"` is required for gpgme-1.7.0 for `std::shared_ptr` support, but this flag is not contained in the `gpgme-config` output. Also the include path `-I/usr/include/gpgme++` seems to be missing.

But even with specifying both locally (and disabling some warnings) in `srcpkgs/kdepim/template` like:
```
CXXFLAGS="-Wno-cpp -Wno-deprecated-declarations -I/usr/include/gpgme++ -std=c++11"`
```

there is an error which I have no idea how to fix

```
/builddir/kdepim-4.14.3/libkleo/backends/qgpgme/qgpgmechangeexpiryjob.cpp: In function 'Kleo::_detail::ThreadedJ
obMixin<Kleo::ChangeExpiryJob>::result_type change_expiry(GpgME::Context*, const GpgME::Key&, const QDateTime&)'
:
/builddir/kdepim-4.14.3/libkleo/backends/qgpgme/qgpgmechangeexpiryjob.cpp:73:46: error: cannot bind 'std::auto_p
tr<GpgME::EditInteractor>' lvalue to 'std::auto_ptr<GpgME::EditInteractor>&&'
   const Error err = ctx->edit( key, ei, data );
                                              ^
In file included from /usr/include/c++/4.9/memory:84:0,
                 from /usr/include/gpgme++/verificationresult.h:32,
                 from /usr/include/gpgme++/context.h:30,
                 from /builddir/kdepim-4.14.3/libkleo/backends/qgpgme/threadedjobmixin.h:44,
                 from /builddir/kdepim-4.14.3/libkleo/backends/qgpgme/qgpgmechangeexpiryjob.h:38,
                 from /builddir/kdepim-4.14.3/libkleo/backends/qgpgme/qgpgmechangeexpiryjob.cpp:33:
/usr/include/c++/4.9/backward/auto_ptr.h:322:5: note: initializing argument 1 of 'std::unique_ptr<_Tp, _Dp>::uni
que_ptr(std::auto_ptr<_Up>&&) [with _Up = GpgME::EditInteractor; <template-parameter-2-2> = void; _Tp = GpgME::E
ditInteractor; _Dp = std::default_delete<GpgME::EditInteractor>]'
```

It seems like kde is just becoming too aged to be compatible with newer libs it requires...

BTW: It fails the in the same way with gcc6.

**Comment by ebfe** [comment]
With gpgme-1.6.2 the build still works.

**Comment by Hoshpak** [comment]
I ran into the same issue earlier today while trying to compile another package that depends on kdepimlibs-devel. Both packages provide (gpgme-devel and kdepimlibs-devel) provide the gpgme++ headers so you have conflicting files if you install both packages and of course they ship different versions.

From what I can find up to know, gpgme++ was originally developed within the KDE project and later integrated into the official gpgme source tree. That seems to have happened between the 1.6.0 and 1.7.0 releases which explains why it works with 1.6.0. At least I couldn't find any of the gpgme++ header files in 1.6.0.

Perhaps it would be possible to move the gpgme++ header files into a separate package and declare a conflict between the new package (gpgmepp-devel ?) and kdepimlibs-devel as a short-term solution. Of course that would cause problems for people needing a current version of gpgme++ and the "old" kdepimlibs-devel but I am not currently aware of any applications that would require it.

**Comment by ebfe** [comment]
@Hoshpak you are right. Flipping the dependency order makes the build go through.

**Comment by pullmoll** [comment]
Heh, I didn't realize the duplication of headers. Thanks for the hint @Hoshpak !

I guess we should really split off a `gpgme++-devel` subpackage then.

**Comment by pullmoll** [comment]
Split is done. Now we'd need to check if any of the packages using gpgme-devel actually linked agains `libgpgmepp.so.6`, in which case it would need to include `makedepends+="gpgmepp-devel"` now.

**Comment by ebfe** [comment]
```
$ xbps-query -R -p shlib-requires -s gpgmepp
$
```

**Comment by pullmoll** [comment]
Yep, while perhaps it still may be advised to revbump kdepimlibs and to probably remove the hacks I applied earlier to kde-runtime, because they should now be unneccesary.

kdepim built now.

**Comment by pullmoll** [comment]
Problem solved. Thank you @Hoshpak and @ebfe
