### ISSUE TITLE
Package request: pdfsam

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#4958]
Tool to split and merge PDF files.
web site: http://www.pdfsam.org/
source code: https://github.com/torakiki/pdfsam/releases

**Comment by Vaelatern** [comment]
Java, AGPL-3.0
Probably needs maven.

**Comment by Hoshpak** [comment]
It indeed does. It also depends on JavaFX so it needs openjfx or something like that. I briefly tried to build it on one of my systems and it first downloaded binary files for an eternity (what happened to building things from source?) and then failed with some (to me) meaningless error message. I really don't want to go into packaging any java based software myself but would appreciate it if someone else would package it since it's really a convenient tool. In the meantime I'm fine with using pdftk on the command line however.

**Comment by Hoshpak** [comment]
now that pdftk is gone, I switched to qpdf. Not as convenient but gets the job done. Since I am no longer interested in pdfsam, I'm closing this issue.
