### ISSUE TITLE
libpng/libpng12 man page conflicts

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#4959]
libpng/libpng12:
- /usr/share/man/man5/png.5 

libpng-devel/libpng12-devel:
- /usr/share/man/man3/libpngpf.3
- /usr/share/man/man3/libpng.3

cc @lemmi

**Comment by lemmi** [comment]
I'll have a look tomorrow. (we need that sanity check in https://github.com/voidlinux/xbps/issues/65 !)

**Comment by Gottox** [comment]
@lemmi any progress?

**Comment by Vaelatern** [comment]
Bump

**Comment by Gottox** [comment]
Hmm... What is using libpng12 anyway? Could we remove the package?

**Comment by Vaelatern** [comment]
We could, but e.g. teamviewer and wps office at the very least use it. wps office currently packages it for itself, but that was when xt refused to consider a libpng12 package
