### ISSUE TITLE
dracut: allow busybox as alternative to bash

### ISSUE THREAD

**Issue by jannisch** [voidlinux/void-packages#4993]
dracut currently depends on bash which is very annoying for users who want to use busybox.
A _05busybox_ module is already included in the dracut package so I just changed to dracut.conf like this:

``` bash
omit_dracutmodules+="bash"
add_dracutmodules+="busybox"
```
it already seems to work, I also checked that the rescue shell uses busybox's ash.

Now I wonder what actually happeded to the base-system-busybox package and how we could automatically use the busybox dracut module instead of bash when installed.

**Comment by Duncaen** [comment]
In the initramfs itself, dracut uses sh, bash is still required for building the initramfs.

**Comment by jannisch** [comment]
Oh, I see.
Nevertheless, the busybox module probably performs better then the bash one so it could be preferred.
But first what about the `base-system-busybox` pkg?

**Comment by Vaelatern** [comment]
@the-maldridge has had experiments with `busybox`, but I don't remember the details.

**Comment by jannisch** [comment]
I see. Besides bash dracut alsa uses some fancy features in the coreutils so it does not work out very well on Void.
