### ISSUE TITLE
linux kernels + ccache

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#4994]
It seems we have a problem with (all?) linux kernels and ccache.

It has been documented by several people, including me, that sometimes the generated host tool `fixdep` is failing to build at all or is reporting header files from another, entirely unrelated kernel build.

I suggest to add `export CCACHE_DISABLE=1` to all kernel templates until this apparent bug of ccache is found and eliminated.

The fact that some builds still fail, despite adding this flag to some templates, is probably due to not cleaning the build environment before retrying.

**Comment by ebfe** [comment]
Do you see this with ccache 3.3.2 too? The builders might not be up to date.

**Comment by pullmoll** [comment]
I _think_ I have seen it happening here with the gcc6 builds, which use the latest ccache.
I'll verify if it really happens here again.

**Comment by pullmoll** [comment]
Yup, just tried to build 4.1.34 for i686 and see this error:
```
  HOSTCC  arch/x86/tools/relocs_64.o
fixdep: error opening config file: /builddir/linux-3.14.77/tools/include/tools/le_byteshift.h: No such file or directory
make[1]: *** [scripts/Makefile.host:108: arch/x86/tools/relocs_common.o] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [arch/x86/Makefile:175: archscripts] Error 2
make: *** Waiting for unfinished jobs....
=> ERROR: linux4.1-4.1.34_1: failed to run do_build() at line 88.
```

**Comment by ebfe** [comment]
FWIW i seen similar failures too, but since i upgraded to 3.3.2 i haven't hit it anymore.

https://ccache.samba.org/releasenotes.html#_ccache_3_3_2
> Fixed a regression in ccache 3.3 related to potentially bad content of dependency files when compiling identical source code but with different source paths.

**Comment by ebfe** [comment]
and IIRC i needed to clean the cache.

**Comment by pullmoll** [comment]
Yes, verified with `./xbps-src chroot` and `ccache --version` that it is indeed `ccache version 3.3.2`.

**Comment by pullmoll** [comment]
Ok, I'll try `ccache -c` for the shared CCACHE_DIR here.

**Comment by pullmoll** [comment]
Same error happens even after cleaning the directory.
It does of course not happen, if I wipe it with `ccache -C`, which I want to avoid to have faster rebuilds in the other 3*7000 packages ;-)

**Comment by pullmoll** [comment]
linux4.4 which already has the `export CCACHE_DISABLE=1` is now building for i686 here.

**Comment by ebfe** [comment]
If the bug produced broken/wrong cache entries I don't know how it could be fixed without wiping the cache :/

**Comment by pullmoll** [comment]
Well, my original suggestion to disable ccache for all kernels should still work, if the builders would be reset (zap + binary-bootstrap?) before the retry.

It doesn't really hurt to disable ccache for the kernels, because you get a hit ratio of next to 0 for a kernel update anyway.

**Comment by pullmoll** [comment]
BTW my CCACHE_DIR currently has 165GiB for the ~22000 pkgs built... *sigh*

**Comment by pullmoll** [comment]
Apropos wiping ccache: if we move to gcc6, all existing ccache entries will become invalid anyway, because the compiler checksum changes. So if there are any buggy files in the cache, they will silently fade away.

**Comment by pullmoll** [comment]
@Duncaen could you please reset the x86_64-musl builder? It always tries to rebuild linux3.18 without cleaning the builddir.

**Comment by Duncaen** [comment]
@pullmoll its clean now, Interesting with the cache size, the musl builder has only 32GB currently.

**Comment by pullmoll** [comment]
Aw, my fault again with DISABLE_CCACHE instead of CCACHE_DISABLE.
Now all kernels should build.
