### ISSUE TITLE
bitcoin: broken because of last boost update

### ISSUE THREAD

**Issue by jannisch** [voidlinux/void-packages#5012]
@ebfe updated the boost libraries a few hours ago, but xbps-install tells me that this update breaks `bitcoin-qt-0.13.0_2` (it's a dependency).

`xbps-query -RX boost | grep bitcoin` does not give any results, how is this possible?

**Comment by Vaelatern** [comment]
It is possible because the builders are still slowly working on getting the boost libraries updated across the board.
This is a non-issue, try updating later.
