### ISSUE TITLE
linux4.8 install - 4.8.3_1   didn't boot after update

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#5021]
Updated xbps, then updated again and rebooted.
The boot froze at the loading initrd point and I had to press the power button to switch off and then booted with the old 4.7 kernel from the Grub menu, which I had previously put on hold to avoid updating that as well. I have only tried this once, I updated just recently.

```
$ inxi -v7 -z
System:    Host: ok Kernel: 4.7.6_1 i686 (32 bit gcc: 4.9.4)
           Desktop: Xfce 4.12.3 (Gtk 2.24.31) info: xfce4-panel dm: lxdm Distro: void
Machine:   System: Dell (portable) product: Latitude C840 Chassis: type: 8
           Mobo: Dell model: Latitude C840 BIOS: Dell v: A08 date: 12/10/2002
Battery    BAT1: charge: 52.4 Wh 92.3% condition: 56.8/63.4 Wh (90%) volts: 15.9/14.4
           model: PanasCompa CPI1691 Li-ion serial: 3 status: Charging cycles: 0
CPU:       Single core Mobile Intel Pentium 4 - M (-UP-) cache: 512 KB
           flags: (pae sse sse2) bmips: 3589 speed/min/max: 1800/1200/1800 MHz
Memory:    Using dmidecode: dmidecode is not installed.
Graphics:  Card: NVIDIA NV17M [GeForce4 440 Go] bus-ID: 01:00.0 chip-ID: 10de:0174
           Display Server: X.Org 1.18.4 drivers: nouveau (unloaded: vesa) Resolution: 1400x1050@60.02hz
           GLX Renderer: Mesa DRI nv17 x86/MMX/SSE2 GLX Version: 1.2 Mesa 12.0.3 Direct Rendering: Yes
Audio:     Card Intel 82801CA/CAM AC'97 Audio Controller
           driver: snd_intel8x0 ports: d800 dc80 bus-ID: 00:1f.5 chip-ID: 8086:2485
           Sound: Advanced Linux Sound Architecture v: k4.7.6_1
Network:   Card-1: 3Com 3c905C-TX/TX-M [Tornado] driver: 3c59x port: ec80 bus-ID: 02:00.0 chip-ID: 10b7:9200
           IF: enp2s0 state: down mac: <filter>
           Card-2: Ralink RT2760 Wireless 802.11n 1T/2R
           driver: rt2800pci v: 2.3.0 bus-ID: 07:00.0 chip-ID: 1814:0701
           IF: wlp7s0 state: up mac: <filter>
           WAN IP: <filter> IF: enp2s0 ip-v4: N/A ip-v6: N/A
           IF: wlp7s0 ip-v4: <filter> ip-v6: <filter>
Drives:    HDD Total Size: 30.0GB (30.7% used)
           ID-1: /dev/sda model: IC25N030ATMR04 size: 30.0GB serial: MRG218K2CEAY6J
           Optical: /dev/sr0 model: TEAC CD-224E rev: 3.7C dev-links: cdrom
           Features: speed: 24x multisession: yes audio: yes dvd: no rw: none state: running
Partition: ID-1: / size: 27G used: 7.4G (30%) fs: btrfs dev: /dev/sda2
           label: N/A uuid: 7106672b-4d04-4a8e-9f78-51f9be667da8
           ID-2: /boot size: 485M used: 164M (36%) fs: ext2 dev: /dev/sda1
           label: N/A uuid: e838f240-7d07-4f7b-a65b-0c2b764d563f
           ID-3: swap-1 size: 1.14GB used: 0.04GB (4%) fs: swap dev: /dev/sda3
           label: N/A uuid: cd9e6387-7688-4fb2-ae41-70bac192b6e3
RAID:      No RAID data: /proc/mdstat missing-is md_mod kernel module loaded?
Unmounted: ID-1: /dev/fd0 size: 0.00G label: N/A uuid: N/A
Sensors:   None detected - is lm-sensors installed and configured?
Info:      Processes: 179 Uptime: 23 min Memory: 666.7/1004.5MB Init: runit v: N/A Gcc sys: 4.9.4
           Client: Shell (bash 4.3.481 running in xfce4-terminal) inxi: 2.3.1 
```

**Comment by Hoshpak** [comment]
Are you sure that this was caused by the kernel update and not some other circumstances like the initrd generation being interrupted or the /boot partition running out of free space during the installation? Did you try manually generating the initrd again and booting into the new kernel?

Of course it is possible that the new kernel has a bug that breaks everything on your specific hardware or software configuration but since it runs fine here and for many other people, it at least doesn't seem to have a bug that breaks the kernel in general. (unlike 4.8)

**Comment by suiginsoft** [comment]
Was there anything in the dmesg log after the freeze?

**Comment by zqqw** [comment]
Here is what I updated on 22 - 10 - 2016:
$ sudo xbps-install -Su
[*] Updating `https://repo.voidlinux.eu/current/i686-repodata' ...
i686-repodata: 1155KB [avg rate: 128KB/s]

Name    Action    Version           New version            Download size
libxbps update    0.51_11           0.51_12                108KB
xbps    update    0.51_11           0.51_12                78KB
$ sudo xbps-pkgdb -m hold linux4.7-4.7.6_1
$ sudo xbps-install -Su
[*] Updating `https://repo.voidlinux.eu/current/i686-repodata' ...

Name     Action    Version           New version            Download size
linux4.4 hold      4.4.5_1           4.4.26_1               -
linux4.7 hold      4.7.6_1           4.7.9_1                -
iw       update    4.7_1             4.9_1                  -
libpng   update    1.6.25_1          1.6.26_1               -
linux4.8 install   -                 4.8.3_1                50MB
linux    update    4.7_1             4.8_1                  648B
tzdata   update    2016g_2           2016h_1                155KB


4.8 kernel didn't boot:
Booting 'Void GNU/Linux'
Loading Linux 4.8.3_1 ...
Loading initial ramdisk ...
_


Nothing more happened at all, I tried again later to be sure.
I chose the 4.7 kernel from the advanced options menu, and moved the 4.8 things from /boot to /opt, and made a copy of /boot/grub/grub.cfg there too.
$ ls /opt |ag 4.8
System.map-4.8.3_1
config-4.8.3_1
initramfs-4.8.3_1.img
vmlinuz-4.8.3_1

I decided not to uninstall the 4.8 kernel so I would still get updates for it as usual.
$ sudo update-grub
Generating grub configuration file ...
Found background: /usr/share/void-artwork/splash.png
Found linux image: /boot/vmlinuz-4.7.6_1
Found initrd image: /boot/initramfs-4.7.6_1.img
Found linux image: /boot/vmlinuz-4.7.4_1
Found initrd image: /boot/initramfs-4.7.4_1.img
Found linux image: /boot/vmlinuz-4.4.5_1
Found initrd image: /boot/initramfs-4.4.5_1.img
done
(Probably there is an easier way to change the default menu option in Grub menu but this worked.)
$ sudo diff -u /boot/grub/grub.cfg /opt/grub.cfg
Password:
--- /boot/grub/grub.cfg 2016-10-22 14:53:38.000000000 +0100
+++ /opt/grub.cfg       2016-10-22 14:53:09.252465446 +0100
@@ -111,12 +111,46 @@
        else
          search --no-floppy --fs-uuid --set=root e838f240-7d07-4f7b-a65b-0c2b764d563f
        fi
-       echo    'Loading Linux 4.7.6_1 ...'
-       linux   /vmlinuz-4.7.6_1 root=UUID=7106672b-4d04-4a8e-9f78-51f9be667da8 ro  loglevel=4
+       echo    'Loading Linux 4.8.3_1 ...'
+       linux   /vmlinuz-4.8.3_1 root=UUID=7106672b-4d04-4a8e-9f78-51f9be667da8 ro  loglevel=4
        echo    'Loading initial ramdisk ...'
-       initrd  /initramfs-4.7.6_1.img
+       initrd  /initramfs-4.8.3_1.img
 }
 submenu 'Advanced options for Void GNU/Linux' $menuentry_id_option 'gnulinux-advanced-7106672b-4d04-4a8e-9f78-51f9be667da8' {
+       menuentry 'Void GNU/Linux, with Linux 4.8.3_1' --class void --class gnu-linux --class gnu --class os $menuentry_id_option
'gnulinux-4.8.3_1-advanced-7106672b-4d04-4a8e-9f78-51f9be667da8' {
+               load_video
+               set gfxpayload=keep
+               insmod gzio
+               insmod part_msdos
+               insmod ext2
+               set root='hd0,msdos1'
+               if [ x$feature_platform_search_hint = xy ]; then
+                 search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1
e838f240-7d07-4f7b-a65b-0c2b764d563f
+               else
+                 search --no-floppy --fs-uuid --set=root e838f240-7d07-4f7b-a65b-0c2b764d563f
+               fi
+               echo    'Loading Linux 4.8.3_1 ...'
+               linux   /vmlinuz-4.8.3_1 root=UUID=7106672b-4d04-4a8e-9f78-51f9be667da8 ro  loglevel=4
+               echo    'Loading initial ramdisk ...'
+               initrd  /initramfs-4.8.3_1.img
+       }
+       menuentry 'Void GNU/Linux, with Linux 4.8.3_1 (recovery mode)' --class void --class gnu-linux --class gnu --class os
$menuentry_id_option 'gnulinux-4.8.3_1-recovery-7106672b-4d04-4a8e-9f78-51f9be667da8' {
+               load_video
+               set gfxpayload=keep
+               insmod gzio
+               insmod part_msdos
+               insmod ext2
+               set root='hd0,msdos1'
+               if [ x$feature_platform_search_hint = xy ]; then
+                 search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1
e838f240-7d07-4f7b-a65b-0c2b764d563f
+               else
+                 search --no-floppy --fs-uuid --set=root e838f240-7d07-4f7b-a65b-0c2b764d563f
+               fi
+               echo    'Loading Linux 4.8.3_1 ...'
+               linux   /vmlinuz-4.8.3_1 root=UUID=7106672b-4d04-4a8e-9f78-51f9be667da8 ro single
+               echo    'Loading initial ramdisk ...'
+               initrd  /initramfs-4.8.3_1.img
+       }
        menuentry 'Void GNU/Linux, with Linux 4.7.6_1' --class void --class gnu-linux --class gnu --class os $menuentry_id_option
'gnulinux-4.7.6_1-advanced-7106672b-4d04-4a8e-9f78-51f9be667da8' {
                load_video
                set gfxpayload=keep

$ sudo du -h /boot
12K	/boot/lost+found
2.3M	/boot/grub/i386-pc
4.0M	/boot/grub/locale
2.3M	/boot/grub/fonts
8.5M	/boot/grub
125M	/boot

/boot is a 0.5GB ext2 partition, so has plenty of space. But I suppose ext2 could be error prone.
There was nothing in any dmesg log about a 4.8 kernel, I think it looks like Grub tried to load whatever it wanted to load from /boot and it just failed immediately, as the last onscreen messages came from grub.cfg.
The 4.7 kernel still seems to work with all the other updated software fortunately.

**Comment by zqqw** [comment]
Some more info and a link to the affected files:
$ sudo ls -lh /boot
total 117M
-rw-r--r-- 1 root root 1.7M Mar 10  2016 System.map-4.4.5_1
-rw-r--r-- 1 root root 1.8M Sep 15 10:04 System.map-4.7.4_1
-rw-r--r-- 1 root root 1.8M Sep 30 10:20 System.map-4.7.6_1
-rw-r--r-- 1 root root 166K Mar 10  2016 config-4.4.5_1
-rw-r--r-- 1 root root 173K Sep 15 10:04 config-4.7.4_1
-rw-r--r-- 1 root root 173K Sep 30 10:20 config-4.7.6_1
drwxr-xr-x 5 root root 1.0K Oct 22 14:53 grub
-rw------- 1 root root  34M Sep 16 14:55 initramfs-4.4.5_1.img
-rw------- 1 root root  34M Sep 18 14:30 initramfs-4.7.4_1.img
-rw------- 1 root root  31M Oct  1 02:56 initramfs-4.7.6_1.img
drwx------ 2 root root  12K Sep 16 14:49 lost+found
-rw-r--r-- 1 root root 3.9M Mar 10  2016 vmlinuz-4.4.5_1
-rw-r--r-- 1 root root 4.1M Sep 15 10:04 vmlinuz-4.7.4_1
-rw-r--r-- 1 root root 4.1M Sep 30 10:20 vmlinuz-4.7.6_1

I uploaded these probably faulty files as a tar.xz archive on a temporary link which can be downloaded here:
https://yadi.sk/d/1Zs6uOi_xTWJD
$ ls -lh /opt |ag 4.8
-rw-r--r-- 1 root root 1.8M Oct 20 13:09 System.map-4.8.3_1
-rw-r--r-- 1 root root 175K Oct 20 13:09 config-4.8.3_1
-rw------- 1 root root  30M Oct 22 02:06 initramfs-4.8.3_1.img
-rw-r--r-- 1 root root 4.1M Oct 20 13:09 vmlinuz-4.8.3_1

(In case anyone was able to decompress and loop mount the image and ask it why it isn't working.)

$ sudo fdisk -l
Disk /dev/sda: 28 GiB, 30005821440 bytes, 58605120 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xaecd75eb

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sda1  *        2048  1026047  1024000  500M 83 Linux
/dev/sda2        1026048 56371199 55345152 26.4G 83 Linux
/dev/sda3       56371200 58605119  2233920  1.1G 82 Linux swap / Solaris

**Comment by pullmoll** [comment]
Just use a triple backquote before and after shell command output or diff files. This disables interpreting special characters as markup code and makes the output use a monospace font. I edited your posts.

**Comment by zqqw** [comment]
Thank you for that, the diff now shows that Grub found the file correctly. I have tried some more things to confirm this is a problem with the kernel package and not some installation glitch.
I reinstalled the package:
/var/cache/xbps$ sudo xbps-rindex -a *.xbps
/var/cache/xbps$ sudo xbps-install -f --repository=/var/cache/xbps linux4.8-4.8.3_1
It still didn't work. So I removed an old kernel to check for space issues:
$ vkpurge list
4.7.4_1
$ sudo vkpurge rm 4.7.4_1
$ sudo xbps-install -f --repository=/var/cache/xbps linux4.8-4.8.3_1
After rebooting, the results were the same. Adding rd.break to the command line didn't help, the boot didn't get that far.
It seems this particular kernel build doesn't work in it's 32 bit form, certainly not on my hardware.

**Comment by cavalier911** [comment]
Pentium M boot failure on Kernel 4.8
https://bugs.archlinux.org/task/51506
https://bbs.archlinux.org/viewtopic.php?pid=1663683

**Comment by zqqw** [comment]
This has been fixed in later versions of the kernel, which I have subsequently upgraded to and  have been using without any boot up problems. So I'm closing this as it has been fixed for a while now, thanks to everyone for the swift and effective action.
