### ISSUE TITLE
Note to self: qt5 cross cmake files are broken

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5059]
As can be seen in pkgs trying to cross compile qt5 using the  cmake build style, the paths stored in the *.cmake files are hosed. Example:  [`breeze-icons`](https://build.voidlinux.eu/builders/armv7l_builder/builds/28569/steps/shell_3/logs/stdio) package.

We need to either set the `QMAKESPEC=${XBPS_CROSS_BASE}/usr/lib/qt5/mkspecs/void-${XBPS_CROSS_TRIPLET}-g++`  iff cross compiling, or always use the default `QMAKESPEC=/usr/lib/qt5/mkspecs/linux-g++` (or none at all, because this is the default) and set (at least) the `QMAKE_CC`, `QMAKE_CXX` and `QMAKE_LINK` variables from the template or a `common/*` script somehow.

Darn, why did I even start to try to get qt5 cross compiling to work? :-/

**Comment by dutsky** [comment]
Because only you knows how to make it! :3

**Comment by ayghor** [comment]
why do you do this to yourself

**Comment by pullmoll** [comment]
Fixed the `Qt5CoreConfigExtrasMkspecDir.cmake` file. `breeze-icons` still does not cross compile because a tool is built for the target, not for the host, but that's a different issue.
