### ISSUE TITLE
Building host pkgs when cross compiling

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5067]
As can be seen in [temporary](https://build.voidlinux.eu/builders/armv6l_builder/builds/28563/steps/shell_3/logs/stdio) and [permanent](https://build.voidlinux.eu/builders/aarch64_builder/builds/1597/steps/shell_3/logs/stdio) failures to cross build a package, there is a problem whenever the cross package builds a not yet available host package as a dependency.

It seems as if the environment set up to cross build has an impact on the native build. For qt5 this happened for cross `armv6l` and `armv7l` building `phototonic` when the `x86_64` package `qt5` was not yet ready. The cross builder then tries to compile the host `qt5` and its shipped 3rdparty/chromium source using the `arm-linux-guneabihf-c++` or the `armv7l-linux-gnueabihf-c++` instead of the host's `c++`.

To me it looks as if an environment variable, which was set up for cross compiling, is not cleaned for the native build in these cases.

Perhaps some `unset CXX_host` or `CXX_target` or similar are required as a clean up?
These are set in `common/xbps-src/shutils/common.sh` for the cross build case.

Testing locally if unsetting the various _host and _target variables cures the problem.

**Comment by pullmoll** [comment]
It worked here, i.e. qt5 for host built before qt5 for target and the package using both.

**Comment by chneukirchen** [comment]
Good catch!
