### ISSUE TITLE
jasper: "Hopefully, these macros ..."

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5069]
The file `/usr/include/jasper/jas_types.h` includes this comment and code
```
#if defined(HAVE_SYS_TYPES_H)
#include <sys/types.h>
#endif

/* Hopefully, these macro definitions will fix more problems than they cause. */
#if !defined(uchar)
#define uchar unsigned char
#endif
#if !defined(ushort)
#define ushort unsigned short
#endif
#if !defined(uint)
#define uint unsigned int
#endif
#if !defined(ulong)
#define ulong unsigned long
#endif
#if !defined(longlong)
#define longlong long long
#endif
#if !defined(ulonglong)
#define ulonglong unsigned long long
#endif
```

And this hope turns out to be disappointed by e.g. `libgdal-2.1.2` which I'm working on.

For glibc I could stop errors regarding these types by adding `#include <sys/types.h>` before `#include <jasper/jasper.h>`, but this does not work out for musl libc.

The problem here is that these types are typedef'd, not #define'd.

Perhaps we can patch `jasper/jas_types.h` to only `#define` these types in an `#else` branch of the existing `#if defined(HAVE_SYS_TYPES_H)`.

If noone objects I can create a patch for jasper along with the update of libgdal.

**Comment by pullmoll** [comment]
It turns out that the macro definitions are not the culprit, because the `#else` patch doesn't fix the problem with libgdal. Looking for a solution that works.

**Comment by pullmoll** [comment]
The real name space polluter seems to be `/usr/include/jasper/jas_config.h`.
There's a number of `#defines` which really shouldn't be there:
```
/* Define to `unsigned char' if <sys/types.h> does not define. */
#define uchar unsigned char

/* Define to `unsigned int' if <sys/types.h> does not define. */
#define uint unsigned int

/* Define to `unsigned long' if <sys/types.h> does not define. */
#define ulong unsigned long

/* Define to `unsigned long long' if <sys/types.h> does not define. */
#define ulonglong unsigned long long

/* Define to `unsigned short' if <sys/types.h> does not define. */
#define ushort unsigned short
```

So it looks like jasper's configure doesn't detect that sys/types.h already defines these types.

And indeed, the configure output for both, x86_64 and x86_64-musl tells:
```
checking for size_t... yes
checking for uchar... no
checking for ushort... no
checking for uint... no
checking for ulong... no
checking for longlong... no
checking for ulonglong... no
```

We better fix or rip out these tests from configure{,.ac} then.

**Comment by ebfe** [comment]
Yes, the latest jasper version still has the same problem.

**Comment by pullmoll** [comment]
I'm trying a patch that removes the type checks from configure.ac, that should solve the problem.

**Comment by pullmoll** [comment]
Solved in https://build.voidlinux.eu/changes/31628

**Comment by pullmoll** [comment]
Now some :beer: is waiting for me ... :laughing:
