### ISSUE TITLE
https://build.voidlinux.eu/builders/x86_64-musl_builder hosed

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5071]
It looks as if our x86_64-musl builder is seriously hosed and creates broken packages, if anything at all.

Obviously disk or tmp is full again.

**Comment by Duncaen** [comment]
I cleaned it, but its going to run out of space again in the near feature.
Need to increase the lvm volume, there is still some free space.

**Comment by pullmoll** [comment]
Perhaps you can meanwhile decrease the ccache buffer space. I seem to remember you said is was 32G?
