### ISSUE TITLE
terminus-font: undesirable alternate tilde

### ISSUE THREAD

**Issue by lafrenierejm** [voidlinux/void-packages#5110]
Several characters in Terminus Font have two variations.  For most of these characters Void's current package uses the first of the two variations. The package's current tilde character ('~'), though, is the secondary `td2` instead of `td1`.

`td2` is elevated in line with '^' instead of being in-line with '-'. The font's [homepage](http://terminus-font.sourceforge.net/) notes that "perhaps td1 should be the default."

**Comment by 7185** [comment]
> **perhaps** td1 should be the default.

That means td2 **is** the default for now. There is a patch in the source code in `alt/td1.diff` if you want to use td1, but I think Void tends to stick with vanilla upstream sources.

**Comment by chneukirchen** [comment]
Convince upstream to change the defaults, or install a patched copy to your own `~/.fonts`.
