### ISSUE TITLE
numix-themes: the source code gets installed to /usr/share/themes instead of the theme

### ISSUE THREAD

**Issue by jcjordyn130** [voidlinux/void-packages#5140]
Whenever I install numix-themes, the source code gets installed instead of the themes.

**Comment by liwakura** [comment]
Same issue, can confirm.
The package is never running make, but just copying the sources into destdir.

**Comment by liwakura** [comment]
There is an pull request by the maintainer already, see #5709

**Comment by maxice8** [comment]
Issue was merged, resolved ?

**Comment by jcjordyn130** [comment]
Closing. Reason: Resolved.
