### ISSUE TITLE
Package request: nweb23

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#5141]
Probably the smallest web server yet: https://gist.github.com/sumpygump/9908417

**Comment by chneukirchen** [comment]
It's not really good code, e.g. see https://news.ycombinator.com/item?id=7505535

**Comment by Anachron** [comment]
Thanks, I will go with `lighttpd` then!

**Comment by chneukirchen** [comment]
IME nginx is more robust.

**Comment by Anachron** [comment]
@chneukirchen yes but also 4x the amount of code being used. I favor light solutions.
