### ISSUE TITLE
libgnomekbd-3.22.0_1, scheme missing

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#5146]
Since libgnomekbd-3.22.0, don't ship with the scheme `org.gnome.libgnomekbd.desktop`, cinnamon_session crash on start with `crash on startup with a glib error`.

**Comment by Gottox** [comment]
Did you try to update cinnamon to 3.2?

**Comment by pulux** [comment]
fixed with cinnamon 3.2
