### ISSUE TITLE
RSA signature invalid: libksba (musl x86_64)

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#5163]
libksba-1.3.5_1: verifying RSA signature...
ERROR: libksba-1.3.5_1: the RSA signature is not valid!
ERROR: libksba-1.3.5_1: removed pkg archive and its signature.

**Comment by ebfe** [comment]
```
$ xbps-verify libksba-1.3.5_1.x86_64-musl.xbps
good signature from 'https://repo.voidlinux.eu/current'
```

Maybe aborted download?

**Comment by 38github** [comment]
On Saturday, November 12, 2016 11:59:22 PM CET Michael Gehring wrote:
> ```
> $ xbps-verify libksba-1.3.5_1.x86_64-musl.xbps
> good signature from 'https://repo.voidlinux.eu/current'
> ```
> 
> Maybe aborted download?
I will try it out later tonight and see what it says. Is there a command to 
force to download all packages again?

**Comment by Vaelatern** [comment]
Bump.

**Comment by 38github** [comment]
When I updated last night I recieved no errors but I can't remember if that package was handled during that process so let me check in ~15 minutes.
⁣

Sent from BlueMail

​

**Comment by 38github** [comment]
It had been installed during -Su it seems.
