### ISSUE TITLE
efibootmgr creating unwanted side-effects

### ISSUE THREAD

**Issue by Neffistopheles** [voidlinux/void-packages#5165]
efibootmgr package has just updated to automatically register the kernel as a bootable option with the system's EFI boot manager,

#5085 

I feel as though this is an invasive choice. The process of booting the system is a decision which should be left to the system administrator. Virtually nobody explicitly installs efibootmgr. 

It's especially worrisome because the quality of EFI implementations still varies greatly, and this may cause unexpected problems for some users, who may have trouble pinpointing it to this package. For instance, on my local machine I use full disk encryption with an external, removable bootloader to prevent bootkitting. Unfortunately my EFI considers removable devices to be ephemeral and their boot selection order will never persist. So despite this re-assuring message I get after updating efibootmgr:

`The bootorder itself is not changed, so your previous boot loader will
stay enabled until you can edit the order in your firmware interface or
using "efibootmgr -o <hexnum>"`

In fact this _will_ change my boot order. I will now have to manually remove the boot entry on every kernel update to avoid my local EFI from circumventing my preferred boot device, or having to manually choose it on each bootup. 

Moreoever, I don't see a correct way to persistently defeat these hooks, which is stable across package updates, so this is specifically working against the intentions of the local system administrator in a very troubling way. We are given no correct means to opt-out of this silly behavior. 

Please revert this absolutely ridiculous commit. This is the type of stuff that belongs in local user scripts, not at the packaging level.

**Comment by CMB** [comment]
I'm also a little worried about boot entries changing out from under me.
But I think I found a compromise which might make everyone happy.
Check out the efiboot branch on CMB/void-packages.
https://github.com/CMB/void-packages/tree/efiboot

**Comment by Neffistopheles** [comment]
Indeed, I have no quarrels with the change if it's optional and disabled by default. I also like your moving the config to `-kernel-hook.conf`, because otherwise it seems as though this behavior is a feature of efibootmgr proper, and not our specific packaging. I'm still wary of _packagers_ adding features like this; I think it's the job of upstream to add features like this to the project proper. But it's at least lot saner than just taking control over local system policies without consent. 

For now I've just reverted the commit in my local void-packages repo. But I really hate having to keep packages on hold. I hope to see your changes pushed soon.

**Comment by CMB** [comment]
Unfortunately my changes really haven't been tested in the wild, as
that would require a reboot of my only EFI machine.
Seems good in theory though.

**Comment by CMB** [comment]
I think this can be closed.  Fixed with commit
8e5f9e9679a6a9a11f9b2e0210367269c80fd013

**Comment by jannisch** [comment]
I am the submitter of the hook PR and want to apologize for the issues you have experienced.
On one hand I thought that it does not even take effect before mounting the efivars as described and one the other hand I could not expect that some firmwares don't properly support this industry standart which seems to be 10 years old now.

But since nobody within more than two weeks commented on the PR this reaction is just offending and disrespectful.
