### ISSUE TITLE
linux: enable CONFIG_MMC_REALTEK_USB

### ISSUE THREAD

**Issue by cavalier911** [voidlinux/void-packages#5195]
grep  CONFIG_MMC_REALTEK_USB  /boot/config-4.8.7_1 
    # CONFIG_MMC_REALTEK_USB is not set

Please read forum thread for more information: 
https://forum.voidlinux.eu/t/realtek-rts5129-sd-card-reader-support/1348/6

**Comment by chneukirchen** [comment]
Let's try to think of this for the next bumps.
