### ISSUE TITLE
easier steam x86_64 install

### ISSUE THREAD

**Issue by aeosynth** [voidlinux/void-packages#5229]
can steam on x86_64 include the 32 bit dependencies? i would like to install without having to check the wiki.

edit: or have a `steam-runtime` package with the deps

**Comment by whitephoenix0** [comment]
Additional info can be found in #4239

**Comment by thypon** [comment]
Duplicate

**Comment by nonchip** [comment]
@whitephoenix0 the issue you referenced has actually nothing to do with 32bit libs, but with broken intel drivers.

@thypon it'd help to know of what exactly this issue is a duplicate. also maybe `wontfix` is the wrong label for dupe-closing?
