### ISSUE TITLE
gcc: package has files which should be in gcc-go

### ISSUE THREAD

**Issue by ackalker** [voidlinux/void-packages#5246]
Checking out the new `gcc` package (thanks for updating btw!), I found that it contains files which I think should be in package `gcc-go`:
```
/usr/lib/libnetgo.a
/usr/lib/libgolibbegin.a
```
OTOH, there seem to be two files missing from `gcc-go`:
```
/usr/lib/libgo.a
/usr/lib/libgobegin.a
```
Please compare this with Arch Linux's [`gcc-go` package filelist](https://www.archlinux.org/packages/core/x86_64/gcc-go/).

**Comment by ebfe** [comment]
#5245
