### ISSUE TITLE
chromium-pepper-flash : broken

### ISSUE THREAD

**Issue by arete** [voidlinux/void-packages#5249]
I try to install chromium-pepper-flash 23.0.0.162_5 on glibc x64,
but have this error message

Certificate issuer: /C=US/O=Google Inc/CN=Google Internet Authority G2
requesting https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stab
le/google-chrome-stable_54.0.2840.100-1_amd64.deb
chromium-pepper-flash.deb: 43MB [avg rate: 697KB/s]
chromium-pepper-flash.deb: OK
mv: impossibile eseguire stat di './var/tmp/chromium-pepper-flash.build/opt/goog
le/chrome/PepperFlash/libpepflashplayer.so': File o directory non esistente
mv: impossibile eseguire stat di './var/tmp/chromium-pepper-flash.build/opt/goog
le/chrome/PepperFlash/manifest.json': File o directory non esistente
chromium-pepper-flash-23.0.0.162_5: post-install message:

**Comment by ackalker** [comment]
Chromium PPAPI Flash plugin [is no more](https://blog.google/products/chrome/flash-and-chrome/). Chrome (and _only_ Chrome!) users can 'update' it from `about://components`, which seems to indicate that it is more tightly integrated with Chrome (for the time being) and cannot be easily extracted anymore.
Please try `freshplayerplugin` package, it should (in theory) work with both Chromium and Firefox.

**Comment by Duncaen** [comment]
There are ppapi builds for linux from adobe http://labs.adobe.com/downloads/flashplayer.html but currently beta and only tarballs without versions.

**Comment by ackalker** [comment]
Indeed, the reason I referred to the Ubuntu package is that it downloads and installs the Adobe binaries as part of package installation, something which could be useful for Void Linux as well.

**Comment by thypon** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pepper-flash

**Comment by ebfe** [comment]
1c9c23bfae1d2f486621ff9a4a4af374f5125c9f

**Comment by ackalker** [comment]
Thanks!
