### ISSUE TITLE
qt5 / qtcreator: error stdlib.h: no such file or directory

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5254]
In my Qt5 projects I now see this error when they for example contain `#include <QImage>`.
The sequence of includes then is:
```
In file included from /usr/include/c++/6.2/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6.2/algorithm:62,
                 from /usr/include/qt5/QtCore/qglobal.h:88,
                 from /usr/include/qt5/QtGui/qrgb.h:37,
                 from /usr/include/qt5/QtGui/qcolor.h:37,
                 from /usr/include/qt5/QtGui/qimage.h:37,
                 from /usr/include/qt5/QtGui/QImage:1,
                 from ../../qi/blit/blit.h:4,
                 from ../../qi/blit/blit.cpp:1:
/usr/include/c++/6.2/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
```

We have seen this error in other places and then fixed it by surrounding the `#include <stdlib.h>` with
```
#define _GLIBCXX_INCLUDE_NEXT_C_HEADERS
#include <stdlib.h>
#undef _GLIBCXX_INCLUDE_NEXT_C_HEADERS
```

In this case, however, it is not the application or qt5 headers where the error happens, but internally in c++ as it seems.

The file `/usr/include/c++/6.2/cstdlib` has this `#define` and `#undef` around the `#include <stdlib.h>` and yet it fails.

I seem to remember that some Qt5 package in the repo could be fixed by setting `QMAKE_CFLAGS_ISYSTEM=` i.e. setting it to an empty string. It can't be right to have to do this for every project, so perhaps it should become the default in qt5.

And indeed, adding a line `QMAKE_CFLAGS_ISYSTEM=` to my main `config.pri` file for unix solves the problem.

Any suggestions or links to how other distros handle(d) this are welcome.
The question is, whether qt5 itself should set `QMAKE_CFLAGS_ISYSTEM=` in its profiles.

**Comment by ebfe** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

Related: https://bugs.webkit.org/show_bug.cgi?id=161697

**Comment by ebfe** [comment]
webkit fix: https://trac.webkit.org/changeset/205672/trunk/Source/cmake/OptionsCommon.cmake

**Comment by pullmoll** [comment]
For reference: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/Q5SWCUUMWQ4EMS7CU2CBOZHV3WZYOOTT/

**Comment by pullmoll** [comment]
The error message persists even with the now correct gcc6.2.1 include paths.
Removing the last path `/usr/include` from the file `/usr/lib/qt5/mkspecs/qconfig.pri` line `QMAKE_DEFAULT_INCDIRS = ...` solves the issue.

I wonder if I should do yet another revbump for qt5-5.6.2 or try to update to qt5-5.7.0 and fix it there, if it's still an issue.

**Comment by pullmoll** [comment]
See https://build.voidlinux.eu/changes/33152

**Comment by pullmoll** [comment]
Sadly the issue is back with qt5-5.7.1
The `sed` does not work, because `/usr/lib/qt5/mkspecs/qconfig.pri` no longer contains the `QMAKE_DEFAULT_INCDIRS` variable.

Need to find the new place where it's set or where else the `-isystem /usr/include` causing this bug comes from.

**Comment by ebfe** [comment]
FWIW, even before the update (and after the fix) several cross builds sti failed with the sllame error. For example:

https://build.voidlinux.eu/builders/aarch64-musl_builder/builds/3036/steps/shell_3/logs/stdio
https://build.voidlinux.eu/builders/armv6l_builder/builds/29973/steps/shell_3/logs/stdio
https://build.voidlinux.eu/builders/aarch64-musl_builder/builds/3032/steps/shell_3/logs/stdio

So whatever the solution is for `/usr/include`, it probably should be applied to `${XBPS_CROSS_BASE}/usr/include` too.

**Comment by pullmoll** [comment]
The root cause of the problem is, as far as I understand the comments related to it, the sequence or order of `-isystem` includes. If `-isystem /usr/include` was the first, or at least before the `-isystem` for the `libstdc++` header file `<cstdlib>`, things should work.

I'll try to remove `-isystem` and see if this fixes my problem and makes the packages you listed cross compile.

And who knows, perhaps gcc6.3 (#5400) also fixes the problem.

**Comment by pullmoll** [comment]
The problem persists with gcc-6.3.0. If time permits, I'll take a closer look into the qt5-5.7.1 installed `*.pri` and `*.prf` files to identify the one causing the `-isystem ${XBPS_CROSS_BASE}/usr/include`.

**Comment by skyhisi** [comment]
I'm getting a similar error trying to compile Qt 5.9.1 on Fedora 26
```
g++ -pipe -O2 -fPIC -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -fno-exceptions -Wall -W -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -D_REENTRANT -DQT_NO_CAST_FROM_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_INPUT_SUPPORT_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_DEVICEDISCOVERY_SUPPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Ishared -Ishared -I../../../include -I../../../include/QtInputSupport -I../../../include/QtInputSupport/5.9.1 -I../../../include/QtInputSupport/5.9.1/QtInputSupport -I../../../include/QtGui/5.9.1 -I../../../include/QtGui/5.9.1/QtGui -I../../../include/QtDeviceDiscoverySupport -I../../../include/QtDeviceDiscoverySupport/5.9.1 -I../../../include/QtDeviceDiscoverySupport/5.9.1/QtDeviceDiscoverySupport -I../../../include/QtCore/5.9.1 -I../../../include/QtCore/5.9.1/QtCore -I../../../include/QtGui -I../../../include/QtCore -I.moc -isystem /usr/include/libdrm -isystem /usr/include -I../../../mkspecs/linux-g++ -x c++-header -c ../../corelib/global/qt_pch.h -o .pch/Qt5InputSupport.gch/c++
In file included from /usr/include/c++/7/bits/stl_algo.h:59:0,
                 from /usr/include/c++/7/algorithm:62,
                 from ../../../include/QtCore/../../src/corelib/global/qglobal.h:109,
                 from ../../../include/QtCore/qglobal.h:1,
                 from ../../corelib/global/qt_pch.h:56:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
```

**Comment by machinekoder** [comment]
We had a similar error with QtQuickVcp and fixed it by adding a gcc version dependent qmake command:
https://github.com/qtquickvcp/QtQuickVcp/blob/master/paths.pri#L56-L63

**Comment by machinekoder** [comment]
Just in case someone wants to fix it in Qt.
