### ISSUE TITLE
Gdb again (please don't block me, it's genuine!)

### ISSUE THREAD

**Issue by raimundomartins** [voidlinux/void-packages#5280]
Here it is after system update instead of just gdb and readline:

```
13:14:30 raimundo@yamtech:~$ sudo xbps-install -Syu
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
13:14:33 raimundo@yamtech:~$ sudo xbps-install gdb
gdb-7.9_1: broken, unresolvable shlib `libreadline.so.6'
Transaction aborted due to unresolved shlibs.
13:14:40 raimundo@yamtech:~$
```
FYI I didn't do system update before because subversion was broken (old sqlite3 version). But I did update package listing so, after that, installing gdb would update the required packages. Seriously? The manual? -.-
If you don't like the new thread, don't block me so fast. It's not a RTFM issue, I've been using void for more than 2 years now...

**Comment by Duncaen** [comment]
You had to do the full system upgrade, there are other packages that depend on `readline`.
The `gdb` in the official repository depends on `libreadline.so.7`, I guess you have a local repositiroy with higher priority than the remote ones, remove/update the gdb package there.
Or add `bestmatching=true` to the xbps configuration to choose packages with the highest version.

**Comment by raimundomartins** [comment]
There! Ok, wasn't that much better than just closing? I had to make a custom gdb to have python-bindings, but it was so long ago that I didn't remember anymore.
And system update doesn't do anything, all I had was qt5 packages, subversion (for the reason already mentioned) and python. I had the ysstem updated yesterday. The most important is the index. After that dependencies come along.
