### ISSUE TITLE
Installation of nvidia340 fails after gcc and kernel upgrade

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#5287]
After updating one of my computers to gcc-6.2 and linux-4.8.12_1, the dkms hook executed during the kernel installation failed with the following error message:

```
gcc-version-check failed:

The compiler used to compile the kernel (gcc
4.9) does not exactly match the current compiler
(gcc 6.2).  The Linux 2.6 kernel module loader
rejects kernel modules built with a version of gcc
that does not exactly match that of the compiler
used to build the running kernel.
```

I first wondered if linux-4.8.12_1 had really still been built with gcc-4.9 but since it was commited to git after the migration to gcc-6.2, it should have been built with gcc-6.2. And indeed, after manually creating the initrd image with dracut, I was able to boot into linux-4.8.12_1 and manually call dkms to compile the desired kernel module (nvidia in my case).

After running dkms with strace, it seems that dkms takes the gcc version from /proc/version which of course shows the gcc version used to build the currently running kernel (4.8.11_1 in my case) and not the gcc version used to build the kernel being installed.

This creates the situation where one has to first install a new kernel version after a gcc upgrade, reboot into the new kernel version (losing whatever functionality is provided by the kernel module installed via dkms) and then trigger the module installation via dkms manually.

**Comment by pullmoll** [comment]
The change of compiler versions won't happen often, so we can take your experience for users having problems with dkms after an update. Perhaps you can devise a Wiki entry from your observations?

**Comment by Hoshpak** [comment]
I will do so once I've got th time to do it. Another curious thing is that this issue only occurred on i686. I updated two more machines in the meantime, bot x86_64. Both built the kernel modules during the update process without complaining.

So this seems to be an issue specific to i686, possibly a subtle difference in the kernel version string or something like that. Since dkms will happily build kernel modules with a newer gcc version than the kernel it is building for was built with if a kernel is booted that has been built with the newer gcc version, the gcc version check in dkms seems to make no sense at all.

**Comment by Hoshpak** [comment]
After looking closer into it once more, the issue isn't architecture specific and also no general dkms issue. The machine in question not only runs the i686 version but also uses the nvidi340 legacy driver due to the relatively old GPU chipset. The nvidia340 source code contains the file "gcc-version-check.c" which parses the /proc/version string passed to it and produces the error message. The current version of the nvidia driver doesn't contain this file. So only people using the nvidia340 legacy driver are affected.

**Comment by pullmoll** [comment]
Then it's rather a bug of that (old) driver and may be fixed there, i.e. rip that version check out.
I doubt that many people will be affected by this issue, though.

**Comment by Hoshpak** [comment]
I agree, the file is only present in the nvidia340 and nvdidia304 dkms sources so it shouldn't affect many users if anyone but me ran into this at all.
