### ISSUE TITLE
buildbots fail to connect to https://repo.voidlinux.eu/distfiles

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5289]
After updating `avr-gcc` to `6.2.1` some buildbots fail to download the file `https://repo.voidlinux.eu/distfiles/gcc-6.2.1.tar.xz`. See https://build.voidlinux.eu/builders/x86_64_builder/builds/28227/steps/shell_3/logs/stdio

For now I set these arches to `broken=...`. If the reason for this hiccup is solved, the packages `avr-gcc` and `avr-libc` can be enabled again.

**Comment by Gottox** [comment]
Worked around. I'm going to fix this by the planned server movement.
