### ISSUE TITLE
Package request: Kea

### ISSUE THREAD

**Issue by jsumners** [voidlinux/void-packages#5293]
Kea is the next generation of ISC's DHCPd server. It is currently at a usable 1.1.0 release.

http://kea.isc.org/wiki

**Comment by pullmoll** [comment]
The package is available. LMK if it works for you.

**Comment by jsumners** [comment]
Looking good so far. A couple notes:

1. It depends on `/var/run/kea/` to exist so that it can create lock files
2. It depends on `/var/kea/` to exist to generate pid files
3. It might be a good idea to patch the default config to set the logger types to `stdout`. Although, anyone using this package probably has the knowledge to solve this, so it's not super important

1 and 2 are breaking issues in my opinion.

**Comment by pullmoll** [comment]
Ok, I think it should be ok to create `/var{,run/}kea` in the service `run` files.
I'll take a look at patching `kea.conf` in `post_install()`.
Do you think we should create a user `kea:kea` and use `chpst` to run the server(s)?

**Comment by jsumners** [comment]
I don't see anything in the user guide (http://kea.isc.org/docs/kea-guide.html) that indicates it supports running as anyone other than root. I would certainly prefer it to drop privileges once it binds the port, but I don't think the software is there yet....

Yep, looks like there is an open ticket regarding the issue -- http://kea.isc.org/ticket/3423

So, for now, there is no need for the `kea:kea` user/group.

**Comment by pullmoll** [comment]
Your suggested fixes are in 1.1.0_3, so please take a look again and, if it everything is all right, close this issue.

**Comment by jsumners** [comment]
I have just noticed that it hasn't been linked with PostgreSQL or MySQL (PostgreSQL being my preference). Can this be done?

**Comment by pullmoll** [comment]
I [asked in the PR](https://github.com/pullmoll/void-packages/commit/cdb85eb888f145ac0f05d0883e2323ab764ed8cd) if either postgresql or mysql should be enabled by default. Since I didn't receive a review or a comment, I decided to merge the PR after a couple of days. I can enable postgresql by default.

**Comment by jsumners** [comment]
Sorry, I didn't see the note in the PR. GitHub didn't send me any notifications of this issue being updated until you said the package is available.

**Comment by pullmoll** [comment]
No problem. I'll add that change as time permits. Currently I'm a little busy :)

**Comment by jsumners** [comment]
Thank you. I appreciate all of the assistance.

**Comment by pullmoll** [comment]
You may be the first to enjoy kea pkg, but certainly no the last one.
I for one enjoyed the fun here :)

**Comment by jsumners** [comment]
Was finally able to install the latest version and try it against a postgres database. It's working great.
