### ISSUE TITLE
Update system for python3-requests failed.

### ISSUE THREAD

**Issue by tom-i** [voidlinux/void-packages#5298]
Hi,
I have small issue with updating system which contains **python3-requests** lib.

`......`
`freetype-devel-2.7_3: unpacked file './usr/lib/libfreetype.a' (1053968 bytes)`
`freetype-devel-2.7_3: unpacked file './usr/lib/libfreetype.so' (0 bytes)`
`python3-requests-2.12.1_1: updating to 2.12.3_1 ...`
`Removing byte-compiled python3.5 code for module requests...`
`Updating ldconfig(8) cache...`
`python3-requests-2.12.3_1: unpacking ...`
`python3-requests-2.12.3_1: unpacked file './usr/lib/python3.5/site-packages/requests/packages/chardet' (0 bytes)`
`python3-requests-2.12.3_1: unpacked file './usr/lib/python3.5/site-packages/requests/packages/urllib3' (0 bytes)`
`ERROR: python3-requests-2.12.3_1: [unpack] failed to extract file './usr/lib/python3.5/site-packages/requests/packages/idna': Directory not empty`
`ERROR: python3-requests-2.12.3_1: [unpack] failed to extract files: Directory not empty`
`ERROR: python3-requests-2.12.3_1: [unpack] failed to unpack files from archive: Directory not empty`

Is it problem on my side or package side? Or should I remove that directory manually?
Thank you very much.
Tom

**Comment by Duncaen** [comment]
https://github.com/voidlinux/xbps/issues/220
