### ISSUE TITLE
Debugging g++ for musl build of simgear

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5299]
It may be interesting to find out why compiling `simgear` file `particles.cxx` makes g++ fail with a segfault and thus internal compiler error. The function which causes this is appendParticles() and is rather big.

I don't know exactly how to debug g++ trying to compile this file. I guess installing gdb in the chroot (via hostmakedepends?) and finding the exact command line used to invoke g++ would be required.

Perhaps someone else feels inclined to take a look. It may result in finding a tight stack size issue (remember: musl) in g++ itself, which could cause headaches in the future.

**Comment by ebfe** [comment]
@ackalker posted some interesting snippets/tools to debug (build) issues someplace i can't remember now.

**Comment by ackalker** [comment]
@pullmoll @ebfe Perhaps you could use [Bear](https://github.com/voidlinux/void-packages/pull/5180/commits/25a6c445d80f7f4ffd698ca9432152876a16b6d0),
Just add `make_cmd="bear make"` to the template, then build the package. This will create a file `compile_commands.json` in the build directory with the compile commands and arguments.

**Comment by ackalker** [comment]
Ah, so this is a CMake build. CMake has built-in support for generating compilation databases. In this case I think you need to add `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to `configure_args`, haven't tested it myself.

**Comment by pullmoll** [comment]
I got distracted by qt-5.7.1 update and now gcc-6.3.0. I'll see if the official gcc fixes the problem.

**Comment by pullmoll** [comment]
The coming update to simgear-2016.4.4 and/or the update to gcc-6.3.0 fixed the problem.
