### ISSUE TITLE
Unable to find "fdm" in the repository pool

### ISSUE THREAD

**Issue by mmmmarascio** [voidlinux/void-packages#5349]
I wish to install the package of fdm[*].  But `sudo xbps-install -S fdm` fails and prints the message "Unable to find 'fdm' in the repository pool."  `sudo xbps-query -R fdm` seems to fail too, since there is no output and the return value is 2.  Both failures are unexpected because `sudo xbps-install -S msmtp` successfully installs the msmtp package and `sudo xbps-query -R msmtp` displays information about the package.

I'm new to Void Linux.  I could build and install fdm manually, but I'd like to install the package.  Assuming that what I describe is unexpected, what can I do to help fix the problem?

[*]: <https://github.com/voidlinux/void-packages/tree/eca0f2e6a8f88606d931542bde9fadff87e8de06/srcpkgs/fdm>

**Comment by Vaelatern** [comment]
What is your architecture and libc?

**Comment by Vaelatern** [comment]
most likely you should clone void-packages and do `./xbps-src pkg fdm`

**Comment by mmmmarascio** [comment]
@Vaelatern: architecture: x86; libc: musl

**Comment by chneukirchen** [comment]
Fixed by 3b7aea6.
