### ISSUE TITLE
Package request: python-evic

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5372]
I'm not good at packaging Python tools and that's why I ask for a favor. The project page is https://github.com/Ban3/python-evic

python-evic requires [cython-hidapi](https://github.com/trezor/cython-hidapi). An AUR package for [cython-hidapi is here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-cython-hidapi-git).

Both packages don't have releases so only a git revision snapshot could be used. For python-evic:
```shell
# Template for 'python-evic'
pkgname=python-evic
version=0.0.0.20161101
revision=1
_gitrev=176cf0b076db331cf79dcab4232abd1158b183fa
wrksrc="${pkgname}-${_gitrev}"
…
distfile="https://github.com/Ban3/python-evic/archive/${_gitrev}.tar.gz>${pkgname}-${version}.tar.gz"
checksum=d3275ef8fa4b30211b0e81d4317251ddcd699be0d02a978a2c5cc7edbd6a84a9
```

And for cython-hidapi:
```shell
# Template for 'cython-hidapi'
pkgname=cython-hidapi
version=0.0.0.20161031
revision=1
_gitrev=0a9068df8d2fcdb1009f7644d1b4686cd5d9fd61
wrksrc="${pkgname}-${_gitrev}"
…
distfile="https://github.com/trezor/cython-hidapi/archive/${_gitrev}.tar.gz>${pkgname}-${version}.tar.gz"
checksum=c0a3bcfd603650d431f541483c7db23a07fcb7ead3afe048ace91db424ecf7cb
```

**Comment by ebfe** [comment]
Back to tobacco?

**Comment by pullmoll** [comment]
Nope. One update done in a VirtualBox environment.
