### ISSUE TITLE
Thunar crashing on renaming a file

### ISSUE THREAD

**Issue by Piraty** [voidlinux/void-packages#5395]
issue: thunar crashes, when it renames a file. (sometimes it even crashes on moving a file, but i don't know yet if that is related)

I found this bahivour quite annoying for a while now, and i looked it up in the xfce-bugzilla.
I found this: https://bugzilla.xfce.org/show_bug.cgi?id=12264
They seem to have succesfully patched it with this patch: https://bugzilla.xfce.org/show_bug.cgi?id=12264#c112 (see attachment #6779).
Testing was done in debian, so it remains to be tested for void.

When i have more time, i will try to implement this patch and test it.

**Comment by pullmoll** [comment]
The most recent comments in that thread suggest that this patch introduces a new problem: Thunar hangs when accessing a non-existent directory, e.g. an (empty) USB drive.

Unless a patch makes it into the upstream source, we should not try to add deep changes like this. Even though Thunar annoyed myself for the exact same reasons over the recent months, I would not approve such a change.

My solution: Don't use Thunar to rename files :) There's `mv` and even `mmv`.

**Comment by Piraty** [comment]
I got your point. I will still try to apply the patch on my machine, to see if the usb issue can be veryfied.

**Comment by pullmoll** [comment]
I [applied](https://build.voidlinux.eu/changes/33954) one patch [I found here](http://tuxdiary.com/2016/06/10/fix-thunar-crash-move-rename/) now. This doesn't seem to be everything that needs a fix, but should be an improvement AFAICT.

**Comment by Piraty** [comment]
Thank you. I just randomly renamed files and did not experience a crash.

**Comment by Piraty** [comment]
well, i was just about to report some new crash scenarios, when today's update of thunar came along.
changelog states the crash issues to be fixed.
