### ISSUE TITLE
when xbps-src extract package contains open-iscsi, it would be fail then clean..

### ISSUE THREAD

**Issue by PopoBear** [voidlinux/void-packages#5397]
Example  -> when I extract libvirt and deps open-iscsi in template

$./xbps-src extract libvirt

   [runtime] ebtables>=0: found ebtables-2.0.10.4_7 (/host/binpkgs)
   [runtime] dnsmasq>=0: found dnsmasq-2.76_1 (/host/binpkgs)
=> libvirt-2.3.0_1: installing host dependency 'automake-1.15_4' ...
=> libvirt-2.3.0_1: installing host dependency 'libtool-2.4.6_1' ...
=> libvirt-2.3.0_1: installing host dependency 'perl-5.24.0_4' ...
=> libvirt-2.3.0_1: installing host dependency 'pkg-config-0.29.1_2' ...
=> libvirt-2.3.0_1: installing host dependency 'lvm2-2.02.168_1' ...
=> libvirt-2.3.0_1: installing host dependency 'parted-3.2_5' ...
=> libvirt-2.3.0_1: installing host dependency 'gettext-devel-0.19.8.1_3' ...
=> libvirt-2.3.0_1: installing host dependency 'iptables-1.6.0_2' ...
=> libvirt-2.3.0_1: installing host dependency 'libxslt-1.1.29_2' ...
=> libvirt-2.3.0_1: installing host dependency 'docbook-xsl-1.79.1_1' ...
=> libvirt-2.3.0_1: installing host dependency 'dnsmasq-2.76_1' ...
=> libvirt-2.3.0_1: installing target dependency 'readline-devel-7.0.000_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libcap-ng-devel-0.7.8_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libnl3-devel-3.2.28_2' ...
=> libvirt-2.3.0_1: installing target dependency 'attr-devel-2.4.47_6' ...
=> libvirt-2.3.0_1: installing target dependency 'gnutls-devel-3.4.17_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libsasl-devel-2.1.26_5' ...
=> libvirt-2.3.0_1: installing target dependency 'libcurl-devel-7.51.0_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libpcap-devel-1.8.1_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libxml2-devel-2.9.4_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libparted-devel-3.2_5' ...
=> libvirt-2.3.0_1: installing target dependency 'device-mapper-devel-2.02.168_1' ...
=> libvirt-2.3.0_1: installing target dependency 'dbus-devel-1.10.14_1' ...
=> libvirt-2.3.0_1: installing target dependency 'eudev-libudev-devel-3.2.1_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libblkid-devel-2.28.2_3' ...
=> libvirt-2.3.0_1: installing target dependency 'libpciaccess-devel-0.13.4_2' ...
=> libvirt-2.3.0_1: installing target dependency 'avahi-libs-devel-0.6.32_3' ...
=> libvirt-2.3.0_1: installing target dependency 'polkit-devel-0.113_2' ...
=> libvirt-2.3.0_1: installing target dependency 'yajl-devel-2.1.0_3' ...
=> libvirt-2.3.0_1: installing target dependency 'python-devel-2.7.13_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libssh2-devel-1.8.0_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libcap-ng-devel-0.7.8_2' ...
=> libvirt-2.3.0_1: installing target dependency 'fuse-devel-2.9.7_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libtirpc-devel-0.3.2_4' ...
=> libvirt-2.3.0_1: installing target dependency 'libnfs-devel-1.11.0_1' ...
=> libvirt-2.3.0_1: installing target dependency 'open-iscsi-2.0.874_1' ...
/void-packages/common/xbps-src/shutils/build_dependencies.sh: line 66: 27465 Segmentation fault      $XBPS_INSTALL_CMD -Ayd "$pkg" > $tmplogf 2>&1
=> libvirt-2.3.0_1: removing autodeps, please wait...

**Then I found log in libvirt 

cat masterdir/builddir/.xbps-libvirt/xbps_x86_64_bdep_open-iscsi-2.0.874_1.log**

[DEBUG] libisns-0.97_1: file ./usr/lib/libisns.so.0 matches existing SHA256, skipping...
[DEBUG] libisns-0.97_1: updated file timestamps to ./usr/lib/libisns.so.0
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsistart.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsistart.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsiuio.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsiuio.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsiadm.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsiadm.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsi_discovery.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsi_discovery.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsid.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsid.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/man/man8/iscsi-iname.8 matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/man/man8/iscsi-iname.8
[DEBUG] open-iscsi-2.0.874_1: file ./usr/share/examples/open-iscsi/iface.example matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/share/examples/open-iscsi/iface.example
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsid matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsid
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsiuio matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsiuio
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsistart matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsistart
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsi_discovery matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsi_discovery
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsi-iname matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsi-iname
[DEBUG] open-iscsi-2.0.874_1: file ./usr/bin/iscsiadm matches existing SHA256, skipping...
[DEBUG] open-iscsi-2.0.874_1: updated file timestamps to ./usr/bin/iscsiadm
[DEBUG] open-iscsi-2.0.874_1: processing conf_file ./etc/iscsi/initiatorname.iscsi
[DEBUG] => ERROR: Please see above for the real error, exiting...

since  ./etc/iscsi/initiatorname.iscsi no here cause xbps-src fail ?

any idea ?

**Comment by PopoBear** [comment]
the same ..
when I xbps-src extract qemu make deps open-iscsi
it's fail too...

open-iscsi has conf_file contain /etc/iscsi/initiatorname.iscsi
but xbps-src can't process correctly when file is not exist ?

**Comment by PopoBear** [comment]
Since I resolve #5401  issue .
I try to add open-iscsi again 

makedepends="readline-devel libcap-ng-devel libnl3-devel attr-devel
 gnutls-devel libsasl-devel libcurl-devel libpcap-devel libxml2-devel
 libparted-devel device-mapper-devel dbus-devel eudev-libudev-devel libblkid-devel
 libpciaccess-devel avahi-libs-devel polkit-devel yajl-devel
 python-devel libssh2-devel libcap-ng-devel fuse-devel libtirpc-devel open-iscsi"
depends="ebtables dnsmasq open-iscsi"


I also fail 

=> libvirt-2.3.0_3: installing target dependency 'open-iscsi-2.0.874_1' ...
/void-packages/common/xbps-src/shutils/build_dependencies.sh: line 66:  4842 Segmentation fault      $XBPS_INSTALL_CMD -Ayd "$pkg" > $tmplogf 2>&1
=> libvirt-2.3.0_3: removing autodeps, please wait...
=> ERROR: libvirt-2.3.0_3: failed to install 'open-iscsi-2.0.874_1' dependency! (error 139)
[DEBUG] XBPS: 0.51 API: 20151030 GIT: UNSET

**Comment by ebfe** [comment]
This is fixed in voidlinux/xbps#148, maybe we should make a release sometime...

**Comment by PopoBear** [comment]
This is fixed in voidlinux/xbps#148, maybe we should make a release sometime...

fortunately, libvirt open-iscsi support doesn't need open-iscsi package to makedeps.

because libvirt is auto check iscsi package.


But ! qemu must makedeps open-iscsi package .
this issue cause Qemu can't support iscsi function, unfortunately.....

when to update this fix ?

**Comment by ebfe** [comment]
cc @xtraeme

**Comment by PopoBear** [comment]
I saw all the xbps package source code try to solve this issue .

Now, in our git tree, xbps version is 0.51

when ./xbps-src extract xbps

I can't see newest diff patch code.

maybe we must wait the newest xbps release ?

**Comment by PopoBear** [comment]
That's my thinking ..

mybe someday , xbps have an option in template file which let user modify to choice ..

because i saw the wiki said, xbps just to fetch "release verison source code and patch" from github

maybe someday we have an option to choice "release or newest on github" to fetch and build..

It's very powerful to some advance user to easy modify code and rebuild package
won't need to patch and release code from github.

it's my sugesstion...

**Comment by PopoBear** [comment]
if #5405 Request finished ..
this issue can closed . or we kust want new xbps package & gcc 6.3 to release ..:-)
