### ISSUE TITLE
Request: update libvirt and deps.

### ISSUE THREAD

**Issue by PopoBear** [voidlinux/void-packages#5398]
Since VoidLinux upgrade Qemu 2.7 up to 2.8 today
May libvirt upgrade also?

libvirt  2.3
libvirt-devel 2.3
wants up to 2.5 release

libvirt-glib 0.2.3 
libvirt-glib-devel
libvirt-glib-python
libvirt-python

wants up to 1.1.0 release (this will change to 2.0.0 if no new release is made
during 2016)

**Comment by PopoBear** [comment]
maybe spice & spice-protocol also needs upgrade ?
just because gstreamer on qemu 2.8 has support H.264...

**Comment by Hoshpak** [comment]
I have submitted a pull request to update libvirt and the related packages to the current version. spice-protocol is already current, spice could be updated by a minor revision. While looking at the package, I noticed that it is currently built without gstreamer. If you are more familiar with the spice protocol, could you please explain what the benefits of building that package with gstreamer would be?

**Comment by maxice8** [comment]
Resolved on fc0635f8c1df5138bcdd69e48822ecb0b2711c4f

@the-maldridge
