### ISSUE TITLE
gcc 6.3

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#5400]
I think gcc 6.3 contains all fixes we have in our "6.2.1", so we could update to a proper release.

@pullmoll can you run a test build easily?

**Comment by pullmoll** [comment]
Not now, because tonite I'm out and currently some builds for qt5-5.7.1 are running here.

I can probably take a look tomorrow. On the other hand I think we should update to 6.3 anyway?

**Comment by pullmoll** [comment]
Compiling gcc6.3 for x86_64 in a bootstrap worked here. The patch set applies without change.
Now building the rest of base-chroot and a base-system to create a live ISO and try it in qemu.

If this succeeds and we update to 6.3, I think we also need to identify pkgs which store the path to (now) `/usr/lib/gcc/x86_64-unknown-linux/gnu/6.2` and rebuild them. Some of them have been rebuilt for 6.2.1 with a git commit message `xxx: rebuild for gcc6` while there are probably more.

**Comment by pullmoll** [comment]
Merry christmas everyone and a happy 6.3.0.

**Comment by pullmoll** [comment]
There's an _oops_ in the `srcpkgs/gcc/files/gcc-6.3.0-musl.diff` patch lines 140-151:
This adds a definition for MUSL_DYNAMIC_LINKER for aarch64, but the gcc-6.3.0 header file `gcc/config/aarch64/aarch64-linux.h` already has it defined one a couple of lines down.

To fix this, someone should remove those lines from the `gcc-6.3.0-musl.diff` file and revbump `gcc` and all `cross*musl*` packages. I'm away soon and probably won't be back to do it probably until Dec 26.
