### ISSUE TITLE
Bug: Rebuild libvirt package can't support iscsi

### ISSUE THREAD

**Issue by PopoBear** [voidlinux/void-packages#5401]
I was modified template above:

# Template file for 'libvirt'
pkgname=libvirt
version=2.3.0
revision=1
build_style=gnu-configure
configure_args="--without-hal --with-storage-lvm --with-qemu-user=libvirt
 --with-qemu-group=libvirt --without-netcf --with-interface --disable-static --with-storage-iscsi"
short_desc="The virtualization API for controlling virtualization engines"
maintainer="Juan RP <xtraeme@voidlinux.eu>"

I had already add --with-storage-iscsi for configure_args

when I execute command to rebuild from local

$./xbps-src -N pkg libvirt

when xbps-src execute ./configure , 
I saw Storage support iscsi  is opened

but, after rebuild package I install libvirt ...

xbps-install --repository=~/void-package/hostdir/binpkgs -yff libvirt

I used

 virsh pool-define virt-iscsi.xml

It told me:

Failed to define pool from virt-iscsi.xml
internal error: missing backend for pool type 5 (iscsi)

any idea ?

**Comment by PopoBear** [comment]
attach building log 

=> libvirt-2.3.0_1: removing autodeps, please wait...
=> libvirt-2.3.0_1: building ...
   [host] automake-1.15_4: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] perl-5.24.0_4: found (/host/binpkgs)
   [host] pkg-config-0.29.1_2: found (/host/binpkgs)
   [host] lvm2-2.02.168_1: found (/host/binpkgs)
   [host] parted-3.2_5: found (/host/binpkgs)
   [host] gettext-devel-0.19.8.1_3: found (/host/binpkgs)
   [host] iptables-1.6.0_2: found (/host/binpkgs)
   [host] libxslt-1.1.29_2: found (/host/binpkgs)
   [host] docbook-xsl-1.79.1_1: found (/host/binpkgs)
   [host] dnsmasq-2.76_1: found (/host/binpkgs)
   [target] readline-devel-7.0.000_1: found (/host/binpkgs)
   [target] libcap-ng-devel-0.7.8_2: found (/host/binpkgs)
   [target] libnl3-devel-3.2.28_2: found (/host/binpkgs)
   [target] attr-devel-2.4.47_6: found (/host/binpkgs)
   [target] gnutls-devel-3.4.17_1: found (/host/binpkgs)
   [target] libsasl-devel-2.1.26_5: found (/host/binpkgs)
   [target] libcurl-devel-7.51.0_2: found (/host/binpkgs)
   [target] libpcap-devel-1.8.1_1: found (/host/binpkgs)
   [target] libxml2-devel-2.9.4_2: found (/host/binpkgs)
   [target] libparted-devel-3.2_5: found (/host/binpkgs)
   [target] device-mapper-devel-2.02.168_1: found (/host/binpkgs)
   [target] dbus-devel-1.10.14_1: found (/host/binpkgs)
   [target] eudev-libudev-devel-3.2.1_1: found (/host/binpkgs)
   [target] libblkid-devel-2.28.2_3: found (/host/binpkgs)
   [target] libpciaccess-devel-0.13.4_2: found (/host/binpkgs)
   [target] avahi-libs-devel-0.6.32_3: found (/host/binpkgs)
   [target] polkit-devel-0.113_2: found (/host/binpkgs)
   [target] yajl-devel-2.1.0_3: found (/host/binpkgs)
   [target] python-devel-2.7.13_1: found (/host/binpkgs)
   [target] libssh2-devel-1.8.0_1: found (/host/binpkgs)
   [target] libcap-ng-devel-0.7.8_2: found (/host/binpkgs)
   [target] fuse-devel-2.9.7_1: found (/host/binpkgs)
   [target] libtirpc-devel-0.3.2_4: found (/host/binpkgs)
   [target] libnuma-devel-2.0.11_1: found (/host/binpkgs)
   [target] libnfs-devel-1.11.0_1: found (/host/binpkgs)
   [target] libisns-devel-0.97_1: found (/host/binpkgs)
   [target] bridge-utils-1.5_11: found (/host/binpkgs)
   [runtime] ebtables>=0: found ebtables-2.0.10.4_7 (/host/binpkgs)
   [runtime] dnsmasq>=0: found dnsmasq-2.76_1 (/host/binpkgs)
=> libvirt-2.3.0_1: installing host dependency 'automake-1.15_4' ...
=> libvirt-2.3.0_1: installing host dependency 'libtool-2.4.6_1' ...
=> libvirt-2.3.0_1: installing host dependency 'perl-5.24.0_4' ...
=> libvirt-2.3.0_1: installing host dependency 'pkg-config-0.29.1_2' ...
=> libvirt-2.3.0_1: installing host dependency 'lvm2-2.02.168_1' ...
=> libvirt-2.3.0_1: installing host dependency 'parted-3.2_5' ...
=> libvirt-2.3.0_1: installing host dependency 'gettext-devel-0.19.8.1_3' ...
=> libvirt-2.3.0_1: installing host dependency 'iptables-1.6.0_2' ...
=> libvirt-2.3.0_1: installing host dependency 'libxslt-1.1.29_2' ...
=> libvirt-2.3.0_1: installing host dependency 'docbook-xsl-1.79.1_1' ...
=> libvirt-2.3.0_1: installing host dependency 'dnsmasq-2.76_1' ...
=> libvirt-2.3.0_1: installing target dependency 'readline-devel-7.0.000_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libcap-ng-devel-0.7.8_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libnl3-devel-3.2.28_2' ...
=> libvirt-2.3.0_1: installing target dependency 'attr-devel-2.4.47_6' ...
=> libvirt-2.3.0_1: installing target dependency 'gnutls-devel-3.4.17_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libsasl-devel-2.1.26_5' ...
=> libvirt-2.3.0_1: installing target dependency 'libcurl-devel-7.51.0_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libpcap-devel-1.8.1_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libxml2-devel-2.9.4_2' ...
=> libvirt-2.3.0_1: installing target dependency 'libparted-devel-3.2_5' ...
=> libvirt-2.3.0_1: installing target dependency 'device-mapper-devel-2.02.168_1' ...
=> libvirt-2.3.0_1: installing target dependency 'dbus-devel-1.10.14_1' ...
=> libvirt-2.3.0_1: installing target dependency 'eudev-libudev-devel-3.2.1_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libblkid-devel-2.28.2_3' ...
=> libvirt-2.3.0_1: installing target dependency 'libpciaccess-devel-0.13.4_2' ...
=> libvirt-2.3.0_1: installing target dependency 'avahi-libs-devel-0.6.32_3' ...
=> libvirt-2.3.0_1: installing target dependency 'polkit-devel-0.113_2' ...
=> libvirt-2.3.0_1: installing target dependency 'yajl-devel-2.1.0_3' ...
=> libvirt-2.3.0_1: installing target dependency 'python-devel-2.7.13_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libssh2-devel-1.8.0_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libcap-ng-devel-0.7.8_2' ...
=> libvirt-2.3.0_1: installing target dependency 'fuse-devel-2.9.7_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libtirpc-devel-0.3.2_4' ...
=> libvirt-2.3.0_1: installing target dependency 'libnuma-devel-2.0.11_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libnfs-devel-1.11.0_1' ...
=> libvirt-2.3.0_1: installing target dependency 'libisns-devel-0.97_1' ...
=> libvirt-2.3.0_1: installing target dependency 'bridge-utils-1.5_11' ...
=> libvirt-2.3.0_1: running do-fetch hook: 00-distfiles ...
=> libvirt-2.3.0_1: running do-extract hook: 00-distfiles ...
=> libvirt-2.3.0_1: extracting distfile(s), please wait...
=> libvirt-2.3.0_1: running post-extract hook: 00-patches ...
=> libvirt-2.3.0_1: running pre-configure hook: 00-gnu-configure-asneeded ...
=> libvirt-2.3.0_1: running pre-configure hook: 01-override-config ...
=> libvirt-2.3.0_1: running pre-configure hook: 02-script-wrapper ...
=> libvirt-2.3.0_1: running pre_configure ...


blablablalbalba.........................


checking for qemu-bridge-helper... /usr/libexec/qemu-bridge-helper
checking whether to compile with macvtap support... yes
checking whether MACVLAN_MODE_PASSTHRU is declared... yes
checking whether to compile with virtual port support... yes
checking whether GET_VLAN_VID_CMD is declared... yes


blablablablaba..................


configure:
configure: Configuration summary
configure: =====================
configure:
configure: Drivers
configure:
configure:       Xen: no
configure:      QEMU: yes
configure:       UML: yes
configure:    OpenVZ: yes
configure:    VMware: yes
configure:      VBox: yes
configure:    XenAPI: no
configure:  xenlight: no
configure:       LXC: yes
configure:      PHYP: yes
configure:       ESX: yes
configure:   Hyper-V: no
configure:        vz: no
configure:     Bhyve: no
configure:      Test: yes
configure:    Remote: yes
configure:   Network: yes
configure:  Libvirtd: yes
configure: Interface: yes
configure:   macvtap: yes
configure:  virtport: yes
configure:
configure: Storage Drivers
configure:
configure:      Dir: yes
configure:       FS: no
configure:    NetFS: no
configure:      LVM: yes
configure:    iSCSI: yes
configure:     SCSI: yes
configure:    mpath: yes
configure:     Disk: yes
configure:      RBD: no
configure: Sheepdog: no
configure:  Gluster: no
configure:      ZFS: no
configure:
configure: Security Drivers
configure:
configure:  SELinux: no ()
configure: AppArmor: no (install profiles: no)
configure:
configure: Driver Loadable Modules
configure:
configure:   dlopen:  -ldl
configure:
configure: Libraries
configure:
configure:   apparmor: no
configure:       attr: yes (CFLAGS='' LIBS='-lattr')
configure:      audit: no
configure:      avahi: yes (CFLAGS='-D_REENTRANT' LIBS='-lavahi-common -lavahi-client')
configure:      blkid: yes (CFLAGS='-I/usr/include/blkid -I/usr/include/uuid' LIBS='-lblkid')
configure:      capng: yes (CFLAGS='' LIBS='-lcap-ng')
configure:       curl: yes (CFLAGS='-DCURL_DISABLE_TYPECHECK ' LIBS='-lcurl')
configure:       dbus: yes (CFLAGS='-I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include' LIBS='-ldbus-1')
configure:       fuse: yes (CFLAGS='-D_FILE_OFFSET_BITS=64 -I/usr/include/fuse' LIBS='-lfuse -pthread')
configure:  glusterfs: no
configure:        hal: no
configure:      netcf: no
configure:    numactl: yes (CFLAGS='' LIBS='-lnuma')
configure:  openwsman: no
configure:  pciaccess: yes (CFLAGS='' LIBS='-lpciaccess')
configure:   readline: yes (CFLAGS='' LIBS='-lreadline')
configure:    sanlock: no
configure:       sasl: yes (CFLAGS='' LIBS='-lsasl2')
configure:    selinux: no
configure:       ssh2: yes (CFLAGS='' LIBS='-lssh2')
configure:       udev: yes (CFLAGS='' LIBS='-ludev')
configure: wireshark_dissector: no
configure:        nss: yes
configure:       yajl: yes (CFLAGS='' LIBS='-lyajl')
configure:   libxml: -I/usr/include/libxml2 -lxml2
configure:   dlopen: -ldl
configure: openwsman: no
configure:   gnutls: -I/usr/include/p11-kit-1 -lgnutls
configure: firewalld: yes
configure:   polkit: /usr/sbin/pkcheck (version 1)
configure:      xen: no
configure:   xenapi: no
configure: xenlight: no
configure:     pcap: -I/usr/include -L/usr/lib  -lpcap
configure:       nl: -I/usr/include/libnl3 -I/usr/include/libnl3 -lnl-3 -lnl-route-3 -lnl-3
configure:    mscom: no
configure:      xdr:
configure:      rbd: no
configure: pm-utils: yes
configure:
configure: Test suite
configure:
configure:          Coverage: no
configure:         Alloc OOM: no
configure:
configure: Miscellaneous
configure:
configure:              Debug: yes
configure:        Use -Werror: no



configure:             DTrace: no
configure:              numad: no
configure:        XML Catalog: /etc/xml/catalog
configure:        Init script: none
configure:  Char device locks: /var/lock
configure:     Default Editor: vi
configure:       Loader/NVRAM:
configure:   virt-login-shell: yes
configure: virt-host-validate: yes
configure:       TLS priority: NORMAL
configure:
configure: Developer Tools
configure:
configure: Wireshark dissector: no
configure:
configure: Privileges
configure:
configure:       QEMU: libvirt:libvirt
configure:
=> libvirt-2.3.0_1: running pre-build hook: 02-script-wrapper ...
=> libvirt-2.3.0_1: running do_build ...
make  all-recursive
make[1]: Entering directory '/builddir/libvirt-2.3.0'
Making all in .
make[2]: Entering directory '/builddir/libvirt-2.3.0'
make[2]: Leaving directory '/builddir/libvirt-2.3.0'
Making all in gnulib/lib

**Comment by PopoBear** [comment]
and one more strange .

after build do install post .

there are two package missing ...

libvirt-admin doesn't on our void-linux package list ?

=> WARNING: libvirt-2.3.0_1: libvirt-admin.so.0 not found in common/shlibs!
=> WARNING: libvirt-2.3.0_1: libnss_libvirt.so.2 not found in common/shlibs!


=> libvirt-2.3.0_1: running post-install hook: 98-lib32 ...
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 03-rewrite-python-shebang ...
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 04-generate-runtime-deps ...
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 05-prepare-32bit ...
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 06-shlib-provides ...
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 90-set-timestamps ...
=> libvirt-devel-2.3.0_1: setting mtimes to Thu Dec 22 09:25:13 CST 2016
=> libvirt-devel-2.3.0_1: running pre-pkg hook: 99-pkglint ...
=> libvirt-2.3.0_1: running pre-pkg hook: 03-rewrite-python-shebang ...
=> libvirt-2.3.0_1: running pre-pkg hook: 04-generate-runtime-deps ...
   SONAME: libvirt.so.0 <-> libvirt-0.8.7_1 (ignored)
   SONAME: libnl-route-3.so.200 <-> libnl3>=3.2.1_1
   SONAME: libnl-3.so.200 <-> libnl3>=3.2.1_1
   SONAME: libnuma.so.1 <-> libnuma>=2.0.7_1
   SONAME: libavahi-common.so.3 <-> avahi-libs>=0.6.25_1
   SONAME: libavahi-client.so.3 <-> avahi-libs>=0.6.25_1
   SONAME: libdbus-1.so.3 <-> dbus-libs>=1.2.10_1
   SONAME: libcurl.so.4 <-> libcurl>=7.19_1
   SONAME: libutil.so.1 <-> glibc>=2.8_1
   SONAME: libcap-ng.so.0 <-> libcap-ng>=0.6.2_1
   SONAME: libyajl.so.2 <-> yajl>=2.0.1_1
   SONAME: libdevmapper.so.1.02 <-> device-mapper>=2.02.110_1
   SONAME: libxml2.so.2 <-> libxml2>=2.7.0_1
   SONAME: libssh2.so.1 <-> libssh2>=1.4.1_1
   SONAME: libsasl2.so.3 <-> libsasl>=2.1.26_1
   SONAME: libgnutls.so.30 <-> gnutls>=3.4.13_1
   SONAME: libdl.so.2 <-> glibc>=2.8_1
   SONAME: libpthread.so.0 <-> glibc>=2.8_1
   SONAME: libc.so.6 <-> glibc>=2.8_1
   SONAME: libblkid.so.1 <-> libblkid>=2.18_1
   SONAME: libpcap.so.1 <-> libpcap>=1.1.1_1
   SONAME: libudev.so.1 <-> libudev>=183_1
   SONAME: libfuse.so.2 <-> fuse>=2.8.1_1
   SONAME: libpciaccess.so.0 <-> libpciaccess>=0.10.5_1
   SONAME: libparted.so.2 <-> libparted>=3.1_1
   SONAME: libvirt-lxc.so.0 <-> libvirt-1.0.2_1 (ignored)
   SONAME: libvirt-qemu.so.0 <-> libvirt-0.8.7_1 (ignored)
   SONAME: libreadline.so.7 <-> readline>=7.0_1
   SONAME: libvirt-admin.so.0 <-> libvirt (ignored)
=> libvirt-2.3.0_1: running pre-pkg hook: 05-prepare-32bit ...
=> libvirt-2.3.0_1: running pre-pkg hook: 06-shlib-provides ...
   SONAME libvirt-admin.so.0 from /usr/lib/libvirt-admin.so.0.2003.0
   SONAME libnss_libvirt.so.2 from /usr/lib/libnss_libvirt.so.2
   SONAME libvirt.so.0 from /usr/lib/libvirt.so.0.2003.0
   SONAME libvirt-lxc.so.0 from /usr/lib/libvirt-lxc.so.0.2003.0
   SONAME libvirt-qemu.so.0 from /usr/lib/libvirt-qemu.so.0.2003.0
=> libvirt-2.3.0_1: running pre-pkg hook: 90-set-timestamps ...
=> libvirt-2.3.0_1: setting mtimes to Thu Dec 22 09:25:13 CST 2016
=> libvirt-2.3.0_1: running pre-pkg hook: 99-pkglint ...
=> WARNING: libvirt-2.3.0_1: libvirt-admin.so.0 not found in common/shlibs!
=> WARNING: libvirt-2.3.0_1: libnss_libvirt.so.2 not found in common/shlibs!
=> libvirt-devel-2.3.0_1: running do-pkg hook: 00-gen-pkg ...
=> libvirt-devel-2.3.0_1: skipping existing libvirt-devel-2.3.0_1.x86_64.xbps pkg...
=> libvirt-devel-2.3.0_1: running post-pkg hook: 00-register-pkg ...
=> Registering libvirt-devel-2.3.0_1.x86_64.xbps into /host/binpkgs ...
index: skipping `libvirt-devel-2.3.0_1' (x86_64), already registered.
index: 736 packages registered.
=> libvirt-2.3.0_1: running do-pkg hook: 00-gen-pkg ...
=> libvirt-2.3.0_1: skipping existing libvirt-2.3.0_1.x86_64.xbps pkg...
=> libvirt-2.3.0_1: running post-pkg hook: 00-register-pkg ...
=> Registering libvirt-2.3.0_1.x86_64.xbps into /host/binpkgs ...
index: skipping `libvirt-2.3.0_1' (x86_64), already registered.
index: 736 packages registered.
=> libvirt-2.3.0_1: removing autodeps, please wait...
=> libvirt-2.3.0_1: cleaning build directory...
=> libvirt: removing files from destdir...
=> libvirt-devel: removing files from destdir...

**Comment by ebfe** [comment]
```
but, after rebuild package I install libvirt ...

xbps-install --repository=~/void-package/hostdir/binpkgs -yff libvirt

I used

virsh pool-define virt-iscsi.xml
Failed to define pool from virt-iscsi.xml
internal error: missing backend for pool type 5 (iscsi)
```

Did you restart libvirtd after installing the rebuilt package?

**Comment by PopoBear** [comment]
Yes! 
I rebooted my server again and again ...

**Comment by PopoBear** [comment]
@ebfe 

Did you restart libvirtd after installing the rebuilt package?

Yes!
I rebooted my server again and again ...

**Comment by ebfe** [comment]
```
[...]
libvirt-2.3.0_1: skipping existing libvirt-2.3.0_1.x86_64.xbps pkg... 
[...]
```

Since you didn't increment version or revision the existing package will not be
replaced unless you pass `-f` to xbps-src. `xbps-src -f pkg libvirt`. Did you
compile it before without iscsi support?

**Comment by PopoBear** [comment]
Since you didn't increment version or revision the existing package will not be
replaced unless you pass -f to xbps-src. xbps-src -f pkg libvirt. Did you
compile it before without iscsi support?

Yes ... I compile it without iscsi support before .
I'm confused ...

every time I change template file and rebuild locally ,
does xbps-src will generate new .xpbs file to ~/void-package/hostdir/binpkgs ?

or, i must to change revision number then build ?

**Comment by ebfe** [comment]
> every time I change template file and rebuild locally ,
> does xbps-src will generate new .xpbs file to ~/void-package/hostdir/binpkgs ?

No, if a .xbps with the same version and revision already exists it will now be
overwritten by default.

> or, i must to change revision number then build ?

Either increment the revision or pass `-f` to xbps-src to force generating a
new .xbps. E.g. `./xbps-src -f pkg libvirt`.

Btw. your git tree seems to be a bit outdated. Current version for libvirt is 2.3.0_2.

**Comment by PopoBear** [comment]
My git tree is the newest .
because since last weekend , I heard Void-Linux is a greatful Linux distro.
I start to install it at 7 days ago..

then I found it , clean and easy to know ! 
Especially, the tool uses shell script to do every thing.
It's very wonderful.

So I do love it , after I study all the wiki and do myself for 5 days !

Void-Linux is really wonderful and greatful !!

OK ! I will change the revision or version number and build it again ...

thank you very much !

BTW, the revision = 1 , that's because i changed it today...(just try different revision to solve my question.)

**Comment by PopoBear** [comment]
Build it again .

after i change "revision" number 1 to 2 ...
the same result .....
it told me already registered....

=> Registering libvirt-devel-2.3.0_2.x86_64.xbps into /host/binpkgs ...
index: skipping `libvirt-devel-2.3.0_2' (x86_64), already registered.
index: 736 packages registered.
=> libvirt-2.3.0_2: running do-pkg hook: 00-gen-pkg ...
=> libvirt-2.3.0_2: skipping existing libvirt-2.3.0_2.x86_64.xbps pkg...
=> libvirt-2.3.0_2: running post-pkg hook: 00-register-pkg ...
=> Registering libvirt-2.3.0_2.x86_64.xbps into /host/binpkgs ...
index: skipping `libvirt-2.3.0_2' (x86_64), already registered.
index: 736 packages registered.
=> libvirt-2.3.0_2: removing autodeps, please wait...
=> libvirt-2.3.0_2: cleaning build directory...
=> libvirt: removing files from destdir...
=> libvirt-devel: removing files from destdir...

**Comment by ebfe** [comment]
As pointed out already, you need to pass `-f` to overwrite existing packages.

**Comment by ebfe** [comment]
Here's what i did to get iscsi working:

```diff
diff --git a/srcpkgs/libvirt/template b/srcpkgs/libvirt/template
index 8e7c32ac1f..9975ff0d0a 100644
--- a/srcpkgs/libvirt/template
+++ b/srcpkgs/libvirt/template
@@ -1,10 +1,10 @@
 # Template file for 'libvirt'
 pkgname=libvirt
 version=2.3.0
-revision=2
+revision=3
 build_style=gnu-configure
 configure_args="--without-hal --with-storage-lvm --with-qemu-user=libvirt
- --with-qemu-group=libvirt --without-netcf --with-interface --disable-static"
+ --with-qemu-group=libvirt --without-netcf --with-interface --with-storage-iscsi --disable-static"
 short_desc="The virtualization API for controlling virtualization engines"
 maintainer="Juan RP <xtraeme@voidlinux.eu>"
 homepage="https://libvirt.org"
@@ -22,8 +22,8 @@ makedepends="readline-devel libcap-ng-devel libnl3-devel attr-devel
  gnutls-devel libsasl-devel libcurl-devel libpcap-devel libxml2-devel
  libparted-devel device-mapper-devel dbus-devel eudev-libudev-devel libblkid-devel
  libpciaccess-devel avahi-libs-devel polkit-devel yajl-devel
- python-devel libssh2-devel libcap-ng-devel fuse-devel libtirpc-devel"
-depends="ebtables dnsmasq"
+ python-devel libssh2-devel libcap-ng-devel fuse-devel libtirpc-devel open-iscsi"
+depends="ebtables dnsmasq open-iscsi"

 case "$XBPS_TARGET_MACHINE" in
        i686*) configure_args+=" --without-xen"; makedepends+=" libnuma-devel";;
```

```
./xbps-src pkg libvirt
```

**Comment by PopoBear** [comment]
So, That's meaning something...
I never have to change revision number !
We just ./xbps-src -N -f pkg libvirt
Then xbps-src will foce rebuild and "force update" .xbps to binpkgs folder ?

right ?

now I change revision 2 -> 3 and force build again ..

but, I am still confused , when I modify the other sub deps package args,
I use -f to build main package ,
does sub package will force rebuild ?

**Comment by PopoBear** [comment]
OK!
That's it !
when I change revision 2 -> 3 
It's success !

now my package is newest , right ?


=> WARNING: libvirt-2.3.0_3: libvirt-admin.so.0 not found in common/shlibs!
=> WARNING: libvirt-2.3.0_3: libnss_libvirt.so.2 not found in common/shlibs!
=> libvirt-devel-2.3.0_3: running do-pkg hook: 00-gen-pkg ...
=> Creating libvirt-devel-2.3.0_3.x86_64.xbps for repository /host/binpkgs ...
=> libvirt-devel-2.3.0_3: running post-pkg hook: 00-register-pkg ...
=> Registering libvirt-devel-2.3.0_3.x86_64.xbps into /host/binpkgs ...
index: added `libvirt-devel-2.3.0_3' (x86_64).
index: 736 packages registered.
=> libvirt-2.3.0_3: running do-pkg hook: 00-gen-pkg ...
=> Creating libvirt-2.3.0_3.x86_64.xbps for repository /host/binpkgs ...
=> libvirt-2.3.0_3: running post-pkg hook: 00-register-pkg ...
=> Registering libvirt-2.3.0_3.x86_64.xbps into /host/binpkgs ...
index: added `libvirt-2.3.0_3' (x86_64).
index: 736 packages registered.
=> libvirt-2.3.0_3: removing autodeps, please wait...
=> libvirt-2.3.0_3: cleaning build directory...
=> libvirt: removing files from destdir...
=> libvirt-devel: removing files from destdir...

**Comment by PopoBear** [comment]
Dear .

Thank you very mush ..
It works !!

[popo@void ~]$ virsh pool-define virt-iscsi.xml
Pool virt-iscsi defined from virt-iscsi.xml

but i am still confused about after modify sub deps package , 
when we build main package , the sub package will rebuild again ?

**Comment by PopoBear** [comment]
the issue is closed!

but !

i have the other issue ... can you help me ?

https://github.com/voidlinux/void-packages/issues/5397

**Comment by ebfe** [comment]
Whenever you want to rebuild a modified package you either have to pass `-f` or increment the `revision` otherwise an existing .xbps won't be updated.

**Comment by PopoBear** [comment]
OK !

I am very clear to know !!

Than you very much !

I do love this distro which is not fork another linux distro..

It's easy to know and clean !!

all you guy is Genius!!!!!!!!!!!!!!!!!!!!!!!!!....

//clap
