### ISSUE TITLE
can anyone tell me what gir-freedesktop & gobject-introspection

### ISSUE THREAD

**Issue by PopoBear** [voidlinux/void-packages#5407]
what's diffrent with these two package ?

all the same makedeps with the other package ...

./xbps-src show-build-deps gobject-introspection
cairo
flex
glib
libffi
libtool
libxml2
pkg-config
python

./xbps-src show-build-deps gir-freedesktop
cairo
flex
glib
libffi
libtool
libxml2
pkg-config
python

**Comment by PopoBear** [comment]
But !
 why are they have diffrent file size ?!?!



what's diffrent with these two package ?

all the same makedeps with the other package ...

./xbps-src show-build-deps gobject-introspection
cairo
flex
glib
libffi
libtool
libxml2
pkg-config
python

./xbps-src show-build-deps gir-freedesktop
cairo
flex
glib
libffi
libtool
libxml2
pkg-config
python

**Comment by Vaelatern** [comment]
You are welcome to read the templates.

**Comment by Gottox** [comment]
See the packages description:
```
~ xbps-query -R -p short_desc gobject-introspection
Introspection system for GObject-based libraries
~ xbps-query -R -p short_desc gir-freedesktop      
Introspection data for some FreeDesktop components
```

**Comment by Vaelatern** [comment]
And to answer your question: They are the same template, used to build two packages.
