### ISSUE TITLE
btrfs-progs: update to 4.9 issue

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#5416]
OS: Void Linux x86_64, Kernel: Linux 4.9.0_3
maybe there's something wrong with btrfs-progs 4.9:

    btrfs subvolume list /

gives me

    btrfs: btrfs-list.c:116: btrfs_list_setup_print_column: Assertion `!(0 <= column && column <= BTRFS_LIST_ALL)' failed.

**Comment by ebfe** [comment]
> `!(0 <= column && column <= BTRFS_LIST_ALL)'

where does the `!` come from. Source is  `ASSERT(0 <= column && column <= BTRFS_LIST_ALL);` but the assertion is triggered when calling `btrfs_list_setup_print_column` with `column=BTRFS_LIST_OBJECTID` (=0).

**Comment by ebfe** [comment]
Looks like a recent changes to the BUG_ON/ASSERT macros broke the logic here
and potentially other places. Reverting to 4.8.5. Please file an upstream bug
report.

**Comment by ebfe** [comment]
Hmm, maybe not an upstream problem after all. 4.9 seems to work fine on other systems. Maybe compiler issue?

**Comment by ebfe** [comment]
Binaries built with our gcc outside of xbps-src also work, so something in our CFLAGS trigger the breakage.

**Comment by ebfe** [comment]
Upstream bug in the "--disable-backtrace" config.
