### ISSUE TITLE
package request: dialogbox

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#5429]
__dialogbox__
GUI widgets for shell scripts: https://github.com/martynets/dialogbox

> Introduction
> 
> The dialogbox application is a scriptable engine which provides a fully customizable GUI dialod box with various widgets. The desired dialog box is built and modified by commands read on the standard input when the end-user actions are reported on standard output. It implements the idea of a GUI <-> text filter tool.
> 
> The main purpose of this application is to provide GUI functionality to shell scripts or any other pure console applications capable to communicate with a child process via its standard input/output.
> 
> This is a Qt application and it introduces all the power of Qt to shell scripts from command buttons through stylesheets and animations.

**Comment by pullmoll** [comment]
See https://build.voidlinux.eu/changes/34188

I added patches to make it build qith Qt5 because we can cross compile with Qt5 but not with Qt4.
This way dialogbox could be used to write a GUI void-installer, if anyone wanted to do that.

**Comment by pullmoll** [comment]
I believe this can be closed. Please re-open otherwise.
