### ISSUE TITLE
Package request: acpi_call (& tpacpi-bat)

### ISSUE THREAD

**Issue by damadmai** [voidlinux/void-packages#5445]
Could you add [acpi_call](https://github.com/mkottman/acpi_call) so that it is not necessary to install it manually after each kernel update?
If it's not too much hassle please also consider adding [tpacpi-bat](https://github.com/teleshoes/tpacpi-bat)
See also http://www.thinkwiki.org/wiki/Tpacpi-bat <- includes [install.pl](https://github.com/teleshoes/tpacpi-bat/blob/master/install.pl) which does the installation of acpi_call.
Happy New Year!

**Comment by thypon** [comment]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/exfat-dkms/template follow this template and you can contribute the package yourself.
This is an example from archlinux aur repository https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=acpi_call-dkms :)

**Comment by asergi** [comment]
#3724
