### ISSUE TITLE
Linux command line Grub 2.02~beta3_3 adds slub_debug=P page_poison=1

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#5453]
What does that do? So I googled it:
https://labs.riseup.net/code/issues/12090
https://outflux.net/blog/archives/2016/09/30/security-things-in-linux-v4-6/
https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project

Synopsis: These options wipe freed memory in the kernel after use. It may not be a good idea as slub_debug=P still points into userland addresses afterwards. There is a 9% performance penalty, and perhaps another 3% too as it isn't optimised yet. These options are recommended for use on ARM64, (not any other platform) according to the developers of this concept.

I'm just reading this stuff, never seen a slub before, but it looks dubious that it should be in /etc/default/grub.

**Comment by Duncaen** [comment]
https://github.com/voidlinux/void-packages/pull/5339

**Comment by zqqw** [comment]
OK, I see it has been carefully considered for inclusion.
