### ISSUE TITLE
Nano - cut to end always enabled.

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#5454]
Open nano, pressing CTRL g for help page (CTRL x to exit help) shows this among other things:

^G    (F1)      Display this help text
^X    (F2)      Close the current file buffer / Exit from nano
M-T             Cut from the cursor position to the end of the file
M-K             Cut to end enable/disable

If you do ALT K (with SHIFT) or ALT k then a message comes up saying cut to end is enabled or disabled, it's disabled by default.
Press ALT T (with SHIFT, doesn't work with t) and everything is cut from the cursor to the end of the file regardless of the above setting.

I spotted this accidentally when intending to press CTRL ALT t to open a new terminal tab.
I don't recall unintentionally deleting most of a files contents previously, but I didn't use this feature either. Anyhow, it isn't working as it should.
(I recovered the files contents by pressing CTRL x and closing without saving, then reopening the file as I had recently saved with CTRL o.)

**Comment by chneukirchen** [comment]
I think this works as documented: M-T always deletes until the end of file.
^K will delete to the end of line, *and* the newline if Cut-to-end is enabled.

**Comment by zqqw** [comment]
OK, I intepreted it as the wrong 'end,' thanks for the speedy resolution.
