### ISSUE TITLE
ARM icecat asks for the previous version of libhunspell

### ISSUE THREAD

**Issue by moinejf** [voidlinux/void-packages#5462]
'xbps-query -R icecat' gives:

 shlib-requires:
  libhunspell-1.5.so.0

while 'xbps-query -R libhunspell' gives:

 shlib-provides:
  libhunspell-1.6.so.0

**Comment by pullmoll** [comment]
icecat can't (currently) be cross compiled. The build log of the failure does not exist anymore, though.

You'd have to build your own icecat on native hardware.

**Comment by localhost** [comment]
Isn't it possible to install an older version of the GNU Icecat package?

**Comment by pullmoll** [comment]
I guess you can pick a previous commit and use an old version to build against newer libhunspell, yes.
Also 45.5.1 will certainly be replaced sooner or later, as it usually goes parallel with firefox-esr.

**Comment by chneukirchen** [comment]
This has been fixed, icecat cross-builds again.
