### ISSUE TITLE
iscsiadm: unrecognized character 'm'; known issue

### ISSUE THREAD

**Issue by sigsegvoid** [voidlinux/void-packages#5465]
iscsiadm responds to every command with following message

iscsiadm: unrecognized character 'm'

Any option given, whether it is -m or --mode and etc. gives response of unrecognized character, except for option --version

**build**
x86_64
Kernel = 4.8.15_1
dracut --force --add-drivers "vfio vfio_iommu_type1 vfio_pci vfio_virqfd pci_stub" --omit-drivers "radeon amdgpu"; radeon is loaded after boot manually.
musl libc (x86_64) - Version 1.1.15
iscsiadm version 2.0-874

Possible bug just like it was observed in alpine linux, which is also built with musl.
https://bugs.alpinelinux.org/issues/4802

Thank you in advance!

**Comment by pullmoll** [comment]
Whenever the x86_64-musl builder gets to build open-iscsi-2.0.874_2 you could give it a try and, if it works, close this issue.

**Comment by pullmoll** [comment]
ping @sigsegvoid

**Comment by sigsegvoid** [comment]
@pullmoll
I am sorry I was a bit busy this week for this.
Thank you for pushing the patch thru! I no longer have a bare metal musl void installation, (running glibc one for skype), but I will spin up a vm and test this, Sunday at the latest!)
Thanks.

**Comment by sigsegvoid** [comment]
@pullmoll 
Huzzah it works like it should!
Tested on vm (qemu -enable-kvm -M q35) with 4.9.4_1 kernel, musl libc 1.1.16, open-iscsi 2.0-874

FYI: when a legitimate error imput error occurs, such as saying 
iscsiadm -m (with no arguments), the error out is
option requires an argument: m
unrecognized character 'm'.
If it means anything to anyone Oo. But, as far as error handling, it seems like its the correct order now, if  a bit redundant haha. ^^

Thank you very much for fixing this! ^^
-sigsegvoid
