### ISSUE TITLE
lxqt-admin et al: fix pending

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5482]
Just FYI I have a cross compile fix for lxqt-admin and will probably add more fixes for lxqt packages.
It's just that the x86_64-musl builder is extremely slow and cross compiling for *-musl requires the qt5 for x86_64-musl being built, so I'll wait until that finishes.

**Comment by ebfe** [comment]
Good to know, i was just going through them all and started fixing. Seems they all can be fixed with
`hostmakedepends+="qt5-qmake qt5-host-tools qt5-tools"` and the flags.make sed.

**Comment by pullmoll** [comment]
Yep, that's almost like the patch for lxqt-admin. Mine is:
```
+hostmakedepends="qt5-host-tools qt5-devel liblxqt-devel"

+post_configure() {
+       find -name flags.make -exec sed -i "{}" -e"s;-isystem;-I;g" \;
+}
+
```

**Comment by pullmoll** [comment]
I modified the following packages to fix for cross compiling

- [x] kwayland
- [x] libkscreen
- [x] kidletime
- [x] lxqt-about
- [x] lxqt-admin
- [x] lxqt-config
- [x] lxqt-globalkeys
- [x] lxqt-notificationd
- [x] lxqt-openssh-askpass
- [x] lxqt-panel
- [x] lxqt-policykit
- [x] lxqt-powermanagement
- [x] lxqt-qtplugin
- [x] lxqt-runner
- [x] lxqt-session
- [x] lxqt-sudo
- [x] pcmanfm-qt
- [x] lximage-qt
- [x] obconf-qt

With this I built lxqt-0.11.0_1 for aarch64 and am now trying the other cross targets.

**Comment by pullmoll** [comment]
Ok, I push my batch...
