### ISSUE TITLE
Lollypop complains about missing Gstreamer plugins [musl]

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#5491]
Lollypop complains when it is opened that there is missing Gstreamer plugins but at least I have no idea what those plugins are. I have installed gst-plugins-* and gstreamer but that did not help. Could it help to make the needed plugins optional dependencies? Regards.

**Comment by pullmoll** [comment]
Please try the updated version. I did add the dependencies `gst-libav` and `youtube-dl` which lollypop supports and seems to expect.

**Comment by pullmoll** [comment]
On my laptop I saw that https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata does not have any new files, e.g. the kernel update to 4.9. Is everything alright with synchronizing the repodata from `kc`?

**Comment by the-maldridge** [comment]
@pullmoll fixed

**Comment by pullmoll** [comment]
Should long be fixed. Otherwise please open a new issue.
