### ISSUE TITLE
Opera Broken: FT_Get_Var_Blend_Coordinates

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#5494]
The most recent version of opera and the most recent version of libharfbuzz do not play well with each other.  Perhaps we aren't building harfbuzz with some optional dependency?

```
maldridge@deepblue:~$ opera
/usr/lib/opera/opera: symbol lookup error: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

```

This issue is present on x86_64, i686 exhibits a different fault.

**Comment by pullmoll** [comment]
The symbol is contained in `libfreetype.a` and thus should be in `libfreetype.so.6.13.0`. Is `libfreetype` in the library search path for `opera`?

**Comment by pullmoll** [comment]
Oh, I see the `opera` package has ` libfreetype.so.6` in both, shlib-provides and shlib-requires. See `xbps-query -R opera`.

I don't know if this makes sense at all.

**Comment by pullmoll** [comment]
Please try if `opera-42.0.2393.94_2` solves the issue.

**Comment by xtraeme** [comment]
Tested this successfully, thanks.
