### ISSUE TITLE
qt5 broken, unresolvable shlib libts

### ISSUE THREAD

**Issue by charles-l** [voidlinux/void-packages#5499]
Tried to run `xbps-install -Su` and got:

`qt5-5.7.1_2: broken, unresolvable shlib 'libts-1.2.so.0'`

I tried `xbps-install -f qt5` and `xbps-reconfigure qt5`, but no dice.

The library is there, so I don't know what the issue is.

```
> ls -lah /usr/lib/libts*
lrwxrwxrwx 1 root root   18 Nov 24 03:49 /usr/lib/libts-1.2.so.0 -> libts-1.2.so.0.0.2
-rwxr-xr-x 1 root root  10K Nov 24 03:49 /usr/lib/libts-1.2.so.0.0.2
```

```
XBPS: 0.51 API: 20151030 GIT: UNSET
Linux gimli 4.8.15_1 #1 SMP PREEMPT Thu Dec 15 23:12:48 UTC 2016 x86_64 GNU/Linux
```

**Comment by Gottox** [comment]
We're aware of that. For the current build status see https://build.voidlinux.eu/waterfall Will be fixed once the build ends. Sorry!

**Comment by charles-l** [comment]
@Gottox ah, cool. Didn't realize there was a build status page. I'll keep that in mind for the future, thanks :)
