### ISSUE TITLE
Package request: open-vm-tools

### ISSUE THREAD

**Issue by jsumners** [voidlinux/void-packages#5502]
https://github.com/vmware/open-vm-tools

`open-vm-tools` provides the guest OS drivers and services for systems running in the VMWare environment. These tools are necessary for proper management of virtual machines within the VSphere environment.

**Comment by jsumners** [comment]
I started investigating how I would contribute this, but only got as far as the following steps:

1. autoreconf -i
2. ./configure —without-x —without-ssl —disable-deploypkg
3. make

Step 2 doesn't finish because the configure script can't find "glib2". And I can't find a "glib2" anything in the repository.

**Comment by Duncaen** [comment]
This is what i have so far, we need to package dnet (libdumbnet1 in debian), `--without-dnet` does not work. 

```
# Template file for 'open-vm-tools'
pkgname=open-vm-tools
version=10.1.0
revision=1
wrksrc="${pkgname}-stable-${version}"
build_wrksrc=${pkgname}
build_style=gnu-configure
configure_args="--without-xmlsecurity --without-dnet --without-kernel-modules"
hostmakedepends="automake gettext libtool pkg-config"
makedepends="fuse-devel glib-devel gtk+-devel gtkmm2-devel libmspack-devel libressl-devel libX11-devel libXext-devel libXinerama-devel libXi-devel libXrender-devel libX
randr-devel libXtst-devel libxerces-c-devel pam-devel procps-ng-devel"
depends=""
short_desc="Set of services and modules that enable several features in VMware"
maintainer="Duncaen <duncaen@voidlinux.eu>"
license="GPL-2, LGPL-2.1, BSD"
homepage="https://github.com/vmware/open-vm-tools"
distfiles="https://github.com/vmware/open-vm-tools/archive/stable-${version}.tar.gz"
checksum=2b76d8461022774f2c077b032fbe870f86046f20724eb24824cf9b6ccc4b5355

pre_configure() {
        sed -i -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
        mkdir -p common-agent/etc/config
        autoreconf -fi
}
```

**Comment by jsumners** [comment]
Source for libdnet is https://github.com/dugsong/libdnet . Debian has it as "libdumbnet" because they already had a "libdnet" ([ref](https://sources.debian.net/src/libdumbnet/1.12-7/debian/patches/01rename_library.sh.dpatch/)).

**Comment by jsumners** [comment]
@Duncaen when you ran `configure` did you get "configure: error: glib2 >= 2.14.0 is required."? I have `glib-devel` installed.

**Comment by Duncaen** [comment]
No, fails later while building without dnet for me, do you have `pkg-config` installed?

**Comment by jsumners** [comment]
I did not have `pkg-config` installed. That has helped `configure` find `glib`. Thanks.

I don't know if I'll be able to get this done myself, but I'm at least trying.

**Comment by jsumners** [comment]
Here's what I have as a template for `libdnet`:

```
# Template file for 'libdnet'
pkgname=libdnet
version=20170118
commit="1570b70ccbd6f62cb8a0f745ff7a4a8c48817fec"
revision=1
build_style=gnu-configure
#configure_args=""
#hostmakedepends=""
#makedepends=""
wrksrc="${pkgname}-${commit}"
short_desc="libdnet provides a simplified interface to networking routines"
maintainer="James Sumners <james.sumners@gmail.com>"
license="MIT"
homepage="https://github.com/dugsong/${pkgname}"
distfiles="${homepage}/archive/${commit}.tar.gz"
checksum="01197806f5e1769995350835d51e2e3eaf65faffad7e68770c6e9ecd4be4e690"

pre_configure() {
  sed -i -e 's/^\(.*tun.h udp.h\)/\1 sctp.h/' include/dnet/Makefile.in
}
```

I have successfully built the `open-vm-tools` code with: `./configure --without-x --without-ssl --disable-deploypkg --without-xmlsecurity --without-kernel-modules --without-pam --without-icu`

**Comment by Duncaen** [comment]
#5347

**Comment by maxice8** [comment]
package is in the repo, this can be closed.
