### ISSUE TITLE
qt missing from repos on arm

### ISSUE THREAD

**Issue by clehner** [voidlinux/void-packages#5531]
On armv7l-musl, qt and dependents are unavailable:
```
$ sudo xbps-install -S mumble
[*] Updating `https://repo.voidlinux.eu/current/musl/armv7l-musl-repodata' ...
Unable to locate 'mumble' in repository pool.
$ sudo xbps-install electrum
MISSING: python-PyQt4>=0
Transaction aborted due to unresolved dependencies.
$ sudo xbps-install python-PyQt4
Unable to locate 'python-PyQt4' in repository pool.
$ sudo xbps-install qt
Unable to locate 'qt' in repository pool.
```

On x86_64-musl, the packages are available:
```
$ sudo xbps-install -S mumble electrum qt -f
[*] Updating `http://repo3.voidlinux.eu/current/musl/x86_64-musl-repodata' ...

Name     Action    Version           New version            Download size
mumble   reinstall 1.2.18_1          1.2.18_1               -
electrum reinstall 2.7.12_2          2.7.12_2               -
qt       reinstall 4.8.7_14          4.8.7_14               -

Size required on disk:          51MB
Free space on disk:             56GB

Do you want to continue? [Y/n]
```

Compiling qt on armv7l-musl is taking too long, and I haven't tried cross-compiling it on x86_64-musl yet, so I don't know if/where the build is failing.

**Comment by Vaelatern** [comment]
Try qt5. Since qt4 is unmaintained, I doubt we will go through the pain to get it cross compiling.
@pullmoll is to thank for all the things of qt we DO have cross compiling.
If you really want qt4, probably best to build it yourself.

**Comment by pullmoll** [comment]
With the experience from qt5 I already thought about trying to give qt4 cross compiling another try. It _is_ possible, but it's certainly more difficult than it was to get qt5 to cross compile.

I'm undecided whether it's worth the trouble while OTOH there are still a big number of packages depending on qt4 and thus being not available for the arm* or mips* architectures.

**Comment by pullmoll** [comment]
@clehner qt4 now cross compiles as well and is available for arm.
It took me a day or two and some :beers: in between :)

**Comment by clehner** [comment]
On Sat, 14 Jan 2017 17:28:11 -0800
J�rgen Buchm�ller <notifications@github.com> wrote:

> @clehner qt4 now cross compiles as well and is available for arm.
> It took me a day or two and some * in between :)

Thank you greatly! Now I can cancel this endless qt-webkit build...
