### ISSUE TITLE
Perl-modules (glibc, x86_64) needs rebuild 

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#5534]
Some of the Perl-modules offered as xbps packages must be rebuild against perl 5.24.0_4

e.g. cpanminus and several others gives the following error:

`Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xdb80080`

**Comment by chneukirchen** [comment]
Can't reproduce, also Cwd is part of perl5.24.0 itself.

**Comment by mdkuser** [comment]
`xbps-install perl perl-IO-Socket-SSL perl-Net-SSLeay perl-URI perl-XML-NamespaceSupport perl-XML-Parser perl-XML-SAX perl-XML-SAX-base perl-XML-Simple cpanminus'


Then type cpanm to see above error.
Same happens for my perl scripts that are using one of the above mentioned mods

**Comment by mdkuser** [comment]
seams the problem is with perl-XML-SAX

trying to remove it by xbps-remove perl-XML-SAX results in same error message.

**Comment by mdkuser** [comment]
I can't even use cpan anymore, same issue. Any hint how to get perl back working?

**Comment by chneukirchen** [comment]
We don't have perl-XML-SAX-base. cpanm shows the usage fine for me.

**Comment by chneukirchen** [comment]
ah, `-Base`. Still can't reproduce. Sure you have the latest packages installed from repo?

**Comment by pullmoll** [comment]
> xbps-install perl perl-IO-Socket-SSL …

The `xbps-install` is missing `-S` (sync). Perhaps you're picking up old versions.

**Comment by mdkuser** [comment]
I did sync and force reinstalld perl and it's modules, no luck.
What fixes it for me was to remove all perl stuff then deleting /usr/lib/perl5 and /usr/share/perl5 and reinstalling latest perl packages and perl-modules...

Can be closed
