### ISSUE TITLE
crossmakedepends

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5550]
Since many packages need extra packages for the host when cross compiling, perhaps the templates can be simplified a bit, if we add a new variable `crossmakedepends`. This would just have to be appended to `hostmakedepends`, iff a cross build is run.

**Comment by Vaelatern** [comment]
We also go the other way, if not crossing then adding some dependencies. It's not clean as it currently is, but it's simple.

**Comment by pullmoll** [comment]
True. Hmm, perhaps a simple prefix before a package name could indicate to (not) include it for cross builds. Like `{c}pkgname` for packages to include only for cross builds and `{n}pkgname` for packages to include only for native builds. Or I may just be talking out of my a*** :)

**Comment by Anachron** [comment]
I think a prefix is not a good way to fix that issue.

**Comment by ebfe** [comment]
> This would just have to be appended to hostmakedepends, iff a cross build is run.

Hmm, the only reason hostmakedepends exists/is meaningful is in cross builds. How would a new variable help here?

**Comment by pullmoll** [comment]
Yes, this was a stupid idea, so I'm closing it.
