### ISSUE TITLE
prosody-0.9.12_1 (x86) ssl support broken due to incompatible luasec version

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#5558]
After upgrading to prosody-0.9.12_1 and lua51-luasec-0.6_1 , prosody complains as follows:

`

> 
 **************************
Prosody was unable to find LuaSec
This package can be obtained in the following ways:

	Source:           http://www.inf.puc-rio.br/~brunoos/luasec/
	Debian/Ubuntu:    http://prosody.im/download/start#debian_and_ubuntu
	luarocks:         luarocks install luasec

SSL/TLS support will not be available
More help can be found on our website, at http://prosody.im/doc/depends
**************************
>
`

Downgrading to lua51-luasec-0.5.1_4 makes prosody working again with SSL/TLS.

**Comment by mdkuser** [comment]
I guess prosody needs to be rebuild against lua51-luasec-0.6_1

**Comment by mdkuser** [comment]
From the official prosody website:

> The newly released LuaSec 0.6 does not work with Prosody 0.9.x

So please downgrade lua51-luasec to 0.5.1_4 (or create a package for prosody named luasec-prosody)

**Comment by Duncaen** [comment]
I don't get it, the release notes state that it is fixed...
http://blog.prosody.im/prosody-0-9-12-released/
