### ISSUE TITLE
KDE 4 plasma broken after last qt update/rebuild

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#5559]
Shortly after installing updates on one of my x86_64 machines yesterday, I noticed that KDE applications looked strange. They no longer had the "smooth" KDE theme but instead looked more like GTK applications usually look under KDE or maybe some ancient KDE theme.

After a reboot of the computer, KDE would no longer start because plasma-desktop segfaulted in libQtCore.so.4.8.7. Since Plasma complained that qt was built with g++-6.3 versus g++-4.9 for the kde libraries and I was aware that a C++ rebuild with the new gcc version is planned, I rebuilt every KDE package I found (kde-workspace, kdelibs, kde-runtime, kdepim, kdepimlibs, kdeplamsma-addons, akonadi, phonon, etc.) locally with the current g++-version and installed them. That restored the KDE theme for KDE applications but plasma-desktop still crashes, this time with a segfault in libQtScript.so.4.8. So I guess something else further down the dependency graph also would need a rebuild, I just couldn't figure out which package exactly that would be yet.

**Comment by pullmoll** [comment]
We have `xbps-dgraph` and it should be possible to find which of the dependencies needs a rebuild.
`xbps-dgraph -R kde | dot -T png kde.png` produces this image:
<img src="http://misc.voidlinux.de/kde.png">

Perhaps you can identify which one of the dependencies needs a rebuild and we can revbump it.

**Comment by pullmoll** [comment]
FWIW I tried a fresh KDE live image built with all packages compiled with gcc6.3 and it works in qemu.
If you want to give it a try, you can [download it here](http://voidlinux.myds.me/repo/live/).

**Comment by Hoshpak** [comment]
Thanks a lot! I can confirm that this generally works for me too. I even copied my KDE profile over into a VM after installing for your image and was able to log in without getting a plasma crash. Strangely enough, plasma works but the widget functionality seems to be gone. Even though kdeplasma-addons is installed in the image (and also the Void installation created from it), the pane for adding new widgets is completely empty and my widgets already configured do not appear on the desktop any more.

To verify it worked before, I grabbed one of the old live images, installed another VM with it using a network installation, installed KDE and downgraded qt to qt-4.8.7_14 afterwards. As expected, the widgets worked fine again. Of course this might be a different issue that only surfaced after the rebuild, not necessarily because of it.

**Comment by Hoshpak** [comment]
I've found at least one more package that needs rebuilding: qt-webkit. After rebuilding that one and installing it additionally to the kde packages I already rebuilt earlier, I am able to log in to my desktop again without getting a plasma crash. As in the VMs, the plasma widget functionality and the previously configured widgets are gone now. Why that happens is still a mystery to me.

**Comment by pullmoll** [comment]
Well, after all it seems that our assumption that C++ compatibility is *good enough* between gcc4.9.4 and gcc6.3.0 is not holding true. I think I should at least give the packages depending on `qt-webkit-devel` a revbump to see if this helps.

**Comment by pullmoll** [comment]
For the plasma widget functionality, perhaps one of the new `CXXFLAGS` introduced in qt-4.8.7_16 is causing this. If you find time, you could try to rebuild `qt` locally without `-fno-lifetime-dse -fno-schedule-insns2`. The `-fno-delete-null-pointer-checks` should be ok because `qt5` also uses it since gcc6.

**Comment by Hoshpak** [comment]
I went back to 4705871f1d0f9eddb60e60983c417716b79e358d and built qt from the old template without the new CXXFLAGS, the error remains. It seems that there's for some reason a degradation in QML functionality, I got the following error messages from .xsession-errors:

```
plasma-desktop(954)/libplasma Plasma::DeclarativeWidgetPrivate::errorPrint: "file:///usr/share/apps/plasma/packages/org.kde.desktop.widgetexplorer/contents/ui/main.qml
Error loading QML file.
51: Cannot assign to non-existent property "onClicked"
" 
QDeclarativeComponent: Component is not ready
plasma-desktop(954)/libplasma Plasma::DeclarativeWidgetPrivate::errorPrint: "file:///usr/share/apps/plasma/packages/org.kde.desktop.widgetexplorer/contents/ui/main.qml
Error loading QML file.
51: Cannot assign to non-existent property "onClicked"
" 
```

On another computer which still has the qt package and KDE built with g++-4.9, loading the widget dialog also prints some errors but none of them are critical and the file is loaded successfully.

**Comment by pullmoll** [comment]
This could perhaps be related to the `-fvisibility=hidden` default(?) attribute for (private) functions, which may be different between g++4.9 and g++6.3. So if this is the reason, presetting visibility to normal by specifying `CXXFLAGS+=" -fvisibility=normal"` in the `qt` template could make a difference.

**Comment by Hoshpak** [comment]
I tried rebuilding with that in the template file but the resulting binary showed the same behaviour as before. I also noticed that the build system always appended ``-fvisibility=hidden`` no matter what is in the template file, so my build was done with ``-fvisibility=default ... -fvisibility=hidden``.

**Comment by pullmoll** [comment]
Ok, the final visibility option of course wins the race then. I'll have a look myself once I'm done with rebuilding the required pkgs for kde (I started from scratch again).

Can you tell how I can test the plasma widget bug with a live ISO or a KDE installation in a VM? I have no experience with KDE and really don't know what "plasma widget" means :)

**Comment by Hoshpak** [comment]
If you click on an empty space on the task bar with the right mouse button, under "Panel options" there is the option "Add widgets". If you click this, a menu opens above the task bar allowing you to select widgets to add to the desktop (clock, system monitoring and things like that). In case of the QML error, the menu remains empty, can only be closed by pressing ESC and you see the QML error in .xsession-errors.

**Comment by pullmoll** [comment]
Thank you. I'll have a look this afternoon and see, if I can get it fixed.

**Comment by pullmoll** [comment]
Ok, I tried to remove the `-reduce-relocations` configure option: no change.
Then I tried a rebuild with patching `-fvisibility=hidden` to `-fvisibility=default` in the Makefiles: no change.
Last option is to try to rebuild KDE packages with the `visibility=default` qt. This is for tomorrow, though.

**Comment by Hoshpak** [comment]
Perhaps an interesting observation I made today: I installed all available updates on my second x86_64 computer, including qt, qt-webkit, kdelibs and kde-baseapps. As was to be expected, plasma crashed after the next login. To fix it, I rebuilt kde-workspace, kdeplasma-addons and kde-runtime (in that order) and installed the resulting packages. Plasma worked after that and so did the widgets! So my current theory is that the QML errors leading to the unavailability of the widget functionality are caused by another package that was of course rebuilt along with all other packages in the live image and which I also rebuilt  manually while trying to get plasma to work again. Hopefully I will be able to figure out which one it is.

**Comment by Hoshpak** [comment]
Oops, I jumped to conclusions to quickly. The widgets I configured before are still there but the menu to add new widgets is also broken on this computer now, same QML error. So while it remains an interesting curiosity that the previously configured widgets kept working here, that observation doesn't help.

**Comment by pullmoll** [comment]
At least the three packages `kde-workspace', `kdeplasma-addons` and `kde-runtime` are revbumped now to be rebuilt with gcc6. I found no solution so far either. It doesn't help the kde4 is slowly dying out and bug reports are from years ago.

**Comment by Hoshpak** [comment]
Thanks for all the effort you put into this. Perhaphs it's about time to remove KDE 4 from Void. Of course that would be easier if KDE 5 was in the repository to replace it.

**Comment by pullmoll** [comment]
I tried some more ideas I had, unfortunately all to no avail:
+ rebuilt kdeplasma-applets with `-fno-delete-null-pointer-check -fno-lifetime-dse -fno-schedule-insns2`
+ rebuilt kde-runtime with `-fno-delete-null-pointer-check -fno-lifetime-dse -fno-schedule-insns2`
+ Add some more patches (for gcc5 and newer) found in BLFS 7.9 for qt-webkit 2.3.4

It is beyond me why the `signal: void clicked();` in the plasma widgets or items (I think it was KMenuItem and KToolButton) is no longer visible for clients like QML. This signal is where the QML `onClicked` would connect to, because a naming rule is involved here: `signal: void foo();` becomes `onFoo` in QML.

I give up on this bug.

**Comment by maxice8** [comment]
can be closed ? @lemmi

**Comment by Hoshpak** [comment]
Indeed, I totally forgot about this issue.
