### ISSUE TITLE
xbps default repository file should be in /etc/xbps.d/

### ISSUE THREAD

**Issue by jsumners** [voidlinux/void-packages#5568]
https://github.com/voidlinux/void-packages/blob/318df1f24f162d35c06edbadb0c2d098f88a9378/srcpkgs/xbps/template#L43-L60

The xbps package writes its default repository to `/usr/share/xbps.d/00-repository-main.conf`. If you add a `/etc/xbps.d/repos.conf` like:

```
repository=http://some.internal.mirror/voidlinux
```

then whenever repository data is synchronized xbps will look at *both* the user defined repository and the default repository. If the system cannot reach the outside world, then this causes xbps to hang for a long time waiting for a timeout. The only current solution is to edit the package supplied `00-repository-main.conf` file to comment out the default repository.

This solution is not desirable: it means the user is editing a system managed file instead of user managed configuration.

Thus, it is my opinion the default repository should be written to `/etc/xbps.d/repos.conf`, or some other file in `/etc/xbps.d`.

**Comment by Gottox** [comment]
```
# man xbps.d
...
DESCRIPTION
     The xbps.d configuration directory sets properties for the XBPS package
     manager.  The configuration directory, by default set to /etc/xbps.d
     overrides settings from files available in the system configuration
     directory, by default set to /usr/share/xbps.d.
...
```

**Comment by jsumners** [comment]
@Gottox did read all of my issue? That is not happening. When I define a repository in `/etc/xbps.d/repos.conf` it is getting queried **in addition to** the one defined in `/usr/share/xbps.d/00-repository-main.conf`.

Further, it shouldn't be a mystery as to where the configuration is being read from. I don't know of any other package manager that defines their standard repositories in `/usr/share` directories. They all define their initial repository configuration in `/etc/`.

**Comment by xtraeme** [comment]
@jsumners I think the manual page is detailed enough. If you want to override the settings of that file (from `/usr/share/xbps.d`), just create a file with the same name in `/etc/xbps.d`.

Just let me know if something is not clear enough and I'll update the manual page.

Thanks.

**Comment by Gottox** [comment]
You can overwrite those files by a file of the same name. So: ```touch /etc/xbps.d/00-repository-main.conf``` will invalidate ```/usr/share/xbps.d/00-repository-main.conf```.

**Comment by jsumners** [comment]
@xtraeme then the manual page is not clear enough. It should state that files in `/etc/xbps.d` will override settings in `/usr/share/xbps.d` of files with the same name. Otherwise, to me at least, it reads like any setting from any file in `/etc/xbps.d` will override any setting of the same name from any file in `/usr/share/xbps.d`.

I do still think the default repository configuration should be `/etc/xbps.d`, though. I don't know what is gained by hiding it in a non-conventional configuration directory.

http://www.pathname.com/fhs/pub/fhs-2.3.html#USRSHAREARCHITECTUREINDEPENDENTDATA
> Any program or package which contains or requires data that doesn't need to be modified should store that data in /usr/share (or /usr/local/share, if installed locally). It is recommended that a subdirectory be used in /usr/share for this purpose.

The configuration of which repository to use is, in my opinion, a prime candidate for data that _may_ be modified.
