### ISSUE TITLE
rust: binaries are gone

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5602]
The `rust` package tries to download binaries like https://repo.voidlinux.eu/distfiles/rustc-1.13.0-x86_64-unknown-linux-musl.tar.gz which are no longer there. Perhaps someone can upload a copy?

**Comment by chneukirchen** [comment]
Why where these removed? Bootstrapping on musl is not possible else...

**Comment by chneukirchen** [comment]
Restored from repo2.voidlinux.eu, SHA256 matched the template.
