### ISSUE TITLE
screen 4.5.0 security fixes

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#5603]
Upstream report: https://lists.gnu.org/archive/html/screen-devel/2017-01/msg00025.html

We should bump this as soon as a fix is out, and also investigate how to run screen setgid instead of setuid root (apparently Debian does this).

**Comment by chneukirchen** [comment]
From https://lists.gnu.org/archive/html/screen-devel/2017-01/msg00025.html

> Some install it SGID utmp.  Some take it a step further - Owl and ALT
> Linux install it SGID to group screen, which only grants the ability to
> invoke utempter (SGID utmp) and tcp_chkpwd (SGID shadow).  Thus, it'd
> take a vulnerability in those other tools to make much use of a screen
> vulnerability.

**Comment by chneukirchen** [comment]
Perhaps we could make screen put the sockets into `/tmp`, then setgid utmp should be good enough.

**Comment by ebfe** [comment]
Fixed by 47a8b53e54655162c35cb92f9daf9ffbdd68f9d1?

**Comment by cr6git** [comment]
`--enable-telnet` should be removed, for security matters.

**Comment by chneukirchen** [comment]
Why?

**Comment by cr6git** [comment]
We use SSH nowadays.

**Comment by chneukirchen** [comment]
We also have inetutils-telnet.

**Comment by cr6git** [comment]
> inetutils-telnet

But it's another package, how does that relate to `screen` ? 

If you are happy using an unencrypted protocol, why are you complaining about security?

**Comment by chneukirchen** [comment]
telnet is obviously unsafe, and not an issue at all if you don't use it.

no need to discuss this further.
