### ISSUE TITLE
perl 5.24.1_1 breaks "git add -p" in git-2.11.0_1

### ISSUE THREAD

**Issue by sunaku** [voidlinux/void-packages#5631]
Today's perl-5.24.1_1 update broke `git add -p` provided by git-2.11.0_1:

```sh
$ git add -p
fatal: 'add--interactive' appears to be a git command, but we were not
able to execute it. Maybe git-add--interactive is broken?
exit 128
```

Downgrading back to perl-5.24.0_4 was an effective workaround for me:

    sudo xdowngrade /var/cache/xbps/perl-5.24.0_4.x86_64.xbps

Thanks for your consideration. :sweat_smile:

**Comment by chneukirchen** [comment]
Fixed in 80cd9e2f80. Thanks for reporting.
