### ISSUE TITLE
Icecat can't connect to Google/Gmail/YouTube/Wikipedia servers

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5647]
Hi !

I have an issue with Icecat 45.5.1: Icecat can't connect to Google/Gmail/YouTube/Wikipedia servers.

Not long ago I complained about the same issue with Firefox-ESR 45.6, which has been fixed...

Today I complained about Icecat on the Void's forum (as I did for Firefox-ESR), but somebody told me that the forum is not the right place to complain about a package, look:
https://forum.voidlinux.eu/t/icecat-issue/1797

Thank you.

**Comment by Anachron** [comment]
Thanks for reporting it here! This is indeed a better place for things like this ;)

**Comment by chneukirchen** [comment]
More detail: https://bugzilla.redhat.com/show_bug.cgi?id=1414987

**Comment by chneukirchen** [comment]
Can you check if `network.http.spdy.enabled.http2=false` is a workaround?

**Comment by chneukirchen** [comment]
Also need to backport https://hg.mozilla.org/releases/mozilla-esr45/rev/571b48abf054895d21d896be638f48338d87e864

**Comment by cr6void** [comment]
I downloaded the Icecat binary here: https://ftp.gnu.org/gnu/gnuzilla/45.5.1/

I just tried it and it works !

**Comment by pullmoll** [comment]
Our icecat-45.5.1_3 should also work - it does here.
