### ISSUE TITLE
nfs-utils: start-statd runs with /bin/sh but needs /bin/bash

### ISSUE THREAD

**Issue by fritschy** [voidlinux/void-packages#5657]
When running start-statd with /bin/sh not being bash - e.g. dash through xbps-alternatives - it does not do what is is intended to:

```
> sudo start-statd
/usr/bin/start-statd: 10: exec: 200: not found
```

The offending line is the exec in the following snippet:

```
# Use flock to serialize the running of this script
exec 200> /var/run/rpc.statd.lock
flock -e 200
```

Using /bin/bash as the interpreter fixes the issue.

This issue prevents nfs exports to be mounted.

**Comment by Duncaen** [comment]
I think we should replace this script with something that would run `sv up statd`.
This script just starts the systemd unit and falls back to executing `rpc.statd` as double forked daemon.

**Comment by fritschy** [comment]
Oh boy, I really just looked at was was the issue and didn't even notice this.

+1 :)
