### ISSUE TITLE
Uzbl fails to run

### ISSUE THREAD

**Issue by SevereOverfl0w** [voidlinux/void-packages#5664]
uzbl depends upon pygtk. pygtk installs to `/usr/lib/python2.7/site-packages/` (so, a Python2 package) but Uzbl is a Python3 package.

I'm not sure what the correct remedy is here, a pygtk-python3 package maybe?

Currently this means uzbl-tabbed is broken.

Changing the uzbl-tabbed to use python2 instead of python3 seems to work for now.

**Comment by SevereOverfl0w** [comment]
Further digging reveals that this seems to be a misconfiguration, https://github.com/uzbl/uzbl/blob/master/bin/uzbl-tabbed uses python2 quite clearly in the script header.

I've noticed some rewriting scripts, could they have been overzealous?

**Comment by asergi** [comment]
This should now be fixed in d92ae8c21b5820c87e6c4b918ef446e2081c4ba7. Can you please verify?
To install `uzbl-tabbed`:
```
# xbps-install -Su
# xbps-install uzbl-tabbed
```

**Comment by SevereOverfl0w** [comment]
Yes, this is working now, thanks!

**Comment by asergi** [comment]
Fixed.
