### ISSUE TITLE
Urxvt stopped working !

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5667]
Hi !
"urxvt" stopped working for us, look here:

https://forum.voidlinux.eu/t/urxvt-stopped-working/1821

thanks. ;)

**Comment by chneukirchen** [comment]
This is not a bug report.

Are you using i686? If yes, I'm working on it.

**Comment by cr6void** [comment]
Yes i686 and ?

**Comment by chneukirchen** [comment]
Perl needs a rebuild. Wait a few hours or downgrade perl to 5.24.0 if you need urxvt to work.

**Comment by chneukirchen** [comment]
Please confirm perl-5.24.1_3 fixes the issue.
