### ISSUE TITLE
Package Request: Compiz 0.8.x series and Emerald (for 0.8.x)

### ISSUE THREAD

**Issue by ShadowKyogre** [voidlinux/void-packages#568]
http://cgit.compiz.org/compiz/core/snapshot/compiz-0.8.9.tar.bz2
http://releases.compiz.org/0.8.8/compiz-plugins-extra-0.8.8.tar.bz2 (AUR tarball shows how to build it with notification fix patch: https://aur.archlinux.org/packages/co/compiz-fusion-plugins-extra/compiz-fusion-plugins-extra.tar.gz )
http://releases.compiz.org/0.8.8/compiz-plugins-main-0.8.8.tar.bz2 (AUR tarball shows how to build it with staticswitcher patch https://aur.archlinux.org/packages/co/compiz-fusion-plugins-main/compiz-fusion-plugins-main.tar.gz)
http://releases.compiz.org/0.8.8/emerald-0.8.8.tar.bz2
http://releases.compiz.org/0.8.4/compizconfig-python-0.8.4.tar.bz2
.http://releases.compiz.org/0.8.4/ccsm-0.8.4.tar.bz2

**Comment by ebfe** [comment]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/compiz-core/template
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/emerald/template
