### ISSUE TITLE
moc: unable to start

### ISSUE THREAD

**Issue by lpvm** [voidlinux/void-packages#5692]
After installing `moc-2.5.2_1`:

```
$ moc
moc: could not find a Qt installation of ''
```

`moc` cannot start.

**Comment by Duncaen** [comment]
```
~$ xbps-query -Rf moc | grep /usr/bin
/usr/bin/mocp
```
`/usr/bin/moc` is something else from qt.

**Comment by lpvm** [comment]
I was mislead by then name of the package.. Sorry.  Have a nice day.
