### ISSUE TITLE
aarch64-musl builder: update kernel-libc-headers

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5703]
It seems as if the aarch64-musl builder, and perhaps also the aarch64 builder, need to manually update their kernel-libc-headers for x86_64 and probably also cross-aarch64* because they don't use the x86_64 repository.

Edit: I thought this was the cause for https://build.voidlinux.eu/changes/1254 failing for aarch64-musl, but this has another reason (extraneous CFLAGS in the template). Perhaps someone can verify that kernel-libc-headers and the cross compilers for x86_64 are up to date anyway.

**Comment by chneukirchen** [comment]
Done.
