### ISSUE TITLE
Package Request: hledger

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#5706]
**Hledger** is a plain text double entry accounting suite written in [Haskell](https://www.haskell.org/). Hledger features a cli, Ncurses UI, and web frontend.

Project page: https://github.com/simonmichael/hledger
Dependencies: zlib, ncurses (pkg-config, stack, ghc, gcc, make)

* Notes:
Each component (hledger, hledger-ui, hledger-web) can be downloaded and built independently via the releases page, or built together using 'stack install' on master. Least build trouble seems to be using master instead of the current releases. Maybe you can get the releases to build?. 

I use this software as my primary finance application. It makes the accounting part fun and motivates me to keep up on my savings. Thanks in advance to anyone who decides to take on the task.

**Comment by Vaelatern** [comment]
Does not build easily with resolver=lts-7.19, needs other packages not mentioned at all.

**Comment by silvernode** [comment]
I only listed what was required for me to build it without a template. Strange that it has issues. I'll look around for clues to what else it needs but the docs aren't exactly clear on that.

**Comment by Vaelatern** [comment]
A first stab attempt. Does not succeed but could use some finessing.
```
# Template file for 'hledger'
pkgname=hledger
version=1.1
revision=1
wrksrc="${pkgname}-${pkgname}-${version}"
build_style=haskell-stack
nocross="Can't cross haskell yet"
stackage="lts-7.19"
hostmakedepends=""
makedepends=""
depends=""
short_desc="Simple, precise, plain text accounting"
maintainer="Toyam Cox <Vaelatern@gmail.com>"
license="GPL-3"
homepage="http://hledger.org"
distfiles="https://github.com/simonmichael/hledger/archive/hledger-1.1.tar.gz"
checksum=b47055fb218c7e8b254bc663c5a63398504d2dfa8daf80646b04983f4d488edb

post_extract() {
        # Unable to parse cabal file /builddir/hledger-hledger-1.1/extra/hledger-chart/hledger-chart.cabal: NoParse "version" 2
        # README says: Warning, this package has been unmaintained since 2011 and will not install.
        rm -rf ${wrksrc}/extra/hledger-chart
}
```

**Comment by Vaelatern** [comment]
5e94074
