### ISSUE TITLE
bind not start with glibc2.25

### ISSUE THREAD

**Issue by arete** [voidlinux/void-packages#5708]
Hi,
i have update my x86_64 system to last glibc 2.25
the bind daemon start, but not listen on the interface
the named process is defunct

```
$ps -aux
root     19990  0.0  0.0  45964  4944    pts/4    S    14:38                 0:00 named -d 4
root     19991  0.0  0.0      0     0 ?        Zsl  14:38   0:00 [named] <defunct>
```

**Comment by chneukirchen** [comment]
You could try building bind without seccomp, but I thought I had adjusted the list of calls?

**Comment by Duncaen** [comment]
This is something related to logging, someone told me with `-g` it works, or its not updated to the latest version.

**Comment by arete** [comment]
Start named with -g option i have this error
`'/var/log/querylog' failed: permission denied`
this are the file permission
`Access: (0644/-rw-r--r--)  Uid: (  998/   named)   Gid: (  998/   named)`
now i have move the log file to folder /var/named/log and work fine.
Thanks
