### ISSUE TITLE
Change Dunst SRC

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#5713]
Dunst has been opened to a group and is now frequently updated again:

https://github.com/dunst-project/dunst

Template is still from knopwob
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/dunst/template

**Comment by ibabushkin** [comment]
It seems that https://github.com/knopwob/dunst redirects to the new location of the project anyway. So far, the new maintainers haven't made a new release either. Thus, it's not really a problem I suppose, and I guess the best time to change this would be the next version bump (as the patching work has started).

**Comment by ebfe** [comment]
f1645c5126996d25575f13bad058bba30aa82fb3
