### ISSUE TITLE
dolphin: broken JIT with PIE

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#5720]
Dolphin makes use of a JIT layer to achieve usable performance for the emulated processor.  This is currently broken on x64 with PIE.  The developers for dolphin fixed this in the Ubuntu package by automatically negating Ubuntu's hardened compiler options for PIE.  I do not believe this is a valid solution for us, but perhaps we should mark dolphin broken until the upstream project manages to release a build that works with hardened flags.

Here is the conversation from the issue with Ubuntu for reference: https://bugs.dolphin-emu.org/issues/9853

Looks like it was this merge that brought in the bad flags: dolphin-emu/dolphin#4365 but I think we're building a version that predates that flag (thus why we don't have a nopie set on dolphin-emu).

**Comment by Vaelatern** [comment]
`nopie` could be set in a conditional in the package, and that might be reasonable.

**Comment by the-maldridge** [comment]
While my initial message suggests that it is only the x86 build that
does not build with PIE, it is in fact the entire package has broken PIE.

**Comment by chneukirchen** [comment]
Making this pkg nopie is no problem.

**Comment by the-maldridge** [comment]
Upstream claims to have fixed this, at any rate I no longer have a desire to run dolphin.
