### ISSUE TITLE
Nvidia-378.13 probably is broken

### ISSUE THREAD

**Issue by 0rdy** [voidlinux/void-packages#5745]
After the last update update from 375.26 to 378.13 my system doesn't run. I see the message in console "nvidia-modeset: Version mismatch: nvidia.ko(378.13) nvidia-modeset(375.26)

**Comment by Vaelatern** [comment]
This is after a reboot?

**Comment by 0rdy** [comment]
Yes, after reboot. Maybe version mismatch because I have tried to downgrade nvidia driver, but version from cache doesn't run too.

**Comment by Vaelatern** [comment]
I welcome input. The best I've got is that your dkms didn't run properly for your kernel, so you need to re-run the dkms hooks.

**Comment by 0rdy** [comment]
@Vaelatern What do you mean by "input"? I didn't get any errors in console and log after rebooting i.e. only black screen, except the message above. How can I re-run the dkms hooks?

**Comment by 0rdy** [comment]
Damn, this bug is awful, but I didn't find any working solution to change the nvidia_modeset version. Instead, I remove all new driver with `# dkms remove nvidia/378.13 --all` and go into` /usr/src/`, rename the `nvidia-378.13` directory to `nvidia-375.26`. After I changed PACKAGE_VERSION inside /usr/src/nvidia-375.26/dkms.conf from "378.13" to "375.26" and finally install with `# dkms install nvidia/375.26 --all`. 
@Vaelatern, thanks for your suggestion to re-run the dkms hooks.

**Comment by dkociela** [comment]
I have this same problem but Ordy's workaround did not help me, I only got an API mismatch error.
