### ISSUE TITLE
Void net-install bug!

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5755]
We have a big problem with a fresh Void net-install as you can see on the forum:

https://forum.voidlinux.eu/t/void-installer-bug/1906

Only the root account is created. The normal user account is not created.
Maybe a bug with void-installer script ?

Regards ;)

**Comment by Duncaen** [comment]
Wrong repository, the installer is part of https://github.com/voidlinux/void-mklive.
And this is probably already fixed in HEAD, the ISOs are old and there are a lot of changes.
