### ISSUE TITLE
Deluge -  MISSING: libtorrent-rasterbar-python>=0

### ISSUE THREAD

**Issue by whitephoenix0** [voidlinux/void-packages#5761]
>$ sudo xbps-install deluge
>MISSING: libtorrent-rasterbar-python>=0
>Transaction aborted due to unresolved dependencies.

I've installed libtorrent-rasterbar and still get this error.

**Comment by Hoshpak** [comment]
On which CPU architecture? If I read the source template correctly, libtorrent-rasterbar-python is not cross-compiled currently so it is only available on i686 and x86_64.

**Comment by whitephoenix0** [comment]
@Hoshpak That explains it, this is on an armv6 raspi one. I was trying to set up the deluge daemon for remote access, couldn't find a package and assumed it was included in the deluge package.

**Comment by ebfe** [comment]
4c1fdcde1ccbcab8dd72425439890b4b179a18b8
