### ISSUE TITLE
x86_64/i686 builders ENOSPC

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5765]
It looks as if our builders for i686 and x86_64 disk space is short again. Building linux4.9-4.9.11 failed two times when both ran in parallel. Now I kicked the x86_64 build alone and hope it finishes before anyone pushes an update and i686 tries to build linux4.9 in parallel again :)

So if you have something to push, please wait until the kernels are built. Or perhaps someone can free up some space on the builders again?

**Comment by pullmoll** [comment]
As a side note I really think using ccache and having a decent CCACHE_DIR size (many GiB) would help the builders a lot.

If the reason we don't use ccache is a shortage of disk space, perhaps we could try to collect some money to rent additional space? I'd be willing to contribute a monthly fee to have our infrastructure improved, because waiting for hours for builds to finish, just because of this kind of shortage, isn't fun at all.

Can someone sched some light on the required amounts of money to achieve that?

**Comment by Gottox** [comment]
Storage isn't a problem, partitioning and garbage collection is. I increased / from 6g to 128GB. This should be sufficient for the next few months.
