### ISSUE TITLE
kernel-libc-headers: lacks of musl patches breaks NetworkManager

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#5786]
Since the update to `kernel-libc-headers-4.9.8` that removed some patches for muslc (commit https://github.com/voidlinux/void-packages/commit/8c773d0d35c86693363dca906257cdd226b4c3da),  NetworkManager (1.02) does not build anymore with musl libc.

I suspect that other network stuff that rely on kernel interfaces might be affected.

I will try to provide patches against musl libc, but It might take ages (lack of spare time these days).

Output of NetworkManager build on x86_64 muslc platform (native):
```
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/x86_64-musl-repodata'
: Not Found
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-r
epodata': Not Found
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-r
epodata': Not Found
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-musl-repodata' ...
x86_64-musl-repodata: [2429B 100%] 66MB/s ETA: 00m00s
x86_64-musl-repodata: 2429B [avg rate: 66MB/s]
[*] Updating `https://repo.voidlinux.eu/current/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/aarch64/x86_64-musl-repodata' ...
=> Reconfiguring bootstrap packages...
ca-certificates: configuring ...
ca-certificates: configured successfully.
=> NetworkManager-1.0.12_8: removing autodeps, please wait...
=> NetworkManager-1.0.12_8: the following build options are set:
   gir: Enable support for gobject introspection data (ON)
=> NetworkManager-1.0.12_8: building ...
   [host] automake-1.15_4: found (https://repo.voidlinux.eu/current/musl)
   [host] libtool-2.4.6_1: found (https://repo.voidlinux.eu/current/musl)
   [host] pkg-config-0.29.1_2: found (https://repo.voidlinux.eu/current/musl)
   [host] intltool-0.51.0_3: found (https://repo.voidlinux.eu/current/musl)

[...]

make[4]: Entering directory '/builddir/NetworkManager-1.0.12/src'
  CC       nm-device.lo
  CC       nm-device-ethernet-utils.lo
  CC       nm-device-factory.lo
  CC       nm-device-generic.lo
  CC       nm-dhcp-client.lo
  CC       nm-dhcp-utils.lo
  CC       nm-dhcp-listener.lo
  CC       nm-dhcp-manager.lo
  CC       nm-dns-dnsmasq.lo
  CC       nm-dns-unbound.lo
  CC       nm-dns-manager.lo
  CC       nm-dns-plugin.lo
  CC       nm-dns-utils.lo
  CC       nm-dnsmasq-manager.lo
  CC       nm-dnsmasq-utils.lo
  CC       nm-fake-platform.lo
  CC       nm-linux-platform.lo
In file included from /usr/include/linux/if_tunnel.h:7:0,
                 from platform/nm-linux-platform.c:33:
/usr/include/linux/in6.h:32:8: error: redefinition of 'struct in6_addr'
 struct in6_addr {
        ^~~~~~~~
In file included from /usr/include/netinet/icmp6.h:11:0,
                 from platform/nm-linux-platform.c:27:
/usr/include/netinet/in.h:23:8: note: originally defined here
 struct in6_addr {
        ^~~~~~~~
In file included from /usr/include/linux/if_tunnel.h:7:0,
                 from platform/nm-linux-platform.c:33:
/usr/include/linux/in6.h:49:8: error: redefinition of 'struct sockaddr_in6'
 struct sockaddr_in6 {
        ^~~~~~~~~~~~
In file included from /usr/include/netinet/icmp6.h:11:0,
                 from platform/nm-linux-platform.c:27:
/usr/include/netinet/in.h:34:8: note: originally defined here
 struct sockaddr_in6 {
        ^~~~~~~~~~~~
In file included from /usr/include/linux/if_tunnel.h:7:0,
                 from platform/nm-linux-platform.c:33:
/usr/include/linux/in6.h:59:8: error: redefinition of 'struct ipv6_mreq'
 struct ipv6_mreq {
        ^~~~~~~~~
In file included from /usr/include/netinet/icmp6.h:11:0,
                 from platform/nm-linux-platform.c:27:
/usr/include/netinet/in.h:42:8: note: originally defined here
 struct ipv6_mreq {
        ^~~~~~~~~
make[4]: *** [Makefile:1552: nm-linux-platform.lo] Error 1
make[4]: Leaving directory '/builddir/NetworkManager-1.0.12/src'
make[3]: *** [Makefile:2110: all-recursive] Error 1
make[3]: Leaving directory '/builddir/NetworkManager-1.0.12/src'
make[2]: *** [Makefile:1138: all] Error 2
make[2]: Leaving directory '/builddir/NetworkManager-1.0.12/src'
make[1]: *** [Makefile:684: all-recursive] Error 1
make[1]: Leaving directory '/builddir/NetworkManager-1.0.12'
make: *** [Makefile:579: all] Error 2
=> ERROR: NetworkManager-1.0.12_8: failed to run do_build() at line 13.
```

**Comment by pullmoll** [comment]
Yeah, the update to kernel-libc-headers-4.9.8 causes a lot of trouble with musl libc. This already required some hackery in various pkgs.

Usually the simpler solution is to not include the `linux/*.h` files which generate the conflicts unless `__GLIBC__` is defined. See https://github.com/voidlinux/void-packages/commit/9e3759b15474c2854ae6e29965ae2f0e39999271 for an example of an ugly hack.

**Comment by yopito** [comment]
hello, thanks for your reply and pointer. 
So patching kernel-libc-headers for musl libc is not welcomed ? too tricky ? but might help a lot of packagings if achieved ("one patch for all").

**Comment by pullmoll** [comment]
Unfortunately there is no standard for the macro names shielding against the re-definition of types.
I guess it would be possible to create a patch for kernel-libc-headers which makes it respect the musl libc macro names. I just don't know if this would be accepted. @xtraeme?

**Comment by yopito** [comment]
I was thinking about patching `linux/libc-compat.h` since a lot of `__UAPI_DEF_*` macros are already present to deal with userspace (glibc) or kernel usage in various `linux/*.h` files. Contrary to out-of-date patches, I was thinking to write the patched `linux/libc-compat.h` to support musl libc this way:

```
 #if defined(__GLIBC__)
 [...]
-#else
+#elif !defined(__KERNEL__) /* userspace with musl libc */
+#define __UAPI_DEF_ ....
+[...]
+#else  /* Kernel mode */
[...]
```

**Comment by pullmoll** [comment]
I took a look into this header file and indeed `/usr/include/linux/libc-compat.h` would need to be patched make a distinction between gnu and musl libc.

I believe it requires quite a bit of research to find the correct values for all those __UAPI_DEF_* values for the musl libc case, though.

This should pay back because patching around the problems in pkg templates is ugly.

Any takers? :grin:

**Comment by yopito** [comment]
Thanks for your return.
I started writing a support of musl libc within `linux/libc-compat.h` as described above. 
Still in dev, but it allows to build NetworkManager with muslc without any patches related to `linux/*.h` files .
I will share my WIP ASAP.

**Comment by pullmoll** [comment]
That's great! I'm working on several other things in parallel and appreciate your efforts very much.

Right now only a few packages are patched, or rather hacked, to work around the problems and IMO it's vital to avoid even more hackery. :)
