### ISSUE TITLE
Debug packages broken: missing .gnu_debuglink

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#5801]
Official binaries after Dec 30 seem to lack .gnu_debuglink sections which makes gdb not able to load debugging symbols from `/usr/lib/debug`. However, locally built packages with `-g` have the debuglinks, at least in DESTDIR.

Any ideas why this is?

**Comment by chneukirchen** [comment]
It doesn't seem to happen for aarch64 packages, so perhaps it's a builder thing?

**Comment by pullmoll** [comment]
FWIW I also saw this happening for x86_64-musl with locally built pkgs when trying to debug `gij` SIGBUS errors.The official repo (https://repo.voidlinux.eu/current/musl/debug) is missing e.g. the most recent gcc-gcj-6.3.0_3.x86_64-musl.xbps - it has other, newer packages, though.

No clue why this is and what causes it.

**Comment by chneukirchen** [comment]
FWIW, the debug packages are not built at all (only `linux*-dbg`, which is made manually...).

**Comment by chneukirchen** [comment]
Ok, actually `.xbps-src.conf` is not read at all. We also don't have `source-revisions` and build using `-j1`...

**Comment by chneukirchen** [comment]
My current guess is that the buildslaves are run using chpst -u which doesn't set $HOME...

**Comment by chneukirchen** [comment]
@the-maldridge can you change the run scripts to use su instead?

**Comment by pullmoll** [comment]
Ouch! -j1 explains why builds are taking so long since the the infrastructure was changed.

**Comment by pullmoll** [comment]
Perhaps we should take advice from the LFS project, especially the one regarding binutils:
```
**Important**
The test suite for Binutils in this section is considered critical.
Do not skip it under any circumstances.
```

Now running `make -k check` as last part of binutils' `do_build()` fails here!
Search for " error:" in [the binutils.log](http://misc.voidlinux.de/binutils.log) output to see how.

The error repeats for several files and always reads:
```
gcctestdir/ld: internal error in relocate, at x86_64.cc:3762
collect2: error: ld returned 1 exit status
```

The code at gold/x86_64.cc:3762 is:
```
    gold_assert(gsym->has_got_offset(GOT_TYPE_STANDARD));
```

I do not yet have an idea what to make out of this. However the entire `make -k check` fails in the end, which is certainly bad.

Perhaps something in our CFLAGS/CXXFLAGS/LDFLAGS is incompatible with how binutils expects to be built and/or tested?

**Comment by chneukirchen** [comment]
Try building binutils with nopie for a start.

**Comment by pullmoll** [comment]
Hey, good idea :)

With nopie=yes the result of `make -k check` for `x86_64-musl` is `1 of 243 tests failed` and the failing test is `/builddir/binutils-2.27/gold/testsuite/pr18689.sh`: pr18689.sh  -- a test case for compressed .debug_macro sections

It looks like what's tested here is a probable cause for my *no debug symbols in gij for x86_64-musl* case.

I'll take a close look.

**Comment by the-maldridge** [comment]
This was fixed quite some time ago but not closed.  Closing now
