### ISSUE TITLE
RFC: make check for core packages

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#5808]
This is partially related to #5801 but IMO worth a separate issue entry and discussion.

Void does not make use of the `make check` or `make test` stages which many packages, specifically core libraries and utilities, offer.

This now turned out to lead to hard to track down problems as in a case where I was baffled that debugging `gcc-gcj-6.3.0_3-x86_64-musl` wouldn't work, because `gdb` could not find symbols in the debug pkg.

I believe we should take the [LFS](http://www.linuxfromscratch.org/lfs/view/8.0-rc1/) recommendations for packages which **definitely** require a `make check` serious and strive to fix what's currently failing.

The first package to fix is obviously `binutils` because it currently fails the `make -k checks`.

IMO further ignoring failing checks for such essential packages may lead to hell on a rather short path.

I think an additional, optional function `do_check()` which, if it exists in a package's template, could be invoked by `common/xbps-src/libexec/xbps-src-dobuild.sh`. It would probably be called as the last step, just before touching `$XBPS_BUILD_DONE`.

Pro? Contra? Other suggestions?

**Comment by chneukirchen** [comment]
I think an additional step that is optionally called (why not make a new xbps-src flag for it?) is a good idea.

I sometimes run tests for important packages manually, but then you need to look up again how it works all the time.

**Comment by pullmoll** [comment]
Why make it optional? Do you think that packagers should be responsible to run the checks on package version changes and the builders would then not run them, or vice versa?

Or do you think of a flag like `XBPS_RUN_CHECKS=yes` which would be enabled by default(?) and could be disabled by xbps-src options or in your own `etc/conf`?

**Comment by chneukirchen** [comment]
Many test suites take a long time, and it may not be approriate to run them for every rebuild or bulk-build... whether default should be on or off we can discuss. But make it customizable.

**Comment by xtraeme** [comment]
Not to mention that 'make check' might also need additional dependencies...

**Comment by pullmoll** [comment]
Yeah, then perhaps at the same time introduce `checkdepends="..."`.

**Comment by zqqw** [comment]
Not all aspects of all packages are well maintained, documented, and currently working. I only tried running make check in one package, I can't remember what one, but couldn't figure out what dependencies it needed so it always failed with errors. GNU findutils had a debug build option but it failed due to commits made several years ago. When I pointed this out they deleted that option. So it's a great idea but allow for the fact that not all checks and tests might be working if nobody else uses them.

**Comment by pullmoll** [comment]
@zqqw: Defining `do_check()` in a template is optional. If it isn't there, there is no change compared to how it is now. Checking is intended primarily for core libraries and binaries, not for the average package.

If you know LFS, the packages where running `make -k check` or similar is strongly recommeded there are the main candidates for checking.

BTW if anyone wants to peer review and test my PR, you're quite welcome.

**Comment by the-maldridge** [comment]
I like the idea of running the tests on the core packages, certainly everything in base-system.  While there are extra deps as suggested by @xtraeme , there are very few packages that are in the core set.  I think we can afford the cycles to run checks for those packages.
