### ISSUE TITLE
chromium-pepper-flash: broken link

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#5852]
sudo xbps-install -S chromium-pepper-flash

requesting https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_54.0.2840.100-1_amd64.deb
https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_54.0.2840.100-1_amd64.deb: Not Found
sha256sum: chromium-pepper-flash.deb: No such file or directory
chromium-pepper-flash.deb: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
Error while extracting

**Comment by SirDoctors** [comment]
Pepper flash is deprecated by google, I would try something like [adobe-flash-plugin](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/adobe-flash-plugin) or [adobe-flash-package](https://github.com/voidlinux/void-packages/pull/5408)

**Comment by silvernode** [comment]
Tried adobe package first and it had a failed download as well.
