### ISSUE TITLE
gmusicbrowser fails to start!

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5855]
We are at least 3 persons affected by this problem:

`$ gmusicbrowser`
`Can't redeclare "my" in "my" at /usr/bin/../share/gmusicbrowser/gmusicbrowser_list.pm line 8001, at end of line
Compilation failed in require at /usr/bin/gmusicbrowser line 440.
BEGIN failed--compilation aborted at /usr/bin/gmusicbrowser line 473.`

:(

Could it be related to? https://github.com/voidlinux/void-packages/issues/4798

**Comment by ebfe** [comment]
https://github.com/squentin/gmusicbrowser/issues/135
