### ISSUE TITLE
numix-themes: fix & update to 2.6.6

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5872]
Hello,

The current numix-themes template is **wrong**, it installs in the **wrong** folder !

**in** `/usr/share/icons/numix-gtk-theme/src` **instead of** `/usr/share/themes/numix-gtk-theme`

The template is **outdated**, too. So I updated it to the **latest** version.
I just rebuilded it and it works now!

```
# Template file for 'numix-themes'
pkgname=numix-themes
version=2.6.6
revision=1
noarch=yes
short_desc="A modern flat GTK3/Metacity/Xfwm theme"
build_style=fetch
maintainer="Jakub Skrzypnik <jot.skrzyp@gmail.com>"
license="GPL-3"
depends="gtk+3 gtk-engine-murrine"
homepage="https://github.com/numixproject/numix-gtk-theme"
distfiles="${homepage}/archive/${version}.tar.gz"
checksum=5ee5ed54bea10fe23c99f1fcc614cbf593764b6310cdf889723f8c251abf0856

do_install() {
        tar xzf ${version}.tar.gz
        vmkdir usr/share/themes
        vcopy numix-gtk-theme-${version}/src usr/share/themes/numix-gtk-theme
}
```

**Comment by cr6void** [comment]
It works yes, but only with **GTK2** applications, sorry.
With **GTK3** the result is just **horrible!!**
There's obviously something missing... :(

**Comment by jcjordyn130** [comment]
I have already made a pull request. https://github.com/voidlinux/void-packages/pull/5709

**Comment by jcjordyn130** [comment]
@cr6void I think you have to compile it first with make.

**Comment by cr6void** [comment]
Yes @jcjordyn130 ,
I only made a `build_style=fetch` , like the old template, but it's not enough here!
When I look to the homepage https://github.com/numixproject/numix-gtk-theme
I can read: "First, you need to compile the theme using the Sass compiler..."
I don't know how to do that. :(

**Comment by jcjordyn130** [comment]
Read my template, line 15.

**Comment by jcjordyn130** [comment]
you need to add ruby to hostmakedepends, run 'gem install sass' then 'make ${makejobs}'.

**Comment by cr6void** [comment]
ok thank you @jcjordyn130 , I should have take a look at your work before opening a useless issue, sorry...
;)

**Comment by jcjordyn130** [comment]
it's fine ;)
