### ISSUE TITLE
musl & firefox-i18n

### ISSUE THREAD

**Issue by cr6void** [voidlinux/void-packages#5879]
Hi !

In the x86_64 musl system I can't set Firefox in my language (french).

`$ xbps-query -s firefox-i18n-fr`
`[*] firefox-i18n-fr-51.0_1 Firefox French language pack`

The right package is installed, I can see it in the "Add-ons", but it doesn't work, Firefox is still in english!

This problem could be related to the lack of locales in musl I guess? _(if true, the i18n packages for musl are useless)_
I say that because the language pack works fine on my other system i686 glibc ...

Thank you!

**Comment by newbluemoon** [comment]
You have to set the language manually: go to `about:config` and set
`intl.locale.matchOS` to `false` and change
`general.useragent.locale` to `fr-FR`

The French language pack needs to be installed, though!

**Comment by cr6void** [comment]
Perfect ! Thank you @newbluemoon
