### ISSUE TITLE
enchant:  integrating with hunspell 

### ISSUE THREAD

**Issue by onekk** [voidlinux/void-packages#588]
The default beahviour of enchant is to search all the dictionaries in /usr/share/enchant/{myspell,aspell}
but there is a configure options  --with-{myspell,apsell}-dir that could be --with-myspell-dir=/usr/share/hunspell to avoid duplication of dictionaries.

I have ready a template file for hunspell-en_US dictionaries and in project many others dicts (at least en_GB small and large version en_US large version, de_DE, it_IT and maybe others if i find a relliable and updated source), for now the workaroound is to create manually symlink the /usr/share/hunspell dir to /usr/share/enchant/myspell

regards

Carlo D.

**Comment by Vaelatern** [comment]
This was done about halfway between this issue being opened and now, in ea8f61d2, closing.
