### ISSUE TITLE
Mysterious and frequent failures when downloading over https with xbps-install or wget

### ISSUE THREAD

**Issue by CMB** [voidlinux/void-packages#5885]
I'm going to document everything I know about the problem here.
Sorry for the novel, just being thorough.

Recently (within the last month or two), I noticed that xbps-install on my
Raspberry Pi 3 would frequently quit with an I/O error while downloading
from the network.  The Pi runs an ARMv7 musl image.
The network connection is wifi.
The program tended to quit somewhere within the first megabyte or two
of a large download, but I've also seen it fail on .sig files and other
small things.
Last week, I tried to discover the cause.  After poking around in gdb,
I determined that xbps-install was terminating because of a failure in SSL_read
in libfetch, bundled with libxbps.
I added some debugging statements to the xbps source, so that I could
see the actual errors from libressl, and here's what I got:
error:060BC064:digital envelope routines:AEAD_AES_GCM_OPEN:bad decrypt.

Next I tried using wget to download similar files from Void mirrors, and
I noticed the same behavior.  A download would be canceled after a
"bad decrypt" from libressl, and then wget would restart it.

I then tried a glibc Void image, and I noticed the same behavior.
Since Void now has aarch64 images for the Raspberry Pi, I decided to try
one of those.  I saw the exact same behavior.
This time, with the aarch64 image, my network connection was ethernet, rather
than wifi.

This has all been one big adventure in WTF-land, and it gets crazier.
Today, I installed Void on a USB stick, because my girlfriend wanted to
run it on her MacBook.  When we booted the stick on the MacBook, guess what
bug appeared?  The "bad decrypt" bug.  Same scenario: failures with xbps
and wget.  The stick is fine on other hardware; it just fails on the MacBook.
The installation is x86_64-musl.
Somewhere I got the bright idea to try curl.  It never failed to download
with https.  100% success.  Then I tried curl on the Pi.  Again, no download
failures at all.
So why are xbps-install and wget failing, while curl isn't?  All three are
linked against libressl.

libressl passes its testsuite in "make check".

The only thing the MacBook and the Pi have in common is Broadcom.  The
Pi's wifi uses the brcmfmac driver, and the MacBook's uses broadcom-wl.

Starting to doubt my own sanity.

**Comment by pullmoll** [comment]
You could try to build `wget` with `gnutls` instead of `ssl` locally:
```
sudo xbps-install -S base-devel
git clone https://github.com/voidlinux/void-packages
cd void-packages
./xbps-src zap
./xbps-src binary-bootstrap
./xbps-src -o gnutls,~ssl pkg wget
```
If you want to build for `x86_64-musl`, specify `./xbps-src binary-bootstrap x86_64-musl` instead.

Then you can force install this wget with `sudo xbps-install -S -f -R hostdir/binpkgs wget` and see, if `wget` fails with `gnutls` as well.

This might narrow down the range of possible bugs, i.e. tell if it is more probably wget or libressl.

**Comment by CMB** [comment]
wget with gnutls also works fine, no failures.
So the open question is why do xbps-install and wget with libressl fail,
while curl (also with libressl) is fine?

**Comment by pullmoll** [comment]
Strange, indeed. It may have to do with how libressl is initialized or configured by these packages. Perhaps the selection of supported ciphers is different. I haven't looked into the source yet, this is just a wild guess.

**Comment by CMB** [comment]
I keep wondering if my problems aren't caused by my network.
I just noticed the exact same issue on an old Acer netbook.
It is i686 glibc,
and it uses a wireless connection.

There's also another wrinkle: affected machines also fail to clone repos
using the git:// protocol.  Clone fails with an error like the following:

error: inflate: data stream error (incorrect data check)
fatal: pack has bad object at offset 279865: inflate returned -3
fatal: index-pack failed

That's apparently an error from zlib.  Something failed a crc32 check.
I've noticed these on all of the affected machines.

Cloning over https or http never fails.

Oh, and downloading over plain http is fine with wget, just https is
affected.

**Comment by chneukirchen** [comment]
Which glibc version do you use? 2.25? Please post /proc/cpuinfo too.

**Comment by CMB** [comment]
The Pi 3 and the MacBook are both musl installs.  The glibc image that I tested
on the Pi 3 did have 2.25.
The Acer netbook had the failures with both glibc 2.24 and 2.25.
On the netbook, failures from both wget and xbps-install go away when I
switch to ethernet.  On the Pi 3, the wget failures go away on ethernet,
but xbps-install continues to fail with "bad decrypt".

/proc/cpuinfo for the Raspberry Pi 3: http://sprunge.us/MBFR
/proc/cpuinfo for the MacBook: http://sprunge.us/ObQb
/proc/cpuinfo for Acer NetBook: http://sprunge.us/ZRTj

I'm really starting to wonder whether it's a problem with my network.
Just tested an Arch stick from last month on the Acer, and it's getting
the same bad decrypt errors with wget and openssl.
The biggest commonality between any of these setups seems to be my
network, mostly wifi.

**Comment by chneukirchen** [comment]
If you fetch a file via http multiple times, do the files match?

**Comment by chneukirchen** [comment]
FTR, glibc 2.25 on N270 is seriously broken currently.

**Comment by CMB** [comment]
Yes, the files match when downloading over HTTP.  Also I've downloaded
known things and checked sha256 sums, and there's no corruption.

**Comment by chneukirchen** [comment]
If you have a remote server, you could try using SOCKS proxying (e.g. `-D 5555`) and fetch over that, and see if corruption happens too... then it would be your network / ISP.

**Comment by CMB** [comment]
Tried with socks proxying and wget running under proxychains, no errors
at all.  I also remembered to reinstall stock wget built against
libressl.  Yesterday I was seeing wget downloads succeeding; I forgot I
had rebuilt it against gnutls.

**Comment by chneukirchen** [comment]
If you use curl, does it use HTTP/2.0?  (Somehow this sounds like a deep packet inspection gone wrong.)

**Comment by CMB** [comment]
Yes, curl uses HTTP/2.  I forced it to use HTTP/1.1 and HTTP/1.0 for
testing just now, and I get the same result, no error.

The other curious thing is that I've never seen any of this failure on
my primary machine, which I'm using to write this message.  It's
using an ethernet connection on the same network as the failing
devices.  In fact, if I make the Pi use that local box as a socks proxy,
I also don't have errors.

**Comment by chneukirchen** [comment]
Since you get the same errors on Arch, I doubt it's a Void-related issue...
