### ISSUE TITLE
Errors: Nvidia 304.135 and the latest 4.10.1_1 kernel

### ISSUE THREAD

**Issue by AngryPhantom** [voidlinux/void-packages#5886]
Hello everybody!

I'm new to Void but I like it and really want to make it my desktop OS. I've been using Debian for years already and try other distros from time to time (mostly from Live CDs and USBs).

After installing the latest Void (from void-live-i686-20170220-cinnamon.iso and/or void-live-i686-20170220-mate.iso) I couldn't install the proprietary 'nvidia304.135' driver against the updated 4.10.1_1 kernel. I'm getting all these errors like: 'DKMS module failed to install' etc., as well as some error like 'kernel/nvidia/nv-pat.c'. I'm sorry I didn't copy the log file and I'm posting this from Debian.
The thing is that I have 7600 GT video card and the only choice for me is 304.xxx drivers.
Well, I tried to install 340.xxx for the fun of it and it compiled OK, but everything I get is 'nvidia device not found' since this branch doesn't support my video card.

Every solution I've tried doesn't work for me unfortunately. I also found this [patch](https://github.com/voidlinux/void-packages/blob/da8070d45f11cbdec29a78e7c884b6f63c1ba842/srcpkgs/nvidia/files/kernel_4.10.patch) here on github but I don't know how to apply it actually and whether it is appropriate for my situation since I'm very new to Void Linux.

Btw, sorry if I posted in a wrong thread, I guess it should be in 'issues'.

How to reproduce it: simply install Void with 7600 GT NVidia or older, **update the system** and try to install 'nvidia304.135' drivers. That's all you have to do.

Void Team, please fix this. Thank you in advance!

**Comment by AngryPhantom** [comment]
P.S. After installing Void you need to **update the system**. Hmm, I've got an idea: I'll try to install the driver first without updating... I will let you know soon!

**Comment by Gottox** [comment]
installing nvidia304 works for me. Can't test the module though as I don't own an nvidia card.

Can you post the output of /var/lib/dkms/nvidia/304.135/build/make.log after the build failed?

**Comment by AngryPhantom** [comment]
Excuse me, could you tell me how to apply this patch? Thank you.
