### ISSUE TITLE
Package request: mldonkey

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#5929]
http://mldonkey.sourceforge.net/

(received via private mail)

**Comment by cr6void** [comment]
Hello @chneukirchen !

Today I created a first draft of this template for you, not sure if it's 100% correct, look:

`# Template file for 'mldonkey'
pkgname=mldonkey
_release=release-3-1-6
version=3.1.6
revision=1
build_style=gnu-configure
hostmakedepends="autoconf camlp4 ocaml ocamlbuild wget"
makedepends="glib-devel ncurses-devel"
short_desc="A multi-platform, multi-network p2p daemon"
maintainer="local <root@localhost>"
license="GPL-2"
homepage="http://mldonkey.sourceforge.net/"
distfiles="https://github.com/ygrek/${pkgname}/archive/${_release}.tar.gz"
checksum=632735d835c33d9815ae64aa8d4abb61b1bd8dd6c55ef66694f9254c97c2877d
wrksrc=${pkgname}-${_release}

do_install() {
        vmkdir usr/bin
        vcopy mlnet usr/bin
}`

I also copied the text from [Install.txt](https://github.com/ygrek/mldonkey/blob/master/distrib/Install.txt) to create an INSTALL.msg like this:

`-If you want to get up and running quickly and easily-

Start 'mlnet'

Leave the terminal window open. MLdonkey is now running.

Open a browser and type in the URL http://localhost:4080 <enter>.
A web-based interface to MLdonkey appears. Certain ports enabling
inbound routing on your firewall/router need to be opened to fully
use MLdonkey. The Options tab in the web interface shows the ports.

Downloaded files will be found in sub-directory incoming/, while
files to be shared should be in a sub-directory called shared/.

-You're done!-`

I successfully builded this package on my Void i686, see [the log](https://pastebin.com/S7PBTr3y) ...

Regards. :wink:
