### ISSUE TITLE
Maim can't grab selection

### ISSUE THREAD

**Issue by 0rdy** [voidlinux/void-packages#5932]
```
maim -s 
No file specified, using /home/ordy/1488992595.png
Slop encountered an error:
Invalid argument `-g`.
Selection was cancelled or slop failed to run. Make sure it's installed!
```

Also version of the maim package is out of date.

**Comment by E100Beta** [comment]
@0rdy, yes, maim is rather old at this point. https://github.com/voidlinux/void-packages/pull/5931 will fix it as soon as it gets merged.

**Comment by 0rdy** [comment]
@E100Beta Thanks for script, but now maim is completely broken cause I even can't take any screenshot. The terminal output looks like that:
![2017-03-08-235517_959x522_scrot](https://cloud.githubusercontent.com/assets/9018005/23725890/f5374078-045a-11e7-8de0-5191c66b387d.png)

**Comment by E100Beta** [comment]
@0rdy are you absolutely sure you specified filename (like `maim -s screenshot.png`)? I have the same issue (issue being the fact that image is outputted to `stdout`) if I forget to specify it with `-s` flag.
P.S. I know this place may be too serious to point that out, but one of bottom lines is filled with 'XDDDDDDDDDDD'.

**Comment by 0rdy** [comment]
@E100Beta oh, sorry for that, I have to read the maim changelog before asking. Now I see the following in Readme.md `Maim cleanly pipes screenshots directly to standard output (unless otherwise specified).` It looks odd for me. 

Thanks again for updating the package.
