### ISSUE TITLE
lxqt-panel fails to display some icons 

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#5934]
After the update of qt to 5.8.0, I noticed that some icons that were displayed previously in the lxqt-panel were not displayed any more. A screenshot to illustrate the issue can be found [here](https://owncloud.helmut-pozimski.de/index.php/s/TS1u8L3I1qf5GYg). So all the icons for the categories are missing and some but not all of the application icons. Also affected is the widget to display the desktop which usually is represented by an icon but now only displays the text.

I couldn't find any relevant error messages in any of the usual log files so I'm relatively clueless about what exactly is causing the issue. It's only clear that it first appeared after the qt update to 5.8.0. To manually reproduce the issue:

1. Install from the 20170220 lxqt image by copying the image to disk
2. Install oxygen-icons (otherwise lxqt-panel doesn't have any to display)
3. Verify that the icons are displayed
4. Update the system
5. The icons are not displayed any more

**Comment by cr6void** [comment]
Hello @Hoshpak ,
The default icon theme for LXQT is called `breeze-icons`
`breeze-icons` is listed in the dependencies of [lxqt template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/lxqt/template)

**Comment by Hoshpak** [comment]
Indeed, that's also installed but makes no difference. Switching to breeze or even the gnome icon theme leads to the same result, a lot of icons not being displayed.

**Comment by ebfe** [comment]
Maybe #5927

**Comment by Hoshpak** [comment]
I tried that yesterday and it didn't resolve the issue. Tried it again today and it's fixed. I must have forgotten to install one of the rebuild packages yesterday. So this issue can be closed as soon as #5927 gets merged.

**Comment by Hoshpak** [comment]
@pullmoll was even faster, thanks.
