### ISSUE TITLE
dmd: says 'GPL-2' on license, but is actually nonfree

### ISSUE THREAD

**Issue by kazblox** [voidlinux/void-packages#5955]
DMD's frontend is licensed under the Boost license, but the backend from Symantec has a license for personal use only.

Therefore, dmd must be marked as nonfree software and must be moved to the 'nonfree' repo.

**Comment by chneukirchen** [comment]
To follow the license closely, we actually need to remove the binary package completely.

I guess everyone is unhappy about this license issue. Arch simply redistributes it...

**Comment by chneukirchen** [comment]
Soon obsolete: https://github.com/dlang/dmd/pull/6680
