### ISSUE TITLE
base-files: sysctl prints 'cannot stat' messages during boot on Raspberry Pi (armv6l)

### ISSUE THREAD

**Issue by amak79** [voidlinux/void-packages#5956]
sysctl prints the following messages during boot on Raspberry Pi (armv6l):

```Applying /usr/lib/sysctl.d/void.conf ...
sysctl: cannot stat /proc/sys/kernel/kexec_load_disabled: No such file or directory
sysctl: cannot stat /proc/sys/kernel/yama/ptrace_scope: No such file or directory
```

This is caused by commit https://github.com/voidlinux/void-packages/commit/a8fa975f9fb60752eb5d03bc2c19132141d651e9. The kernel config options `CONFIG_KEXEC` and `CONFIG_SECURITY_YAMA` are undefined/not set for the Raspbery Pi kernel. The messages go away if I comment out the relevant lines in `/usr/lib/sysctl.d/void.conf`, but they return when the base-files package is updated.

**Comment by pullmoll** [comment]
Adding `-e` to the sysctl call in `/etc/runit/core-services/08-sysctl.sh` line 13 should suffice. If you give it a try and it works, an update for `runit-void` should be no problem.

**Comment by amak79** [comment]
Adding `-e` silenced the messages. Thank you.

**Comment by amak79** [comment]
What is the status of this issue?
