### ISSUE TITLE
qt5 needs to be patched to work with libressl

### ISSUE THREAD

**Issue by zx2c4** [voidlinux/void-packages#5998]
Qt5 has code like this in `qsslcontext_openssl.cpp`:

```c++
    case QSsl::TlsV1_2:
#if OPENSSL_VERSION_NUMBER >= 0x10001000L
        sslContext->ctx = q_SSL_CTX_new(client ? q_TLSv1_2_client_method() : q_TLSv1_2_server_method());
#else
        // TLS 1.2 not supported by the system, but chosen deliberately -> error
        sslContext->ctx = 0;
        unsupportedProtocol = true;
#endif
```

Since you're building against libressl headers, things aren't what you'd hope, and so you do a lot of patching.

Right now you patch this as:

```diff
-#if OPENSSL_VERSION_NUMBER >= 0x10001000L
+#if (OPENSSL_VERSION_NUMBER >= 0x10001000L) && !defined(LIBRESSL_VERSION_NUMBER)
```

That's probably not correct, since it always goes to the error path.

**Comment by Duncaen** [comment]
libressl defines `OPENSSL_VERSION_NUMBER`.

/usr/include/openssl/opensslv.h:
```
#define OPENSSL_VERSION_NUMBER  0x20000000L
```

**Comment by zx2c4** [comment]
But your patch changes the line to:

```
#if (OPENSSL_VERSION_NUMBER >= 0x10001000L) && !defined(LIBRESSL_VERSION_NUMBER)
```

So it always falls to the error case.

**Comment by Duncaen** [comment]
Oh I see, we really need some better way to review/test all the libressl patches.
Its definitively too easy to make such mistakes which could be really bad.

**Comment by zx2c4** [comment]
> Its definitively too easy to make such mistakes which could be really bad.

This is one such mistake, unfortunately. :(
Can this ticket be assigned to whoever does the Qt stuff for y'all?

**Comment by pullmoll** [comment]
Thank you! Well, this is going to be a tedious job: 48 patches to inspect and validate ;-P

**Comment by pullmoll** [comment]
Ok, the TLSv1_{1,2}_{client,server}_method are available in libressl and thus a good number of patches are wrong. I [stripped them from the patch](http://misc.voidlinux.de/libressl-compat.patch) in a first round. 41 patches left.

**Comment by pullmoll** [comment]
Patches validation
- [x] TLSv1_{1,2}_{client,server}_method available in libressl; related patches removed
- [x] EC_curve_nist2nid not available in libressl; patches must remain
- [ ] SSL_{set,get}_ex_data, SSL_get_ex_new_index are available in libressl.
      Need to closely inspect the related patches.
- [x] SSL_set_psk_{client,server}_callback not available, i.e. related patches must remain
       or I could perhaps use -DOPENSSL_NO_PSK
- [ ] more to come...
