### ISSUE TITLE
Tracking issue: Python 3.6

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#6023]
Python 3.6.1 is there, requiring a full rebuild of all Python 3 packages.

---

Thanks to @asergi for doing this bump!

Fallout:
~~- [x] python-tornado depends on python-backports_abc which has 3.5 stuff?~~

- [x] python3 alternative gets lost during update? (even needed?)
- [x] lots of obsolete python3.4 _transitional dummy_ packages can be removed now, 10 months after python 3.5

~~- [x] python-ipython_ipykernel fails to build on aarch64 builder (but not locally oO)~~

**Comment by scadu** [comment]
Is there any news on this? I assume the only reason why it hasn't been done yet is the scale of rebuild.

**Comment by magicgoose** [comment]
3.6.2 is out now, so probably should jump right to it, skipping 3.6.1

**Comment by Epictek** [comment]
Arch is already on Python 3.6, Would be really nice if Void would update Python

**Comment by ibabushkin** [comment]
The python3-alternative is needed, as some stuff relies on the symlink, e.g. `ranger`.
Running on a completely updated system (zsh, `python3` installed):

```sh
$ rifle some.pdf
zsh: /usr/bin/rifle: bad interpreter: /usr/bin/python3: no such file or directory
$ which python3
python3 not found
```

**Comment by chneukirchen** [comment]
The alternative is not needed because we only have one python3.

**Comment by ibabushkin** [comment]
On 2017-08-28, Leаh Neukirchen wrote:
> The alternative is not needed because we only have one python3.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/issues/6023#issuecomment-325404147

Makes sense. A `python3` symlink is, however. What about the tons of
`python3.4-*` packages though (those initially confused me to believe
that we *do* have more than one python 3)?

**Comment by Epictek** [comment]
Surely python3.4-* packages can be updated to python3.6-* will likely involve a lot of work but will be better than maintaining 2 versions of python3

**Comment by Duncaen** [comment]
`python3.4-` packages are a relict from the times we had a `python3.4` package.
All packages were renamed to `python3-` and `python3` for `python3.5`. 
They are just meta packages that depend on `python3-${pkgname/python3.4-//}`.

**Comment by Hoshpak** [comment]
p7 reported in IRC that libixion11 and liborcus11 still need to be rebuilt, I created #7524 for that. Besides that, two more packages still seem to link to python 3.5:

```
python3-editdistance-0.3.1_1: libpython3.5m.so.1.0 (https://repo.voidlinux.eu/current)
python3-regex-2017.06.23_2: libpython3.5m.so.1.0 (https://repo.voidlinux.eu/current)
```

python3-regex was removed from void-packages in 9130426b346c9a76d0f1a112f36c36cb7829caaf , the other one in 6771d706a35272b9d00a98dcb45654733b7b782e . Perhaps these should be removed from the repository to ensure they won't cause confusion in the future.

**Comment by asergi** [comment]
> python-tornado depends on python-backports_abc which has 3.5 stuff?

`python-backports_abc` is needed for Python < 3.5

> pytthon3 alternative gets lost during update? (even needed?)

It's a `xbps-alternatives` issue. That said, the `python3` alternatives group is a legacy of the old `python3.4` package when we could have multiple python3.x versions at the same time. OK to remove now.

> lots of obsolete python3.4 packages can be removed now, 10 months after python 3.5

It's on the roadmap. Hope 10 months are enough.

> python-ipython_ipykernel fails to build on aarch64 builder (but not locally oO)

Cannot reproduce. I guess is like the `ctop` package, it fails to detect the default locale/encoding and fallback to C locale.

> p7 reported in IRC that libixion11 and liborcus11 still need to be rebuilt, I created #7524 for that.

Both weren't update on purpose. They're no longer needed since 700b682a5472228d5b0813e0ff108dbe19725a6b and should be removed instead.

**Comment by chneukirchen** [comment]
Yes, just set the alternative again.
