### ISSUE TITLE
There needs to be a way to hide maintainers' emails from spammers.

### ISSUE THREAD

**Issue by crocket** [voidlinux/void-packages#6027]
If emails were exposed to the public internet, spammers would find a way to mine them.
Maintainers' emails are exposed to the public internet.

We can find other ways than email to contact maintainers.

AUR protects email addresses by hiding email addresses and providing a communication interface.

**Comment by Anachron** [comment]
How about encrypting them? And let xbps decrypt them.

**Comment by crocket** [comment]
That makes it less likely for spammers to access email addresses, but it will still allow any void system to look up email addresses.

On AUR, only moderators have access to emails. Thus, it is more secure.

**Comment by Duncaen** [comment]
No, mail is the standard method to communicate on the internet every one does it, forcing some other method like github or a self build platform is not better.
I don't see the problem here, you have to use spam filters anyway, there are other sources that expose mail addresses and are more likely to be abused.

**Comment by crocket** [comment]
> forcing some other method like github or a self build platform is not better.

I'd like you to substantiate your opinion although it seems you just don't want to spend energy into fixing this problem.

**Comment by Vaelatern** [comment]
No you can not, it won't be merged.

**Comment by crocket** [comment]
I just received a notification email triggered by Toyam Cox.
He said `No you can not, it won't be merged.`. But, I cannot see his comment here.
Can I interpret it as an agreement that void-packages do not force people to use only email addresses for contact information?

**Comment by Duncaen** [comment]
No, email is the standard and we don't want to have different methods per package.
Maybe we can get a mailing list address like `bugs@voidlinux.eu` for packages that are not maintained by a specific person or contributors that don't want to provide their mail address.

**Comment by zqqw** [comment]
Some mail accounts allow disposable addresses to be created, so you can delete them if they get too much spam. I've had to change my email address before to get rid of spam, and that's a real time consuming nuisance. Publishing email addresses online is totally outdated and insecure. Anywhere this happens results in spam being received and it still ends up in the spam box and wastes time checking it isn't something important. Sometimes genuine emails go in the spam box too. Often these emails are dangerously deceptive phishing or fraud, I know people who have had to contact the police and close bank accounts as a result of 'spam', it is no joke. Git Hub hides mail addresses but be careful not to use it to sign in to other sites, as they sometimes reveal your Git Hub email and then yes, spam is the inevitable result. Using a website with a contact form protected by a captcha is a good way to allow user feedback and seems to be totally spam free for me so far, but xlint won't accept anything except an email address in the field.
My favourite spam was the one supposedly from the scantily clad Russian girl who wanted to get to know me better, not that I answered, but few are that entertaining.
