### ISSUE TITLE
Weechat Perl Support on Raspberry Pi

### ISSUE THREAD

**Issue by seisatsu** [voidlinux/void-packages#6066]
There appears to be no support for perl plugins on the raspberry pi build of Weechat, nor is a perl plugin packaged. From the looks of the Weechat template, the perl plugin is intentionally not built for the arm repos. A lot of the more important plugins use perl; can we fix this?

**Comment by Duncaen** [comment]
It does not work when cross compiled, this must be fixed.
You can build it locally on your hardware to get perl support.
