### ISSUE TITLE
lldb: unable to enter commands, keypresses echo as escaped Unicode

### ISSUE THREAD

**Issue by ackalker** [voidlinux/void-packages#6073]
Void Linux x86_64 (glibc).

When I run `lldb` from a Bash shell (tried both URxvt and a text VT), I'm unable to execute any commands, also any keys I press echo as some kind of escaped Unicode representations.

Output from running `lldb` and typing `help RET ^D`, twice, to show different outcomes. At the end of the second try, `^D` alone didn't exit from `lldb` so I tried hitting `RET ^D` a few more times before giving up, then I suspended and forcibly killed the `lldb` process:
```shell
$ lldb
(lldb) \U+0868\U+0865\U+086C\U+0870
error: empty command
(lldb) \U+0804
$ lldb
(lldb) \U+20168\U+20165\U+2016C\U+20170\U+2010A\U+20104\U+2010A
[1]+  Stopped                 lldb
$ kill %
[1]+  Terminated              lldb
$
```
When I tried `LC_ALL=C LANG=C lldb` I got similar results.
```shell
$ xbps-query -p pkgver lldb
lldb-3.9.1_2
```
```shell
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by ackalker** [comment]
Piping a command into `lldb` works without problems, for example `echo "help" | lldb`. This seems to indicate some problem with keyboard input or terminal handling.

**Comment by chneukirchen** [comment]
See https://bugs.archlinux.org/task/49974

**Comment by ackalker** [comment]
Thanks!

**Comment by chneukirchen** [comment]
At least ASCII chars work with the wchar override...

**Comment by ackalker** [comment]
Thanks for looking into this! :-)
