### ISSUE TITLE
nim: nimble crashes due to missing compatible libcrypto.so version, creates 0-byte executables

### ISSUE THREAD

**Issue by asiekierka** [voidlinux/void-packages#6087]
[... ~]$ nimble
    could not load: libcrypto.so(|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8)
    compile with -d:nimDebugDlOpen for more information

All packages updated to latest as of creating this issue; in particular, nim 0.16.0_1 and libressl 2.4.5_3.

**Comment by asiekierka** [comment]
Editing lib/wrappers/openssl.nim from:

    versions = "(|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8)"

to

    versions = "(|.39|.38|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8)"

seems to work fine.

**Comment by asiekierka** [comment]
In addition, installing aporia with nimble seems to create a 0-byte "aporia" executable file. Running "nim c aporia.nim" in the folder seems to work fine, however.

**Comment by asiekierka** [comment]
https://github.com/nim-lang/Nim/issues/4893

**Comment by allan** [comment]
I cannot reproduce your errors.  Nimble was just updated to 0.8.4.  Do you still have issues?

**Comment by asiekierka** [comment]
With nim 0.16.0_2, the first issue persists.

>could not load: libcrypto.so(|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8)
>compile with -d:nimDebugDlOpen for more information

Testing the second issue requires fixing the first one, naturally.
