### ISSUE TITLE
03-rewrite-python-shebang.sh: why rewrite versioned shebangs?

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#6151]
03-rewrite-python-shebang.sh currently rewrites shebangs that are exactly `#!/usr/bin/python2` and `#!/usr/bin/python3`, resulting in a wrong shebang 50% of the time. ;)

I think it should only rewrite unversoned python and overly specific (3.5 to 3).

**Comment by Gottox** [comment]
Can you provide a package with the wrong behavior?

**Comment by chneukirchen** [comment]
E.g. a package that doesn't depend on python at all, contains a python script with #!/usr/bin/python3 is rewritten to #!/usr/bin/python2 (e.g. rlwrap-0.43 without overriding python_version=)

**Comment by Gottox** [comment]
so, the right behavior should be to stop the build process if a shebang is detected without the corresponding python dependency?

**Comment by chneukirchen** [comment]
Not sure, I don't want to depend rlwrap on python3 just because some plugins could possibly use it...

(Also, depending on python is not enough to fix the version, you need to set python_version...)

**Comment by Gottox** [comment]
so make python_version mandatory if it can't be auto detected.

**Comment by chneukirchen** [comment]
Assume a project that contains a python2 and a python3 script (not sure that exists, but it could be possible...), the hook will still fuck it up.
