### ISSUE TITLE
Package Request: syncthing-inotify

### ISSUE THREAD

**Issue by go2null** [voidlinux/void-packages#6157]
[Syncthing](https://github.com/syncthing/syncthing) is already [packaged](https://github.com/voidlinux/void-packages/tree/master/srcpkgs/syncthing).

`syncthing-inotify` code is [here](https://github.com/syncthing/syncthing-inotify).

**Comment by Piraty** [comment]
You could package it yourself, the pkgbuild of archlinux doesn't look that hard...

**Comment by maxice8** [comment]
package is now available as of 21/09/17 on commit 73cfcc8b4b8a42458149fa1e79f9e9c505370c8e
