### ISSUE TITLE
libGL for i686-musl

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#6189]
I think the following lines in `srcpkgs/libGL/template` are meant to cover the i686 multilib case:
```
case "$XBPS_TARGET_MACHINE" in
        i686*) configure_args+=" --with-dri-driverdir=/usr/lib32/xorg/modules/drivers";;
        *) configure_args+=" --with-dri-driverdir=/usr/lib/xorg/modules/drivers";;
esac
```
For i686-musl we do not support multilib and thus the drivers should be in `/usr/lib/xorg/modules/drivers` where the subpackages expect them to be - just as in all other cases.

So the `i686*)` should really be `i686)`, no?

Edit: FWIW after changing this line locally I can continue to build the i686-musl packages to see if one of the desktop environments will work.

**Comment by xtraeme** [comment]
Right
