### ISSUE TITLE
Newsbeuter - STFL Parser Error near

### ISSUE THREAD

**Issue by neton-bricio** [voidlinux/void-packages#6206]
I have a problem running newsbeuter using **Musl**. See what appears on terminal.

> XDG: configuration directory '/home/$USER/.config/newsbeuter' not accessible, using '/home/$USER/.newsbeuter' instead.
> Starting newsbeuter 2.9...
> Loading configuration...done.
> Opening cache...done.
> Loading URLs from /home/$USER/.newsbeuter/urls...done.
> Loading articles from cache...done.
> STFL Parser Error near ''.
> Aborted

**Comment by neton-bricio** [comment]
any sugestion for this bug?

**Comment by ebfe** [comment]
https://github.com/akrennmair/newsbeuter/issues/364
