### ISSUE TITLE
Update the nim package manager

### ISSUE THREAD

**Issue by 0rdy** [voidlinux/void-packages#6208]
The latest version of [nimble is 0.8.4](https://github.com/nim-lang/nimble/releases), which fixes some important bugs, but we have [0.8.2](https://github.com/voidlinux/void-packages/blob/7b2e94d2b5178219127bd2c6142f7c2c3ec2f70f/srcpkgs/nim/template#L6).

**Comment by allan** [comment]
updated in 20b75fc416c3a7dcad94155b7b5db9bf273e017b
