### ISSUE TITLE
vkpurge not working on arm (rpi)

### ISSUE THREAD

**Issue by engblom** [voidlinux/void-packages#6225]
```
$ vkpurge
vkpurge is x86 specific, exiting...  
```
Please make vkpurge also to support rpi, so one would not need to clean out old kernels as often as the kernel is updated.

**Comment by Duncaen** [comment]
I don't get it, there is just one kernel at a time with `rpi-kernel`.

**Comment by engblom** [comment]
I have been cleaning up everything as the card got full, but now again after latest update I have under /boot:
vmlinux-4.10.10_1*
vmlinux-4.10.11_1*
vmlinux-rpi3*
System.map-4.10.10_1*
System.map-4.10.11_1*
config-4.10.10_1*
config-4.10.11_1*

And under /lib/modules:
4.10.10_1/
4.10.11_1/

The boot partition gets easily full if one does not frequently clean up and the module libraries are not small either. This is especially a problem when running from small SD cards.

**Comment by engblom** [comment]
In case there is a difference between the rpi images, I need to add that I am running aarch64 on rpi3.
