### ISSUE TITLE
Package Request: xst

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#6247]
If I add https://github.com/neeasade/xst to the void packages, will it be accepted?

It's a fork of st with many patches included and additional features like Xresources compliance.

**Comment by chneukirchen** [comment]
It doesn't have releases, so probably no.

**Comment by Anachron** [comment]
There is a first release now,- I'll try to submit a package.

**Comment by maxice8** [comment]
resolved at https://github.com/voidlinux/void-packages/commit/50159591e9550f9c31a5481d55ce7bbfb338bcc1

@the-maldridge
