### ISSUE TITLE
zathura-pdf-mupdf building with wrong version of libjpeg

### ISSUE THREAD

**Issue by inefarius** [voidlinux/void-packages#6264]
Mupdf throws the following error with documents containing jpeg images:
`Wrong JPEG library version: library is 80, caller expects 90`
It's looking for version 9, but libjpeg turbo only supports up to version 8.

I found a similar issue with Arch Linux here: https://bugs.archlinux.org/task/34590

**Comment by ebfe** [comment]
Seems fixed with a785d317884a09671ff4e27980001644577ab612
