### ISSUE TITLE
tlmgr missing from texlive-bin

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#6268]
Good day,

I have installed texlive-bin and it warns me a fair bit to use only `tlmgpr`. The problem is that there is no such a file in `/opt/texlive/2016/bin/x86_64-linux/`
```

❰root❙~❱✘≻ ls /opt/texlive/2016/bin/x86_64-linux/
afm2tfm*      dvipdfm@   dvitomp@    gftopk*   kpseaccess*    latex@            luatex*     mfplain@  mkofm*     mktexpk*   pdflatex@  texlua@
bibtex*       dvipdfmx@  ebb@        gftype*   kpsereadlink*  luajittex*        makeindex*  mft*      mktexfmt@  mktextfm*  pktogf*    texluac@
dvilualatex@  dvipdft*   extractbb@  gsftopk*  kpsestat*      lualatex@         mf*         mkindex*  mktexlsr*  mpost*     pktype*    texluajit@
dviluatex@    dvips*     gftodvi*    inimf@    kpsewhich*     luaotfload-tool@  mf-nowin*   mkocp*    mktexmf*   mptopdf@   texhash@   texluajitc@
```

Am I missing something?

There are two files with that name, but they are scripts:
```

❰eichhorn❙~❱✔≻ xbps-query -f texlive2016-bin | grep tlmgr
/opt/texlive2016-installer/texmf-dist/scripts/texlive/tlmgr.pl
/opt/texlive2016-installer/texmf-dist/scripts/texlive/tlmgrgui.pl
```

And the INSTALLMSG warned me explicitly not to use the scripts there:

```
  WARNING: To avoid messing up your TeXLive installation, DON'T use
  the installation scripts in /opt/texlive-installer.
```

**Comment by xelxebar** [comment]
That's odd. I have `tlmgr`:

```
$ xbps-query -s texlive
[*] texlive-bin-2016_1     TeX Live Binary distribution through tl-install (newest version)
[*] texlive2016-bin-2016_1 TeX Live Binary distribution through tl-install

$ which tlmgr
/opt/texlive/2016/bin/x86_64-linux/tlmgr
```

In fact, it looks like your `/opt/texlive/2016/bin/x86_64-linux` is missing a bunch of stuff---`xetex`, `udpmap` *etc*. Are you sure something else didn't nuke your texlive installation inadvertently?

For good measure, what repos are you using? Here are mine:

```
$ xbps-query -L
 7931 https://repo.voidlinux.eu/current (RSA signed)
   42 https://repo.voidlinux.eu/current/nonfree (RSA signed)
```

**Comment by Vintodrimmer** [comment]
Strange. 

I use the default installation and tried right after the install.
```

❰eichhorn❙~❱✘≻ xbps-query -L
 7931 https://repo.voidlinux.eu/current (RSA signed)
❰eichhorn❙~❱✔≻ xbps-query -s texlive
[*] texlive-bin-2016_1     TeX Live Binary distribution through tl-install (newest version)
[*] texlive2016-bin-2016_1 TeX Live Binary distribution through tl-install
❰eichhorn❙~❱✔≻ which tlmgr
which: no tlmgr in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/texlive/2016/bin/x86_64-linux)
❰eichhorn❙~❱✘≻ sudo xbps-install -Su^C
❰eichhorn❙~❱✘≻ sudo xbps-install uzbl-tabbed^C
❰eichhorn❙~❱✘≻ file (which tlmgr)
which: no tlmgr in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/texlive/2016/bin/x86_64-linux)
Usage: file [-bcEhikLlNnprsvzZ0] [--apple] [--extension] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]
ding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]

```

Might this be because of the shell I use? Default for both root and user is `fish`, which is partially incompatible with `bash`. I will try reinstalling it with bash and report.

Also, is it OK that after removal and `xbps-remove -Oo` the folder `/opl/texlive2016` remains?

**Comment by Vintodrimmer** [comment]
I have found the problem.

Even if it does not succeed in the installation, it runs post-install and sets the status to "installed". So you can even instantly cancel an installation and it will list everything as installed and working.

In other words, download of the `tlmgr` failed, so the process stopped and I got an incomplete texlive distribution.

Not sure if it can be counted as a bug or not.

**Comment by chneukirchen** [comment]
I think the XBPS post hooks can't fail, so this goes unnoticed... I don't have ideas for improvement.

**Comment by Vintodrimmer** [comment]
Well, turns out it is impossible to make XBPS aware of the process.

What do you think about adding a warning to the INSTALL.msg?
