### ISSUE TITLE
Package request: OpenSceneGraph

### ISSUE THREAD

**Issue by NeoChontrix** [voidlinux/void-packages#6281]
http://www.openscenegraph.org/

I'm trying to package OpenMW, bu I'm failing to build a package for OpenSceneGraph (cmake creates a lib64 folder instead of an lib folder and idk how to properly handle it).
My "work" so far https://github.com/NeoChontrix/void-packages/commit/d5f57b956985f36fdfc77c67e5754d04a90188bc
(I hard coded the Endianess to little, since I don't know how to let it detect in my musl build enviroment and OpenMW itself only works on litttle Endian systems (compiles also on big Endian but has some bugs when tryting to play)

**Comment by ebfe** [comment]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/osg/template
