### ISSUE TITLE
neovim: fails to start

### ISSUE THREAD

**Issue by aeosynth** [voidlinux/void-packages#6309]
```
> nvim
nvim: symbol lookup error: nvim: undefined symbol: termkey_hook_terminfo_getstr
```

possibly related to https://github.com/neovim/neovim/issues/6356

> So the problem arises if libtermkey is installed, and Neovim wants to use a bundled version, which then fails because it does not use the bundled version when linking.

**Comment by renatocf** [comment]
I was having this error on Arch Linux since I updated Neovim from version 0.1.7 to 0.2.0. The problem was that I had installed `libtermkey-bzr` instead of `libtermkey`. I replaced the package and everything worked fine!
