### ISSUE TITLE
brother-brscan3: possibly incorrect license

### ISSUE THREAD

**Issue by pienjo** [voidlinux/void-packages#6313]
The template of brother-brscan3 (a SANE driver for certain Brother multi-functionals) claims that this package is licensed under the GPL v2. This is not entirely correct - it uses a rather peculiar shrink-wrap license; see 

http://www.brother.com/agreement/English_sane/agree.html

(Note that the Brother website is inconsistent - depending on the model of printer and/or language it sometimes uses a *different* shrinkwrap license for the very same (binary) package, but the gist is the same)

Is this a concern? I'm working on a template for the related 'brother-brscan4' package (which targets a different line of printers), and I'd like to do The Right Thing there as well

**Comment by the-maldridge** [comment]
Go ahead and build your package with the same license and then we can work out the license issues during PR review.

**Comment by pienjo** [comment]
I already did :)

https://github.com/voidlinux/void-packages/pull/6325

**Comment by the-maldridge** [comment]
Go ahead and vlicense whatever shinkwrap license you get, and I suspect that the GPLv2 in the other template may refer to the template itself, and to certain internal components of the package.
