### ISSUE TITLE
Package Request: youtube-viewer

### ISSUE THREAD

**Issue by neton-bricio** [voidlinux/void-packages#6315]
Very great command line Youtube client for GNU/Linux.

[youtube-viewer project](youtube-viewer) > [Realeases](https://github.com/trizen/youtube-viewer/releases)

**Comment by Vaelatern** [comment]
you may be interested in `youtube-dl` and `mpv`.
example usage: `mpv https://www.youtube.com/watch?v=2m_TeJDVIIw`

**Comment by neton-bricio** [comment]
@Vaelatern Using MPV I need access to the site to obtain a url.

With youtube-viewer can search terms using the terminal.

[See video demonstratios](https://www.youtube.com/watch?v=YzN2scO025I).

youtube-viewer is very cool.

**Comment by IbnSaeed** [comment]
excellent find. Thanks for posting this.
