### ISSUE TITLE
gnome-boxes: Needs a QEMU with smartcard support

### ISSUE THREAD

**Issue by espectalll** [voidlinux/void-packages#6336]
When attempting to run a recently-created GNOME Boxes (`libvirt`) virtual machine, the program is unable to do so. The client returns on the terminal the following:

    (gnome-boxes:6322): Boxes-WARNING **: machine.vala:611: Failed to start [VM]: Unable to start domain: unsupported configuration: this QEMU binary lacks smartcard passthrough mode support

Manually editing the corresponding settings file at `$XDG_CONFIG_HOME/libvirt/qemu` by deleting the `smartcard` tag works. A more serious fix could be either [patching GNOME Boxes](/GNOME/gnome-boxes/blob/4478d5db841e083340ced7cbd3fbae6e36f19763/src/vm-configurator.vala#L89) locally or upstream (what does it _need_ smartcard support for by default?), or enabling by default the `smartcard` flag at [srcpkgs/qemu/template#L26](../blob/master/srcpkgs/qemu/template#L26).

~~EDIT: Nevermind, here's the problem: [srcpkgs/gnome-boxes/template#L7](../blob/master/srcpkgs/gnome-boxes/template#L7)~~

**Comment by espectalll** [comment]
OK, so this commit almost a year ago actually removed the option to disable smartcard support: GNOME/gnome-boxes@6bf871c4e220cb4c32f7d96c143618e6f5b680cb

What would break the KISS principle less, patching GNOME Boxes or adding support to QEMU? Sorry for asking, but still new to Void 😕

**Comment by Gottox** [comment]
\*sigh\* okay.
