### ISSUE TITLE
Package Request: Turses - A Twitter client for the console.

### ISSUE THREAD

**Issue by neton-bricio** [voidlinux/void-packages#6346]
Very cool cli Twitter client.

[Project](https://github.com/dialelo/turses) / [Releases](https://github.com/dialelo/turses/releases) / [Documentation](http://turses.readthedocs.io/en/latest/).

Se a [screenshot](https://raw.githubusercontent.com/dialelo/turses/master/docs/images/turses_urxvt.png) / [video review](https://www.youtube.com/watch?v=kmnEdldw7WY)

**Comment by maxice8** [comment]
resolved at f4b3e5554de185b284be7b9192b0c3182a97a4d1

@the-maldridge
