### ISSUE TITLE
openttd: remove hardcoded data directory, move to XDG instead

### ISSUE THREAD

**Issue by skrzyp** [voidlinux/void-packages#6349]
The template for `openttd` contains `--personal-dir` hardcoded, while upstream started to support XDG-style directories. It's more comfortable for me to store data like that in some reasonable place, like `~/data/local` (as bound to `XDG_DATA_HOME` environment variable) instead of polluting the root of home directory.

Solution: rebuild with `--with-xdg-basedir`autoconf parameter, remove hardcoded `--personal-dir=.openttd`.

CC: @pullmoll

**Comment by Gottox** [comment]
This will require all openttd users to move their ``.openttd`` directory, won't it?

**Comment by skrzyp** [comment]
No, the program looks for old style `.openttd` directory too, from what I understand the code.
