### ISSUE TITLE
Rdesktop dependencies broken 

### ISSUE THREAD

**Issue by sholwe** [voidlinux/void-packages#6357]
This is essentially a copy from the forum post, as I don't see any specific format requested to report issues.

rdesktop's dependencies are broken. Not only for the binary, but for the build.

It uses MIT Kerberos 5, which is linked against gss, which isn't functional in a default build.
If you do an xbps-src build, it still fails to pull the library that it's linked to, so you get an error:

~~~
latty% rdesktop -u x x
can't open /usr/lib/libgssapi_krb5.so: /usr/lib/libgssapi_krb5.so: cannot open shared object file: No such file or directory
WARNING: CredSSP: System doesn't have support for desired authentication mechanism.
Failed to connect, CredSSP required by server.
~~~

Linking /usr/lib/libgssapi_krb5.so.2 to libgssapi_krb5.so is not the proper solution- but I can't find what provides /usr/lib/libgssapi_krb5.so - I've rebuilt my xlocate database and tried to install the most likely candidates..

**Comment by ebfe** [comment]
`mit-krb5-devel-1.14.4_3 /usr/lib/libgssapi_krb5.so -> /usr/lib/libgssapi_krb5.so.2.2`

**Comment by sholwe** [comment]
I tried rebuilding and relinking, but I still had the same error above.

**Comment by ebfe** [comment]
which arch?

**Comment by sholwe** [comment]
Sorry.  This issue has only been realized on x86_64/glibc; I have not tried i686, ARM, or musl based.

**Comment by ebfe** [comment]
And you have `mit-krb5-devel` installed?

**Comment by sholwe** [comment]
Yes.  I even manually created the symlink to the library, as it did not install.  I then built it with xbps-src, built a package, and installed it- but no symlink, however the timestamp of /usr/lib/libgssapi_krb5.so.* has changed.

**Comment by ebfe** [comment]
Just to be sure, i'm talking about `mit-krb5-devel` not `mit-krb5`.

**Comment by sholwe** [comment]
Yes.  It pulled in db-devel, and a few other oddities at the time-  which I was not expecting.    
 :)

I'll do a git pull, reinstall the rdesktop binary, and create the whole flow from that point, since I've done several pulls from void-packages since the time this issue initially popped up.  I have had it exhibit the same issues on two systems, with the same issue with libgssapi.

**Comment by ebfe** [comment]
Well, i can't reproduce this at all. The symlink is part of `mit-krb5-devel` and installs fine.

**Comment by sholwe** [comment]
The symlink missing didn't bother me so much as it exhibiting the same error/issue when I manually created it to the file in question.  It was acting like it couldn't read the library- and when I tried to build it with xbps-src, then do a bindir=... install, I saw no change.  I'll stat the library tomorrow and see if I can find anything odd on my two systems that "should not be".

**Comment by ebfe** [comment]
The symlink missing or being wrong is the most sane explanation for the error message.

**Comment by ebfe** [comment]
The missing dependency is libgssglue -> mit-krb5-devel, however that doesn't fix your problem.

**Comment by sholwe** [comment]
Well this is interesting.

I happened to have a clean install today, so I just did an xbps-install -S rdesktop, and it pulled in libgssglue.  The two machines exhibiting fault do not have that.

**Comment by sholwe** [comment]
Hah.  Good timing.  Cheers!  :)
