### ISSUE TITLE
[mount] Large files are truncated when copying from UFS filesystem

### ISSUE THREAD

**Issue by willbprog127** [voidlinux/void-packages#6371]
Greetings!

On most other Linux distros, I can use the following to mount my FreeBSD filesystem and copy files from it successfully:

`sudo mount -t ufs -o ufstype=ufs2 -o ro /dev/sdc2 /mnt/adisk`

When I use this mount command on Void (amd64 non-musl) the UFS filesystem mounts fine, but when I use `mc`, `cp` or `pcmanfm` to copy from the UFS filesystem, any file over 2.1 GB is truncated to 2.1 GB!

This problem does not happen on most other Linux distros.  There are no relevant messages in `dmesg` and when files are copied using `lxterminal`, no error message appears when the truncating occurs.

**Comment by chneukirchen** [comment]
Can you name your kernel version, and a Distro and kernel version that works?

**Comment by willbprog127** [comment]
@chneukirchen Thanks

My kernel info is:
`Linux will-void 4.10.15_1 #1 SMP PREEMPT Tue May 9 07:23:39 UTC 2017 x86_64 GNU/Linux`

Other distros such as Salix (and by extension, Slackware), Debian and Ubuntu all copy files properly using the same UFS mount command shown above.

**Comment by chneukirchen** [comment]
The Slackware 14.2 has roughly the same related config flags with 4.4.14, perhaps you can try our linux-lts kernel?

**Comment by willbprog127** [comment]
@chneukirchen Thanks.  Very well, I will try this when I have a moment.

So this appears to be a kernel issue?

**Comment by chneukirchen** [comment]
I have no idea what else it could be, we don't have any specific tweaks related to this.

**Comment by willbprog127** [comment]
@chneukirchen I am now running this:

`Linux will-void 4.4.66_1 #1 SMP PREEMPT Fri May 5 23:39:08 UTC 2017 x86_64 GNU/Linux`

and the UFS copying issue is *not* present.  It must be a kernel issue, then.  Any suggestions on who to contact next?

Thanks!

**Comment by chneukirchen** [comment]
Ok, then I'd write directly to the maintainer of the UFS2 subsystem (see bottom of https://github.com/torvalds/linux/blob/master/Documentation/filesystems/ufs.txt), this is probably specific enough that not too many other people care.

**Comment by willbprog127** [comment]
If I'm reading the kernel git site correctly, the ufs stuff hasn't been touched since 2007.  I will try another distro with kernel 4.10 and see how it fares.

Thanks! :smile:

**Comment by willbprog127** [comment]
An update:  I tried the same UFS copy scenario on Manjaro Linux OpenRC with kernel 4.9 and the problem exists there, too.

I have sent an e-mail to the two persons listed on the ufs.txt document linked above by @chneukirchen.  I will let you know what I hear, if anything.

**Comment by chneukirchen** [comment]
Closing this, leaving the bug upstream.
