### ISSUE TITLE
Libreoffice: CPU usage 100%

### ISSUE THREAD

**Issue by alasic** [voidlinux/void-packages#6375]
As soon as launched, libreoffice uses 100% of one core.
I think the problem is recent. It appeared after the java support addition.

**Comment by E100Beta** [comment]
@alasic same, and I don't think it's related to java. `musl` systems have java disabled, but when I launch Libreoffice i hear my laptop cry in pain with all its fan's noise capability :(

**Comment by alasic** [comment]
I’m agree with you. My message wasn’t clear enough. I am quite sure that the issue was posterior to the java support addition, but not immediately posterior: last time I used libreoffice base, it was with the java support, and my fan wasn’t trying to elevate my laptop… ☹ So that’s would be more recent.

De : Pavel Kiselev<mailto:notifications@github.com>
Envoyé le :jeudi 11 mai 2017 20:52
À : voidlinux/void-packages<mailto:void-packages@noreply.github.com>
Cc : alasic<mailto:alasic@hotmail.fr>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [voidlinux/void-packages] Libreoffice: CPU usage 100% (#6375)


@alasic<https://github.com/alasic> same, and I don't think it's related to java. musl systems have java disabled, but when I launch Libreoffice i hear my laptop cry in pain with all its fan's noise capability :(

**Comment by Piraty** [comment]
same here

**Comment by E100Beta** [comment]
A marginally funny finding - the CPU usage drops to 0 when I open Preferences. 
Also I noticed frequent CPU spikes when using Firefox. Both it and Libreoffice didn't do that before. I suspect one of the libs they both depend on.

Aaaaand massive breakthrough!
========================
After stumbling around not knowing what I'm doing for a bit, I fired up `gdb`, it complained on `glib`, then  I downgraded to `glib-2.52.1` and the issue disappeared.
