### ISSUE TITLE
blender: symbol lookup error:

### ISSUE THREAD

**Issue by chriscamacho** [voidlinux/void-packages#6394]
`[chris@xpslaptop ~]$ blender
blender: symbol lookup error: blender: undefined symbol: _ZN9COLLADASW12StreamWriter11openElementERKSs

[chris@xpslaptop ~]$ ldd /usr/bin/blender | grep COLLADASt

libOpenCOLLADAStreamWriter.so => /usr/lib/libOpenCOLLADAStreamWriter.so (0x00007febc434d000)

[chris@xpslaptop ~]$ grep _ZN9COLLADASW12StreamWriter11openElementERKSs /usr/lib/libOpenCOLLADAStreamWriter.so

Binary file /usr/lib/libOpenCOLLADAStreamWriter.so matches`

seems at least one other system effected (with different C lib)

https://forum.voidlinux.eu/t/blender-borkage/2560

**Comment by chriscamacho** [comment]
I've just installed blender on my desktop machine (where it wasn't previously installed) and can confirm the same issue happes when attempting to run it.

**Comment by ebfe** [comment]
Downgrading to opencollada-1.6.45 helps.
