### ISSUE TITLE
wmutils-core not working correctly

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#6418]
So it looks like commands `pfw` and alike print windowIDs correctly, but `wtf` and alike wont do anything. There doesn't seem to be any error throwing in neither console nor system-logs.

**Comment by ebfe** [comment]
Please provide an example on what you think is an issue with the our wmutils-core package. Which command did you run, what did you expect, what did actually happen and why do you think it's a problem with our package and not an upstream bug.
