### ISSUE TITLE
fping: Address family not supported by protocol

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#6456]
void glibc
pkgver: fping-4.0_1

In any way I try to execute the command (also logged as root), the result is always this:

    # fping -h
    (null): can't create raw socket (must run as root?) : Address family not supported by protocol

**Comment by ebfe** [comment]
Can't reproduce. What are the permissions on /usr/bin/fping?

**Comment by paoloschi** [comment]
> What are the permissions on /usr/bin/fping?

```
~ $ ls -l /usr/bin/fping
-rwsr-xr-x 1 root root 43960  1 mag 00.01 /usr/bin/fping
```
I tried to run both from shell bash and dash:

```
~ $ dash
$ fping
(null): can't create raw socket (must run as root?) : Address family not supported by protocol
$ 
```

**Comment by paoloschi** [comment]
From a long time (and distro migrations) in `/etc/default/grub` I'm bringing behind the `ipv6.disable=1` kernel option. I've found just now that by removing `ipv6.disable` i get `fping-4.0_1` it **works here too** !!!!

Years ago, disabling ipv6 speeded up my Internet connection; I assume that it is no longer true today and that it's a good idea if finally I remove it (......)

I apologize for the time I've made you lose :-[
@ebfe: so, on the basis of my discovery, can we close this _issue_ now ?

**Comment by ebfe** [comment]
`fping -4` should still work with ipv6 disabled.

**Comment by chneukirchen** [comment]
Should fping use CAP_NET_RAW?

**Comment by ebfe** [comment]
> Should fping use CAP_NET_RAW?

It could. But unrelated to this issue.

**Comment by paoloschi** [comment]
> fping -4 should still work with ipv6 disabled.

But it does not here! The reason why, unlike 3.x versions, fping 4.0 does not work by disabling IPv6 [is explained here](https://github.com/schweikert/fping/releases/tag/v4.0) and everything is clear to me.

It remains the fact that running the program with `ipv6.disable=1` kernel option, it is not possible here to set any fping 4.0 parameters, not even to simply print the help with the `-h` option.
This fact to me is more incomprehensible...

**Comment by djzort** [comment]
:(

**Comment by djzort** [comment]
See also https://github.com/schweikert/fping/issues/118
