### ISSUE TITLE
Forum unreachable !

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#6466]
Hello, 
My issue is not _directly_ related to void-packages but, in the last 4 hours, the Void [forum](https://forum.voidlinux.eu) was unreachable, with no explanation... 
At this time I still can't access the forum. 
Why ? 
Do you have a technical problem with the forum ? 
Thanks.

**Comment by Vaelatern** [comment]
Notice was given in #voidlinux on IRC. Hard disk issue.

**Comment by cr6git** [comment]
IRC ??

**Comment by Vaelatern** [comment]
That's okay. The forums will be back.

**Comment by cr6git** [comment]
OK. Fixed now. :)
