### ISSUE TITLE
Move /etc/locale.conf from the runit-void package to base-files?

### ISSUE THREAD

**Issue by CMB** [voidlinux/void-packages#6471]
I think /etc/locale.conf belongs in base-files, rather than runit-void.
When building a glibc rootfs tarball, glibc-locales is added before
runit-void, so this file is unavailable when the "post" action
runs in glibc-locales.install.
@maldridge asked about musl.
I think in the musl case, it doesn't matter which package contains
locale.conf; base-files would be just as appropriate.

**Comment by CMB** [comment]
@the-maldridge you asked me to ping you on this; here's your ping.
Sorry, I  pinged the wrong person when opening it.

**Comment by the-maldridge** [comment]
I'm happy with this, can you draft a PR including this change?

**Comment by CMB** [comment]
This seemed like a lovely idea, but apparently it will not fly with xbps.
Apparently I cannot just move a config file from one package to another.
If the config file previously installed by runit-void has been locally
modified, it is clobbered
by the fresh one from base-files.

**Comment by chneukirchen** [comment]
Add a remove hook that makes a backup copy, and an install.msg that tells people how to restore it...

**Comment by ebfe** [comment]
> Add a remove hook that makes a backup copy, and an install.msg that tells people how to restore it...

Only works if runit-void is updated before the base-files.

**Comment by CMB** [comment]
Turns out that my reason for opening this bug in the first place
was incorrect.  The contents of /etc/locale.conf have no effect on
the post action of glibc-locales.install at all.
What was I thinking?
There's still a convincing argument that locale.conf belongs
in base-files, because it is sourced by /etc/profile.d/locale.sh,
installed by base-files.  But since there's no easy way to migrate
a config file between packages without causing trouble for
someone, it isn't worth it.
Closing this issue for now.
