### ISSUE TITLE
Multiboot broken

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#6484]
Multiboot broken by `os-prober` [update](https://github.com/voidlinux/void-packages/commit/bd375d82f9c55e28d61d76e4443e3717564f4fc2) to 1.75 

Downgraded `os-prober` to 1.74 fixed the problem !

**Comment by Vaelatern** [comment]
Great. What was the problem?

**Comment by cr6git** [comment]
@Vaelatern Yes, sorry, at least we are two users with the same issue, discussed [here](https://forum.voidlinux.eu/t/multiboot-broken/2621) ... 

With version **1.74**: 

`$ sudo update-grub`
`Generating grub configuration file ...`
`Found linux image: /boot/vmlinuz-4.10.17_1`
`Found initrd image: /boot/initramfs-4.10.17_1.img`
`Found void on /dev/sda4`
`done`

With version **1.75**: 

`$ sudo update-grub`
`Generating grub configuration file ...`
`Found linux image: /boot/vmlinuz-4.10.17_1`
`Found initrd image: /boot/initramfs-4.10.17_1.img`
`done`

Here my second Void system on /dev/sda4 does not appear in the list.

**Comment by cr6git** [comment]
Just a thought: this update has not been tested before releasing it _into the wild_ ? 
There's nothing more I can do, sorry, I'll be gone for a week. 

Regards.

**Comment by Bubble-be** [comment]
Same here. It only seems to other linux that it doesn't detect.

1.75 found my windows partition, but not my Manjaro one.
```

Generating grub configuration file ...
Found background: /usr/share/void-artwork/VoidFloe.png
Found linux image: /boot/vmlinuz-4.10.17_1
Found initrd image: /boot/initramfs-4.10.17_1.img
Found linux image: /boot/vmlinuz-4.10.16_1
Found initrd image: /boot/initramfs-4.10.16_1.img
Found linux image: /boot/vmlinuz-4.10.15_1
Found initrd image: /boot/initramfs-4.10.15_1.img
Found Windows Boot Manager on /dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for EFI firmware configuration
done
```

1.74 finds the two.

```
Generating grub configuration file ...
Found background: /usr/share/void-artwork/VoidFloe.png
Found linux image: /boot/vmlinuz-4.10.17_1
Found initrd image: /boot/initramfs-4.10.17_1.img
Found linux image: /boot/vmlinuz-4.10.16_1
Found initrd image: /boot/initramfs-4.10.16_1.img
Found linux image: /boot/vmlinuz-4.10.15_1
Found initrd image: /boot/initramfs-4.10.15_1.img
Found Windows Boot Manager on /dev/sda1@/EFI/Microsoft/Boot/bootmgfw.efi
Found Manjaro Linux (17.0.1) on /dev/sdb2
Adding boot menu entry for EFI firmware configuration
done
```

**Comment by IbnSaeed** [comment]
I had the same issue after todays update.

ill downgrade and see if it solves the issue.

**Comment by IbnSaeed** [comment]
I cannot downgrade os-prober as i dont have os-prober-1.74 in repository pool

/var/cache/xbps/ only lists os-prober-1.75

**Comment by chneukirchen** [comment]
Can somebody affected please run `sudo os-prober` and show the logs generated in syslog?

1.75 removed one detection path, which was assumed to be obsolete by the maintainers.

**Comment by chneukirchen** [comment]
Ah stupid. Void doesn't have grub-mount, which is preferred. :P

**Comment by IbnSaeed** [comment]
> Can somebody affected please run sudo os-prober and show the logs generated in syslog?

When i run `sudo os-prober` it just goes to normal prompt. 

How to check syslog ?

**Comment by chneukirchen** [comment]
Please update again, a required tool was missing.

**Comment by IbnSaeed** [comment]
> Please update again, a required tool was missing.

alright, ill update right now.

Thanks for helping out @chneukirchen

**Comment by IbnSaeed** [comment]
@chneukirchen It worked fine this time and detected my 2nd OS.

So os-prober-1.75**_2** works 

Thanks

**Comment by chneukirchen** [comment]
Cue the first person to hit https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=760148 then. ;)
