### ISSUE TITLE
KDE frameworks package versions removed from KDE mirror

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#6514]
The KDE frameworks packages in Void are currently at version 5.29. I just discovered that these versions were removed from the KDE server. https://download.kde.org/stable/frameworks/ only lists versions from 5.30 on. This will lead to issues if rebuilds are necessary.

The packages should either be updated to the current version or the distfile URLs be changed to another server still hosting the files (if such a server exists).

**Comment by Vaelatern** [comment]
Finding such a server with older software versions would be preferred.

**Comment by amak79** [comment]
Older releases can be found here: https://download.kde.org/Attic/frameworks/

**Comment by Hoshpak** [comment]
Thanks, I will create a pull request.

**Comment by ebfe** [comment]
#6052 merged
