### ISSUE TITLE
Trouble with Helvatica font in xorg-fonts package

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#6523]
Hi everyone,

Have a problem with Helvetica font that is available in `font-adobe-75dpi` and `font-adobe-100dpi` (dependencies of `xorg-fonts`).

This is how it appears in font manager:
![Helvetica jagged font](http://i.imgur.com/lCR29jG.png)

And this is what i get on git-hub in Firefox (and many other sites):
![Firefox Helvetica issues](http://i.imgur.com/pnAWTtH.png)

This is pretty annoying.
The simple workaround is to disable the use of system fonts in Firefox, but its not the best one.

Also, please note, that yes, all the packages are upto date.

Please let me know if this needs to be reported elsewhere. Or perhaps more suitable for a forum thread.
Thanks!

**Comment by Duncaen** [comment]
I don't think there is much that we can do about it, afaik there is no "sane" helvetica version available for free.
The fons in `font-adobe-*` are bitmap fonts.
You can install alternative fonts like `liberation-fonts-ttf` or `dejavu-fonts-ttf`.

**Comment by direwolfie** [comment]
Big thanks for the suggestion! :)
Can you please advise, will I run into trouble if I remove the xorg-fonts?

**Comment by teh-jazzman** [comment]
If you manually installd `xorg-fonts` there should be no problem. Just make sure that you have at least some font installed that xorg can use.

If `xorg-fonts` was installed as a dependency for the `xorg` metapackage, removing it will be a little more tricky. You may need to mark `xorg`'s other dependencies as "manually installed" and then remove both `xorg-fonts` and `xorg`:

`xbps-pkgdb -m manual xorg-server xorg-apps xorg-input-drivers xorg-video-drivers`
`xbps-remove -R xorg-fonts xorg`

**Comment by direwolfie** [comment]
> xbps-pkgdb -m manual xorg-server xorg-apps xorg-input-drivers xorg-video-drivers
> xbps-remove -R xorg-fonts xorg

I installed it manually, but this is very interesting.
Will probably come in handy in the future. Thank you! :)
