### ISSUE TITLE
Forum unreachable, again.

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#6533]
I can't access to the forum. 
What's wrong ? 
Forum unreachable for several hours... 
Nobody cares ?? 
That's ridiculous, **seriously**.

**Comment by the-maldridge** [comment]
Thank you for your interest.  We are aware of this problem and are investigating.  There is currently no ETA for service restoration.

**Comment by cr6git** [comment]
OK, Fixed now !! :)
