### ISSUE TITLE
htop is not built for aarch64, both glibc and musl

### ISSUE THREAD

**Issue by praticamentetilde** [voidlinux/void-packages#6537]
Hi there. I've just installed void musl on my Raspberry Pi 3, and I've noticed that i can't find `htop` with `xbps-query`. https://repo.voidlinux.eu/current/aarch64/ does not list the `htop` package, both for musl and glibc.

**Comment by Sir-Boops** [comment]
8e633aa2912cfadfc8a9e4475c7526f56f278b0b Fixes this issue
