### ISSUE TITLE
Update weston to 3

### ISSUE THREAD

**Issue by ibrokemypie** [voidlinux/void-packages#6545]
Weston v3 is now available and some packages such as orbital do not build without it now

**Comment by Sir-Boops** [comment]
Where are you seeing the release announcement of weston v3?

**Comment by ibrokemypie** [comment]
I think its actually libweston3 rather than weston 3

**Comment by asergi** [comment]
To date, the latest stable release of weston is version [2.0.0](https://wayland.freedesktop.org/releases/).

So, there's nothing to update here now.
