### ISSUE TITLE
physlock broken

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#6551]
For now running `physlock` results into `/var/run/utmp: No entry for tty7 found`.

The issue is documented here: https://github.com/muennich/physlock/issues/44

And the fix here: https://github.com/muennich/physlock/commit/ab695683ef3d656823c91deae87ca17c529477f6

But there is no release since the fix.

@uggedal  this was your pkg so I tagged you FYI.

**Comment by ebfe** [comment]
updated to physlock-11_1 c48e46bbd1fbd415057ca8444b54148b7898d2bb
