### ISSUE TITLE
idea: drop gcc specs file

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#6590]
gcc 6 has `--enable-default-pie` which essentially passes `-fPIE` all the time.
We pass relro and bind now via -Wl anyway due to libtool.

So I think we could build gcc with default-pie (e.g. Debian does this too), and drop the specs files,
and save the hassle of leaked flags.
(Debian also has a patch to make relro and bind now default.)

This means nopie=yes then needs to pass `-fno-PIE`. Users will get PIE builds on their own gcc invocations, which probably is a good idea.

**Comment by Gottox** [comment]
![Make it so](https://media.giphy.com/media/bKnEnd65zqxfq/giphy.gif)

**Comment by xtraeme** [comment]
+1

**Comment by chneukirchen** [comment]
I'll prepare a PR.

**Comment by maxice8** [comment]
ping

**Comment by chneukirchen** [comment]
We only use these during bootstrap now.

Mission accomplished.
