### ISSUE TITLE
package request: jsonlite

### ISSUE THREAD

**Issue by paoloschi** [voidlinux/void-packages#6599]
Nothing to build: this is a single bash script that any _non-privileged_ user can copy to his `~/bin` directory (or where else he wants).

__jsonlite__
 A simple, self-contained, serverless, zero-configuration, json document store. 
<https://github.com/nodesocket/jsonlite>

Do you think it might be interesting to have it in `/usr/bin` and updated by xbps for everyone?

**Comment by cr6git** [comment]
@paoloschi Today I created a template if you want: 

# Template file for 'jsonlite'
pkgname=jsonlite
version=1.1.0
revision=1
short_desc="Simple, self-contained, serverless, zero-configuration, JSON document store"
maintainer="local <root@localhost>"
homepage="https://github.com/nodesocket/jsonlite"
license="Apache-2.0"
distfiles="${homepage}/archive/${version}.tar.gz"
checksum=dae9cac038c0bfde3ac7f8e9bbeb5bf1cf70b8e3723a14d53267461f669c0602

do_install() {
	vbin jsonlite.bash
}

:wink:

**Comment by paoloschi** [comment]
Thanks cr6, do you plan to make a PR?
(I'm not able to do it ..)

**Comment by cr6git** [comment]
Yes, I can make the PR, why not... 
But I must change this line: 

`maintainer="local <root@localhost>"`

To add your name / email. 

(Since it has _little interest_ to me, I don't want to become the maintainer of this particular package, sorry.) 

Before an eventual PR for this program, did you run some tests on your computer to see if it works?

**Comment by cr6git** [comment]
@paoloschi When you say: _"I'm not able to do it.."_ What do you mean? Can you explain? 
Maybe I misunderstood something? 

Regards.

**Comment by paoloschi** [comment]
@cr6git: Thanks for the interest but this is not a forum, we must not divag..
To manipulate JSON documents, in the repository there are already packets like __jq__, __yajl__, __jo__ and others.
__jsonlite__ can be seen as a useful companion of these tools to expand its scope of use.. 

On the other hand, thinking of all the work that involves the maintenance of a package when, on the practical side, it's just a matter to copying to `/bin` a single 4Kb file, this is making me reconsider the opportunity of this my request.
I decided to withdraw it. I apologize for not thinking well before and also for wasting you time..
