### ISSUE TITLE
Download link for opus needs an update.

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6639]
Not sure yet where the correct url is located. I see previous versions there but not 1.1.5.

**Comment by cr6git** [comment]
What are you talking about ? The [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/opus/template) is correct. 
Don't you see opus-1.1.5 [tarball](http://downloads.xiph.org/releases/opus/opus-1.1.5.tar.gz) ?

**Comment by The-Fred** [comment]
Yep, I get a 404 from the original url. I found the second one and that one looks correct.

## Not Found

`The requested URL /releases/opus/opus-1.1.5.tar.gz was not found on this server.
***
_Apache Server at downloads.xiph.org Port 80_

**Comment by asergi** [comment]
b4b14b0f2e529ef804b9de7b7cb4692150dfa1fc
