### ISSUE TITLE
rxvt-unicode: add patches or switch to using source from CVS.

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6666]
There are some updates that land in cvs that don't show up until a new release is made and sometimes the releases don't happen right away. From what I've seen using the source from CVS is low risk.

I see a patches directory but that seems to be just patches specific to Void. But is that another way to stay up to date? i.e. make patches from CVS and apply them to the last release

**Comment by the-maldridge** [comment]
Our package policy does not permit shipping non released code.  If you wish to build rxvt-unicode locally you could still use xbps-src and work on a branch, but we do not ship *-git *-cvs *-svn versions of packages in the main repo.

**Comment by The-Fred** [comment]
Sounds like a good, reasonable approach. I get it. I'm not asking for exceptions but there are some projects that forget to release or even have stopped doing them and just treat some branch (usually master) as a rolling release.

**Comment by The-Fred** [comment]
Turns out that the policy is flexible(see below), which is good and it should be applied here to rxvt-unicode. The release that's currently fetched is 18 months old and there have been significant patches made since.

See [Tracking bug: change scm fetch methods to proper distfiles](https://github.com/voidlinux/void-packages/issues/2070)

**Comment by the-maldridge** [comment]
Actually, if you read the ticket you linked, you'll see that those are packages that are out of line with the package policy from a very long time ago.  They were being moved over to using proper distfiles as the title clearly states.

rxvt-unicode will remain at the stable release.  If you'd like to run a system that pulls from CVS and has the latest code at all times, perhaps you would be interested in [Arch Linux](https://www.archlinux.org/)

**Comment by The-Fred** [comment]
And if you read that ticket you would have noticed that many never complied.  Here's just one example: linux-firmware.  There will never be a release of that.  It's good that we have a policy that's flexible.

You have missed the real problems.  The real problem is not the latest code. One real problem is the least buggy code. Another real problem is the reality that there's a trend toward keeping master branches stable and not bothering with releases.

**Comment by the-maldridge** [comment]
Go poke the maintainers of rxvt-unicode if you want a new version that badly, the policy here stands.
