### ISSUE TITLE
libldap-devel-32bit Wont Build

### ISSUE THREAD

**Issue by ibrokemypie** [voidlinux/void-packages#6680]
libldap-devel-32bit apparently requires the package openldap-32bit which doesnt actually exist, so it will not build.

**Comment by asergi** [comment]
Not sure it fixes your problem, but the `depends` line of  `libldap-devel` is wrong:
```diff
 libldap-devel_package() {
-       depends="${makedepends} ${sourcepkg}>=${version}_${revision}"
+       depends="${makedepends} libldap>=${version}_${revision}"
```
