### ISSUE TITLE
protobuf: ERROR: SHA256 mismatch

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6688]
The build, of course, fails when it "couldn't verify distfiles, exiting...". Not much else to say here. File size was 4120KB.  The url requested was very long (I don't have at hand), it was a redirect to an amazon s3 store.

**Comment by cr6git** [comment]
You are right!

`=> protobuf-3.3.0_3: verifying checksum for distfile 'protobuf-cpp-3.3.0.tar.gz'...`
`=> ERROR: SHA256 mismatch for 'protobuf-cpp-3.3.0.tar.gz:'`
`5e2587dea2f9287885e3b04d3a94ed4e8b9b2d2c5dd1f0032ceef3ea1d153bd7`
`=> ERROR: protobuf-3.3.0_3: couldn't verify distfiles, exiting...`

`$ cat srcpkgs/protobuf/template |grep checksum`
`checksum=578a2589bf9258adb03245dec5d624b61536867ebb732dbb8aeb30d96b0ada1f`

**Comment by pullmoll** [comment]
[92f7637](https://github.com/voidlinux/void-packages/commit/92f763756bc6a62f5241f0caa6f09f3ad7d77cce)
