### ISSUE TITLE
ffmpeg invalid certificate

### ISSUE THREAD

**Issue by vaartis** [voidlinux/void-packages#6690]
ffmpeg's ca certificate seems to be invalid and wget/xbps-src cannot download it
How to reproduce:
1. `wget https://www.ffmpeg.org/releases/ffmpeg-3.3.1.tar.xz`
```
ERROR: cannot verify www.ffmpeg.org's certificate, issued by ‘CN=StartCom Class 2 IV Server CA,OU=StartCom Certification Authority,O=StartCom Ltd.,C=IL’:
  Unable to locally verify the issuer's authority.
```

Maybe we should use some mirror to download it?

**Comment by chneukirchen** [comment]
Just use http://

**Comment by vaartis** [comment]
xbps package uses https tho, i can't install it

**Comment by cr6git** [comment]
I _can_ download this file without problem, see my [log](https://paste2.org/VgDIj2aH)

**Comment by Vaelatern** [comment]
date on your system?

**Comment by vaartis** [comment]
@Vaelatern yeah, it was the date..
