### ISSUE TITLE
Package Request: Waterfox

### ISSUE THREAD

**Issue by 1ElkCrew** [voidlinux/void-packages#6719]
https://github.com/MrAlex94/Waterfox

64 bit fork of Firefox. I'd love to see it on xbps instead of manually updating it.
I'd suggest checking for compatability issues between Waterfox and Firefox juts in case.

**Comment by Vaelatern** [comment]
As if firefox didn't work on 64bit systems already?
What's the point of this?
And why do we need another Firefox fork?

**Comment by the-maldridge** [comment]
@Vaelatern Its basically firefox but with all the Mozilla stuff turned off.

**Comment by The-Fred** [comment]
Sounds like Icecat which we already have. Right?

Another important factor that you may (or may not) want to consider is that Waterfox on github is just a massive blob for each release. Not the typical release style or at least different from Icecat's release/repo style.

Also it's not that clean as you think as far as "Mozilla stuff turned off."

**Comment by the-maldridge** [comment]
@The-Fred I'm perfectly familiar with what Waterfox is and how it came to be, but until there's a PR behind it, I won't spend much time to write up anything on it here.

**Comment by chneukirchen** [comment]
I'm strongly against more Firefox-sized browsers.

**Comment by the-maldridge** [comment]
Closed by poke from a senior maintainer.
