### ISSUE TITLE
Package Request: cppzmq

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6723]
It's very small, but useful.

https://github.com/zeromq/cppzmq

C++ binding for 0MQ http://www.zeromq.org

**Comment by cr6git** [comment]
````
# Template file for 'cppzmq-git'
pkgname=cppzmq-git
version=20170720
revision=1
_commit=a89d35b1ecf53774a7bfcbbf0a3eafc859724411
build_style=cmake
hostmakedepends="pkg-config"
makedepends="zeromq-devel"
maintainer="local <root@localhost>"
short_desc="C++ binding for 0MQ"
homepage="http://www.zeromq.org/"
license="MIT"
distfiles="https://github.com/zeromq/cppzmq/archive/${_commit}.tar.gz>${pkgname}-${version}.tar.gz"
checksum=cb6e3be899a9922da4956e6aa8e895814bf2fb03df47df18d4d123453e26cbc5
wrksrc="cppzmq-${_commit}"

post_install() {
	vlicense LICENSE
}

````

I just created this template for you ;) 
Using the latest git commit, because the old release [4.2.1](https://github.com/zeromq/cppzmq/releases/tag/v4.2.1) does not compile on my system.

**Comment by newbluemoon** [comment]
@cr6git There’s an official 4.2.2 release now that should work. Maybe you would like to update your template and make a PR?

**Comment by Vaelatern** [comment]
@newbluemoon, unlikely. Giving it a go myself now.

**Comment by Vaelatern** [comment]
Nope. 
This issue still is pending (on me). Anybody want to give it a go? https://github.com/zeromq/libzmq/issues/2597

**Comment by Vaelatern** [comment]
Thanks to @maxice8 for noticing a pkg-config fallback!
