### ISSUE TITLE
st does not apply patches in the last revision

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#6734]
Good day,

I have tried patching "st" and even though during the process it says that patches are being applied, there is no change when you actually launch the terminal emulator. This is seen the easiest with the "solarized" theme.

If I roll back before the "fixing the template" commit (there is a different template and no "files" directory), same patches start working as intended.

Could you check it, please?

**Comment by Duncaen** [comment]
If you patch `config{,.def}.h` then it doesn't apply anymore, there is a `config.h` file which is copied from `files/`, which happens after the patching phase.
https://github.com/voidlinux/void-packages/blob/8e43ca9cdc7b5927b2669a93a3823470bb8af78a/srcpkgs/st/template#L18
