### ISSUE TITLE
heimdall: New release v1.4.2

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6740]
New release made last month. The build_style should now be cmake (or "cmake" 😜).

Should the package be renamed to Heimdall as it is on 

https://github.com/Benjamin-Dobell/Heimdall

**Comment by Duncaen** [comment]
There is a list of outdated packages at https://repo.voidlinux.eu/void-updates/void-updates.txt that is generated every day.
Its not really necessary to open issues, except if its urgent and there is some critical issue.

**Comment by The-Fred** [comment]
Great, I didn't know that. I will refrain.  This one might be significant since the previous release was 3 years ago.  It's not urgent or critical afaik fwiw but I am using 1.4.2.

Good to read there're things that're automated.

**Comment by cr6git** [comment]
@The-Fred I did what I could to update it, see [PR#6745](https://github.com/voidlinux/void-packages/pull/6745). The Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/heimdall) was helpful.

**Comment by aeosynth** [comment]
@Duncaen perhaps `CONTRIBUTING.md` could mention the autogenerated reports. it's not obvious that this type of issue isn't needed.

**Comment by ebfe** [comment]
6ca1e9a5aafb38123e4176c852dd31c695b0225c
