### ISSUE TITLE
Texlive-bin is possibly outdated

### ISSUE THREAD

**Issue by Vintodrimmer** [voidlinux/void-packages#6759]
Good day,

Currently `texlive2017-bin` is the latest version, while `texlive-bin` points to the `texlive2016-bin`.

If that's not the intended behaviour, consider updating the template, please.

**Comment by chneukirchen** [comment]
I'll leave 2017 for testing a bit.

**Comment by ebfe** [comment]
83e66df24604b8fec76e2fa5edf8dbb48fe37829
