### ISSUE TITLE
Package Request: Sonic-Visualiser

### ISSUE THREAD

**Issue by JesSch1023** [voidlinux/void-packages#6771]
"Sonic Visualiser is an application for viewing and analysing the contents of music audio files."

[http://www.sonicvisualiser.org](url)

Dependencies:
REQUIRED        Qt v5                   http://qt-project.org/
REQUIRED        Vamp Plugin SDK v2.x    http://www.vamp-plugins.org/
REQUIRED        Rubber Band Library     http://www.breakfastquay.com/rubberband/
REQUIRED        libsndfile              http://www.mega-nerd.com/libsndfile/
REQUIRED        libsamplerate           http://www.mega-nerd.com/SRC/
REQUIRED        FFTW3                   http://www.fftw.org/
REQUIRED        bzip2 library           http://www.bzip.org/
REQUIRED        Sord and Serd libraries http://drobilla.net/software/
REQUIRED        Cap'n Proto             http://capnproto.org/
Optional        MAD mp3 decoder         http://www.underbit.com/products/mad/
Optional        Oggz and fishsound      http://xiph.org/oggz/
Optional        liblo OSC library       http://www.plugin.org.uk/liblo/
Optional        JACK                    http://www.jackaudio.org/
Optional        PortAudio v19           http://www.portaudio.com/
Optional        PulseAudio              http://www.pulseaudio.org/

**Comment by cr6gtx** [comment]
Not easy to build. I get [this error](https://paste2.org/V7CgtPB6).

**Comment by JesSch1023** [comment]
Hmm. Looks VAMP specific. The VAMP SDK has held me up in the past trying to just make/make install. I see "sonic-visualiser-3.0.3_1 x86_64-**musl** build error", could this be a musl specific compilation problem? I've never used musl and honestly know nothing about it. I am an intermediate Linux user at best, so I'm likely unable to help sort that error out. If I can figure Git and XBPS-src out, I'll try to repro the error.

**Comment by cr6gtx** [comment]
You can try to improve my [template](https://paste2.org/tsBYwvB1). 
I tried to build it again this morning but I get the same error, see the complete [log](https://paste2.org/CU4GLLJe).
