### ISSUE TITLE
[fltk/fltk-devel]  FLTK 1.3.3 is old, please update to 1.3.4-1

### ISSUE THREAD

**Issue by willbprog127** [voidlinux/void-packages#6772]
Greetings!

I do a lot of work in FLTK and have been missing some bug-fixes and features that are in 1.3.4 that aren't in 1.3.3.  Can you please update `fltk` and `fltk-devel` to 1.3.4-1?

Thank you! :smile:

**Comment by biopsin** [comment]
..new
checksum=c8ab01c4e860d53e11d40dc28f98d2fe9c85aaf6dbb5af50fd6e66afec3dc58f
remove patches folder as patch is included in new release.

tried pack it and built ok, however some warnings came up;
make warning: -jN forced in submake: disabling jobserver mode. (making src & docu..)
/bin/sh/: man: command not found (6times)

**Comment by willbprog127** [comment]
@Sir-Boops Thank you!
