### ISSUE TITLE
Updates for intellij-idea-community-edition 

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#6776]
Hi eveyone!

`intellij-idea-community-edition` is out of date in the repository. 
Repository version **2016.3.2**
Current version is **2017.1**

Kindly please consider updating it.

If this can be done manually by me, please advise how it can be done.

Thanks!

**Comment by asiekierka** [comment]
https://github.com/voidlinux/void-packages/pull/6630

**Comment by direwolfie** [comment]
Thanks! Was not aware of that.
Will do so next time :)
