### ISSUE TITLE
lightdm/xinit: No support for running ~/.xsession

### ISSUE THREAD

**Issue by wagnerflo** [voidlinux/void-packages#6785]
The other Linux distributions I know of (primarily Debian and Arch) have some place in their login manager scripts that checks for `~/.xsession` and if that exists executes it instead of the selected display manager.

Using `lightdm` on Void, there doesn't seem to be anywhere this is done in the shipped configuration and scripts.

I see three possible solutions:

1. Added it to the end of `/etc/lightdm/Xsession`.
2. Provide a `/etc/X11/xinit/xinitrc.d/99-xsession` either in the `xinit` or in a separate package.
3. Provide a "custom login" Xsession in a separate package.

I can provide patches and/or packages if this is a desired addition.

**Comment by wagnerflo** [comment]
CC @xtraeme.

**Comment by the-maldridge** [comment]
Option 3 is the cleanest IMHO.  Package it and mention me in the PR.
