### ISSUE TITLE
Package request: qt5ct

### ISSUE THREAD

**Issue by AcarBurak** [voidlinux/void-packages#6796]
Extremely useful –to globally set/change/create qt5 themes, icons, fonts, stylesheets etc. It is indispensable for a qt5 system like LXQt or a WM with qt5 packages.

https://sourceforge.net/projects/qt5ct/

**Comment by xYuusha** [comment]
I started creating the template yesterday but i don't know which programs it affects so i can't really test it.

I think it works with qt5 programs but i don't know to many. Can you give me some examples?

**Comment by AcarBurak** [comment]
Thanks very much.

It sets themes, fonts, icons etc. for all the qt5 apps globally by entering this in ~/.bashrc or other such like file:

`export QT_QPA_PLATFORMTHEME=qt5ct`

In short it's the best, logical, unbloated, functional system setting tool I've seen, better (or finer) than even the KDE systemsettings.

Here's a screen shot:

![qt5ct](https://user-images.githubusercontent.com/1426842/27465995-dc83b088-57df-11e7-979e-2f72937e79a1.png)

Please tell me if its use case is not clear enough.

**Comment by AcarBurak** [comment]
Obviously, it is for non KDE systems.

**Comment by AcarBurak** [comment]
It will create these under ~/.config/qt5ct/
```
/colors/YOUR_CUSTOM_COLOUR_SCHEMES (to be created simply by the gui)

/qss (optional style sheet to be created manually, though you hardly need them unless you'd like very intricate, special themes)

qt5ct.conf
```

For a start you may try a read made of mine and modify it. Just put this in /colors/AlmostFrost.conf:

```
[ColorScheme]
active_colors=#fffbee, #9a8678, #ffffff, #cbc7c4, #bcb0a5, #b8b5b2, #fffbee, #ffffff, #fffbee, #75655b, #9a8678, #767472, #788c9a, #ffffff, #55aaff, #ffaaff, #75655b, #000000, #55aa7f, #ffffff
disabled_colors=#9faa84, #9a8678, #ffffff, #cbc7c4, #bcb0a5, #b8b5b2, #9faa84, #ffffff, #9faa84, #75655b, #9a8678, #767472, #788c9a, #dcdcdc, #55aaff, #ffaaff, #75655b, #000000, #55aa7f, #ffffff
inactive_colors=#fffbee, #9a8678, #ffffff, #cbc7c4, #bcb0a5, #b8b5b2, #fffbee, #ffffff, #fffbee, #75655b, #9a8678, #767472, #788c9a, #ffffff, #55aaff, #ffaaff, #75655b, #000000, #55aa7f, #ffffff
```

**Comment by AcarBurak** [comment]
Here's another screen shot of QupZilla and QtCreator (my text editor!) under a pure qt5 Fluxbox system:

![qt5ct2](https://user-images.githubusercontent.com/1426842/27466513-f0db9cea-57e3-11e7-9e7d-473afc5086d3.png)

**Comment by xYuusha** [comment]
Thanks, that helped me to test the package.

I created a pull request for this package. #6837

**Comment by AcarBurak** [comment]
Thank you.

**Comment by maxice8** [comment]
resolved at https://github.com/voidlinux/void-packages/commit/b7b17c166f5730790ad065a0c2af181527eaafc5

@the-maldridge
