### ISSUE TITLE
Package request: qarma

### ISSUE THREAD

**Issue by AcarBurak** [voidlinux/void-packages#6797]
Very functional and simple zenity replacement for a qt5 system like LXQt or a WM with qt5 packages.

https://github.com/luebking/qarma

By

`ln -s /usr/bin/qarma $pkgdir/usr/bin/zenity`

one can use zenity scripts/dialogues without any alteration as well such as this useful [script](https://github.com/stamatisxm/ZumDisks) (among many others) to very easily un/mount drives without any bloat like gvfs or the likes:

![qarma](https://user-images.githubusercontent.com/1426842/27468051-ff341a72-57ef-11e7-96d5-7c4d03047fed.png)

**Comment by cr6gtx** [comment]
I created a [template](https://paste2.org/nMV2Gjsn) to build the latest git version, dated 2017-02-14.

**Comment by AcarBurak** [comment]
Thanks very much.

**Comment by cr6gtx** [comment]
Another [template](https://paste2.org/d4F4yVg4) to build the latest Release [t1](https://github.com/luebking/qarma/releases/tag/t1).

**Comment by AcarBurak** [comment]
Thank you.

**Comment by cr6git** [comment]
@AcarBurak As you can see, my first PR for `qarma` has been ignored... 
Is it worth it to open a new PR ?

**Comment by AcarBurak** [comment]
It's very useful for a Qt-only desktop and now it's a recommended app for LXQt. Void seems more welcoming to Qt apps, so it would fit. Yet, naturally, it's up to you…

**Comment by cr6git** [comment]
ok, let's try again.

**Comment by AcarBurak** [comment]
Thank you.

**Comment by cr6git** [comment]
it's done.

**Comment by AcarBurak** [comment]
Thank you.
