### ISSUE TITLE
Package request: goldendict

### ISSUE THREAD

**Issue by AcarBurak** [voidlinux/void-packages#6798]
The best dictionary application (by a wide margin) and indispensable for translators and non-native speakers.

The stable release may be dated, but it is actively developed and I'd been using the git qt5 version from the official Arch repo for quite some time without any issue; it is stable.

https://github.com/goldendict/goldendict

**Comment by asergi** [comment]
cba8baa31881336ec548c72086c80d2327ecdb09

**Comment by AcarBurak** [comment]
Thank you.
