### ISSUE TITLE
 Could you (anyone) please maintain ttf-tlwg package to void package list?

### ISSUE THREAD

**Issue by foxmean** [voidlinux/void-packages#6851]
This package is about add Thai font to GNU/Linux system that I found it's really useful and easy to install Thai font.
And This package is Arch GNU/Linux package that I mention to => https://www.archlinux.org/packages/extra/any/fonts-tlwg/
I really think that may be it can convert to void package? But I'm newbie and I'm really not understand document about create and maintain packages, may be the next day I can.
So, now please do this if you can because it's not for only me but many Thai people too.

This blog is showing how this package works. => https://9mza.blogspot.com/2016/10/arch-thai-language.html

However this issue (can not read Thai) have solved for me because I manully install it. But I think it can do easier by xbps-install way like my experience that I can install it by pacman package manager.

Thank you very much for all of you.

**Comment by ColdPhoenix00** [comment]
Made it here: #6855

**Comment by foxmean** [comment]
Thank you so much @ColdPhoenix00 .

**Comment by the-maldridge** [comment]
resolved in bdf247038c
