### ISSUE TITLE
fail2ban: version/branch change needed.

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6863]
As you can see from here:
https://repo.voidlinux.eu/void-updates/void-updates.txt

The request is to update fail2ban to 0.9.7 but 

>**0.9.x line is no longer heavily developed.  If you are interested in
new features (e.g. IPv6 support), please consider 0.10 branch and its
releases.**

I don't see any releases they mention for the 0.10 branch.  But this url seems to work:

https://github.com/fail2ban/fail2ban/archive/0.10.tar.gz

**Comment by The-Fred** [comment]
I did find a release:
https://github.com/fail2ban/fail2ban/releases/tag/0.10.0a1

**Comment by the-maldridge** [comment]
0.10a1 is a preview release.  Perhaps you can file an issue with them to click the release button for the .10 series?  Alternatively they aren't ready to release 0.10.x as the primary series yet.

**Comment by The-Fred** [comment]
If someone needs ipv6 they'll then need 0.10.
