### ISSUE TITLE
mpv in arm is not fixed

### ISSUE THREAD

**Issue by moinejf** [voidlinux/void-packages#6868]
The resolution of #6866 via d4c589f8d0bba2841740b6495719857e980c955e does not work.
I updated all my packages, including mpv, and I still get the same message:

`mpv: error while loading shared libraries: /usr/lib/libx265.so.116: unexpected reloc type 0x03`

It seems that the problem is in the libx265 library, not in mpv.

**Comment by asergi** [comment]
ARM version? 6, 7 or aarch64?
musl or glibc?

**Comment by moinejf** [comment]
armv7l
glibc

**Comment by asergi** [comment]
Can you apply this [patch](https://gist.github.com/8bfdd557b5ccd2c31614bdd182a79b2f), rebuild x265, and see if it works? Thanks.

**Comment by moinejf** [comment]
mpv works fine again.
Thanks.
