### ISSUE TITLE
package ttf-tlwg-0.6.3 has a bug

### ISSUE THREAD

**Issue by foxmean** [voidlinux/void-packages#6881]
This package #6855 which recently add by kindly man has a bug.
Because I'm Thai, when I've test it I easily got that something wrong
This picture show the problem
![inuse_ttf_tlwg](https://user-images.githubusercontent.com/13077459/27633427-55739254-5c29-11e7-877e-5b8c393ec9f1.png)
And after I manully add Thai font by this method, which I use to solved the problem that void can't show Thai alphabet in web-browser before this package was add. It was resolved like this picture
![inmanual](https://user-images.githubusercontent.com/13077459/27633571-f3c89b7a-5c29-11e7-95b7-68c03184cf01.png)

Sorry that I can't maintain this package now because of lacking knowlage (yes, there is an manual [here](https://github.com/voidlinux/void-packages/blob/master/Manual.md) but I really stuck with it now).

However, the step of manully install Thai font that I use may be helpful for you, maintainer - @ColdPhoenix00 , I hope so. And below is my bash shell command that I use.

```
$ wget https://linux.thai.net/pub/thailinux/software/thai-ttf/ttf-tlwg-0.6.1.tar.xz
$ tar xJfv ttf-tlwg-0.6.1.tar.xz 
$ cd ttf-tlwg-0.6.1/
$ sudo cp -r * /usr/share/fonts/TTF/
$ cd /usr/share/fonts/TTF/
$ sudo mkfontdir && sudo mkfontscale
$ sudo fc-cache -f -v
$ sudo reboot
```

Thank you so much.

**Comment by foxmean** [comment]
Sorry, I'm forgot that this package >>> Fonts-TLWG-0.6.3_1 <<< have this problem too.
Thank you.

**Comment by ColdPhoenix00** [comment]
Here's template resembling your script: https://pastebin.com/raw/80WQnmEF 
You might also try installing `noto-fonts-ttf` which has almost all glyphs(except Chinese, Japanese and Korean which are part of `noto-fonts-cjk`)
`

**Comment by the-maldridge** [comment]
Fonts-TLWG and ttf-tlwg are the same package, I merged it with the wrong name and then a few minutes later changed the name (sorry for the confusion!).   The first one (ttf-tlwg) is definitely buggy and I don't think correctly triggers the font-cache rebuild on install (again, my mistake: I asked for patches to the template and then did not fully verify that they were correct).

As the Thai glyphs look like a lot of squiggles to me, I'm not fully clear on what the bug is.  Can you elaborate on what you expected to happen and what actually happened?

**Comment by foxmean** [comment]
@ColdPhoenix00 I try to test the noto-fonts-ttf package but I've alredy install font manully so I've to remove all Thai font and install that package but it so much Thai font and I aware that I will remove other fonts too. Because of that, I've tried to simulate Void on VirtualBox but it can't install successfully (problem with install GRUB -> cannot both, the others was successful).
Now, I will try to install on flash drive to test if 'noto-fonts-ttf' can also solve the Thai font rendering problem or not and I will tell you again. But I think try your script may be a good idea?

@the-maldridge the problem is when I was install this package, the Thai alphabet is not rendering in good arrangement, it was entanglement, overlap each other.

**Comment by the-maldridge** [comment]
@foxmean this sounds like it may be an issue with the glyph width being set incorrectly in your browser.  I'm not entirely sure how  that could have happened or the best way to fix it, but it is one of the only issues I can think of that would have caused the font to not render correctly.

**Comment by the-maldridge** [comment]
CNR
