### ISSUE TITLE
xbps-src: Address family not supported by protocol

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6884]
Saw this with poppler and cairo. The build fails. Manual restart does succeed. Looks like all that is needed is to change homepage from http -> https

**Comment by ebfe** [comment]
Sounds like an temporary network issue on your side. No need to change anything.

**Comment by the-maldridge** [comment]
CNR

**Comment by The-Fred** [comment]
No temporary network issues at all. In fact only those two failed and those two websites have switched to https. So it may sound like something temporary to you but seems unlikely since only those two sites failed.

**Comment by ebfe** [comment]
> Manual restart does succeed

Sounds temporary to me.

> those two websites have switched to https

Doesn't seem to be true: `xbps-uhelper fetch http://cairographics.org/releases/cairo-1.14.10.tar.xz` still works fine. At least from 3 different endpoints i tried it from, before suggesting it might be  an issue in your network...

Either way, good luck figuring it out.

**Comment by the-maldridge** [comment]
@ebfe  I think he means that the protocol was switched to https in the template and the website doesn't support it.  Though the updates built just fine on Travis, so I dunno what could be going on here.

**Comment by The-Fred** [comment]
Actually I pointed my browser there and the sites redirect to https. There's nothing left to figure out. No other package downloads failed except those two. And those two both redirect a browser to https.

**Comment by ebfe** [comment]
Except a http -> https redirect doesn't cause EAFNOSUPPORT, but whatever. I'm out.

**Comment by The-Fred** [comment]
Yeah that symptom's odd. Maybe yet another bad transparent proxy at the ISP??? FWIW the direct connection to fetch the file using https is about 100 msecs faster.
