### ISSUE TITLE
FYI: qt-5.9.0 does not build with musl libc

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#6893]
Something in the depths of webkit building now completely relies on glibc exposing the weak symbols like `_malloc` and `_free`, which musl libc just does not expose. It happens during the bootstrapping stage of a tool `gn`, which replaces gypi(something), and I have not yet found a way around it. 5.9.0 just fails for musl libc.

This also stalls my try to split qt5 into submodules, which is a different kind of story. But there also cross compiling is failing, which is why I'm kind of sticking up on that try. If the musl libc issues can be solved, also cross compiling for armv7* should be possible with the monolithic approach again. Until then, I won't try anymore.

As the subject says: that's just a FYI and someone may beat me to trying to get issues solved.
You can win an... hum... pink painted unicorn hoof!? Or some honor on the pace to the medal.

**Comment by ebfe** [comment]
Maybe worth to take a look at the chromium patches. IIRC it uses gn too and the issue sounds familiar.

**Comment by ebfe** [comment]
@pullmoll ported over some patches from chromium: https://github.com/ebfe/void-packages/tree/qt5-split 

Seems to build now.

**Comment by ebfe** [comment]
s/qt5-webengine/gn/, needs more patches ported

**Comment by ebfe** [comment]
```
FAILED: gen/components/resources/about_credits.bro                                                               
/usr/bin/python2 ../../3rdparty/chromium/build/gn_run_binary.py x64/bro --force --no-copy-stat --input gen/components/resources/about_credits.html --output gen/components/resources/about_credits.bro
```

**Comment by ebfe** [comment]
@Duncaen i think you've also hit the x86/bro issue in chromium too. Do you remember the fix?

**Comment by ebfe** [comment]
disabling gold on musl fixed that

**Comment by pullmoll** [comment]
Good news! Thanks @ebfe. With this set of patches we can update the monolithic build to 5.9.0.

For the split modules I couldn't get cross building to work, i.e. everything depending upon `qt5-base-devel` is failing with wrong compiler, C{XX]FLAGS or L{,D}FLAGS.

**Comment by ebfe** [comment]
```index: added `qt5-webengine-5.9.0_1' (x86_64-musl).```

Updated the branch.

@pullmoll i used a sledgehammer to disable gold on musl in `files/musl-patches/musl-no-gold.patch`, I'm sure someone who understands the qt config stuff can come up with something better.

Oh, and i take the pink unicorn hoof :)

**Comment by pullmoll** [comment]
Here you go @ebfe
![unicorn_t41](https://user-images.githubusercontent.com/10061347/27749913-e867a566-5dd5-11e7-93fc-d99974ce709e.jpg)

I integrated your patches in my branch. Next I'll be trying to solve cross building issues.

**Comment by pullmoll** [comment]
Closing because qt5-split does not seem to be easy enough for me to finish (read: I can't get it working for cross building qt5).

**Comment by Epictek** [comment]
@pullmoll any luck upgrading qt to 5.9 though?

**Comment by pullmoll** [comment]
IIRC I tried 5.8.0 some time ago. I'd say let's wait for 5.9.2 which is said to be out soon.
Then we need to take some care to get the beast built for all targets (avoid ENOMEM :-)
