### ISSUE TITLE
xinit: too many blank lines in /etc/X11/xinit/xinitrc

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#6950]
I tried to determine where my ```/etc/X11/xinit/xinitrc``` comes from, I guess it's assembled at some point. 

It has a lot of extra blank lines that aren't needed. Nothing fatal but odd.

**Comment by ebfe** [comment]
That's what upstream provides (generated during build from `xinit-1.3.4/xinitrc.cpp`), we don't modify it. If it really bothers you, please file an issue there.
