### ISSUE TITLE
gradle: gradle gui is broken

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#7001]
Looks for `/usr/lib/gradle/bin/gradle`

Maybe just a symlink is needed in the template.
I did:

- `mkdir /usr/lib/gradle/bin/`
- `ln -s /usr/bin/gradle /usr/lib/gradle/bin/gradle`

**Comment by ebfe** [comment]
f3cb8d11eb757ff52cbf0d202d422ffcf5fe29cb
