### ISSUE TITLE
ltrace: crash on musl

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#7010]
ltrace with single functions work, but a glob makes it crash

```
$ ltrace -x '*' -L ls    
Assertion failed: bp->libsym == NULL (proc.c: breakpoint_for_symbol: 820)
Aborted (core dumped)
```

**Comment by ebfe** [comment]
It tries to set a breakpoint at `ls@_fini` twice. There's already an #ifdef to disable that check on __mips__.

**Comment by ebfe** [comment]
34641b7b72b4f4f0f28fc27010025c002ee42bd6
