### ISSUE TITLE
/usr/share/xbps.d/xbps.conf isn't a conf file

### ISSUE THREAD

**Issue by zqqw** [voidlinux/void-packages#7012]
It isn't declared as a conf file in the xbps template. I wanted to use the preserve feature to save a couple of modified non-conf files from being overwritten on updates, up to now I just fixed them manually on updates when needed. I thought I should check it out so ran 
xbps-install -f xbps
and my modifications vanished. -ff should overwrite conf files, -f only does a standard reinstall so ought to be a realistic test.

**Comment by ebfe** [comment]
Custom configuration should be placed in `/etc/xbps.d/*.conf`. See `man xbps.d` for the details.

**Comment by zqqw** [comment]
FILES
     /etc/xbps.d                          Default configuration directory.

     /usr/share/xbps.d                    Default system configuration directory.

OK, that would work, but if that is the solution the man page calls it a configuration directory which it isn't.

**Comment by ebfe** [comment]
It is, it provides the systems default configuration. If you want to change that `/etc/xbps.d` is the place to do so. Feel free to submit a pull request with improved wording for the man page.
