### ISSUE TITLE
findutils locatedb group

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#7032]
wat about making a `locate` system group liek and setting `/var/lib/locate/locatedb` to it so that only members are allowed to use teh db?

`mlocate` pkg is doing this now, but `findutils` is not.

i can do this if its ok.

<3

**Comment by ayghor** [comment]
actually, i just noticed that `mlocate` behaviour is different. anyway, arch does pretty much wat im talking about:

https://wiki.archlinux.org/index.php/users_and_groups

**Comment by chneukirchen** [comment]
What is this good for?

**Comment by ayghor** [comment]
if you `chmod 700 somedir`, everybody can still see teh paths inside it because `/var/lib/locate/locatedb` is readable.

**Comment by ayghor** [comment]
`locate` can be setgid to its own group so that only it will be able to read `locatedb`. then it can be world executable if `locatedb` is in `slocate` format, which wont show users paths they arent allowed to see.

**Comment by chneukirchen** [comment]
So we would need to make glocate setuid glocate, chown the database to glocate, and ensure updatedb uses slocate format, which is not default. I'd be ok with this, but I don't want to add users to a special group to make use of locate at all.

If you care about security, you can just use mlocate right now. ;)

**Comment by ayghor** [comment]
i am using `mlocate` right now, but `glocate` comes with void and with a `cron.daily` job to generate teh unsafe db.

id rather not have that silently by default.

options i see:

  1. setgid, allow world-exec and use `slocate` db
  so we dont need to add anybody to `glocate` group, since teh binary is setgid. this is teh same as `mlocate`.

  2. dont segid, forbid world-exec and keep default db
  we have to add allowed users to `glocate` group, since teh binary isnt world

  3. ~just disable teh default cron job~

**Comment by chneukirchen** [comment]
Disabling the cron job sounds good actually, since almost everyone will have findutils installed, but may not need locate.

**Comment by ayghor** [comment]
noooo lets create a group and a**void** bad surprises its better pleeease =o(

**Comment by chneukirchen** [comment]
I think (1) is the best.

**Comment by chneukirchen** [comment]
I implemented (1), but it's probably not good, glocate will always say:
```
glocate: ‘/var/lib/locate/locatedb’ is an slocate database.  Support for these is new, expect problems for now.         
glocate: ‘/var/lib/locate/locatedb’ is an slocate database.  Turning on the '-e' option.
```

I checked what debian does, and they run updatedb as user nobody. Perhaps this would be a reasonable thing to do, too.

**Comment by ayghor** [comment]
yes this warning is baaad, but running `updatedb` as `nodoby` would _silently_ exclude private stuff from teh index. id rather hit **permission denied** than have `locate` not _locating_.

also, `man glocate` says

> 4.3.2     Support for the slocate database format

and http://ftp.gnu.org/pub/gnu/findutils says

> findutils-4.4.0.tar.gz | 2008-03-15 08:59 | 1.9M

so i suspect that those warnings are mostly harmless. anyway i just asked on findutils mailing list. lets c if they say something about this.

**Comment by ayghor** [comment]
noooooo =o(

**Comment by ayghor** [comment]
ok its better than leaking ty

**Comment by ayghor** [comment]
@chneukirchen just for teh record...

> On Wed, Jul 19, 2017 at 2:46 AM, Bernhard Voelker
