### ISSUE TITLE
gnustep-make: Scripts contain references to build env.

### ISSUE THREAD

**Issue by KenjiTakahashi** [voidlinux/void-packages#7074]
GNUstep is preserving some variables, such as `install` script location, in the final distribution. Right now, it stores paths to /builddir/ locations.
For example, in `/usr/share/GNUstep/Makefiles/config.make:155` there's `INSTALL     = /builddir/.xbps-gnustep-make/wrappers/install -c -p`. This breaks all builds that use gnustep-make (including other gnustep-* libs).

I'd like to go and resolve that, but I'm not sure how. Should I just brute force `sed` it in `post_install`? Or maybe there's a better way?

**Comment by Vaelatern** [comment]
Only that one file has this problem.
A hacky solution in post_install is acceptable for right now.

**Comment by Vaelatern** [comment]
That is of course unless other maintainers who have dealt with this before have better suggestions.

**Comment by KenjiTakahashi** [comment]
Yeah, this case (`wrapper` path) seems to be singular, but there are more strange things.
FYI: I'm trying to package the `gnustep-base` lib, which I need for one of my projects.
Now I've found this:

`/usr/share/GNUstep/Makefiles/config.make:65`: `OPTFLAG  = -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe   -g`

which makes `gnustep-config --objc-flags` return
```bash
-MMD -MP -DGNU_RUNTIME=1 -DGNUSTEP_BASE_LIBRARY=1 -fno-strict-aliasing -pthread -fPIC -Wall -DGSWARN -DGSDIAGNOSE -Wno-import -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fgnu-runtime -I. -I/home/kenji/GNUstep/Library/Headers -I/usr/include
```
that, again, doesn't work.

Not quite sure where these come from, yet.

**Comment by Piraty** [comment]
https://github.com/Piraty/void-packages/blob/23cd06b5e29346a317d5585640f7eb8851b5c52b/srcpkgs/gnustep-make/template
this is what helped me along, if i understood your problem correctly.

**Comment by KenjiTakahashi** [comment]
It does help for the first issue, but not for the second. Also, do we really want to remove this wrapper? I thought it was there for a reason :-].
