### ISSUE TITLE
'valadoc-git' should be changed to 'valadoc'

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#7084]
The [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/valadoc-git/template) for `valadoc-git` is **outdated** and should be changed to `valadoc`, as the Arch [package](https://www.archlinux.org/packages/extra/x86_64/valadoc/). 

````
# Template file for 'valadoc'
pkgname=valadoc
version=0.36.0
revision=1
build_style=gnu-configure
hostmakedepends="pkg-config libtool automake vala-devel"
makedepends="libglib-devel libgee08-devel graphviz-devel"
replaces="valadoc-git>=0"
short_desc="Documentation tool for the vala project"
maintainer="Juan RP <xtraeme@voidlinux.eu>"
license="LGPL-3"
homepage="https://wiki.gnome.org/Projects/Valadoc"
distfiles="${GNOME_SITE}/valadoc/${version%.*}/valadoc-${version}.tar.xz"
checksum=f564ad83ee195d1b4ff1430efad45bde209156e0ad5660bf6d1045f204766789
nocross="error: cannot run C compiled programs"
````

And update the shlibs: 

`libvaladoc.so.0 valadoc-0.36.0_1`

**Comment by ebfe** [comment]
Since you already did the work, how about submitting a PR? :)

**Comment by cr6git** [comment]
I still can't figure out how to "squash" two commits in one PR. :(

**Comment by Anachron** [comment]
git reset --soft HEAD~3 &&
git commit

Example to squash 3 latest commits. Edit as you wish.

**Comment by ebfe** [comment]
Or with git-rebase: see (for example) here: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history for an introduction.

**Comment by cr6git** [comment]
Thank you, I will try today.

**Comment by cr6git** [comment]
Done.
