### ISSUE TITLE
Package Request: FocusWriter

### ISSUE THREAD

**Issue by mopfunk** [voidlinux/void-packages#7087]
[https://gottcode.org/focuswriter/](url)

From the developer's site:
> FocusWriter is a simple, distraction-free writing environment. It utilizes a hide-away interface that you access by moving your mouse to the edges of the screen, allowing the program to have a familiar look and feel to it while still getting out of the way so that you can immerse yourself in your work. It’s available for Linux, Windows, and Mac OS X, and has been translated into many different languages.

Every time I try to compile this on Void I run into errors regarding **hunspell**. I'm not sure what I am doing wrong as I have all of the hunspell libraries and such installed, and I am not yet versed in xbps-src yet to make this package myself.

Any help with this would be excellent, thanks!

**Comment by chneukirchen** [comment]
We can't help if you don't show how you compile it and the exact, full, error message.

**Comment by mopfunk** [comment]
Ok, here is the full error message:

> Project ERROR: hunspell development package not found

The given instructions:

>  1.) Type 'qmake' to configure the program. If you would like to install the
        program somewhere other than /usr/local, pass a new value for PREFIX
        during configuration: 'qmake PREFIX=/opt'.

...followed by 2) 'make' and 3) 'sudo make install'.

I have hunspell, hunspell-devel, libhunspell, and the 32-bit versions of these installed.

**Comment by chneukirchen** [comment]
Do you have pkg-config installed?

**Comment by mopfunk** [comment]
Dang! I thought so, but apparently I did not on this machine. I installed that and zlib-devel, but now I am getting

> Project ERROR: Unknown module(s) in QT: multimedia

So, I am looking into that now.

**Comment by mopfunk** [comment]
Update:

I grabbed qt5-multimedia & qt5-multimedia-devel. This got me through qmake, but when I run **make** I am presented with

>/usr/lib/qt5/bin/lrelease -silent translations/focuswriter_af_ZA.ts -qm translations/focuswriter_af_ZA.qm
>make: /usr/lib/qt5/bin/lrelease: Command not found
>make: *** [Makefile:693: translations/focuswriter_af_ZA.qm] Error 127

I'll keep playing with it when I have time and update if I get it.

**Comment by Anachron** [comment]
You could create a PR with the pkg template.

**Comment by cr6git** [comment]
I have a template that works well. ([screenshot](https://ibb.co/d2Op4k)) 

````
# Template file for 'focuswriter'
pkgname=focuswriter
version=1.6.5
revision=1
build_style=qmake
hostmakedepends="pkg-config"
makedepends="hunspell-devel pulseaudio-devel
 qt5-multimedia-devel qt5-tools-devel"
depends="desktop-file-utils hicolor-icon-theme"
maintainer="local <root@localhost>"
short_desc="Simple, distraction-free writing environment"
homepage="https://gottcode.org/focuswriter/"
license="GPL-3 LGPL-3"
distfiles="https://gottcode.org/focuswriter/${pkgname}-${version}-src.tar.bz2"
checksum=48e949986a65bc51f46f10c075de2904b2e1feb0e1c74c0a8efe99cd8c2de0ce

if [ $CROSS_BUILD ]; then
	hostmakedepends+=" $makedepends"
fi
````

**Comment by mopfunk** [comment]
Excellent. Thanks for making that template.

**Comment by cr6git** [comment]
@Piraty just made the Pull Request [#7260](https://github.com/voidlinux/void-packages/pull/7260).
