### ISSUE TITLE
howto check update for KDE Framework 5 ?

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#7090]
Following PR #6052 : kf5 packages are missing update detection.  
The storage layout of their source files looks like:  
` http://download.kde.org/stable/frameworks/ <version-short> / <file> - <version> . tar.xz`

So I propose the following `update-check` file : 
```
# indirect detection via folder's name: /stable/frameworks/<version-short>/
site=http://download.kde.org/stable/frameworks
pattern=">\K[\d.]+(?=/</a>)"
```

Questions:

1. is it OK to write it like this ? acceptable ?

2. do I have to provide the same `update-check` to each of the ~70 packages or just one on a a subset of them ? Because update happens once a month, so output (into '`void-updates.txt`) can be huge, like 150 lines if 2 months oudated for instance

Thanks for your comments and advices !

**Comment by ebfe** [comment]
Ideally you'd want to check both /stable/frameworks for minor updates and /stable/frameworks/<version-short> for point releases of individual packages? I don't think this is possible with the current machinery. 

As for the 70 update files: we already have custom defaults for some sites in https://github.com/voidlinux/void-packages/blob/master/common/xbps-src/shutils/update_check.sh#L32-L63. Maybe that's appopriate here too.

**Comment by yopito** [comment]
Thanks for the pointer; looks like more efficient, I will give a try on this way to do.
