### ISSUE TITLE
eog & ristretto cannot open grayscale jpegs anymore

### ISSUE THREAD

**Issue by juliendehos** [voidlinux/void-packages#7151]
Error message: Unsupported number of color components (1).

I don't have this problem with png images.

**Comment by cr6git** [comment]
I found the answer on the Arch [forum](https://bbs.archlinux.org/viewtopic.php?id=228382). 
The problem comes from `gdk-pixbuf` and should be fixed soon.

**Comment by juliendehos** [comment]
Salut
Indeed, the problem should be fixed with the next release of gdk-pixbuf. Thanks.
