### ISSUE TITLE
perl-Test-Tester: conflicts with perl

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#7182]
```
perl-Test-Tester-0.109_1.noarch <-> perl-5.24.1_4.x86_64:
	/usr/share/man/man3/Test::Tester.3p
	/usr/share/man/man3/Test::Tester::Capture.3p
	/usr/share/man/man3/Test::Tester::CaptureRunner.3p
```

**Comment by svenper** [comment]
I thought the perl provides and conflicts were generated [programatically](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/perl/files/update-perl-provides.pl) based on what perl provides? Maybe that script is missing something? Or was it just not run for some reason?

There is a bigger issue here: installing other versions of modules provided by core perl itself seems to have no real conflicts except these man pages.

**Comment by chneukirchen** [comment]
perl-Test-Tester was removed in 4aec6d6ea4
