### ISSUE TITLE
oxyen-icons5: conflicts with oxygen-icons

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#7189]
```
oxygen-icons5-5.36.0_1.noarch <-> oxygen-icons-4.14.3_1.noarch:
	/usr/share/icons/oxygen/index.theme
```

**Comment by cr6git** [comment]
For this one, why not: 
````
pkgname=oxygen-icons5
conflicts="oxygen-icons"
````

````
pkgname=oxygen-icons
conflicts="oxygen-icons5"
````

**Comment by cr6git** [comment]
@ebfe I just found a workaround to prevent any conflicts, by modifying the `CMakeLists.txt` that is present in the tarball source `oxygen-icons5-5.36.0.tar.xz` : 
````
27 -set(OXYGEN_INSTALL_DIR ${KDE_INSTALL_ICONDIR}/oxygen/base)
27 +set(OXYGEN_INSTALL_DIR ${KDE_INSTALL_ICONDIR}/oxygen5/base)
...
29 -install( FILES index.theme DESTINATION ${KDE_INSTALL_ICONDIR}/oxygen)
29 +install( FILES index.theme DESTINATION ${KDE_INSTALL_ICONDIR}/oxygen5)
````

With this change I can have both icon themes installed without conflicts. 
But they still have the same name defined in their `index.theme` : 
````
$ cat /usr/share/icons/oxygen/index.theme |grep Name
Name=Oxygen
$ cat /usr/share/icons/oxygen5/index.theme |grep Name
Name=Oxygen
````

**Comment by cr6git** [comment]
Note: KDE depends on `oxygen-icons` while LXQT depends on `breeze-icons` : so changing the path to `/usr/share/icons/oxygen5` should not break these two DE.

**Comment by dutsky** [comment]
why not just add "conflicts"?
