### ISSUE TITLE
mariadb: conflicts with mytop

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#7191]
```
mariadb-10.1.24_1.x86_64 <-> mytop-10.1.24_1.noarch:
	/usr/bin/mytop
```

**Comment by cr6git** [comment]
[mytop](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/mytop) and [mariadb](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/mariadb/template#L123) are actually the same package! :/

**Comment by ebfe** [comment]
Good catch!

**Comment by cr6git** [comment]
Congratulations for you for finding all these conflicts between packages.
