### ISSUE TITLE
apr-util-1.6.0_1.x86_64 problem: apache cannot start ssl crypto engine after update

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#7203]
from apache_error_log:

 `[session_crypto:error] [pid 8526] (20019)DSO load failed: AH01845: The crypto library 'openssl' could not be loaded: /usr/lib/apr-util-1/apr_crypto_openssl-1.so: undefined symbol: EVP_CIPHER_CTX_reset (apr_crypto_openssl-1.so: 0)
[Sun Jul 30 11:59:56.136511 2017] [:emerg] [pid 8526] AH00020: Configuration Failed, exiting
`

searching the web suggests installing apr-util-openssl as a solution, but this package is missing in voids repos...

**Comment by mdkuser** [comment]
seams the issue can be solved by downgrading apr-util to 1.5.4_9.x86_64

**Comment by ebfe** [comment]
62688dfa781ebca90e3f741b0c014f03caa9588b, please try 1.6.0_2

**Comment by mdkuser** [comment]
I hereby confirm that upgrading to apr-util-1.6.0_2.x86_64 solved the problem!
Thank you very much for the swift reply and the quick fix!
