### ISSUE TITLE
docker: Version is "unknown-version"

### ISSUE THREAD

**Issue by bryananderson** [voidlinux/void-packages#7230]
When installed, the Docker client version number becomes "unknown-version" instead of "17.06.0-ce" as it appears in most installations. The server version number is unaffected.

This makes it impossible to run nvidia-docker as it fails to parse the version number.

This individual has the same version number issue with Docker on Void Linux, as of 5 days ago.
https://github.com/moby/moby/issues/34283

My full output of `sudo docker version`:

Client:
 Version:      unknown-version
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   v17.06.0-ce
 Built:        Sun Jul  9 09:17:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by cr6git** [comment]
Not sure, but I noticed that the Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/docker#n84) uses a VERSION variable: 

`make VERSION=$pkgver-ce dynbinary`

The Void [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/docker/template#L28) does not use it: 

`hack/make.sh dynbinary`

**Comment by cr6git** [comment]
This morning I tried to build `docker-17.06.0` and I noticed these lines: 
````
=> docker-17.06.0_1: running do_build ...
# WARNING! I don't seem to be running in a Docker container.
# The result of this command might be an incorrect build, and will not be
# officially supported.
#
# Try this instead: make all
#
````
Incorrect build ? 
Weird... 
Maybe it's just related to linux-4.12, as your link points in that direction.

**Comment by Epictek** [comment]
I'm also having the same issue as OP

**Comment by cr6git** [comment]
Maybe @thypon has an idea ?

**Comment by arete** [comment]
commit 2cde47b0a6d010805b2d76370c27830c0b517094 fix this issue ?
```
 docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:15:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   v17.11.0-ce
 Built:        Tue Nov 28 17:25:15 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thypon** [comment]
yep, fixed.
