### ISSUE TITLE
Calibre missing dependency ?

### ISSUE THREAD

**Issue by n0p513d** [voidlinux/void-packages#7244]
Went to use calibre today and got this error message:

    Traceback (most recent call last):
    File “/usr/lib/calibre/calibre/gui2/main.py”, line 292, in initialize_db_stage2
    self.start_gui(db)
    File “/usr/lib/calibre/calibre/gui2/main.py”, line 232, in start_gui
    main.initialize(self.library_path, db, self.listener, self.actions)
    File “/usr/lib/calibre/calibre/gui2/ui.py”, line 239, in initialize
    ac.do_genesis()
    File “/usr/lib/calibre/calibre/gui2/actions/init.py”, line 145, in do_genesis
    self.genesis()
    File “/usr/lib/calibre/calibre/gui2/actions/add.py”, line 80, in genesis
    from calibre.ebooks.oeb.polish.create import valid_empty_formats
    File “/usr/lib/calibre/calibre/ebooks/oeb/polish/create.py”, line 18, in
    from calibre.ebooks.oeb.polish.parsing import parse
    File “/usr/lib/calibre/calibre/ebooks/oeb/polish/parsing.py”, line 12, in
    import html5_parser
    ImportError: No module named html5_parser

**Comment by cr6git** [comment]
I think your are right: `python-html5lib` is missing in the Void [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/calibre/template) while it's present in the Arch [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/calibre).

**Comment by n0p513d** [comment]
I have that installed though.

**Comment by cr6git** [comment]
See [commit](https://github.com/voidlinux/void-packages/commit/e7bca63eb88d25202aa98e9d2059097f9d0a734b).
