### ISSUE TITLE
gnuplot: lacking functionality without pngcairo

### ISSUE THREAD

**Issue by The-Fred** [voidlinux/void-packages#7245]
As you can see gnuplot devs place confidence/precedence in pngcairo terminal as one of the most important.

http://gnuplot.sourceforge.net/demo_5.0/

> Demo scripts for gnuplot version 5 (pngcairo terminal)

https://github.com/voidlinux/void-packages/blob/master/srcpkgs/gnuplot/template#L47

**Comment by chneukirchen** [comment]
Then use `gnuplot-wx`?

**Comment by abenson** [comment]
This also seems to break plotting with wxMaxima

**Comment by abenson** [comment]
Ah, it looks like gnuplot-wx does in fact work fine. If you have both installed (wx/x11), you need to make sure wx is set as the active gnuplot.

    xbps-alternatives -g gnuplot -s gnuplot-wx
