### ISSUE TITLE
Libreoffice fails with "Application Error"

### ISSUE THREAD

**Issue by stevelitt** [voidlinux/void-packages#7248]
On a terminal, logged in as root or a normal user, type the command:
libreoffice
You'll see the splash screen start to appear, and then the error message "Application Error" appears on the command line of the terminal you were using.

It also acts the same if you type libreoffice whatever.odt, whether or not whatever.odt really exists.

This has happened on 2 different Void computers, x64, up to date. I first noticed it about 3 weeks ago: This being August 2, it would have been around July 10, 2017 that I first noticed it.

**Comment by pullmoll** [comment]
Works perfectly fine here. We need to find what differences are between you environment and an up to date environment with the latest libreoffice (which is currently 5.3.4.2).

**Comment by stevelitt** [comment]
Void Linux. According to libreoffice --version:

LibreOffice 5.0.4.2 2b9802c1994aa0b7dc6079e128979269cf95bc78

So I xbps-install -u libreoffice

ERROR: [trans] failed to download `libreoffice-5.3.4.2_1' package from `https://repo.voidlinux.eu/current': Not Found

So I' m now going to try repo1, repo2, repo3, and repo4. I live in Orlando, Florida, and have been having lots of trouble with the various repositories not working during the past 6 weeks.

I'll let you know the results.

**Comment by ebfe** [comment]
> LibreOffice 5.0.4.2 2b9802c1994aa0b7dc6079e128979269cf95bc78

That is very old. Do you still have the long removed `libreoffice-bin` installed?

> ERROR: [trans] failed to download libreoffice-5.3.4.2_1' package fromhttps://repo.voidlinux.eu/current': Not Found

The current version in the repo is `libreoffice-5.3.4.2_2`. Maybe add running `xbps-install -S` to your troubleshooting routine? ;)

**Comment by ebfe** [comment]
https://repo.voidlinux.eu/current/libreoffice-5.3.4.2_2.x86_64.xbps

https://repo.voidlinux.eu/current should work. The other mirrors might currently be out of date due to repo3. running out of space.

**Comment by stevelitt** [comment]
I resolved the issue, with the help of the folks on #xbps, as follows:
* Change all files in /usr/share/xbps.d and /etc/xbps.d to repo.voidlinux.eu
* xpbs-install -S
* xbps-install -u
* xbps-remove libreoffice-bin
* xbps-install libreoffice

This was primarily a repo issue created by my changing /usr/share/xbps.d instead of confining my changes to /etc/xbps.d, combined with the recent problems with repo3.
