### ISSUE TITLE
swh-lv2 build fails

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#7255]
Trying to build the package `swh-lv2` , it fails with this error message: 
````
=> swh-lv2-1.0.15_4: running pre-pkg hook: 99-pkglint ...
=> ERROR: swh-lv2-1.0.15_4: PKGDESTDIR is empty and build_style != meta
=> ERROR: swh-lv2-1.0.15_4: cannot continue with installation!
````
Why ? Wrong template ? 
I searched in the Issues for a similar problem with this package, and I noticed that `swh-lv2` is present in the **list of Issues** published by @pullmoll in [#4825](https://github.com/voidlinux/void-packages/issues/4825).

**Comment by ebfe** [comment]
Last build 2014, package contained no files. not many users of that package apparently :)

**Comment by cr6git** [comment]
Thank you @ebfe ! 
swh plugins are useful with audacity , for example.
