### ISSUE TITLE
spacefm: cross compilation fails

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#7268]
Cross compilation fails because of something wrong related to `libstdc++.so.6` and `libffmpegthumbnailer.so` , as you can see in my [build log](https://bpaste.net/show/951bcd087b70). 

I discovered this problem when I was trying to compile `spacefm-ng` (fork), producing the same error! 
Good night.

**Comment by ebfe** [comment]
You are trying to build a `x86_64-musl` in a x86_64 masterdir.

**Comment by cr6git** [comment]
This is not possible ?

**Comment by cr6git** [comment]
According to [#cross-compiling-packages-for-a-target-architecture](https://github.com/voidlinux/void-packages#cross-compiling-packages-for-a-target-architecture) , it's possible to run: 

`$ ./xbps-src -a <target> pkg <pkgname>`

So, please @ebfe can you explain to me why it's different for `spacefm` ?
Thank you.

**Comment by Johnnynator** [comment]
You can only cross compile for a different target CPU architecture but not for a different c library

**Comment by cr6git** [comment]
@Johnnynator Ah ok, I understand my error now. Thank you!!
