### ISSUE TITLE
Package Request: cbatticon

### ISSUE THREAD

**Issue by ctucx** [voidlinux/void-packages#7281]
Hello,
i'm wanted to try void-linux but im missing the lovely cbatticon utility!
wish to have a package for it. 

https://github.com/valr/cbatticon

greetings, 
ctucx

**Comment by cr6git** [comment]
@ctucx Here's the GTK2 version, but maybe you prefer GTK3? I don't know ;)

**Comment by cr6git** [comment]
Added GTK3 version! [#7291](https://github.com/voidlinux/void-packages/pull/7291)

**Comment by cr6git** [comment]
@ctucx [Merged](https://github.com/voidlinux/void-packages/commit/52021cb92edc9723637a13af0a1c43d44d43cc95). You can close this ;)

**Comment by maxice8** [comment]
as cr6git mentioned, resolved

@the-maldridge
