### ISSUE TITLE
glibc-2.26 breakage

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#7307]
Packages which are broken after the glibc-2.26 update:

- [x] diffutils-3.6 when cross compiling
- [ ] xbps-0.51_18 needs to be updated to upstream
- [x] llvm-4.0.1 is broken for std::isnan() and std::isinf()
- [x] iproute2-4.10.0 update to 4.12.0 seems to fix it
- [x] mysql-5.6.30 std::isfinite() issue
```
In file included from /builddir/mysql-5.6.30/include/probes_mysql.h:21:0,
                 from /builddir/mysql-5.6.30/storage/heap/ha_heap.cc:20:
/builddir/mysql-5.6.30/sql/item_func.h: In member function 'double Item_func::fix_result(double)':
/builddir/mysql-5.6.30/include/my_global.h:768:26: error: '__builtin_isfinite' is not a member of 'std'
   #define my_isfinite(X) std::isfinite(X)
                          ^
```
- [x] libGL-17.1.5 lots of std::is... functions not defined
- [x] atom-1.19.0 std::isfinite() not defined
- [x] eigen-3.3.4 std::isfinite() not defined

**Comment by Gottox** [comment]
#7259 

Also see https://blog.fefe.de/?ts=a77b2171 (german)

**Comment by pullmoll** [comment]
Regarding #7259 it looks like you have missed @xtraeme already [having pushed the glibc-2.26 update](https://github.com/voidlinux/void-packages/commit/cabef7df181360af7d604e6485cd3175c987a6d5)?
Also updating the cross compilers to glibc-2.26 as well was missing after this step.
We need to be careful when updating packages now, this is why I'm collecting known breakages here.

**Comment by Gottox** [comment]
:/ indeed I missed that.

**Comment by Gottox** [comment]
I read something that this update broke some i686 systems. Can s/o verify this?

**Comment by pullmoll** [comment]
I'm still rebuilding packages based on a bootstrap with the new glibc-2.26 etc.
Once the base packages are done, I can create an i686 ISO and give it a try.

**Comment by pullmoll** [comment]
Ping @xtraeme. What shall we do with pkgs broken due to glibc-2.26 update: replace std:is* with __builtin_is* or try to find the issue behind it and fix that?

I for one have currently no idea why the std::is* functions are no longer visible or became invalid.

**Comment by chneukirchen** [comment]
I think `#include <cmath>` should be enough for these functions. This is exactly what C++11 specifies.

**Comment by Gottox** [comment]
@Duncaen found a commit regarding glibc breakage. Unfortunately I only have the commit hash of the commit

**Comment by Gottox** [comment]
Are there compilerflags that enable the old behavior again? - The correctest behavior is utterly bullshit (sorry for the Torvaldism) if it breaks our packages.

**Comment by pullmoll** [comment]
> I think #include <cmath> should be enough for these functions.

For llvm I tried to `#include <cmath>` both after and before `#include <cstdint>` in `include/llbm/Support/NativeFormatting.h`.

Now there are some more errors  besides the known ones :-P
```
/builddir/llvm-4.0.1.src/projects/compiler-rt/lib/builtins/atomic.c: In function 'unlock':
/builddir/llvm-4.0.1.src/projects/compiler-rt/lib/builtins/atomic.c:93:3: warning: implicit declaration of function '__c11_atomic_store' [-Wimplicit-function-declaration]
   __c11_atomic_store(l, 0, __ATOMIC_RELEASE);
   ^~~~~~~~~~~~~~~~~~
/builddir/llvm-4.0.1.src/projects/compiler-rt/lib/builtins/atomic.c: In function 'lock':
/builddir/llvm-4.0.1.src/projects/compiler-rt/lib/builtins/atomic.c:99:11: warning: implicit declaration of function '__c11_atomic_compare_exchange_weak' [-Wimplicit-function-declaration]
   while (!__c11_atomic_compare_exchange_weak(l, &old, 1, __ATOMIC_ACQUIRE,
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

So no, including cmath does not seem to solve the problem.

**Comment by pullmoll** [comment]
Looking at `/usr/include/c++/6.3/cmath` I see many of the seemingly missing definitions being wrapped in one or more of
```
#ifndef __CORRECT_ISO_CPP_MATH_H_PROTO
```
```
#ifndef __CORRECT_ISO_CPP_MATH_H_PROTO_FP
```
```
#ifndef __CORRECT_ISO_CPP_MATH_H_PROTO_INT
```
and I see no definition of this macro in e.g. `/usr/include/c++/6.3/x86_64-unknown-linux-gnu/bits/c++config.h` or anywhere else below `/usr/include`. This doesn't help me to understand where the real problem arises from...

**Comment by chneukirchen** [comment]
Upstream fix: https://sourceware.org/ml/libc-alpha/2017-08/msg00586.html

**Comment by pullmoll** [comment]
Problems are solved.
