### ISSUE TITLE
rkt: circular dependencies

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#7312]
rkt -> rkt-stage1
rtk-stage1-coreos (provides rkt-stage1) -> rkt

https://forum.voidlinux.eu/t/segmentation-fault-when-removing-rkt-using-xbps-remove/3177

**Comment by thypon** [comment]
solved upstream

**Comment by da99** [comment]
That was fast. (I was the one who submitted on the Void forums.)
Thanks for fixing it @ebfe  and @thypon
