### ISSUE TITLE
man top segfaults

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#7330]
```
$ man top
Falha de segmentação
```

or perhaps

```
$ export LANG=C
$ man top
Segmentation fault
```

will investigate soon if nobody cares before me

**Comment by m-cz** [comment]
I'd bet it's related to [this](http://mdocml.bsd.lv/cgi-bin/cvsweb/man_term.c?rev=1.209&content-type=text/x-cvsweb-markup).

**Comment by m-cz** [comment]
Yep, bumping mdocml version to 1.14.3 (and removing srcpkgs/mdocml/patches/boundary-check.patch) fixes it for me.
