### ISSUE TITLE
 Firefox 55 crash on x86_64-musl (Multiprocess Problem)

### ISSUE THREAD

**Issue by chmod77** [voidlinux/void-packages#7350]
Since Firefox 54 for Musl, firefox open with crash tabs. The temporary solution is disable the e10s (multiprocess) manually.

For this: (Temporary Fix)
1 - about:config
2 - browser.tabs.remote.autostart = false
3 - browser.tabs.remote.autostart2 = false

The old open bug is here: https://github.com/voidlinux/void-packages/issues/6746
**edit: Re-open the issue:** It's not a extension problem as related. Now, I test with clean profile (sudo rm -rf ~/.mozilla) and the problem persists.

**Comment by chmod77** [comment]
**Problem resolved:** Is not a firefox bug. 

The problem is result of a specific extension.

**Comment by chmod77** [comment]
**Problem resolved:** Is not a firefox bug.

The problem is result of a specific extension.

**Comment by Gottox** [comment]
Which extension?

**Comment by chmod77** [comment]
Gottox.

Stylus, a stilish alternative with webextension.

**Comment by chmod77** [comment]
I will re-open this issue. The problem persists.

**Comment by Duncaen** [comment]
Found the issue after a lot of back and forth debugging with `gdb` and `strace`, musl a different flag in the `clone(2)` syscall.
It was already reported upstream as [Bug 1376653](https://bugzilla.mozilla.org/show_bug.cgi?id=1376653) and fixed but its not yet part of the release. I'm going to backport the patch and push it afterwards.

**Comment by chmod77** [comment]
Thanks a lot, Duncaen!
