### ISSUE TITLE
Opera 47 broken - requiring rpi-userland as a dependency

### ISSUE THREAD

**Issue by rGabiru** [voidlinux/void-packages#7354]
Cannot update opera to the version 47 because it's requiring a dependency `rpi-userland` (armv-musl) which is not available in x86_64 systems.

**Comment by ebfe** [comment]
#4723

**Comment by m-wynn** [comment]
https://github.com/voidlinux/void-packages/pull/7353

**Comment by zraffer** [comment]
the same
