### ISSUE TITLE
mbpfan service is broken (@the-maldridge)

### ISSUE THREAD

**Issue by egorenar** [voidlinux/void-packages#7367]
Hi,

I installed mbpfan service on my MacBook Pro and the console is getting flooded
with this message:

`chpst: option requires an argument -- f`

This fixed the problem:

/etc/sv/mbpfan/run:
#!/bin/sh
exec 2>&1
exec mbpfan -f

Regards

**Comment by cr6git** [comment]
Why did you put (@the-maldridge) in the title ?

**Comment by the-maldridge** [comment]
@cr6git because I asked to be mentioned in IRC.

**Comment by the-maldridge** [comment]
resolved in 8d0bbdf9f29e63e0f22667306a606fe2e67f6bae
