### ISSUE TITLE
cryptsetup: LUKS doesn't work with sha3-512

### ISSUE THREAD

**Issue by dxtr** [voidlinux/void-packages#7404]
I have an encrypted drive with sha3-512 that I created with Arch Linux and it cryptsetup simply isn't buying it:

```
$ cryptsetup luksDump /dev/sdc
Requested LUKS hash sha3-512 is not supported.
```

According to lsmod sha3_generic is loaded:

```
$ lsmod|grep -i sha3
sha3_generic           16384  0
```

The package version I have installed:
```
$ xbps-query -s cryptsetup
[*] cryptsetup-1.7.5_1    Setup virtual encryption devices under Linux dm-crypt
[*] libcryptsetup-1.7.5_1 Setup virtual encryption devices under Linux dm-crypt - runtime libraries
```

```
$ uname -a
Linux greger 4.11.11_1 #1 SMP PREEMPT Sat Jul 15 21:48:45 UTC 2017 x86_64 GNU/Linux
```

**Comment by chneukirchen** [comment]
Do you know how you created that one? sha3 only seems to be supported by libgcrypt, but we use libressl.

**Comment by dxtr** [comment]
Something like 
```
cryptsetup luksFormat -h sha3-512 -c aes-xts-plain64 -s 512 -y /dev/sdc
```
libgcrypt? I thought cryptsetup used the kernel cryptography facilities.

**Comment by chneukirchen** [comment]
No, the header decryption is done in userspace.

You'll have to tweak the template to use gcrypt and rebuild cryptsetup if you want to open this on Void.

**Comment by chneukirchen** [comment]
I think we should enable cryptsetup-reencrypt however, then you can change the hash if you want.

**Comment by chneukirchen** [comment]
Silly me, you need to run cryptsetup-reencrypt on Arch...

**Comment by dxtr** [comment]
Oh, well that explain a lot!

Closing this considering it's a non-issue then.
