### ISSUE TITLE
mpv failing with dvb-t

### ISSUE THREAD

**Issue by neoklis** [voidlinux/void-packages#7428]
Hi

Lately I am getting this error message from mpv:

```
Playing: dvb://PIK HD
No protocol handler found to open URL dvb://PIK HD
The protocol is either unsupported, or was disabled at compile-time.
```
Perhaps it needs to be re-compiled with dvb support?

Apologies if I am doing something wrong myself....

**Comment by chneukirchen** [comment]
Release notes say "DVB support is disabled by default since it does not work with some older kernels.", but I guess this doesn't affect us?

**Comment by chneukirchen** [comment]
8ff538c5db
