### ISSUE TITLE
gbdfed will not run

### ISSUE THREAD

**Issue by neoklis** [voidlinux/void-packages#7429]
Hi,

I tried to install and run gbdfed but I get this message:

`gbdfed: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
`
Perhaps it needs to be re-compiled to link with the new version of libpng?

**Comment by chneukirchen** [comment]
Do you have an old freetype, you either held back packages or built something yourself? Official binaries use libpng16.so.

**Comment by neoklis** [comment]
Oh, my apologies here - although I checked that there was no gbdfed in /usr/bin, there was an old version in /usr/local/bin that was started by bash in place of the installed /usr/bin/gbdfed.
I must have installed it my self a long time ago and forgotten about it :-(

Well, done, you suggested the right thing....
