### ISSUE TITLE
libxslt: includes xlocale.h

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#7432]
libxslt includes xlocale.h in the header files in xsltlocale.h which is shipped in the libxslt-devel package. Since xlocale.h has been removed in glibc-2.26, this leads to compilation failures for software using libxslt. I encountered this while trying to recompile kodi locally.

Just removing the xlocale.h include from that file removes the immediate compilation failure since everything that was in xlocale.h earlier is now indirectly included in locale.h, but since the detection of locale support in libxslt's configure script depends on the availability of xlocale.h, the configure script would also have to be changed to fix locale detection with glibc>=2.26. I haven't found a way to do this cleanly (yet).

**Comment by chneukirchen** [comment]
I think the fallback code works fine, so rebuilding is good enough?

**Comment by Hoshpak** [comment]
I don't understand what the fallback code does but after a rebuild, XSLT_LOCALE_XLOCALE is not set so xlocale.h is not included. If we don't loose any functionality this way, that would do it. I wonder why it didn't work for me the first time I tried to just rebuild the package but that's probably just a case of the package already being installed and me not checking if the locally build version was used.

**Comment by chneukirchen** [comment]
AFAICS the fallback code just loads locale.h (modulo one typedef to void*, which doesn't matter.)
