### ISSUE TITLE
wrong libGL simlinks on nvidia driver

### ISSUE THREAD

**Issue by Altai-man** [voidlinux/void-packages#7440]
I am not sure how proprietary driver hooks work exactly, but it seems it doesn't work for me.

Latest `nvidia` package is installed and used, but on attempt to run wine I'm getting:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  262
  Current serial number in output stream:  266
```
Judging by googling, it may be the wrong simlink, but it seems that everything is okay:
```
# find /usr -iname "*libGL.so*" -exec ls -l {} \; 
lrwxrwxrwx 1 root root 14 Aug 15 13:53 /usr/lib/libGL.so -> libGL.so.1.0.0
lrwxrwxrwx 1 root root 14 Aug 15 13:53 /usr/lib/libGL.so.1 -> libGL.so.1.0.0
-rwxr-xr-x 1 root root 665712 Aug 15 13:53 /usr/lib/libGL.so.1.0.0
lrwxrwxrwx 1 root root 14 Aug 11 12:01 /usr/lib32/libGL.so -> libGL.so.1.2.0
-rwxr-xr-x 1 root root 444124 Aug 11 12:03 /usr/lib32/libGL.so.1.2.0
lrwxrwxrwx 1 root root 14 Aug 11 12:01 /usr/lib32/libGL.so.1 -> libGL.so.1.2.0
```

I **don't** use Steam, just running different applications on wine and the result is the same. All things I'm running work perfectly with wine.

Things like glxgears from `mesa-demo` package work fine.

**Comment by Hoshpak** [comment]
Do you have nvidida-libs-32bit from the multilib repository installed? Since the nvidia-libs package provides libGL.so.1.0.0 and currently there is libGL.so.1.2.0 which is provided by the libGL package in the lib32 directory, it looks like you might be using the mesa libGL for 32bit applications like wine which would explain the error.

**Comment by Altai-man** [comment]
Thanks, @Hoshpak!

If really resolved the issue. I wonder why proprietary drivers page doesn't mention that. Closing.
