### ISSUE TITLE
*-musl builders need to be scrubbed

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#7443]
The *musl builders need to be scrubbed: **ENOSPC**.

Perhaps a `./xbps-src purge-distfiles` and binary bootstrap for the build environments.

**Comment by Duncaen** [comment]
Purged distfiles, cleaned up the `ccache` and executed the clean repo script.

```
/dev/mapper/Repo3Storage-BuildbotHostdir  237G  106G  132G  45% /hostdir
```

**Comment by pullmoll** [comment]
Thank you @Duncaen
