### ISSUE TITLE
Firefox 55 on Musl X64 [Click on login/pass field crashs the tab]

### ISSUE THREAD

**Issue by chmod77** [voidlinux/void-packages#7461]
1 - Open Firefox
2 - Goes to reddit page https://www.reddit.com/ or https://github.com/
3 - Click on the login field, now alternate to password field (with tab key) and the current firefox tab crashs

Terminal shows the error:
 **###!!! [Parent][MessageChannel] Error: (msgtype=0x280080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv**

**EDITED:**
With **firefox --verbose** on term, i can grab a new error message:
**###!!! [Parent][MessageChannel] Error: (msgtype=0x800017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv**

strace -o test.log firefox
```
writev(2, [{iov_base="\n###!!! [Parent][MessageChannel]"..., iov_len=40}, {iov_base="(msgtype=0x800017,name=PHttpChan"..., iov_len=84}], 2) = 124
writev(2, [{iov_base="\n\n", iov_len=2}, {iov_base=NULL, iov_len=0}], 2) = 2
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=26, events=POLLIN}, {fd=27, events=POLLIN}], 4, 0) = 0 (Timeout)
write(12, "\0", 1)                      = 1
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=26, events=POLLIN}, {fd=27, events=POLLIN}], 4, 0) = 0 (Timeout)
writev(2, [{iov_base="\n###!!! [Parent][MessageChannel]"..., iov_len=40}, {iov_base="(msgtype=0x280080,name=PBrowser:"..., iov_len=77}], 2) = 117
writev(2, [{iov_base="\n\n", iov_len=2}, {iov_base=NULL, iov_len=0}], 2) = 2
```

**A curiosity:** 
When click on Firefox / Preferences / Advanced / General (Tab) /
The field: Use **hardware acceleration when available** is missing

Hardware Information:
**00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)**
Tested with: Linux 4.12.5_1 and Linux 4.11.11_1

**Comment by Duncaen** [comment]
Can't reproduce, did you try a clean profile?

**Comment by chmod77** [comment]
Yes, Duncaen. Clean profile

With **firefox --verbose** i can grab a new error message
**###!!! [Parent][MessageChannel] Error: (msgtype=0x800017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv**

I'm tried to change my xorg monitor defaults, but the error persists.
Test with uxa / sna / DRI2 / DRI3 / Tear Free ON/OFF

A curiosity: When click on Firefox / Preferences / Advanced / General (Tab) / 
The field: **Use hardware acceleration when available** is missing

**Comment by chmod77** [comment]
If I turn OFF the e10s (firefox multiprocess)
**browser.tabs.remote.autostart;false**
**browser.tabs.remote.autostart.2;false**

The problem is gone.

**Comment by chmod77** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1371708

**Comment by chmod77** [comment]
strace -o test.log firefox

```
writev(2, [{iov_base="\n###!!! [Parent][MessageChannel]"..., iov_len=40}, {iov_base="(msgtype=0x800017,name=PHttpChan"..., iov_len=84}], 2) = 124
writev(2, [{iov_base="\n\n", iov_len=2}, {iov_base=NULL, iov_len=0}], 2) = 2
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=26, events=POLLIN}, {fd=27, events=POLLIN}], 4, 0) = 0 (Timeout)
write(12, "\0", 1)                      = 1
recvmsg(4, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=4, events=POLLIN}, {fd=5, events=POLLIN}, {fd=26, events=POLLIN}, {fd=27, events=POLLIN}], 4, 0) = 0 (Timeout)
writev(2, [{iov_base="\n###!!! [Parent][MessageChannel]"..., iov_len=40}, {iov_base="(msgtype=0x280080,name=PBrowser:"..., iov_len=77}], 2) = 117
writev(2, [{iov_base="\n\n", iov_len=2}, {iov_base=NULL, iov_len=0}], 2) = 2
```

**Comment by Duncaen** [comment]
This is the parent process, try to `MOZ_DEBUG_CHILD_PROCESS=1 firefox` and then attach strace to the new child process, it prints the pid and waits until a debugger is attached.

**Comment by chmod77** [comment]
> This is the parent process, try to MOZ_DEBUG_CHILD_PROCESS=1 firefox and then attach strace to the new child process, it prints the pid and waits until a debugger is attached.

Thanks for the tip, Duncaen :)

Now new messages appears:
 ```
MOZ_DEBUG_CHILD_PROCESS=1 firefox
  2 CHILDCHILDCHILDCHILD
  3   debug me @ 4919
  4 
  5 ATTENTION: default value of option force_s3tc_enable overridden by environment.
  6 
  7 ###!!! [Parent][MessageChannel] Error: (msgtype=0x800017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv
  8 
  9 
 10 ###!!! [Parent][MessageChannel] Error: (msgtype=0x280080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
 11 
 12 [Parent 27743] WARNING: pipe error (46): Connection reset by peer: file /builddir/firefox-55.0.2/ipc/chromium/src/chrome/common/ipc_channel_pos    ix.cc, line 353
 13 
 14 [Parent 29641] WARNING: pipe error (60): Connection reset by peer: file /builddir/firefox-55.0.2/ipc/chromium/src/chrome/common/ipc_channel_pos    ix.cc, line 353
```

**Comment by Duncaen** [comment]
> ` 3   debug me @ 4919`

You need to attach strace to the new child process: `strace -p 4919`.

**Comment by chmod77** [comment]
Thanks, Duncaen! For the explanations on #voidlinux IRC channel

The problem is caused by dconf package. Firefox 55 is work like a charm!
