### ISSUE TITLE
xombrero segfaults on startup

### ISSUE THREAD

**Issue by tac1ica** [voidlinux/void-packages#7475]
Just now I tried xombrero for the first time and according to what it prints on the console, it's segfaulting on startup right after opening the GUI. I can't find any log, here's the console output:

`xombrero: config_parse: cannot open /home/tactica/.xombrero.conf: No existe el fichero o el directorio`

`(xombrero:12016): Gtk-WARNING **: Theme parsing error: xombrero.css:28:11: Not using units is deprecated. Assuming 'px'.`

`(xombrero:12016): Gtk-WARNING **: Theme parsing error: xombrero.css:29:10: Not using units is deprecated. Assuming 'px'.`

`(xombrero:12016): Gtk-WARNING **: Theme parsing error: xombrero.css:36:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version`
`Violación de segmento`

This is on a 100% up to date x86_64-glibc void. And no, creating the .conf file manually doesn't help.

**Comment by Gottox** [comment]
I think it's best to remove xombrero. There's no active development since years and even the Github page states [it's retired](https://github.com/conformal/xombrero) - One webkit1/gtk2 dependency less.
