### ISSUE TITLE
easyrsa: not working

### ISSUE THREAD

**Issue by xYuusha** [voidlinux/void-packages#7478]
The easyrsa package is not working right now. Every command returns errors like

```bash
140016168154816:error:0EFFF068:configuration file routines:CRYPTO_internal:variable has no value:conf/conf_def.c:563:line 3

Easy-RSA error:

Missing or invalid OpenSSL
Expected to find openssl command at: /usr/bin/openssl
```
I think the issue is from [upstream](https://github.com/OpenVPN/easy-rsa/issues/74).

**Comment by cavalier911** [comment]
Libressl not working with easy-rsa was reported upstream back in 2015.
https://github.com/OpenVPN/easy-rsa/issues/76
https://bugs.gentoo.org/show_bug.cgi?id=605460
The workaround in the 2nd comment of the gentoo bug report did not work for me.
I ended up booting into a distro using openssl to use easy-rsa.

**Comment by xYuusha** [comment]
Thanks for pointing me to the gentoo bug report. I made it work but it's quite hackish and I don't think that can be added as a fix right now.

**Comment by dutsky** [comment]
to be fair, there are good replacement(but unfortunately with GUI) to easy-rsa called [xca](http://xca.sourceforge.net/"). It's already in void packages.

**Comment by Gottox** [comment]
removed easyrsa. They don't seem to be interested in fixing this issue.

**Comment by cavalier911** [comment]
@Gottox 
Please remove easyrsa-3.0.4_1  from all package repos.
