### ISSUE TITLE
perl not working 

### ISSUE THREAD

**Issue by dinama** [voidlinux/void-packages#7499]
after latest upgrade all perl modules report -  "loadable library and perl binaries are mismatched"

> i3-dmenu-desktop 
> Dumper.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

> sudo perl -MCPAN -e 'upgrade'
> Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

**Comment by chneukirchen** [comment]
Sounds like you didn't update your system completely.

There should be no references to perl 5.24 in the repos anymore.

**Comment by dinama** [comment]
> uname -a
Linux pbox 4.11.12_1 #1 SMP PREEMPT Thu Aug 17 15:14:00 UTC 2017 x86_64 GNU/Linux

> sudo xi -Su
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo2.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo2.voidlinux.eu/current/multilib/x86_64-repodata' ...
[*] Updating `https://repo2.voidlinux.eu/current/nonfree/x86_64-repodata' ...

> i3-dmenu-desktop 
Dumper.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

**Comment by chneukirchen** [comment]
```
% xq perl | sed 1q
pkgver: perl-5.26.0_1
% md5sum /usr/lib/perl5/**/Dumper.so 
ef4ab99ddb85ac7d72fbd325fd78efd9  /usr/lib/perl5/core_perl/auto/Data/Dumper/Dumper.so
```

(i3-dmenu-desktop works fine here.)

**Comment by dinama** [comment]
```
$ xq perl | sed 1q
pkgver: perl-5.26.0_1

$ md5sum /usr/lib/perl5/core_perl/auto/Data/Dumper/Dumper.so
ef4ab99ddb85ac7d72fbd325fd78efd9  /usr/lib/perl5/core_perl/auto/Data/Dumper/Dumper.so

$ xq perl | grep Dumper
perl-Data-Dumper-2.167_1

$ i3-dmenu-desktop 
Dumper.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
```

**Comment by dinama** [comment]
```
$md5sum /usr/lib/perl5/site_perl/auto/Data/Dumper/Dumper.so
40293f6c87d3a1b35b8d9860ad1b6551  /usr/lib/perl5/site_perl/auto/Data/Dumper/Dumper.so
```
how i can remove  "site_perl" and leave "core_perl" revision?

**Comment by chneukirchen** [comment]
Sounds like you installed Data::Dumper manually, from CPAN or something?

You need to rebuild all packages in /usr/lib/perl5/site_perl then after the perl update.
(This dir should not be used by Void, will fix the three packages that do it...)

**Comment by dinama** [comment]
> Sounds like you installed Data::Dumper manually, from CPAN or something?

maybe as dependent package from over manually installed (like JSON). i can't see this because
```
$perldoc perllocal
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
``` 
>You need to rebuild all packages in /usr/lib/perl5/site_perl then after the perl update

thank you.

**Comment by dinama** [comment]
cpan also broken
```
cpan -u
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
```

**Comment by dinama** [comment]
problem solved by removing site_perl directories  perl -V (/usr/share/perl5/site_perl/ ,  /usr/lib/perl5/site_perl/)
