### ISSUE TITLE
Replace ntp by openntpd

### ISSUE THREAD

**Issue by Ypnose** [voidlinux/void-packages#752]
Hi,
Do you think it's a good idea to replace <code>ntp</code> by <code>openntpd</code>?

**Comment by Ypnose** [comment]
An <code>openntpd-portable</code> port is WIP. Could be very interesting for us. Here → https://github.com/openntpd-portable/openntpd-portable

**Comment by xtraeme** [comment]
openntpd-5.7p1 has been packaged and is available now in void.

Will be made the default soon via xbps.d(5) (virtualpkg).

**Comment by Ypnose** [comment]
Thx to you, xtraeme :bear:

**Comment by uggedal** [comment]
Is it working for you @Ypnose? @xtraeme was saying on IRC that it was
broken.

**Comment by Ypnose** [comment]
@uggedal Didn't try yet. Will do it tomorrow and I'll report back if necessary.

**Comment by xtraeme** [comment]
My fault, it's working correctly.. simply that setproctitle() does not.

I reported this upstream, will be fixed in the next release.

I'm using it in server mode on the rpi and my other computers on the lan
sync off it.

Cheers

2015-01-09 19:44 GMT+01:00 Ypnose <notifications@github.com>:
