### ISSUE TITLE
diffutils: cross compiling for aarch64-musl generates a bad program

### ISSUE THREAD

**Issue by lonwillett** [voidlinux/void-packages#7539]
The version of "diff" for aarch64-musl that is in the repositories segfaults for context diffs (-u, -c, maybe more). I found that rebuilding the package natively generates a version that works correctly, while cross-compiling it results in the erroneous behaviour.

So it would seem that cross compiling has some fairly serious problems. I imagine that lack of resources make this a fairly low priority issue, so I don't know how you want to handle this. But people should at least be made aware of this fact.

**Comment by newbluemoon** [comment]
I just encountered the very same issue independently on armv7l-musl (Raspberry Pi 3). For further testing I set up a i686-musl masterdir on a native i686 machine to cross compile diffutils in a 32-bit environment but the situation remains the same. I don’t have an armv7l glibc environment right now but it works on x86_64-musl, i686, but not on i686-musl.
