### ISSUE TITLE
gcc package does not contains xbps-src's triplet for cpp

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#7544]
while building burp2-server:
* x86_64 glibc native build:  configure output: 
    ```
    checking how to run the C preprocessor... cpp
    ```
* cross x86_64 musl buid:  configure output
    ```
    checking how to run the C preprocessor... x86_64-linux-musl-cpp
    configure: error: in `/builddir/burp-2.1.16':
    configure: error: C preprocessor "x86_64-linux-musl-cpp" fails sanity check
    ```
"string" `x86_64-linux-musl-cpp` seems to be provided by `$CPP` from xbps-src.

but gcc package for x86_64-musl that not provides `(/usr/bin/)x86_64-linux-musl-cpp` :
```
$ XBPS_TARGET_ARCH=x86_64-musl xbps-query -M -R \
                  --repository=https://repo.voidlinux.eu/current/musl -f gcc \
                  | grep -e  "\(x86_64-linux-musl\|cpp\)" | grep "/bin/"
/usr/bin/x86_64-linux-musl-c++
/usr/bin/x86_64-linux-musl-g++
/usr/bin/x86_64-linux-musl-gcc-ranlib
/usr/bin/x86_64-linux-musl-gcc-ar
/usr/bin/x86_64-linux-musl-gcc-6.3.0
/usr/bin/x86_64-linux-musl-gcc
/usr/bin/cpp
/usr/bin/x86_64-linux-musl-gcc-nm
/usr/lib/cpp -> /usr/bin/cpp
```

I did not check other arches.

**Comment by Duncaen** [comment]
Not sure if this is really an error, you use the cross compiler `cross-x86_64-linux-musl` if you cross compile for `x86_64-musl` which contains `/usr/bin/x86_64-linux-musl-cpp`.
You should create a `x86_64-musl` masterdir and compile natively instead.

**Comment by yopito** [comment]
ah yes, my bad. My crossbuild env must be broken somehow, so a complety wrong analysis. 
Sorry for the noise and thanks for your help.
