### ISSUE TITLE
Broken package: irssi

### ISSUE THREAD

**Issue by DirectorX** [voidlinux/void-packages#7547]
```
➜  ~ irssi
LibXML.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
```

**Comment by Gottox** [comment]
🙄 give me a sec.

**Comment by Gottox** [comment]
Works for me. which version of perl and irssi is installed?

**Comment by DirectorX** [comment]
```
➜  ~ irssi -v
irssi 1.0.4 (20170705 1712)
➜  ~ perl -v
This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux
```

**Comment by Gottox** [comment]
Output of:
```
xbps-query -p pkgver irssi
xbps-query -p pkgver perl
```

**Comment by DirectorX** [comment]
```
➜  ~ xbps-query -p pkgver irssi
irssi-1.0.4_2
➜  ~ xbps-query -p pkgver perl
perl-5.26.0_1
```

**Comment by Gottox** [comment]
Are there any perl modules installed?

**Comment by DirectorX** [comment]
nop

**Comment by Gottox** [comment]
I cannot reproduce your problem here. Are there any more informations you can provide? (scripts/plugins/similar)

**Comment by DirectorX** [comment]
yes. im using this script https://github.com/autodl-community/autodl-irssi
It is quite large and complex and there is a chance that it is the source of the problem.

**Comment by Gottox** [comment]
can you try to disable it?

**Comment by DirectorX** [comment]
yes, irssi works well without it.

**Comment by Gottox** [comment]
Okay, are you sure you didn't install the dependencies via cpan?

**Comment by DirectorX** [comment]
only `HTML::Entities`

**Comment by Gottox** [comment]
tried reinstalling it?

**Comment by DirectorX** [comment]
yes

**Comment by Gottox** [comment]
From my PoV this is a problem with third party software. We cannot help you with that.

**Comment by ebfe** [comment]
> LibXML.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

perl-XML-LibXML up to date?

**Comment by DirectorX** [comment]
yes http://search.cpan.org/dist/XML-LibXML/LibXML.pod

**Comment by ebfe** [comment]
The error message suggest your XML::LibXML was built against an older perl
release. `perl-XML-LibXML-2.0129_2` from the repo works fine on x86_64. Maybe
you installed it manually or with cpan?

If `perl -e 'use XML::LibXML;'` produces the same error message you need to
rebuild it.

**Comment by DirectorX** [comment]
```
➜  ~ perl -e 'use XML::LibXML;'
LibXML.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)
```

nice shot @ebfe
