### ISSUE TITLE
csync 0.50 built-in plugins (sftp) missing

### ISSUE THREAD

**Issue by jfcolom** [voidlinux/void-packages#7552]
when csyncing remote using SFTP:

`csync /mirror/ sftp://server/mirror/`

I get the following message:

`[2017/09/02 14:25:33.853812, 4] csync_vio_init:  loading sftp plugin failed - /usr/lib/csync-0/csync_sftp.so: cannot open shared object file: No such file or directory
csync_init: No such file or directory`

**Comment by Hoshpak** [comment]
Since #7562 has been merged yesterday and the package been rebuilt, the following plugins are now included in the package:

```
# xbps-query -Rf csync | grep csync-0
/usr/lib/csync-0/csync_smb.so
/usr/lib/csync-0/csync_owncloud.so
/usr/lib/csync-0/csync_sftp.so
```

Could you please update the package on your system and check if it works for you now?

**Comment by jfcolom** [comment]
It works!

Thank you very much.

`csync /mirror/ sftp://server:/mirror/`
(note the ':' after the server name)
