### ISSUE TITLE
Package request: cadence

### ISSUE THREAD

**Issue by jarbowski** [voidlinux/void-packages#7572]
Running PulseAudio on top of JACK is a pain and QJackCtl doesn't help much.
From the official jackaudio site: "remove QJackCtl if you use that and install Cadence from the KXStudio repositories. From within Cadence you can enable the ALSA and PulseAudio bridges with the GUI. Done."

http://kxstudio.linuxaudio.org/Applications:Cadence

jack_capture and zita-ajbridge are the only missing (but optional) dependencies in the repo

**Comment by cr6git** [comment]
````
=> cadence-0.8.1_1: running do_build ...
make -C c++/jackmeter
make -C c++/xycontroller
pyrcc4 -py3 resources/resources.qrc -o src/resources_rc.py
make: pyrcc4: Command not found
=> ERROR: cadence-0.8.1_1: failed to run do_build() at line 9.
````

As I understand it: `pyrcc4` must be part of `python3-PyQt4-devel`, but this package is not available in Void repos. 
😕

**Comment by Johnnynator** [comment]
@cr6git It is in python-PyQt4-devel-tools.

**Comment by cr6git** [comment]
OK! I'll tray again...

**Comment by cr6git** [comment]
@jarbowski I wonder what the Void devs are waiting for...

**Comment by cr6git** [comment]
@jarbowski it's done!
