### ISSUE TITLE
srcpkg xorriso template

### ISSUE THREAD

**Issue by Yann-Kaelig** [voidlinux/void-packages#7595]
xorrisos-1.4.7 build failed with : ERROR: SHA256 mismatch for 'xorriso-1.4.7.tar.gz:'

[VoidLinux-Xorriso-1.4.7-Logfile.txt](https://github.com/voidlinux/void-packages/files/1288700/VoidLinux-Xorriso-1.4.7-Logfile.txt)

Version 1.4.7 is a development snapshot, there is no .sig file ( need confirmation )

I propose a downgrade to the stable version 1.4.6 with .sig file

[xorriso-1.4.6-template.txt](https://github.com/voidlinux/void-packages/files/1288738/xorriso-1.4.6-template.txt)

Successful pkgsrc building on x86_64 arch

[VoidLinux-Xorriso-Logfile.txt](https://github.com/voidlinux/void-packages/files/1288732/VoidLinux-Xorriso-Logfile.txt)

**Comment by Vaelatern** [comment]
Downgraded xorriso to stable 9e32c97
