### ISSUE TITLE
qucs: broken after glibc update from 2.25 to 2.26

### ISSUE THREAD

**Issue by pienjo** [voidlinux/void-packages#7604]
(also reported to qucs upstream)

The recent update of libgc to 2.26 seems to have broken qucs. While the GUI seems to work just fine, the actual simulator ("qucsator") crashes, even on trivial schematics. I have narrowed this down to the update of glibc; if I downgrade glibc and glibc-devel to 2.25_6 qucsator works again. 

Downgrading glibc is not a feasible workaround; there are several binaries that no longer work (including sudo)

**Comment by newbluemoon** [comment]
The build date of qucs is 2017-07-26 and glibc 2.26 was introduced on 2017-08-05. So I did a rebuild of qucs against glibc 2.26, but it still crashes.

**Comment by pienjo** [comment]
I have narrowed this down; it looks like it's a bug in qucs (which triggers undefined behaviour). Apparently, the result of the undefined behaviour is different when using glibc-2.26 than it is with glibc-2.25, but that's not glibc's fault..

I'm working on a patch
