### ISSUE TITLE
HowTo fix dpkg

### ISSUE THREAD

**Issue by r0br0dz** [voidlinux/void-packages#7653]
I needed the [redox toolchain](https://static.redox-os.org/toolchain/apt/). 

If you install `dpkg` *now 930PM EST* and try to install a `.deb`, it will fail.

## Solution
`mkdir -p /var/lib/dpkg/updates`
`touch /var/lib/dpkg/status` 
`mkdir /var/lib/dpkg/info`
`touch /var/lib/dpkg/format-new`

I hope the next installation of dpkg causes no errors for the user.

**Thank you devs!!!**

*ps: this is my very first contribution to open-source on github*

**Comment by chneukirchen** [comment]
Note that using dpkg as a package manager is not supported on Void Linux.

**Comment by r0br0dz** [comment]
I am not. Im installing software that is only in deb format. I believe the
pkg maintainer needs to address the issue. Closing the issue under an
assumption was a mistake.

**Comment by Gottox** [comment]
We strongly suggest to NOT install software on void using dpkg. This likely will break your system pretty soon. This is not supported and will never be supported.
