### ISSUE TITLE
Replace caddy with wedge in light of caddy's new EULA

### ISSUE THREAD

**Issue by lemmi** [voidlinux/void-packages#7657]
Yesterday the caddy maintainers announced their new commercial licenses along with a new EULA for their free version as well. (Applying to the binaries they provide on their site, not self-compiled binaries)
https://caddyserver.com/blog/accouncing-caddy-commercial-licenses.html

Especially [this commit](https://github.com/mholt/caddy/commit/ad973f1d125d4da9ba8bc21448dcd3de3fe79cbe) is source for a lot of grief.
It introduces a Header to every HTTP Response that includes the name of their sponsors. Users of their binary version are not allowed to temper that header with other tools. The config file won't allow for removing that header even for self-compiled versions.

This is an unacceptable situation for us, but we have a few options:

1. remove caddy
2. patch caddy ourselves (which I think is legally allowed)
3. replace caddy with [https://github.com/WedgeServer/wedge](https://github.com/WedgeServer/wedge), a caddy fork that removes the header.

I think option 3 is the most sensible. The caddy developers seem to be content with this fork aswell. 

@SevereOverfl0w @voidlinux/pkg-committers

**Comment by SevereOverfl0w** [comment]
Why is 1 a requirement? The code is still apache licensed, so there's no
need to remove it altogether.

**Comment by lemmi** [comment]
@SevereOverfl0w we had a short discussion on IRC and at that time this the favourite option, which is why I included it. Adding wedge doesn't mean we have to remove the old caddy version. I'd like to keep version 0.10.8 around for a while to give people time to migrate.

**Comment by KenjiTakahashi** [comment]
FYI: https://github.com/mholt/caddy/pull/1866

**Comment by lemmi** [comment]
I'm glad this blew over, and mholt being a real professional about it.
