### ISSUE TITLE
Why Google Chrome and Slack are restricted?

### ISSUE THREAD

**Issue by cryptomaniac512** [voidlinux/void-packages#7678]
Why [google-chrome](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/google-chrome/template) and [slack-desktop](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/slack-desktop/template) packages are restricted?

**Comment by Duncaen** [comment]
Because they don't allow to redistribute binaries.
