### ISSUE TITLE
autofs: build package

### ISSUE THREAD

**Issue by jfcolom** [voidlinux/void-packages#7693]
When building the autofs package (`./xbps-src build autofs`), i get the following error.

`
=> lvm2: building (dependency of nfs-utils) ...
=> lvm2-2.02.173_1: installing host dependency 'pkg-config-0.29.2_1' ...
=> lvm2-2.02.173_1: installing target dependency 'libblkid-devel-2.30.1_1' ...
=> lvm2-2.02.173_1: installing target dependency 'readline-devel-7.0.000_1' ...
=> lvm2-2.02.173_1: installing target dependency 'eudev-libudev-devel-3.2.2_1' ...
=> lvm2-2.02.173_1: running do-fetch hook: 00-distfiles ...
=> lvm2-2.02.173_1: fetching distfile 'LVM2.2.02.173.tgz'...
looking up mirrors.kernel.org
connecting to mirrors.kernel.org:443
SSL options: 80004014
Peer verification enabled
Using CA cert path: /etc/ssl/certs
Verify hostname
TLSv1.2 connection established using ECDHE-RSA-AES128-GCM-SHA256
Certificate subject: /OU=Domain Control Validated/OU=PositiveSSL Multi-Domain/CN=kernel.org
Certificate issuer: /C=FR/ST=Paris/L=Paris/O=Gandi/CN=Gandi Standard SSL CA 2
requesting https://mirrors.kernel.org/sourceware/lvm2/LVM2.2.02.173.tgz
https://mirrors.kernel.org/sourceware/lvm2/LVM2.2.02.173.tgz: Not Found
=> ERROR: lvm2-2.02.173_1: failed to fetch LVM2.2.02.173.tgz.
`

Effectively, lvm2-2.02.173_1 is missing in mirrors.kernel.org

**Comment by ebfe** [comment]
Should be fixed in master: 2bda3977eb8e53e7201c5d6507d8403d4bef5847

**Comment by jfcolom** [comment]
Thank you very much,
I've locally made the changes stated in [2bda397](https://github.com/voidlinux/void-packages/comit/2bda3977eb8e53e7201c5d6507d8403d4bef5847), and now lvm2 gets built.
However, now i get a compilation error when building nfs-utils. As now I understand that this is not realted to autofs, i will open another issue
