### ISSUE TITLE
nfs-utils: compilation error

### ISSUE THREAD

**Issue by jfcolom** [voidlinux/void-packages#7695]
When building nfs-utils, i get the following compilation error:

`make[3]: Entering directory '/builddir/nfs-utils-1.3.4/support/nsm'
cc -DHAVE_CONFIG_H -I. -I../../support/include  -I/usr/include/tirpc -D_GNU_SOURCE -Wall -Wextra -Wstrict-prototypes  -pipe -specs=/void-packages/common/environment/configure/gccspecs/hardened-cc1  -fstack-protector-strong -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -MT rpc.o -MD -MP -MF .deps/rpc.Tpo -c -o rpc.o rpc.c
rpc.c: In function 'nsm_recv_getport':
rpc.c:469:13: error: 'UINT16_MAX' undeclared (first use in this function)
  if (port > UINT16_MAX) {
             ^~~~~~~~~~
rpc.c:469:13: note: each undeclared identifier is reported only once for each function it appears in
rpc.c: In function 'nsm_recv_getaddr':
rpc.c:506:25: error: 'UINT16_MAX' undeclared (first use in this function)
  if (port < 0 || port > UINT16_MAX) {
                         ^~~~~~~~~~
make[3]: *** [Makefile:449: rpc.o] Error 1
make[3]: Leaving directory '/builddir/nfs-utils-1.3.4/support/nsm'
make[2]: *** [Makefile:394: all] Error 2
make[2]: Leaving directory '/builddir/nfs-utils-1.3.4/support/nsm'
[student@study void-packages]$ make[1]: *** [Makefile:427: all-recursive] Error 1
make[1]: Leaving directory '/builddir/nfs-utils-1.3.4/support'
make: *** [Makefile:469: all-recursive] Error 1
=> ERROR: nfs-utils-1.3.4_3: failed to run do_build() at line 13.
`

Seems that `#include <stdint.h>` is missing in rpc.c

**Comment by ebfe** [comment]
This is also already fixed in master cd8af586a8b00a8ba162d070ac1a4e9cb8d28da9

Please update you repository.

**Comment by jfcolom** [comment]
Done, Thank you!

**Comment by matthew-l-weber** [comment]
I've ran into a similar issue.  Looks like Glibc 2.26 is at fault.
