### ISSUE TITLE
julia: Target architecture mismatch

### ISSUE THREAD

**Issue by espectalll** [voidlinux/void-packages#7710]
Here's the entire log I get every time I try to run Julia:

    ERROR: Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}.

The error is being reported on `x86_64`, after verifying the system was clean of system files from previous Julia manual builds.

**Comment by silvernode** [comment]
https://github.com/JuliaLang/julia/issues/10639

I am looking into it, and I am building it now with some flags. I hope it works

**Comment by silvernode** [comment]
@espectalll sent you an email

**Comment by silvernode** [comment]
@espectalll Well the build is complete and the installed package works but that doesn't mean it will work for you. I'm not sure if I should send you the package directly to make sure it works or if I should just commit to the repo

**Comment by espectalll** [comment]
I can confirm it works on my machine natively. Let me try out as `i686` and I'll confirm if it works there too.

**Comment by espectalll** [comment]
...not working on `i686`, as shown on the next screenshot, with a chroot and a Virtualbox VM:

![captura de pantalla de 2017-09-18 17-52-54](https://user-images.githubusercontent.com/2456419/30551234-2ae352e8-9c9a-11e7-9968-c9c759727a6b.png)

This is likely easy to fix, so give me a moment... I wish it was easier to debug how things will be built in prod, though.

**Comment by silvernode** [comment]
Looks like a solid fix, great work.

**Comment by silvernode** [comment]
apparently, this is a thing in their README:  

*You can also set MARCH=native for a maximum-performance build customized for the current machine CPU.*

**Comment by espectalll** [comment]
Yes, I'm aware. The problem is, I don't think it's properly detecting the architecture.

...in fact, it seems that the i686 builds are still failing???

**Comment by wangp** [comment]
Unfortunately building for core2 on x86_64 means the binary does not work on a Phenom II processor which lacks SSSE3:
```
ERROR: The current host does not support SSSE3, but the system image was compiled for Core2.
Please delete or regenerate sys.{so,dll,dylib}.
```
For comparison, the official build does work.
