### ISSUE TITLE
Opera package requires rpi-userland on x64??

### ISSUE THREAD

**Issue by seisatsu** [voidlinux/void-packages#7759]
The opera package requires the rpi-userland package on x64, which obviously doesn't exist.

$ sudo xbps-install opera
MISSING: rpi-userland>=0.0.0.0.20150907_1
Transaction aborted due to unresolved dependencies.

**Comment by Johnnynator** [comment]
#4723 and #7354

**Comment by cr6git** [comment]
@Johnnynator have you noticed that the same file was present in `vivaldi` package: 

`/opt/vivaldi/swiftshader/libGLESv2.so`

But the problem with `rpi-userland` does not occur, however.

**Comment by Johnnynator** [comment]
@cr6git a file can be in many packages, the questions is whether smth links against it in the same package.
