### ISSUE TITLE
wine: binary package broken with freetype-2.8.1

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#7760]
Running any application with wine currently results in an immediate crash:

```
# wine iexplore
fixme:winediag:start_process Wine Staging 2.16 is a testing version containing experimental patches.
fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
fixme:ole:CoResumeClassObjects stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
wine: Unhandled page fault on read access to 0x00000004 at address 0x7e78ad0b (thread 0009), starting debugger...
winedbg: Internal crash at 0x7e829d0b
```

This is apparently caused by the freetype-2.8.1 update since downgrading freetype-32bit to 2.8 resolves the issue.

**Comment by maxice8** [comment]
I'd like to add that only graphical applications seem to be affected, i ran various Chess UCI engines and all of them worked.

**Comment by tsudoko** [comment]
Graphical applications which don't use the Win32 GUI don't seem to be affected. Winecfg and several PC emulators crash, but QEMU and certain games work fine.
