### ISSUE TITLE
breeze-gtk: does not work properly with gtk3 applications

### ISSUE THREAD

**Issue by mstraube** [voidlinux/void-packages#7762]
breeze-gtk-5.8.7_1 does not work properly with gtk3 applications. Gtk2 seems not affected.
Updating breeze-gtk to 5.10.5 solved it for me.

e.g.   caja-1.18.3_1

5.8.7
![caja1](https://user-images.githubusercontent.com/20053197/30708698-131b81f4-9f00-11e7-9cf9-76a081965882.png)
 
`(caja:8071): Gtk-WARNING **: Theme parsing error: gtk.css:2785:46: The :insensitive pseudo-class is deprecated. Use :disabled instead.`

5.10.5
![caja2](https://user-images.githubusercontent.com/20053197/30708816-6687f980-9f00-11e7-8283-e51ab59c0284.png)

no warning in terminal

**Comment by dutsky** [comment]
just select another gtk3 theme in KDE's systemsettings like Adwaita or something like that

**Comment by Yann-Kaelig** [comment]
You get this issue because breeze-gtk-5.8.7 CMakeLists.txt has this lines:

set(WITH_GTK3_VERSION 3.18 CACHE STRING
    "Use the theme for the specified GTK+3 version (default: 3.18)")

but breeze-gtk since version 5.10.0 doesn't has this.

**Comment by mstraube** [comment]
Ah, thanks. Maybe [this](https://cgit.kde.org/breeze-gtk.git/commit/?id=d25084c791d82850fb9ea0f3a5ad178e28991e4b) should be backported? Solved it for me.
