### ISSUE TITLE
Arduino, avr-gcc > 6.3.0_1

### ISSUE THREAD

**Issue by vctrex** [voidlinux/void-packages#7785]
Can we upgrade avr-gcc? 6.3.0_1 breaks Arduino making Serial library unable to compile.

**Comment by ebfe** [comment]
#7427

**Comment by liwakura** [comment]
I attempted to upgrade avr-gcc in #6849, and avr-gcc 7.1.0 segfaulted when invoked via the Arduino IDE.

**Comment by ebfe** [comment]
e4444878b1fb3cfce19bcf83b0bff99aa4652c74
