### ISSUE TITLE
Boost update to 1.65.1 is breaking Libreoffice

### ISSUE THREAD

**Issue by rGabiru** [voidlinux/void-packages#7807]
During my system update i get the error of broken dependencies:
`boost-1.65.1_1 (update) breaks installed pkg `libcmis-0.5.1_2'`
`boost-1.65.1_1 (update) breaks installed pkg libreoffice-5.4.0.3_2'`

`Transaction aborted due to unresolved dependencies.`

**Comment by ebfe** [comment]
boost rebuild in progress, try again later. https://build.voidlinux.eu/waterfall

**Comment by rGabiru** [comment]
Quick response! thanks
