### ISSUE TITLE
Missing qt5-quickcontrols in depends in template from cura

### ISSUE THREAD

**Issue by teldra** [voidlinux/void-packages#7823]
It is missing qt5-quickcontrols to use gui.

**Comment by teldra** [comment]
https://github.com/voidlinux/void-packages/pull/7863

**Comment by karl-nilsson** [comment]
@teldra Uranium is the GUI framework used by Cura, and it already pulls in python-PyQt5-quick
I incorrectly assumed python-PyQt5-quick pulled in qt5-quickcontrols

I just submitted a PR #7999
Let me know if you have any other problems with this package
