### ISSUE TITLE
memtest86+ doesn't run at all

### ISSUE THREAD

**Issue by 0rdy** [voidlinux/void-packages#7860]
After selection the memtest86+ entry in my GRUB2 menu I can see only the Void logo and nothing else appears. GRUB2 with x86_64 EFI support .

Other Void user has the same problem.

**Comment by liwakura** [comment]
Can you check if the memtest binary is present in /boot?

**Comment by 0rdy** [comment]
Hm.  I have the executable file  with name memtest86+ within /boot. 
`` 
~ ❯  file /boot/memtest86+ 
/boot/memtest86+: DOS/MBR boot sector
``

**Comment by yopito** [comment]
hello,

I've test removal and reinstall of `memtest86+` without any problem, but it's a MBR boot-based system.

Try to reinstall memtest86+ package:
```
$ sudo xbps-reconfigure  -f memtest86+
memtest86+: configuring ...
Generating grub configuration file ...
Found background: /usr/share/void-artwork/splash.png
Found linux image: /boot/vmlinuz-4.12.13_1
Found initrd image: /boot/initramfs-4.12.13_1.img
Found linux image: /boot/vmlinuz-4.11.12_1
Found initrd image: /boot/initramfs-4.11.12_1.img
Found linux image: /boot/vmlinuz-4.10.17_1
Found initrd image: /boot/initramfs-4.10.17_1.img
Found memtest86+ image: /memtest86+
done
memtest86+: configured successfully.
```

Also check grub's config for memtest, although it's part of the package, so it's should have not changed:

```
$ cat /etc/grub.d/20_memtest86+ 
#! /bin/sh
set -e

# older versions of grub2 do not have this yet (LP: #459080)
if [ ! -e /usr/share/grub/grub-mkconfig_lib ]; then
    echo "no grub-mkconfig_lib, exiting"
    exit 0
fi

. /usr/share/grub/grub-mkconfig_lib

if test -e /boot/memtest86+ ; then
  MEMTESTPATH=$( make_system_path_relative_to_its_root "/boot/memtest86+" )
  echo "Found memtest86+ image: $MEMTESTPATH" >&2
  cat << EOF
menuentry "Memory test (memtest86+)" {
EOF
  prepare_grub_to_access_device ${GRUB_DEVICE_BOOT} | sed -e "s/^/\t/"
  cat << EOF
	linux16 $MEMTESTPATH
}
menuentry "Memory test (memtest86+, serial console 115200)" {
EOF
  prepare_grub_to_access_device ${GRUB_DEVICE_BOOT} | sed -e "s/^/\t/"
  cat << EOF
	linux16 $MEMTESTPATH console=ttyS0,115200n8
}
EOF
fi
```

**Comment by chneukirchen** [comment]
memtest doesn't work with EFI, never did.

**Comment by 0rdy** [comment]
@yopito I've tried to reinstall the memtest86+ package without success. Also I have /etc/grub.d/20_memtest86+  same as you.

**Comment by 0rdy** [comment]
@chneukirchen the memtest website asserts that the software supports both UEFI and BIOS. At least version 7.4. 

There is [memtest86-efi ](https://aur.archlinux.org/packages/memtest86-efi) in AUR.

**Comment by yopito** [comment]
@0rdy: thanks for the pointer. BTW, memtest86+ (http://www.memtest.org/) and memtest86 (http://memtest86.com) are not the same projects.

@chneukirchen: I guess the boot sequence was `UEFI > grub > memtest86+` for UEFI systems. So memtest86+ does not work in that case, have to boot memtest86+ directly from UEFI ?

**Comment by chneukirchen** [comment]
memtest+ is not memtest, memtest+ doesn't work on EFI.

memtest is closed source.

**Comment by 0rdy** [comment]
Well, I understood that the open-source memtest86+, which was included in the Void repository, has no UEFI support. Then I close this issue.
