### ISSUE TITLE
qt5: move lrelease to qt5-host-tools?

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#7872]
```
qt-host-tools-4.8.7_23  /usr/lib/qt/bin/lrelease
qt5-tools-5.8.0_8       /usr/lib/qt5/bin/lrelease
```

One reason qt5-host-tools sometimes isn't  enough to get cross builds working is lrelease. It's already part of host tools for qt-4.

**Comment by pullmoll** [comment]
Definitely.
