### ISSUE TITLE
mbedtls: lots of binaries in /usr/bin

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#7934]
mbedtls pollutes /usr/bin with many binaries of test programs:

```
/usr/bin/hello
/usr/bin/mini_client
/usr/bin/strerror
/usr/bin/benchmark
...
```

I guess some of them can be useful, but probably should go into a separate package, or be renamed.

**Comment by ebfe** [comment]
Fixed in  #12032
