### ISSUE TITLE
hiawatha needs polarssl compiled with POLARSSL_THREADING_PTHREAD

### ISSUE THREAD

**Issue by Gottox** [voidlinux/void-packages#795]
... otherwise it will fail with

```
PolarSSL was compiled without the required POLARSSL_THREADING_PTHREAD compiler flag.
```
at start

**Comment by robotanarchy** [comment]
Same issue with mbedtls now, hiawatha says this when started:
> mbed TLS was compiled without the required MBEDTLS_THREADING_PTHREAD compiler flag.

**Comment by Gottox** [comment]
fixed, thanks for reporting
