### ISSUE TITLE
Package request:rstudio

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#7975]
Hello, if any of you can and got the time can you please take a look at Rstudio

https://github.com/rstudio/rstudio/

Thanks

**Comment by Piraty** [comment]
rstudio exists in the repository already, although it is slightly outdated; therefore the title of this issue doesn't match the situation.
( run `xbps-query -Rs rstudio` to see for yourself )
1.0.153 is current, according to https://www.rstudio.com/products/rstudio/download/

**Comment by icf20** [comment]
a mistake on my part
