### ISSUE TITLE
sddm with ConsoleKit2 broken after 0.16.0 update

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#8048]
Sddm 0.16.0 introduced Seat support for logind and ConsoleKit2. Unfortunately, the implementation doesn't work with ConsoleKit (upstream bug https://github.com/sddm/sddm/issues/903) so sddm is broken and doesn't start any more when ConsoleKit2 is running. I don't know how many sddm users there are on Void but that would break graphical login for many of them. Therefore I think it would be best to revert to 0.15.0 until a fix is available.

**Comment by KenjiTakahashi** [comment]
Here I am :-]. And yes, it did break the DM, I just had no time to look into it, so thanks for the info.

**Comment by the-maldridge** [comment]
Agreed, I am preparing the revert now.

**Comment by cr6git** [comment]
@the-maldridge sddm seems broken again, on x86_64-musl.
