### ISSUE TITLE
libressl-2.1.2_2 update breaks some packages

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#809]
[root@SkyLittleSystem ~]# xbps-install -u
    libressl-2.1.2_2 breaks `libevent-2.0.21_5' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `libmowgli-2.0.0_8' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `librtmp-2.4_5' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `neon-0.30.1_1' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `python3.4-3.4.2_1' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `ruby-2.2.0_1' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `serf-1.3.8_1' (needs `libssl.so.27', got 'libssl.so.29')
    libressl-2.1.2_2 breaks `wpa_supplicant-2.3_4' (needs `libssl.so.27', got 'libssl.so.29')
    Transaction aborted due to unresolved shlibs.

**Comment by ayghor** [comment]
seems libevent was solved just a second ago

**Comment by ayghor** [comment]
only python3 is broken now

**Comment by xtraeme** [comment]
There's a massive package rebuilding due to libressl-2.1.2, some packages are being still built (including python3.4).

Check http://build.voidlinux.eu to see its progress.

**Comment by ayghor** [comment]
ok thank you!
