### ISSUE TITLE
webkit2gtk 2.18.0_1 broken

### ISSUE THREAD

**Issue by emdete** [voidlinux/void-packages#8159]
since i upgraded to 2.18.0 webpages are not rendered correctly (for example in epiphany) anymore.

**Comment by pullmoll** [comment]
I can confirm problems with `webkit2gtk` when it's used in `evolution` to render e-mails containing HTML. It hangs or crashes every now and then when switching between mails and an empty box where the text should be displayed is all I can see most of the times.

After closing evolution there are one or more WebKitWebProcess processes hanging and hogging CPU time.

**Comment by ebfe** [comment]
does downgrading glib help?

**Comment by pullmoll** [comment]
I can't downgrade to 2.54.0_1 for some reason.
`xbps-install -Sf glib-2.54.0_1` fails even though the package is in my `/var/cache/xbps`. Am I missing something?

**Comment by ebfe** [comment]
Hmm, did downgrading with xbps-install ever work? I always use xdowngrade /var/cache/xbps/...

If you still have glib-2.52.x that would be a better test. 2.54.0 -> 2.54.1 doesn't look interesting.

**Comment by pullmoll** [comment]
I have 2.52.3_1 and must admit I never downgraded anything :)

**Comment by pullmoll** [comment]
Downgraded and without reboot I see no differece, i.e. evolution's webkit2gtk processes still crash sometimes.

**Comment by ebfe** [comment]
webkit2gtk-dbg would be useful :(

```
#0  0x00007f851bb27cbc in bmalloc::Heap::isLarge(std::lock_guard<bmalloc::StaticMutex>&, void*) () from /usr/lib/libjavascriptcoregtk-4.0.so.18
#1  0x00007f851bb26999 in bmalloc::Deallocator::deallocateSlowCase(void*) () from /usr/lib/libjavascriptcoregtk-4.0.so.18
#2  0x00007f851f955395 in ?? () from /usr/lib/libwebkit2gtk-4.0.so.37
#3  0x00007f851f931cdb in ?? () from /usr/lib/libwebkit2gtk-4.0.so.37
#4  0x00007f851fc4198d in ?? () from /usr/lib/libwebkit2gtk-4.0.so.37
```

**Comment by pullmoll** [comment]
Well, StaticMutex suggests that indeed there may be a dead-lock situation which causes WebKitWebProcess to hang an hog CPU. I'll take a look at webkit2gtk's configure options.

**Comment by ebfe** [comment]
looks more like it's spinning in a for loop with absurd bounds.

**Comment by pullmoll** [comment]
Perhaps this is related: https://lists.webkit.org/pipermail/webkit-gtk/2017-October/003158.html

**Comment by ebfe** [comment]
```
  4 if (NOT USE_SYSTEM_MALLOC)                                                                                                                                                                                                    
  5     add_subdirectory(bmalloc)                                                                                                                                                                                                 
  6 endif ()   
```

we could try disabling bmalloc

**Comment by Anachron** [comment]
I have the same issue with qutebrowser which (sometimes) leaves QTWebEngine Render processes around after closing related windows. 

This happens especially when I have a lot if sites open and close them rapidly.

Not sure if it's related, I'll try to investigate.

**Comment by pullmoll** [comment]
FWIW the problem persists with the updated versions of evolution-3.26.1_1 and webkit2gtk-2.18.1_1, which has USE_SYSTEM_MALLOC=ON now.

**Comment by monstergroup42** [comment]
I downgraded webkit to 2.16.1_1 and that seemed to resolve the issues.

**Comment by pullmoll** [comment]
And problem persists also with evolution-3.26.2_1.

**Comment by Piraty** [comment]
i just updated to 2.18.2 and it seems ok now

**Comment by emdete** [comment]
same here: fixed. thank  you.
