### ISSUE TITLE
linux: update to 4.13.

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#8185]
Update the default kernel to 4.13.

Please check what works:

* [x] nvidia
* [x] nvidia340
* [x] acpi_call-dkms
* [ ] batman-adv
* [ ] batman-adv14
* [ ] bbswitch
* [x] exfat-dkms
* [x] spl
* [x] sysdig
* [x] tp_smapi
* [x] virtualbox-ose-dkms
* [x] virtualbox-ose-guest-dkms
* [x] wireguard
* [x] zfs

**Comment by Sir-Boops** [comment]
nvidia* , virtualbox-ose* and exfat-dkms all work fine on kernel 4.13

**Comment by Johnnynator** [comment]
acpi_call-dkms works fine on my laptop

**Comment by chneukirchen** [comment]
Ping @Gottox, @Vaelatern, @xtraeme

**Comment by Vaelatern** [comment]
upstream zfs supports through 4.13 kernels.

**Comment by chneukirchen** [comment]
Rest is niche enough we don't need to take special care.
