### ISSUE TITLE
loop when building kde5 or sddm from source

### ISSUE THREAD

**Issue by Yann-Kaelig** [voidlinux/void-packages#8195]
=> vala-0.38.1_1: building (dependency of colord) ...
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] flex-2.6.4_2: found (/host/binpkgs)
   [host] libxslt-1.1.31_1: found (/host/binpkgs)
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [target] libglib-devel-2.54.1_1: found (/host/binpkgs)
   [target] libfl-devel-2.6.4_2: found (/host/binpkgs)
   [target] graphviz-devel-2.40.1_1: not found.
=> graphviz-2.40.1_1: building (dependency of vala) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] flex-2.6.4_2: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] libltdl-devel-2.4.6_1: found (/host/binpkgs)
   [target] libpng-devel-1.6.34_1: found (/host/binpkgs)
   [target] gd-devel-2.2.5_1: found (/host/binpkgs)
   [target] gtk+-devel-2.24.31_2: found (/host/binpkgs)
   [target] librsvg-devel-2.40.19_1: not found.
   [target] libltdl-devel-2.4.6_1: found (/host/binpkgs)
   [target] libXaw-devel-1.0.13_1: found (/host/binpkgs)
=> librsvg-2.40.19_1: the following build options are set:
   gir: Enable support for gobject introspection data (ON)
=> librsvg-2.40.19_1: building (dependency of graphviz) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] intltool-0.51.0_3: found (/host/binpkgs)
   [host] python-2.7.14_1: found (/host/binpkgs)
   [host] glib-devel-2.54.1_1: found (/host/binpkgs)
   [host] gdk-pixbuf-devel-2.36.11_1: found (/host/binpkgs)
   [host] gobject-introspection-1.54.0_1: found (/host/binpkgs)
   [target] libcroco-devel-0.6.12_1: found (/host/binpkgs)
   [target] gtk+3-devel-3.22.22_1: not found.
=> gtk+3-3.22.22_1: the following build options are set:
   broadway: Enable support for the HTML5 Broadway backend (ON)
   colord: Enable support for colord (ON)
   cups: Enable support for CUPS (ON)
   gir: Enable support for gobject introspection data (ON)
   wayland: Enable support for the Wayland backend (ON)
   x11: Enable support for X11 (ON)
=> gtk+3-3.22.22_1: building (dependency of librsvg) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] gettext-devel-0.19.8.1_3: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] glib-devel-2.54.1_1: found (/host/binpkgs)
   [host] gtk-doc-1.26_2: found (/host/binpkgs)
   [host] gobject-introspection-1.54.0_1: found (/host/binpkgs)
   [host] gtk-update-icon-cache-2.24.31_2: found (/host/binpkgs)
   [host] wayland-devel-1.13.0_1: found (/host/binpkgs)
   [host] wayland-protocols-1.10_1: found (/host/binpkgs)
   [target] libglib-devel-2.54.1_1: found (/host/binpkgs)
   [target] atk-devel-2.26.0_1: found (/host/binpkgs)
   [target] at-spi2-atk-devel-2.26.0_1: found (/host/binpkgs)
   [target] libepoxy-devel-1.4.3_1: found (/host/binpkgs)
   [target] libpng-devel-1.6.34_1: found (/host/binpkgs)
   [target] fontconfig-devel-2.12.6_1: found (/host/binpkgs)
   [target] cairo-devel-1.14.10_1: found (/host/binpkgs)
   [target] pango-devel-1.40.12_1: found (/host/binpkgs)
   [target] gdk-pixbuf-devel-2.36.11_1: found (/host/binpkgs)
   [target] colord-devel-1.3.5_1: not found.
   [target] cups-devel-2.2.4_2: found (/host/binpkgs)
   [target] libxkbcommon-devel-0.7.2_1: not found.
   [target] wayland-devel-1.13.0_1: found (/host/binpkgs)
   [target] wayland-protocols-1.10_1: found (/host/binpkgs)
   [target] libwayland-egl-17.2.2_2: found (/host/binpkgs)
   [target] MesaLib-devel-17.2.2_2: found (/host/binpkgs)
   [target] libXcursor-devel-1.1.14_4: found (/host/binpkgs)
   [target] libXdamage-devel-1.1.4_4: found (/host/binpkgs)
   [target] libXext-devel-1.3.3_2: found (/host/binpkgs)
   [target] libXinerama-devel-1.1.3_2: found (/host/binpkgs)
   [target] libXi-devel-1.7.9_1: found (/host/binpkgs)
   [target] libXrandr-devel-1.5.1_1: found (/host/binpkgs)
   [target] libXcomposite-devel-0.4.4_3: found (/host/binpkgs)
   [runtime] gtk-update-icon-cache>=0: found gtk-update-icon-cache-2.24.31_2 (/host/binpkgs)
   [runtime] shared-mime-info>=0: found shared-mime-info-1.9_1 (/host/binpkgs)
   [runtime] dbus-x11>=0: found dbus-x11-1.10.24_1 (/host/binpkgs)
=> colord-1.3.5_1: the following build options are set:
   gir: Enable support for gobject introspection data (ON)
=> colord-1.3.5_1: building (dependency of gtk+3) ...
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] intltool-0.51.0_3: found (/host/binpkgs)
   [host] docbook2x-0.8.8_4: found (/host/binpkgs)
   [host] gobject-introspection-1.54.0_1: found (/host/binpkgs)
   [target] vala-devel-0.38.1_1: not found.
   [target] libgudev-devel-232_1: found (/host/binpkgs)
   [target] polkit-devel-0.113_2: not found.
   [target] lcms2-devel-2.8_2: found (/host/binpkgs)
   [target] dbus-devel-1.10.24_1: found (/host/binpkgs)
   [target] libusb-devel-1.0.21_1: found (/host/binpkgs)
   [target] libgusb-devel-0.2.11_1: not found.
   [target] sqlite-devel-3.20.1_1: found (/host/binpkgs)
   [target] sane-devel-1.0.27_1: not found.
   [target] eudev-libudev-devel-3.2.4_1: found (/host/binpkgs)
   [target] bash-completion-2.7_1: not found.
=> vala-0.38.1_1: building (dependency of colord) ...
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] flex-2.6.4_2: found (/host/binpkgs)
   [host] libxslt-1.1.31_1: found (/host/binpkgs)
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [target] libglib-devel-2.54.1_1: found (/host/binpkgs)
   [target] libfl-devel-2.6.4_2: found (/host/binpkgs)
   [target] graphviz-devel-2.40.1_1: not found.
=> graphviz-2.40.1_1: building (dependency of vala) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] flex-2.6.4_2: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] libltdl-devel-2.4.6_1: found (/host/binpkgs)
   [target] libpng-devel-1.6.34_1: found (/host/binpkgs)
   [target] gd-devel-2.2.5_1: found (/host/binpkgs)
   [target] gtk+-devel-2.24.31_2: found (/host/binpkgs)
   [target] librsvg-devel-2.40.19_1: not found.
   [target] libltdl-devel-2.4.6_1: found (/host/binpkgs)
   [target] libXaw-devel-1.0.13_1: found (/host/binpkgs)
=> librsvg-2.40.19_1: the following build options are set:
   gir: Enable support for gobject introspection data (ON)
=> librsvg-2.40.19_1: building (dependency of graphviz) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] intltool-0.51.0_3: found (/host/binpkgs)
   [host] python-2.7.14_1: found (/host/binpkgs)
   [host] glib-devel-2.54.1_1: found (/host/binpkgs)
   [host] gdk-pixbuf-devel-2.36.11_1: found (/host/binpkgs)
   [host] gobject-introspection-1.54.0_1: found (/host/binpkgs)
   [target] libcroco-devel-0.6.12_1: found (/host/binpkgs)
   [target] gtk+3-devel-3.22.22_1: not found.
=> gtk+3-3.22.22_1: the following build options are set:
   broadway: Enable support for the HTML5 Broadway backend (ON)
   colord: Enable support for colord (ON)
   cups: Enable support for CUPS (ON)
   gir: Enable support for gobject introspection data (ON)
   wayland: Enable support for the Wayland backend (ON)
   x11: Enable support for X11 (ON)
=> gtk+3-3.22.22_1: building (dependency of librsvg) ...
   [host] automake-1.15.1_1: found (/host/binpkgs)
   [host] gettext-devel-0.19.8.1_3: found (/host/binpkgs)
   [host] libtool-2.4.6_1: found (/host/binpkgs)
   [host] pkg-config-0.29.2_1: found (/host/binpkgs)
   [host] glib-devel-2.54.1_1: found (/host/binpkgs)
   [host] gtk-doc-1.26_2: found (/host/binpkgs)
   [host] gobject-introspection-1.54.0_1: found (/host/binpkgs)
   [host] gtk-update-icon-cache-2.24.31_2: found (/host/binpkgs)
   [host] wayland-devel-1.13.0_1: found (/host/binpkgs)
   [host] wayland-protocols-1.10_1: found (/host/binpkgs)
   [target] libglib-devel-2.54.1_1: found (/host/binpkgs)
   [target] atk-devel-2.26.0_1: found (/host/binpkgs)
   [target] at-spi2-atk-devel-2.26.0_1: found (/host/binpkgs)
   [target] libepoxy-devel-1.4.3_1: found (/host/binpkgs)
   [target] libpng-devel-1.6.34_1: found (/host/binpkgs)
   [target] fontconfig-devel-2.12.6_1: found (/host/binpkgs)
   [target] cairo-devel-1.14.10_1: found (/host/binpkgs)
   [target] pango-devel-1.40.12_1: found (/host/binpkgs)
   [target] gdk-pixbuf-devel-2.36.11_1: found (/host/binpkgs)
   [target] colord-devel-1.3.5_1: not found.
   [target] cups-devel-2.2.4_2: found (/host/binpkgs)
   [target] libxkbcommon-devel-0.7.2_1: not found.
   [target] wayland-devel-1.13.0_1: found (/host/binpkgs)
   [target] wayland-protocols-1.10_1: found (/host/binpkgs)
   [target] libwayland-egl-17.2.2_2: found (/host/binpkgs)
   [target] MesaLib-devel-17.2.2_2: found (/host/binpkgs)
   [target] libXcursor-devel-1.1.14_4: found (/host/binpkgs)
   [target] libXdamage-devel-1.1.4_4: found (/host/binpkgs)
   [target] libXext-devel-1.3.3_2: found (/host/binpkgs)
   [target] libXinerama-devel-1.1.3_2: found (/host/binpkgs)
   [target] libXi-devel-1.7.9_1: found (/host/binpkgs)
   [target] libXrandr-devel-1.5.1_1: found (/host/binpkgs)
   [target] libXcomposite-devel-0.4.4_3: found (/host/binpkgs)
   [runtime] gtk-update-icon-cache>=0: found gtk-update-icon-cache-2.24.31_2 (/host/binpkgs)
   [runtime] shared-mime-info>=0: found shared-mime-info-1.9_1 (/host/binpkgs)
   [runtime] dbus-x11>=0: found dbus-x11-1.10.24_1 (/host/binpkgs)
=> colord-1.3.5_1: the following build options are set:
   gir: Enable support for gobject introspection data (ON)

**Comment by Yann-Kaelig** [comment]
Fix found here: http://www.linuxfromscratch.org/blfs/view/svn/general/vala.html
------------------
Fix the issue, vala build

**Comment by the-maldridge** [comment]
If your issue is fixed, please close this thread.

**Comment by mexicarne** [comment]
> ## Fix found here: http://www.linuxfromscratch.org/blfs/view/svn/general/vala.html

How do you fixed the loop? The link just contains the general information about vala package. Did you fix it by updating vala to particular version? Thank you!
