### ISSUE TITLE
apache-2.4.10_4: fails to start with default configuration

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#820]
[root@SkyLittleSystem /]# httpd
AH00526: Syntax error on line 31 of /etc/httpd/extra/httpd-multilang-errordoc.conf:
Invalid command 'LanguagePriority', perhaps misspelled or defined by a module not included in the server configuration

**Comment by ayghor** [comment]
I searched a bit, but couldn't find a reason for this. I'm commenting out teh affected files

**Comment by xtraeme** [comment]
Applied your pullreq, should be ok? feel free to close this if the issue has been fixed. thanks.
