### ISSUE TITLE
package request:astroid email client

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#8229]
project github https://github.com/astroidmail/astroid

this is a email client more new user friendly that mutt/neomutt

**Comment by ebfe** [comment]
#4751

**Comment by icf20** [comment]
@ebfe this is confusing then ...
![image](https://user-images.githubusercontent.com/17784575/31651448-fa6481a8-b31b-11e7-8c7c-3a0d04aa45c6.png)

**Comment by ebfe** [comment]
It's not merged yet.

**Comment by icf20** [comment]
the search dont look at the whole repo ?

**Comment by ebfe** [comment]
It does. The PR isn't merged yet, so it isn't in the repo.

**Comment by Anachron** [comment]
I want to try Astroid and may pick up the PR and fix the issues mentioned in it if Astroid is worth the switch.

**Comment by icf20** [comment]
@Anachron well it look like a decent alternative to evolution/thunderbird when the mail holder get over few GB, the other alternative is mutt while mutt and mutt is mutt

**Comment by NoctuaNivalis** [comment]
I took a look at the mentioned PR, and I'm not sure it'll work. `android` depends on the notmuch python bindings, IIRC, and those aren't included in the `notmuch` package. You'd have to add them to that (or a new) package first.

**Comment by NoctuaNivalis** [comment]
I'm adding notmuch python bindings in #8514. I'll have a look at packaging alot and astroid when it's merged.
