### ISSUE TITLE
php-apache-5.6.4_2: php is not threadsafe

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#823]
[root@SkyLittleSystem php]# httpd
[Tue Jan 06 05:36:39.401602 2015] [:crit] [pid 23663:tid 140145795434368] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
AH00013: Pre-configuration failed

**Comment by ayghor** [comment]
I hate apache and php sooo much

**Comment by xtraeme** [comment]
https://wiki.archlinux.org/index.php/Apache_HTTP_Server#Apache_is_running_a_threaded_MPM.2C_but_your_PHP_Module_is_not_compiled_to_be_threadsafe.

**Comment by ayghor** [comment]
well yes, but we don't have any of those modules installed:

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule mpm_prefork_module modules/mod_mpm_prefork.so

and I couldn't find them in separate packages as well.

**Comment by xtraeme** [comment]
Fixed in aefdea87e5cbfa999a130d4dc732d016cdb931be

Thanks.

**Comment by ayghor** [comment]
just a suggestion:

this line
LoadModule mpm_prefork_module /usr/libexec/httpd/mod_mpm_prefork.so

doesn't come commented on httpd.conf, like for teh other modules that come with apache. This may cause confusion.
