### ISSUE TITLE
missing conflict for packages

### ISSUE THREAD

**Issue by emdete** [voidlinux/void-packages#8241]
* [x] mozjs52 should conflict with mozjs38
* [x] liborcus ... liborcus11
* [x] libixion ... libixion11
* [x] libreoffice ... libreoffice-i18n-de

otherwise they overwrite files.

**Comment by Gottox** [comment]
mozjs* is fixed.

**Comment by pullmoll** [comment]
liborcus11 and libixion11 are gone
libreoffice-i18n-de does not exist

**Comment by pullmoll** [comment]
Solved.

**Comment by emdete** [comment]
thank you! :D
