### ISSUE TITLE
MISSING: desktop-file-utils>=0

### ISSUE THREAD

**Issue by Yann-Kaelig** [voidlinux/void-packages#8273]
Start from a fresh git clone void-packages, I get this issue for kde5 build

ERROR: extra-cmake-modules-5.37.0_1: failed to install 'qt5-tools-5.8.0_9' dependency! (error 19)
MISSING: desktop-file-utils>=0
[DEBUG.txt](https://github.com/voidlinux/void-packages/files/1393878/DEBUG.txt)

**Comment by Yann-Kaelig** [comment]
In my opinion desktop-file-utils should be a part of kde5 meta package.

**Comment by Yann-Kaelig** [comment]
I don't understand how these subpackage are managed and why desktop-file-utils is not built

**Comment by pullmoll** [comment]
The subpackage qt5-tools defines a dependency on desktop-file-utils, but subpackage's dependencies are not resolved prior to building a project.

This is actually a bug or missing feature of xbps-src. Only hostmakedepends, makedepends and depends of the main template are evaluated and built, if missing, before building a package.

The workaround here would be to add desktop-file-utils and hicolor-icon-theme to the qt5/template depends= line.
