### ISSUE TITLE
package request: kodi-c2

### ISSUE THREAD

**Issue by 7185** [voidlinux/void-packages#8288]
Kodi for the Odroid-C2

Arch Linux ARM [has it](https://github.com/archlinuxarm/PKGBUILDs/blob/master/alarm/kodi-c2/PKGBUILD) but they're using [Owersun's fork](https://github.com/Owersun/xbmc) which has some interesting optimizations.

I might try to package it myself when I get some free time, but I also wanted to know about the community thoughts about it (should we have it? should we use the fork with no release?). Maybe someone has already tried to build it too.

**Comment by Yann-Kaelig** [comment]
Hi,

It's just my personal opinion, but Odroid-C2 is officialy supported by LibreElec. It's certainly a better choice than Voidlinux.
The only one reason I would go with Voidlinux for Kodi is for example an not supported board from LibreElec, for example the Cubieboards.

**Comment by 7185** [comment]
Demat dit, @Yann-Kaelig!

I understand what you mean and I agree with what you said, but I chose to use Void because I'm used to it and I want a little more than just a Kodi box.
Actually I'm currently using `kodi-rpi` on my Raspberry Pi v1, which is also supported by LibreElec.
