### ISSUE TITLE
exiv2 fatal error: exv_conf.h: No such file or directory

### ISSUE THREAD

**Issue by Yann-Kaelig** [voidlinux/void-packages#8299]
## System Information:
* Architecture: amd64 (x86_64)
* Kernel: Linux 4.12.13_1
* Locale: LANG=en_US.UTF-8 LC_CTYPE="en_US.UTF-8"
## Package
* Name: exiv2
* Version: 0.26
* Revision: 1
## Bug or Feature ?
> Bug
### Description
> Exiv2 build failed with the output: "exiv2 fatal error: exv_conf.h: No such file or directory"
### How to reproduce the bug ?
> Build with parallel jobs >=2
### How to fix the issue ?
> Disable parallel build with the option "disable_parallel_build=yes"
## Srcpkg version/revision with the fix:
* Version:
* Revision:

**Comment by lorhm** [comment]
Did you manage to overcome the issue?
