### ISSUE TITLE
itstool segfaults when building gtk-doc

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#8365]
```
Making all in manual
make[2]: Entering directory '/builddir/gtk-doc-1.26/help/manual'
  GEN    fr/
  GEN    pt_BR/
  GEN    zh_CN/
/bin/sh: line 4:   662 Segmentation fault      itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/fdl-appendix.xml
make[2]: *** [Makefile:523: zh_CN/zh_CN.stamp] Error 139
make[2]: *** Waiting for unfinished jobs....
/bin/sh: line 4:   658 Segmentation fault      itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/fdl-appendix.xml
make[2]: *** [Makefile:523: fr/fr.stamp] Error 139
/bin/sh: line 4:   660 Segmentation fault      itstool -m "${mo}" ${d}/C/index.docbook ${d}/C/fdl-appendix.xml
make[2]: *** [Makefile:523: pt_BR/pt_BR.stamp] Error 139
make[2]: Leaving directory '/builddir/gtk-doc-1.26/help/manual'
make[1]: *** [Makefile:370: all-recursive] Error 1
make[1]: Leaving directory '/builddir/gtk-doc-1.26/help'
make: *** [Makefile:733: all-recursive] Error 1
=> ERROR: gtk-doc-1.26_2: failed to run do_build() at line 13.
```

It looks like it crashes in `libxml2-python'`s shared object `libxml2mod.so`:

```
[jbu@/tmp/glibc-1 /builddir/gtk-doc-1.26/help/manual/fr]$ gdb python
GNU gdb (GDB) 8.0.1
…
Reading symbols from python...(no debugging symbols found)...done.
(gdb) set args /usr/bin/itstool -m fr.mo ../C/index.docbook ../C/fdl-appendix.xml
(gdb) run
Starting program: /usr/bin/python /usr/bin/itstool -m fr.mo ../C/index.docbook ../C/fdl-appendix.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff590f953 in ?? () from /usr/lib/python2.7/site-packages/libxml2mod.so
(gdb) 
```

This has probably to do with me adding the icu-devel dependency to libxml2.
But rather than reverting this change I'd like to find the cause for the crash.

If anyone has an idea you're welcome.

I'll try to find out what goes wrong using debug symbols now.

Crash happens at the `switch (cur->type) {`:
```
libxml_type (self=<optimized out>, args=<optimized out>) at libxml.c:2758

   2739 static PyObject *
   2740 libxml_type(ATTRIBUTE_UNUSED PyObject * self, PyObject * args)
   2741 {
   2742     PyObject *resultobj, *obj;
   2743     xmlNodePtr cur;
   2744     const xmlChar *res = NULL;
   2745
   2746     if (!PyArg_ParseTuple(args, (char *) "O:last", &obj))
   2747         return NULL;
   2748     cur = PyxmlNode_Get(obj);
   2749     if (cur == NULL) {
   2750         Py_INCREF(Py_None);
   2751         return (Py_None);
   2752     }
   2753
   2754 #ifdef DEBUG
   2755     printf("libxml_type: cur = %p\n", cur);
   2756 #endif
   2757
   2758     switch (cur->type) {
   2759         case XML_ELEMENT_NODE:
   2760             res = (const xmlChar *) "element";
   2761             break;
```

**Comment by pullmoll** [comment]
It looks like it is a regression in itstool-2.0.4.
Reverting the libxml2 addition of icu-devel makes no difference.
Reverting itstool to 2.0.3 solves the segfaults.

**Comment by maxice8** [comment]
also segfaults when building `rhythmbox`

```
/bin/sh: line 4:  8154 Segmentation fault      itstool -m "${mo}" ${d}/C/fdl-appendix.xml ${d}/C/index.docbook ${d}/C/legal.xml
```

**Comment by Yann-Kaelig** [comment]
In my side, sometimes gtk-docs compilation fails with a segfault and sometimes gtk-doc compilation fails like that:

gtk-doc was configured with the following options:
==================================================
configure:    PDF support disabled, no dblatex or fop available
configure:    Syntax highlighting of examples disabled
configure:    Skipping regression tests
configure:    Debug tracing disabled
configure: ** Documentation enabled
=> gtk-doc-1.26_2: running pre-build hook: 02-script-wrapper ...
=> gtk-doc-1.26_2: running do_build ...
Making all in cmake
make[1]: Entering directory '/builddir/gtk-doc-1.26/cmake'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/builddir/gtk-doc-1.26/cmake'
Making all in help
make[1]: Entering directory '/builddir/gtk-doc-1.26/help'
Making all in manual
make[2]: Entering directory '/builddir/gtk-doc-1.26/help/manual'
  GEN      bn_IN/bn_IN.mo
  GEN      cs/cs.mo
  GEN      de/de.mo
  GEN      el/el.mo
  GEN      en_GB/en_GB.mo
  GEN      es/es.mo
  GEN      fr/fr.mo
  GEN      gl/gl.mo
  GEN      gu/gu.mo
  GEN      pt_BR/pt_BR.mo
  GEN      sl/sl.mo
  GEN      sv/sv.mo
  GEN      ta/ta.mo
  GEN      te/te.mo
  GEN      zh_CN/zh_CN.mo
  GEN    bn_IN/
  GEN    cs/
Error: Could not merge translations:
'NoneType' object has no attribute '__getitem__'
make[2]: *** [Makefile:523: cs/cs.stamp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/builddir/gtk-doc-1.26/help/manual'
make[1]: *** [Makefile:370: all-recursive] Error 1
make[1]: Leaving directory '/builddir/gtk-doc-1.26/help'
make: *** [Makefile:733: all-recursive] Error 1
=> ERROR: gtk-doc-1.26_2: failed to run do_build() at line 13.

**Comment by Gottox** [comment]
solved by 900ec33563ddc6b6e4426813d3f3c0d52442138e

**Comment by maxice8** [comment]
upstream released a commit https://github.com/itstool/itstool/commit/9b84c007a73e8275ca45762f1bfa3ab7c3a852e2 that is believed to fix this problem, i am rebuilding all packages know to cause problems locally to test.

Please send candidates.

**Comment by pullmoll** [comment]
I tested it locally and can confirm it fixes gtk-doc built for x86_64, i686 and x86_64-musl.
Currently trying the other candidates for various target arches.

**Comment by maxice8** [comment]
gnome-user-docs works but it requires https://github.com/GNOME/gnome-user-docs/commit/97cfd5c2e4daf7eb0bcf4c9503a385f8e082d16c to fix dutch translation tags.

If itstool is bumped again this commit needs to be included as a patch ( only applies to gnome-user-docs-3.26.1.1 )

**Comment by pullmoll** [comment]
Even with the patch for `nl.po` I see an error when building gnome-user-docs for `x86_64-musl`:
```
Error: Could not merge translations:
'NoneType' object has no attribute '__getitem__'
make[1]: *** [Makefile:851: pl/pl.stamp] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/builddir/gnome-user-docs-3.26.1.1/gnome-help'
make: *** [Makefile:325: all-recursive] Error 1
=> ERROR: gnome-user-docs-3.26.1.1_1: failed to run do_build() at line 13.
```
