### ISSUE TITLE
Differences between 'configure' / 'gnu-configure' ?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8389]
About the `build_style` : what are the differences between `configure` / `gnu-configure` ❓  
````
$ diff -y --suppress-common-lines common/build-style/configure.sh common/build-style/gnu-configure.sh
# This helper is for templates using configure scripts (not g |	# This helper is for templates using GNU configure scripts.
# by the GNU autotools).
````
It's not clear to me. 😕

**Comment by Vaelatern** [comment]
`configure` is scripts that work like `configure` scripts but do not come from the GNU project, and may have totally non-standardized options.
