### ISSUE TITLE
Package Request: tunesviewer

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#8451]
project webpage http://tunesviewer.sourceforge.net/

this is a project that allow linux users access content from ITunes-Universirty while the RSS subscriptions can be handled by gpodder

**Comment by cr6git** [comment]
⚠️ At the moment, in [files](https://sourceforge.net/projects/tunesviewer/files/) there is only BETA version.

**Comment by icf20** [comment]
@cr6git look like the "correct" version for example ubuntu has 1.4.99 https://packages.ubuntu.com/zesty/tunesviewer

**Comment by cr6git** [comment]
@icf20 As you can see in my PR, there was a problem with the license. It should be `GPL-2` but @Vaelatern  did not agree.
