### ISSUE TITLE
Add GrSec/PaX kernels

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#846]

**Comment by XVilka** [comment]
And paxtool + gradm for managing them.

**Comment by nmeum** [comment]
:+1:

**Comment by thypon** [comment]
Interested.

**Comment by 0xcaca0** [comment]
https://gist.github.com/0xcaca0/fa7ecc80b912285ea009
I threw this together, it's pretty terrible and needs some (read: a lot of) review.
It should also really be packaged with paxctld or similar to apply proper PAX exceptions to binaries.
Mostly merged from the older linux3.2-grsec template and the current linux3.14
It's been sitting on my drive for over a month now so I thought I'd throw it out there.

**Comment by jannisch** [comment]
@ghost this gist seems to be gone, can you upload it again?

**Comment by t0b1nux** [comment]
As the grsecurity project no longer provide the grsec patch, this issue should be closed.

**Comment by XVilka** [comment]
Best way ever, to solve the issues.

**Comment by t0b1nux** [comment]
Well, unless you can provide voidlinux a paid subscription ? 
TBH, I'm not even sure it would be in the defaults kernels, so its usage would remains some niche users, sadly.
