### ISSUE TITLE
Out of date - FreeRDP

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#8460]
Hi everyone,

A kind request to update FreeRDP please.
As a some major security updates have been released lately (https://github.com/FreeRDP/FreeRDP/releases).
Current version is: `freerdp-1.0.2_14`.

Thanks in advance!

**Comment by Johnnynator** [comment]
These are all pre-release versions, 1.0.2 is still the latest release

**Comment by direwolfie** [comment]
You are absolutely right.
Missed that...
Thank you!
