### ISSUE TITLE
Request: Runit service for laptop-mode

### ISSUE THREAD

**Issue by mid-kid** [voidlinux/void-packages#848]
Just noticed they're missing.

**Comment by mid-kid** [comment]
Trying to make one for tlp myself, I see there isn't any one-time service management in runit, and that there only are one-time scripts at boot-time in /etc/runit/core-services, but not for shutdown.
If there's some way to do this in a way the user can enable/disable the service, I've been unable to find any documentation.

**Comment by teh-jazzman** [comment]
Runlevel 2 already executes /etc/rc.local, I suggest to call all boot-time scripts from there.
Another script could be created (maybe /etc/rc.shutdown or simmilar) and called from runlevel 3.
Would this be viable or am I missing something?

**Comment by xtraeme** [comment]
This makes sense, feel free to submit a pullup.

**Comment by xtraeme** [comment]
@mid-kid you need a runit service that runs "tlp start" and  execs pause(1) (see alsa runit service) and a finish script that exec "tlp stop" or similar.

**Comment by teh-jazzman** [comment]
One-time scripts at system shutdown can now be called from /etc/rc.shutdown

**Comment by mid-kid** [comment]
There's a runit service for tlp now (see #877), changed title.
