### ISSUE TITLE
tilda: broken requires vte290

### ISSUE THREAD

**Issue by logenkain** [voidlinux/void-packages#850]
It would seem that vte updated to 2.91.  I'm not sure if I will need to package 2.90 or not to keep it working.  If anyone has a simple fix let me know.  I'm going to go ask the tilda guys if there is a way to compile it agains 1.91.  Looks like sakura is broken too, I'll open up another issue for that.

**Comment by xtraeme** [comment]
This commit 9c949c5457ce9aa9324be5a3283bf61eaa609e01 made by @Gottox updated vte3 to 0.38.x and didn't rebuild the pkgs that were linked against libvte2_90.so.9.

The affected pkgs should be rebuilt against new vte3 or create a vte290 pkg... anyway assiging it to the guilty developer :-)

**Comment by xtraeme** [comment]
Closing this, will be coordinated in #851 instead, thanks.
