### ISSUE TITLE
lxc-2.1.1_1.x86_64 & liblxc-2.1.1_1.x86_64 hang and not working for unprivileged containers after upgrade

### ISSUE THREAD

**Issue by mdkuser** [voidlinux/void-packages#8521]
### System

* uname -r 
 4.13.9_1
* xuname:  
  Void 4.13.9_1 x86_64 AuthenticAMD/KVM notuptodate hold rD
* architecture:  
  x64_64
* libc:  
  glibc
* package:  
  lxc-2.1.1_1.x86_64
  liblxc-2.1.1_1.x86_64

### Expected behavior
lxc commands should work and container started

### Actual behavior
container cannot be started and lxc commands like lxc-ls, lxc-start hang

### Steps to reproduce the behavior

- upgrade lxc and liblxc to version 2.1.1_1.x86_64
- reboot the system
- try to start an unprivileged container with lxc-start -n container 

Downgrading lxc and liblxc to version lxc-2.0.8_1 fixes the issue.

**Comment by maxice8** [comment]
Can't seem to reproduce here, my Alpine container works normally.

**Comment by mdkuser** [comment]
are you running lxc inside KVM virtual machine or native?

**Comment by maxice8** [comment]
Native

**Comment by mdkuser** [comment]
I tested the same on a different virtual machine running latest a Void x86_64 (glibc) where I just run an xbps-install -Suy a few minutes before.
Same problem, lxc and xuname both hang after upgrade.

I can reporduce it on two different kvm guests running on different hosts!

**Comment by mdkuser** [comment]
I have to mention that my conatiners are unprivileged containers.
Someone hat tried with unprivileged containers and can reproduce the issue?

**Comment by mdkuser** [comment]
I was able to start an privileged container using lxc-2.1.1 on my test vms.
However unprivileged containers won't start anymore with 2.1.1.

**Comment by mdkuser** [comment]
I solved it!
The problem is, that with lxc-2.1.1, it seems cgmanager is no longer needed.
And if cgmanager is running, while lxc-2.1.1 is installed, unprivileged containers don't start apparently.
So what I did to fix it was:

1.) removing cgmanager
2.) commenting the following line in /etc/sv/lxc-autostart
'sv check cgmanager >/dev/null || exit 1'

**Comment by mdkuser** [comment]
solved

**Comment by Vaelatern** [comment]
Pushed change to lxc package.
