### ISSUE TITLE
NetworkManager: failed to start the dbus service

### ISSUE THREAD

**Issue by silvernode** [voidlinux/void-packages#853]
Steps to reproduce:
1. Install fresh copy of Void Linux (Xfce edition)
2. Connect to WPA2 personal (tkip/aes) encrypted SSID
3. Be happy that you can ping
4. sudo xbps-install -Su
5. Reboot
6. Be sad that you can't ping
7. Connect to an open SSID and be happy
8. Wonder why NetworkManager can't connect to dbus

Debug:
http://pastebin.com/Rseda3Eb

**Comment by xtraeme** [comment]
Paste the output of `sv status dbus`.

**Comment by silvernode** [comment]
[mollusk@drunkdev ~]$ sudo sv status dbus
Password: 
run: dbus: (pid 521) 2432s
[mollusk@drunkdev ~]$

**Comment by xtraeme** [comment]
ok, try `ls -l /var/service/`

**Comment by silvernode** [comment]
http://pastebin.com/pFVjvN5K

**Comment by silvernode** [comment]
So I figured I would try adding myself to the networkmanager group....yeah that didn't help either. wicd doesn't want to connect to the ssid either. For now I am connected to an open wireless network nearby that comcast provides for paying customers.

**Comment by xtraeme** [comment]
Can you still reproduce it? I'm unable to reproduce it on any of my machines.

**Comment by silvernode** [comment]
I apologize for not closing this earlier, a few days ago there was an update to network manager and everything has been working fine since. I'll go ahead and close this, thanks for your effort.
