### ISSUE TITLE
Package request: otpw

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#854]
Can you please add the otpw from: https://www.cl.cam.ac.uk/~mgk25/download/

OTPW – A one-time password login package with optional PAM integration.

See doc from: http://www.cl.cam.ac.uk/~mgk25/otpw.html

**Comment by Duncaen** [comment]
I added the package with https://github.com/voidlinux/void-packages/commit/28df05277dcc21ff34e4a4c0ed11a07fda51dced

**Comment by xtraeme** [comment]
Packaged by @Duncaen
