### ISSUE TITLE
Albert update

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8598]
The package `albert` in Void repos is old (version 0.12.0). 
I'm trying to update to the latest version [0.14.4](https://github.com/albertlauncher/albert/releases/tag/v0.14.4) but I get these errors during the build: 
````
warning: libglobalshortcut.so, needed by ../../lib/libalbertcore.so, not found (try using -rpath or -rpath-link)
warning: libxdg.so, needed by ../../lib/libalbertcore.so, not found (try using -rpath or -rpath-link)
````
In which packages are located these libraries ? 
I cant' find them.

**Comment by Johnnynator** [comment]
They are normally provided by albert itself, at least it is like that in version 0.12.0

**Comment by cr6git** [comment]
Yes, you are right! 
I forgot to mention that this problem occurs **only** when cross compiling.

**Comment by Johnnynator** [comment]
I just checked v0.12.0 and I get the same issue when I try to cross compile it

**Comment by cr6git** [comment]
I stopped working on it, I can't find the solution.

**Comment by cr6git** [comment]
it's done.
