### ISSUE TITLE
Project since: dead ?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8626]
I just checked the [template](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/since/template) : the homepage is unreachable and I can't download the tarball (Connection refused). 
It looks like the project is dead.

**Comment by cr6git** [comment]
Updated.

**Comment by Sir-Boops** [comment]
If not many people are using "since" it might be a better idea to just drop it.

**Comment by Anachron** [comment]
It has a noreply email too which is invalid.
