### ISSUE TITLE
Package Request: Filebot

### ISSUE THREAD

**Issue by anarchomoh** [voidlinux/void-packages#8641]
Hi
Could I please request that Filebot be added to the Void repository?

Website: https://sourceforge.net/projects/filebot/

Source Code: https://sourceforge.net/projects/filebot/files/latest/download

**Comment by cr6git** [comment]
The [User Reviews](https://sourceforge.net/projects/filebot/reviews/?sort=created_date&stars=0#reviews-n-ratings) does not look very promising...

**Comment by anarchomoh** [comment]
Hi @cr6git.  I believe the nagware is only in the windows client ;).  Have never seen it on Manjaro (which I used to use before).

**Comment by cr6git** [comment]
Thanks for the info! I will give it a try.

**Comment by cr6git** [comment]
No, on second thought, it doesn't make me want to try... I'm sorry.
