### ISSUE TITLE
Package Request: Kaffeine

### ISSUE THREAD

**Issue by anarchomoh** [voidlinux/void-packages#8642]
Hi 

Could you please package Kaffeine for Void?

Website: https://www.kde.org/applications/multimedia/kaffeine/

https://github.com/KDE/kaffeine

**Comment by cr6git** [comment]
There aren't any [releases](https://github.com/Me-TV/Me-TV/releases) ?

**Comment by anarchomoh** [comment]
@cr6git, Hi - you're right. I got confused with the older Me-Tv which is on Launchpad and is no longer being developed.  I have found a better option to watch TV and have updated the package request accordingly.

**Comment by cr6git** [comment]
Done.

**Comment by anarchomoh** [comment]
Thanks Heaps!!!

**Comment by cr6git** [comment]
You can close.
