### ISSUE TITLE
qt5: 5.4 released upstream

### ISSUE THREAD

**Issue by The-Compiler** [voidlinux/void-packages#870]
I noticed [qt5](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/qt5/template) is still on 5.3.2 while 5.4 [has  been released upstream](http://blog.qt.digia.com/blog/2014/12/10/qt-5-4-released/).

Since it's quite a big update (with new modules, etc.) and I'm unaware of the implications, I'd prefer if someone else took care of this :)

**Comment by xtraeme** [comment]
Is that a pollite way of saying that qt5 should be updated to 5.4? :-)

I'm aware that 5.4 was released a while ago... but I also need time and help :-)

**Comment by The-Compiler** [comment]
Yeah, it is indeed :)

I know the feeling, I'm also way too busy with [my own project](https://github.com/The-Compiler/qutebrowser) at the moment to look at this. And I'm not even a Void user (yet?), just noticed a crash report by a user with an older Qt version. Thanks for your work!

**Comment by The-Compiler** [comment]
Awesome, thank you! :smile:
