### ISSUE TITLE
Where is lollypop ?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8702]
### System

* xuname:  Void 4.13.10_1 x86_64 GenuineIntel uptodate rFFFFF

* architecture:  x64_64
* libc:  glibc
* package:  lollypop-0.9.304

### Expected behavior
Xbps should be able to find and download [lollypop-0.9.304](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/lollypop/template). 

### Actual behavior
````
$ sudo xbps-install -S lollypop
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
Unable to locate 'lollypop' in repository pool.
$ sudo xbps-query -Rs lollypop
(nothing)
````
Weird.

### Steps to reproduce the behavior
Try to search and install lollypop.

**Comment by cr6git** [comment]
The package does not exist on the server: 
````
$ wget --spider https://repo.voidlinux.eu/current/lollypop-0.9.304_1.x86_64.xbps
Mode « spider » activé. Vérification de l’existence d’un fichier distant.
--2017-10-30 11:01:54--  https://repo.voidlinux.eu/current/lollypop-0.9.304_1.x86_64.xbps
Résolution de repo.voidlinux.eu… 148.251.199.112, 2a01:4f8:212:34cc::1d:b
Connexion à repo.voidlinux.eu|148.251.199.112|:443… connecté.
requête HTTP transmise, en attente de la réponse… 404 Not Found
Le fichier distant n’existe pas — lien mort.
````
lien mort = broken link.

**Comment by ebfe** [comment]
c3140091cc303c394175b5e87e4e910e38dbdd0f
