### ISSUE TITLE
Package request: Discord

### ISSUE THREAD

**Issue by Txemadh** [voidlinux/void-packages#8769]
Could you please add the Discord program to this wonderful distribution?
Thank you very much for assisting me

[https://discordapp.com](Program Url)
https://discordapp.com/download
 
I use the distribution Void Linux x86_64 bit.

Best regards ,
Sincerely,
Txema

**Comment by Sir-Boops** [comment]
https://github.com/voidlinux/void-packages/blob/master/srcpkgs/discord/template

See https://github.com/voidlinux/void-packages#building-packages for some help building it

**Comment by Txemadh** [comment]
Thanks so much for the help.
Best regards,
Sincerely,
Txema
