### ISSUE TITLE
Is there a way to stop xbps from removing /opt ?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8772]
By default, `xbps` removes empty dirs. 
If a package is installed in `/opt/${pkgname}` , and you want to remove it: then `xbps` will remove `/opt` if empty! :confused: 
`xbps` should make an allowance for an empty `/opt` , in my opinion.

**Comment by chneukirchen** [comment]
`touch /opt/.keep`

**Comment by cr6git** [comment]
really? so it's really quite simple! :)
