### ISSUE TITLE
Lollypop, text moves and becomes messed up.

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#8775]
### System

* xuname:  Void 4.13.9_1 x86_64-musl GenuineIntel uptodate rF
* architecture:  x86_64
* libc: musl
* package:  lollypop

### Expected behavior
The text that the mouse is hovering above should become bold or highlighted.
### Actual behavior
The text moves and becomes a mess.
### Steps to reproduce the behavior
https://ufile.io/ojm5v (lollypop_misplaced_text_vp9.mkv, 466.4 KB)

**Comment by cr6git** [comment]
Weird. 
Looks like an ugly GTK theme. 
Try with Adwaita theme.

**Comment by cr6git** [comment]
What's new @38github ?

**Comment by 38github** [comment]
cr6git: I am not on my Void installation but I will try it out later tonight when I have more time. Regards.

**Comment by 38github** [comment]
I haven't had time to try it on my laptop but using the same system (on USB) on another computer with a 1920x1200 display there is nothing wrong happening.

**Comment by cr6git** [comment]
Good to know. If `lollypop` is not the culprit I guess you can close the issue.
