### ISSUE TITLE
Youtube-dl fish-shell autocompletion

### ISSUE THREAD

**Issue by edgardiniz** [voidlinux/void-packages#8815]
### System

* xuname: Void 4.4.95_1 x86_64 GenuineIntel uptodate rFFFFFF
* architecture: x64_64
* libc: glibc
* package: youtube-dl-2017.10.29_1

### Expected behavior
Fish shell should suggest autocompletion with \<TAB\>
### Actual behavior
Fish shell autocompletion does not work with youtube-dl
### Steps to reproduce the behavior
Write `youtube-dl --down` (or any other option) in a fish shell and press \<TAB\>

The package template installs the completions to `/usr/share/fish/completions/youtube-dl`, but the file name should be `youtube-dl.fish`. Symlinking to this file works, thought it would be nice to have this right from the template.

**Comment by maxice8** [comment]
Working on it
