### ISSUE TITLE
Add GCC 6 Package (For CUDA)

### ISSUE THREAD

**Issue by benrob0329** [voidlinux/void-packages#8856]
### System

* xuname:  Void 4.13.10_1 x86_64 GenuineIntel notuptodate rrrrmmnF
* architecture:  x86_64
* libc:  glibc
* package:  gcc-*

### Expected behavior
Other distros have the option to allow the installation of multiple compiler versions, such as for the use of CUDA (which currently does not support gcc > 6).
### Actual behavior
Void only has one compiler version, which is incompatible with CUDA.
### Steps to reproduce the behavior
1. Install the CUDA runtime from runfile.
2. Attempt to compile anything (if you did --override to stop the pre-installation checks)
3. Fail, unsupported gcc version

**Comment by the-maldridge** [comment]
Our current package architecture includes only one version for each package.  Maintaining the single GCC package is already at the limit of what we can do, adding another one is simply beyond the resources, and out of scope of the project goals.
