### ISSUE TITLE
Package Request: Guacamole

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#8864]
project link: http://guacamole.incubator.apache.org/releases/
License:Apache-2.0 

anyone interested in this project ?

**Comment by cr6git** [comment]
I am currently working on this, but I have a problem here: 
````
checking for uuid_make in -lossp-uuid... no
checking for uuid_make in -luuid... no
configure: error: "The OSSP UUID library is required"
=> ERROR: guacamole-server-0.9.13_1: failed to run do_configure() at line 7.
````

I can see `libossp-uuid` in the `shlibs`
````
$ grep uuid common/shlibs
libuuid.so.1 libuuid-2.18_1
libossp-uuid.so.16 libossp-1.6.2_1
````

But I can't find the package `libossp`
````
$ xbps-query -Rs libossp
(returns nothing)
````

Weird.

**Comment by Vaelatern** [comment]
0d083ba937

**Comment by cr6git** [comment]
deleted ? so `guacamole` won't be packaged.

**Comment by Vaelatern** [comment]
Unless it can use a different uuid package, try libuuid?

**Comment by cr6git** [comment]
I tryed with `libuuid-devel-2.31_2` but it doesn't work. 
See the documentation in [#required-dependencies](http://guacamole.incubator.apache.org/doc/gug/installing-guacamole.html#required-dependencies) : `OSSP UUID` is required.

**Comment by cr6git** [comment]
@Vaelatern So, what more can be done ??

**Comment by Vaelatern** [comment]
sadly nothing more, unless the upstream picks a maintained library.
