### ISSUE TITLE
nodejs: remove python dependency

### ISSUE THREAD

**Issue by aeosynth** [voidlinux/void-packages#8886]
i can go to https://nodejs.org/en/, download a node binary, and run it without needing python. is there a reason the void package depends on python to install?

**Comment by arete** [comment]
Hi the python dependency is necessary for npm install (node-gyp build tool)
https://github.com/nodejs/node-gyp
Some  npm package have need local rebuild via node-gyp.

**Comment by Gottox** [comment]
agreed.
