### ISSUE TITLE
package intel-ucode fails to place file on /boot 

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#8897]
* xuname:  
Void 4.13.10_1 x86_64 GenuineIntel uptodate rrrrmmn
* architecture:  
 x64
* libc:  
glibc
* package:  
intel-ucode

### Expected behavior

create a intel-ucode.img into /boot 

### Actual behavior

intel-ucode.img is not on into /boot 

### Steps to reproduce the behavior

sudo xbps-install -Sf intel-ucode

**Comment by cr6git** [comment]
It's in `/boot/initramfs.img` generated by dracut.

**Comment by icf20** [comment]
well is not for some reason 
![image](https://user-images.githubusercontent.com/17784575/32415745-91577f1c-c23e-11e7-87f1-ec4bf8613413.png)

**Comment by cr6git** [comment]
And what model is your CPU ?

**Comment by icf20** [comment]
model name      : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by Duncaen** [comment]
```
mkdir /etc/dracut.d
echo early_microcode=yes >>/etc/dracut.d/intel-ucode.conf
xbps-reconfigure -f linux4.13
```

**Comment by icf20** [comment]
> xbps-reconfigure -f linux4.13

that was the missing step
