### ISSUE TITLE
`xbps-remove linux4.8` tries to remove /boot

### ISSUE THREAD

**Issue by avoidr** [voidlinux/void-packages#8899]
I don't know if this is reason for concern, but this just happened:
```
# xbps-remove linux4.8

Name     Action    Version           New version            Download size
linux4.8 remove    4.8.17_1          -                      -

Do you want to continue? [Y/n] y
Removing `linux4.8-4.8.17_1' ...
ERROR: linux4.8-4.8.17_1: failed to remove directory `/boot': Device or resource busy
Executing post-remove kernel hook: 20-dracut ...
Executing post-remove kernel hook: 50-grub ...
Generating grub configuration file ...
[…]
Found linux image: /boot/vmlinuz-4.8.12_1
Found initrd image: /boot/initramfs-4.8.12_1.img
done
Removed `linux4.8-4.8.17_1' successfully.
```

Also, `vkpurge list` didn't show 4.8.17 prior to the removal, only 4.8.12.

Is it normal, that xbps-remove tries to remove /boot?

**Comment by icf20** [comment]
@avoidr the proper way is `sudo vkpurge rm 4.8.17_1`

**Comment by avoidr** [comment]
Yes, but vkpurge didn't show 4.8.17, only 4.8.12.

And even if, xbps-remove shouldn't even attempt to remove /boot.
I don't know where this behaviour comes from, but I would like to know.

What I expected is it removes 4.8.17 with the same result as vkpurge would have done. I also expected it would maybe remove 4.8.12 also, since the package is linux4.8.
But I didn't expect it to try to remove /boot, which seems like a weird thing to do. When I xbps-remove any other userland package, it doesn't try to remove /usr/bin, either.

**Comment by cr6git** [comment]
Have a look at [#8899](https://github.com/voidlinux/void-packages/issues/8899).

**Comment by avoidr** [comment]
Eh, I failed to search void-packages for this issue. Only did in xbps repo.

Thank you, @cr6git !
