### ISSUE TITLE
Request Chromium update

### ISSUE THREAD

**Issue by elroncio** [voidlinux/void-packages#8930]
The current version (61) is old, the newest stable version is Chromium 62.

**Comment by Duncaen** [comment]
https://github.com/voidlinux/void-packages/commit/53fed9bb202bdbd80a24b2f4095bf458ae14102a

**Comment by StreetStrider** [comment]
I've updated chromium 61 -> 63 today. Now it fails to start:
`/usr/lib/chromium/chromium: /usr/lib/libstdc++.so.6: version GLIBCXX_3.4.23 not found (required by /usr/lib/chromium/chromium)`.
