### ISSUE TITLE
Wrapper for go/rust/python/perl/etc-pkgs?

### ISSUE THREAD

**Issue by Anachron** [voidlinux/void-packages#8942]
I was just thinking:

What would be if we have a wrapper (for example `xbps-go`, `xbps-rust`, etc) which handles pkg installations for each package system?

Right now it's quite a hassle between pkgs that exist and pkgs that are needed to be added to the pkg-tree.

My idea was to have a eco-system dependent tree/structure which allows for easier and safer handling of those. For example using `virtualenv` and alike for `python`, so all dependencies can be cleaned up correctly on uninstall. 

What do you guys think? Is this something worth investing in? 

Edit:
Maybe I should elaborate further. I was thinking about using some custom paths (e.g. `/usr/lib/go-pkgs/` to put `xbps-go` packages into (being installed by `xbps-go`).

**Comment by Duncaen** [comment]
You are going to end up with 10 limited wrappers for programs that already support installing into their own prefix.

**Comment by Anachron** [comment]
Then what's the point of having python-packages if you are having trouble to correctly cleanup orphans on the default packaging system?

**Comment by Duncaen** [comment]
afaik python packages are solely working around the issue that xbps packages depend on python packages or python packages that depend on xbps packages.
Not sure what you mean by trouble cleaning up orphans.

**Comment by Anachron** [comment]
I'm closing this,- I'll create this one myself if nobody else sees the use.
