### ISSUE TITLE
spacefm-ng version should be GTK2, not GTK3.

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#8947]
### System

* package:  [spacefm-ng](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/spacefm-ng/template) 1.0.6

### Expected behavior
The version should be GTK2, like the old [spacefm](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/spacefm/template). 
According to the [documentation](https://github.com/Teklad/spacefm-ng/wiki/building-the-source) GTK2 is enabled by default. GTK3 is conditional. 
I propose to change the template, to remove this line: 
`build_options_default="gtk3"`

**Comment by Gottox** [comment]
are there any problems with gtk3?

**Comment by cr6git** [comment]
I quote this [comment](https://github.com/IgnorantGuru/spacefm/issues/636#issuecomment-209533330) from @IgnorantGuru: "In general GTK3 is prone to this breakage across versions. That's why GTK2 is still and may always be the default for SpaceFM, especially if stability is preferred." 

And the [README](https://github.com/IgnorantGuru/spacefm/blob/master/README#L170) says: "PACKAGERS: Due to other desktop components, some users may require or prefer GTK2. Please consider providing both spacefm-gtk2 and spacefm-gtk3 packages for your users."

I think we should respect that.

**Comment by Gottox** [comment]
Seem reasonable. Default is now gtk2.
