### ISSUE TITLE
Package request: io.js

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#900]
https://iojs.org/

**Comment by uggedal** [comment]
We should wait until it is stable (it's currently marked as *Unstable*). When (if) it gets stabilized we could evaluate whether we should replace nodejs with iojs.

**Comment by radare** [comment]
it's already stable. 1.2.0 has been released. See https://iojs.org/dist/v1.2.0/

**Comment by radare** [comment]
i think keeping nodejs and iojs at the same time can be interesting, nodejs aims to be stable, and iojs aims to support latest v8 and so, benchmarks show that iojs is better in some cases, but worst in others, and its changing more frequently.  For production I would choose nodejs

**Comment by Gottox** [comment]
The discussion about io.js and node has settled. Many big projects (such as atom) made a switch to iojs. On the other hand, Joyent announced that they will move node.js to a independant foundation. So in the short term a io.js package makes perfectly sense. In the long term I suspect that io.js will be merged back to node.js. (or node.js into io.js, we'll see)

**Comment by xtraeme** [comment]
xbps-query -R iojs
