### ISSUE TITLE
Package Request: Firefox Quantum

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#9009]
https://www.mozilla.org/en-US/firefox/developer/

imo some people can be interested into firefox for web developers

**Comment by 7185** [comment]
Quantum is Firefox 57. The differences between the developer edition and the normal edition are close to none. I'm not sure it's really useful to package this, unless I'm missing something.

**Comment by icf20** [comment]
> close to none.

just try to put firebug on normal firefox, https://getfirebug.com/

**Comment by Vaelatern** [comment]
Firebug is depreciated.

**Comment by icf20** [comment]
@Vaelatern afaik is put in developer edition

**Comment by Duncaen** [comment]
The normal version has developer tools too, the only difference is the dark theme and that its based on the beta version as far as I know.
Void has no resources left to maintain or build another Firefox version, if you really need the developer edition, you can try the binaries provided by Mozilla.
