### ISSUE TITLE
Package Request: mate-tweak

### ISSUE THREAD

**Issue by mrnhmath** [voidlinux/void-packages#9043]
Tweak tool for the MATE Desktop

https://github.com/ubuntu-mate/mate-tweak

**Comment by cr6git** [comment]
@ebfe see my pr.

**Comment by cr6git** [comment]
allo?

**Comment by cr6git** [comment]
@mrnhmath Seems like the Void devs are not interested in this program...

**Comment by cr6git** [comment]
I updated my PR to the latest version 18.04.0.

**Comment by cr6git** [comment]
Done.

**Comment by mrnhmath** [comment]
Yay! ty @cr6git
