### ISSUE TITLE
hugin: C++ ABI mismatch

### ISSUE THREAD

**Issue by Veyrdite** [voidlinux/void-packages#9047]
### System

* xuname:  Void 4.13.12_1 x86_64 GenuineIntel uptodate rrrrmmnF
* architecture:   x64_64, i686
* libc:  glibc
* package:  hugin-2017.0.0_4

### Error
     $ hugin
     Fatal Error: Mismatch between the program and library build versions detected.
     The library used 3.0 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 2.8),
     and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
     Aborted

**Comment by ebfe** [comment]
It needs a rebuild due to the gcc update and the wxWidgets ABI check. Unfortuanetly it doesn't currently build c16fb984561c5ad3dd54d9cfe382b30968400e63

**Comment by ebfe** [comment]
Seems fixed by 5ca276d45ee232c94984d0c34b8f3ddd67d20a2d

**Comment by pullmoll** [comment]
I tried locally and hugin builds again. It was the missing _GLIBCXX_USE_C99_STDLIB or _GLIBCXX_USE_C99_STDIO flags which caused the breakage. broken= can be removed.
