### ISSUE TITLE
synergy: missing distfile

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#9107]
```
https://github.com/symless/synergy/archive/v1.8.8-stable.tar.gz: Not Found
=> ERROR: synergy-1.8.8_2: failed to fetch v1.8.8-stable.tar.gz.
```

**Comment by newbluemoon** [comment]
Was renamed to synergy-core and updated to 2.0.0. Cmake’s complaints about a revision string can be solved by adding `-DSYNERGY_VERSION_STAGE=stable` to `configure_args`. But then the build stops with

    error: 'SSL_get_client_ciphers' was not declared in this scope

because this function doesn’t exist in libressl.

**Comment by Johnnynator** [comment]
The LibreSSL issue is only minor: https://github.com/symless/synergy-core/pull/6182
The other problem is that they completely removed the gui from the code: ttps://news.ycombinator.com/item?id=15335174

Also the question is if the full featured 1.8.8 should be replaced by the crippled 2.0.0 or if there should be a new package named synergy-core which would be synergy 2.
