### ISSUE TITLE
enblend-enfuse: cannot find libgsl.so.19

### ISSUE THREAD

**Issue by Veyrdite** [voidlinux/void-packages#9112]
### System

* xuname:  Void 4.13.12_1 x86_64 GenuineIntel uptodate rrrrmmnFFF
* package:  enblend-enfuse-4.2_2

### Error

     $ enblend
     enblend: error while loading shared libraries: libgsl.so.19: cannot open shared object file: No such file or directory

### Workaround

     $ cd /usr/lib; sudo ln libgsl.so libgsl.so.19

Enblend seems to work fine after this (however I might not be using it in a case where libgsl calls are made).

**Comment by ebfe** [comment]
The unversioned symlink is in gsl-devel.

**Comment by Veyrdite** [comment]
@ebfe: the program points directly to the libgsl.so.19 version, ignores the unversioned libgsl.so

**Comment by ebfe** [comment]
Oh, switched that up. Are you using an outdated mirror? Current gsl has libgsl.so.23 and enblend-enfuse is working fine on x86_64.

**Comment by Veyrdite** [comment]
I'm a fool ebfe.  Thankyou for your time, sorry about my mistake.

     $ which enblend
    /home/valentine/bin/enblend
