### ISSUE TITLE
Docker minimal image: xbps-install error

### ISSUE THREAD

**Issue by arete** [voidlinux/void-packages#9133]
### System+++

* xuname:  
  Void 4.13.12_1 x86_64 AuthenticAMD uptodate rrrmF
* package:  
  xbps

### Steps to reproduce the behavior

I try to create an minimal Docker image for voidlinux.
this is the Dockerfile
`FROM scratch
ADD ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ADD https://repo.voidlinux.eu/static/xbps-static-latest.x86_64-musl.tar.xz  /

RUN ["/usr/bin/xbps-install","-Syuv","-d","-R","https://repo.voidlinux.com/curre
nt","base-files","dash","bash","coreutils","grep","xbps","iana-etc","tzdata","se
d"]
`

this is the error
`[DEBUG] XBPS: 0.51 API: 20151030 GIT: UNSET
[DEBUG] Processing configuration directory: /etc/xbps.d
[DEBUG] Processing system configuration directory: /usr/share/xbps.d
[DEBUG] rootdir=/
[DEBUG] metadir=//var/db/xbps
[DEBUG] cachedir=/var/cache/xbps
[DEBUG] confdir=/etc/xbps.d
[DEBUG] sysconfdir=/usr/share/xbps.d
[DEBUG] syslog=true
[DEBUG] bestmatching=false
[DEBUG] Architecture: x86_64
[DEBUG] Target Architecture: (null)
[DEBUG] Repository[0]=https://repo.voidlinux.com/current
[*] Updating `https://repo.voidlinux.com/current/x86_64-repodata' ...
[DEBUG] st.st_size: 0
[DEBUG] st.st_atime: 01 Jan 1970 00:00
[DEBUG] st.st_mtime: 01 Jan 1970 00:00
[DEBUG] url_stat.size: -1
[DEBUG] url_stat.atime: 01 Jan 1970 00:00
[DEBUG] url_stat.mtime: 01 Jan 1970 00:00
ERROR: [reposync] failed to fetch file `https://repo.voidlinux.com/current/x86_64-repodata': Address not available
[DEBUG] [rpool] `https://repo.voidlinux.com/current' failed to fetch repository data: Address not available
[DEBUG] [repo] `//var/db/xbps/https___repo_voidlinux_com_current/x86_64-repodata' open repodata No such file or directory
The command '/usr/bin/xbps-install -Syuv -d -R https://repo.voidlinux.com/current base-files dash bash coreutils grep xbps iana-etc tzdata sed' returned a non-zero code: 95
`

**Comment by yopito** [comment]
Check your network connectivity ? first error in your log:
```
ERROR: [reposync] failed to fetch file https://repo.voidlinux.com/current/x86_64-repodata': Address not available
```

**Comment by arete** [comment]
Hi, the network is ok, get fine xbps statica archive.


Il 12 nov 2017 21:43, "yopito" <notifications@github.com> ha scritto:

**Comment by Vaelatern** [comment]
You sure? Seems like something network is broken.

**Comment by pullmoll** [comment]
FWIW the https://repo.voidlinux.com/current repo is not reachable for me but https://repo.voidlinux.eu/current is.

**Comment by arete** [comment]
my bad.
