### ISSUE TITLE
autoconf cache value for sizeof(off_t) is wrong some (many?) times

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/void-packages#9143]
### System

* xuname:  
  * Void 4.13.12_1 x86_64 GenuineIntel notuptodate rrrdFFF
* package:  
  * i686* arm*

### Expected behavior
`  sizeof(off_t) == 8` in some (many?) cases
### Actual behavior
  `sizeof(off_t) == 4`
defined in `common/environment/configure/autoconf_cache/{ix86-common,arm-linux}`
as `ac_cv_sizeof_off_t=${ac_cv_sizeof_off_t=4}`
### Steps to reproduce the behavior
  See `/usr/include/bits/alltypes.h` in musl libc (always 64 bits)
or `/usr/include/sys/types.h` in glibc with `__USE_FILE_OFFSET64` defined (if `_FILE_OFFSET_BITS=64`).

### Suggestion
For musl libc the `ac_cv_sizeof_off_t` should **always be 8**.
For glibc it would need some function (using the C preprocessor?) in e.g. `common/environment/configure/gnu-configure-args.sh` to detect if `CFLAGS` or `CXXFLAGS` contain a macro which leads to `off_t` being 64 bits.

For native builds presetting `ac_cv_sizeof_off_t` is not needed but for cross builds it needs to be set to what comes out of the compiler. Perhaps there is a clever trick to find that value without running a cross arch binary.

As it is now e.g. `zip` for `i686-musl` is broken because `sizeof(uzoff_t) != sizeof(zoff_t)`.
```
[jbu@/tmp/musl-i686 /]$ zip

zip error: Not supported (uzoff_t not same size as zoff_t)
```

**Edit:** Also `ino_t` is affected

**Comment by pullmoll** [comment]
A try to detect off64_t could be like this:
```
tmpfile=$(mktemp /tmp/XXXXXX.c)

cat > ${tmpfile} <<EOF
#include <sys/types.h>
int main() { off_t offs; (void)offs; return 0; }
EOF

if [ -n "$(gcc $CFLAGS -E ${tmpfile} | grep " off_t;$" | grep 64)" ]; then
    ac_cv_sizeof_off_t=8
else
    ac_cv_sizeof_off_t=4
fi
rm -f ${tmpfile}
```
Similar for `ino_t` and perhaps also `blkcnt_t`, which is not yet defined in autoconf cache.

**Comment by pullmoll** [comment]
At least this patch would IMO make sense:
```patch
--- common/environment/configure/autoconf_cache/musl-linux
+++ common/environment/configure/autoconf_cache/musl-linux
@@ -169,6 +169,9 @@ gt_cv_func_gnugettext1_libc=yes
 gt_cv_func_gnugettext2_libc=yes
 gt_cv_func_gnugettext3_libc=yes
 ac_cv_sys_file_offset_bits=64
+ac_cv_sizeof_off_t=8
+ac_cv_sizeof_ino_t=8
+ac_cv_sizeof_blkcnt_t=8
 
 # Force detection of musl's iconv
 ac_cv_libiconv_utf8=yes
```

**Comment by chneukirchen** [comment]
we should always use  _FILE_OFFSET_BITS=64 on i686.

else :+1:

**Comment by pullmoll** [comment]
Agree. `_FILE_OFFSET_BITS=64` will make very few packages fail, if any. I think that could become part of `hardening.sh` which modifies CFLAGS and CXXFLAGS anyway, and all autoconf cache entries for off_t, ino_t and blkcnt_t would change to 8.

**Comment by chneukirchen** [comment]
oO I thought we already set this.

Remember why not, @xtraeme?

**Comment by pullmoll** [comment]
Proposed patch:
```patch
--- common/environment/configure/autoconf_cache/arm-linux
+++ common/environment/configure/autoconf_cache/arm-linux
@@ -10,7 +10,7 @@ ac_cv_sizeof_int_p=${ac_cv_sizeof_int_p=4}
 ac_cv_sizeof_long=${ac_cv_sizeof_long=4}
 ac_cv_sizeof_long_int=${ac_cv_sizeof_long_int=4}
 ac_cv_sizeof_long_long=${ac_cv_sizeof_long_long=8}
-ac_cv_sizeof_off_t=${ac_cv_sizeof_off_t=4}
+ac_cv_sizeof_off_t=${ac_cv_sizeof_off_t=8}
 ac_cv_sizeof_short=${ac_cv_sizeof_short=2}
 ac_cv_sizeof_short_int=${ac_cv_sizeof_short_int=2}
 ac_cv_sizeof_size_t=${ac_cv_sizeof_size_t=4}
diff --git a/common/environment/configure/autoconf_cache/ix86-common b/common/environment/configure/autoconf_cache/ix86-common
index beed9a24a1..3f2dd7e152 100644
--- common/environment/configure/autoconf_cache/ix86-common
+++ common/environment/configure/autoconf_cache/ix86-common
@@ -17,10 +17,10 @@ ac_cv_sizeof_ssize_t=${ac_cv_sizeof_ssize_t=4}
 ac_cv_sizeof_void_p=${ac_cv_sizeof_void_p=4}
 ac_cv_sizeof_long_p=${ac_cv_sizeof_long_p=4}
 ac_cv_sizeof_float=${ac_cv_sizeof_float=4}
-ac_cv_sizeof_off_t=${ac_cv_sizeof_off_t=4}
+ac_cv_sizeof_off_t=${ac_cv_sizeof_off_t=8}
 ac_cv_sizeof_uid_t=${ac_cv_sizeof_uid_t=4}
 ac_cv_sizeof_gid_t=${ac_cv_sizeof_gid_t=4}
-ac_cv_sizeof_ino_t=${ac_cv_sizeof_ino_t=4}
+ac_cv_sizeof_ino_t=${ac_cv_sizeof_ino_t=8}
 ac_cv_sizeof_dev_t=${ac_cv_sizeof_dev_t=8}
 ac_cv_func_lstat_dereferences_slashed_symlink=${ac_cv_func_lstat_dereferences_slashed_symlink=yes}
 ac_cv_func_lstat_empty_string_bug=${ac_cv_func_lstat_empty_string_bug=no}
diff --git a/common/environment/configure/hardening.sh b/common/environment/configure/hardening.sh
index 0b4024e253..1d87dddd7e 100644
--- common/environment/configure/hardening.sh
+++ common/environment/configure/hardening.sh
@@ -26,3 +26,9 @@ else
 	CXXFLAGS="-fno-PIE ${CFLAGS}"
 	LDFLAGS="-no-pie ${LDFLAGS}"
 fi
+case "$XBPS_TARGET_MACHINE" in
+	i686*|arm*|mips*)
+		CFLAGS="-D_FILE_OFFSET_BITS=64 ${CFLAGS}"
+		CXXFLAGS="-D_FILE_OFFSET_BITS=64 ${CXXFLAGS}"
+		;;
+esac

```

**Comment by chneukirchen** [comment]
+1 for defining this, but perhaps not in hardening.sh? I'd not search for it there.

**Comment by pullmoll** [comment]
:-1: for this change, because e.g. armv5tel glibc build fails with _FILE_OFFSET_BITS=64 being set.
The errors look strange like:
```
CC     ../sysdeps/posix/sigsetmask.c
In file included from ../include/stdlib.h:10:0,
                 from ../include/atomic.h:48,
                 from ../sysdeps/nptl/lowlevellock.h:22,
                 from ../nptl/descr.h:29,
                 from ../sysdeps/arm/nptl/tls.h:42,
                 from ../sysdeps/unix/sysv/linux/arm/tls.h:23,
                 from ../include/errno.h:25,
                 from ../sysdeps/posix/signal.c:19,
                 from ../sysdeps/unix/sysv/linux/signal.c:3:
../include/sys/stat.h:16:1: warning: asm declaration ignored due to conflict with previous rename [-Wpragmas]
 hidden_proto (__fxstat)
 ^~~~~~~~~~~~
../include/sys/stat.h:18:1: warning: asm declaration ignored due to conflict with previous rename [-Wpragmas]
 hidden_proto (__lxstat)
 ^~~~~~~~~~~~
../include/sys/stat.h:20:1: warning: asm declaration ignored due to conflict with previous rename [-Wpragmas]
 hidden_proto (__xstat)
 ^~~~~~~~~~~~
../include/sys/stat.h:35:1: warning: asm declaration ignored due to conflict with previous rename [-Wpragmas]
 libc_hidden_proto (__fxstatat)
 ^~~~~~~~~~~~~~~~~
In file included from ../include/stdlib.h:10:0,
                 from ../include/atomic.h:48,
                 from ../sysdeps/nptl/lowlevellock.h:22,
                 from ../nptl/descr.h:29,
                 from ../sysdeps/arm/nptl/tls.h:42,
                 from ../sysdeps/unix/sysv/linux/arm/tls.h:23,
                 from ../sysdeps/unix/sysv/linux/arm/sysdep.h:30,
                 from ../sysdeps/unix/sysv/linux/raise.c:20:
```

I wasn't able solve this by setting various C{,XX}FLAGS options when trying.
It seems as if we have to resort to another way to make `the glibc ac_cv_sizeof_off_t={4,8}` match what the compiler will generate. Chicken-egg problem here is inspecting vs. defining configure_args. This feels like opening Pandora's box.

**Comment by pullmoll** [comment]
Rethinking the _FILE_OFFSET_BITS=64 patch perhaps the glibc and cross-* templates, i.e. everything that builds a glibc, can be modified to undefine this macro or remove it from the flags. I'll give it a try here and if it works out will create a PR.

**Comment by pullmoll** [comment]
I gave up on trying to find a solution for this chicken - egg problem. You can't decide which of 4 or 8 to use for ac_cv_sizeof_off_t because it would require to know the CFLAGS and/or CXXFLAGS beforehand, while on the other end these depend on the configure results.
