### ISSUE TITLE
John has way too few available formats

### ISSUE THREAD

**Issue by faulesocke** [voidlinux/void-packages#9226]
`john -h` only shows the following hash formats:

```
--format=NAME             force hash type NAME: AFS bcrypt bsdicrypt crypt
                          descrypt dummy dynamic_n LM md5crypt scrypt tripcode
```

However, the used jumbo version of John should be theoretically capable of doing a sh*tload of hash formats. On one of my arch linux machines it reports about 30 lines in the help message and even when compiled without openmp and mpi, it should be *a lot*.

I've poked in the template for like 3 hours but couldn't find what causes the issue. Maybe someone else has a clue?

Regards

**Comment by newbluemoon** [comment]
The [homepage](http://www.openwall.com/john/) says it needs OpenSSL for additional hash and cipher types:

> This version integrates lots of contributed patches adding GPU support (OpenCL and CUDA), support for a hundred of additional hash and cipher types (including popular ones such as NTLM, raw MD5, etc., and even things such as encrypted OpenSSH private keys, ZIP and RAR archives, PDF files, etc.), as well as some optimizations and features. Unfortunately, its overall quality is lower than the official version's. **Requires OpenSSL**.

**Comment by Vaelatern** [comment]
We have `libressl` there during build, so if it needs OpenSSL beyond that, it's just a shame.

**Comment by Vaelatern** [comment]
Follow-up issue seems to understand where this happened.
