### ISSUE TITLE
Elantech Trackpad Not Recognized Correctly and Unresponsive

### ISSUE THREAD

**Issue by Antonio-Malcolm** [voidlinux/void-packages#923]
Elantech trackpad isn't recognized correctly by the system, and doesn't respond to input.
This is not a particularly new issue, and I believe there may be a kernel patch for it.

Output of xinput list (I beleive it's being identified as the first E-Signal Keyboard entry, id=13, [slave  pointer  (2)]):

⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ MLK rapoo 3500                          	id=11	[slave  pointer  (2)]
⎜   ↳ E-Signal Keyboard                       	id=13	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Video Bus                               	id=9	[slave  keyboard (3)]
    ↳ Power Button                            	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
    ↳ E-Signal Keyboard                       	id=12	[slave  keyboard (3)]
    ↳ HD WebCam   

Output of cat /proc/bus/input/devices:

I: Bus=0011 Vendor=0001 Product=0001 Version=ab83
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input0
U: Uniq=
H: Handlers=sysrq kbd event0 
B: PROP=0
B: EV=120013
B: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0019 Vendor=0000 Product=0005 Version=0000
N: Name="Lid Switch"
P: Phys=PNP0C0D/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/PNP0C0D:00/input/input2
U: Uniq=
H: Handlers=event1 
B: PROP=0
B: EV=21
B: SW=1

I: Bus=0019 Vendor=0000 Product=0003 Version=0000
N: Name="Sleep Button"
P: Phys=PNP0C0E/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/PNP0C0E:00/input/input3
U: Uniq=
H: Handlers=kbd event2 
B: PROP=0
B: EV=3
B: KEY=4000 0 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=PNP0C0C/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input4
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input5
U: Uniq=
H: Handlers=kbd event4 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:4f/LNXVIDEO:00/input/input6
U: Uniq=
H: Handlers=kbd event5 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:01/input/input7
U: Uniq=
H: Handlers=kbd event6 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0010 Vendor=001f Product=0001 Version=0100
N: Name="PC Speaker"
P: Phys=isa0061/input0
S: Sysfs=/devices/platform/pcspkr/input/input8
U: Uniq=
H: Handlers=kbd event7 
B: PROP=0
B: EV=40001
B: SND=6

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel HDMI HDMI/DP,pcm=3"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:03.0/sound/card0/input9
U: Uniq=
H: Handlers=event8 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel HDMI HDMI/DP,pcm=7"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:03.0/sound/card0/input10
U: Uniq=
H: Handlers=event9 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel HDMI HDMI/DP,pcm=8"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:03.0/sound/card0/input11
U: Uniq=
H: Handlers=event10 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH Mic"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card1/input13
U: Uniq=
H: Handlers=event11 
B: PROP=0
B: EV=21
B: SW=10

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card1/input14
U: Uniq=
H: Handlers=event12 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH SPDIF"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card1/input15
U: Uniq=
H: Handlers=event13 
B: PROP=0
B: EV=21
B: SW=140

I: Bus=0003 Vendor=04fc Product=05da Version=0110
N: Name="MLK rapoo 3500"
P: Phys=usb-0000:00:14.0-6/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-6/3-6:1.0/0003:04FC:05DA.0001/input/input16
U: Uniq=
H: Handlers=kbd mouse0 event14 
B: PROP=0
B: EV=1f
B: KEY=3f0003007f 0 0 483ffff17aff32d bf54444600000000 1f0001 120f938b17c000 677bfad9415fed 9ed68000004400 10000002
B: REL=1c3
B: ABS=100000000
B: MSC=10

I: Bus=0003 Vendor=1044 Product=7a06 Version=0110
N: Name="E-Signal Keyboard"
P: Phys=usb-0000:00:14.0-8/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8:1.0/0003:1044:7A06.0002/input/input17
U: Uniq=
H: Handlers=sysrq kbd event15 
B: PROP=0
B: EV=120013
B: KEY=1000000000007 ff9f207ac14057ff febeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=1044 Product=7a06 Version=0110
N: Name="E-Signal Keyboard"
P: Phys=usb-0000:00:14.0-8/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8:1.1/0003:1044:7A06.0003/input/input18
U: Uniq=
H: Handlers=kbd mouse1 event16 js0 
B: PROP=0
B: EV=10001f
B: KEY=3f0003007f 0 0 483ffff17aff32d bf54444600000000 1f0001 120f938b17c000 677bfad9415fed 9ed68000004400 10000002
B: REL=1c0
B: ABS=100000003
B: MSC=10

I: Bus=0003 Vendor=1bcf Product=2c6b Version=0003
N: Name="HD WebCam"
P: Phys=usb-0000:00:14.0-11/button
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb3/3-11/3-11:1.0/input/input19
U: Uniq=
H: Handlers=kbd event17 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

**Comment by Antonio-Malcolm** [comment]
OK, I *may* have found a workaround for this.
I say "*may*", because it's a bit wonky, and I can't promise it will work for everyone.

It involves adding some very specific settings to 50-synaptics.conf, then leaving the machine powered down for 10min-15min afterward. If that sounds like voodoo, believe me, it looks like voodoo, too; *the additional settings, alone, aren't enough- something needs time to clear for them to stick*. My guess is that there's something in the contents of memory which needs to clear. That said, once the settings are added, and the machine is down for a bit, you can reboot, and the touchpad will work through subsequent reboots. 

Here are the settings, followed by a brief explanation. I may also post this to the Google list, as, until known kinks in the Linux kernel are worked out, this may be the only reliable means of using an Elantech touchpad in Linux (outside of the more common/widely-used/well-worn distros, who already have patches in place):

    # 50-synaptics.conf
    
    Section "InputClass"
       Identifier "touchpad ignore duplicates"
       MatchIsTouchpad "on"
       MatchOS "Linux"
       MatchDevicePath "/dev/input/mouse*"
       Option "Ignore" "on"
    EndSection

    Section "InputClass"
       Identifier "touchpad catchall"
       Driver "synaptics"
       MatchIsTouchpad "on"
       MatchDevicePath "/dev/input/event*"
       Option "SHMConfig" "on"
    EndSection

The primary block to note, here, is at the top, and contains the ignore duplicate settings. Other settings, such as those for tapping and scrolling, can be placed in subsequent blocks, but, for this to work, the top block must be used, *as-is*.

**Comment by xtraeme** [comment]
From Linux 3.18.4 (which I've just pushed):

```

commit aae7cd96b4e51e28032b2fa14f1552cec5d90146
Author: Srihari Vijayaraghavan <linux.bug.reporting@gmail.com>
Date:   Wed Jan 7 16:25:53 2015 -0800

    Input: i8042 - reset keyboard to fix Elantech touchpad detection
    
    commit 148e9a711e034e06310a8c36b64957934ebe30f2 upstream.
    
    On some laptops, keyboard needs to be reset in order to successfully detect
    touchpad (e.g., some Gigabyte laptop models with Elantech touchpads).
    Without resettin keyboard touchpad pretends to be completely dead.
    
    Based on the original patch by Mateusz Jończyk this version has been
    expanded to include DMI based detection & application of the fix
    automatically on the affected models of laptops. This has been confirmed to
    fix problem by three users already on three different models of laptops.
    
    Bugzilla: https://bugzilla.kernel.org/show_bug.cgi?id=81331
    Signed-off-by: Srihari Vijayaraghavan <linux.bug.reporting@gmail.com>
    Acked-by: Mateusz Jończyk <mat.jonczyk@o2.pl>
    Tested-by: Srihari Vijayaraghavan <linux.bug.reporting@gmail.com>
    Tested by: Zakariya Dehlawi <zdehlawi@gmail.com>
    Tested-by: Guillaum Bouchard <guillaum.bouchard@gmail.com>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
```

Could be related to your issue :-)

**Comment by xtraeme** [comment]
This commit could also be related:

```
commit 17afe476900a76e3dfc3bc51d5776a52738eb2eb
Author: Sam hung <sam.hung@emc.com.tw>
Date:   Thu Jan 8 13:22:43 2015 -0800

    Input: elantech - support new ICs types for version 4
    
    commit 810aa0918b2b032684c8cad13f73d6ba37ad11c0 upstream.
    
    This change allows the driver to recognize newer Elantech touchpads.
    
    Signed-off-by: Yi ju Hong <sam.hung@emc.com.tw>
    Signed-off-by: Dmitry Torokhov <dmitry.torokhov@gmail.com>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
```

**Comment by amalcolm-cds** [comment]
Ok, I'll update my local.
Currently, my trackpad is working, but without multi-touch/scrolling.
If the kernel update doesn't sort that out, I will have a look at this module patch:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1166442/+index?comments=all

**Comment by Antonio-Malcolm** [comment]
Ok, I'll update my local.
Currently, my trackpad is working, but without multi-touch/scrolling.
If the kernel update doesn't sort that out, I will have a look at this module patch:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1166442/+index?comments=all

**Comment by amalcolm-cds** [comment]
Yup, that solved the problem of it being recognized- now, if I can only get multitouch features to work. Vertical edge scrolling *sort of* works. That is more likely an issue with the driver, itself, however.
Thanks!

**Comment by Antonio-Malcolm** [comment]
Yup, that solved the problem of it being recognized- now, if I can only get multitouch features to work. Vertical edge scrolling *sort of* works. That is more likely an issue with the driver, itself, (or, more xorg settings being overridden by cinnamon) however.
Thanks!

**Comment by Antonio-Malcolm** [comment]
Ok, I think we can consider this fixed. Got multitouch features working via X11 config. Odd, cinnamon settings recognize the trackpad and offer up all the settings, but they don't work without a detailed X11 config (vs things like screen DPI, for which it overrides the X11 settings).

Anyhow, this appears to be working properly, from the kernel POV.

**Comment by xtraeme** [comment]
Is this still applicable? if it's resolved please close it.
