### ISSUE TITLE
xorg-input-drivers should depend on xf86-input-libinput

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#9246]
Any reason it doesn't?

**Comment by pullmoll** [comment]
xf86-input-libinput was added 2015-02-15 and the last relevant change in xorg-input-drivers predates that. Looks like an oversight.

**Comment by pullmoll** [comment]
Can meta packages be architecture dependent? In that case xorg-input-drivers should include xf86-input-vmmouse only for i686* and x86_64*.

**Comment by ebfe** [comment]
> Can meta packages be architecture dependent? 

I don't think there is anything special to meta packages. Btw. last build of xorg-input-drivers was in 2014 so there are not arm* or aarch* packages.

**Comment by pullmoll** [comment]
That's why I asked. Without xorg-input-drivers, which currently can't be built for arm* and aarch*, there is no xorg package either :)

**Comment by chneukirchen** [comment]
There is no restriction on meta package dependencies. They should just depend on what makes sense for that platform.
