### ISSUE TITLE
Run 16-bit protected mode legacy code

### ISSUE THREAD

**Issue by newbluemoon** [voidlinux/void-packages#9251]
I’m trying to create a package for [dosemu2](https://github.com/stsp/dosemu2) to run some old DOS programs. To be able to have DPMI support to run protected mode programs following kernel options are needed:

```
CONFIG_MODIFY_LDT_SYSCALL
CONFIG_X86_16BIT
CONFIG_X86_ESPFIX64
```

of which only the first one is available in Void.

My knowledge in these matters is quite limited. Is there a reason why they are disabled/not enabled; would it be a drawback to have them in general? Would I have to build my own kernel if I wanted to use them?

**Comment by chneukirchen** [comment]
These were removed as part of hardening the x86_64 kernel in 
7ef2c2705f.

You'll have to build your own kernel, or use i686.

**Comment by newbluemoon** [comment]
Ok. Thank you!

**Comment by newbluemoon** [comment]
Would it make sense then if I made a PR for dosemu2, maybe with an INSTALL.msg explaining this? Non-protected mode programs can be run and I’ve been using it for a while now. Or do you think there’s no chance adding the package?

**Comment by chneukirchen** [comment]
I don't mind adding the package.

**Comment by newbluemoon** [comment]
Ok. When there is the next release (which will include musl compatibility) I’ll open a PR. Thanks.
