### ISSUE TITLE
xbps-install -u made system unusable!

### ISSUE THREAD

**Issue by ayghor** [voidlinux/void-packages#927]
On a xterm, I ran

		# xbps-install -S
		# xbps-install -u

and got away for a while.

When I got back, I was on tty6, where I `startx`. Didn't remember if X had
died, but I couldn't switch to anything but tty1 and tty6, which had no login
prompts.

I `ctrl-alt-del` and it worked. On restart, teh bootscripts ran normally but
there was no login prompt at teh end.

I managed to boot with teh pendrive I used to install void, chrooted into my hd
and ran teh same commands to update all packages. It worked!

After rebooting, login prompts were back and here I am.

I also noticed tty5 and 6 were disabled, and relinked them into runit.

**Comment by xtraeme** [comment]
Sounds like the `runit-void` package couldn't be configured successfully.

runit-void-20150127_1 disabled agetty-tty[5-6], and then it was corrected in _2.

**Comment by xtraeme** [comment]
Try `xbps-query -l` and then look if you have any pkg in `uu` state. That means the pkg was unpacked but not configured... run `xbps-reconfigure -a` to reconfigure them.

**Comment by ayghor** [comment]
[root@SkyLittleSystem ~]# xbps-query -l | grep uu
    ii libuuid-2.25.2_4                        UUID library
    ii libuuid-devel-2.25.2_4                  UUID library development files

**Comment by xtraeme** [comment]
I suppose you ran `startx` in `tty6` and the update disabled agetty on it...

**Comment by ayghor** [comment]
Yes, probably. And then `xbps-install -u` was killed in teh middle.

**Comment by xtraeme** [comment]
Problem understood, thanks for reporting :-)
