### ISSUE TITLE
do_check should be part of build_styles

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#9270]
`do_check() {  make -j${makejobs} check  }` would already cover many cases

**Comment by Anachron** [comment]
:+1: 

There are some script which would break though:
[python-envdir](https://github.com/voidlinux/void-packages/blob/103f57f4823fcda9b321fce425fa6800561d4a13/srcpkgs/python-envdir/template#L19)

**Comment by ebfe** [comment]
Then you adjust the corresponding build_style, use {pre,post}_check or override do_check as with any other function.

**Comment by pullmoll** [comment]
I'm undecided whether this would be good. Ok, you have to enable checking anyway, but many packages would fail to build, if you enabled XBPS_CHECK_PKGS=yes and those packages fail the check or have another way to run tests.

**Comment by ebfe** [comment]
Are there e.g. `gnu-configure` packages that don't have a `make check` target? And if yes, would it be hard to detect?

**Comment by pullmoll** [comment]
I have no clue if or how many packages would be affected. IMO we can give it a try because only people enabling checking will be affected.

**Comment by chneukirchen** [comment]
This is not a good default, there are many packages which don't have `make check`.

We could use `make -q check` and test for $? to be 1, then run the test suite (if it doesn't exist it's $2 == 2).

**Comment by ebfe** [comment]
> This is not a good default, there are many packages which don't have make check.

That why it should be part of build_style.

**Comment by ebfe** [comment]
autotools seem to always generate a `check` target so `gnu-configure` could use a default. For `go` something like `go test ${go_package}` should work as reasonable default. `meson` has `ninja test` etc.

**Comment by maxice8** [comment]
> meson has ninja test,

for do_check i added to meson packages, `ninja -C build test`  worked perfectly

> perl-ModuleBuild ./Build test, perl-module make test, ...

I found that some perl-module packages don't have make test somehow and you need to `prove -b`

also `cargo test --release` should work for rust.

**Comment by ebfe** [comment]
Just to clear this up: 
 - this is not about enabling the check step by default for every build.
 - yes, the build_styles do_check will not work in 100% of the cases (just like every other step)
 - for some build_styles there might not be a good default at all

This is merely about providing a reasonable default do_check based on the build_style.
