### ISSUE TITLE
Package Request:  Llvm 5

### ISSUE THREAD

**Issue by Txemadh** [voidlinux/void-packages#9285]
Would love to have this packages within the void linux repos to have a better experience with this amazing distro:

Llvm 5 [http://releases.llvm.org/download.html](url) and Clang 5 for a best use driver amdgpu for Rx580,because I have problems with some steam games that I can not make work, as for example almost none of the company feral type rally shadow of mordor f1 2017.
Best regards,
Sincerely,
Txema

**Comment by ebfe** [comment]
https://github.com/voidlinux/void-packages/pull/7612

**Comment by Txemadh** [comment]
thank you very much for all the work done to help me with the issue of llvm 5, have made most feral games work in my system, such as F1 2017 at an incredible speed,
Many thanks again to everyone for making void the best Linux distro, especially for me,
Best regards,
Sincerely,
Txema
