### ISSUE TITLE
NetworkManager installation not creating /etc/NetworkManager/system-connections

### ISSUE THREAD

**Issue by ViktorF** [voidlinux/void-packages#932]
So i installed NetworkManager and i was unable to add connections. 
While using nm-applet an error message occurred "No plugin found for this connection". The Message occured no mather which connection I tried to add.
So i started NetworkManager in debugging mode and found this warning:
"Cannot read directory '/etc/NetworkManager/system-connections': (4) Error opening directory '/etc/NetworkManager/system-connections': No such file or directory"
I checked if the directory exists but it didn't. So I created it and it fixed the error.

Screenshot: https://i.imgur.com/meQhD4Y.png

**Comment by xtraeme** [comment]
Thanks @ViktorF :+1:
