### ISSUE TITLE
bftpd: do_check fails 

### ISSUE THREAD

**Issue by maxice8** [voidlinux/void-packages#9348]
### System

* xuname:  Void 4.13.11_1 x86_64-musl GenuineIntel uptodate rrFFFFFFFFFF
* package: bftpd-4.7_1

### Expected behavior

autoconf create a dummy check target that always works

### Actual behavior

make check fails

### Steps to reproduce the behavior

1. Sync xbps-src tree
2. ./xbps-src check bftpd

log: https://p.iotek.org/w92

==> bftpd__do-fetch_00-distfiles.log

==> bftpd__do-extract_00-distfiles.log
[1m=> bftpd-4.8_1: extracting distfile(s), please wait...
[m

==> bftpd__post-extract_00-patches.log

==> bftpd__pre-configure_00-gnu-configure-asneeded.log

==> bftpd__pre-configure_01-override-config.log

==> bftpd__pre-configure_02-script-wrapper.log

==> bftpd__do_configure.log
creating cache ./config.cache
checking for gcc... cc
checking whether the C compiler (cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -Wl,-z,relro -Wl,-z,now -Wl,--as-needed    ) works... yes
checking whether the C compiler (cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -Wl,-z,relro -Wl,-z,now -Wl,--as-needed    ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether cc accepts -g... yes
checking how to run the C preprocessor... cpp
checking for AIX... no
checking for a BSD compatible install... /builddir/.xbps-bftpd/wrappers/install -c
checking for getusershell in -lc... yes
checking for inet_ntoa in -lc... yes
checking for socket in -lsocket... no
checking for connect in -lsocket... no
checking for crypt in -lcrypt... yes
checking for dirent.h that defines DIR... yes
checking for opendir in -ldir... no
checking for paths.h... yes
checking for netinet/in.h... yes
checking for sys/time.h... yes
checking for time.h... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for sys/socket.h... yes
checking for asm/socket.h... yes
checking for wait.h... no
checking for sys/wait.h... yes
checking for shadow.h... yes
checking for arpa/inet.h... yes
checking for syslog.h... yes
checking for crypt.h... yes
checking for utmp.h... yes
checking for sys/sendfile.h... yes
checking whether to enable pam... no
checking whether to enable libz... yes
checking for zlib.h... yes
checking whether to enable debug... no
updating cache ./config.cache
creating ./config.status
creating Makefile
creating config.h

==> bftpd__pre-build_02-script-wrapper.log

==> bftpd__pre_build.log

==> bftpd__do_build.log
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o bftpdutmp.o bftpdutmp.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o commands.o commands.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o commands_admin.o commands_admin.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o cwd.o cwd.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o dirlist.o dirlist.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o list.o list.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o login.o login.c
login.c: In function 'checkshell':
login.c:629:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (!strcasecmp(config_getoption("AUTH_ETCSHELLS"), "no"))
     ^~
login.c:632:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  pwd = getpwnam(user);
  ^~~
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o logging.o logging.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o main.o main.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o mystring.o mystring.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o options.o options.c
cc -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -DHAVE_CONFIG_H -Wall -I. -DVERSION=\"4.8\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DPREFIX=\"/usr\"       -c -o md5.o md5.c
./mksources 
cc bftpdutmp.o commands.o commands_admin.o cwd.o dirlist.o list.o login.o logging.o main.o mystring.o options.o md5.o  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed     -lcrypt -lz -o bftpd

==> bftpd__do_check.log
make: *** No rule to make target 'check'.  Stop.
[1m[31m=> ERROR: bftpd-4.8_1: failed to run do_check() at line 20.
[m

**Comment by ebfe** [comment]
> autoconf create a dummy check target that always works

autoconf doesn't create make targets. automake would, but isn't used here.

**Comment by maxice8** [comment]
Ok so how do we deal with packages that use gnu-configure but don't provide make check or any tests that can be directed at all, declare `do_check() { : ; }` ?
