### ISSUE TITLE
SyntaxError: invalid syntax on python-Cheroot update

### ISSUE THREAD

**Issue by direwolfie** [voidlinux/void-packages#9383]
### Issue
Seeing following on update:
```
python-Cheroot-5.9.1_1: configuring ...
Byte-compiling python2.7 code for module cheroot...
Compiling usr/lib/python2.7/site-packages/cheroot/test/test_core_BACKUP_1440.py ...
  File "usr/lib/python2.7/site-packages/cheroot/test/test_core_BACKUP_1440.py", line 13
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

Updating ldconfig(8) cache...
python-Cheroot-5.9.1_1: updated successfully.
```

### Steps to reproduce the behavior
Update system that has python-Cheroot package installed.
Version from -> to:
`python-Cheroot  update    5.9.0_1     ->    5.9.1_1                46KB `

**Comment by maxice8** [comment]
Installing python-Cherrot-5.10.0 seems to have it fixed

**Comment by direwolfie** [comment]
Thanks. Seems so.
Did not see errors during install of `python-Cherrot-5.10.0`.
