### ISSUE TITLE
Qt5 is missing

### ISSUE THREAD

**Issue by newbluemoon** [voidlinux/void-packages#9403]
Reverting Qt5 from revision 9 to 8 in commit https://github.com/voidlinux/void-packages/commit/b8f81f8ad1c5913dba71b3a2843ed03b512b3871 leaves revison 9 registered in the repos, but building packages with xbps-src requests revision 8, cannot find it for platforms other than x86_64 and starts building Qt5.

In repo 1 and 3, for example, revision 8 doesn’t even exist for armv6l, armv7l, and i686 anymore, only 9.

**Comment by ebfe** [comment]
```
      armv6l | qt5-5.8.0_9
      armv7l | qt5-5.8.0_9
        i686 | qt5-5.8.0_9
 armv6l-musl | qt5-5.8.0_9
      x86_64 | qt5-5.8.0_8
 armv7l-musl | qt5-5.8.0_8
 x86_64-musl | qt5-5.8.0_8
     aarch64 | qt5-5.8.0_8
aarch64-musl | qt5-5.8.0_8
```

**Comment by ebfe** [comment]
b8f81f8ad1c5913dba71b3a2843ed03b512b3871 says build fails with a compiler eroor. Not sure how to fix this if the build fails, other than removing the packages from repo/index manually.

**Comment by pullmoll** [comment]
We need to clean up the builders. I think it was actually an out of disk space error, at least in one case.
I would then try to re-apply the patch. Everything built fine locally.

**Comment by pullmoll** [comment]
I could also re-apply it now and, if it fails again, wait for the person in charge for the builders to purge them.

**Comment by pullmoll** [comment]
See https://build.voidlinux.eu/changes/13102 - if this fails we have a seriouse problem, because we can't add a reverts= either as long as the builders fail to build qt5-5.8.0.

**Comment by pullmoll** [comment]
- [ ] x86_64-musl fails compiling `src/3rdparty/chromium/third_party/WebKit/Source/core/gen/blink/bindings/core/v8/webcore_generated.V8GeneratedCoreBindings13.cpp`
    I'll try to extract that file from a local build for closer inspection.
- [ ] armv7l-musl fails linking `libQt5WebEngineCore.so.5.8.0`
    Perhaps a memory problem.
- [ ] armv6l-musl also fails compiling `src/3rdparty/chromium/third_party/WebKit/Source/core/gen/blink/bindings/core/v8/webcore_generated.V8GeneratedCoreBindings13.cpp`

**Comment by ebfe** [comment]
Something strange is going on in the i686 repo:

        i686 | qt5-websockets-5.8.0_9
        i686 | qt5-websockets-devel-5.8.0_8

**Comment by cr6git** [comment]
Me I got this error: 
````
$ sudo xbps-install -S qt5-declarative
[*] Updating `https://repo.voidlinux.eu/current/musl/x86_64-musl-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/musl/nonfree/x86_64-musl-repodata' ...

Name            Action    Version           New version            Download size
qt5-xmlpatterns install   -                 5.8.0_9                898KB 
qt5-declarative install   -                 5.8.0_9                2802KB 

Size to download:             3700KB
Size required on disk:          19MB
Free space on disk:           6456MB

Do you want to continue? [Y/n] y

[*] Downloading binary packages
ERROR: [trans] failed to download `qt5-xmlpatterns-5.8.0_9' package from `https://repo.voidlinux.eu/current/musl': Not Found
````

**Comment by ebfe** [comment]
@pullmoll I'd suggest we mark qt5 broken for now, drain the builder queue. Let people make space on the builders and try again with a _10 on otherwise idle builders?

**Comment by newbluemoon** [comment]
The the most recent i686 rebuild is from 22-Nov-2017 04:24, but has revision 8.
One exception stands out: qt5-websockets-devel-5.8.0_8.i686.xbps is from 21-Nov-2017 15:26.
Revision 9 is from 20-Nov-2017. I guess this is @pullmoll’s build.

**Comment by pullmoll** [comment]
@ebfe yes, go for it. I'll be busy for some time now, then away and back in the early afternoon.

@Gottox asked to make a PR to allow scheduling for the musl builders, but to achieve this it would need to mark arches broken and then enable one after another. Not sure how this would work out.

**Comment by pullmoll** [comment]
@newbluemoon the latest the i686 builder was doing was still qt5-5.8.0_8. It seems it has a difficult time to catch up on the pending kernel updates etc. and rebuilds qt5 for every pkg that depends on it.

**Comment by Gottox** [comment]
The idea was, that we disable the builders on the build servers and just enable them one by one so that the qt builds aren't processed in parallel.

**Comment by pullmoll** [comment]
So for which architectures is qt5-5.8.0_9 built already?
Looking at https://repo.voidlinux.eu/current/ I see
- [x] x86_64
- [x] i686
- [x] armv6l
- [x] armv7l

Looking at https://repo.voidlinux.eu/current/musl/
- [x] armv6l-musl
- [x] armv7l-musl
- [x] x86_64-musl

Looking at https://repo.voidlinux.eu/current/aarch64/
- [ ] aarch64
- [x] aarch64-musl

This leaves aarch64 to be done which failed due to insufficient disk space.

**Comment by ebfe** [comment]
@pullmoll i don't think the _9 builds are reliable. Note that there are subpackages missing on at least x86_64-musl, and i686 has mixed revisions.

**Comment by pullmoll** [comment]
Oh, I see. Then the builders should be purged, qt5 revbumped and @Gottox idea of disabling and enabling one after another be scheduled.

**Comment by pullmoll** [comment]
BTW when revbumping we could change the template to enable -silent and disable -v in the opts+= in do_configure().

**Comment by xtraeme** [comment]
I think the real fix is moving generated pkgs to a temporary path and
then when all subpkgs are built move them to the final destination.

2017-11-23 11:51 GMT+01:00 Jürgen Buchmüller <notifications@github.com>:

**Comment by pullmoll** [comment]
@ebfe x86_64-musl seems to be alright. I installed a VM with Void x86_64-musl and a base image, then qtcreator-full which pulls in (almost) all qt5 packages and it worked. Perhaps the x86_64-musl anomaly was due to only partial synchronization of the musl builder(s) with the repo?

**Comment by ebfe** [comment]
> Perhaps the x86_64-musl anomaly was due to only partial synchronization of the musl builder(s) with the repo?

Yes, looks like that is the case. qt5-xmlpatterns, which was previously
missing, is there now.

**Comment by pullmoll** [comment]
@xtraeme Regarding temporary paths, I don't know the (virtual) disk layout of the builders. If there isn't sufficient space on a single mount point, then moving files around changes nothing. Qt5 is a beast - IIRC it takes > 20GB close to the end of the build steps.

I tried to split qt5 months ago but failed because of not getting cross builds done. It would have reduced the impact on builders a little with qt5-webengine still being a beast.

With qt5-5.9.2 (or qt5-5.10 which is to be expected in a couple of days) things won't get easier for the builders. Besides that there is the problem that x86_64 building armv[56]l cross does no longer work, but i686 building armv[56]l cross does.

**Comment by newbluemoon** [comment]
I think this can be closed now.
