### ISSUE TITLE
linux-lts release plan for January

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#9411]
In January, I'd like to bump linux-lts to kernel 4.14 (or whatever else is deemed to be next LTS then),
so people doing a default install of linux-lts will not get an already 2 year old kernel.

The linux-4.4 package will not go away.

**Comment by cr6git** [comment]
Interesting, Slackware had experienced some difficulty in upgrading to 4.14, as we can see in the [changelog](http://www.slackware.com/changelog/current.php?cpu=x86_64)... 

Sat Dec 2 20:32:45 UTC 2017
We're moving back to the 4.9.x kernel series in the main tree until we can
figure out a fix for unstable 4.14.x kernels (especially on 32-bit).

**Comment by cr6git** [comment]
Arch recently added a [patch](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/linux&id=e42e6ffc6243370215eb33690b3c68f96f181cdb) for 4.14 to "disallow unprivileged `CLONE_NEWUSER`". 
However it breaks [xbps-uunshare](https://github.com/voidlinux/void-packages#xbps-uunshare1).

**Comment by chneukirchen** [comment]
I suggest we do that bump when 4.9 gets KPTI backported.

**Comment by chneukirchen** [comment]
I decided to bump to 4.9 only so far.
