### ISSUE TITLE
xbps-src: using build_options drops default flags if CFLAGS are set

### ISSUE THREAD

**Issue by ebfe** [voidlinux/void-packages#9454]
```
[...]
CFLAGS=foo
do_build() {
        echo $CFLAGS
}
[...]

```

```
$ ./xbps-src build a
[...]
=> a-1.0_1: running do_build ...
-D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe foo
```

```
$ ./xbps-src -g build a
[...]
=> a-1.0_1: running do_build ...
-D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe foo -g
```

Add a build_option
```
[...]
build_options="bar"
CFLAGS=foo
do_build() {
        echo $CFLAGS
}
[...]

```

```
$ ./xbps-src -g build a
[...]
=> a-1.0_1: running do_build ...
-D_FORTIFY_SOURCE=2 foo
```

**Comment by ebfe** [comment]
Using build_options causes the template to be sourced a second time, so this could be called a bug in the template. However tons of templates use this...

**Comment by pullmoll** [comment]
This is due to the `XBPS_BUILD_OPTIONS_PARSED` hack in `common/xbps-src/shutils/common.sh:set_build_options()`. Perhaps this recursive call can be run in a separate shell and the result echoed and assigned in the call instead of exported to `PKG_BUILD_OPTIONS ` at the end of the function!?

**Comment by ebfe** [comment]
I'm not sure if it is easy, because i think that part is also responsible for evaluation all the `$(vopt_if ...)`.

**Comment by pullmoll** [comment]
Hmm.. if the last line of that function is just
```
echo "$PKG_BUILD_OPTIONS"|tr ' ' '\n'|sort|tr '\n' ' '
```
and the call like
```
export PKG_BUILD_OPTIONS="$(set_build_options)"
```
shouldn't the separate shell inherit everything necessary and the echoed string contain everything that's actually changed, i.e. just the sorted PKG_BUILD_OPTIONS?
I admit I haven't tried...

**Comment by xtraeme** [comment]
A subshell for this case seems to be a good idea...

thanks!

2017-11-22 21:56 GMT+01:00 Jürgen Buchmüller <notifications@github.com>:

**Comment by ebfe** [comment]
Hmm, maybe i miss something, but how does configure_args get the right value if the second evaluation happens in a subshell in this case:

```
configure_args=$(vopt_if foo bar)
build_options="foo"
build_options_default="foo"
```

**Comment by pullmoll** [comment]
Exactly, see my edit. I was under the false impression that PKG_BUILD_OPTIONS would be the only variable which the recursive call changed. So @xtraeme no, this was no good idea at all :)

**Comment by ebfe** [comment]
Moving `set_build_options` before the default CFLAGS are set in `setup_pkg` might work, but it's unclear where the right place is.
