### ISSUE TITLE
Package update: john 1.8

### ISSUE THREAD

**Issue by radare** [voidlinux/void-packages#946]
Current package is 1.7.9-jumbo, but latest release is 1.8.0-jumbo. Looks like the entire build system has changed (now it's based on autotools), but seems to use C_Block which is not available in LibreSSL?

```
# Template file for 'john'
pkgname=john
version=1.8.0
_jumbover=1
revision=1
wrksrc="${pkgname}-${version}-jumbo-${_jumbover}/src"
hostmakedepends="libgomp-devel"
makedepends="zlib-devel libgomp-devel libressl-devel>=2.1.3"
conf_files="/etc/john/john.conf"
short_desc="John the Ripper password cracker (jumbo-${_jumbover} patch included)"
maintainer="Juan RP <xtraeme@gmail.com>"
license="GPL-2"
build_style=gnu-configure
homepage="http://www.openwall.com/john/"
distfiles="$homepage/j/$pkgname-${version}-jumbo-${_jumbover}.tar.xz"
checksum=bac93d025995a051f055adbd7ce2f1975676cac6c74a6c7a3ee4cfdd9c160923
nocross=yes
```

Also, why it is marked as nocross? it would be interesting to have support to build support for CUDA/OPENCL as an option. and also to crosscompile statically against musl for mips.

thanks

**Comment by chneukirchen** [comment]
Updated to 1.8, CUDA/OPENCL not done yet because I don't know jack about that stuff.
