### ISSUE TITLE
Package request: Orion

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#9524]
I dont know if anyone is interested in picking up https://alamminsalo.github.io/orion/ but here it is

**Comment by maxice8** [comment]
I might take this up since i use twitch to see csgo streams. will be leaving to take friends to another city and will be back to try to make a template for it in around 5 hours.

**Comment by Thunderbottom** [comment]
Okay, the package builds and works fine on x86_64 at least. Submitted a PR for it.
