### ISSUE TITLE
[Request] Free Orion 

### ISSUE THREAD

**Issue by codingHahn** [voidlinux/void-packages#9526]
FreeOrion is a 4x space strategy sim. Github repo: https://github.com/freeorion/freeorion Website: http://www.freeorion.org/index.php/Main_Page
The page about compiling: http://www.freeorion.org/index.php/Compile

**Comment by cr6git** [comment]
I created a template. 
I am currently compiling the program on my laptop, but this is so heavy that my CPU is in trouble! 
Please be patient. 😉

**Comment by codingHahn** [comment]
Thank you. No worry, I'll be

**Comment by cr6git** [comment]
@codingHahn done!
