### ISSUE TITLE
Steam: Not starting at all

### ISSUE THREAD

**Issue by necrophcodr** [voidlinux/void-packages#953]
So, after a recent update as of today (7th of February 2015), there seems to be no support for running Steam anymore. Given that it is a 32bit application, and that other 64bit applications function just fine, it seems to be an issue with some 32bit system.

Running
    $ STEAM_DEBUG=1 steam

Results in the following (pasted) output:

http://dpaste.com/3HTGFDA

**Comment by logenkain** [comment]
On Sat, Feb 07, 2015 at 01:12:42PM -0800, necrophcodr wrote:
> So, after a recent update as of today (7th of February 2015), there seems to be no support for running Steam anymore. Given that it is a 32bit application, and that other 64bit applications function just fine, it seems to be an issue with some 32bit system.

I updated and ran steam today, opened up a game of Euphloria HD.
Everything ran fine.

I took a look at your report after this, it looks like you are having an
issue with your graphics.  I'm running on intel drivers for an hd3000.
No problems.

My desktop is using AMD proprietary drivers, testing steam now...

Steam loaded properly and I started a game of Serious Sam 3.

Looks like this is a local issue, make sure you have all your 32-bit
drivers.

I am also able to run Eve via wine(32 bit) with no problems.

Looks to me that those last 5 issues are noting a problem with swrast.
I seem to remember having a swrast issue in the past on AMD... but I
can't remember what it was or how I fixed it.

Good luck.

**Comment by xtraeme** [comment]
I'm able to run doom3-32bit with the Intel GPU (integrated) and with the Radeon HD770 via DRI_PRIME.

Looks like your issue is that the Steam bootstrap was installed and the libstdc++ supplied with it is incompatible with ours (ubuntu 12.02 uses gcc-4.7).

See this one and check if that fixes steam for you: https://bbs.archlinux.org/viewtopic.php?id=181743

**Comment by necrophcodr** [comment]
Not sure what caused this bug to return to the system, but it fixed the issue by removing (or moving) that file. (libstdc++.so.6)

I suppose this is not a bug related to Void Linux anyway, but thanks for the help!

**Comment by xtraeme** [comment]
This is not our problem. It will happen each time steam is updated to a new version and its ubuntu 12.02 bootstrap packages are updated.

Tell them to switch to a newer ubuntu version!

**Comment by necrophcodr** [comment]
Yeah, either that, or default to running with STEAM_RUNTIME=0. That *might* work too, although I haven't really tested it (relying on vague documentation from around the net).
