### ISSUE TITLE
VLC: Interface distorted. 100% cpu. Will "almost" not be killed.

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#9535]
### System

* xuname: Void 4.14.2_1 x86_64-musl GenuineIntel uptodate rF
* package: vlc 2.2.6

### Expected behavior
Open interface.
### Actual behavior
Interface opens but is distorted looking and utilises 100% cpu of one core. pkill does not work but has to be killed through mate-monitor.
### Steps to reproduce the behavior
Start VLC.

**Comment by cr6git** [comment]
### System

* xuname:  Void 4.13.15_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFFFFFFFFFFF

* package:  vlc-2.2.6_2

### Actual behavior
is working perfectly.

**Comment by Anachron** [comment]
Can you tell us what `ps -edalf | grep $(pgrep vlc)` shows for this process?

**Comment by 38github** [comment]
I will test later today when I have got time. Thanks for the support!

Den 27 nov. 2017 11:15 skrev "Anachron" <notifications@github.com>:

**Comment by 38github** [comment]
Anachron: That command only gives me:
$ ps -edalf | grep $(pgrep vlc)
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.

**Comment by 38github** [comment]
Sorry. I didn't understand that I had to have VLC running.

0 S voiduser       2646  1711 99  80   0 - 73058 -      02:02 ?        00:00:03 /usr/bin/vlc --started-from-file
0 S voiduser       2657  2585  0  80   0 -   902 -      02:02 pts/0    00:00:00 grep 2646

**Comment by Vaelatern** [comment]
Can you `strace` the process?

**Comment by 38github** [comment]
I straced it somehow it works today. I don't know if some package has been updated that affects VLC but at least it works now and files are played. Also the annoying system tray icon that won't go away is now working as it is intended.

**Comment by cr6git** [comment]
Hey have you noticed this patch in Arch: [vlc-2.2.6-fix-memleak.patch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/vlc-2.2.6-fix-memleak.patch?h=packages/vlc) ? 
Is it relevant ?
