### ISSUE TITLE
Pulseaudio: include soxr resample method

### ISSUE THREAD

**Issue by 38github** [voidlinux/void-packages#9537]
### System

* xuname: Void 4.14.2_1 x86_64-musl GenuineIntel uptodate rF
* package:  pulseaudio

### Expected behavior
Being able to use resample-methods soxr-mq soxr-hq and soxr-vhq
### Actual behavior
"pulseaudio --dump-resample-methods" shows no soxr options
### Steps to reproduce the behavior
pulseaudio --dump-resample-methods

**Comment by cr6git** [comment]
The solution is to add `libsoxr-devel` to the [makedepends](https://github.com/voidlinux/void-packages/blob/master/srcpkgs/pulseaudio/template#L13).

**Comment by cr6git** [comment]
I wonder what `--disable-systemd` is supposed to do ? 
````
=> pulseaudio-11.1_1: running do_configure ...
configure: WARNING: unrecognized options: --disable-systemd
````

**Comment by 38github** [comment]
On a fedora's/redhat's bugzilla i found that it disables optional systemd daemon (socket activation) support. I have no clue myself what that really means.

**Comment by cr6git** [comment]
I will look into it, but at the moment my cpu is busy compiling another package... you'll have to wait.
