### ISSUE TITLE
[wicd] Unable to configure wireless network

### ISSUE THREAD

**Issue by srlang** [voidlinux/void-packages#954]
When attempting to configure options for a new (my home) network, wicd-curses exits with a dbus error (I will post exact errors soon)

This has happened since the upgrade from 1.7.2 to 1.7.3_2 

Steps:
1. open up wicd-curses
2. highlight the specific network broadcasting
3. press the right arrow key to attempt to edit configuration options (e.g. passphrase)
4. Failure occurs

**Comment by srlang** [comment]
`wicd-curses --version`
`wicd-curses-uimod (using wicd 1.7.3)`, package version 1.7.3_2

stderr captured:
```
Traceback (most recent call last):
  File "/usr/share/wicd/curses/wicd-curses.py", line 1146, in call_update_ui
    self.update_ui(True)
  File "/usr/share/wicd/curses/wicd-curses.py", line 97, in wrapper
    return func(*args, **kargs)
  File "/usr/share/wicd/curses/wicd-curses.py", line 1159, in update_ui
    self.handle_keys(input_data)
  File "/usr/share/wicd/curses/wicd-curses.py", line 1037, in handle_keys
    self.diag = WirelessSettingsDialog(pos, self.frame)
  File "/usr/share/wicd/curses/netentry_curses.py", line 503, in __init__
    self.set_values()
  File "/usr/share/wicd/curses/netentry_curses.py", line 543, in set_values
    wireless.GetWirelessProperty(networkID, 'bitrate')
ValueError: None is not in list
```

**Comment by srlang** [comment]
Also of note because it was asked on tthe IRC channel:

using `python-urwid-1.3.0_1`

**Comment by xtraeme** [comment]
Can you verify if this commit https://github.com/voidlinux/void-packages/commit/3e5c66a3c15b256987d7ceefb36003b770720414 fixes it?

**Comment by srlang** [comment]
Issue is not fixed; still present after commit 3e5c66a
Problem presented itself in Arch distro as well, so I will be reporting it to their bug-tracker as well.

**Comment by heben2** [comment]
I get the exact same crash/bug

**Comment by Duncaen** [comment]
@heben2 @srlang should be fixed now, i can select a network and go to settings without crashing.
Please confirm further, i dont use wicd myself.

**Comment by srlang** [comment]
works as of wicd-1.7.3_4

**Comment by heben2** [comment]
Is this getting released on Arch soon? Maybe this is the wrong place to ask?

**Comment by xtraeme** [comment]
We are not Arch... wrong site to ask.

**Comment by heben2** [comment]
Yep, thought so - but thanks for correcting the error nonetheless

**Comment by spreadpanic** [comment]
@heben2 A patch is available in the AUR: https://aur.archlinux.org/packages/wicd-patched/

I've updated the Arch's wiki.
