### ISSUE TITLE
Package request: Xiki shell

### ISSUE THREAD

**Issue by icf20** [voidlinux/void-packages#9566]
https://github.com/trogdoro/xiki  

I bet people who do allot of things on ruby will love this

**Comment by Anachron** [comment]
Looks like another program that wants to do everything... I don't like, but maybe someone else wants to package it.

**Comment by Vaelatern** [comment]
I read that article too!

**Comment by aeosynth** [comment]
last commit on Nov 16, 2016
last release on Aug 28, 2012
