### ISSUE TITLE
gajim: broken with python-openssl-17.4.0

### ISSUE THREAD

**Issue by Hoshpak** [voidlinux/void-packages#9571]
### System

* xuname:  
  Void 4.14.2_1 x86_64 GenuineIntel notuptodate hold rrrmDDDDDDFFF
* package:  
  gajim-0.16.8_1

### Expected behavior
gajim should start when the command is executed.

### Actual behavior
Crash with backtrace:

```
Traceback (most recent call last):
  File "gajim.py", line 307, in <module>
    OpenSSL.rand.load_file(str(RNG_SEED))
AttributeError: 'module' object has no attribute 'load_file'
```

This issue seems to be caused by the partial re-add of OpenSSL.rand in python-openssl-17.4.0. [Upstream bug report](https://dev.gajim.org/gajim/gajim/issues/8788) for reference.

### Steps to reproduce the behavior

Install gajim, try to execute it.

**Comment by maxice8** [comment]
https://forum.voidlinux.eu/t/gajim-attributeerror-module-object-has-no-attribute-load-file/3956/2

**Comment by Hoshpak** [comment]
proposed workaround in #9576

**Comment by Hoshpak** [comment]
workaround has been merged

**Comment by gnutechs** [comment]
This workaround doesn't exactly fix it for me. I can start gajim now but I can't sign in.
Upstream's solution: https://dev.gajim.org/gajim/gajim/commit/3dd35f5e762dcef2cf05e325705d0e7a2db21917

**Comment by Hoshpak** [comment]
Are you sure that this is caused by the workaround and not yet another issue caused by the python-openssl update? The workaround only changes the behaviour to match the one if Openssl.rand wasn't available so it would surprise me if that would cause your issues. Specifically someone else already reported an issue which seems to boil down to a bug in python-openssl: https://github.com/pyca/pyopenssl/issues/722 .
