### ISSUE TITLE
FreeOrion doesn't show build number

### ISSUE THREAD

**Issue by codingHahn** [voidlinux/void-packages#9610]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
Void 4.13.15_1 x86_64 GenuineIntel uptodate rrrm
* package:  
  *affected package(s) including the version*
freeorion-0.4.7.1
### Expected behavior
Show build number in bottom right corner.
### Actual behavior
Shows ```[build ???]```
### Steps to reproduce the behavior
Start the program
### Possible solution
After seeing this error in the buildlog:
```
=> freeorion-0.4.7.1_1: skipping check (XBPS_CHECK_PKGS is disabled) ...
=> freeorion-0.4.7.1_1: running pre-install hook: 00-lib32 ...
=> freeorion-0.4.7.1_1: running pre-install hook: 02-script-wrapper ...
=> freeorion-0.4.7.1_1: running do_install ...
[ 16%] Built target GiGi
WARNING: git not installed or not setup correctly
WARNING: Can't determine git commit!
Writing file: util/Version.cpp
Building v0.4.7.1 build ???
[ 16%] Built target freeorionversion
```
I might suspect that git is missing in the (host)makedeps.

**Comment by Vaelatern** [comment]
Definitely not in the `hostmakedepends`, but it might not work anyway seeing as we don't do a git checkout of the source to build it.

**Comment by cr6git** [comment]
@codingHahn does it prevent you from playing your game ?

**Comment by teh-jazzman** [comment]
I second @Vaelatern since I've compiled the source by hand from a .tar.gz and I got the same warning despite git beeing installed on my system.

**Comment by Vaelatern** [comment]
We can overwrite it if there is a nice way to get the build number.

**Comment by newbluemoon** [comment]
The build number is generated in `cmake/make_versioncpp.py` which creates `util/Version.cpp` from `util/Version.cpp.in`. Checking how this number is composed it seems that it’s the part between the underscores of the source tarball’s filename.

So

```
post_extract() {
        _build_no=${_release/*_/}
        sed -i -e "s|\${FreeOrion_BUILD_NO}|$_build_no|" util/Version.cpp.in
}
```
should set the right build number.
