### ISSUE TITLE
Bluefish lacks zencoding

### ISSUE THREAD

**Issue by stevelitt** [voidlinux/void-packages#9638]
### System

* xuname:  
  *output of ``xuname`` (part of xtools)*
[slitt@mydesk void]$ uname -a
Linux mydesk 4.13.10_1 #1 SMP PREEMPT Sun Oct 29 17:25:31 UTC 2017 x86_64 GNU/Linux
[slitt@mydesk void]$

* package:  
  *affected package(s) including the version*
bluefish-2.2.10_1

### Expected behavior
While editing an xhtml file, if you type h1 and then press the zencoding keycombo (typically Ctrl+Shift+Enter), it fills in the start and end tag, namely, `<h1></h1>`.

### Actual behavior
While editing an xhtml file, if you type h1 and then press the zencoding keycombo, absolutely nothing happens.

### Steps to reproduce the behavior
* Install bluefish.
* Run bluefish
* Dialog->General->Quickstart
* Set DTD to XHTML 1.0 Transitional (I think any DTD will trigger this bad behavior,  but I KNOW xhtml 1.0 Transitional will.
* Click OK
* Save as junk.xhtml
* Edit->Preferences->Editor_settings->Autocompletion_&_references
* View or set the Shortcut key combination
* Between `<body>` and `</body>`, type h1 then press the Shortcut key combination
* Observe that nothing happens, when it *should* change to `<h1></h1>`. 

MORE INFO...
The expected change from h1 to `<h1></h1>` on pressing the Shortcut key combo is a feature called zencoding.
The usual cause of lack of zencoding is failure to compile Bluefish with Python support, but Help->Build shows that you compiled it with Python support. I tried zencoding while watching the stdout of Bluefish, and when I pressed my keycombo (Ctrl+Shift+Enter in my case),I got the following Python error trace:
```
Traceback (most recent call last):
  File "/usr/share/bluefish/plugins/zencoding/__init__.py", line 1, in <module>
    import utils
  File "/usr/share/bluefish/plugins/zencoding/utils.py", line 31, in <module>
    import copy
  File "/usr/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```
Apparently _weakdef is a Python library built in C. 

Edited by @pullmoll: I put backticks (`) around HTML tags and triple backticks (```) in the line before and after the traceback. This is the way to avoid text being interpreted as MD.

**Comment by stevelitt** [comment]
Zencoding means when you press the Shortcut key, after typing h1, the h1 changes to &lt;h1&gt; &lt;/h1&gt;

When writing the symptom description I put in the actual angle brackets, which caused them not to show up.

**Comment by pullmoll** [comment]
You can mark a word and click on the angle brackets icon above the editor, or you can enter backticks around HTML code which is not to be interpreted. You should perhaps read the description linked to at the bottom of the input editor [Styling with Markdown is supported].(https://guides.github.com/features/mastering-markdown/).

**Comment by stevelitt** [comment]
pullmoll, perhaps Bluefish has other ways of doing the same thing, but the fact that it can't turn h1 to &lt;h1&gt;&lt;/h1&gt; after I hit the Shortcut key does not happen on normally compiled versions of Bluefish. I'm not sure what markdown has to do with it, but I use Bluefish because I need full Xhtml capabilities.

**Comment by stevelitt** [comment]
LOL, pullmoll, now I understand what you were saying. Thanks for the tip about using those little htmlhelpers in the bar atop the edit area of this bug tracker. I'll try those out: They look pretty cool. Thanks!

**Comment by pullmoll** [comment]
Ok, you got it :) For the problem itself I have no real idea.
I am not the Python nerd around here and can only imagine that perhaps some dependency is missing.

**Comment by chneukirchen** [comment]
Does `python2 -m weakref` terminate without error/output?

**Comment by chneukirchen** [comment]
Fixed now.
