### ISSUE TITLE
gst-plugins-bad1: needs to update common/shlibs

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9642]
### System

* xuname:  `Void 4.13.15_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFFFFFFFFFFFFF`

* package:  `gst-plugins-bad1-1.12.3_2`

### Actual behavior
Errors, because `common/shlibs` needs to be updated.
### Steps to reproduce the behavior
Just try to build the package... 
````
=> gst-plugins-bad1-1.12.3_2: running pre-pkg hook: 99-pkglint ...
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstinsertbin-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstbadaudio-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstbadvideo-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstbadbase-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstmpegts-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstadaptivedemux-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstplayer-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstbadallocators-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgsturidownloader-1.0.so.0 not found in common/shlibs!
=> WARNING: gst-plugins-bad1-1.12.3_2: libgstwayland-1.0.so.0 not found in common/shlibs!
````

How is that possible ?

**Comment by Duncaen** [comment]
Its just a warning, if there is nothing that need to link the listed shared libraries, they don't need to be added to `common/shlibs`, those are plugins which are loaded by `gstreamer1` as far as I know.

**Comment by cr6git** [comment]
ok... I was very surprised because this is the first time I see such error...
I'm trying to create a new package for [pulseeffects](https://github.com/wwmm/pulseeffects) and it needs to link to gstreamer to work. 

In fact `pulseeffects` needs `GstInsertBin` to get built (see [comment](https://github.com/wwmm/pulseeffects/issues/22#issuecomment-347897269)) , so I must modify the template to add `gobject-introspection`.

I hope it's ok ?
