### ISSUE TITLE
rfkill package still included and can crash system.

### ISSUE THREAD

**Issue by scottro11** [voidlinux/void-packages#9652]
### System

* xuname:  
Void 4.13.15_1 x86_64 GenuineIntel
 
* package:  
rfkill
  

### Expected behavior
To not crash the system

### Actual behavior
crashes system

### Steps to reproduce the behavior
See https://forum.voidlinux.eu/t/package-removal-crashes-system/4012/5
If a user doesn't realize, after installation, that rfkill is already provided by util-linux, and installs rfkill with xbps-install -S rfkill, upon the next boot, the system will fail to boot.  The rfkill package should be purged from the repository.

**Comment by chneukirchen** [comment]
Removed now.

**Comment by scottro11** [comment]
Great, thanks for the quick action.

**Comment by aproto** [comment]
This is still an issue at least in the musl version. I just did a fresh chroot install, added a user, and installed my list of packages which included rfkill. Rebooted, crashed, and was dropped into recovery shell. There should be an RSS feed or mailing list for system breaking bugs if there isn't already.
