### ISSUE TITLE
freshplayerplugin is broken on musl ?

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9656]
### System

* xuname:  `Void 4.13.15_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFFFFFFFFFFFFFFFF`

* package:  `freshplayerplugin`

### Actual behavior
seems like it's broken.
### Steps to reproduce the behavior
````
$ sudo xbps-install freshplayerplugin
freshplayerplugin-0.3.5_3: broken, unresolvable shlib `libevent-2.0.so.5'
freshplayerplugin-0.3.5_3: broken, unresolvable shlib `libevent_pthreads-2.0.so.5'
Transaction aborted due to unresolved shlibs.
````

**Comment by cr6git** [comment]
Yes, broken for now, see [commit](https://github.com/voidlinux/void-packages/commit/b109fa04338dad286355dde0b4a6d88b3e2b9297) ...

**Comment by Duncaen** [comment]
There is no flash for musl, why would you need `freshplayerplugin`.
And in general, adobe is distributing npapi and ppapi plugins again.
Firefox (removed?) npapi support and chrome doesn't ship pepperflash as a shared library anymore.

**Comment by cr6git** [comment]
You're right, `adobe-flash-plugin` is `only_for_archs="i686 x86_64"`.
It should be the same for `freshplayerplugin`.

**Comment by cr6git** [comment]
Mystery solved, I guess we can close this then. 😉
