### ISSUE TITLE
xbps-pkgdb -m hold Not Working

### ISSUE THREAD

**Issue by Antonio-Malcolm** [voidlinux/void-packages#967]
Attempting a dist-update, via xbps-install -Syuv, resulted in a conflict error involving xorg-server (will file a separate issue for that), so I ran xbps-pkgdb -m hold xorg-server, in hopes to update the rest of the system, but that did not work. I still receive the conflict error, and it refuses to update the rest of the system.

**Comment by xtraeme** [comment]
I'd like to see output of the affected commands with `-d` (debug).

**Comment by xtraeme** [comment]
If you are still able to reproduce this issue please re-submit it to the correct repository: https://github.com/voidlinux/xbps
