### ISSUE TITLE
linux-firmware is outdated

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9687]
### System

* package:  `linux-firmware-20170622`

### Actual behavior
Some users have reported problems with WiFi, frequent connection loss. 
This is a known issue, see [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=96a7402d4172f4786ee93dd9f7cb3f76e1a8025e) for reference. 
The package needs to be updated.

**Comment by jsumners** [comment]
I came here to file an issue about the ath10k firmware, so this seems like a good thread to do it in. I have had an issue for many months where new kernels cause the `ath10k_pci` driver to crash. I can boot normally, and have a working wifi card, with kernel "4.8.17_1 #1 SMP PREEMPT Mon Jan 9 08:32:27 UTC 2017 x86_64 GNU/Linux".

This system is an HTPC, and thus 1. not updated too often and 2. very difficult to get data from. So the attached picture is as good as I can do. I tried https://wireless.wiki.kernel.org/en/users/drivers/ath10k/debug#firmware_crash_dump_file but it results in nothing.

![img_2085](https://user-images.githubusercontent.com/321201/33510170-dd51d28a-d6d6-11e7-8174-c346b715a2cc.JPG)

**Comment by cr6git** [comment]
Confirmed: see [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=18d71a812f620edc3f702581e7ebee7c713493fd). 
10.2.4.70.63-2 was buggy.

**Comment by xtraeme** [comment]
Updated to the latest revision with https://github.com/voidlinux/void-packages/commit/4266371fa658b72ecfa82d109d4ff5daaef213d9

Thanks!

**Comment by jsumners** [comment]
Thanks guys, it's working fantastically now.
