### ISSUE TITLE
Security flaws in vlc

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9700]
### System

* package:  `vlc-2.2.6`

### Actual behavior
Security flaws, see the Arch [Security Tracker](https://security.archlinux.org/package/vlc) for example. 

Seems like it's fixed in version 2.2.7 (released 15-Nov-2017). 
There is even a newer version 2.2.8 (released 21-Nov-2017). 
It's time to update.

**Comment by codingHahn** [comment]
Working on it

**Comment by codingHahn** [comment]
I have encountered a problem. Whenever I try to build vlc of any version I see this error:
```
=> vlc-2.2.6_2: installing target dependency 'x265-devel-2.4_2' ...
/void-packages/common/xbps-src/shutils/common.sh: line 31: cd: /builddir/vlc-2.2.6: No such file or directory
=> ERROR: vlc-2.2.6_2: cannot access wrksrc directory [/builddir/vlc-2.2.6]
```
I am using the "proot" method, because the others don't work for me.

**Comment by cr6git** [comment]
`proot` ? I don't know, never used...

**Comment by Vaelatern** [comment]
just for sanity sake, make sure `void-packages/masterdir/builddir` exits?

**Comment by codingHahn** [comment]
@Vaelatern it exists with all subfolders. As its impossible for me to do this issue, I propose that somebody else does this.

PS: if it helps, I build on the voidlinux/voidlinux docker image fully updated

**Comment by jnbr** [comment]
see #9952

**Comment by cr6git** [comment]
thanks @jnbr
