### ISSUE TITLE
Package Request: Firejail

### ISSUE THREAD

**Issue by pulux** [voidlinux/void-packages#974]
Firejail is a sandbox program that reduces the risk of security breaches by restricting the running environment of untrusted applications using Linux namespaces. It currently implements hostname, filesystem, PID, IPC and networking stack isolation, and it runs on any recent Linux system. It includes a sandbox profile for Mozilla Firefox.

Code: http://sourceforge.net/projects/firejail/

**Comment by Duncaen** [comment]
Added https://github.com/voidlinux/void-packages/blob/master/srcpkgs/firejail/template and disabled seccomp for arm
