### ISSUE TITLE
Chromium missing valuable security patches

### ISSUE THREAD

**Issue by jmfgdev** [voidlinux/void-packages#9745]
Chromium is pretty far behind other distros, on OpenSuse
it's on version 62, same with Debian, I think the list of CVEs would be quite long.

**Comment by cr6git** [comment]
duplicate of [#8930](https://github.com/voidlinux/void-packages/issues/8930).

**Comment by Vaelatern** [comment]
Feel free to contribute patches so it works on `musl`.

**Comment by Duncaen** [comment]
https://github.com/voidlinux/void-packages/commit/53fed9bb202bdbd80a24b2f4095bf458ae14102a

**Comment by jmfgdev** [comment]
Nicely done 👌
