### ISSUE TITLE
docker-17.11.0_1 problems with cgroups

### ISSUE THREAD

**Issue by iaroki** [voidlinux/void-packages#9811]
### System

* xuname:  
Void 4.13.15_1 x86_64 AuthenticAMD notuptodate hold rrFF
* package:  
docker-17.11.0_1

### Expected behavior
Docker should create and run containers from images
### Actual behavior
Docker daemon starts ok but `docker run` command return error:

```
root:/ >>> docker run -it --rm ubuntu:16.04 bash
docker: Error response from daemon: cgroups: cannot found cgroup mount destination: unknown.
```

### Steps to reproduce the behavior
* Install latest docker-17.11.0_1
* Start docker daemon `sv start docker`
* Run container `docker run -it alpine sh`

### PS

On Void foum users suggested disable and remove `cgmanager` service symlink and this actually solve the problem. But if you do this LXC containers refuse to start and freeze at startup:

```
root:/ >>> lxc-start -n jira -F
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization lxc.
Detected architecture x86-64.

Welcome to CentOS Linux 7 (Core)!

Cannot determine cgroup we are running in: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```

I had to downgrade and hold old __docker-17.09.0_1__ which is perfectly work.
So new __docker-17.11.0_1__ can't work with running __cgmanager__ and __LXC__ can't work without running __cgmanager__.

**Comment by hipperson0** [comment]
When using LXC without `cgmanager` the `/sys/fs/cgroup/systemd` is needed, see this comment on how to create it: https://github.com/voidlinux/void-packages/issues/4018#issuecomment-208353453

**Comment by iaroki** [comment]
This allow me to run docker and lxc without cgmanager, thanks

```
mkdir /sys/fs/cgroup/systemd
mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```

Service `run` cgmanager file contain:

```
#!/bin/sh
sv check dbus >/dev/null || exit 1
exec cgmanager -q -m name=systemd
```

Is this not the same functionality? Then why new docker can't run with `systemd` cgroup created by cgmanager?

**Comment by hipperson0** [comment]
`cgmanager -m name=systemd` didn't create any kind of systemd cgroup for me, it created `/run/cgmanager/fs/none,name=systemd` but I don't know what that does or what its for. 

So I guess that `cgmanager -m name=systemd` is not equivalent to `mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd`

**Comment by iaroki** [comment]
Okay, since cgmanager is old and even LXC devs say it is deprecated what is best option to create and mount `/sys/fs/cgroup/systemd`? Add lines to `/etc/rc.local` or create simple `runit` script?

BTW void kernel compiled with `cgroups v1`. Is there some reason not to use `cgroups v2`?

**Comment by hipperson0** [comment]
I personally would add it as an `/etc/fstab` entry.

I **think** that Void supports both cgroups v1 and v2 as I was able to create a v2 cgroup with  `mount -t cgroup2 none /sys/fs/cgroup/cgroup2` (I don't know if anything else is needed)

I don't know much about cgroupv2, I've seen that there is a lot of debate about it though.

**Comment by iaroki** [comment]
Thanks a lot for help and clarifying things.

**Comment by jkbaseer** [comment]
@iaroki  so which reply is the solution for this? Also if what you have shared about mkdir should be done, do you mind to share at which location we should do this mkdir? 

For your information, am currently on a MEteor app, and getting this error why doing mup deploy with "Prepare bundle Failed"

**Comment by skrzyp** [comment]
This issue still remains and I've just spend about 1,5h to debug it on my work machine.

As it looks like even Docker is systemd-centric-at-any-cost, can't we just patch it around locally?

**Comment by jkbaseer** [comment]
Hey Guys, I have not solved but i started from fresh configuration by opening a new digitalocean droplet. so all good. Thanks @iaroki

**Comment by 4goodapp** [comment]
@iaroki Thanks, this solved the issue for me.

**Comment by ggordan** [comment]
Removing `cgmanager` resolved the issue for me.

**Comment by go2null** [comment]
broken again in latest Void update.

```
sudo mkdir -p /sys/fs/cgroup/systemd
grep 'cgroup/systemd' /etc/fstab >/dev/null 2>& \
  && echo 'cgroup /sys/fs/cgroup/systemd cgroup none,name=systemd 0 0' \
       | sudo tee -a /etc/fstab
sudo mount -a
```

**Comment by Vaelatern** [comment]
Please open an issue against the new repo, @go2null

**Comment by go2null** [comment]
Thanks @Vaelatern. Ticket created, with updated solution that works on reboots.
