### ISSUE TITLE
sway does not start or XDG_RUNTIME_DIR and /run/user/$(id -u)

### ISSUE THREAD

**Issue by giorgiga** [voidlinux/void-packages#9812]
### System

* xuname: 
  * Void 4.14.4_1 x86_64-musl GenuineIntel/KVM notuptodate rF
* package:  
  * sway-0.15.0_1

### Expected behavior

Sway (think "i3 for wayland") should start after installing.

### Actual behavior

Sway does not start, and reports:

`[main.c:48] [wlc] Failed to add socket to wayland display`

### Steps to reproduce the behavior

```
sudo xbps-install -y sway
sway
```
(not sure it matters, but I have only `base-system` and grub installed - ie: no desktop environment of sorts besides sway)

**Comment by giorgiga** [comment]
## Preliminary investigation

Running sway with the `-d` flag, one sees that the error is actually due to sway depending on XDG_RUNTIME_DIR to be set:

```
$ sway -d 2>&1 >/dev/null | tail
I: 12/06/17 14:19:38 - [main.c:207] XKB_DEFAULT_MODEL=(null)
I: 12/06/17 14:19:38 - [main.c:207] XKB_DEFAULT_LAYOUT=(null)
I: 12/06/17 14:19:38 - [main.c:207] XKB_DEFAULT_VARIANT=(null)
I: 12/06/17 14:19:38 - [main.c:207] XKB_DEFAULT_OPTIONS=(null)
D: 12/06/17 14:19:38 - [main.c:52] [wlc] Running on vt 7 (fd 3)
D: 12/06/17 14:19:38 - [main.c:52] [wlc] error: XDG_RUNTIME_DIR not set in the environment

E: 12/06/17 14:19:38 - [main.c:48] [wlc] Failed to add socket to wayland display
D: 12/06/17 14:19:38 - [main.c:52] [wlc] Parent exit (894)
D: 12/06/17 14:19:38 - [main.c:52] [wlc] Restoring vt 7 (0x3) (fd 3)
```

`XDG_RUNTIME_DIR` usually points to a directory `/run/user/$(id -u)`.
`pam_systemd` usually creates the directory and sets the variable during login.

Ref:
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
- http://manpages.ubuntu.com/manpages/xenial/en/man8/pam_systemd.8.html

**Comment by Duncaen** [comment]
There are different ways of doing this, thats why there is no default.
The pam module from the `pam_rundir` package would be one, elogind would be another one.
Or even just setting the variable in your profile works.

**Comment by giorgiga** [comment]
Thanks @Duncaen!

I tried both `pam_rundir` and `elogind`  and, out of the box, neither seems to set `XDG_RUNTIME_DIR`.

Do you think they should? Or should sway depend on some new virtual package "xdg-base-directory" implemented by two "xdg-base-directory-elogind" and "xdg-base-directory-pam_rundir"?

Or... am I getting void linux wrong (hey, I'm new here!) and it's actually ok for a (non-mainstream) package not to work out of the box?

**Comment by Duncaen** [comment]
See `/etc/pam.d/system-login`, the elogind pam module should be loaded by default if installed,
for `pam_rundir` the module needs to be added to the pam module configuration.

No I think, something like `xdg-base-directory` makes a problem that is simple but solved in a complex way even more complex.
And yes, in this case I think its ok that it doesn't work ootb.

**Comment by giorgiga** [comment]
**Closing this issue now**: sway is currently quite experimental and it's fine if it doesn't work (plus, they are refactoring anyway:  swaywm/sway#1390).

As for `pam_elogind`, @Duncaen, I can confirm that the module is set to be loaded in my `/etc/pam.d/system-login`, but still after log in `XDG_RUNTIME_DIR` is not set and no `/run/user/$(id -u)` directory is created.

From `man pam_elogind`:

> [...]
>
> On login, this module — in conjunction with systemd-logind.service —
ensures the following:
>
 > 1. If it does not exist yet, the user runtime directory /run/user/$UID is either created or mounted as new "tmpfs" file system with quota applied, and its ownership changed to the user that is logging in.
>
> [...]

My guess is that it doesn't work because on this virtual machine I'm playing with a super-minimal install and I need some other package on top of elogind:
```
$ xbps-query -m
base-system-0.112_3
elogind-234.4_1
grub-x86_64-efi-2.02_1
```
Do you see any value in me investigating this or can I just forget about it?
(ie: I'll just create my own `XDG_RUNTIME_DIR` since I ~~hate~~ don't care very much about pam, but I'll gladly look into this if you smell it could lead to improving the distro).
