### ISSUE TITLE
keepassxc 2.2.2 does not start

### ISSUE THREAD

**Issue by wesbarnett** [voidlinux/void-packages#9816]
### System

* xuname:  `Void 4.14.4_1 x86_64-musl GenuineIntel uptodate rFF`
* package:  `keepassxc-2.2.2_1`

### Expected behavior

keepassxc should open.

### Actual behavior

keepassxc opens to a black window and does nothing. There don't seem to be any logs or output.

### Steps to reproduce the behavior

Open keepasscx.

**Comment by cr6git** [comment]
### System

* xuname:  `Void 4.14.4_1 x86_64-musl GenuineIntel uptodate rrnFFFFFFFFFFFFFFFFFFFFFFF`
  *output of ``xuname`` (part of xtools)*
* package:  `keepassxc-2.2.2_1`
  *affected package(s) including the version*

### Actual behavior
Oddly enough, it seems to be working for me, see my [screenshot](https://i.paste.pics/2bc192655ff08d3c655e522e0d129a38.png).

**Comment by wesbarnett** [comment]
I wonder if I'm missing some kind of package or video setting. I'm guessing my problem with qutebrowser is the same issue (#9814). That tells me Qt might be the common denominator.

**Comment by wesbarnett** [comment]
I must have had some kind of conflict with one of the mesa packages. I went through and removed all of the `mesa-xxx-dri` packages and this fixed this issue (as well as #9814).
