### ISSUE TITLE
php-7.2.0_1 (update) breaks installed pkg `php-mcrypt-7.1.12_1

### ISSUE THREAD

**Issue by arete** [voidlinux/void-packages#9820]
### System

* xuname:  
   hp-7.2.0_1 (update) breaks installed pkg `php-mcrypt-7.1.12_1'
Transaction aborted due to unresolved dependencies.
Void 4.14.3_1 x86_64 AuthenticAMD uptodate rrrmF

* package:  
  *affected package(s) including the version*
php 7.2.0

### Actual behavior
php modules non in repository
### Steps to reproduce the behavior

xbps-install -Syu
[*] Updating `https://repo.voidlinux.eu/current/x86_64-repodata' ...
x86_64-repodata: 1408KB [avg rate: 978KB/s]
[*] Updating `https://repo.voidlinux.eu/current/multilib/nonfree/x86_64-repodata' ...
[*] Updating `https://repo.voidlinux.eu/current/multilib/x86_64-repodata' ...
x86_64-repodata: 511KB [avg rate: 3779MB/s]
[*] Updating `https://repo.voidlinux.eu/current/nonfree/x86_64-repodata' ...
php-7.2.0_1 (update) breaks installed pkg `php-mcrypt-7.1.12_1'
Transaction aborted due to unresolved dependencies.

**Comment by maxice8** [comment]
Just remove php-mcrypt it was removed upstream, same situation was gcj from gcc-7.2.0

**Comment by arete** [comment]
For fix this, i have to remove on my pc the php-mcrypt ?

**Comment by cr6git** [comment]
@maxice8 maybe `replaces` should have been added to the template: 
````
php-sodium_package() {
	replaces="php-mcrypt>=0"
	...
}
````

**Comment by maxice8** [comment]
On Fri, Dec 08, 2017 at 08:46:19AM +0000, Gerardo Di Iorio wrote:
> For fix this, i have to remove on my pc the php-mcrypt ?
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/voidlinux/void-packages/issues/9820#issuecomment-350207462

Yes, it was removed on the 7.2.0 update and "replaced" with php-sodium.
