### ISSUE TITLE
android-studio-3.0.1_1 fails to install with cross-vpkg-dummy conflicts

### ISSUE THREAD

**Issue by Ethan-ks** [voidlinux/void-packages#9830]
### System

* xuname:  
Void 4.13.13_1 x86_64 GenuineIntel uptodate rrrm
* package:  
android-studio-3.0.1_1

### Expected behavior
Android studio install normally

### Actual behavior
install fails with 

    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg kernel-libc-headers-4.9.8_3 (matched by kernel-libc-headers>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg binutils-2.29.1_1 (matched by binutils>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgcc-7.2.0_4 (matched by libgcc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libstdc++-7.2.0_4 (matched by libstdc++>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libstdc++-devel-7.2.0_4 (matched by libstdc++-devel>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgfortran-7.2.0_4 (matched by libgfortran>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgomp-7.2.0_4 (matched by libgomp>=0) 
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg gcc-7.2.0_4 (matched by gcc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg glibc-2.26_3 (matched by glibc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg glibc-devel-2.26_3 (matched by glibc-devel>=0)
    Transaction aborted due to conflicting packages.

### Steps to reproduce the behavior
On my system, attempting to install with 
`# xbps-install android-studio` 
and 
`# xbps-install --repository=hostdir/binpkgs android-studio`
after building the package in my local clone of the void packages repo with xbps-src

I do not have another void machine to test this behaviour on.

the output of `xbps-install -d -n android-studio` is as follows:

    [DEBUG] XBPS: 0.51 API: 20151030 GIT: UNSET
    [DEBUG] Processing configuration directory: /etc/xbps.d
    [DEBUG] /etc/xbps.d: ignoring .empty
    [DEBUG] Processing system configuration directory: /usr/share/xbps.d
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/00-repository-main.conf
    [DEBUG] [repo] `https://repo.voidlinux.eu/current' stored successfully
    [DEBUG] /usr/share/xbps.d/00-repository-main.conf: added repository https://repo.voidlinux.eu/current
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/10-repository-multilib-nonfree.conf
    [DEBUG] [repo] `https://repo.voidlinux.eu/current/multilib/nonfree' stored successfully
    [DEBUG] /usr/share/xbps.d/10-repository-multilib-nonfree.conf: added repository https://repo.voidlinux.eu/current/multilib/nonfree
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/10-repository-multilib.conf
    [DEBUG] [repo] `https://repo.voidlinux.eu/current/multilib' stored successfully
    [DEBUG] /usr/share/xbps.d/10-repository-multilib.conf: added repository https://repo.voidlinux.eu/current/multilib
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/10-repository-nonfree.conf
    [DEBUG] [repo] `https://repo.voidlinux.eu/current/nonfree' stored successfully
    [DEBUG] /usr/share/xbps.d/10-repository-nonfree.conf: added repository https://repo.voidlinux.eu/current/nonfree
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/void-virtualpkgs.conf
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg awk for gawk
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg cron-daemon for dcron
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg editor for nvi
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg man for openbsd-man
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg ntp-daemon for openntpd
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg openssl for libressl-openssl
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg shell for dash
    [DEBUG] /usr/share/xbps.d/void-virtualpkgs.conf: added virtualpkg smtp-server for opensmtpd
    [DEBUG] Parsing configuration file: /usr/share/xbps.d/xbps.conf
    [DEBUG] rootdir=/
    [DEBUG] metadir=//var/db/xbps
    [DEBUG] cachedir=/var/cache/xbps
    [DEBUG] confdir=/etc/xbps.d
    [DEBUG] sysconfdir=/usr/share/xbps.d
    [DEBUG] syslog=true
    [DEBUG] bestmatching=false
    [DEBUG] Architecture: x86_64
    [DEBUG] Target Architecture: (null)
    [DEBUG] Repository[0]=https://repo.voidlinux.eu/current
    [DEBUG] Repository[1]=https://repo.voidlinux.eu/current/multilib/nonfree
    [DEBUG] Repository[2]=https://repo.voidlinux.eu/current/multilib
    [DEBUG] Repository[3]=https://repo.voidlinux.eu/current/nonfree
    [DEBUG] [pkgdb] added vpkg compton-20170430_1 for compton-git
    [DEBUG] [pkgdb] added vpkg libudev-220_1 for eudev-libudev
    [DEBUG] [pkgdb] added vpkg libudev-32bit-220_1 for eudev-libudev-32bit
    [DEBUG] [pkgdb] added vpkg libudev-devel-220_1 for eudev-libudev-devel
    [DEBUG] [pkgdb] added vpkg awk-0_1 for gawk
    [DEBUG] [pkgdb] added vpkg i3-4.14.1_1 for i3-gaps
    [DEBUG] [pkgdb] added vpkg jpeg-8_1 for libjpeg-turbo
    [DEBUG] [pkgdb] added vpkg jpeg-32bit-8_1 for libjpeg-turbo-32bit
    [DEBUG] [pkgdb] added vpkg jpeg-devel-8_1 for libjpeg-turbo-devel
    [DEBUG] [pkgdb] added vpkg jpeg-tools-8_1 for libjpeg-turbo-tools
    [DEBUG] [pkgdb] added vpkg openssl-2.5.5_1 for libressl
    [DEBUG] [pkgdb] added vpkg man-0_1 for man-db
    [DEBUG] [pkgdb] added vpkg mysql-10.1.28_1 for mariadb
    [DEBUG] [pkgdb] added vpkg mysql-client-10.1.28_1 for mariadb-client
    [DEBUG] [pkgdb] added vpkg man-0_1 for mdocml
    [DEBUG] [pkgdb] added vpkg nodejs-runtime-0_1 for nodejs
    [DEBUG] [pkgdb] added vpkg ntp-daemon-0_1 for ntp
    [DEBUG] [pkgdb] added vpkg libOpenCL-1.2_1 for ocl-icd
    [DEBUG] [pkgdb] added vpkg libOpenCL-32bit-1.2_1 for ocl-icd-32bit
    [DEBUG] [pkgdb] added vpkg perl-Archive-Tar-2.24_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Attribute-Handlers-0.99_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-AutoLoader-5.74_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-B-Debug-1.24_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-CPAN-2.18_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-CPAN-Meta-2.150010_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-CPAN-Meta-Requirements-2.140_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-CPAN-Meta-YAML-0.018_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Carp-1.42_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Compress-Raw-Bzip2-2.074_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Compress-Raw-Zlib-2.074_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Config-Perl-V-0.28_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-DB_File-1.840_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Data-Dumper-2.167_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Devel-PPPort-3.35_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Devel-SelfStubber-1.06_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Digest-1.17_01_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Digest-MD5-2.55_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Digest-SHA-5.96_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Dumpvalue-1.18_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Encode-2.88_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Env-1.04_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Exporter-5.72_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-CBuilder-0.280225_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-Constant-0.23_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-Install-2.04_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-MakeMaker-7.24_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-Manifest-1.70_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-ExtUtils-ParseXS-3.34_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-File-Fetch-0.52_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-File-Path-2.12_01_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-File-Temp-0.2304_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Filter-Simple-0.93_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Filter-Util-Call-1.55_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Getopt-Long-2.49_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-HTTP-Tiny-0.070_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-I18N-Collate-1.02_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-I18N-LangTags-0.42_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IO-1.38_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IO-Compress-2.074_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IO-Socket-IP-0.38_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IO-Zlib-1.10_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IPC-Cmd-0.96_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-IPC-SysV-2.07_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-JSON-PP-2.27400_02_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Locale-Codes-3.42_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Locale-Maketext-1.28_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Locale-Maketext-Simple-0.21_01_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-MIME-Base64-3.15_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Math-BigInt-1.999806_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Math-BigInt-FastCalc-0.5005_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Math-BigRat-0.2611_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Math-Complex-1.5901_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Memoize-1.03_01_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Module-CoreList-5.20170530_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Module-Load-0.32_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Module-Load-Conditional-0.68_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Module-Loaded-0.08_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Module-Metadata-1.000033_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-NEXT-0.67_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Net-Ping-2.55_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Params-Check-0.38_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-PathTools-3.67_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Perl-OSType-1.010_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-PerlIO-via-QuotedPrint-0.08_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Checker-1.73_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Escapes-1.07_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Parser-1.63_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Perldoc-3.28_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Simple-3.35_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Pod-Usage-1.69_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Safe-2.40_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Scalar-List-Utils-1.46_02_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Search-Dict-1.07_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-SelfLoader-1.23_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Socket-2.020_03_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Storable-2.62_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Sys-Syslog-0.35_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Term-ANSIColor-4.06_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Term-Cap-1.17_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Term-Complete-1.403_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Term-ReadLine-1.16_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Test-1.30_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Test-Harness-3.38_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Test-Simple-1.302073_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Text-Abbrev-1.02_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Text-Balanced-2.03_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Text-ParseWords-3.30_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Text-Tabs-2013.0523_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Thread-Queue-3.12_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Thread-Semaphore-2.13_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Tie-File-1.02_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Tie-RefHash-1.39_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Time-HiRes-1.9741_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Time-Local-1.25_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Time-Piece-1.31_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Unicode-Collate-1.19_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Unicode-Normalize-1.25_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Win32-0.52_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-Win32API-File-0.1203_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-XSLoader-0.27_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-autodie-2.29_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-autouse-1.11_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-base-2.25_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-bignum-0.47_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-constant-1.33_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-encoding-warnings-0.13_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-experimental-0.016_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-if-0.0606_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-lib-0.64_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-libnet-3.10_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-parent-0.236_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-perlfaq-5.021011_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-podlators-5.006_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-threads-2.15_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-threads-shared-1.56_1 for perl
    [DEBUG] [pkgdb] added vpkg perl-version-0.9917_1 for perl
    [DEBUG] [pkgdb] added vpkg python-distribute-36.7.2_1 for python-setuptools
    [DEBUG] [pkgdb] added vpkg python3-distribute-36.7.2_1 for python3-setuptools
    [DEBUG] [pkgdb] added vpkg texlive-2017_1 for texlive-bin
    [DEBUG] [pkgdb] added vpkg eject-2.31_1 for util-linux
    [DEBUG] [pkgdb] added vpkg rfkill-2.31_1 for util-linux
    [DEBUG] [pkgdb] added vpkg vim-8.0.1352_1 for vim-huge
    [DEBUG] [pkgdb] added vpkg xserver-abi-extension-10_1 for xorg-server
    [DEBUG] [pkgdb] added vpkg xserver-abi-input-24_1 for xorg-server
    [DEBUG] [pkgdb] added vpkg xserver-abi-video-23_1 for xorg-server
    [DEBUG] [pkgdb] added vpkg xf86-video-modesetting-1_1 for xorg-server
    [DEBUG] [pkgdb] initialized ok.
    [DEBUG] [rpool] `https://repo.voidlinux.eu/current' registered.
    [DEBUG] [rpool] `https://repo.voidlinux.eu/current/multilib/nonfree' registered.
    [DEBUG] [rpool] `https://repo.voidlinux.eu/current/multilib' registered.
    [DEBUG] [rpool] `https://repo.voidlinux.eu/current/nonfree' registered.
    [DEBUG] Added `android-studio-3.0.1_1' into the dependency list (https://repo.voidlinux.eu/current/nonfree)
    [DEBUG] Finding required dependencies for 'android-studio-3.0.1_1':
    [DEBUG] android-studio-3.0.1_1: requires dependency 'gtk+>=0': installed `gtk+-2.24.31_2'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libGL>=0': installed `libGL-17.2.6_1'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'musl>=0.9.9_1': not installed.
    [DEBUG] cross-vpkg-dummy-0.25_1: finding dependencies:
    [DEBUG]  cross-vpkg-dummy-0.25_1: requires dependency 'base-files>=0.126': installed `base-files-0.139_9'.
    [DEBUG] Added `cross-vpkg-dummy-0.25_1' into the dependency list (https://repo.voidlinux.eu/current)
    [DEBUG] android-studio-3.0.1_1: requires dependency 'glibc>=2.25_1':  (cross-vpkg-dummy-0.25_1 queued)
    [DEBUG] android-studio-3.0.1_1: requires dependency 'openjdk-jre>=8u20_1': not installed.
    [DEBUG] openjdk-jre-8u172b00_1: finding dependencies:
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'glibc>=2.25_1':  (cross-vpkg-dummy-0.25_1 queued)
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'zlib>=1.2.3_1': installed `zlib-1.2.11_2'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libX11>=1.2_1': installed `libX11-1.6.5_2'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'freetype>=2.3.9_1': installed `freetype-2.8.1_1'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libgcc>=4.4.0_1':  (cross-vpkg-dummy-0.25_1 queued)
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libXext>=1.0.5_1': installed `libXext-1.3.3_2'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libXrender>=0.9.4_1': installed `libXrender-0.9.10_1'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libXtst>=1.0.3_1': installed `libXtst-1.2.3_1'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'libXi>=1.2.1_1': installed `libXi-1.7.9_1'.
    [DEBUG]  openjdk-jre-8u172b00_1: requires dependency 'alsa-lib>=1.0.20_1': installed `alsa-lib-1.1.5_1'.
    [DEBUG] Added `openjdk-jre-8u172b00_1' into the dependency list (https://repo.voidlinux.eu/current)
    [DEBUG] android-studio-3.0.1_1: requires dependency 'freetype>=2.3.9_1': installed `freetype-2.8.1_1'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libgcc>=4.4.0_1':  (cross-vpkg-dummy-0.25_1 queued)
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libXext>=1.0.5_1': installed `libXext-1.3.3_2'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libX11>=1.2_1': installed `libX11-1.6.5_2'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libXrender>=0.9.4_1': installed `libXrender-0.9.10_1'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libXtst>=1.0.3_1': installed `libXtst-1.2.3_1'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'libXi>=1.2.1_1': installed `libXi-1.7.9_1'.
    [DEBUG] android-studio-3.0.1_1: requires dependency 'alsa-lib>=1.0.20_1': installed `alsa-lib-1.1.5_1'.
    [DEBUG] found conflicting installed pkg kernel-libc-headers-4.9.8_3 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by kernel-libc-headers>=0 [trans])
    [DEBUG] found conflicting installed pkg binutils-2.29.1_1 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by binutils>=0 [trans])
    [DEBUG] found conflicting installed pkg libgcc-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by libgcc>=0 [trans])
    [DEBUG] found conflicting installed pkg libstdc++-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by libstdc++>=0 [trans])
    [DEBUG] found conflicting installed pkg libstdc++-devel-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by libstdc++-devel>=0 [trans])
    [DEBUG] found conflicting installed pkg libgfortran-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by libgfortran>=0 [trans])
    [DEBUG] found conflicting installed pkg libgomp-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by libgomp>=0 [trans])
    [DEBUG] found conflicting installed pkg gcc-7.2.0_4 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by gcc>=0 [trans])
    [DEBUG] found conflicting installed pkg glibc-2.26_3 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by glibc>=0 [trans])
    [DEBUG] found conflicting installed pkg glibc-devel-2.26_3 with pkg in transaction cross-vpkg-dummy-0.25_1 (matched by glibc-devel>=0 [trans])
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg kernel-libc-headers-4.9.8_3 (matched by kernel-libc-headers>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg binutils-2.29.1_1 (matched by binutils>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgcc-7.2.0_4 (matched by libgcc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libstdc++-7.2.0_4 (matched by libstdc++>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libstdc++-devel-7.2.0_4 (matched by libstdc++-devel>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgfortran-7.2.0_4 (matched by libgfortran>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg libgomp-7.2.0_4 (matched by libgomp>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg gcc-7.2.0_4 (matched by gcc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg glibc-2.26_3 (matched by glibc>=0)
    CONFLICT: cross-vpkg-dummy-0.25_1 with installed pkg glibc-devel-2.26_3 (matched by glibc-devel>=0)
    Transaction aborted due to conflicting packages.
    [DEBUG] [pkgdb] released ok.

**Comment by pullmoll** [comment]
This line shows that somehow android-studio picked up wrong dependencies from `common/shlibs`:
```
[DEBUG] android-studio-3.0.1_1: requires dependency 'musl>=0.9.9_1': not installed.
```
Of course `musl` can't be installed on a `glibc` system. The question is why and how it happens.

**Comment by pullmoll** [comment]
It's due to a (expected) symlink for libc:
```
SONAME: libc.so <-> musl>=0.9.9_1
```
This is wrong for a glibc system. `glibc-2.26` contains a symlink `/usr/lib/libc.so` but the one for `musl-1.1.18` is the only one listed in `common/shlibs`. Not sure how to solve this. @chneukirchen @xtraeme ?

**Comment by skrzyp** [comment]
I've got into the same problem. Anyone actually cares about that?

**Comment by basiliscos** [comment]
me too met the problem.

**Comment by Follpvosten** [comment]
I have investigated a bit, and it might just be me, but it looks like glibc's template would need something like

`shlib_provides="libc.so"`

since `cross-vpkg-dummy` is set to provide the needed file this way in its template. Am i right on that?

**Comment by Follpvosten** [comment]
I know this isn't really a solution (and i would also prefer to use a native xbps package), but there is a Flatpak of android-studio on Flathub, if you absolutely need it:
`# xbps-install flatpak`
`# flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
`# flatpak install -y flathub com.google.AndroidStudio`
(Restart the session if you've just installed flatpak, so Flatpaks appear in menus)

**Comment by skrzyp** [comment]
It's not a solution, especially when someone wants to avoid that pseudo-modern crap like Flatpaks.

**Comment by Pretch** [comment]
As a temporary solution patch android-studio template and build a package.
This works for me.

```diff
diff --git a/srcpkgs/android-studio/template b/srcpkgs/android-studio/template
index a68f9f9540..461d9ce785 100644
--- a/srcpkgs/android-studio/template
+++ b/srcpkgs/android-studio/template
@@ -22,6 +22,9 @@ homepage="http://tools.android.com/"
 nopie=yes
 nostrip=yes

+noverifyrdeps=yes
+depends="openjdk-jre libgcc libXtst libXrender libXi libXext libX11 glibc freetype alsa-lib"
+
 do_install() {
        unzip android-studio-ide-${_studio_build}-linux.zip
        vmkdir opt/${pkgname}
```

**Comment by Pretch** [comment]
I belive that issue is caused by several `libperfa.so` files in android-studio ZIP archive.
When running `find android-studio/ -name '*.so' -exec file {} \;` among other lines I got:
```
android-studio/plugins/android/resources/perfa/armeabi-v7a/libperfa.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, stripped
android-studio/plugins/android/resources/perfa/x86/libperfa.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, stripped
android-studio/plugins/android/resources/perfa/arm64-v8a/libperfa.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, stripped
```
`ldd` claims that files are not linked dynamicly and `objump -p` reveals this:
```
find android-studio/ -name 'libperfa.so' -exec objdump -p {} \; | grep libc
  NEEDED               libc.so
  required from libc.so:
  NEEDED               libc.so
  required from libc.so:
  NEEDED               libc.so
  required from libc.so:
```
Probably because of thouse `libc.so` entries wrong dependency is added. See this hook:
https://github.com/voidlinux/void-packages/blob/master/common/hooks/pre-pkg/04-generate-runtime-deps.sh#L73

**Comment by shizonic** [comment]
@Pretch Thanks for pointing this out. Any suggestions to solve it?

**Comment by Pretch** [comment]
@shizonic You can clone this repository, patch `srcpkgs/android-studio/template` as provided above and run `./xbps-src pkg android-studio`
After that you can install builded package with `xbps-install -i --repository=./hostdir/binpkgs/ android-studio`
Please, let me know, if this won't help.

**Comment by shizonic** [comment]
@Pretch Thank you very much. I will give it a try asap. But why this still isn't upstreamed?
