### ISSUE TITLE
Package Request: pd

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#984]
Pure Data (Pd) is a visual programming language for creating interactive computer music and multimedia works.

tarball: http://sourceforge.net/projects/pure-data/files/pure-data/0.45.4/pd-0.45-4.src.tar.gz/download

website: http://puredata.info/

**Comment by xtraeme** [comment]
Added long ago by @thypon

**Comment by hjek** [comment]
The version of **pd** currently available in **voidlinux** is only compiled with **jack** and **oss** support (no **alsa** or **portaudio**). **oss** appears not to work, and if **jack** is selected, it segfaults. So the **pd** package is currently broken (apart from the gui).

**Comment by Vaelatern** [comment]
Please open a new issue to report these problems.

**Comment by hjek** [comment]
Opened an issue here: #4031
