### ISSUE TITLE
Package Request: gmusicbrowser

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#986]
gmusicbrowser : A customizable open-source jukebox for large music collections.

tarball: http://gmusicbrowser.org/download/gmusicbrowser-1.1.13.tar.gz

website: http://gmusicbrowser.org/

**Comment by dominikh** [comment]
Are you still interested in this package being added?

**Comment by dicktyr** [comment]
> Are you still interested in this package being added?

it's useful software
and I would certainly use a void package
but I have some problems to solve
before I can migrate to void

so: thank you, yes
but I won't be using it immediately

**Comment by dominikh** [comment]
Perl program, depends on some unpackaged perl modules, notably Glib-Object-Introspection and dbus. Should be packaged by someone who likes dealing with perl.

**Comment by dicktyr** [comment]
I'm surprised there's not more interest in gmusicbrowser

I use it because it handles large (> 700GB) libraries very well
and it has an excellent (and extensible) interface

it can also be invoked with an optional library-file-path
which is useful for managing entirely separate libraries

in any case
I'd very much appreciate the package(s) :}

**Comment by logenkain** [comment]
On Sat, Nov 14, 2015 at 06:27:12PM -0800, dicktyr wrote:
> I'm surprised there's not more interest in gmusicbrowser

Oh wow, I used to use this a while back.  I thought it was in void, guess not.  I'll take a look at it later today (assuming I don't forget).

**Comment by dicktyr** [comment]
@logenkain thanks, I'm curious: why did you stop using it?

**Comment by logenkain** [comment]
On Sun, Nov 15, 2015 at 12:04:47PM -0800, dicktyr wrote:
> @logenkain thanks, I'm curious: why did you stop using it?

I've gone down to just using VLC or Mplayer.  That's usually for onetime listens though.  
For music I have an Rpi2 setup with Ampache.  With that I use either the HTML5 player or download a playlist and use vlc/mplayer.

**Comment by sunaku** [comment]
There's also **[mpd](https://en.wikipedia.org/wiki/Music_Player_Daemon)** already available in void.  It ought to be able to handle your large +700GB library. :guitar: It has a host of terminal (e.g. ncmpc) and GUI (e.g. sonata) frontends that are also already available in void. :ticket:

**Comment by dicktyr** [comment]
> mpd

thanks
I should have mentioned I tried it
and if I were satisfied with a terminal interface
I may have kept with it

**Comment by sunaku** [comment]
On Sun, 15 Nov 2015 15:44:27 -0800, dicktyr wrote:
> if I were satisfied with a terminal interface
> I may have kept with it

mpd has graphical interfaces too,
see http://www.musicpd.org/clients/

**Comment by dicktyr** [comment]
I just noticed this has been packaged

thank you Juan :}
