### ISSUE TITLE
Package Request: gnumeric

### ISSUE THREAD

**Issue by dicktyr** [voidlinux/void-packages#987]
Gnumeric is an open-source spreadsheet program.

tarball: http://ftp.gnome.org/pub/GNOME/sources/gnumeric/1.12/gnumeric-1.12.20.tar.xz

website: http://gnumeric.org/

**Comment by xtraeme** [comment]
Already available.

**Comment by dicktyr** [comment]
sorry about that 
I searched but perhaps with a typo
as I see it there now
