### ISSUE TITLE
HPLIP GUI

### ISSUE THREAD

**Issue by ErinVoid** [voidlinux/void-packages#9895]
### System
Void 4.14.4_1 x86_64 AuthenticAMD uptodate rr
HPLIP 3.17.10

### Expected behavior
Expect GUI to run and icon in systray

### Actual behavior
hp-systray fails to run the GUI with messages
"warning: GUI mode disabled in build."
"error: hp-systray requires Qt4 GUI and DBus support. Exiting."

### Steps to reproduce the behavior
install and run hp-systray from terminal.

Would be ideal if the QT4 GUI could be disabled and the QT5 one built instead (configuration options (--disable-qt4 --enable-qt5)). It would require the PyQt and PyQt-dbus dependencies to be pulled in, they are not with current template.

Thanks

**Comment by cr6git** [comment]
Trying to build the new release `3.17.11`, it fails immediatly: 
````
=> hplip-3.17.11_1: running do_configure ...
/void-packages/srcpkgs/hplip/template: line 32: ppd/hpijs/*.ppd.gz.temp: No such file or directory
gzip: ppd/hpijs/*.ppd.gz: No such file or directory
=> ERROR: hplip-3.17.11_1: failed to run do_configure() at line 32.
````
It's here in the template: 
````
do_configure() {
	# https://bugs.archlinux.org/task/30085 - hack found in Gentoo
	# Use system foomatic-rip for hpijs driver instead of foomatic-rip-hplip
	# The hpcups driver does not use foomatic-rip
	local i
	for i in ppd/hpijs/*.ppd.gz ; do
		rm -f ${i}.temp
		gunzip -c ${i} | sed 's/foomatic-rip-hplip/foomatic-rip/g' | gzip > ${i}.temp
		mv ${i}.temp ${i}
	done
````
I have no idea how to fix this, however.

**Comment by cr6git** [comment]
The change you proposed works fine for `3.17.10`, at least.

**Comment by ErinVoid** [comment]
3.17.11 has appeared in userland. However, the gui still does not work and running hp-systray causes the same error messages. Checking with "hp-check -t" shows the /etc/hp/hplip.conf file has the following set (only relevant lines included):
# Following values are determined at configure time and cannot be changed.
[configure]
gui-build=no
internal-tag=3.17.11
ui-toolkit=no
qt3=no
qt4=no
qt5=no

So something strange is going on. End result is the same, no GUI or tray icon.

**Comment by pullmoll** [comment]
This is not too strange as GUI is disabled by default to avoid the huge dependency tree which many people don't need or want.

If you really need the GUI, you now need to compile your own hplip.
Just pull the repostitory and build it, then install your locally built hplit
```
$ git clone https://github.com/voidlinux/void-packages.git
$ cd void-packages
$ ./xbps-src binary-bootstrap
$ ./xbps-src -o gui pkg hplip
$ sudo xbps-install -S -R hostdir/binpkgs hplip
```
If you installed the official hplip before, you need to remove that first with `sudo xbps-remove hplip`.

**Comment by ErinVoid** [comment]
Thanks for the reply but the mod by CR6 was supposed to permit the GUI being built in 3.17.11. Other distributions have it as a separate package, specifically to avoid a large dependency pull. The dependencies appear to be dbus-session and PyQt4/5 [so Qt]. 

The original issue has not been solved. If maintainers wish to leave the GUI out, the template is wrong, even before the changes. An official statement stating that the GUI will not be build would be appreciated.

**Comment by pullmoll** [comment]
I don't have the time to split the package and I don't think we want the GUI default enabled.
I'll leave this issue open in case someone else wants to try to split the package into hplip and hplip-gui or similar.

**Comment by cr6git** [comment]
@ErinVoid you asked for `--disable-qt4 --enable-qt5` and I made the change. Now You can build the Qt5 GUI.

**Comment by newbluemoon** [comment]
@ErinVoid There’s a <i>hplip-gui</i> package now. Does it work for you and solve this issue?

**Comment by ErinVoid** [comment]
Solved so going to close issue. Thanks to all who've contributed.
