### ISSUE TITLE
libvirt getaddrinfo error

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#990]
libvirt yields this message on system startup:

warning : virGetHostname:671 : getaddrinfo failed for $HOSTNAME : System error

I solved this bug by adding this line to /etc/hosts: 

    127.0.1.1 $HOSTNAME.localdomain $HOSTNAME

maybe we have to add this to the installer system.

**Comment by xtraeme** [comment]
Our /etc/hosts is ok as is right now, as any other operating system out there it just defines "127.0.0.1 as localhost.localdomain".

This should be modified by the user directly, perhaps adding a message to libvirt.
