### ISSUE TITLE
spl requires bumping to version >=spl-0.7.4 (once it's released), or apply interim patch to work with linux4.14

### ISSUE THREAD

**Issue by datenwolf** [voidlinux/void-packages#9937]
### System

* package:  
  *affected package(s):* <=spl-0.7.3 (and by dependency also <=zfs-0.7.3)

### Expected behavior
No error on `modprobe spl`. Building spl does not fail!

### Actual behavior
Loading spl.ko fails due to deprecated kernel symbol exports. The issue is known to the zfsonlinux developers https://github.com/zfsonlinux/spl/commit/ed19bccfb651843fa208232b3a2d3d22a4152bc8

### Steps to reproduce the behavior
Update to >=linux4.14, rebuild spl, try to load.

### Actions required

* bump version of spl package as soon 0.7.4 is released

or

* include the suggested patch inside the package until the issue has been resolved upstream

**Comment by chneukirchen** [comment]
Patch is small enough, should be fine. Delegating to package maintainer.

**Comment by chneukirchen** [comment]
a663a4679b df611102bc
