### ISSUE TITLE
Package request: yakuake

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#996]
Yakuake is a Quake-style terminal emulator based on KDE Konsole technology.

I think if nobody is interested in including it i'd add it myself.

**Comment by logenkain** [comment]
> Yakuake is a Quake-style terminal emulator based on KDE Konsole technology.
I didn't even notice it wasn't here.  I just didn't want to pull in all
of KDE for Yakuake and ended up packaging tilda for my purposes.
