### ISSUE TITLE
linux-tools is outdated

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9965]
### System

* package:  `linux-tools-4.12_2`

### Expected behavior
Should be up to date: we are at `linux-4.14` now.
### Actual behavior
Is outdated.

**Comment by chneukirchen** [comment]
1caa35ab9b]

**Comment by cr6git** [comment]
@chneukirchen I just noticed a detail in the `linux-tools-meta` package in Arch: in the [changes log](https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/linux-tools) just after the update to 4.13-1, I can see: [Hyperv is missing in meta package](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/linux-tools&id=83f073b7fe83263af17dac49c7e1bf092f6d3e76). 
But I don't see any reference to "hyperv" in our template. 
Maybe we should add it, too ?

**Comment by chneukirchen** [comment]
I have no idea what that is, if anyone needs it, send a PR.

**Comment by cr6git** [comment]
> no idea what that is

Neither do I. 
Searching for "hyperv", I only find this: 
````
$ xbps-query -Rs hyperv
[-] xen-4.7.2_1            The Xen hypervisor utilities
[-] xen-devel-4.7.2_1      The Xen hypervisor utilities - development files
[-] xen-hypervisor-4.7.2_1 Xen Hypervisor
[-] xen-libs-4.7.2_1       The Xen hypervisor utilities - runtime libraries
````
