### ISSUE TITLE
baloo5 does not build

### ISSUE THREAD

**Issue by cr6git** [voidlinux/void-packages#9980]
### System

* xuname:  `Void 4.14.5_2 x86_64-musl GenuineIntel uptodate rrnFFFFFFFFFFFFFFFF`

* package:  `baloo5-5.40.0_1`

### Expected behavior
I should be able to build this package.
### Actual behavior
It fails!
I found this problem while I was trying to resolve [#7180](https://github.com/voidlinux/void-packages/issues/7180).
The build log is just **crazy**, you can see it [here](https://gist.github.com/cr6git/47420957c239eb4311f2cb98b4ca07fa)...

**Comment by newbluemoon** [comment]
Just built it for x86_64 and x86_64-musl without any problem. You could try to zap your masterdir and do a fresh bootstrap.

**Comment by cr6git** [comment]
I just did zap + new bootstrap but that changed nothing, still the same error: 
````
=> ERROR: baloo5-5.40.0_1: failed to install 'kio-devel-5.40.0_1' dependency! (error 1)
````
And the crazy output... 😞

**Comment by newbluemoon** [comment]
Did you see

```
kwidgetsaddons-5.40.0_1: verifying RSA signature...ERROR: kwidgetsaddons-devel-5.40.0_1: the RSA signature is not valid!
ERROR: kwidgetsaddons-devel-5.40.0_1: removed pkg archive and its signature.
```

Try to delete `kwidgetsaddons*` in `hostdir/repocache`.

**Comment by cr6git** [comment]
````
$ sudo rm hostdir/repocache/*
sudo: unable to execute /usr/bin/rm: Argument list too long
````
er... what? a new bug? 

````
$ rm hostdir/repocache/*
````
Without `sudo` that works, however! 

OK, now my repocache is empty and... Tada! 🎉 I can build `baloo5` ! 
Congratulations @newbluemoon
