### ISSUE TITLE
HTML 5 video (H.264) does not work with qutebrowser (webengine)

### ISSUE THREAD

**Issue by wesbarnett** [voidlinux/void-packages#9985]
### System

* xuname:  `Void 4.14.5_2 x86_64-musl GenuineIntel uptodate rFF`
* package:  `qutebrowser-1.0.4_1`

### Expected behavior

After installing gstreamer plugins, HTML 5 video should work.

### Actual behavior

Visiting https://html5test.com/ indicates H.264 is not working.

### Steps to reproduce the behavior

 1. Install `qutebrowser`, `gstreamer1`, `gst-plugins-{bad,good,ugly,base}1`, `gst-libav`. 
 2. Set `allow-plugins` to `true` in qutebrowser.
 3. Visit https://html5test.com/ to show H.264 video is not working.

```
xbps-query -s gst
[*] gst-libav-1.12.3_1         GStreamer libav plugin (1.x)
[*] gst-plugins-bad1-1.12.3_3  GStreamer plugins from the bad set (v1.x)
[*] gst-plugins-base1-1.12.3_1 GStreamer Base Plug-ins (v1.x)
[*] gst-plugins-good1-1.12.3_1 GStreamer set of well-maintained good plug-ins (1.x)
[*] gst-plugins-ugly1-1.12.3_1 GStreamer plugins from the ugly set (1.x)
[*] gstreamer1-1.12.3_1        Core GStreamer libraries and elements (1.x)
```

Note that this seems similiar to #4355 but instead of webkit, webengine is being used as the backend.

**Comment by wesbarnett** [comment]
@The-Compiler maybe you can give some input to what I am missing or what the issue might be.

**Comment by The-Compiler** [comment]
Sounds like Void compiles QtWebEngine without support for proprietary codecs.

**Comment by wesbarnett** [comment]
Hey @uggedal, can you take a look to see if the build is missing support for propriety codecs? Thanks.

**Comment by wesbarnett** [comment]
[https://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs This] is the flag that is missing in the qt5-webengine package.

**Comment by rr-** [comment]
Same issue seems to happen on arch linux

**Comment by rr-** [comment]
Found this issue: https://bugs.archlinux.org/task/45652

**Comment by The-Compiler** [comment]
@rr- That's been fixed since years.

**Comment by rr-** [comment]
Welp, at any rate, I have installed everything related to `gst` on my Arch Linux and html5test.com shows I can't play h264/h265 video and mp3/aac audio. (using webengine backend)

**Comment by pullmoll** [comment]
I can't find anything H.264 related (in Chromium it's called proprietary-codecs) in the current qt5-webkit-5.8.0. Also the next version does not seem to have a specific switch or option to enable that.

It seems I can soon update to 5.9.0 and there I can chage the default 'ENABLE_VIDEO=0` and `ENABLE_WEBAUDIO=0` to `=1`. If that actually enables H.264 throgh the gstreamer plugins I don't know.

Currently building locally for all possible target architectures to see if I can update master.

**Comment by pullmoll** [comment]
FWIW `x264-devel` is used by `gst-plugins-ugly1` so this is the plugin you need to install.

**Comment by The-Compiler** [comment]
QtWebEngine on Archlinux (with `-proprietary-codecs` enabled) should come with all those codecs built-in, so at least h264-support should work without any other packages.

@rr- My guess would be that you're either using QtWebKit, or have a PyQt5 installed via pip/tox which comes with its own Qt packages. When you do `:version`, you should see something like `Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt`.

If you're still having trouble, I suggest you drop by in the [qutebrowser IRC channel](https://github.com/qutebrowser/qutebrowser#getting-help), mailinglist, or subreddit - this isn't really the right place for qutebrowser support :wink:

**Comment by pullmoll** [comment]
@The-Compiler exactly :) And if I see it right, qutebrowser uses our qt5-webengine package through python-PyQt5-webengine, so all this has nothing to do with the qt5-webkit package. It was my fault to think it was qt5-webkit, which is still used by some packages, causing the problem.

**Comment by rr-** [comment]
>…or have a PyQt5 installed via pip/tox which comes with its own Qt packages. When you do :version, you should see something like Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt.

That was the case. Thanks!
